# Generated by Django 5.2.15 on 2026-07-15 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0024_consequenceeffect_asset_status_target"),
        ("dreams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DreamPerilConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resist_difficulty",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Target difficulty for the Dream Peril resist check.",
                    ),
                ),
                (
                    "resist_check_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Check type rolled for Dream Peril resistance.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dream_peril_configs",
                        to="checks.checktype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dream Peril Config",
                "verbose_name_plural": "Dream Peril Configs",
            },
        ),
    ]
