# Generated by Django 5.2.14 on 2026-06-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("areas", "0002_create_areaclosure_view"),
        ("buildings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="allowed_building_kinds",
            field=models.ManyToManyField(
                blank=True, related_name="allowed_in_wards", to="buildings.buildingkind"
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="permit_cost_multiplier",
            field=models.DecimalField(decimal_places=3, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name="area",
            name="permit_eligibility",
            field=models.CharField(
                choices=[
                    ("open", "Open — anyone with a permit"),
                    (
                        "reputation_gated",
                        "Reputation gated — minimum standing required",
                    ),
                    (
                        "npc_controlled",
                        "NPC controlled — only via specific NPC's authority",
                    ),
                    ("closed", "Closed — no permits issued"),
                ],
                default="open",
                max_length=32,
            ),
        ),
    ]
