# Generated by Django 5.2.14 on 2026-06-14 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("areas", "0003_area_allowed_building_kinds_and_more"),
        ("mechanics", "0002_initial"),
        ("objects", "0014_defaultobject_defaultcharacter_defaultexit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("feature", "Feature"),
                            ("aerial", "Aerial"),
                            ("elevated", "Elevated"),
                            ("barrier_side", "Barrier Side"),
                        ],
                        default="feature",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "ordering": ["room", "name"],
            },
        ),
        migrations.CreateModel(
            name="ObjectPosition",
            fields=[
                (
                    "objectdb",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="object_position",
                        serialize=False,
                        to="objects.objectdb",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occupants",
                        to="areas.position",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PositionEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_passable", models.BooleanField(default=True)),
                (
                    "gating_challenge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gated_position_edges",
                        to="mechanics.challengeinstance",
                    ),
                ),
                (
                    "position_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edges_as_a",
                        to="areas.position",
                    ),
                ),
                (
                    "position_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edges_as_b",
                        to="areas.position",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="position",
            constraint=models.UniqueConstraint(
                fields=("room", "name"), name="unique_position_per_room"
            ),
        ),
        migrations.AddConstraint(
            model_name="positionedge",
            constraint=models.UniqueConstraint(
                fields=("position_a", "position_b"), name="unique_position_edge"
            ),
        ),
        migrations.AddConstraint(
            model_name="positionedge",
            constraint=models.CheckConstraint(
                condition=models.Q(("position_a__lt", models.F("position_b"))),
                name="position_edge_canonical_order",
            ),
        ),
    ]
