# Generated by Django 5.2.14 on 2026-06-14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("areas", "0004_position_objectposition_positionedge_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="positionedge",
            options={"ordering": ["position_a", "position_b"]},
        ),
    ]
