# Generated by Django 5.2.14 on 2026-06-27 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("areas", "0010_area_color"),
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="climate",
            field=models.ForeignKey(
                blank=True,
                help_text="Regional climate baseline (#1522). Resolves most-specific-wins down the hierarchy (see weather.services.get_effective_climate), like realm.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="areas",
                to="weather.climate",
            ),
        ),
    ]
