# Generated by Django 5.2.14 on 2026-07-10 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("areas", "0014_position_shelter_applies_to_attacks"),
        ("character_sheets", "0010_remove_charactersheet_family_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="positionedge",
            name="created_by_sheet",
            field=models.ForeignKey(
                blank=True,
                help_text="Provenance: the caster who conjured this obstacle. Null for staff-authored edges.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conjured_obstacles",
                to="character_sheets.charactersheet",
            ),
        ),
        migrations.AddField(
            model_name="positionedge",
            name="duration_rounds",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="For conjured obstacles: rounds until expiry. Null = permanent (staff-authored).",
                null=True,
            ),
        ),
    ]
