# Generated by Django 5.2.14 on 2026-07-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("areas", "0016_blueprintposition_layout_x_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="grid_x",
            field=models.IntegerField(
                blank=True,
                help_text="Position within the PARENT area's local grid (rendering/hint data only — never routing); units are parent-local cells, meaningful only among siblings.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="grid_y",
            field=models.IntegerField(
                blank=True,
                help_text="Position within the PARENT area's local grid (rendering/hint data only — never routing); units are parent-local cells, meaningful only among siblings.",
                null=True,
            ),
        ),
    ]
