# Generated by Django 5.2.15 on 2026-07-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worship", "0004_miracledamageprofile_execute_missing_health_multiplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="miraclecapabilitygrant",
            name="intensity_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Sensitivity of this grant to the caster's power (#2708). 0 (default) is a flat, rock-steady grant; higher values curve the value harder as power rises. Inert (no curve at all) until a CapabilityPowerConfig row exists.",
                max_digits=5,
            ),
        ),
    ]
