# Generated by Django 5.2.4 on 2026-02-22 00:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mechanics", "0001_initial"),
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.PositiveIntegerField(default=0)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Freeform notes describing specific goals within this domain.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        help_text="Current status of this goal.",
                        max_length=20,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this goal was completed (if applicable).",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        help_text="Goal domain (ModifierType with category='goal')",
                        limit_choices_to={"category__name": "goal"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="character_goals",
                        to="mechanics.modifiertype",
                    ),
                ),
            ],
            options={
                "unique_together": {("character", "domain")},
            },
        ),
        migrations.CreateModel(
            name="GoalInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "roll_story",
                    models.TextField(
                        help_text="Player's narrative of how this goal applied to the roll"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="goals.charactergoal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoalJournal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Public journals can be read by other players.",
                    ),
                ),
                (
                    "xp_awarded",
                    models.PositiveIntegerField(
                        default=0, help_text="XP awarded for this journal entry."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal_journals",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: specific goal domain this entry relates to.",
                        limit_choices_to={"category__name": "goal"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goal_journals",
                        to="mechanics.modifiertype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoalRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_revised_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal_revision",
                        to="objects.objectdb",
                    ),
                ),
            ],
        ),
    ]
