# Generated by Django 5.2.14 on 2026-07-06 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gm", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GMLevelCap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("starting", "Starting GM"),
                            ("junior", "Junior GM"),
                            ("gm", "GM"),
                            ("experienced", "Experienced GM"),
                            ("senior", "Senior GM"),
                        ],
                        db_index=True,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "max_beat_risk",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("extreme", "Extreme"),
                        ],
                        default="none",
                        help_text="Highest beat risk tier a GM at this level may author.",
                        max_length=20,
                    ),
                ),
                (
                    "allow_custom_stakes",
                    models.BooleanField(
                        default=False,
                        help_text="Whether a GM at this level may author custom (template=null) stakes.",
                    ),
                ),
                (
                    "allow_global_scope_authoring",
                    models.BooleanField(
                        default=False,
                        help_text="Whether a GM at this level may author global-scope content.",
                    ),
                ),
            ],
            options={
                "verbose_name": "GM Level Cap",
                "verbose_name_plural": "GM Level Caps",
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="GMLevelChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_level",
                    models.CharField(
                        choices=[
                            ("starting", "Starting GM"),
                            ("junior", "Junior GM"),
                            ("gm", "GM"),
                            ("experienced", "Experienced GM"),
                            ("senior", "Senior GM"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_level",
                    models.CharField(
                        choices=[
                            ("starting", "Starting GM"),
                            ("junior", "Junior GM"),
                            ("gm", "GM"),
                            ("experienced", "Experienced GM"),
                            ("senior", "Senior GM"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Why the level changed — shown in the audit trail."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        help_text="Staff account that made this change.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="level_changes",
                        to="gm.gmprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "GM Level Change",
                "verbose_name_plural": "GM Level Changes",
                "ordering": ["-created_at", "-pk"],
            },
        ),
    ]
