# Generated by Django 5.2.14 on 2026-07-12 06:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("conditions", "0017_add_position_targeting_fields"),
        ("evennia_extensions", "0009_exitprofile"),
        ("magic", "0101_portalanchorkind_technique_travel_anchor_kind_and_more"),
        ("room_features", "0011_alter_roomfeaturekind_service_strategy"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExitBarsDetails",
            fields=[
                (
                    "exit_profile",
                    models.OneToOneField(
                        help_text="The exit these bars are installed on.",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="bars_details",
                        serialize=False,
                        to="evennia_extensions.exitprofile",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Durability tier. Capped at EXIT_BARS_MAX_LEVEL.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "installed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_upgraded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dissolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the bars are broken to destruction; null = active.",
                        null=True,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("level__gte", 1)),
                        name="exit_bars_details_level_gte_1",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RoomAlarmDetails",
            fields=[
                (
                    "room_profile",
                    models.OneToOneField(
                        help_text="The room this alarm watches.",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="alarm_details",
                        serialize=False,
                        to="evennia_extensions.roomprofile",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Alarm tier. Capped at ROOM_ALARM_MAX_LEVEL.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "installed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_upgraded_at", models.DateTimeField(blank=True, null=True)),
                ("dissolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("level__gte", 1)),
                        name="room_alarm_details_level_gte_1",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RoomWardDetails",
            fields=[
                (
                    "room_profile",
                    models.OneToOneField(
                        help_text="The room this ward protects.",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="ward_details",
                        serialize=False,
                        to="evennia_extensions.roomprofile",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Ward tier. Capped at ROOM_WARD_MAX_LEVEL.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "resonance_reserve",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Banked resonance the daily upkeep tick drains from.",
                    ),
                ),
                (
                    "reaction_damage_amount",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Damage dealt to an unauthorized entrant, if nonzero.",
                    ),
                ),
                (
                    "installed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_upgraded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lapsed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when resonance_reserve hits 0; ward stops reacting. Null = active.",
                        null=True,
                    ),
                ),
                ("dissolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reaction_condition",
                    models.ForeignKey(
                        blank=True,
                        help_text="Condition applied to an unauthorized entrant, if set.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ward_reactions",
                        to="conditions.conditiontemplate",
                    ),
                ),
                (
                    "resonance",
                    models.ForeignKey(
                        help_text="The resonance flavor powering this ward's upkeep.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wards",
                        to="magic.resonance",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("level__gte", 1)),
                        name="room_ward_details_level_gte_1",
                    )
                ],
            },
        ),
    ]
