# Generated by Django 5.2.14 on 2026-07-12 07:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

import core.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("room_features", "0012_alter_roomfeaturekind_service_strategy"),
        ("scenes", "0050_sceneactionrequest_originated_as_entrance"),
        ("societies", "0027_propagandacampaigntier_propagandadetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="VaultDetails",
            fields=[
                (
                    "feature_instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="vault_details",
                        serialize=False,
                        to="room_features.roomfeatureinstance",
                    ),
                ),
                (
                    "max_items",
                    models.PositiveSmallIntegerField(
                        default=20,
                        help_text="Maximum loose items the vault room can hold. Scaled by level at install: max_items = level * VAULT_MAX_ITEMS_PER_LEVEL.",
                    ),
                ),
                (
                    "founder_persona",
                    models.ForeignKey(
                        help_text="The persona who installed the vault. Has implicit owner access — always on the access list regardless of VaultAccessEntry rows. The founder's RosterTenure is the consent source for steal_permitted when an unowned vault item is stolen.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="founded_vaults",
                        to="scenes.persona",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VaultAccessEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "holder_type",
                    models.CharField(
                        choices=[
                            ("persona", "Persona"),
                            ("organization", "Organization"),
                        ],
                        max_length=20,
                    ),
                ),
                ("added_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vault_access_granted",
                        to="scenes.persona",
                    ),
                ),
                (
                    "holder_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vault_access_entries",
                        to="societies.organization",
                    ),
                ),
                (
                    "holder_persona",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vault_access_entries",
                        to="scenes.persona",
                    ),
                ),
                (
                    "vault_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_entries",
                        to="room_features.vaultdetails",
                    ),
                ),
            ],
            options={
                "ordering": ["vault_details", "added_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("holder_type", "PERSONA")),
                        fields=("vault_details", "holder_persona"),
                        name="vault_access_persona_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("holder_type", "ORGANIZATION")),
                        fields=("vault_details", "holder_organization"),
                        name="vault_access_org_unique",
                    ),
                ],
            },
            bases=(core.mixins.DiscriminatorMixin, models.Model),
        ),
    ]
