# Generated by Django 5.2.14 on 2026-06-26 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("buildings", "0011_alter_styleaffinity_stat_key"),
        ("evennia_extensions", "0005_roomprofile_enclosure"),
    ]

    operations = [
        migrations.CreateModel(
            name="DecorationKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Admin-editable flavour describing the decoration. PLACEHOLDER.",
                    ),
                ),
                (
                    "amenity",
                    models.IntegerField(
                        default=0,
                        help_text="Positive comfort points (the AMENITY pool) added by presence. Small for utility pieces (a hearth is mostly mitigation); large for luxury/magical comfort.",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RoomDecoration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kind",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placements",
                        to="buildings.decorationkind",
                    ),
                ),
                (
                    "room_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decorations",
                        to="evennia_extensions.roomprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["room_profile", "placed_at"],
            },
        ),
        migrations.CreateModel(
            name="DecorationAffinity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stat_key",
                    models.CharField(
                        choices=[
                            ("crime", "Crime"),
                            ("order", "Order"),
                            ("cleanliness", "Cleanliness"),
                            ("lighting", "Lighting"),
                            ("noise", "Noise"),
                            ("traffic", "Traffic"),
                            ("cold", "Cold exposure"),
                            ("heat", "Heat exposure"),
                            ("wet", "Wet exposure"),
                            ("wind", "Wind exposure"),
                            ("amenity", "Amenity (positive comfort)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        help_text="Usually negative: mitigates that discomfort axis. + would add exposure."
                    ),
                ),
                (
                    "kind",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affinities",
                        to="buildings.decorationkind",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "stat_key"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "stat_key"),
                        name="unique_decoration_affinity_per_axis",
                    )
                ],
            },
        ),
    ]
