# Generated by Django 5.2.14 on 2026-07-06 20:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("buildings", "0021_buildingupgradedetails"),
        ("evennia_extensions", "0008_remove_roomprofile_tenant_persona"),
    ]

    operations = [
        migrations.CreateModel(
            name="MothballedRoomState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "was_public",
                    models.BooleanField(
                        help_text="RoomProfile.is_public value at mothball time, restored on return."
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.AlterModelOptions(
            name="buildingprojectinstance",
            options={"ordering": ["pk"]},
        ),
        migrations.RemoveIndex(
            model_name="buildingprojectinstance",
            name="buildings_b_buildin_7db8d3_idx",
        ),
        migrations.RemoveField(
            model_name="building",
            name="dormant_since",
        ),
        migrations.RemoveField(
            model_name="building",
            name="is_accessible",
        ),
        migrations.RemoveField(
            model_name="buildingprojectinstance",
            name="consecutive_missed_upkeep",
        ),
        migrations.RemoveField(
            model_name="buildingprojectinstance",
            name="decay_priority",
        ),
        migrations.RemoveField(
            model_name="buildingprojectinstance",
            name="decayed_at",
        ),
        migrations.RemoveField(
            model_name="projecttemplate",
            name="decay_priority",
        ),
        migrations.AddField(
            model_name="building",
            name="condition_since",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When condition_tier last changed. Drives the above-normal dwell decay (ABOVE_NORMAL_DWELL_DAYS).",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="condition_tier",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Decayed"),
                    (1, "Ramshackle"),
                    (2, "Worn"),
                    (3, "Fine"),
                    (4, "Good"),
                    (5, "Excellent"),
                    (6, "Extravagantly Polished"),
                    (7, "Immaculate"),
                ],
                default=5,
                help_text="Condition ladder position (#1930). EXCELLENT is the normal state held by ordinary paid upkeep; above-normal tiers come from preparation and decay on a dwell timer; below-normal tiers come from sustained missed upkeep, floored at DECAYED.",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="consecutive_missed_upkeep",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Consecutive missed weekly upkeep cycles for this building (building-scoped; upkeep is charged per building). Past GRACE_MISSES the condition tier slides every SLIP_WEEKS_PER_TIER further misses.",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="consecutive_paid_upkeep",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Consecutive paid weekly cycles — every REGAIN_WEEKS_PER_TIER paid weeks climbs one tier back toward EXCELLENT.",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="mothballed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when long owner inactivity hides this building from the grid and freezes all upkeep/condition accrual (#1930). Cleared when the owner returns.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="ultra_upkeep",
            field=models.BooleanField(
                default=False,
                help_text="Owner opt-in premium (ULTRA_UPKEEP_MULTIPLIER × weekly cost, on top of normal upkeep) that holds IMMACULATE past its dwell.",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="upkeep_arrears",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="Owed upkeep in coppers, accrued on missed weeks and capped at ARREARS_CAP_WEEKS × weekly cost. Owner-only surface; settled via settle_upkeep_arrears.",
            ),
        ),
        migrations.AddField(
            model_name="mothballedroomstate",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mothballed_room_states",
                to="buildings.building",
            ),
        ),
        migrations.AddField(
            model_name="mothballedroomstate",
            name="room_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="evennia_extensions.roomprofile",
            ),
        ),
        migrations.AddConstraint(
            model_name="mothballedroomstate",
            constraint=models.UniqueConstraint(
                fields=("building", "room_profile"),
                name="buildings_mothballed_room_state_unique",
            ),
        ),
    ]
