# Generated by Django 5.2.4 on 2026-03-04 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("conditions", "0002_initial"),
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
        ("obstacles", "0002_bypasscheckrequirement_bypasscapabilityrequirement"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObstacleTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "description_template",
                    models.TextField(
                        blank=True,
                        help_text="Narrative text with {variables} for context customization.",
                    ),
                ),
                (
                    "severity",
                    models.PositiveIntegerField(
                        default=1, help_text="Difficulty multiplier for bypass checks."
                    ),
                ),
                (
                    "blocked_capability",
                    models.ForeignKey(
                        help_text="Which capability this obstacle blocks.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conditions.capabilitytype",
                    ),
                ),
                (
                    "properties",
                    models.ManyToManyField(
                        blank=True,
                        related_name="obstacle_templates",
                        to="obstacles.obstacleproperty",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ObstacleInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_variables",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Variables for description_template rendering.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="obstacle_instances",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="obstacles.obstacletemplate",
                    ),
                ),
            ],
        ),
    ]
