# Generated by Django 5.2.4 on 2026-04-02 23:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fatigue", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fatiguepool",
            old_name="character",
            new_name="character_sheet",
        ),
    ]
