# Generated by Django 5.2.4 on 2026-03-05 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("conditions", "0001_initial"),
        ("magic", "0001_initial"),
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conditioninstance",
            name="source_technique",
            field=models.ForeignKey(
                blank=True,
                help_text="Technique used to apply this condition",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conditions_caused",
                to="magic.technique",
            ),
        ),
        migrations.AddField(
            model_name="conditioninstance",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="condition_instances",
                to="objects.objectdb",
            ),
        ),
        migrations.AddField(
            model_name="conditionstage",
            name="resist_check_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Check type to resist progression",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="conditions.checktype",
            ),
        ),
        migrations.AddField(
            model_name="conditionresistancemodifier",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                help_text="Set for stage-specific effects",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="conditions.conditionstage",
            ),
        ),
        migrations.AddField(
            model_name="conditioninstance",
            name="current_stage",
            field=models.ForeignKey(
                blank=True,
                help_text="Current stage for progressive conditions",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="conditions.conditionstage",
            ),
        ),
        migrations.AddField(
            model_name="conditiondamageovertime",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                help_text="Set for stage-specific effects",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="conditions.conditionstage",
            ),
        ),
        migrations.AddField(
            model_name="conditioncheckmodifier",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                help_text="Set for stage-specific effects",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="conditions.conditionstage",
            ),
        ),
        migrations.AddField(
            model_name="conditioncapabilityeffect",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                help_text="Set for stage-specific effects",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="conditions.conditionstage",
            ),
        ),
        migrations.AddField(
            model_name="conditiontemplate",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conditions",
                to="conditions.conditioncategory",
            ),
        ),
        migrations.AddField(
            model_name="conditiontemplate",
            name="cure_check_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Check type used to cure this condition, if any",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cures_conditions",
                to="conditions.checktype",
            ),
        ),
        migrations.AddField(
            model_name="conditionstage",
            name="condition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stages",
                to="conditions.conditiontemplate",
            ),
        ),
        migrations.AddField(
            model_name="conditionresistancemodifier",
            name="condition",
            field=models.ForeignKey(
                blank=True,
                help_text="Set for condition-level effects (all stages)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="conditions.conditiontemplate",
            ),
        ),
        migrations.AddField(
            model_name="conditioninstance",
            name="condition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="conditions.conditiontemplate",
            ),
        ),
        migrations.AddField(
            model_name="conditiondamageovertime",
            name="condition",
            field=models.ForeignKey(
                blank=True,
                help_text="Set for condition-level effects (all stages)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="conditions.conditiontemplate",
            ),
        ),
        migrations.AddField(
            model_name="conditiondamageinteraction",
            name="applies_condition",
            field=models.ForeignKey(
                blank=True,
                help_text="Condition to apply as a result of this interaction",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applied_by_damage_interaction",
                to="conditions.conditiontemplate",
            ),
        ),
        migrations.AddField(
            model_name="conditiondamageinteraction",
            name="condition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="damage_interactions",
                to="conditions.conditiontemplate",
            ),
        ),
        migrations.AddField(
            model_name="conditionconditioninteraction",
            name="condition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions_as_primary",
                to="conditions.conditiontemplate",
            ),
        ),
        migrations.AddField(
            model_name="conditionconditioninteraction",
            name="other_condition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions_as_secondary",
                to="conditions.conditiontemplate",
            ),
        ),
        migrations.AddField(
            model_name="conditionconditioninteraction",
            name="result_condition",
            field=models.ForeignKey(
                blank=True,
                help_text="Resulting condition for transform/merge outcomes",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_by_interaction",
                to="conditions.conditiontemplate",
            ),
        ),
        migrations.AddField(
            model_name="conditioncheckmodifier",
            name="condition",
            field=models.ForeignKey(
                blank=True,
                help_text="Set for condition-level effects (all stages)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="conditions.conditiontemplate",
            ),
        ),
        migrations.AddField(
            model_name="conditioncapabilityeffect",
            name="condition",
            field=models.ForeignKey(
                blank=True,
                help_text="Set for condition-level effects (all stages)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="conditions.conditiontemplate",
            ),
        ),
    ]
