# Generated by Django 5.2.4 on 2026-01-27 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("conditions", "0001_initial"),
        ("mechanics", "0001_initial"),
    ]

    operations = [
        # Clear existing resonance references before schema change.
        # Resonances are now managed via ModifierType entries.
        migrations.RunSQL(
            sql="UPDATE conditions_damagetype SET resonance_id = NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="damagetype",
            name="resonance",
            field=models.OneToOneField(
                blank=True,
                help_text="Associated magical resonance (category='resonance'), if any",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="damage_type",
                to="mechanics.modifiertype",
            ),
        ),
    ]
