# Generated by Django 5.2.14 on 2026-07-03 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("checks", "0001_initial"),
        ("conditions", "0001_initial"),
        ("mechanics", "0001_initial"),
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="capabilitytype",
            name="prerequisite",
            field=models.ForeignKey(
                blank=True,
                help_text="Capability-level prerequisite checked for ALL sources of this Capability.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="capability_types",
                to="mechanics.prerequisite",
            ),
        ),
        migrations.AddField(
            model_name="conditioncapabilityeffect",
            name="capability",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="conditions.capabilitytype",
            ),
        ),
        migrations.AddField(
            model_name="conditioncheckmodifier",
            name="check_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="checks.checktype"
            ),
        ),
        migrations.AddField(
            model_name="conditioninstance",
            name="source_character",
            field=models.ForeignKey(
                blank=True,
                help_text="Character who applied this condition",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conditions_caused",
                to="objects.objectdb",
            ),
        ),
    ]
