# Generated by Django 5.2.4 on 2026-03-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conditions", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conditioncapabilityeffect",
            name="effect_type",
        ),
        migrations.RemoveField(
            model_name="conditioncapabilityeffect",
            name="modifier_percent",
        ),
        migrations.AddField(
            model_name="conditioncapabilityeffect",
            name="value",
            field=models.IntegerField(
                default=0,
                help_text="Additive modifier. Negative reduces, positive enhances. A large negative effectively blocks the capability.",
            ),
        ),
    ]
