# Generated by Django 5.2.14 on 2026-05-29 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0004_initial"),
        ("conditions", "0004_capabilitytype_innate_baseline"),
    ]

    operations = [
        migrations.AddField(
            model_name="damagetype",
            name="death_pool",
            field=models.ForeignKey(
                blank=True,
                help_text="Tiered death consequences for this damage type. Null → config default.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="death_pool_damage_types",
                to="actions.consequencepool",
            ),
        ),
        migrations.AddField(
            model_name="damagetype",
            name="wound_pool",
            field=models.ForeignKey(
                blank=True,
                help_text="Permanent-wound pool for this damage type. Null = use config default.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wound_pool_damage_types",
                to="actions.consequencepool",
            ),
        ),
    ]
