# Generated by Django 5.2.4 on 2026-05-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "conditions",
            "0007_remove_treatmentattempt_unique_treatment_attempt_per_helper_scene_and_more",
        ),
        ("flows", "0011_alter_triggerdefinition_event_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="conditiontemplate",
            name="reactive_triggers",
            field=models.ManyToManyField(
                blank=True,
                help_text="TriggerDefinitions installed as Trigger rows on the bearer when an instance of this template is applied. Cleanup is automatic via Trigger.source_condition CASCADE on ConditionInstance deletion.",
                related_name="installing_templates",
                to="flows.triggerdefinition",
            ),
        ),
    ]
