# Generated by Django 5.2.15 on 2026-07-22 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("conditions", "0022_treatmentattempt_health_mended_and_more"),
        ("covenants", "0041_alter_vowsituationalperkrung_count_threshold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conditioninstance",
            name="source_vow",
            field=models.ForeignKey(
                blank=True,
                help_text="The applier's engaged-vow anchor at apply time (#2643) — the first of ``character.covenant_roles.currently_engaged_roles()``, resolved to its anchor (``parent_role`` or itself, never a resolved sub-role). Null when the applier had no engaged role. Drives vow-keyed diminishing returns on the bounded team-damage-percent lane's read (``world.magic.services.techniques._team_lane_delta``): contributions sharing one vow diminish; distinct vows stack fully.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="covenants.covenantrole",
            ),
        ),
    ]
