# Generated by Django 5.2.15 on 2026-07-24 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("character_sheets", "0013_charactersheet_durance_cohort_and_more"),
        ("conditions", "0023_conditioninstance_source_vow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatmentattempt",
            name="helper",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="treatment_attempts_as_helper",
                to="character_sheets.charactersheet",
            ),
        ),
        migrations.AlterField(
            model_name="treatmentattempt",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="treatment_attempts_as_target",
                to="character_sheets.charactersheet",
            ),
        ),
    ]
