# Generated by Django 5.2.15 on 2026-07-25 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0026_alter_consequenceoutcomemodifier_source_kind"),
        ("conditions", "0025_alter_capabilitytype_innate_baseline_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="conditioncheckmodifier",
            name="check_modifier_unique_condition",
        ),
        migrations.RemoveConstraint(
            model_name="conditioncheckmodifier",
            name="check_modifier_unique_stage",
        ),
        migrations.AddField(
            model_name="conditioncheckmodifier",
            name="check_category",
            field=models.ForeignKey(
                blank=True,
                help_text="When set (and check_type is null), this modifier applies to ANY check in this category — including per-character checks like the signature magic check. Mutually exclusive with check_type.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="condition_check_modifiers",
                to="checks.checkcategory",
            ),
        ),
        migrations.AlterField(
            model_name="conditioncheckmodifier",
            name="check_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific check type. Mutually exclusive with check_category.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="checks.checktype",
            ),
        ),
        migrations.AddConstraint(
            model_name="conditioncheckmodifier",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("check_category__isnull", True), ("check_type__isnull", False)),
                    models.Q(("check_category__isnull", False), ("check_type__isnull", True)),
                    _connector="OR",
                ),
                name="check_modifier_exactly_one_check_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="conditioncheckmodifier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("check_type__isnull", False), ("condition__isnull", False)),
                fields=("condition", "check_type"),
                name="check_modifier_unique_condition",
            ),
        ),
        migrations.AddConstraint(
            model_name="conditioncheckmodifier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("check_type__isnull", False), ("stage__isnull", False)),
                fields=("stage", "check_type"),
                name="check_modifier_unique_stage",
            ),
        ),
        migrations.AddConstraint(
            model_name="conditioncheckmodifier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("check_category__isnull", False), ("condition__isnull", False)),
                fields=("condition", "check_category"),
                name="check_modifier_unique_condition_category",
            ),
        ),
        migrations.AddConstraint(
            model_name="conditioncheckmodifier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("check_category__isnull", False), ("stage__isnull", False)),
                fields=("stage", "check_category"),
                name="check_modifier_unique_stage_category",
            ),
        ),
    ]
