# Generated by Django 5.2.4 on 2026-01-15 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("objects", "0001_initial"),
        ("species", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormTrait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Internal key", max_length=50, unique=True),
                ),
                (
                    "display_name",
                    models.CharField(help_text="Display name for UI", max_length=100),
                ),
                (
                    "trait_type",
                    models.CharField(
                        choices=[("color", "Color"), ("style", "Style")],
                        default="style",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FormTraitOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Internal key", max_length=50),
                ),
                (
                    "display_name",
                    models.CharField(help_text="Display name for UI", max_length=100),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="forms.formtrait",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("trait", "name")},
            },
        ),
        migrations.CreateModel(
            name="SpeciesFormTrait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_available_in_cg",
                    models.BooleanField(
                        default=True, help_text="Show this trait in character creation"
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_traits",
                        to="species.species",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species_links",
                        to="forms.formtrait",
                    ),
                ),
            ],
            options={
                "verbose_name": "Species Form Trait",
                "verbose_name_plural": "Species Form Traits",
                "abstract": False,
                "unique_together": {("species", "trait")},
            },
        ),
        migrations.CreateModel(
            name="SpeciesOriginTraitOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, help_text="True=add this option, False=remove it"
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="origin_overrides",
                        to="forms.formtraitoption",
                    ),
                ),
                (
                    "species_origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trait_option_overrides",
                        to="species.speciesorigin",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="origin_overrides",
                        to="forms.formtrait",
                    ),
                ),
            ],
            options={
                "verbose_name": "Species Origin Trait Option",
                "verbose_name_plural": "Species Origin Trait Options",
                "abstract": False,
                "unique_together": {("species_origin", "trait", "option")},
            },
        ),
        migrations.CreateModel(
            name="CharacterForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, help_text="Optional form name", max_length=100),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("true", "True Form"),
                            ("alternate", "Alternate Form"),
                            ("disguise", "Disguise"),
                        ],
                        default="true",
                        max_length=20,
                    ),
                ),
                (
                    "is_player_created",
                    models.BooleanField(
                        default=False, help_text="True for player-created disguises"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        limit_choices_to={"db_typeclass_path__contains": "Character"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forms",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Form",
                "verbose_name_plural": "Character Forms",
            },
        ),
        migrations.CreateModel(
            name="CharacterFormValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="forms.characterform",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_values",
                        to="forms.formtraitoption",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_values",
                        to="forms.formtrait",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Form Value",
                "verbose_name_plural": "Character Form Values",
                "unique_together": {("form", "trait")},
            },
        ),
        migrations.CreateModel(
            name="CharacterFormState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active_form",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_for",
                        to="forms.characterform",
                    ),
                ),
                (
                    "character",
                    models.OneToOneField(
                        limit_choices_to={"db_typeclass_path__contains": "Character"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_state",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Form State",
                "verbose_name_plural": "Character Form States",
            },
        ),
        migrations.CreateModel(
            name="TemporaryFormChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("equipped_item", "Equipped Item"),
                            ("applied_item", "Applied Item"),
                            ("spell", "Spell"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="ID of the source object", null=True
                    ),
                ),
                (
                    "duration_type",
                    models.CharField(
                        choices=[
                            ("until_removed", "Until Removed"),
                            ("real_time", "Real Time"),
                            ("game_time", "Game Time"),
                            ("scene", "Scene-Based"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, help_text="For real-time duration", null=True),
                ),
                (
                    "expires_after_scenes",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="For scene-based duration", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        limit_choices_to={"db_typeclass_path__contains": "Character"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporary_form_changes",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporary_changes",
                        to="forms.formtraitoption",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporary_changes",
                        to="forms.formtrait",
                    ),
                ),
            ],
            options={
                "verbose_name": "Temporary Form Change",
                "verbose_name_plural": "Temporary Form Changes",
            },
        ),
    ]
