# Generated by Django 5.2.4 on 2026-01-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0002_remove_redundant_trait_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Build",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Internal key", max_length=50, unique=True),
                ),
                (
                    "display_name",
                    models.CharField(help_text="Display name", max_length=100),
                ),
                (
                    "weight_factor",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Multiplier for weight calculation (height × factor = weight)",
                        max_digits=3,
                    ),
                ),
                (
                    "is_cg_selectable",
                    models.BooleanField(
                        default=True,
                        help_text="Whether available in character creation",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="HeightBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Internal key", max_length=50, unique=True),
                ),
                (
                    "display_name",
                    models.CharField(help_text="Display name", max_length=100),
                ),
                (
                    "min_inches",
                    models.PositiveSmallIntegerField(
                        help_text="Minimum height in inches (inclusive)"
                    ),
                ),
                (
                    "max_inches",
                    models.PositiveSmallIntegerField(
                        help_text="Maximum height in inches (inclusive)"
                    ),
                ),
                (
                    "weight_min",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum weight in pounds (for extreme bands)",
                        null=True,
                    ),
                ),
                (
                    "weight_max",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum weight in pounds (for extreme bands)",
                        null=True,
                    ),
                ),
                (
                    "is_cg_selectable",
                    models.BooleanField(
                        default=False,
                        help_text="Whether players can select heights in this band during CG",
                    ),
                ),
                (
                    "hide_build",
                    models.BooleanField(
                        default=False,
                        help_text="Hide build display at this scale (e.g., dragon-size)",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "min_inches"],
            },
        ),
        migrations.AddField(
            model_name="formtraitoption",
            name="height_modifier_inches",
            field=models.SmallIntegerField(
                blank=True,
                help_text="Inches added to apparent height when visible (e.g., horns)",
                null=True,
            ),
        ),
    ]
