# Generated by Django 5.2.14 on 2026-06-28 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("character_sheets", "0010_remove_charactersheet_family_and_more"),
        ("forms", "0002_characterformvalue_natural_option_and_more"),
        ("magic", "0052_remove_sanctum_personal_unique_constraint"),
        ("mechanics", "0005_modifiersource_residence_comfort"),
        ("scenes", "0038_scenerounddefaultsconfig_abandonment_grace_rounds"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlternateSelf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tuning_value", models.IntegerField(blank=True, null=True)),
                ("display_name", models.CharField(blank=True, max_length=100)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternate_selves",
                        to="character_sheets.charactersheet",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternate_self_grants",
                        to="forms.characterform",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alternate_self_grants",
                        to="scenes.persona",
                    ),
                ),
                (
                    "techniques",
                    models.ManyToManyField(
                        blank=True,
                        related_name="alternate_self_grants",
                        to="magic.technique",
                    ),
                ),
            ],
            options={
                "ordering": ["character", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="ActiveAlternateSelf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_alternate_self",
                        to="character_sheets.charactersheet",
                    ),
                ),
                (
                    "return_form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_for_active",
                        to="forms.characterform",
                    ),
                ),
                (
                    "return_persona",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_for_active",
                        to="scenes.persona",
                    ),
                ),
                (
                    "alternate_self",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_for",
                        to="forms.alternateself",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FormCombatProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=100)),
                (
                    "form",
                    models.ForeignKey(
                        help_text="The ALTERNATE form this stat-suite belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combat_profiles",
                        to="forms.characterform",
                    ),
                ),
            ],
            options={
                "ordering": ["form", "display_name"],
            },
        ),
        migrations.AddField(
            model_name="alternateself",
            name="combat_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grants",
                to="forms.formcombatprofile",
            ),
        ),
        migrations.CreateModel(
            name="FormCombatProfileEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.IntegerField(help_text="Modifier value (can be negative)."),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="effects",
                        to="forms.formcombatprofile",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_effects",
                        to="mechanics.modifiertarget",
                    ),
                ),
            ],
            options={
                "ordering": ["profile", "target"],
            },
        ),
    ]
