# Generated by Django 5.2.14 on 2026-06-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0005_characterformstate_active_fake_overlay_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formcombatprofile",
            options={"ordering": ["form", "depth", "display_name"]},
        ),
        migrations.AddField(
            model_name="formcombatprofile",
            name="depth",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Profile tier within the form; higher bands select deeper profiles.",
            ),
        ),
    ]
