# Generated by Django 5.2.15 on 2026-07-18 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "evennia_extensions",
            "0014_rename_evennia_ext_player__8c3895_idx_evennia_ext_player__dc5e36_idx",
        ),
        ("forms", "0010_alternateself_resonance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alternateself",
            name="thumbnail",
            field=models.ForeignKey(
                blank=True,
                help_text="Thumbnail shown when this alternate self is active (overrides persona default)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alternate_self_thumbnails",
                to="evennia_extensions.media",
            ),
        ),
    ]
