# Generated by Django 5.2.15 on 2026-07-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0013_alter_characterform_character_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="speciesformtrait",
            name="is_required",
            field=models.BooleanField(
                default=False,
                help_text="This species must have a value for this trait (species identity marker, e.g. horns for True Infernals). CG blocks submit without a selection.",
            ),
        ),
        migrations.AlterField(
            model_name="formtrait",
            name="trait_type",
            field=models.CharField(
                choices=[
                    ("color", "Color"),
                    ("style", "Style"),
                    ("feature", "Feature"),
                ],
                default="style",
                max_length=20,
            ),
        ),
    ]
