[settings]
# Enable idiomatic version files for Python
idiomatic_version_file_enable_tools = ["python"]

[tools]
python = "3.13.0"
node = "24.4.1"
pnpm = "latest"
uv = "latest"

[env]
VIRTUAL_ENV = ".venv"
