# Generated by Django 5.2.16 on 2026-09-06 00:50


from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

import core.mixins
import core.natural_keys
from core_management.batched_migration import BatchedCreateModelMigration
import evennia_extensions.mixins
import evennia_extensions.models
from world.migrations._generations import replaced_slice


class Migration(BatchedCreateModelMigration):
    dependencies = [
        ("arxii", "0008_g2_part_8"),
    ]

    replaces = replaced_slice(9, 103)
    operations = [
        migrations.CreateModel(
            name="AccentExclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "target_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accent_exclusions_a",
                        to="arxii.modifiertarget",
                    ),
                ),
                (
                    "target_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accent_exclusions_b",
                        to="arxii.modifiertarget",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target_a", "target_b"), name="items_accentexclusion_unique_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ActionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name (e.g., 'Fire Bolt', 'Pick Lock').",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Narrative description of this action."),
                ),
                (
                    "pipeline",
                    models.CharField(
                        choices=[
                            ("single", "Single Check"),
                            ("gated", "Gated (with prerequisite checks)"),
                        ],
                        default="single",
                        help_text="Resolution pattern: SINGLE (one check) or GATED (prerequisite checks first).",
                        max_length=20,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("self", "Self"),
                            ("single", "Single Target"),
                            ("area", "Area"),
                            ("filtered_group", "Filtered Group"),
                        ],
                        default="self",
                        help_text="What kind of target this action operates on.",
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Frontend icon identifier.", max_length=50
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Grouping category (e.g., 'magic', 'combat', 'exploration').",
                        max_length=50,
                    ),
                ),
                (
                    "accepts_pose_text",
                    models.BooleanField(
                        default=False,
                        help_text="If true, dispatch may carry freeform pose_text echoed with the outcome.",
                    ),
                ),
                (
                    "default_delivery",
                    models.CharField(
                        choices=[
                            ("pose", "Pose (whole room)"),
                            ("whisper", "Whisper (target only)"),
                            ("table_talk", "Table talk (your place)"),
                            ("mutter", "Mutter (partial echo)"),
                        ],
                        default="pose",
                        help_text="Default audience routing for this action's result echo (#903). Intimate/suggestive socials should author WHISPER; players may override per use.",
                        max_length=20,
                    ),
                ),
                (
                    "ap_cost",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Action points charged on resolution (abstracted time).",
                    ),
                ),
                (
                    "social_fatigue_cost",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Base social fatigue charged on resolution, scaled by effort_level.",
                    ),
                ),
                (
                    "difficulty_tier_modifier",
                    models.IntegerField(
                        default=0,
                        help_text="Shifts this action's resolved difficulty by N tiers relative to the derived base (#1697). Seduce = +1 (one tier harder than Flirt). 0 for ordinary actions.",
                    ),
                ),
                (
                    "grants_entry_flourish",
                    models.BooleanField(
                        default=False,
                        help_text="If True, a successful dispatch of this action triggers an entry flourish resonance grant for the actor (used by the Entrance social action).",
                    ),
                ),
                (
                    "check_type",
                    models.ForeignKey(
                        help_text="Check type for the main resolution step.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="action_templates",
                        to="arxii.checktype",
                    ),
                ),
                (
                    "consequence_pool",
                    models.ForeignKey(
                        blank=True,
                        help_text="Consequence pool for the main resolution step. Null = check-only action.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="action_templates",
                        to="arxii.consequencepool",
                    ),
                ),
                (
                    "consent_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Consent category for social actions (#1141). Null = uncategorized (gated only by the master switch). Staff tag social templates.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_templates",
                        to="arxii.socialconsentcategory",
                    ),
                ),
            ],
            options={"verbose_name": "Action Template", "verbose_name_plural": "Action Templates"},
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="AmbientEmoteLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "parent_type",
                    models.CharField(
                        choices=[("area", "Area"), ("room", "Room")],
                        help_text="Selects which FK (area or room_profile) is active.",
                        max_length=10,
                    ),
                ),
                (
                    "condition_connector",
                    models.CharField(
                        choices=[("and", "All conditions"), ("or", "Any condition")],
                        default="and",
                        help_text="How this line's conditions combine. Ignored with 0-1 conditions.",
                        max_length=3,
                    ),
                ),
                (
                    "bystander_body",
                    models.TextField(
                        blank=True,
                        help_text="What the room's other occupants see. Leave empty for unconditional lines.",
                    ),
                ),
                (
                    "arriver_body",
                    models.TextField(blank=True, help_text="What the arriving character sees."),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Relative draw weight among this condition-group's own lines.",
                    ),
                ),
                (
                    "fire_chance",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="0-100: probability this line fires once selected. Dial down noisy rooms.",
                    ),
                ),
                (
                    "cooldown_minutes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Re-fire throttle after this line fires, scoped to the line itself.",
                    ),
                ),
                (
                    "last_fired_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Runtime only — never exported to the lore repo grid bundle.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ambient_emote_lines",
                        to="arxii.area",
                    ),
                ),
                (
                    "room_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ambient_emote_lines",
                        to="arxii.roomprofile",
                    ),
                ),
            ],
            options={"ordering": ["parent_type", "id"]},
            bases=(core.mixins.DiscriminatorMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Betrothal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="An unfulfilled promise lapses quietly after this; null = open-ended.",
                        null=True,
                    ),
                ),
                ("broken_at", models.DateTimeField(blank=True, null=True)),
                ("wed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kinsperson_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="betrothals_as_a",
                        to="arxii.kinsperson",
                    ),
                ),
                (
                    "kinsperson_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="betrothals_as_b",
                        to="arxii.kinsperson",
                    ),
                ),
                (
                    "junior_house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="betrothals_as_junior",
                        to="arxii.organization",
                    ),
                ),
                (
                    "senior_house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="betrothals_as_senior",
                        to="arxii.organization",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Betrothals", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Display name for this board.", max_length=100),
                ),
                (
                    "max_active_posts",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="Newest-first display cap. Older posts fall off the display but are retained in the DB (no auto-expiry at MVP).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="ORG board anchor: the organization this board belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boards",
                        to="arxii.organization",
                    ),
                ),
                (
                    "room_profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="LOCATION board anchor: the room this board physically stands in.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boards",
                        to="arxii.roomprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("room_profile__isnull", False),
                            ("organization__isnull", False),
                            _connector="XOR",
                        ),
                        name="board_exactly_one_anchor",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("room_profile__isnull", False)),
                        fields=("room_profile",),
                        name="unique_board_per_room",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("organization__isnull", False)),
                        fields=("organization",),
                        name="unique_board_per_org",
                    ),
                ]
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("BUILDING_CONSTRUCTION", "Building Construction"),
                            ("BUILDING_EXTENSION", "Building Extension"),
                            ("BUILDING_PREPARATION", "Building Preparation"),
                            ("BUILDING_RENOVATION", "Building Renovation"),
                            ("BUILDING_UPGRADE", "Building Upgrade"),
                            ("BUILDING_ACTIVATION", "Building Activation"),
                            ("DOMAIN_IMPROVEMENT", "Domain Improvement"),
                            ("FORTIFICATION_UPGRADE", "Fortification Upgrade"),
                            ("INTERIOR_DESIGN", "Interior Design"),
                            ("ROOM_FEATURE_PROGRESSION", "Room Feature Progression"),
                            ("ROOM_DEFENSE_INSTALLATION", "Room Defense Installation"),
                            ("RESEARCH", "Research"),
                            ("RANSOM", "Ransom"),
                            ("ITEM_REFINEMENT", "Item Refinement"),
                            ("SHIP_CONSTRUCTION", "Ship Construction"),
                            ("SHIP_UPGRADE", "Ship Upgrade"),
                            ("SHIP_REPAIR", "Ship Repair"),
                            ("TEST_KIND", "Test Kind (framework tests only)"),
                            ("GANG_TURF", "Gang Turf"),
                            ("ORGANIZATION_CAPABILITY", "Organization Capability"),
                            ("PROPAGANDA", "Propaganda Campaign"),
                            ("CITY_DEFENSE", "City Defense"),
                            ("FRAME_JOB", "Frame Job"),
                            ("WAR_FUNDING", "War Funding"),
                            ("CLEANUP", "Area Cleanup"),
                        ],
                        help_text="Discriminator selecting which per-kind details model applies.",
                        max_length=40,
                    ),
                ),
                (
                    "completion_mode",
                    models.CharField(
                        choices=[
                            ("SINGLE_THRESHOLD", "Single Threshold"),
                            ("TIERED_PERIOD", "Tiered Period"),
                        ],
                        help_text="SINGLE_THRESHOLD: completes on progress>=threshold OR now>=time_limit. TIERED_PERIOD: completes only at time_limit; tier by progress.",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "Planning"),
                            ("ACTIVE", "Active"),
                            ("RESOLVING", "Resolving"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLANNING",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("time_limit", models.DateTimeField()),
                ("threshold_target", models.PositiveIntegerField(blank=True, null=True)),
                ("current_progress", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner_persona",
                    models.ForeignKey(
                        help_text="The persona who initiated the project (weighted-check source at resolution). Resolved from account.active_persona at creation if triggered from an account-level action like permit activation.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects_owned",
                        to="arxii.persona",
                    ),
                ),
                (
                    "outcome_tier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set at resolution. CheckOutcome row indicating tier via success_level.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_outcomes",
                        to="arxii.checkoutcome",
                    ),
                ),
                (
                    "resonance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="arxii.resonance",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "time_limit"], name="arxii_proje_status_82f397_idx"
                    ),
                    models.Index(fields=["kind"], name="arxii_proje_kind_f341e1_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CaptivityConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "cell_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Default cell room name (player-visible — author in your voice).",
                        max_length=255,
                    ),
                ),
                (
                    "cell_description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Default cell room description (player-visible — author in your voice).",
                    ),
                ),
                (
                    "clue_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Default rescue-clue name at the capture site (player-visible — your voice).",
                        max_length=255,
                    ),
                ),
                (
                    "clue_description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Default rescue-clue description (player-visible — author in your voice).",
                    ),
                ),
                (
                    "clue_detect_difficulty",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Default Search-check difficulty to spot the rescue clue. Placeholder.",
                    ),
                ),
                (
                    "captive_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default mission granted to the captive on capture — its options carry the escape + get-word-out CHALLENGE loops. Null = no captive loop yet.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.missiontemplate",
                    ),
                ),
                (
                    "rescue_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default rescue mission surfaced to allies at the capture site / cell.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.missiontemplate",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="CharacterCodexKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("uncovered", "Uncovered"), ("known", "Known")],
                        default="uncovered",
                        max_length=20,
                    ),
                ),
                (
                    "learning_progress",
                    models.PositiveIntegerField(
                        default=0, help_text="Accumulated progress toward entry.learn_threshold."
                    ),
                ),
                (
                    "learned_at",
                    models.DateTimeField(
                        blank=True, help_text="When this entry was fully learned.", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_knowledge",
                        to="arxii.codexentry",
                    ),
                ),
                (
                    "roster_entry",
                    models.ForeignKey(
                        help_text="Character (via roster entry) that has this knowledge.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codex_knowledge",
                        to="arxii.rosterentry",
                    ),
                ),
                (
                    "learned_from",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenure who taught this entry.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="codex_taught",
                        to="arxii.rostertenure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Codex Knowledge",
                "verbose_name_plural": "Character Codex Knowledge",
                "unique_together": {("roster_entry", "entry")},
            },
            bases=(evennia_extensions.mixins.RelatedCacheClearingMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CharacterRitualKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("learned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ritual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="known_by_records",
                        to="arxii.ritual",
                    ),
                ),
                (
                    "roster_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="known_rituals",
                        to="arxii.rosterentry",
                    ),
                ),
                (
                    "learned_from",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tenure of the character who taught this ritual. NULL when self-authored or granted by background.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="taught_rituals",
                        to="arxii.rostertenure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Ritual Knowledge",
                "verbose_name_plural": "Character Ritual Knowledge",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("roster_entry", "ritual"), name="unique_roster_ritual_knowledge"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CheckProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "proposed_name",
                    models.CharField(
                        help_text="The check's proposed name (e.g. 'Riverside Tracking').",
                        max_length=100,
                    ),
                ),
                (
                    "intent",
                    models.TextField(
                        help_text="What this check is meant to cover -- the gap in the catalog."
                    ),
                ),
                (
                    "suggested_traits_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Suggested stat+skill pairing in plain text (e.g. 'Perception + Survival'). Advisory only -- no live Trait FK exists until staff author the real row.",
                        max_length=200,
                    ),
                ),
                (
                    "situation_text",
                    models.TextField(
                        help_text="The situation this check would serve -- when someone would roll it."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("reviewed", "Reviewed"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff account that reviewed this proposal.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by_account",
                    models.ForeignKey(
                        help_text="OOC authoring, not IC -- mirrors PlayerFeedback.reporter_account.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by_persona",
                    models.ForeignKey(
                        help_text="The persona the submitter was wearing when proposing.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_proposals",
                        to="arxii.persona",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        help_text="The scene the proposal arose in, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="check_proposals",
                        to="arxii.scene",
                    ),
                ),
            ],
            options={
                "verbose_name": "Check Proposal",
                "verbose_name_plural": "Check Proposals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CheckTypeAspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Relevance multiplier for this aspect (default 1.0)",
                        max_digits=4,
                    ),
                ),
                (
                    "aspect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_type_aspects",
                        to="arxii.aspect",
                    ),
                ),
                (
                    "check_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aspects",
                        to="arxii.checktype",
                    ),
                ),
            ],
            options={"unique_together": {("check_type", "aspect")}},
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CheckTypeCapabilityModifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Multiplier applied to the character's effective capability value MINUS its innate baseline, so an unimpaired character contributes 0. Per-check contribution is int(sum of weight x deviation) truncated toward zero.",
                        max_digits=4,
                    ),
                ),
                (
                    "capability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_type_modifiers",
                        to="arxii.capabilitytype",
                    ),
                ),
                (
                    "check_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capability_modifiers",
                        to="arxii.checktype",
                    ),
                ),
            ],
            options={"unique_together": {("check_type", "capability")}},
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CheckTypeSituationFit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "written_on",
                    models.DateField(
                        blank=True, help_text="Date the prose was written.", null=True
                    ),
                ),
                (
                    "reviewed_on",
                    models.DateField(
                        blank=True, help_text="Date the prose was reviewed.", null=True
                    ),
                ),
                (
                    "fit_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Why this check fits this kind of scene -- shown in browse results.",
                    ),
                ),
                (
                    "check_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="situation_fits",
                        to="arxii.checktype",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who reviewed this row's prose, if anyone. Distinct from writing it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.contentcontributor",
                    ),
                ),
                (
                    "written_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who wrote this row's prose. Null means it is still a placeholder.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.contentcontributor",
                    ),
                ),
                (
                    "situation_kind",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_fits",
                        to="arxii.situationkind",
                    ),
                ),
            ],
            options={
                "verbose_name": "Check Type Situation Fit",
                "verbose_name_plural": "Check Type Situation Fits",
                "ordering": ["situation_kind__name", "check_type__name"],
                "unique_together": {("check_type", "situation_kind")},
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CheckTypeSpecialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Multiplier for this specialization's contribution (default 1.0)",
                        max_digits=4,
                    ),
                ),
                (
                    "check_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specializations",
                        to="arxii.checktype",
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_type_specializations",
                        to="arxii.specialization",
                    ),
                ),
            ],
            options={"unique_together": {("check_type", "specialization")}},
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CheckTypeTrait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Multiplier for this trait's contribution (default 1.0)",
                        max_digits=4,
                    ),
                ),
                (
                    "check_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traits",
                        to="arxii.checktype",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_type_traits",
                        to="arxii.trait",
                    ),
                ),
            ],
            options={"unique_together": {("check_type", "trait")}},
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CodexEntryFiling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Order for display within the filed subject's listing."
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filings",
                        to="arxii.codexentry",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filed_entries",
                        to="arxii.codexsubject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Codex Entry Filing",
                "verbose_name_plural": "Codex Entry Filings",
                "ordering": ["subject", "sort_order", "pk"],
                "unique_together": {("entry", "subject")},
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CodexEntryRitualGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "codex_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ritual_grants",
                        to="arxii.codexentry",
                    ),
                ),
                (
                    "ritual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="arxii.ritual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Codex Entry Ritual Grant",
                "verbose_name_plural": "Codex Entry Ritual Grants",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("codex_entry", "ritual"), name="unique_codex_entry_ritual_grant"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CodexKnowledgeRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this requirement"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this requirement is active"
                    ),
                ),
                (
                    "class_level_unlock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_requirements",
                        to="arxii.classlevelunlock",
                    ),
                ),
                (
                    "codex_entry",
                    models.ForeignKey(
                        help_text="The codex entry the character must know (KNOWN status).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codex_knowledge_requirements",
                        to="arxii.codexentry",
                    ),
                ),
                (
                    "path",
                    models.ForeignKey(
                        blank=True,
                        help_text="Path this requirement gates (#2538). Used for hybrid path entry and cross-path technique learning. Exactly one of class_level_unlock / thread_crossing_threshold / path must be set.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_requirements",
                        to="arxii.path",
                    ),
                ),
                (
                    "thread_crossing_threshold",
                    models.ForeignKey(
                        blank=True,
                        help_text="Thread crossing threshold this requirement gates. Exactly one of class_level_unlock / thread_crossing_threshold / path must be set.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_requirements",
                        to="arxii.threadcrossingthreshold",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("class_level_unlock__isnull", False),
                                ("thread_crossing_threshold__isnull", True),
                                ("path__isnull", True),
                            ),
                            models.Q(
                                ("class_level_unlock__isnull", True),
                                ("thread_crossing_threshold__isnull", False),
                                ("path__isnull", True),
                            ),
                            models.Q(
                                ("class_level_unlock__isnull", True),
                                ("thread_crossing_threshold__isnull", True),
                                ("path__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="codexknowledgerequirement_exactly_one_unlock_target",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CohortEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohort_enrollments",
                        to="arxii.persona",
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="arxii.durancecohort",
                    ),
                ),
                (
                    "enrollment_scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cohort_enrollments_here",
                        to="arxii.scene",
                    ),
                ),
            ],
            options={
                "ordering": ["-enrolled_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cohort", "persona"), name="cohort_enrollment_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ComboDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "hidden",
                    models.BooleanField(
                        default=True, help_text="Hidden until learned by at least one PC."
                    ),
                ),
                ("discoverable_via_training", models.BooleanField(default=True)),
                ("discoverable_via_combat", models.BooleanField(default=True)),
                ("discoverable_via_research", models.BooleanField(default=False)),
                (
                    "minimum_probing",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Probing counter required on target before this combo is available.",
                        null=True,
                    ),
                ),
                (
                    "bypass_soak",
                    models.BooleanField(
                        default=True,
                        help_text="Whether combo damage bypasses the target's soak value.",
                    ),
                ),
                (
                    "bonus_damage",
                    models.PositiveIntegerField(
                        default=0, help_text="Flat bonus damage added when the combo fires."
                    ),
                ),
                (
                    "discovery_first_body",
                    models.TextField(
                        blank=True,
                        help_text="Gamewide announcement body for first-ever discovery. Must NOT name the discoverer. Example: 'For the first time, a covenant has unleashed Firestorm Fusion in battle.'",
                    ),
                ),
                (
                    "discovery_personal_body",
                    models.TextField(
                        blank=True,
                        help_text="Personal announcement body for repeat discovery. Example: 'Your covenant has discovered Firestorm Fusion.'",
                    ),
                ),
                (
                    "required_clash_flavor",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CLASH", "Clash"),
                            ("LOCK", "Lock"),
                            ("WARD", "Ward"),
                            ("BREAK", "Break"),
                        ],
                        help_text="If set, this combo is only available during a Clash of the specified flavor. Null means the combo is not clash-gated.",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "discovery_achievement",
                    models.ForeignKey(
                        blank=True,
                        help_text="Achievement granted (with global-first Discovery) the first time a character gains this content. Null = not discoverable.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="arxii.achievement",
                    ),
                ),
                (
                    "required_clash_window_condition",
                    models.ForeignKey(
                        blank=True,
                        help_text="Clash-window gate: the target must have an active instance of this condition for the combo to be available. Null means no window condition is required.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="arxii.conditiontemplate",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
