# Generated by Django 5.2.16 on 2026-09-06 00:50


import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

import core.mixins
import core.natural_keys
from core_management.batched_migration import BatchedCreateModelMigration
from world.migrations._generations import replaced_slice


class Migration(BatchedCreateModelMigration):
    dependencies = [
        ("arxii", "0013_g2_part_13"),
    ]

    replaces = replaced_slice(14, 103)
    operations = [
        migrations.CreateModel(
            name="EpisodeProgressionRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "required_outcome",
                    models.CharField(
                        choices=[
                            ("unsatisfied", "Unsatisfied"),
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("expired", "Expired"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                (
                    "beat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gating_for_episodes",
                        to="arxii.beat",
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progression_requirements",
                        to="arxii.episode",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("episode", "beat"), name="unique_progression_req_per_episode_beat"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="EpisodeScene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episode_scenes",
                        to="arxii.episode",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_episodes",
                        to="arxii.scene",
                    ),
                ),
            ],
            options={"ordering": ["episode", "order"], "unique_together": {("episode", "scene")}},
        ),
        migrations.CreateModel(
            name="EquippedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "body_region",
                    models.CharField(
                        choices=[
                            ("head", "Head"),
                            ("face", "Face"),
                            ("neck", "Neck"),
                            ("shoulders", "Shoulders"),
                            ("torso", "Torso"),
                            ("back", "Back"),
                            ("waist", "Waist"),
                            ("left_arm", "Left Arm"),
                            ("right_arm", "Right Arm"),
                            ("left_hand", "Left Hand"),
                            ("right_hand", "Right Hand"),
                            ("left_leg", "Left Leg"),
                            ("right_leg", "Right Leg"),
                            ("feet", "Feet"),
                            ("left_finger", "Left Finger"),
                            ("right_finger", "Right Finger"),
                            ("left_ear", "Left Ear"),
                            ("right_ear", "Right Ear"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "equipment_layer",
                    models.CharField(
                        choices=[
                            ("skin", "Skin"),
                            ("under", "Under"),
                            ("base", "Base"),
                            ("over", "Over"),
                            ("outer", "Outer"),
                            ("accessory", "Accessory"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "opened_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Worn open (#2985): the show verb parts this garment so whatever lies beneath it shows — the next layer, or skin at the bottom of the stack. Cleared by conceal or by dressing at the region; dies with the row on unequip.",
                        null=True,
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        help_text="The character wearing/wielding this item.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipped_items",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "item_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipped_slots",
                        to="arxii.iteminstance",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character", "body_region", "equipment_layer"),
                        name="items_unique_equipped_slot",
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="EscalationCurve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "start_round",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="First round the escalation tick fires (>=2 keeps round one calm).",
                    ),
                ),
                (
                    "intensity_step",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Intensity modifier added to each participant's engagement per tick.",
                    ),
                ),
                (
                    "pace_difficulty_base",
                    models.PositiveIntegerField(
                        default=0, help_text="Base difficulty of the pace check."
                    ),
                ),
                (
                    "pace_difficulty_per_level",
                    models.PositiveIntegerField(
                        default=0, help_text="Difficulty added per accumulated escalation level."
                    ),
                ),
                (
                    "control_step_on_success",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Control modifier gained on a pace-check success (success_level >= 1).",
                    ),
                ),
                (
                    "control_step_on_partial",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Control modifier gained on a partial success (success_level == 0).",
                    ),
                ),
                (
                    "control_step_on_botch",
                    models.IntegerField(
                        default=-1,
                        help_text="Control modifier change on a botch (success_level <= -2); author negative.",
                    ),
                ),
                (
                    "max_escalation_level",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Tick stops raising pressure past this level. 0 = uncapped.",
                    ),
                ),
                (
                    "spike_intensity_amount",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Intensity spike applied to bonded co-combatants when an ally falls.",
                    ),
                ),
                (
                    "spike_minimum_track_points",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum developed_points on a spike-fueling relationship track for the bond to qualify.",
                    ),
                ),
                (
                    "tick_narration",
                    models.TextField(
                        blank=True,
                        help_text="Narrative line surfaced to the combat panel on each tick.",
                    ),
                ),
                (
                    "peril_spike_intensity_amount",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Intensity spike applied to bonded co-combatants when an ally enters mortal peril (#2013).",
                    ),
                ),
                (
                    "hated_foe_spike_intensity_amount",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Intensity spike applied when a hated NPC foe enters the encounter (#2013).",
                    ),
                ),
                (
                    "interference_spike_intensity_amount",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Intensity spike for the locked duelist when a non-locked PC interferes with the duel (#2020).",
                    ),
                ),
                (
                    "boss_phase_spike_intensity_amount",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Intensity spike for every ACTIVE PC when a boss crosses into a new phase without hitting harder (#3445). 0 disables this beat for the curve.",
                    ),
                ),
                (
                    "boss_enrage_spike_intensity_amount",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="Intensity spike for every ACTIVE PC when a phase transition raises the boss's damage_multiplier (#3445). 0 disables this beat for the curve.",
                    ),
                ),
                (
                    "boss_break_spike_intensity_amount",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="Intensity spike for every ACTIVE PC when a boss's break bar reaches zero (#3445). Fires once per boss per phase, so the re-break loop cannot repeat it. 0 disables this beat for the curve.",
                    ),
                ),
                (
                    "surge_narration",
                    models.TextField(
                        blank=True,
                        help_text="Generic dramatic-surge narration template. Only the literal substring '{character}' is substituted (the surging PC's name) — never the bond, track, or subject, per the leak rule (#2013). Blank uses a built-in generic line.",
                    ),
                ),
                (
                    "pace_check_type",
                    models.ForeignKey(
                        help_text="Check rolled each tick to keep control in pace with intensity.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escalation_curves",
                        to="arxii.checktype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escalation Curve",
                "verbose_name_plural": "Escalation Curves",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EstateSettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deadline",
                    models.DateTimeField(
                        help_text="When the sweeper door auto-settles (opened_at + config window)."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("settled", "Settled"),
                            ("parked", "Parked (staff attention)"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "settled_via",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("funeral", "Funeral"),
                            ("reading", "Will Reading"),
                            ("auto", "Deadline Sweeper"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "character_sheet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estate_settlement",
                        to="arxii.charactersheet",
                    ),
                ),
            ],
            options={"ordering": ["-opened_at"]},
        ),
        migrations.CreateModel(
            name="EstateClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claimant_persona",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estate_claims",
                        to="arxii.persona",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estate_claims",
                        to="arxii.iteminstance",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="arxii.estatesettlement",
                    ),
                ),
                (
                    "claimant_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estate_claims",
                        to="arxii.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["settlement_id", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("claimant_persona__isnull", False),
                            ("claimant_organization__isnull", False),
                            _connector="XOR",
                        ),
                        name="claim_one_claimant",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EventCatering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("container", "Catering Vessel"), ("provision", "Provision")],
                        help_text="CONTAINER (a flagged vessel) or PROVISION (a consumable set out in one).",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contributed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who flagged the vessel or set the dish out (provenance).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catering_contributions",
                        to="arxii.persona",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catering",
                        to="arxii.event",
                    ),
                ),
                (
                    "item_instance",
                    models.ForeignKey(
                        help_text="The vessel or provision itself — still a real item in the world.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catering_uses",
                        to="arxii.iteminstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Catering",
                "verbose_name_plural": "Event Catering",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "item_instance"),
                        name="events_catering_unique_item_per_event",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EventHost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="The primary host is the 'face' of the event on listings",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosts",
                        to="arxii.event",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hosted_events",
                        to="arxii.persona",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("persona__isnull", False)),
                        fields=("event", "persona"),
                        name="unique_event_host",
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="EventInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("persona", "Persona"),
                            ("organization", "Organization"),
                            ("society", "Society"),
                        ],
                        max_length=20,
                    ),
                ),
                ("can_bring_guests", models.BooleanField(default=False)),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "response",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="arxii.event",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations_sent",
                        to="arxii.persona",
                    ),
                ),
                (
                    "target_persona",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_invitations",
                        to="arxii.persona",
                    ),
                ),
                (
                    "target_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_invitations",
                        to="arxii.organization",
                    ),
                ),
                (
                    "target_society",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_invitations",
                        to="arxii.society",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("target_type", "persona")),
                        fields=("event", "target_type", "target_persona"),
                        name="unique_persona_invitation",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("target_type", "organization")),
                        fields=("event", "target_type", "target_organization"),
                        name="unique_organization_invitation",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("target_type", "society")),
                        fields=("event", "target_type", "target_society"),
                        name="unique_society_invitation",
                    ),
                ]
            },
            bases=(core.mixins.DiscriminatorMixin, models.Model),
        ),
        migrations.CreateModel(
            name="EventModification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "room_description_overlay",
                    models.TextField(
                        blank=True,
                        help_text="Text that augments the room description while event is active",
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modification",
                        to="arxii.event",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ExpulsionBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("imposed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lifted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the bar was lifted. Null while active.",
                        null=True,
                    ),
                ),
                (
                    "barred_sheet",
                    models.ForeignKey(
                        help_text="The character sheet barred from re-entry.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expulsion_bars",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "imposed_by",
                    models.ForeignKey(
                        help_text="The persona who imposed the bar (audit trail, not a permission gate).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expulsion_bars_imposed",
                        to="arxii.persona",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        help_text="The room the barred character may not re-enter.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expulsion_bars",
                        to="arxii.roomprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-imposed_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("lifted_at__isnull", True)),
                        fields=("room", "barred_sheet"),
                        name="unique_active_expulsion_bar_per_room_sheet",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FacetVogueMomentum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vogue_momentum",
                        to="arxii.facet",
                    ),
                ),
                (
                    "society",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facet_momentum",
                        to="arxii.society",
                    ),
                ),
            ],
            options={
                "ordering": ["-points"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("society", "facet"), name="unique_facet_momentum"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FallRedemptionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "conversion_type",
                    models.CharField(
                        choices=[("FALL", "Fall"), ("REDEMPTION", "Redemption")], max_length=16
                    ),
                ),
                (
                    "from_affinity",
                    models.CharField(
                        choices=[
                            ("celestial", "Celestial"),
                            ("primal", "Primal"),
                            ("abyssal", "Abyssal"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "to_affinity",
                    models.CharField(
                        choices=[
                            ("celestial", "Celestial"),
                            ("primal", "Primal"),
                            ("abyssal", "Abyssal"),
                        ],
                        max_length=16,
                    ),
                ),
                ("multiplier", models.DecimalField(decimal_places=2, max_digits=4)),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fall_redemption_records",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fall_redemption_records",
                        to="arxii.scene",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fall / Redemption Record",
                "verbose_name_plural": "Fall / Redemption Records",
                "ordering": ["-performed_at"],
            },
        ),
        migrations.CreateModel(
            name="FamilyMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("born", "Born Into"),
                            ("married_in", "Married In"),
                            ("adopted", "Adopted"),
                            ("legitimized", "Legitimized"),
                            ("granted", "Granted"),
                            ("founding", "Founding Member"),
                        ],
                        help_text="How this person came to belong (born/married-in/adopted/...).",
                        max_length=20,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=True, help_text="Whether this is the surname-carrying membership."
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "end_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("disowned", "Disowned"),
                            ("married_out", "Married Out"),
                            ("renounced", "Renounced"),
                            ("annulled", "Annulled"),
                        ],
                        help_text="Why it ended (disowned/married-out/...). Blank while active.",
                        max_length=20,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="arxii.family",
                    ),
                ),
                (
                    "kinsperson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_memberships",
                        to="arxii.kinsperson",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["family", "ended_at"], name="arxii_famil_family__3f01d7_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FashionStyleBonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="Authored magnitude multiplier on the worn facet-match value.",
                        max_digits=4,
                    ),
                ),
                (
                    "fashion_style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonuses",
                        to="arxii.fashionstyle",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fashion_style_bonuses",
                        to="arxii.modifiertarget",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("fashion_style", "target"),
                        name="items_unique_fashionstylebonus_per_target",
                    )
                ]
            },
        ),
    ]
