# Generated by Django 5.2.16 on 2026-09-06 00:50


from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

import core.mixins
import core.natural_keys
from core_management.batched_migration import BatchedCreateModelMigration
from world.migrations._generations import replaced_slice


class Migration(BatchedCreateModelMigration):
    dependencies = [
        ("arxii", "0016_g2_part_16"),
    ]

    replaces = replaced_slice(17, 103)
    operations = [
        migrations.CreateModel(
            name="InsightTableEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "written_on",
                    models.DateField(
                        blank=True, help_text="Date the prose was written.", null=True
                    ),
                ),
                (
                    "reviewed_on",
                    models.DateField(
                        blank=True, help_text="Date the prose was reviewed.", null=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Curated entry name, e.g. 'A Gap in Their Guard'.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "prose",
                    models.TextField(
                        help_text="The announced reading, shared loudly on both the web broadcast and telnet. Supports {caster}/{target} placeholders."
                    ),
                ),
                (
                    "target_kind",
                    models.CharField(
                        choices=[("self", "Self"), ("ally", "Ally"), ("team", "Team")],
                        help_text="Who the condition lands on when this entry is drawn.",
                        max_length=10,
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Relative weight in the weighted-random draw over active entries.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive entries are excluded from the draw without deleting them.",
                    ),
                ),
                (
                    "condition",
                    models.ForeignKey(
                        help_text="The authored one-round effect this entry applies. Author a one-round duration on the condition itself — the Insight never overrides it.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="insight_entries",
                        to="arxii.conditiontemplate",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who reviewed this row's prose, if anyone. Distinct from writing it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.contentcontributor",
                    ),
                ),
                (
                    "written_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who wrote this row's prose. Null means it is still a placeholder.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.contentcontributor",
                    ),
                ),
            ],
            options={"ordering": ["name"]},
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="InstancedRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_key", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("completed", "Completed")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gm_owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="GM who spun this instance up (story scene rooms, #2450).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_instances",
                        to="arxii.gmprofile",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_instances",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "return_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instance_data",
                        to="arxii.roomprofile",
                    ),
                ),
            ],
            options={"verbose_name": "Instanced Room", "verbose_name_plural": "Instanced Rooms"},
        ),
        migrations.CreateModel(
            name="ItemAccent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "item_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accents",
                        to="arxii.iteminstance",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        help_text="How strongly the accent realized (its own roll at craft time).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="item_accents",
                        to="arxii.accentlevel",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        help_text="The styleable axis (is_styleable=True): allure, menace, …",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="item_accents",
                        to="arxii.modifiertarget",
                    ),
                ),
            ],
            options={
                "ordering": ["target__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("item_instance", "target"),
                        name="items_itemaccent_unique_per_target",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemCheckModifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "modifier_value",
                    models.IntegerField(
                        help_text="Flat modifier applied when the item is equipped (positive = bonus, negative = penalty)."
                    ),
                ),
                (
                    "check_type",
                    models.ForeignKey(
                        help_text="The check type this modifier affects.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_check_modifiers",
                        to="arxii.checktype",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="Item template that carries this modifier.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_modifiers",
                        to="arxii.itemtemplate",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("template", "check_type"),
                        name="items_unique_itemcheckmodifier_per_template_check",
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="ItemFacet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applied_by_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="item_attachments",
                        to="arxii.facet",
                    ),
                ),
                (
                    "item_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_facets",
                        to="arxii.iteminstance",
                    ),
                ),
                (
                    "attachment_quality_tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_attachments",
                        to="arxii.qualitytier",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("item_instance", "facet"),
                        name="items_unique_itemfacet_per_instance",
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="ItemRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this requirement"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this requirement is active"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Template-mode only; touchstone-mode is a possess-at-least-one check.",
                    ),
                ),
                (
                    "class_level_unlock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_requirements",
                        to="arxii.classlevelunlock",
                    ),
                ),
                (
                    "item_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="class_level_item_requirements",
                        to="arxii.itemtemplate",
                    ),
                ),
                (
                    "path",
                    models.ForeignKey(
                        blank=True,
                        help_text="Path this requirement gates (#2538). Used for hybrid path entry and cross-path technique learning. Exactly one of class_level_unlock / thread_crossing_threshold / path must be set.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_requirements",
                        to="arxii.path",
                    ),
                ),
                (
                    "min_quality_tier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Template-mode only; ignored in touchstone mode.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.qualitytier",
                    ),
                ),
                (
                    "min_touchstone_tier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Touchstone mode: any item attuned to the character, tied to a Resonance they've claimed, at or above this tier, satisfies this requirement. Exactly one of item_template/min_touchstone_tier is set.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="arxii.resonancetier",
                    ),
                ),
                (
                    "thread_crossing_threshold",
                    models.ForeignKey(
                        blank=True,
                        help_text="Thread crossing threshold this requirement gates. Exactly one of class_level_unlock / thread_crossing_threshold / path must be set.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_requirements",
                        to="arxii.threadcrossingthreshold",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("item_template__isnull", False),
                                ("min_touchstone_tier__isnull", True),
                            ),
                            models.Q(
                                ("item_template__isnull", True),
                                ("min_touchstone_tier__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="itemrequirement_exactly_one_mode",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("class_level_unlock__isnull", False),
                                ("thread_crossing_threshold__isnull", True),
                            ),
                            models.Q(
                                ("class_level_unlock__isnull", True),
                                ("thread_crossing_threshold__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="itemrequirement_exactly_one_unlock_target",
                    ),
                ]
            },
        ),
        migrations.CreateModel(
            name="ItemStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applied_by_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_styles",
                        to="arxii.iteminstance",
                    ),
                ),
                (
                    "attachment_quality_tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_attachments",
                        to="arxii.qualitytier",
                    ),
                ),
                (
                    "style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="item_attachments",
                        to="arxii.style",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("item_instance", "style"),
                        name="items_unique_itemstyle_per_instance",
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="ItemTemplateAppearanceEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "item_template",
                    models.ForeignKey(
                        help_text="The item template this cosmetic effect belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appearance_effects",
                        to="arxii.itemtemplate",
                    ),
                ),
                (
                    "target_option",
                    models.ForeignKey(
                        blank=True,
                        help_text="The value the trait is set to when this item is used. Null = the user chooses any option of the trait at use time (#2632 — one Styling Kit selects the style; Ariwn Lenses take 'a drop of dye' in any color).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="item_template_effects",
                        to="arxii.formtraitoption",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        help_text="The appearance trait this item can change (e.g., hair_color).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="item_template_effects",
                        to="arxii.formtrait",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("item_template", "trait"),
                        name="items_one_appearance_effect_per_trait_per_template",
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="ItemTemplateProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.PositiveIntegerField(default=1)),
                (
                    "item_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="default_properties",
                        to="arxii.itemtemplate",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_template_defaults",
                        to="arxii.property",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("item_template", "property"), name="items_template_property_unique"
                    )
                ]
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="JournalBequestGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by_settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_bequest_grants",
                        to="arxii.estatesettlement",
                    ),
                ),
                (
                    "deceased_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_bequests_granted",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "recipient_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_bequests_received",
                        to="arxii.charactersheet",
                    ),
                ),
            ],
            options={
                "ordering": ["deceased_sheet_id", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("recipient_sheet", "deceased_sheet"),
                        name="unique_journal_bequest_grant",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="KinSlotPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text='Player-facing pool blurb, e.g. "children of the current nobles".',
                        max_length=200,
                    ),
                ),
                (
                    "count_remaining",
                    models.PositiveIntegerField(
                        help_text="Slots left in this pool; claiming decrements."
                    ),
                ),
                ("age_min", models.PositiveIntegerField(blank=True, null=True)),
                ("age_max", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "allowed_genders",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Constraint on minted claimants. Empty = unconstrained.",
                        related_name="+",
                        to="arxii.gender",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kin_slot_pools",
                        to="arxii.family",
                    ),
                ),
                (
                    "parents",
                    models.ManyToManyField(
                        help_text="The parent-set minted children link to.",
                        related_name="kin_slot_pools",
                        to="arxii.kinsperson",
                    ),
                ),
            ],
            options={"ordering": ["family", "pk"]},
        ),
        migrations.CreateModel(
            name="KinspersonTraitValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kinsperson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trait_values",
                        to="arxii.kinsperson",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kinsperson_values",
                        to="arxii.formtraitoption",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kinsperson_values",
                        to="arxii.formtrait",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kinsperson", "trait"), name="roster_kinsperson_trait_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="KudosTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Kudos change (positive for awards, negative for claims)"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Visible description explaining why kudos was awarded/claimed",
                        max_length=500,
                    ),
                ),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kudos_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "awarded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Account that awarded this kudos (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kudos_awarded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        help_text="Character involved (e.g., for death bonus)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kudos_transactions",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "claim_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Claim category for claims (null for awards)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="arxii.kudosclaimcategory",
                    ),
                ),
                (
                    "source_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source category for awards (null for claims)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="arxii.kudossourcecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_date"],
                "indexes": [
                    models.Index(
                        fields=["account", "-transaction_date"],
                        name="arxii_kudos_account_0f46d7_idx",
                    ),
                    models.Index(
                        fields=["source_category", "-transaction_date"],
                        name="arxii_kudos_source__aac5b0_idx",
                    ),
                    models.Index(
                        fields=["claim_category", "-transaction_date"],
                        name="arxii_kudos_claim_c_bc8849_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LegendDeedStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.TextField(help_text="The player-written account of the deed")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The persona that wrote this account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legend_stories_written",
                        to="arxii.persona",
                    ),
                ),
                (
                    "deed",
                    models.ForeignKey(
                        help_text="The legend entry this story is about",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deed_stories",
                        to="arxii.legendentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legend Deed Story",
                "verbose_name_plural": "Legend Deed Stories",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("deed", "author"), name="unique_deed_story_per_author"
                    )
                ],
            },
        ),
    ]
