# Generated by Django 5.2.15 on 2026-08-04 07:42


import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0023_initial_part_23"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingPreparationDetails",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="building_preparation_details",
                        serialize=False,
                        to="arxii.project",
                    ),
                ),
                (
                    "target_tier",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Decayed"),
                            (1, "Ramshackle"),
                            (2, "Worn"),
                            (3, "Fine"),
                            (4, "Good"),
                            (5, "Excellent"),
                            (6, "Extravagantly Polished"),
                            (7, "Immaculate"),
                        ],
                        help_text="Condition tier applied on completion (current tier + 1 at commission).",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the tier was applied; NULL until the handler runs. Idempotency marker.",
                        null=True,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preparation_details",
                        to="arxii.building",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Building preparation details"},
        ),
        migrations.CreateModel(
            name="BuildingRenovationDetails",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="building_renovation_details",
                        serialize=False,
                        to="arxii.project",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the kind was re-pointed; NULL until the handler runs. Idempotency marker.",
                        null=True,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renovation_details",
                        to="arxii.building",
                    ),
                ),
                (
                    "target_kind",
                    models.ForeignKey(
                        help_text="The catalog BuildingKind this building is re-pointed to on completion.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="renovation_targets",
                        to="arxii.buildingkind",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Building renovation details"},
        ),
        migrations.CreateModel(
            name="BuildingUpgradeDetails",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="building_upgrade_details",
                        serialize=False,
                        to="arxii.project",
                    ),
                ),
                (
                    "new_target_size",
                    models.PositiveSmallIntegerField(
                        help_text="Size tier this upgrade targets on completion.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the size was applied; NULL until the handler runs. Idempotency marker.",
                        null=True,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upgrade_details",
                        to="arxii.building",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Building upgrade details"},
        ),
        migrations.CreateModel(
            name="CityDefenseDetails",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="city_defense_details",
                        serialize=False,
                        to="arxii.project",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the handler runs; idempotency guard (claim-filter pattern).",
                        null=True,
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        help_text="The defended region. PROTECT prevents deleting an area with a defense project.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="city_defense_projects",
                        to="arxii.area",
                    ),
                ),
                (
                    "outcome_tier",
                    models.ForeignKey(
                        blank=True,
                        help_text="The graded outcome tier, set when the handler runs at deadline.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="city_defense_projects",
                        to="arxii.checkoutcome",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="CityDefenseTierThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "min_progress",
                    models.PositiveIntegerField(
                        help_text="Minimum progress at which this tier applies."
                    ),
                ),
                (
                    "outcome_tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="city_defense_thresholds",
                        to="arxii.checkoutcome",
                    ),
                ),
                (
                    "details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tier_thresholds",
                        to="arxii.citydefensedetails",
                    ),
                ),
            ],
            options={"ordering": ["-min_progress"]},
        ),
        migrations.CreateModel(
            name="CleanupProjectDetails",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="cleanup_details",
                        serialize=False,
                        to="arxii.project",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the quality bump was applied; NULL until the handler runs.",
                        null=True,
                    ),
                ),
                (
                    "target_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cleanup_projects",
                        to="arxii.area",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="CleanupTierThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("min_progress", models.PositiveIntegerField()),
                (
                    "quality_delta",
                    models.PositiveSmallIntegerField(
                        help_text="How much quality rises if this tier is reached."
                    ),
                ),
                (
                    "outcome_tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cleanup_thresholds",
                        to="arxii.checkoutcome",
                    ),
                ),
                (
                    "details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tier_thresholds",
                        to="arxii.cleanupprojectdetails",
                    ),
                ),
            ],
            options={"ordering": ["-min_progress"]},
        ),
        migrations.CreateModel(
            name="DefenseProgressionDetails",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="defense_progression_details",
                        serialize=False,
                        to="arxii.project",
                    ),
                ),
                (
                    "defense_kind",
                    models.CharField(
                        choices=[
                            ("EXIT_BARS", "Exit Bars"),
                            ("ROOM_WARD", "Room Ward"),
                            ("ROOM_ALARM", "Room Alarm"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "target_level",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "reaction_damage_amount",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="Optional ward reaction damage (ROOM_WARD installs only).",
                        null=True,
                    ),
                ),
                (
                    "reaction_condition",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional ward reaction condition (ROOM_WARD installs only). Must be from a ConditionCategory with is_negative=True.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="defense_progression_projects",
                        to="arxii.conditiontemplate",
                    ),
                ),
                (
                    "resonance",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required for ROOM_WARD installs only.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="defense_progression_projects",
                        to="arxii.resonance",
                    ),
                ),
                (
                    "target_exit_profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set only for EXIT_BARS installs/upgrades.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="defense_progression_projects",
                        to="arxii.exitprofile",
                    ),
                ),
                (
                    "target_room_profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set only for ROOM_WARD/ROOM_ALARM installs/upgrades.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="defense_progression_projects",
                        to="arxii.roomprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DomainImprovementDetails",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="domain_improvement_details",
                        serialize=False,
                        to="arxii.project",
                    ),
                ),
                (
                    "gross_increase",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Coppers/cycle added to the holding's stream on success. PLACEHOLDER.",
                    ),
                ),
                (
                    "prosperity_increase",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Prosperity points added on success (domain-target projects).",
                    ),
                ),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="improvement_details",
                        to="arxii.domain",
                    ),
                ),
                (
                    "holding",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = improves the domain's prosperity instead of one holding.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="improvement_details",
                        to="arxii.domainholding",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Domain improvement details"},
        ),
        migrations.CreateModel(
            name="FortificationUpgradeDetails",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="fortification_upgrade_details",
                        serialize=False,
                        to="arxii.project",
                    ),
                ),
                (
                    "target_level",
                    models.PositiveSmallIntegerField(
                        help_text="Fortification level this upgrade targets on completion.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the level was applied; NULL until the handler runs. Idempotency marker.",
                        null=True,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fortification_upgrade_details",
                        to="arxii.building",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Fortification upgrade details"},
        ),
        migrations.CreateModel(
            name="GangTurfDetails",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="gang_turf_details",
                        serialize=False,
                        to="arxii.project",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The gang organization exerting pressure.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gang_turf_projects",
                        to="arxii.organization",
                    ),
                ),
                (
                    "target_area",
                    models.ForeignKey(
                        blank=True,
                        help_text="IC flavor: the area under pressure. Not a control field this slice.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gang_turf_projects",
                        to="arxii.area",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="GangTurfTierThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "min_progress",
                    models.PositiveIntegerField(
                        help_text="Minimum progress at which this tier applies."
                    ),
                ),
                (
                    "outcome_tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gang_turf_thresholds",
                        to="arxii.checkoutcome",
                    ),
                ),
                (
                    "details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tier_thresholds",
                        to="arxii.gangturfdetails",
                    ),
                ),
            ],
            options={"ordering": ["-min_progress"]},
        ),
        migrations.CreateModel(
            name="InteriorDesignDetails",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="interior_design_details",
                        serialize=False,
                        to="arxii.project",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the polish was applied; NULL until the handler runs. Idempotency marker.",
                        null=True,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_details",
                        to="arxii.building",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target room; NULL = the whole building.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_details",
                        to="arxii.roomprofile",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="design_details",
                        to="arxii.projecttemplate",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Interior design details"},
        ),
        migrations.CreateModel(
            name="ItemRefinementDetails",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="item_refinement_details",
                        serialize=False,
                        to="arxii.project",
                    ),
                ),
                (
                    "accent_target",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Accent axis being raised/added; null = base quality.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refinement_projects",
                        to="arxii.modifiertarget",
                    ),
                ),
                (
                    "item_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refinement_projects",
                        to="arxii.iteminstance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropagandaDetails",
            fields=[
                (
                    "magnitude",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("very_high", "Very High"),
                        ],
                        default="small",
                        help_text="Renown magnitude passed to fire_renown_award.",
                        max_length=20,
                    ),
                ),
                (
                    "risk",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("extreme", "Extreme"),
                        ],
                        default="none",
                        help_text="Risk level for legend award; NONE means no legend granted.",
                        max_length=20,
                    ),
                ),
                (
                    "reach",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("local", "Local"),
                            ("regional", "Regional"),
                            ("continental", "Continental"),
                            ("world", "World"),
                        ],
                        help_text="Override reach; if null, derived from magnitude default.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="propaganda_details",
                        serialize=False,
                        to="arxii.project",
                    ),
                ),
                (
                    "campaign_name",
                    models.CharField(
                        help_text="Sponsor-authored campaign title; becomes the renown deed's title.",
                        max_length=200,
                    ),
                ),
                (
                    "renown_fired",
                    models.BooleanField(
                        default=False,
                        help_text="Set by the kind handler after fire_renown_award; guards re-fires.",
                    ),
                ),
                (
                    "source_tier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Provenance: the tier this campaign's config was copied from.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns",
                        to="arxii.propagandacampaigntier",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="RoomFeatureProgressionDetails",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="room_feature_progression_details",
                        serialize=False,
                        to="arxii.project",
                    ),
                ),
                (
                    "target_level",
                    models.PositiveSmallIntegerField(
                        help_text="The level this project aims to reach. Install → 1; upgrade → current+1 (or higher). Bounded by ``feature_kind.max_level`` at project-creation time.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "target_feature_kind",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="progression_projects",
                        to="arxii.roomfeaturekind",
                    ),
                ),
                (
                    "target_room_profile",
                    models.ForeignKey(
                        help_text="The room the feature will be installed in or upgraded.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feature_progression_projects",
                        to="arxii.roomprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WarFundingDetails",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="war_funding_details",
                        serialize=False,
                        to="arxii.project",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the handler runs; idempotency guard (claim-filter pattern).",
                        null=True,
                    ),
                ),
                (
                    "covenant",
                    models.ForeignKey(
                        help_text="The covenant whose military readiness this drive funds.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="war_funding_projects",
                        to="arxii.covenant",
                    ),
                ),
                (
                    "outcome_tier",
                    models.ForeignKey(
                        blank=True,
                        help_text="The graded outcome tier, set when the handler runs at deadline.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="war_funding_projects",
                        to="arxii.checkoutcome",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="WarFundingTierThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "min_progress",
                    models.PositiveIntegerField(
                        help_text="Minimum progress at which this tier applies."
                    ),
                ),
                (
                    "outcome_tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="war_funding_thresholds",
                        to="arxii.checkoutcome",
                    ),
                ),
                (
                    "details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tier_thresholds",
                        to="arxii.warfundingdetails",
                    ),
                ),
            ],
            options={"ordering": ["-min_progress"]},
        ),
    ]
