# Generated by Django 5.2.16 on 2026-09-06 00:50


from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

from core_management.batched_migration import BatchedCreateModelMigration
from world.migrations._generations import replaced_slice


class Migration(BatchedCreateModelMigration):
    dependencies = [
        ("arxii", "0025_g2_part_25"),
    ]

    replaces = replaced_slice(26, 103)
    operations = [
        migrations.CreateModel(
            name="NpcPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "valence",
                    models.CharField(
                        choices=[("likes", "Likes"), ("dislikes", "Dislikes")], max_length=10
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="npc_preferences",
                        to="arxii.persona",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holders",
                        to="arxii.personalitytrait",
                    ),
                ),
            ],
            options={
                "ordering": ["persona", "trait__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("persona", "trait"), name="unique_npc_preference_per_trait"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PersonaTraitDescriptor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="Free-text flavor for the trait (e.g. 'Robin's-egg', 'Crimson').",
                        max_length=120,
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        help_text="The presented face this descriptor belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trait_descriptors",
                        to="arxii.persona",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        help_text="The appearance trait this describes.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persona_descriptors",
                        to="arxii.formtrait",
                    ),
                ),
            ],
            options={
                "verbose_name": "Persona Trait Descriptor",
                "verbose_name_plural": "Persona Trait Descriptors",
                "ordering": ["persona", "trait"],
                "unique_together": {("persona", "trait")},
            },
        ),
        migrations.CreateModel(
            name="Petition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("unfair_death", "Unfair / Unjustified Death"),
                            ("scene_conduct", "Scene Turning OOC-Hostile"),
                            ("stuck_unplayable", "Character Stuck / Unplayable"),
                            ("other_emergency", "Other Emergency"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Short and specific — this is an emergency line.", max_length=1000
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("reviewed", "Reviewed"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("staff_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="petitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject_character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="petitions_about",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="petitions",
                        to="arxii.scene",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "open")),
                        fields=("account",),
                        name="one_open_petition_per_account",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("removed", "Removed"),
                            ("hidden", "Hidden"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        help_text="The room this place belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="places",
                        to="arxii.roomprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("room__isnull", False)),
                        fields=("room", "name"),
                        name="unique_place_per_room",
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "ante",
                    models.PositiveIntegerField(
                        help_text="Fixed ante every seat pays to join, in coppers."
                    ),
                ),
                (
                    "pot",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Coppers currently escrowed at the table (sum of unrefunded antes).",
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "opened_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opened_tavern_game_sessions",
                        to="arxii.persona",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tavern_game_sessions",
                        to="arxii.place",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="arxii.taverngame",
                    ),
                ),
            ],
            options={"ordering": ["-opened_at"]},
        ),
        migrations.CreateModel(
            name="GameSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ante_paid", models.PositiveIntegerField()),
                ("roll_result", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("seated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tavern_game_seats",
                        to="arxii.persona",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="arxii.gamesession",
                    ),
                ),
            ],
            options={
                "ordering": ["seated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "persona"), name="unique_seat_per_session_persona"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="The actual written text of the interaction"),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("pose", "Pose"),
                            ("emit", "Emit"),
                            ("say", "Say"),
                            ("whisper", "Whisper"),
                            ("mutter", "Mutter"),
                            ("shout", "Shout"),
                            ("action", "Action"),
                            ("outcome", "Outcome"),
                        ],
                        default="pose",
                        help_text="The type of IC interaction",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("perceived_only", "Perceived Only"),
                            ("very_private", "Very Private"),
                        ],
                        default="default",
                        help_text="Privacy override — can only escalate, never reduce",
                        max_length=20,
                    ),
                ),
                (
                    "pose_kind",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("entry", "Entry"),
                            ("departure", "Departure"),
                        ],
                        db_index=True,
                        default="standard",
                        help_text="Classifies the pose as standard, entry, or departure. Set by the +enter command (future) or scene-entry hook. Spec C reads ENTRY to filter scene-entry-endorsement targets.",
                        max_length=16,
                    ),
                ),
                (
                    "vote_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of weekly votes (nominations for Memorable Poses)",
                    ),
                ),
                (
                    "strain_committed",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Canonical post-resolution audit of strain the player actually committed for this action. Populated for both clash and non-clash.",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "attributed_companion",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cosmetic pose attribution (#3294): when set, the feed renders this bonded companion as the visible actor with an owner tell, e.g. a wolfhound's growl attributed to the wolfhound. Authorship — block/mute/consent/moderation — stays entirely on `persona`, which is always the companion's OWNER; this field is never a substitute writer and never affects visibility filtering.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.companion",
                    ),
                ),
                (
                    "fury_committed",
                    models.ForeignKey(
                        blank=True,
                        help_text="Post-resolution audit of the realized Fury tier (clash + non-clash).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.furytier",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        help_text="How the writer appeared at this moment. Always set — every interaction has a persona, even if it's just the character's primary persona.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interactions_written",
                        to="arxii.persona",
                    ),
                ),
                (
                    "writer_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="The account that wrote this, pinned at creation (#1219). Party identity for private-content log visibility — stable across persona hand-offs, so an inheriting player is never treated as a party to the prior player's whispers.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        help_text="Spoken language; null = universal/untagged (poses, emits, pre-#2993 rows).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="arxii.language",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sub-location where this interaction occurred",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interactions",
                        to="arxii.place",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        help_text="Scene container if one was active",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interactions",
                        to="arxii.scene",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("vote_count__gte", 0)),
                        name="interaction_vote_count_nonnegative",
                    )
                ],
                "indexes": [
                    models.Index(
                        fields=["persona", "timestamp"], name="arxii_inter_persona_71209a_idx"
                    ),
                    models.Index(
                        fields=["scene", "timestamp"], name="arxii_inter_scene_i_74acef_idx"
                    ),
                    models.Index(
                        condition=models.Q(("visibility", "very_private")),
                        fields=["timestamp"],
                        name="interaction_very_private_idx",
                    ),
                    models.Index(
                        condition=models.Q(("scene__isnull", True)),
                        fields=["timestamp"],
                        name="interaction_no_scene_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ClassLevelAdvancement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "level_before",
                    models.PositiveSmallIntegerField(
                        help_text="Character level immediately before the crossing."
                    ),
                ),
                (
                    "level_after",
                    models.PositiveSmallIntegerField(
                        help_text="Character level granted by the crossing."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="durance_advancements",
                        to="arxii.characterclass",
                    ),
                ),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_level_advancements",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "officiant",
                    models.ForeignKey(
                        blank=True,
                        help_text="The trainer who inducted this advance (PC or academy NPC).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="officiated_advancements",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "witnesses",
                    models.ManyToManyField(
                        blank=True, related_name="witnessed_advancements", to="arxii.persona"
                    ),
                ),
                (
                    "declaration_interaction",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The declaration pose. Soft FK — partitioned table.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.interaction",
                    ),
                ),
                (
                    "ritual",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="class_level_advancements",
                        to="arxii.ritual",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.scene",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class Level Advancement",
                "verbose_name_plural": "Class Level Advancements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DramaticMomentTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "interaction_timestamp",
                    models.DateTimeField(
                        blank=True,
                        help_text="Denormalized from interaction.timestamp for the partitioned-table composite FK.",
                        null=True,
                    ),
                ),
                ("tagged_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dramatic_moment_tags",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "tagged_by",
                    models.ForeignKey(
                        help_text="Account that tagged this moment. PROTECT because provenance must be kept.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dramatic_moment_tags_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "moment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tags",
                        to="arxii.dramaticmomenttype",
                    ),
                ),
                (
                    "interaction",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The pose that earned this moment; nullable for non-pose tags.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dramatic_moment_tags",
                        to="arxii.interaction",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        help_text="Scene context; nullable for resilience to scene cleanup.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dramatic_moment_tags",
                        to="arxii.scene",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["character_sheet", "tagged_at"], name="dramatic_tag_sheet_time_idx"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="InteractionAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ordering",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Display order within the pose (low values render first).",
                    ),
                ),
                (
                    "action_interaction",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="The ACTION Interaction being elaborated.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pose_links",
                        to="arxii.interaction",
                    ),
                ),
                (
                    "pose",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="The POSE Interaction that elaborates the action(s).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_links",
                        to="arxii.interaction",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pose", "action_interaction"), name="unique_action_link_per_pose"
                    )
                ],
                "indexes": [
                    models.Index(
                        fields=["pose", "ordering"], name="arxii_inter_pose_id_495983_idx"
                    ),
                    models.Index(
                        fields=["action_interaction"], name="arxii_inter_action__1f107b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InteractionFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="Denormalized from interaction — required for composite FK with partitioned table"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interaction",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="The bookmarked interaction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="arxii.interaction",
                    ),
                ),
                (
                    "roster_entry",
                    models.ForeignKey(
                        help_text="The player who bookmarked this",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_interactions",
                        to="arxii.rosterentry",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("interaction", "roster_entry"),
                        name="unique_favorite_per_interaction",
                    )
                ]
            },
        ),
    ]
