# Generated by Django 5.2.15 on 2026-08-04 07:42

from decimal import Decimal

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0028_initial_part_28"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengeTemplateProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.PositiveIntegerField(default=1)),
                (
                    "challenge_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_template_properties",
                        to="arxii.challengetemplate",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_template_properties",
                        to="arxii.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharacterAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "earned_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this achievement was earned"
                    ),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        help_text="The achievement that was earned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_achievements",
                        to="arxii.achievement",
                    ),
                ),
                (
                    "character_sheet",
                    models.ForeignKey(
                        help_text="The character who earned this achievement",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "discovery",
                    models.ForeignKey(
                        blank=True,
                        help_text="The discovery record if this character was among the first to find it",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discoverers",
                        to="arxii.discovery",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharacterAnima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "current",
                    models.PositiveIntegerField(default=10, help_text="Current anima available."),
                ),
                (
                    "maximum",
                    models.PositiveIntegerField(default=10, help_text="Maximum anima capacity."),
                ),
                (
                    "last_recovery",
                    models.DateTimeField(
                        blank=True,
                        help_text="When anima was last recovered through ritual.",
                        null=True,
                    ),
                ),
                (
                    "pre_audere_maximum",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Stored maximum before Audere expanded the pool. Null when not in Audere.",
                        null=True,
                    ),
                ),
                (
                    "glut",
                    models.PositiveIntegerField(
                        default=0, help_text="Decaying overfill from feeding past maximum (#2853)."
                    ),
                ),
                (
                    "character",
                    models.OneToOneField(
                        help_text="The character this anima belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anima",
                        to="arxii.charactersheet",
                    ),
                ),
            ],
            options={"verbose_name": "Character Anima", "verbose_name_plural": "Character Anima"},
        ),
        migrations.CreateModel(
            name="CharacterAura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "celestial",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage of Celestial affinity (0-100).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "primal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("80.00"),
                        help_text="Percentage of Primal affinity (0-100).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "abyssal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        help_text="Percentage of Abyssal affinity (0-100).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "glimpse_story",
                    models.TextField(
                        blank=True,
                        help_text="Narrative of the character's first magical awakening (The Glimpse).",
                    ),
                ),
                (
                    "glimpse_state",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not started"),
                            ("TAGS_ONLY", "Tags chosen, story unwritten"),
                            ("COMPLETE", "Complete"),
                        ],
                        default="NOT_STARTED",
                        help_text="Deferral/progress state of the Glimpse (#2427). Cache of prose+tag truth — maintained by world.magic.services.glimpse, never written directly.",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.OneToOneField(
                        help_text="The character this aura belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aura",
                        to="arxii.charactersheet",
                    ),
                ),
            ],
            options={"verbose_name": "Character Aura", "verbose_name_plural": "Character Auras"},
        ),
        migrations.CreateModel(
            name="CharacterChallengeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("resolved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_records",
                        to="arxii.challengeapproach",
                    ),
                ),
                (
                    "challenge_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_records",
                        to="arxii.challengeinstance",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_records",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "outcome",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="challenge_records",
                        to="arxii.checkoutcome",
                    ),
                ),
                (
                    "consequence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="challenge_records",
                        to="arxii.consequence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsequenceOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("modifier_total", models.IntegerField(default=0)),
                ("summary", models.CharField(blank=True, max_length=255)),
                (
                    "combat_interaction_timestamp",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Denormalized from combat_interaction.timestamp. Required because scenes_interaction is range-partitioned by timestamp. No DB-level composite FK constraint is enforced — integrity is maintained by the writer setting both columns atomically.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge_record",
                    models.ForeignKey(
                        blank=True,
                        help_text="The CharacterChallengeRecord this outcome was resolved for. Null for combat-based resolutions.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consequence_outcomes",
                        to="arxii.characterchallengerecord",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consequence_outcomes",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "check_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consequence_outcomes",
                        to="arxii.checktype",
                    ),
                ),
                (
                    "selected_consequence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consequence_outcomes",
                        to="arxii.consequence",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        blank=True,
                        help_text="The ConsequencePool used for roulette selection. Null for plain (non-template) challenge resolutions whose roulette is reconstructed on read from the authored consequence links rather than persisted as a derived pool.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consequence_outcomes",
                        to="arxii.consequencepool",
                    ),
                ),
                (
                    "combat_interaction",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The Interaction created when this outcome was resolved via combat. Null for challenge-based resolutions.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consequence_outcomes",
                        to="arxii.interaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsequenceOutcomeModifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("condition", "Condition"),
                            ("rollmod", "Roll Modifier"),
                            ("scene", "Surroundings"),
                            ("equipment", "Equipment"),
                            ("fashion", "Fashion"),
                            ("character", "Character"),
                            ("effort", "Effort"),
                            ("fatigue", "Fatigue"),
                            ("strain", "Strain"),
                            ("affinity", "Affinity"),
                            ("pull", "Combat Pull"),
                            ("relationship", "Relationship"),
                            ("capability", "Capability"),
                            ("soulfray", "Soulfray"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_label", models.CharField(max_length=120)),
                ("value", models.IntegerField()),
                (
                    "outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifiers",
                        to="arxii.consequenceoutcome",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="CharacterClassLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Current level in this class (1-30)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Whether this is the character's primary class"
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_class_levels",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "character_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_assignments",
                        to="arxii.characterclass",
                    ),
                ),
            ],
            options={"ordering": ["character", "-is_primary", "-level", "character_class__name"]},
        ),
        migrations.CreateModel(
            name="CharacterCovenantRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "engaged",
                    models.BooleanField(
                        default=False,
                        help_text="True when the character is currently 'fulfilling' this role for this covenant. At most one engaged active row per (character_sheet, covenant.covenant_type) — service-enforced + clean()-enforced. Drives role bonuses (modifier pipeline) and COVENANT_ROLE Thread pull eligibility. See spec 2026-05-09 §3.6.",
                    ),
                ),
                (
                    "is_secondary",
                    models.BooleanField(
                        default=False,
                        help_text="Marks an engaged SECONDARY vow membership (#2641). Chassis layers (combat-identity blend, defense/gear/stat scaling) never read secondary memberships — only technique specialty and situational perks do, scaled by SecondaryVowConfig.potency_tenths. Distinct from the anchor-vs-sub-role 'primary role' sense (see the covenants glossary's 'Secondary Vow' entry).",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="covenant_role_assignments",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "covenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="arxii.covenant",
                    ),
                ),
                (
                    "rank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="arxii.covenantrank",
                    ),
                ),
                (
                    "covenant_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="character_assignments",
                        to="arxii.covenantrole",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CharacterDistinction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Current rank of this distinction (1 for binary distinctions).",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Player notes about this distinction.", max_length=280
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("character_creation", "Character Creation"),
                            ("gameplay", "Gameplay"),
                            ("gm_award", "GM Award"),
                            ("achievement_auto_grant", "Achievement"),
                            ("consequence_pool", "Consequence"),
                            ("endorsement_threshold", "Endorsement Threshold"),
                            ("species", "Species"),
                            ("unlock_purchase", "Unlock Purchase"),
                        ],
                        default="character_creation",
                        help_text="How this character acquired the distinction.",
                        max_length=30,
                    ),
                ),
                (
                    "is_temporary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this distinction is temporary (e.g., magical effect).",
                    ),
                ),
                (
                    "source_description",
                    models.TextField(
                        blank=True,
                        help_text="Description of how the distinction was acquired (for gameplay).",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this distinction was granted."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this distinction was last modified."
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        help_text="The character sheet this distinction belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distinctions",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "from_glimpse",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Glimpse (aura) this distinction was born in; null = no glimpse link.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="glimpse_born_distinctions",
                        to="arxii.characteraura",
                    ),
                ),
                (
                    "distinction",
                    models.ForeignKey(
                        help_text="The distinction granted to this character.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="character_grants",
                        to="arxii.distinction",
                    ),
                ),
                (
                    "secret",
                    models.OneToOneField(
                        blank=True,
                        help_text="The Secret this distinction was relocated into; null = publicly visible.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="distinction",
                        to="arxii.secret",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Distinction",
                "verbose_name_plural": "Character Distinctions",
            },
        ),
        migrations.CreateModel(
            name="SheetUpdateRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("distinction_add", "Add Distinction"),
                            ("distinction_remove", "Remove Distinction"),
                        ],
                        help_text="What kind of sheet update this request represents.",
                        max_length=20,
                    ),
                ),
                (
                    "rank",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Target rank for ADD (absolute, not a delta — a rank-up authorization for an existing holder sets this above the current rank). Ignored for REMOVE.",
                    ),
                ),
                (
                    "justification",
                    models.TextField(help_text="Player's narrative justification for this change."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        help_text="Lifecycle state of this request.",
                        max_length=10,
                    ),
                ),
                (
                    "xp_cost",
                    models.PositiveIntegerField(
                        help_text="XP cost computed at submission time. 0 for free transactions."
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("character_creation", "Character Creation"),
                            ("gameplay", "Gameplay"),
                            ("gm_award", "GM Award"),
                            ("achievement_auto_grant", "Achievement"),
                            ("consequence_pool", "Consequence"),
                            ("endorsement_threshold", "Endorsement Threshold"),
                            ("species", "Species"),
                            ("unlock_purchase", "Unlock Purchase"),
                        ],
                        default="unlock_purchase",
                        help_text="First-acquisition provenance passed to grant_distinction at approval.",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "character_sheet",
                    models.ForeignKey(
                        help_text="The character requesting the change.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sheet_update_requests",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The GM who approved or denied this request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_sheet_update_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The account that submitted this request. The player's own account for player-initiated; the GM's account for GM-direct.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_sheet_update_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_character_distinction",
                    models.ForeignKey(
                        blank=True,
                        help_text="The CharacterDistinction to remove (set for DISTINCTION_REMOVE only). Null after the distinction is deleted — the request row survives as a receipt.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remove_sheet_update_requests",
                        to="arxii.characterdistinction",
                    ),
                ),
                (
                    "target_distinction",
                    models.ForeignKey(
                        blank=True,
                        help_text="The distinction to add (set for DISTINCTION_ADD only).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="add_sheet_update_requests",
                        to="arxii.distinction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sheet Update Request",
                "verbose_name_plural": "Sheet Update Requests",
            },
        ),
        migrations.CreateModel(
            name="DistinctionChangeRequestDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="A distinctions.SheetUpdateRequestType value (distinction_add/distinction_remove).",
                        max_length=20,
                    ),
                ),
                (
                    "character_distinction",
                    models.ForeignKey(
                        blank=True,
                        help_text="The held distinction to remove (DISTINCTION_REMOVE only; nulls after deletion).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="table_update_request_details",
                        to="arxii.characterdistinction",
                    ),
                ),
                (
                    "distinction",
                    models.ForeignKey(
                        blank=True,
                        help_text="The distinction to add/rank up (DISTINCTION_ADD only).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="table_update_request_details",
                        to="arxii.distinction",
                    ),
                ),
                (
                    "sheet_update_request",
                    models.ForeignKey(
                        blank=True,
                        help_text="The #2628 request created-and-approved at table sign-off.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="table_update_request_details",
                        to="arxii.sheetupdaterequest",
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distinction_details",
                        to="arxii.tableupdaterequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distinction Change Request Details",
                "verbose_name_plural": "Distinction Change Request Details",
            },
        ),
        migrations.CreateModel(
            name="CharacterDistinctionOther",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "freeform_text",
                    models.CharField(
                        help_text="What the player entered as their 'Other' value.", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending Review"),
                            ("approved", "Approved"),
                            ("mapped", "Mapped to Distinction"),
                        ],
                        default="pending_review",
                        help_text="Current status of this 'Other' entry.",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this entry was created."
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        help_text="The character sheet that entered this 'Other' distinction.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distinction_other_entries",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "parent_distinction",
                    models.ForeignKey(
                        help_text="The variant parent distinction this 'Other' belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_entries",
                        to="arxii.distinction",
                    ),
                ),
                (
                    "staff_mapped_distinction",
                    models.ForeignKey(
                        blank=True,
                        help_text="The distinction this was mapped to by staff.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mapped_from_other",
                        to="arxii.distinction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Distinction Other Entry",
                "verbose_name_plural": "Character Distinction Other Entries",
            },
        ),
        migrations.CreateModel(
            name="CharacterDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "current_stage",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Origin"),
                            (2, "Heritage"),
                            (3, "Lineage"),
                            (4, "Distinctions"),
                            (5, "Path"),
                            (6, "Gift"),
                            (7, "Attributes & Skills"),
                            (8, "Appearance"),
                            (9, "Identity"),
                            (10, "Final Touches"),
                            (11, "Review"),
                        ],
                        default=1,
                        help_text="Current stage in character creation flow",
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Character age in years (18-65)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(18),
                            django.core.validators.MaxValueValidator(65),
                        ],
                    ),
                ),
                (
                    "birthday_month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Month (1-12) of the celebrated birthday / waking day.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "birthday_day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Day of month of the celebrated birthday / waking day.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "defer_parents",
                    models.BooleanField(
                        default=False,
                        help_text="CG deferral (#2062): leave parents deliberately undefined, to be filled later through review.",
                    ),
                ),
                (
                    "height_inches",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Exact height in inches within the selected band",
                        null=True,
                    ),
                ),
                (
                    "draft_data",
                    models.JSONField(
                        default=dict, help_text="Staged data: stats, skills, traits, identity, etc."
                    ),
                ),
                (
                    "is_gm_creation",
                    models.BooleanField(
                        default=False,
                        help_text="GM is designing a roster character, not playing one.",
                    ),
                ),
                (
                    "story_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Title for the Story created at finalize (GM drafts only).",
                        max_length=200,
                    ),
                ),
                (
                    "story_description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description for the Story created at finalize (GM drafts only).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Account creating this character",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "build",
                    models.ForeignKey(
                        blank=True,
                        help_text="Selected build type",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drafts",
                        to="arxii.build",
                    ),
                ),
                (
                    "selected_beginnings",
                    models.ForeignKey(
                        blank=True,
                        help_text="Selected beginnings path",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drafts",
                        to="arxii.beginnings",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        blank=True,
                        help_text="Selected family (null for orphan or special heritage).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="character_drafts",
                        to="arxii.family",
                    ),
                ),
                (
                    "selected_gender",
                    models.ForeignKey(
                        blank=True,
                        help_text="Selected gender",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drafts",
                        to="arxii.gender",
                    ),
                ),
                (
                    "target_table",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which GM table the finalized character will belong to. Required at finalize for GM drafts.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="draft_characters",
                        to="arxii.gmtable",
                    ),
                ),
                (
                    "height_band",
                    models.ForeignKey(
                        blank=True,
                        help_text="Selected height band for CG",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drafts",
                        to="arxii.heightband",
                    ),
                ),
                (
                    "claimed_kin_pool",
                    models.ForeignKey(
                        blank=True,
                        help_text="Slot pool a node is minted from at finalization.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drafts",
                        to="arxii.kinslotpool",
                    ),
                ),
                (
                    "claimed_kin_slot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Appable kinship node this character claims at finalization.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drafts",
                        to="arxii.kinsperson",
                    ),
                ),
                (
                    "selected_path",
                    models.ForeignKey(
                        blank=True,
                        help_text="Selected starting path (Prospect stage only)",
                        limit_choices_to={"is_active": True, "stage": 1},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drafts",
                        to="arxii.path",
                    ),
                ),
                (
                    "second_parent_species",
                    models.ForeignKey(
                        blank=True,
                        help_text="Species of the invented non-dominant parent when cross-species (#2815).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.species",
                    ),
                ),
                (
                    "selected_species",
                    models.ForeignKey(
                        blank=True,
                        help_text="Selected species",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drafts",
                        to="arxii.species",
                    ),
                ),
                (
                    "selected_area",
                    models.ForeignKey(
                        blank=True,
                        help_text="Selected starting area",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drafts",
                        to="arxii.startingarea",
                    ),
                ),
                (
                    "selected_tradition",
                    models.ForeignKey(
                        blank=True,
                        help_text="Selected magical tradition (gates magic template).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.tradition",
                    ),
                ),
                (
                    "public_worship",
                    models.ForeignKey(
                        blank=True,
                        help_text="The being this character publicly worships (optional).",
                        limit_choices_to={"is_active": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.worshippedbeing",
                    ),
                ),
                (
                    "secret_worship",
                    models.ForeignKey(
                        blank=True,
                        help_text="The being this character SECRETLY worships — the public faith is a front; finalization mints a Secret.",
                        limit_choices_to={"is_active": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.worshippedbeing",
                    ),
                ),
            ],
            options={"verbose_name": "Character Draft", "verbose_name_plural": "Character Drafts"},
        ),
        migrations.CreateModel(
            name="DraftApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "character_name",
                    models.CharField(
                        blank=True,
                        help_text="Character name populated at approval time (survives draft deletion).",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("in_review", "In Review"),
                            ("revisions_requested", "Revisions Requested"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="submitted",
                        max_length=30,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "submission_notes",
                    models.TextField(
                        blank=True, help_text="Player's notes about the character submission."
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set on deny/withdraw for soft-delete grace period.",
                        null=True,
                    ),
                ),
                (
                    "draft",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application",
                        to="arxii.characterdraft",
                    ),
                ),
                (
                    "player_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="The player who submitted this application (survives draft deletion).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claimed_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_via",
                    models.ForeignKey(
                        blank=True,
                        help_text="If the applicant arrived via a game invite, the invite that brought them. Set by annotate_application() during submission.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to="arxii.gameinvite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Draft Application",
                "verbose_name_plural": "Draft Applications",
            },
        ),
        migrations.CreateModel(
            name="DraftApplicationComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.TextField()),
                (
                    "comment_type",
                    models.CharField(
                        choices=[("message", "Message"), ("status_change", "Status Change")],
                        default="message",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="arxii.draftapplication",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for system-generated status change events.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Comment",
                "verbose_name_plural": "Application Comments",
                "ordering": ["created_at"],
            },
        ),
    ]
