# Generated by Django 5.2.16 on 2026-09-05 23:20


import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

import core.mixins
import core.natural_keys
from core_management.batched_migration import BatchedCreateModelMigration
from world.migrations._generations import replaced_slice


class Migration(BatchedCreateModelMigration):
    dependencies = [
        ("arxii", "0034_g2_part_34"),
    ]

    replaces = replaced_slice(35, 103)
    operations = [
        migrations.CreateModel(
            name="StakeContractActivation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("locked_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("party_average_level", models.PositiveIntegerField()),
                (
                    "declared_target_level",
                    models.PositiveIntegerField(
                        default=0, help_text="Beat.target_level snapshot at activation (0 = unset)."
                    ),
                ),
                (
                    "declared_risk",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("extreme", "Extreme"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "effective_risk",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("extreme", "Extreme"),
                        ],
                        help_text="What Legend actually pays on — see compute_effective_risk.",
                        max_length=10,
                    ),
                ),
                (
                    "is_ready",
                    models.BooleanField(
                        help_text="Readiness verdict at activation; False forced effective NONE."
                    ),
                ),
                ("readiness_notes", models.TextField(blank=True, default="")),
                (
                    "beat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stake_activations",
                        to="arxii.beat",
                    ),
                ),
            ],
            options={
                "ordering": ["-locked_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("resolved_at__isnull", True)),
                        fields=("beat",),
                        name="unique_open_activation_per_beat",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LegendContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "success_level",
                    models.SmallIntegerField(
                        help_text="The check's success_level (-10 to +10). SERVER-ONLY — never serialize."
                    ),
                ),
                (
                    "was_crucial",
                    models.BooleanField(
                        default=False,
                        help_text="Derived at write time from the served stake's severity, never authored per row. Crucial contributions carry the standout pass.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character_sheet",
                    models.ForeignKey(
                        help_text="Who acted.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legend_contributions",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "check_type",
                    models.ForeignKey(
                        help_text="What kind of thing they did.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legend_contributions",
                        to="arxii.checktype",
                    ),
                ),
                (
                    "stake",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which objective this served; null when the act served the beat at large.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legend_contributions",
                        to="arxii.stake",
                    ),
                ),
                (
                    "activation",
                    models.ForeignKey(
                        help_text="The staked unit being settled; the contribution dies with it.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legend_contributions",
                        to="arxii.stakecontractactivation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legend Contribution",
                "verbose_name_plural": "Legend Contributions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["activation", "character_sheet"],
                        name="legendcontrib_activation_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StakeResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "column",
                    models.CharField(
                        choices=[("win", "Win"), ("loss", "Loss"), ("withdrawal", "Withdrawal")],
                        max_length=12,
                    ),
                ),
                (
                    "outcome_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Short designer-authored slug naming this branch within its column's polarity (#1760) — e.g. 'destroyed', 'captured', 'given_to_allies'. Blank = the column's single default branch (backward compatible with pre-#1760 content). column stays the coarse WIN/LOSS/WITHDRAWAL polarity every severity/reward/machine-grading rule keys off; outcome_key is a finer dimension within it, not a replacement axis.",
                        max_length=40,
                    ),
                ),
                (
                    "escalates_to_risk",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("extreme", "Extreme"),
                        ],
                        default="",
                        help_text="The risk tier the situation spawned by this branch carries — the fuse mechanic. Blank = no escalation declared.",
                        max_length=10,
                    ),
                ),
                (
                    "narrative_summary",
                    models.TextField(
                        blank=True,
                        help_text="What happens in the story when this branch fires (GM-authored).",
                    ),
                ),
                (
                    "forfeits_subject_item",
                    models.BooleanField(
                        default=False,
                        help_text="On fire, soft-forfeit the stake's subject_item (ITEM stakes only).",
                    ),
                ),
                (
                    "subject_standing_delta",
                    models.SmallIntegerField(
                        default=0,
                        help_text="On fire, adjust standing between the stake's subject and each participant persona (#1760). NPC_FATE: adjusts NPCStanding via subject_sheet's primary persona (unchanged pre-#1760 behavior). FACTION: adjusts SocietyReputation or OrganizationReputation (whichever of subject_society/subject_organization is set) — previously a dead FK (subject_society/subject_organization were never read); this is the fix.",
                    ),
                ),
                (
                    "npc_regard_delta",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Pre-authored NpcRegard delta applied on resolution, when stake.subject_kind is NPC_FATE (#2039). Fires via record_npc_regard_event, citing this row.",
                    ),
                ),
                (
                    "sets_subject_lifecycle",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ALIVE", "Alive"),
                            ("CAPTURED", "Captured"),
                            ("UNKNOWN", "Whereabouts unknown"),
                            ("COMA", "Coma"),
                            ("RETIRED", "Retired"),
                            ("DEAD", "Dead"),
                        ],
                        default="",
                        help_text="On fire, set_lifecycle_state(subject_sheet, value). NPC_FATE only, and only when the subject sheet is not player-held (pillar 12).",
                        max_length=10,
                    ),
                ),
                (
                    "machine_match_lifecycle_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ALIVE", "Alive"),
                            ("CAPTURED", "Captured"),
                            ("UNKNOWN", "Whereabouts unknown"),
                            ("COMA", "Coma"),
                            ("RETIRED", "Retired"),
                            ("DEAD", "Dead"),
                        ],
                        default="",
                        help_text="On automatic (machine) grading, if the stake's subject_sheet's actual lifecycle_state equals this value, THIS branch is selected over the column's plain default (#1760, generalizing the old is-dead-only override to the full LifecycleState ladder: ALIVE/CAPTURED/COMA/RETIRED/DEAD). NPC_FATE stakes only; blank means no machine-match, so the branch keyed to the completion's outcome_key resolves, else the plain column default (#3561: never a GM pick).",
                        max_length=10,
                    ),
                ),
                (
                    "transitions_subject_asset",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="On fire, transition the stake's subject_asset to this AssetStatus (COMPROMISED/LOST/DISMISSED). ASSET stakes only — blank means no direct asset transition (use the consequence_pool for check-gated transitions instead). Mirrors sets_subject_lifecycle for NPC_FATE stakes.",
                        max_length=20,
                    ),
                ),
                (
                    "consequence_pool",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pool to fire when this column resolves (tier-aware).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.consequencepool",
                    ),
                ),
                (
                    "stake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolutions",
                        to="arxii.stake",
                    ),
                ),
            ],
            options={
                "ordering": ["stake", "column", "outcome_key"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("stake", "column", "outcome_key"),
                        name="unique_resolution_per_stake_column_outcome_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StakeOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "column",
                    models.CharField(
                        choices=[("win", "Win"), ("loss", "Loss"), ("withdrawal", "Withdrawal")],
                        max_length=12,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("machine", "Machine")],
                        help_text="Always MACHINE (#3561 retired the GM constrained pick).",
                        max_length=12,
                    ),
                ),
                (
                    "gm_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Historical audit field from before #3561 retired the GM constrained pick: the deciding GM's notes, on rows resolved that way. Always blank on rows resolved since.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which locked contract this outcome resolved under (audit).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stake_outcomes",
                        to="arxii.stakecontractactivation",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Historical audit field from before #3561 retired the GM constrained pick: the GM who picked the column, on rows resolved that way. Always null on rows resolved since.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stake_outcomes",
                        to="arxii.gmprofile",
                    ),
                ),
                (
                    "stake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcomes",
                        to="arxii.stake",
                    ),
                ),
                (
                    "resolution",
                    models.ForeignKey(
                        blank=True,
                        help_text="The authored branch that fired; null = no branch authored for the column.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.stakeresolution",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
                "constraints": [
                    models.UniqueConstraint(fields=("stake",), name="unique_outcome_per_stake")
                ],
            },
        ),
        migrations.CreateModel(
            name="StakesEscalationModifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "stakes_level",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("regional", "Regional"),
                            ("national", "National"),
                            ("continental", "Continental"),
                            ("world", "World"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "intensity_step_bonus",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Added to the curve's intensity_step during each escalation tick.",
                    ),
                ),
                (
                    "initial_surge",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="HIGH_STAKES-kind surge amount granted once to every ACTIVE PC participant. 0 = no initial surge.",
                    ),
                ),
                (
                    "default_curve",
                    models.ForeignKey(
                        blank=True,
                        help_text="Curve auto-assigned at encounter creation when the encounter's escalation_curve is null and its stakes_level matches this row.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.escalationcurve",
                    ),
                ),
            ],
            options={"ordering": ["stakes_level"]},
        ),
        migrations.CreateModel(
            name="StandingDeclaration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("favor", "Favor"), ("disfavor", "Disfavor")],
                        help_text="Whether this declaration pushed standing toward favor or disfavor.",
                        max_length=16,
                    ),
                ),
                (
                    "delta_applied",
                    models.IntegerField(
                        help_text="The clamped delta actually applied via bump_organization_reputation."
                    ),
                ),
                (
                    "citation",
                    models.TextField(
                        help_text="The leader's public citation — why this declaration was made."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "declared_by_persona",
                    models.ForeignKey(
                        help_text="The leader persona who made the declaration.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standing_declarations_made",
                        to="arxii.persona",
                    ),
                ),
                (
                    "game_week",
                    models.ForeignKey(
                        help_text="IC week this declaration was made in — backs the per-(org, target) rate limit.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="standing_declarations",
                        to="arxii.gameweek",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The organization whose standing with the target moved.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standing_declarations",
                        to="arxii.organization",
                    ),
                ),
                (
                    "target_persona",
                    models.ForeignKey(
                        help_text="The persona declared favored or disfavored.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standing_declarations_received",
                        to="arxii.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Standing Declaration",
                "verbose_name_plural": "Standing Declarations",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "target_persona", "game_week"),
                        name="unique_standing_declaration_per_org_target_week",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StartingArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "written_on",
                    models.DateField(
                        blank=True, help_text="Date the prose was written.", null=True
                    ),
                ),
                (
                    "reviewed_on",
                    models.DateField(
                        blank=True, help_text="Date the prose was reviewed.", null=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the starting area (e.g., 'Arx')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Rich description shown on hover/click in character creation"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this area can be selected in character creation",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order in selection UI (lower = first)"
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("all", "All Players"),
                            ("trust_required", "Trust Required"),
                            ("staff_only", "Staff Only"),
                        ],
                        default="all",
                        help_text="Who can select this area in character creation",
                        max_length=20,
                    ),
                ),
                (
                    "minimum_trust",
                    models.IntegerField(
                        default=0,
                        help_text="Minimum trust required when access_level is 'trust_required'",
                    ),
                ),
                (
                    "grants_residence_tenancy",
                    models.BooleanField(
                        default=True,
                        help_text="Whether finalizing a character here grants a LocationTenancy at the starting room (#2036) — auto-defaulting current_residence via maybe_default_residence, so the daily residence-trickle gate is reachable with zero manual player step. An authored per-area toggle: not every starting area need be residence-backed (e.g. a staff testing area with no real dorm room).",
                    ),
                ),
                (
                    "crest_art",
                    models.ForeignKey(
                        blank=True,
                        help_text="Crest/flag art for this area. Leave unset for gradient placeholder.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="starting_area_crests",
                        to="arxii.media",
                    ),
                ),
                (
                    "default_starting_room",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default room (via its RoomProfile) where characters from this area start. A staff config gap if unset — get_starting_room() falls back to the canonical seeded room (#2121).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="starting_area_default",
                        to="arxii.roomprofile",
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        blank=True,
                        help_text="Canonical realm/area referenced by this StartingArea (realms app).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="starting_areas",
                        to="arxii.realm",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who reviewed this row's prose, if anyone. Distinct from writing it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.contentcontributor",
                    ),
                ),
                (
                    "written_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who wrote this row's prose. Null means it is still a placeholder.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.contentcontributor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Starting Area",
                "verbose_name_plural": "Starting Areas",
                "ordering": ["sort_order", "name"],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Beginnings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "written_on",
                    models.DateField(
                        blank=True, help_text="Date the prose was written.", null=True
                    ),
                ),
                (
                    "reviewed_on",
                    models.DateField(
                        blank=True, help_text="Date the prose was reviewed.", null=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'Sleeper', 'Noble Birth')", max_length=100
                    ),
                ),
                ("description", models.TextField(help_text="Worldbuilding text shown to players")),
                (
                    "trust_required",
                    models.IntegerField(
                        default=0,
                        help_text="Minimum trust level required to see/select this option",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Staff toggle to enable/disable this option"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order in selection UI (lower = first)"
                    ),
                ),
                (
                    "grants_species_languages",
                    models.BooleanField(
                        default=True,
                        help_text="If False, characters don't get species' racial language (Misbegotten)",
                    ),
                ),
                (
                    "social_rank",
                    models.IntegerField(
                        default=0,
                        help_text="Staff-only rank for determining noble/commoner/royal (not exposed to players)",
                    ),
                ),
                (
                    "cg_point_cost",
                    models.IntegerField(
                        default=0,
                        help_text="CG point cost for this beginning; summed with species gift grant costs into the character-creation points budget.",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who reviewed this row's prose, if anyone. Distinct from writing it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.contentcontributor",
                    ),
                ),
                (
                    "written_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who wrote this row's prose. Null means it is still a placeholder.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.contentcontributor",
                    ),
                ),
                (
                    "heritage",
                    models.ForeignKey(
                        blank=True,
                        help_text="Heritage type for characters with this beginning (e.g., Sleeper, Misbegotten). Null defaults to 'Normal' heritage at finalization.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="beginnings",
                        to="arxii.heritage",
                    ),
                ),
                (
                    "starting_languages",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Languages granted to all characters from this path",
                        related_name="beginnings",
                        to="arxii.language",
                    ),
                ),
                (
                    "art",
                    models.ForeignKey(
                        blank=True,
                        help_text="Visual presentation art for this beginnings path.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="beginnings_art",
                        to="arxii.media",
                    ),
                ),
                (
                    "prelude_mission",
                    models.ForeignKey(
                        blank=True,
                        help_text="The prelude Mission auto-granted at CG finalization for characters choosing this Beginning (#2470). Null = no auto-grant (e.g. content not authored yet for this Beginning).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.missiontemplate",
                    ),
                ),
                (
                    "property_grant_profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Granted automatically at finalize_character when set. NULL = no automatic property grant for this path.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="beginnings",
                        to="arxii.propertygrantprofile",
                    ),
                ),
                (
                    "starting_room_override",
                    models.ForeignKey(
                        blank=True,
                        help_text="Override starting room for this Beginnings path (e.g., Sleeper wake room)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="beginnings_start",
                        to="arxii.roomprofile",
                    ),
                ),
                (
                    "societies",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Societies characters gain awareness/membership in during character creation",
                        related_name="connected_beginnings",
                        to="arxii.society",
                    ),
                ),
                (
                    "allowed_species",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Species available for this path. Parent species include all children.",
                        related_name="beginnings",
                        to="arxii.species",
                    ),
                ),
                (
                    "starting_area",
                    models.ForeignKey(
                        help_text="The starting area this option belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beginnings",
                        to="arxii.startingarea",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beginnings",
                "verbose_name_plural": "Beginnings",
                "unique_together": {("starting_area", "name")},
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="OriginTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "written_on",
                    models.DateField(
                        blank=True, help_text="Date the prose was written.", null=True
                    ),
                ),
                (
                    "reviewed_on",
                    models.DateField(
                        blank=True, help_text="Date the prose was reviewed.", null=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name (part of natural key).", max_length=100
                    ),
                ),
                (
                    "frame_narrative",
                    models.TextField(
                        help_text="The fixed frame prose every character with this beginning shares."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Inactive templates are hidden from CG."
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Display order when multiple templates exist."
                    ),
                ),
                (
                    "cg_point_cost",
                    models.IntegerField(
                        default=0,
                        help_text="Flat CG cost of this Upbringing (#3617). Negative refunds, like a drawback.",
                    ),
                ),
                (
                    "trust_required",
                    models.IntegerField(
                        default=0, help_text="Minimum trust to see/select this Upbringing (#3617)."
                    ),
                ),
                (
                    "allows_claim_family",
                    models.BooleanField(
                        default=False, help_text="Player may claim a staff-authored family (#3617)."
                    ),
                ),
                (
                    "allows_name_family",
                    models.BooleanField(
                        default=False,
                        help_text="Player may name a new family with no authority (#3617).",
                    ),
                ),
                (
                    "allows_no_family",
                    models.BooleanField(
                        default=False,
                        help_text="Player has no family; the tarot surname ritual applies (#3617).",
                    ),
                ),
                (
                    "beginning",
                    models.ForeignKey(
                        help_text="The beginning this origin-story frame belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="origin_templates",
                        to="arxii.beginnings",
                    ),
                ),
                (
                    "claimable_kinds",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Kinds offered on the claim path; empty = every kind (#3617).",
                        related_name="claimable_in_templates",
                        to="arxii.familykind",
                    ),
                ),
                (
                    "family_templates",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Family Templates the name path offers (#3648); one is auto-picked.",
                        related_name="upbringings",
                        to="arxii.housetemplate",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who reviewed this row's prose, if anyone. Distinct from writing it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.contentcontributor",
                    ),
                ),
                (
                    "written_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who wrote this row's prose. Null means it is still a placeholder.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.contentcontributor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Upbringing",
                "verbose_name_plural": "Upbringings",
                "ordering": ["beginning", "sort_order", "name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("allows_claim_family", True),
                            ("allows_name_family", True),
                            ("allows_no_family", True),
                            _connector="OR",
                        ),
                        name="origintemplate_at_least_one_family_path",
                    )
                ],
                "unique_together": {("beginning", "name")},
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
    ]
