# Generated by Django 5.2.16 on 2026-09-05 23:20


from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

import core.mixins
import core.natural_keys
from core_management.batched_migration import BatchedCreateModelMigration
from world.migrations._generations import replaced_slice


class Migration(BatchedCreateModelMigration):
    dependencies = [
        ("arxii", "0035_g2_part_35"),
    ]

    replaces = replaced_slice(36, 103)
    operations = [
        migrations.CreateModel(
            name="OriginTemplateSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "written_on",
                    models.DateField(
                        blank=True, help_text="Date the prose was written.", null=True
                    ),
                ),
                (
                    "reviewed_on",
                    models.DateField(
                        blank=True, help_text="Date the prose was reviewed.", null=True
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Slot name (part of natural key).", max_length=100),
                ),
                ("prompt", models.TextField(help_text="The question shown to the player.")),
                (
                    "example",
                    models.TextField(
                        blank=True, help_text="Short illustrative answer shown in the guided step."
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="Required slots are marked in the post-CG finish-later editor.",
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("any", "Any path"),
                            ("claimed", "Claim a staff-authored family"),
                            ("named", "Name your own family"),
                            ("none", "No family"),
                        ],
                        default="any",
                        help_text="Which family path shows this prompt; 'any' shows it always (#3617).",
                        max_length=10,
                    ),
                ),
                (
                    "allows_text",
                    models.BooleanField(
                        default=True,
                        help_text="Player may write a free-text answer (the 'other' box on a pick-list) (#3617).",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who reviewed this row's prose, if anyone. Distinct from writing it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.contentcontributor",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="The template this slot belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="arxii.origintemplate",
                    ),
                ),
                (
                    "written_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who wrote this row's prose. Null means it is still a placeholder.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.contentcontributor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Upbringing Prompt",
                "verbose_name_plural": "Upbringing Prompts",
                "ordering": ["template", "sort_order", "name"],
                "unique_together": {("template", "name")},
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="OriginTemplateSlotChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "written_on",
                    models.DateField(
                        blank=True, help_text="Date the prose was written.", null=True
                    ),
                ),
                (
                    "reviewed_on",
                    models.DateField(
                        blank=True, help_text="Date the prose was reviewed.", null=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Choice label (part of natural key).", max_length=100
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Player-facing blurb.")),
                (
                    "cg_point_cost",
                    models.IntegerField(default=0, help_text="Flat CG cost of this choice."),
                ),
                (
                    "cost_per_influence",
                    models.IntegerField(
                        default=0, help_text="CG cost per point of the claimed family's influence."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who reviewed this row's prose, if anyone. Distinct from writing it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.contentcontributor",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="arxii.origintemplateslot",
                    ),
                ),
                (
                    "written_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who wrote this row's prose. Null means it is still a placeholder.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.contentcontributor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Upbringing Prompt Choice",
                "verbose_name_plural": "Upbringing Prompt Choices",
                "ordering": ["slot", "sort_order", "name"],
                "unique_together": {("slot", "name")},
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="StatTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "value",
                    models.IntegerField(default=0, help_text="Current value of the tracked stat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this stat was last modified"
                    ),
                ),
                (
                    "character_sheet",
                    models.ForeignKey(
                        help_text="The character this stat belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stat_trackers",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "stat",
                    models.ForeignKey(
                        help_text="The stat being tracked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trackers",
                        to="arxii.statdefinition",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character_sheet", "stat"), name="unique_character_stat"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="StatureShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "cause",
                    models.CharField(
                        choices=[
                            ("death", "A Death"),
                            ("pact_signed", "Pact Signed"),
                            ("pact_dissolved", "Pact Dissolved"),
                            ("crisis_opened", "Crisis Opened"),
                            ("crisis_surfaced", "Crisis Surfaced"),
                            ("crisis_resolved", "Crisis Resolved"),
                            ("whispers", "Whisper Campaign"),
                            ("convergence", "Word Spreads"),
                            ("recompute", "Weekly Recompute"),
                            ("band_change", "Standing Repriced"),
                            ("grand_display", "Grand Display"),
                        ],
                        max_length=20,
                    ),
                ),
                ("delta_true", models.IntegerField(default=0)),
                ("delta_perceived", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stature_shifts",
                        to="arxii.organization",
                    ),
                ),
                (
                    "subject_kinsperson",
                    models.ForeignKey(
                        blank=True,
                        help_text="The person whose death/marriage moved the number, when one did.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.kinsperson",
                    ),
                ),
                (
                    "subject_persona",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.persona",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="StockListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("price", models.PositiveIntegerField(help_text="Coppers. PLACEHOLDER pricing.")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "min_regard",
                    models.IntegerField(
                        blank=True,
                        help_text="Reserved-stock access gate (#2995): the stall's shopkeeper_persona's NpcRegard of the buyer must meet this to see/buy the listing, above and beyond the global refusal floor. Null (default) = no extra gate.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-1000),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "stall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_listings",
                        to="arxii.marketstall",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_listings",
                        to="arxii.itemtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["stall", "template__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("stall", "template"), name="items_market_stock_unique_per_stall"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StoryArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "area",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_ownership",
                        to="arxii.area",
                    ),
                ),
                (
                    "gm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="story_areas",
                        to="arxii.gmprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Story Area",
                "verbose_name_plural": "Story Areas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoryFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "is_gm_feedback",
                    models.BooleanField(
                        default=False, help_text="True if feedback is about GM performance"
                    ),
                ),
                ("comments", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="arxii.story",
                    ),
                ),
            ],
            options={"unique_together": {("story", "reviewer", "reviewed_player")}},
        ),
        migrations.CreateModel(
            name="StoryGMOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, help_text="Optional note from offerer.")),
                ("response_note", models.TextField(blank=True, help_text="Optional GM response.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "offered_by_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_offers_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offered_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_offers_received",
                        to="arxii.gmprofile",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gm_offers",
                        to="arxii.story",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("story", "offered_to"),
                        name="unique_pending_offer_per_story_per_gm",
                    )
                ],
                "indexes": [
                    models.Index(
                        fields=["offered_to", "status"], name="arxii_story_offered_a4fd0f_idx"
                    ),
                    models.Index(fields=["story", "status"], name="arxii_story_story_i_2ca6ec_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StoryNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="arxii.story",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="StoryParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "participation_level",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("important", "Important"),
                            ("optional", "Optional"),
                        ],
                        default="optional",
                        max_length=20,
                    ),
                ),
                (
                    "trusted_by_owner",
                    models.BooleanField(
                        default=False,
                        help_text="Story owner has explicitly trusted this player for this story",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_participations",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="arxii.story",
                    ),
                ),
            ],
            options={"unique_together": {("story", "character")}},
        ),
    ]
