# Generated by Django 5.2.15 on 2026-08-04 07:42


import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

import core.mixins
import core.natural_keys


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0035_initial_part_35"),
    ]

    operations = [
        migrations.CreateModel(
            name="StablesDetails",
            fields=[
                (
                    "feature_instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="stables_details",
                        serialize=False,
                        to="arxii.roomfeatureinstance",
                    ),
                ),
                (
                    "capacity_bonus_per_level",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Flat Companion Capacity bonus per Stables level. Total bonus = capacity_bonus_per_level * instance.level.",
                    ),
                ),
            ],
            options={"ordering": ["feature_instance"]},
        ),
        migrations.CreateModel(
            name="VaultDetails",
            fields=[
                (
                    "feature_instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="vault_details",
                        serialize=False,
                        to="arxii.roomfeatureinstance",
                    ),
                ),
                (
                    "max_items",
                    models.PositiveSmallIntegerField(
                        default=20,
                        help_text="Maximum loose items the vault room can hold. Scaled by level at install: max_items = level * VAULT_MAX_ITEMS_PER_LEVEL.",
                    ),
                ),
                (
                    "founder_persona",
                    models.ForeignKey(
                        help_text="The persona who installed the vault. Has implicit owner access — always on the access list regardless of VaultAccessEntry rows. The founder's RosterTenure is the consent source for steal_permitted when an unowned vault item is stolen.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="founded_vaults",
                        to="arxii.persona",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="VaultAccessEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "holder_type",
                    models.CharField(
                        choices=[("persona", "Persona"), ("organization", "Organization")],
                        max_length=20,
                    ),
                ),
                ("added_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vault_access_granted",
                        to="arxii.persona",
                    ),
                ),
                (
                    "holder_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vault_access_entries",
                        to="arxii.organization",
                    ),
                ),
                (
                    "holder_persona",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vault_access_entries",
                        to="arxii.persona",
                    ),
                ),
                (
                    "vault_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_entries",
                        to="arxii.vaultdetails",
                    ),
                ),
            ],
            options={"ordering": ["vault_details", "added_at"]},
            bases=(core.mixins.DiscriminatorMixin, models.Model),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="active_persona",
            field=models.ForeignKey(
                blank=True,
                help_text="The face this character is currently presenting as (#981); NULL ⇒ PRIMARY. Resolve via active_persona_for_sheet; set only via set_active_persona — never gate IC reads on primary_persona directly.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="arxii.persona",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="allowed_building_kinds",
            field=models.ManyToManyField(
                blank=True, related_name="allowed_in_wards", to="arxii.buildingkind"
            ),
        ),
        migrations.AddField(
            model_name="battleunittemplate",
            name="capabilities",
            field=models.ManyToManyField(
                blank=True,
                help_text="What a unit staged from this template can DO, at an authored per-template magnitude via BattleUnitTemplateCapability — see BattleUnit.capabilities.",
                related_name="+",
                through="arxii.BattleUnitTemplateCapability",
                to="arxii.capabilitytype",
            ),
        ),
        migrations.AddField(
            model_name="checktype",
            name="owner_sheet",
            field=models.ForeignKey(
                blank=True,
                help_text="Character this synthesized check belongs to. NULL = staff-authored.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_check_types",
                to="arxii.charactersheet",
            ),
        ),
        migrations.AddField(
            model_name="classleveladvancement",
            name="witnesses",
            field=models.ManyToManyField(
                blank=True, related_name="witnessed_advancements", to="arxii.persona"
            ),
        ),
        migrations.AddField(
            model_name="codexentry",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True,
                help_text="Entries required before this can be learned.",
                related_name="unlocks",
                to="arxii.codexentry",
            ),
        ),
        migrations.AddField(
            model_name="combatopponentaction",
            name="opponent_targets",
            field=models.ManyToManyField(
                help_text="Opponent targets (#1584): an ALLY summon attacks ENEMY opponents. Exactly one of targets / opponent_targets is populated per action — the participant pool when it has hostile PCs, else this.",
                related_name="incoming_opponent_attacks",
                to="arxii.combatopponent",
            ),
        ),
        migrations.AddField(
            model_name="combatopponentaction",
            name="targets",
            field=models.ManyToManyField(
                related_name="incoming_attacks", to="arxii.combatparticipant"
            ),
        ),
        migrations.AddField(
            model_name="conditioninstance",
            name="detected_by",
            field=models.ManyToManyField(
                blank=True,
                help_text="Characters who have pierced this specific concealing instance via a detection check. Per-observer: one character detecting it does not reveal it to anyone else. Only meaningful when the condition's category has conceals_from_perception=True.",
                related_name="detected_concealments",
                to="arxii.charactersheet",
            ),
        ),
        migrations.AddField(
            model_name="conditionstage",
            name="on_entry_conditions",
            field=models.ManyToManyField(
                blank=True,
                related_name="applied_on_entry_of",
                through="arxii.ConditionStageOnEntry",
                to="arxii.conditiontemplate",
            ),
        ),
        migrations.AddField(
            model_name="companionability",
            name="conditions_applied",
            field=models.ManyToManyField(
                blank=True, related_name="companion_abilities", to="arxii.conditiontemplate"
            ),
        ),
        migrations.AddField(
            model_name="codexteachingoffer",
            name="visible_to_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Consent groups who can see this (if mode is 'groups').",
                related_name="%(class)s_visible",
                to="arxii.consentgroup",
            ),
        ),
    ]
