# Generated by Django 5.2.15 on 2026-08-04 07:42


import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0036_initial_part_36"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengetemplate",
            name="consequences",
            field=models.ManyToManyField(
                blank=True,
                related_name="challenge_templates",
                through="arxii.ChallengeTemplateConsequence",
                to="arxii.consequence",
            ),
        ),
        migrations.AddField(
            model_name="covenantriteinstance",
            name="participants",
            field=models.ManyToManyField(
                related_name="covenant_rite_instances",
                through="arxii.CovenantRiteParticipant",
                to="arxii.charactersheet",
            ),
        ),
        migrations.AddField(
            model_name="covenantrole",
            name="granted_capabilities",
            field=models.ManyToManyField(
                blank=True,
                help_text="#2022: Capabilities granted by this role while engaged. Written to the character's capability ledger on engage; revoked on disengage.",
                related_name="granted_by_roles",
                to="arxii.capabilitytype",
            ),
        ),
        migrations.AddField(
            model_name="distinction",
            name="mutually_exclusive_with",
            field=models.ManyToManyField(
                blank=True,
                help_text="Distinctions that are mutually exclusive with this one.",
                to="arxii.distinction",
            ),
        ),
        migrations.AddField(
            model_name="distinction",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags for filtering and searching.",
                related_name="distinctions",
                to="arxii.distinctiontag",
            ),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="durance_cohort",
            field=models.ForeignKey(
                blank=True,
                help_text="Cached cohort for cheap reads; canonical membership is CohortEnrollment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="arxii.durancecohort",
            ),
        ),
        migrations.AddField(
            model_name="fashionstyle",
            name="in_vogue_facets",
            field=models.ManyToManyField(
                blank=True,
                help_text="Facets that are currently fashionable in this style.",
                related_name="fashion_styles",
                to="arxii.facet",
            ),
        ),
        migrations.AddField(
            model_name="formtraitoption",
            name="trait",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="arxii.formtrait",
            ),
        ),
        migrations.AddField(
            model_name="formtrait",
            name="composite_option",
            field=models.ForeignKey(
                blank=True,
                help_text="The umbrella value blends resolve to (#2632 — hair_color: multihued, eye_color: mismatched). Null = this trait does not support blends. The blend's actual colors live in FormValueComponent rows, so the normalized layer can still say 'red-green' under descriptor concealment without the distinctive prose.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="composite_for_traits",
                to="arxii.formtraitoption",
            ),
        ),
        migrations.AddField(
            model_name="functionary",
            name="persona",
            field=models.ForeignKey(
                blank=True,
                help_text="The materialized identity behind this placement (#2827 tier 1). NULL = still a faceless slot; set when a player engagement (or staff) makes them real. The persona survives the placement — extraction/standing promotion clears this link, never the identity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="functionary_placements",
                to="arxii.persona",
            ),
        ),
        migrations.AddField(
            model_name="covenantrole",
            name="granted_gifts",
            field=models.ManyToManyField(
                blank=True,
                help_text="#2022: Gifts granted by this role while engaged. The role's gift techniques are auto-granted on engage and auto-revoked on disengage (the #2051 vow-dim path). Techniques are primarily enhancements that boost overlapping techniques from the character's existing gifts.",
                related_name="granted_by_roles",
                through="arxii.CovenantRoleGiftGrant",
                to="arxii.gift",
            ),
        ),
        migrations.AddField(
            model_name="housetemplate",
            name="aspect_definitions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Required catalog choices for claims on this template (#2079).",
                related_name="templates",
                to="arxii.houseaspectdefinition",
            ),
        ),
        migrations.AddField(
            model_name="housetemplate",
            name="features",
            field=models.ManyToManyField(
                blank=True,
                help_text="Cultural facts stamped on materialized houses (#2079).",
                related_name="templates",
                to="arxii.housefeature",
            ),
        ),
        migrations.AddField(
            model_name="housetemplate",
            name="holdings",
            field=models.ManyToManyField(
                blank=True,
                help_text="Holdings materialized on the title's seat domain at finalization.",
                related_name="house_templates",
                to="arxii.holdingkind",
            ),
        ),
    ]
