# Generated by Django 5.2.16 on 2026-09-05 23:20

from decimal import Decimal

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

import core.mixins
import core.natural_keys
from core_management.batched_migration import BatchedCreateModelMigration
from world.migrations._generations import replaced_slice


class Migration(BatchedCreateModelMigration):
    dependencies = [
        ("arxii", "0040_g2_part_40"),
    ]

    replaces = replaced_slice(41, 103)
    operations = [
        migrations.CreateModel(
            name="TechniqueDraftRemovedCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "target_kind",
                    models.CharField(
                        choices=[("self", "Self"), ("ally", "Ally"), ("enemy", "Enemy")],
                        default="enemy",
                        max_length=16,
                    ),
                ),
                (
                    "minimum_success_level",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum success level required to apply this condition.",
                    ),
                ),
                (
                    "base_severity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Flat base severity applied when the condition triggers.",
                    ),
                ),
                (
                    "severity_intensity_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Multiplied by effective_power and added to severity.",
                        max_digits=5,
                    ),
                ),
                (
                    "severity_per_extra_sl",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Extra severity added per success level above the minimum.",
                    ),
                ),
                (
                    "base_duration_rounds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Base duration in rounds. When null, falls back to condition.default_duration_value.",
                        null=True,
                    ),
                ),
                (
                    "duration_intensity_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Multiplied by effective_power and added to duration.",
                        max_digits=5,
                    ),
                ),
                (
                    "duration_per_extra_sl",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Extra duration rounds added per success level above the minimum.",
                    ),
                ),
                (
                    "stack_count",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of condition stacks applied when triggered."
                    ),
                ),
                (
                    "remove_all_stacks",
                    models.BooleanField(
                        default=True,
                        help_text="If True, all stacks of the condition are removed. If False, only one stack is decremented.",
                    ),
                ),
                (
                    "condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_applied",
                        to="arxii.conditiontemplate",
                    ),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="removed_conditions",
                        to="arxii.techniquedraft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technique Draft Removed Condition",
                "verbose_name_plural": "Technique Draft Removed Conditions",
            },
        ),
        migrations.CreateModel(
            name="TechniqueFunctionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "function",
                    models.CharField(
                        choices=[
                            ("damage_buff_self", "Self Damage Buff"),
                            ("damage_buff_ally", "Ally Damage Buff"),
                            ("defense_buff", "Defense Buff"),
                            ("barrier", "Barrier"),
                            ("cleanse", "Cleanse"),
                            ("mobility", "Mobility"),
                            ("charm", "Charm"),
                            ("distraction", "Distraction"),
                            ("fear", "Fear"),
                            ("weaken", "Weaken"),
                            ("perception", "Perception"),
                            ("concealment", "Concealment"),
                            ("hold", "Hold / Lock"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="function_tags",
                        to="arxii.technique",
                    ),
                ),
            ],
            options={
                "ordering": ["technique__name", "function"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("technique", "function"), name="unique_function_per_technique"
                    )
                ],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TechniqueGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "acquisition_ap_cost",
                    models.PositiveIntegerField(
                        default=0, help_text="AP cost to learn via this grant (0 = free)."
                    ),
                ),
                (
                    "acquisition_xp_cost",
                    models.PositiveIntegerField(
                        default=0, help_text="XP cost to learn via this grant (0 = free)."
                    ),
                ),
                (
                    "verb",
                    models.CharField(
                        default="study",
                        help_text="Narrative verb for the acquisition message (study, devour, consume, meditate).",
                        max_length=50,
                    ),
                ),
                (
                    "flavor_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional flavor text shown on acquisition.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Item that grants this technique on use. Mutually exclusive with ritual.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="technique_grants",
                        to="arxii.itemtemplate",
                    ),
                ),
                (
                    "ritual",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ritual that grants this technique on performance. Mutually exclusive with item_template.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="technique_grants",
                        to="arxii.ritual",
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        help_text="The technique this grant teaches.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grants",
                        to="arxii.technique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technique Grant",
                "verbose_name_plural": "Technique Grants",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("item_template__isnull", False)),
                        fields=("technique", "item_template"),
                        name="unique_technique_item_grant",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("ritual__isnull", False)),
                        fields=("technique", "ritual"),
                        name="unique_technique_ritual_grant",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TechniqueProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "points_accumulated",
                    models.PositiveIntegerField(
                        default=0, help_text="Development points accumulated toward the technique."
                    ),
                ),
                (
                    "total_required",
                    models.PositiveIntegerField(
                        help_text="Total development points required, snapshotted at creation."
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("assumed_alternate_self", "assuming an alternate self"),
                            ("reverted_alternate_self", "reverting to your true self"),
                            ("covenant_role_engaged", "taking up your covenant role"),
                            ("covenant_role_disengaged", "setting down your covenant role"),
                            ("character_creation", "your origins"),
                            ("path_advancement", "advancing into a new path"),
                            ("gift_acquisition", "acquiring a new gift"),
                            ("technique_grant", "studying a technique source"),
                            ("academy_training", "training at the Academy"),
                            ("codex_learning", "learning a piece of lore"),
                            ("gm_award", "a GM's story award"),
                        ],
                        help_text="Provenance: how this meter was created.",
                        max_length=30,
                    ),
                ),
                (
                    "is_cross_path",
                    models.BooleanField(
                        default=False,
                        help_text="True when the teacher's Path.style differed from the learner's at creation. Drives the effective weekly cap.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technique_progress",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "teacher_tenure",
                    models.ForeignKey(
                        blank=True,
                        help_text="Teacher RosterTenure when applicable; null for self-directed acquisition.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="technique_progress_taught",
                        to="arxii.rostertenure",
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="progress_records",
                        to="arxii.technique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technique Progress",
                "verbose_name_plural": "Technique Progress",
                "ordering": ["character_sheet", "technique"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character_sheet", "technique"),
                        name="unique_technique_progress_per_character",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TechniqueProgressWeekly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "points_contributed",
                    models.PositiveIntegerField(
                        default=0, help_text="Meter-progress points contributed this week."
                    ),
                ),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technique_progress_weekly",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "game_week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technique_progress_weekly",
                        to="arxii.gameweek",
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_weekly",
                        to="arxii.technique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technique Progress Weekly",
                "verbose_name_plural": "Technique Progress Weekly",
                "ordering": ["character_sheet", "technique", "game_week"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character_sheet", "technique", "game_week"),
                        name="unique_technique_progress_weekly",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TechniquePropertyAffinity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("modifier", models.SmallIntegerField()),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="battle_technique_affinities",
                        to="arxii.property",
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="battle_property_affinities",
                        to="arxii.technique",
                    ),
                ),
            ],
            options={
                "ordering": ["technique", "property"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("technique", "property"), name="unique_technique_property_affinity"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TechniqueRemovedCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "target_kind",
                    models.CharField(
                        choices=[("self", "Self"), ("ally", "Ally"), ("enemy", "Enemy")],
                        default="enemy",
                        max_length=16,
                    ),
                ),
                (
                    "minimum_success_level",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum success level required to apply this condition.",
                    ),
                ),
                (
                    "base_severity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Flat base severity applied when the condition triggers.",
                    ),
                ),
                (
                    "severity_intensity_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Multiplied by effective_power and added to severity.",
                        max_digits=5,
                    ),
                ),
                (
                    "severity_per_extra_sl",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Extra severity added per success level above the minimum.",
                    ),
                ),
                (
                    "base_duration_rounds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Base duration in rounds. When null, falls back to condition.default_duration_value.",
                        null=True,
                    ),
                ),
                (
                    "duration_intensity_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Multiplied by effective_power and added to duration.",
                        max_digits=5,
                    ),
                ),
                (
                    "duration_per_extra_sl",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Extra duration rounds added per success level above the minimum.",
                    ),
                ),
                (
                    "stack_count",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of condition stacks applied when triggered."
                    ),
                ),
                (
                    "remove_all_stacks",
                    models.BooleanField(
                        default=True,
                        help_text="If True, all stacks of the condition are removed. If False, only one stack is decremented (the condition persists with stacks - 1).",
                    ),
                ),
                (
                    "cure_power_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Multiplied by eff_intensity and added as extra_modifiers to the opposed cure check (0 = power has no effect on the roll, today's behavior).",
                        max_digits=5,
                    ),
                ),
                (
                    "condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_applied",
                        to="arxii.conditiontemplate",
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="removed_conditions",
                        to="arxii.technique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technique Removed Condition",
                "verbose_name_plural": "Technique Removed Conditions",
                "ordering": ["pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("technique", "condition", "target_kind"),
                        name="unique_removed_condition_per_technique",
                    )
                ],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TechniqueTeachingOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "pitch",
                    models.TextField(
                        help_text="Player-written description of what they're offering to teach."
                    ),
                ),
                (
                    "learn_ap_cost",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="AP the learner pays to accept. Teacher sets this per offer.",
                    ),
                ),
                (
                    "gold_cost",
                    models.PositiveIntegerField(
                        default=0, help_text="Optional gold payment required from learner."
                    ),
                ),
                (
                    "banked_ap",
                    models.PositiveIntegerField(help_text="AP committed from teacher's pool."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="Tenure (player-character instance) offering to teach.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technique_teaching_offers",
                        to="arxii.rostertenure",
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        help_text="The technique being offered.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teaching_offers",
                        to="arxii.technique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technique Teaching Offer",
                "verbose_name_plural": "Technique Teaching Offers",
            },
        ),
        migrations.CreateModel(
            name="TechniqueVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "unlock_thread_level",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 = base/parent; >=3 = variant (thread level needed to unlock).",
                    ),
                ),
                (
                    "name_override",
                    models.CharField(
                        blank=True,
                        help_text="Display name for this variant; blank = inherit parent's name.",
                        max_length=200,
                    ),
                ),
                (
                    "intensity_delta",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Added to the parent technique's intensity when this variant resolves.",
                    ),
                ),
                (
                    "control_delta",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Added to the parent technique's control when this variant resolves.",
                    ),
                ),
                (
                    "codex_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="Variant only: lore entry unlocked on manifestation.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="arxii.codexentry",
                    ),
                ),
                (
                    "discovery_achievement",
                    models.ForeignKey(
                        blank=True,
                        help_text="Variant only: achievement granted (+ global-first Discovery) on manifestation.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="arxii.achievement",
                    ),
                ),
                (
                    "parent_technique",
                    models.ForeignKey(
                        help_text="The parent technique this variant specializes.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="arxii.technique",
                    ),
                ),
                (
                    "resonance",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for the base/parent row; set for variants.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_subrole",
                        to="arxii.resonance",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("parent_technique", "resonance", "unlock_thread_level"),
                        name="technique_variant_unique_parent_resonance_level",
                    )
                ]
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
    ]
