# Generated by Django 5.2.16 on 2026-09-06 00:50


import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

import core.mixins
import core.natural_keys
from core_management.batched_migration import BatchedCreateModelMigration
from world.migrations._generations import replaced_slice


class Migration(BatchedCreateModelMigration):
    dependencies = [
        ("arxii", "0042_g2_part_42"),
    ]

    replaces = replaced_slice(43, 103)
    operations = [
        migrations.CreateModel(
            name="ThreadWeavingTeachingOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("pitch", models.TextField(help_text="Teacher's narrative pitch for this offer.")),
                (
                    "gold_cost",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Gold price the teacher charges (XP cost stays on the unlock).",
                    ),
                ),
                (
                    "banked_ap",
                    models.PositiveIntegerField(
                        help_text="Teacher's AP commitment backing this offer."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="Teaching tenure offering this unlock.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thread_weaving_offers",
                        to="arxii.rostertenure",
                    ),
                ),
                (
                    "unlock",
                    models.ForeignKey(
                        help_text="Authored unlock being offered.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teaching_offers",
                        to="arxii.threadweavingunlock",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ThreatPoolEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "written_on",
                    models.DateField(
                        blank=True, help_text="Date the prose was written.", null=True
                    ),
                ),
                (
                    "reviewed_on",
                    models.DateField(
                        blank=True, help_text="Date the prose was reviewed.", null=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "hit_narration",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Player-facing line for when this NPC attack lands on a target (#3554). Use {actor} and {target}; both are required. The machine appends the damage figure and any wound, knockout or defeat clause after it, so write the blow, not the ledger: '{actor} rakes {target} with its claws'. Blank falls back to the standard sentence. Plain register.",
                    ),
                ),
                (
                    "miss_narration",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Player-facing line for when this NPC attack misses its target (#3554). Use {actor} and {target}; both are required. Blank falls back to the standard sentence. Plain register.",
                    ),
                ),
                (
                    "attack_category",
                    models.CharField(
                        choices=[
                            ("physical", "Physical"),
                            ("social", "Social"),
                            ("mental", "Mental"),
                        ],
                        max_length=20,
                    ),
                ),
                ("base_damage", models.PositiveIntegerField(default=0)),
                ("weight", models.PositiveIntegerField(default=10, help_text="Selection weight")),
                (
                    "targeting_mode",
                    models.CharField(
                        choices=[("single", "Single"), ("multi", "Multi"), ("all", "All")],
                        default="single",
                        max_length=20,
                    ),
                ),
                (
                    "delivery",
                    models.CharField(
                        choices=[("melee", "Melee"), ("missile", "Missile")],
                        default="melee",
                        help_text="How this strike reaches its target — drives rampart interception (#2209).",
                        max_length=10,
                    ),
                ),
                ("target_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "target_selection",
                    models.CharField(
                        choices=[
                            ("random", "Random"),
                            ("highest_threat", "Highest Threat"),
                            ("lowest_health", "Lowest Health"),
                            ("specific_role", "Specific Role"),
                        ],
                        default="specific_role",
                        max_length=30,
                    ),
                ),
                ("minimum_phase", models.PositiveIntegerField(blank=True, null=True)),
                ("cooldown_rounds", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "windup_rounds",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Rounds this attack telegraphs before it lands (#2637). 0 (default) is today's same-round behavior. > 0 creates a PendingOpponentAttack at declaration instead of a same-round CombatOpponentAction; the attack matures resolves_round rounds later, and can be interrupted/downgraded by PC hits on the opponent in the meantime.",
                    ),
                ),
                (
                    "windup_telegraph",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Telegraph text broadcast when this wind-up is declared (#2637). Blank falls back to a generic line ('The {opponent} begins something enormous...') at broadcast time.",
                        max_length=300,
                    ),
                ),
                (
                    "requires_steady",
                    models.BooleanField(
                        default=False,
                        help_text="If True, this entry is skipped when the opponent is faltering (morale_state FALTER). Lets designers author 'weakened' entries (#2015).",
                    ),
                ),
                (
                    "sends_flying",
                    models.BooleanField(
                        default=False,
                        help_text="Big attacks that launch their victim on a damaging hit (#2638). Pairs naturally with windup_rounds — a telegraphed haymaker that connects sends the victim flying. Applies the seeded 'Sent Flying' marker condition (world.combat.sent_flying_content) whenever this entry's attack deals damage > 0; the marker is then reactable (an armed guardian INTERPOSE may catch it mid-air) or resolves explicitly at end of round — see world.combat.services._resolve_sent_flying_markers.",
                    ),
                ),
                (
                    "clash_capable",
                    models.BooleanField(
                        default=False,
                        help_text="When True, this entry can initiate or sustain a Clash.",
                    ),
                ),
                (
                    "is_lock_applying",
                    models.BooleanField(
                        default=False,
                        help_text="When this attack lands on a PC, it opens a LOCK-flavor Clash — the PC must win a Break Free clash to escape. Requires `clash_break_free_force`.",
                    ),
                ),
                (
                    "is_sustained_attack",
                    models.BooleanField(
                        default=False,
                        help_text="This attack is a sustained multi-round barrage that opens a WARD-flavor Clash — PCs endure it for `sustained_duration_rounds`. Distinct from `is_lock_applying`.",
                    ),
                ),
                (
                    "sustained_duration_rounds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="How many rounds a sustained attack persists before the NPC must re-use it.",
                        null=True,
                    ),
                ),
                (
                    "clash_break_free_force",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="The BREAK-clash PC win threshold for breaking free of a lock applied by this entry. Required when is_lock_applying=True.",
                        null=True,
                    ),
                ),
                (
                    "clash_npc_pressure",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="NPC's per-round pressure contribution in a Clash initiated or sustained by this entry.",
                        null=True,
                    ),
                ),
                (
                    "clash_per_round_pool",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional per-round consequence pool fired each round of a Clash initiated by this entry.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="arxii.consequencepool",
                    ),
                ),
                (
                    "clash_resolution_pool",
                    models.ForeignKey(
                        blank=True,
                        help_text="Consequence pool fired when a Clash initiated by this entry resolves.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="arxii.consequencepool",
                    ),
                ),
                (
                    "conditions_applied",
                    models.ManyToManyField(
                        blank=True, related_name="threat_pool_entries", to="arxii.conditiontemplate"
                    ),
                ),
                (
                    "damage_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Damage type for resistance lookup. Null = untyped attack.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="threat_pool_entries",
                        to="arxii.damagetype",
                    ),
                ),
                (
                    "defense_check_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="CheckType the targeted PC rolls to evade/mitigate this attack. Null = flat base_damage with no defense roll (backward-compatible).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="threat_pool_entries",
                        to="arxii.checktype",
                    ),
                ),
                (
                    "effect_properties",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Effect Properties this NPC attack carries. Drives clash-opposition matching against PC techniques' effect properties. Empty = attack cannot trigger or assist clashes.",
                        related_name="threat_pool_entries",
                        to="arxii.property",
                    ),
                ),
                (
                    "on_hit_consequence_pool",
                    models.ForeignKey(
                        blank=True,
                        help_text="Consequence pool fired unconditionally (no roll) whenever this attack lands with damage > 0 surviving Interpose. Distinct from clash_resolution_pool (clash-specific) — this fires on every successful hit. A MOVE_TO_POSITION/AWAY_FROM_ACTOR effect here is how a GM authors 'this attack knocks back.'",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="arxii.consequencepool",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="arxii.threatpool",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who reviewed this row's prose, if anyone. Distinct from writing it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.contentcontributor",
                    ),
                ),
                (
                    "written_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who wrote this row's prose. Null means it is still a placeholder.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.contentcontributor",
                    ),
                ),
            ],
            options={"unique_together": {("pool", "name")}},
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TradeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="proposed",
                        max_length=20,
                    ),
                ),
                ("initiator_confirmed", models.BooleanField(default=False)),
                ("counterparty_confirmed", models.BooleanField(default=False)),
                (
                    "initiator_coppers",
                    models.PositiveIntegerField(
                        default=0, help_text="Coin the initiator has staged onto the table."
                    ),
                ),
                (
                    "counterparty_coppers",
                    models.PositiveIntegerField(
                        default=0, help_text="Coin the counterparty has staged onto the table."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the session reached COMPLETED or CANCELLED.",
                        null=True,
                    ),
                ),
                (
                    "counterparty_sheet",
                    models.ForeignKey(
                        help_text="The character invited to the trade.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_sessions_received",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "initiator_sheet",
                    models.ForeignKey(
                        help_text="The character who proposed the trade.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_sessions_initiated",
                        to="arxii.charactersheet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["initiator_sheet", "status"], name="arxii_trade_initiat_addc6a_idx"
                    ),
                    models.Index(
                        fields=["counterparty_sheet", "status"],
                        name="arxii_trade_counter_ceee4e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TradeItemStake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("staked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_stakes",
                        to="arxii.iteminstance",
                    ),
                ),
                (
                    "offered_by_sheet",
                    models.ForeignKey(
                        help_text="Must equal session.initiator_sheet or session.counterparty_sheet.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_stakes",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_stakes",
                        to="arxii.tradesession",
                    ),
                ),
            ],
            options={
                "ordering": ["staked_at"],
                "indexes": [
                    models.Index(fields=["session"], name="arxii_trade_session_8c9008_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="TraditionCodexGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "is_perspective",
                    models.BooleanField(
                        default=False,
                        help_text="This entry is the granting tradition's own take on its subject, written in that tradition's voice, rather than canon-neutral knowledge it happens to teach (#3281).",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tradition_grants",
                        to="arxii.codexentry",
                    ),
                ),
                (
                    "tradition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codex_grants",
                        to="arxii.tradition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tradition Codex Grant",
                "verbose_name_plural": "Tradition Codex Grants",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_perspective", True)),
                        fields=("entry",),
                        name="one_tradition_perspective_holder_per_entry",
                    )
                ],
                "unique_together": {("tradition", "entry")},
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TraditionGiftGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "gift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tradition_grants",
                        to="arxii.gift",
                    ),
                ),
                (
                    "special_techniques",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Techniques special to this tradition for this gift — additive extras on top of the path's starter pool. Empty = no tradition-specific extras. For partial-depth access, list only the restricted subset the tradition offers.",
                        related_name="granted_by_tradition_gifts",
                        to="arxii.technique",
                    ),
                ),
                (
                    "tradition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gift_grants",
                        to="arxii.tradition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tradition Gift Grant",
                "verbose_name_plural": "Tradition Gift Grants",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tradition", "gift"), name="unique_tradition_gift_grant"
                    )
                ],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TrainingAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ap_amount",
                    models.PositiveIntegerField(
                        help_text="Action points allocated per week (minimum 1)"
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        help_text="The character this training allocation belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_allocations",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Mentor persona; null means self-study",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mentored_allocations",
                        to="arxii.persona",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        help_text="The skill being trained (mutually exclusive with specialization)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_allocations",
                        to="arxii.skill",
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        blank=True,
                        help_text="The specialization being trained (mutually exclusive with skill)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_allocations",
                        to="arxii.specialization",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("skill__isnull", False), ("specialization__isnull", True)),
                            models.Q(("skill__isnull", True), ("specialization__isnull", False)),
                            _connector="OR",
                        ),
                        name="training_skill_xor_specialization",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ap_amount__gte", 1)), name="training_ap_amount_min_1"
                    ),
                ],
                "indexes": [
                    models.Index(fields=["character"], name="arxii_train_charact_e02122_idx")
                ],
                "unique_together": {("character", "skill"), ("character", "specialization")},
            },
        ),
        migrations.CreateModel(
            name="TrainOfferDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "learn_ap_cost",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Base AP the learner pays to accept, before the has-gift/major-gift multiplier (mirrors TechniqueTeachingOffer.learn_ap_cost).",
                    ),
                ),
                (
                    "gold_cost",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Coin charged to the learner's purse, credited to the Academy's treasury.",
                    ),
                ),
                (
                    "offer",
                    models.OneToOneField(
                        help_text="The NPCServiceOffer row this details model decorates.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="train_offer_details",
                        to="arxii.npcserviceoffer",
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        help_text="The technique this trainer teaches on this offer.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="train_offers",
                        to="arxii.technique",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Transition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        blank=True,
                        choices=[("therefore", "Therefore"), ("but", "But")],
                        default="",
                        help_text="Narrative flavor: THEREFORE / BUT.",
                        max_length=20,
                    ),
                ),
                (
                    "connection_summary",
                    models.TextField(
                        blank=True,
                        help_text="Short narrative description of why this transition fires.",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbound_transitions",
                        to="arxii.episode",
                    ),
                ),
                (
                    "target_episode",
                    models.ForeignKey(
                        blank=True,
                        help_text="May be null when next episode is unauthored (frontier pause).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inbound_transitions",
                        to="arxii.episode",
                    ),
                ),
            ],
            options={
                "ordering": ["source_episode", "order"],
                "indexes": [
                    models.Index(fields=["source_episode"], name="arxii_trans_source__dfdc97_idx")
                ],
            },
        ),
    ]
