# Generated by Django 5.2.16 on 2026-09-06 00:50

from decimal import Decimal

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

import core.mixins
import core.natural_keys
from core_management.batched_migration import BatchedCreateModelMigration
from world.migrations._generations import replaced_slice


class Migration(BatchedCreateModelMigration):
    dependencies = [
        ("arxii", "0043_g2_part_43"),
    ]

    replaces = replaced_slice(44, 103)
    operations = [
        migrations.CreateModel(
            name="EpisodeResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("gm_notes", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character_sheet",
                    models.ForeignKey(
                        blank=True,
                        help_text="For CHARACTER-scope stories: the character whose progress advanced.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episode_resolutions",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolutions",
                        to="arxii.episode",
                    ),
                ),
                (
                    "era",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="episode_resolutions",
                        to="arxii.era",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="episode_resolutions",
                        to="arxii.gmprofile",
                    ),
                ),
                (
                    "gm_table",
                    models.ForeignKey(
                        blank=True,
                        help_text="For GROUP-scope stories: the GMTable whose progress advanced.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="episode_resolutions",
                        to="arxii.gmtable",
                    ),
                ),
                (
                    "chosen_transition",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null when the episode resolves with no transition (frontier pause).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolutions_using",
                        to="arxii.transition",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["episode", "-resolved_at"], name="arxii_episo_episode_23a5d9_idx"
                    ),
                    models.Index(
                        fields=["character_sheet", "-resolved_at"],
                        name="arxii_episo_charact_af17b6_idx",
                    ),
                    models.Index(
                        fields=["gm_table", "-resolved_at"], name="arxii_episo_gm_tabl_834e67_idx"
                    ),
                ]
            },
        ),
        migrations.CreateModel(
            name="TransitionRequiredOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "required_outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unsatisfied", "Unsatisfied"),
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("expired", "Expired"),
                        ],
                        default="",
                        help_text="Required beat outcome; blank on stake-level rows.",
                        max_length=20,
                    ),
                ),
                (
                    "required_stake_column",
                    models.CharField(
                        blank=True,
                        choices=[("win", "Win"), ("loss", "Loss"), ("withdrawal", "Withdrawal")],
                        default="",
                        help_text="Required StakeOutcome column; only with stake set.",
                        max_length=12,
                    ),
                ),
                (
                    "required_outcome_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Beat-level rows only: also require Beat.outcome_key to equal this MissionOption.key (#3565). Blank = any key.",
                        max_length=100,
                    ),
                ),
                (
                    "beat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routing_for_transitions",
                        to="arxii.beat",
                    ),
                ),
                (
                    "stake",
                    models.ForeignKey(
                        blank=True,
                        help_text="When set, this requirement routes on the stake's StakeOutcome column instead of the beat's outcome.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routing_for_transitions",
                        to="arxii.stake",
                    ),
                ),
                (
                    "transition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_outcomes",
                        to="arxii.transition",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("stake__isnull", True)),
                        fields=("transition", "beat"),
                        name="unique_routing_req_per_transition_beat",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("stake__isnull", False)),
                        fields=("transition", "stake"),
                        name="unique_routing_req_per_transition_stake",
                    ),
                ]
            },
        ),
        migrations.CreateModel(
            name="Trap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "detect_difficulty",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Authored target difficulty for the on-entry detection check.",
                    ),
                ),
                (
                    "disarm_difficulty",
                    models.PositiveIntegerField(
                        default=0, help_text="Authored target difficulty for the disarm check."
                    ),
                ),
                (
                    "is_armed",
                    models.BooleanField(
                        default=True,
                        help_text="A disarmed trap never triggers and cannot be disarmed again.",
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the trap needs a detection roll at all. False means an authored, obvious hazard: visible to everyone in the room's trap list with no roll on entry or search. True (default) means it must be spotted (on entry, on a deliberate search, or by taking the hit) before it becomes known to that character.",
                    ),
                ),
                (
                    "duration_rounds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="For zone hazards: rounds until the hazard dissipates. Null = permanent trap (one-shot entry trigger).",
                        null=True,
                    ),
                ),
                (
                    "consequence_pool",
                    models.ForeignKey(
                        help_text="Graded damage payload, keyed by the detection/disarm check outcome tier: success tiers should carry no consequence (avoided); failure tiers deal the authored damage.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="traps",
                        to="arxii.consequencepool",
                    ),
                ),
                (
                    "created_by_sheet",
                    models.ForeignKey(
                        blank=True,
                        help_text="Provenance: the caster who conjured this hazard. Null for staff-authored traps.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conjured_hazards",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "detect_check_type",
                    models.ForeignKey(
                        help_text="Check rolled on entry to spot the trap before it triggers.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detect_traps",
                        to="arxii.checktype",
                    ),
                ),
                (
                    "detected_by",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Characters for whom this trap is resolved — they spotted or already triggered it, so it neither re-triggers nor stays hidden for them.",
                        related_name="detected_traps",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "disarm_check_type",
                    models.ForeignKey(
                        help_text="Check rolled by the disarm action.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disarm_traps",
                        to="arxii.checktype",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional specific spot this hazard is anchored to. Unset (default) = room-wide, matching pre-#1317 behavior. When set, this trap only fires for a character actually occupying this Position — whether they walked there or were knocked there.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="traps",
                        to="arxii.position",
                    ),
                ),
                (
                    "room_profile",
                    models.ForeignKey(
                        help_text="The room this trap is set in. A room may hold several traps.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traps",
                        to="arxii.roomprofile",
                    ),
                ),
            ],
            options={"ordering": ["room_profile_id", "name"]},
        ),
        migrations.CreateModel(
            name="TreasuredSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "visibility_mode",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("characters", "Specific Characters"),
                            ("groups", "Consent Groups"),
                        ],
                        default="private",
                        help_text="Who can see this content.",
                        max_length=20,
                    ),
                ),
                (
                    "subject_kind",
                    models.CharField(
                        choices=[
                            ("personal_jeopardy", "Personal jeopardy"),
                            ("npc_fate", "NPC fate"),
                            ("location", "Location"),
                            ("faction", "Faction relationship"),
                            ("item", "Item"),
                            ("campaign_track", "Campaign track"),
                            ("asset", "Asset"),
                            ("custom", "Custom (trust-gated)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "subject_label",
                    models.CharField(
                        blank=True,
                        help_text="Freeform subject name (CUSTOM / CAMPAIGN_TRACK / LOCATION, or flavor).",
                        max_length=200,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "excluded_tenures",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Tenures explicitly excluded even if otherwise visible.",
                        related_name="%(class)s_excluded",
                        to="arxii.rostertenure",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treasured_subjects",
                        to="arxii.rostertenure",
                    ),
                ),
                (
                    "subject_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="For ITEM subjects. Nulls if the item instance is deleted/consumed.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.iteminstance",
                    ),
                ),
                (
                    "subject_organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="For FACTION subjects (organization-level). Nulls if the org is deleted.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.organization",
                    ),
                ),
                (
                    "subject_sheet",
                    models.ForeignKey(
                        blank=True,
                        help_text="For NPC_FATE / PERSONAL_JEOPARDY subjects. Nulls if the sheet is deleted.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treasured_by",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "subject_society",
                    models.ForeignKey(
                        blank=True,
                        help_text="For FACTION subjects (society-level). Nulls if the society is deleted.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.society",
                    ),
                ),
                (
                    "visible_to_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Consent groups who can see this (if mode is 'groups').",
                        related_name="%(class)s_visible",
                        to="arxii.consentgroup",
                    ),
                ),
                (
                    "visible_to_tenures",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Tenures who can see this (if mode is 'characters').",
                        related_name="%(class)s_visible",
                        to="arxii.rostertenure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Treasured Subject",
                "verbose_name_plural": "Treasured Subjects",
                "ordering": ["owner", "subject_kind"],
            },
        ),
        migrations.CreateModel(
            name="TreasuredSignoff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "beat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treasured_signoffs",
                        to="arxii.beat",
                    ),
                ),
                (
                    "player_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treasured_signoffs",
                        to="arxii.playerdata",
                    ),
                ),
                (
                    "treasured_subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signoffs",
                        to="arxii.treasuredsubject",
                    ),
                ),
            ],
            options={"ordering": ["beat", "player_data"]},
        ),
        migrations.CreateModel(
            name="TreatmentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "target_kind",
                    models.CharField(
                        choices=[
                            ("primary", "Primary condition severity"),
                            ("aftermath", "Aftermath child condition severity"),
                            ("pending_alteration", "Pending alteration tier"),
                        ],
                        max_length=32,
                    ),
                ),
                ("target_difficulty", models.PositiveIntegerField(default=0)),
                ("requires_bond", models.BooleanField(default=False)),
                ("resonance_cost", models.PositiveIntegerField(default=0)),
                ("anima_cost", models.PositiveIntegerField(default=0)),
                ("once_per_scene_per_helper", models.BooleanField(default=True)),
                ("scene_required", models.BooleanField(default=True)),
                ("backlash_severity_on_failure", models.PositiveIntegerField(default=0)),
                ("reduction_on_crit", models.PositiveIntegerField(default=0)),
                ("reduction_on_success", models.PositiveIntegerField(default=0)),
                ("reduction_on_partial", models.PositiveIntegerField(default=0)),
                ("reduction_on_failure", models.PositiveIntegerField(default=0)),
                (
                    "mend_on_crit",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="HP mended on a critical success, routed through mend_wound() (0 = no mend).",
                    ),
                ),
                (
                    "mend_on_success",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="HP mended on a success, routed through mend_wound() (0 = no mend).",
                    ),
                ),
                (
                    "mend_on_partial",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="HP mended on a partial success, routed through mend_wound() (0 = no mend).",
                    ),
                ),
                (
                    "once_per_wound_per_helper",
                    models.BooleanField(
                        default=False,
                        help_text="When true, the duplicate-attempt gate keys on (helper, wound instance) instead of (helper, scene) — each healer gets exactly one tending per wound, ever, scene-independent (#2644). Mend-bearing treatments should set this True; leave once_per_scene_per_helper governing everything else.",
                    ),
                ),
                (
                    "mend_intensity_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Multiplied by the caster's eff_intensity and added to the outcome-tier mend amount, before mend_wound()'s never-to-full cap is applied (0 = power has no effect, today's behavior).",
                        max_digits=5,
                    ),
                ),
                (
                    "backlash_target_condition",
                    models.ForeignKey(
                        blank=True,
                        help_text="When null, perform_treatment falls back to target_condition.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="treatment_backlash_source",
                        to="arxii.conditiontemplate",
                    ),
                ),
                (
                    "check_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="arxii.checktype"
                    ),
                ),
                (
                    "target_condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="treatments",
                        to="arxii.conditiontemplate",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="TechniqueDraftTreatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "target_kind",
                    models.CharField(
                        choices=[("self", "Self"), ("ally", "Ally"), ("enemy", "Enemy")],
                        default="ally",
                        max_length=16,
                    ),
                ),
                ("minimum_success_level", models.PositiveIntegerField(default=1)),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatments",
                        to="arxii.techniquedraft",
                    ),
                ),
                (
                    "treatment_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="draft_technique_payloads",
                        to="arxii.treatmenttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technique Draft Treatment",
                "verbose_name_plural": "Technique Draft Treatments",
            },
        ),
        migrations.CreateModel(
            name="TechniqueTreatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "target_kind",
                    models.CharField(
                        choices=[("self", "Self"), ("ally", "Ally"), ("enemy", "Enemy")],
                        default="ally",
                        max_length=16,
                    ),
                ),
                (
                    "minimum_success_level",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum success level required to perform this treatment.",
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatments",
                        to="arxii.technique",
                    ),
                ),
                (
                    "treatment_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="technique_payloads",
                        to="arxii.treatmenttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technique Treatment",
                "verbose_name_plural": "Technique Treatments",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("technique", "treatment_template"),
                        name="unique_treatment_per_technique",
                    )
                ],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
    ]
