# Generated by Django 5.2.15 on 2026-08-04 07:42


import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0043_initial_part_43"),
    ]

    operations = [
        migrations.AddField(
            model_name="technique",
            name="target_prerequisites",
            field=models.ManyToManyField(
                blank=True,
                help_text="Property-based targeting preconditions a target must satisfy (ALL must pass) to be a legal target for this technique.",
                related_name="gated_techniques",
                to="arxii.prerequisite",
            ),
        ),
        migrations.AddField(
            model_name="pathgiftgrant",
            name="starter_techniques",
            field=models.ManyToManyField(
                blank=True,
                help_text="Curated subset of this gift's techniques minted on crossing into this path.",
                related_name="granted_by_path_gifts",
                to="arxii.technique",
            ),
        ),
        migrations.AddField(
            model_name="alternateself",
            name="techniques",
            field=models.ManyToManyField(
                blank=True, related_name="alternate_self_grants", to="arxii.technique"
            ),
        ),
        migrations.AddField(
            model_name="technique",
            name="applied_conditions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Conditions this technique can apply, with formula-based scaling.",
                related_name="techniques_applying",
                through="arxii.TechniqueAppliedCondition",
                to="arxii.conditiontemplate",
            ),
        ),
        migrations.AddField(
            model_name="techniquedraft",
            name="restrictions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Restrictions applied for power bonuses.",
                related_name="technique_drafts",
                to="arxii.restriction",
            ),
        ),
        migrations.AddField(
            model_name="itemtemplate",
            name="interactions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Actions that can be performed on items of this type.",
                related_name="templates",
                through="arxii.TemplateInteraction",
                to="arxii.interactiontype",
            ),
        ),
        migrations.AddField(
            model_name="tenuregallery",
            name="allowed_viewers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tenures allowed to view this private gallery",
                related_name="shared_galleries",
                to="arxii.rostertenure",
            ),
        ),
        migrations.AddField(
            model_name="tenuregallery",
            name="tenure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="galleries",
                to="arxii.rostertenure",
            ),
        ),
        migrations.AddField(
            model_name="tenuremedia",
            name="gallery",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="arxii.tenuregallery",
            ),
        ),
        migrations.AddField(
            model_name="tenuremedia",
            name="tenure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="arxii.rostertenure",
            ),
        ),
        migrations.AddField(
            model_name="rosterentry",
            name="profile_picture",
            field=models.ForeignKey(
                blank=True,
                help_text="Profile picture for this character",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile_for_entries",
                to="arxii.tenuremedia",
            ),
        ),
        migrations.AddField(
            model_name="sceneactionpulldeclaration",
            name="threads",
            field=models.ManyToManyField(
                help_text="Threads pulled; owned by the actor, sharing ``resonance``.",
                related_name="action_pull_declarations",
                to="arxii.thread",
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="related_threads",
            field=models.ManyToManyField(
                blank=True, related_name="related_journal_entries", to="arxii.thread"
            ),
        ),
        migrations.AddField(
            model_name="combatpull",
            name="threads",
            field=models.ManyToManyField(related_name="combat_pulls", to="arxii.thread"),
        ),
        migrations.AddField(
            model_name="threadweavingunlock",
            name="paths",
            field=models.ManyToManyField(
                blank=True,
                help_text="Paths that treat this unlock as in-band (full xp_cost).",
                related_name="thread_weaving_unlocks",
                to="arxii.path",
            ),
        ),
    ]
