# Generated by Django 5.2.15 on 2026-08-04 07:42


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0044_initial_part_44"),
    ]

    operations = [
        migrations.AddField(
            model_name="threatpoolentry",
            name="conditions_applied",
            field=models.ManyToManyField(
                blank=True, related_name="threat_pool_entries", to="arxii.conditiontemplate"
            ),
        ),
        migrations.AddField(
            model_name="threatpoolentry",
            name="effect_properties",
            field=models.ManyToManyField(
                blank=True,
                help_text="Effect Properties this NPC attack carries. Drives clash-opposition matching against PC techniques' effect properties. Empty = attack cannot trigger or assist clashes.",
                related_name="threat_pool_entries",
                to="arxii.property",
            ),
        ),
        migrations.AddField(
            model_name="projecttemplate",
            name="tier_prerequisites",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tier thresholds the target building must already meet before this template can be commissioned. Empty = no prereqs.",
                related_name="gated_project_templates",
                to="arxii.tierthreshold",
            ),
        ),
        migrations.AddField(
            model_name="beginnings",
            name="traditions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Traditions available for this beginning during CG.",
                related_name="available_beginnings",
                through="arxii.BeginningTradition",
                to="arxii.tradition",
            ),
        ),
        migrations.AddField(
            model_name="traditiongiftgrant",
            name="special_techniques",
            field=models.ManyToManyField(
                blank=True,
                help_text="Techniques special to this tradition for this gift — additive extras on top of the path's starter pool. Empty = no tradition-specific extras. For partial-depth access, list only the restricted subset the tradition offers.",
                related_name="granted_by_tradition_gifts",
                to="arxii.technique",
            ),
        ),
        migrations.AddField(
            model_name="characterclass",
            name="core_traits",
            field=models.ManyToManyField(
                blank=True,
                help_text="Core traits associated with this class",
                related_name="classes_requiring_trait",
                to="arxii.trait",
            ),
        ),
        migrations.AddField(
            model_name="trap",
            name="detected_by",
            field=models.ManyToManyField(
                blank=True,
                help_text="Characters for whom this trap is resolved — they spotted or already triggered it, so it neither re-triggers nor stays hidden for them.",
                related_name="detected_traps",
                to="arxii.charactersheet",
            ),
        ),
        migrations.AddField(
            model_name="treasuredsubject",
            name="excluded_tenures",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tenures explicitly excluded even if otherwise visible.",
                related_name="%(class)s_excluded",
                to="arxii.rostertenure",
            ),
        ),
        migrations.AddField(
            model_name="treasuredsubject",
            name="visible_to_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Consent groups who can see this (if mode is 'groups').",
                related_name="%(class)s_visible",
                to="arxii.consentgroup",
            ),
        ),
        migrations.AddField(
            model_name="treasuredsubject",
            name="visible_to_tenures",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tenures who can see this (if mode is 'characters').",
                related_name="%(class)s_visible",
                to="arxii.rostertenure",
            ),
        ),
        migrations.AddField(
            model_name="conditiontemplate",
            name="reactive_triggers",
            field=models.ManyToManyField(
                blank=True,
                help_text="TriggerDefinitions installed as Trigger rows on the bearer when an instance of this template is applied. Cleanup is automatic via Trigger.source_condition CASCADE on ConditionInstance deletion.",
                related_name="installing_templates",
                to="arxii.triggerdefinition",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="required_trust_categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Trust categories required to participate in this story",
                through="arxii.StoryTrustRequirement",
                to="arxii.trustcategory",
            ),
        ),
        migrations.AddField(
            model_name="playertrust",
            name="trust_categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Trust categories and levels for this player",
                through="arxii.PlayerTrustLevel",
                to="arxii.trustcategory",
            ),
        ),
        migrations.AddField(
            model_name="storyfeedback",
            name="trust_categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Trust categories this feedback applies to with ratings",
                through="arxii.TrustCategoryFeedbackRating",
                to="arxii.trustcategory",
            ),
        ),
    ]
