# Generated by Django 5.2.15 on 2026-08-04 07:42


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0046_initial_part_46"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tarotcard", unique_together={("arcana_type", "suit", "rank")}
        ),
        migrations.AlterUniqueTogether(
            name="threadcrossingthreshold", unique_together={("target_kind", "level")}
        ),
        migrations.AddConstraint(
            model_name="threadpullcost",
            constraint=models.UniqueConstraint(
                condition=models.Q(("target_kind__isnull", True)),
                fields=("tier",),
                name="threadpullcost_tier_universal",
            ),
        ),
        migrations.AddConstraint(
            model_name="threadpullcost",
            constraint=models.UniqueConstraint(
                condition=models.Q(("target_kind__isnull", False)),
                fields=("tier", "target_kind"),
                name="threadpullcost_tier_kind",
            ),
        ),
        migrations.AddIndex(
            model_name="trait",
            index=models.Index(
                fields=["trait_type", "category"], name="arxii_trait_trait_t_8ba2d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trait",
            index=models.Index(fields=["is_public"], name="arxii_trait_is_publ_aa8f80_idx"),
        ),
        migrations.AddConstraint(
            model_name="weaponclass",
            constraint=models.CheckConstraint(
                condition=models.Q(("strength_tenths__lte", 10)),
                name="items_weaponclass_strength_tenths_max_ten",
            ),
        ),
        migrations.AddConstraint(
            model_name="appetiteupkeepreceipt",
            constraint=models.UniqueConstraint(
                fields=("character_sheet", "upkeep", "period_start"),
                name="unique_appetite_upkeep_receipt_per_period",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="auraaffinitythreshold", unique_together={("affinity", "threshold_percent")}
        ),
        migrations.AddConstraint(
            model_name="battleround",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["declaring", "resolving", "between_rounds"])),
                fields=("battle",),
                name="unique_active_battle_round",
            ),
        ),
        migrations.AddConstraint(
            model_name="battleside",
            constraint=models.UniqueConstraint(
                fields=("battle", "role"), name="unique_battle_side_role"
            ),
        ),
        migrations.AddConstraint(
            model_name="battleparticipant",
            constraint=models.UniqueConstraint(
                fields=("battle", "character_sheet"), name="unique_battle_participant"
            ),
        ),
        migrations.AddConstraint(
            model_name="blueprintbattleplace",
            constraint=models.UniqueConstraint(
                fields=("blueprint", "name"), name="unique_blueprint_place_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="business",
            constraint=models.UniqueConstraint(
                fields=("owner_persona", "name"), name="business_name_unique_per_owner"
            ),
        ),
    ]
