# Generated by Django 5.2.15 on 2026-08-04 07:42


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0047_initial_part_47"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="battleunittemplatecapability",
            constraint=models.UniqueConstraint(
                fields=("template", "capability"), name="unique_battle_unit_template_capability"
            ),
        ),
        migrations.AddConstraint(
            model_name="auderemajorafaithvariantcapabilitygrant",
            constraint=models.UniqueConstraint(
                fields=("faith_variant", "capability"), name="faith_variant_cap_grant_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="ceremonyhonoree",
            constraint=models.UniqueConstraint(
                fields=("ceremony", "honoree_sheet"), name="unique_ceremony_honoree"
            ),
        ),
        migrations.AddIndex(
            model_name="characterclasslevel",
            index=models.Index(fields=["character"], name="arxii_chara_charact_870370_idx"),
        ),
        migrations.AddIndex(
            model_name="characterclasslevel",
            index=models.Index(
                fields=["character", "level"], name="arxii_chara_charact_0592c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="characterclasslevel",
            index=models.Index(
                fields=["character", "is_primary"], name="arxii_chara_charact_a06684_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="characterclasslevel", unique_together={("character", "character_class")}
        ),
        migrations.AddIndex(
            model_name="characterunlock",
            index=models.Index(
                fields=["character", "-unlocked_date"], name="arxii_chara_charact_d518aa_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="characterunlock",
            unique_together={("character", "character_class", "target_level")},
        ),
        migrations.AddIndex(
            model_name="characterxp",
            index=models.Index(
                fields=["character", "transferable"], name="arxii_chara_charact_efaeb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="characterxptransaction",
            index=models.Index(
                fields=["character", "-transaction_date"], name="arxii_chara_charact_ca31e3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(name="checktype", unique_together={("name", "category")}),
        migrations.AlterUniqueTogether(
            name="checktypeaspect", unique_together={("check_type", "aspect")}
        ),
        migrations.AlterUniqueTogether(
            name="checktypecapabilitymodifier", unique_together={("check_type", "capability")}
        ),
        migrations.AddConstraint(
            model_name="clashround",
            constraint=models.UniqueConstraint(
                fields=("clash", "round_number"), name="unique_round_per_clash"
            ),
        ),
    ]
