# Generated by Django 5.2.15 on 2026-08-04 07:42


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0051_initial_part_51"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="conditionresistancemodifier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("condition__isnull", False)),
                fields=("condition", "damage_type"),
                name="resistance_modifier_unique_condition",
            ),
        ),
        migrations.AddConstraint(
            model_name="conditionresistancemodifier",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stage__isnull", False)),
                fields=("stage", "damage_type"),
                name="resistance_modifier_unique_stage",
            ),
        ),
        migrations.AddConstraint(
            model_name="conditiondamageovertime",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("condition__isnull", False), ("stage__isnull", True)),
                    models.Q(("condition__isnull", True), ("stage__isnull", False)),
                    _connector="OR",
                ),
                name="arxii_conditiondamageovertime_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="conditiondamageovertime",
            constraint=models.UniqueConstraint(
                condition=models.Q(("condition__isnull", False)),
                fields=("condition", "damage_type"),
                name="damage_over_time_unique_condition",
            ),
        ),
        migrations.AddConstraint(
            model_name="conditiondamageovertime",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stage__isnull", False)),
                fields=("stage", "damage_type"),
                name="damage_over_time_unique_stage",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conditiondamageinteraction", unique_together={("condition", "damage_type")}
        ),
        migrations.AddConstraint(
            model_name="blueprintpositionshelter",
            constraint=models.UniqueConstraint(
                fields=("blueprint_position", "damage_type"), name="unique_bp_position_shelter"
            ),
        ),
        migrations.AddConstraint(
            model_name="decorationaffinity",
            constraint=models.UniqueConstraint(
                fields=("kind", "stat_key"), name="unique_decoration_affinity_per_axis"
            ),
        ),
        migrations.AddConstraint(
            model_name="characterachievement",
            constraint=models.UniqueConstraint(
                fields=("character_sheet", "achievement"), name="unique_character_achievement"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="distinctioncodexgrant", unique_together={("distinction", "entry")}
        ),
        migrations.AlterUniqueTogether(
            name="distinctionprerequisite", unique_together={("distinction", "key")}
        ),
        migrations.AddConstraint(
            model_name="distinctionregardseed",
            constraint=models.UniqueConstraint(
                fields=("distinction", "npc_persona"), name="unique_distinction_regard_seed"
            ),
        ),
        migrations.AddConstraint(
            model_name="dramaticsurgerecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subject_sheet__isnull", False)),
                fields=("encounter", "participant", "trigger_kind", "subject_sheet"),
                name="unique_surge_with_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="dramaticsurgerecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subject_sheet__isnull", True)),
                fields=("encounter", "participant", "trigger_kind"),
                name="unique_surge_without_subject",
            ),
        ),
    ]
