# Generated by Django 5.2.15 on 2026-08-04 07:42


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0054_initial_part_54"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="houseclaimaspect",
            constraint=models.UniqueConstraint(
                fields=("claim", "option"), name="unique_claim_option"
            ),
        ),
        migrations.AddConstraint(
            model_name="consequenceoutcome",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("combat_interaction__isnull", False), ("challenge_record__isnull", True)
                    ),
                    models.Q(
                        ("combat_interaction__isnull", True), ("challenge_record__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="consequence_outcome_exactly_one_source",
            ),
        ),
        migrations.AddIndex(
            model_name="interactionaction",
            index=models.Index(fields=["pose", "ordering"], name="arxii_inter_pose_id_495983_idx"),
        ),
        migrations.AddIndex(
            model_name="interactionaction",
            index=models.Index(
                fields=["action_interaction"], name="arxii_inter_action__1f107b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="interactionaction",
            constraint=models.UniqueConstraint(
                fields=("pose", "action_interaction"), name="unique_action_link_per_pose"
            ),
        ),
        migrations.AddIndex(
            model_name="interactionpowerledgerentry",
            index=models.Index(
                fields=["interaction", "ordering"], name="arxii_inter_interac_d073e3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="interactionreaction",
            constraint=models.UniqueConstraint(
                fields=("interaction", "account", "emoji"), name="unique_interaction_reaction"
            ),
        ),
        migrations.AddIndex(
            model_name="interactionreceiver",
            index=models.Index(
                fields=["persona", "interaction"], name="arxii_inter_persona_015680_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interactionreceiver",
            index=models.Index(fields=["timestamp"], name="interactionreceiver_ts_brin"),
        ),
        migrations.AddConstraint(
            model_name="interactionreceiver",
            constraint=models.UniqueConstraint(
                fields=("interaction", "persona"), name="unique_receiver_per_interaction"
            ),
        ),
        migrations.AddConstraint(
            model_name="interactiontargetpersona",
            constraint=models.UniqueConstraint(
                fields=("interaction", "persona"), name="unique_target_per_interaction"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemcheckmodifier",
            constraint=models.UniqueConstraint(
                fields=("template", "check_type"),
                name="items_unique_itemcheckmodifier_per_template_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemtemplateappearanceeffect",
            constraint=models.UniqueConstraint(
                fields=("item_template", "trait"),
                name="items_one_appearance_effect_per_trait_per_template",
            ),
        ),
        migrations.AddConstraint(
            model_name="journaltag",
            constraint=models.UniqueConstraint(
                fields=("entry", "name"), name="unique_tag_per_entry"
            ),
        ),
    ]
