# Generated by Django 5.2.16 on 2026-09-05 23:20


from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

from core_management.batched_migration import BatchedCreateModelMigration
from world.migrations._generations import replaced_slice


class Migration(BatchedCreateModelMigration):
    dependencies = [
        ("arxii", "0056_g2_part_56"),
    ]

    replaces = replaced_slice(57, 103)
    operations = [
        migrations.CreateModel(
            name="BugReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("description", models.TextField(help_text="What the player observed.")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("reviewed", "Reviewed"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "github_issue_number",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="GitHub issue number, once staff have filed one from this report (#1164).",
                        null=True,
                    ),
                ),
                (
                    "github_issue_url",
                    models.URLField(
                        blank=True, help_text="Link to the filed GitHub issue (empty until filed)."
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "reporter_account",
                    models.ForeignKey(
                        help_text="The account that submitted this.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter_persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bug_reports",
                        to="arxii.persona",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="BuildingActivationDetails",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="building_activation_details",
                        serialize=False,
                        to="arxii.project",
                    ),
                ),
                (
                    "target_tier",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Decayed"),
                            (1, "Ramshackle"),
                            (2, "Worn"),
                            (3, "Fine"),
                            (4, "Good"),
                            (5, "Excellent"),
                            (6, "Extravagantly Polished"),
                            (7, "Immaculate"),
                        ],
                        help_text="Snapshot of the granting profile's activation_target_tier at commission time.",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When condition_tier was set; NULL until the handler runs. Idempotency marker.",
                        null=True,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activation_details",
                        to="arxii.building",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Building activation details"},
        ),
        migrations.CreateModel(
            name="BuildingExtensionDetails",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="building_extension_details",
                        serialize=False,
                        to="arxii.project",
                    ),
                ),
                (
                    "added_budget",
                    models.PositiveIntegerField(
                        help_text="Space-budget units this extension adds on completion.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the budget was applied; NULL until the handler runs. Idempotency marker.",
                        null=True,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extension_details",
                        to="arxii.building",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Building extension details"},
        ),
        migrations.CreateModel(
            name="BuildingPreparationDetails",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="building_preparation_details",
                        serialize=False,
                        to="arxii.project",
                    ),
                ),
                (
                    "target_tier",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Decayed"),
                            (1, "Ramshackle"),
                            (2, "Worn"),
                            (3, "Fine"),
                            (4, "Good"),
                            (5, "Excellent"),
                            (6, "Extravagantly Polished"),
                            (7, "Immaculate"),
                        ],
                        help_text="Condition tier applied on completion (current tier + 1 at commission).",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the tier was applied; NULL until the handler runs. Idempotency marker.",
                        null=True,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preparation_details",
                        to="arxii.building",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Building preparation details"},
        ),
        migrations.CreateModel(
            name="BuildingRenovationDetails",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="building_renovation_details",
                        serialize=False,
                        to="arxii.project",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the kind was re-pointed; NULL until the handler runs. Idempotency marker.",
                        null=True,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renovation_details",
                        to="arxii.building",
                    ),
                ),
                (
                    "target_kind",
                    models.ForeignKey(
                        help_text="The catalog BuildingKind this building is re-pointed to on completion.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="renovation_targets",
                        to="arxii.buildingkind",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Building renovation details"},
        ),
        migrations.CreateModel(
            name="BuildingUpgradeDetails",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="building_upgrade_details",
                        serialize=False,
                        to="arxii.project",
                    ),
                ),
                (
                    "new_target_size",
                    models.PositiveSmallIntegerField(
                        help_text="Size tier this upgrade targets on completion.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the size was applied; NULL until the handler runs. Idempotency marker.",
                        null=True,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upgrade_details",
                        to="arxii.building",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Building upgrade details"},
        ),
        migrations.CreateModel(
            name="CityDefenseDetails",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="city_defense_details",
                        serialize=False,
                        to="arxii.project",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the handler runs; idempotency guard (claim-filter pattern).",
                        null=True,
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        help_text="The defended region. PROTECT prevents deleting an area with a defense project.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="city_defense_projects",
                        to="arxii.area",
                    ),
                ),
                (
                    "outcome_tier",
                    models.ForeignKey(
                        blank=True,
                        help_text="The graded outcome tier, set when the handler runs at deadline.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="city_defense_projects",
                        to="arxii.checkoutcome",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="CityDefenseTierThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "min_progress",
                    models.PositiveIntegerField(
                        help_text="Minimum progress at which this tier applies."
                    ),
                ),
                (
                    "outcome_tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="city_defense_thresholds",
                        to="arxii.checkoutcome",
                    ),
                ),
                (
                    "details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tier_thresholds",
                        to="arxii.citydefensedetails",
                    ),
                ),
            ],
            options={
                "ordering": ["-min_progress"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("details", "outcome_tier"), name="uniq_city_defense_tier"
                    )
                ],
            },
        ),
    ]
