# Generated by Django 5.2.16 on 2026-09-06 00:50


from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

from core_management.batched_migration import BatchedCreateModelMigration
from world.migrations._generations import replaced_slice


class Migration(BatchedCreateModelMigration):
    dependencies = [
        ("arxii", "0061_g2_part_61"),
    ]

    replaces = replaced_slice(62, 103)
    operations = [
        migrations.CreateModel(
            name="CarriedBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "carried",
                    models.OneToOneField(
                        help_text="The character being carried.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carried_by",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "carrier",
                    models.OneToOneField(
                        help_text="The character doing the carrying.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carrying_body",
                        to="arxii.charactersheet",
                    ),
                ),
            ],
            options={"verbose_name": "Carried Body", "verbose_name_plural": "Carried Bodies"},
        ),
        migrations.CreateModel(
            name="CatalogSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "proposal_kind",
                    models.CharField(
                        choices=[
                            ("new_situation", "New Situation"),
                            ("check_fit", "Check Fit"),
                            ("difficulty_guide", "Difficulty Guide"),
                            ("pool_guide", "Pool Guide"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "proposal_text",
                    models.TextField(help_text="Freeform: what the GM is proposing, and why."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("reviewed", "Reviewed"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff account that reviewed this suggestion.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        help_text="OOC authoring, not IC -- mirrors GMApplication.account, not persona-anchored.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "situation_kind",
                    models.ForeignKey(
                        blank=True,
                        help_text="The kind this suggestion relates to, if any (e.g. a check-fit proposal).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggestions",
                        to="arxii.situationkind",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catalog Suggestion",
                "verbose_name_plural": "Catalog Suggestions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ceremony",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "quality_level",
                    models.IntegerField(
                        blank=True,
                        help_text="Success level of the officiant's Rites roll at finish (null until then).",
                        null=True,
                    ),
                ),
                (
                    "officiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ceremonies_officiated",
                        to="arxii.persona",
                    ),
                ),
                (
                    "ceremony_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ceremonies",
                        to="arxii.ceremonytype",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ceremonies",
                        to="arxii.event",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ceremonies",
                        to="arxii.roomprofile",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ceremonies",
                        to="arxii.scene",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        help_text="CORONATION only: the already-held title being solemnized (#2358).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coronation_ceremonies",
                        to="arxii.title",
                    ),
                ),
                (
                    "being",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ceremonies",
                        to="arxii.worshippedbeing",
                    ),
                ),
                (
                    "presented_being",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="arxii.worshippedbeing",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ceremonies",
                "ordering": ["-opened_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "open")),
                        fields=("location",),
                        name="one_open_ceremony_per_location",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Coronation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("crowned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ceremony",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coronation",
                        to="arxii.ceremony",
                    ),
                ),
                (
                    "honoree_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coronations",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coronations",
                        to="arxii.title",
                    ),
                ),
            ],
            options={
                "ordering": ["-crowned_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("honoree_sheet", "title"),
                        name="unique_coronation_per_honoree_title",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CeremonyHonoree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("prestige_awarded", models.BigIntegerField(default=0)),
                (
                    "ceremony",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="honorees",
                        to="arxii.ceremony",
                    ),
                ),
                (
                    "honoree_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ceremony_honors",
                        to="arxii.charactersheet",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ceremony", "honoree_sheet"), name="unique_ceremony_honoree"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SeanceManifestationOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ceremony_honoree",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seance_offer",
                        to="arxii.ceremonyhonoree",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="WeddingConsentOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ceremony_honoree",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wedding_consent_offer",
                        to="arxii.ceremonyhonoree",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
