# Generated by Django 5.2.15 on 2026-08-04 07:42


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0064_initial_part_64"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="challengetemplateproperty",
            constraint=models.UniqueConstraint(
                fields=("challenge_template", "property"), name="challenge_template_property_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="challengeapproach",
            constraint=models.UniqueConstraint(
                fields=("challenge_template", "application"),
                name="challenge_approach_unique_per_template",
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                fields=("capability", "target_property", "name"),
                name="application_unique_cap_prop_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertydamagemodifier",
            constraint=models.UniqueConstraint(
                fields=("property", "damage_type"), name="property_damage_modifier_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="pursedrainweek",
            constraint=models.UniqueConstraint(
                fields=("character_sheet", "game_week"), name="purse_drain_week_unique_per_sheet"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemfacet",
            constraint=models.UniqueConstraint(
                fields=("item_instance", "facet"), name="items_unique_itemfacet_per_instance"
            ),
        ),
        migrations.AddConstraint(
            model_name="craftingskillcap",
            constraint=models.UniqueConstraint(
                fields=("recipe", "min_skill_value"),
                name="items_craftingskillcap_recipe_min_skill_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="craftingmaterialrequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("item_template__isnull", False), ("material_category__isnull", True)),
                    models.Q(("item_template__isnull", True), ("material_category__isnull", False)),
                    _connector="OR",
                ),
                name="items_craftingmaterialrequirement_template_xor_category",
            ),
        ),
        migrations.AddConstraint(
            model_name="craftingmaterialrequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("required_value__isnull", True),
                    ("material_category__isnull", False),
                    _connector="OR",
                ),
                name="items_craftingmaterialrequirement_value_needs_category",
            ),
        ),
        migrations.AddConstraint(
            model_name="crafteditemrecipe",
            constraint=models.UniqueConstraint(
                fields=("item_instance", "recipe"), name="items_crafteditemrecipe_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="rampartelementresistance",
            constraint=models.UniqueConstraint(
                fields=("profile", "damage_type"), name="unique_rampart_resistance_per_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="randomscenetarget",
            constraint=models.UniqueConstraint(
                fields=("account", "game_week", "slot_number"), name="unique_rs_target_per_slot"
            ),
        ),
        migrations.AddConstraint(
            model_name="nobiliaryparticle",
            constraint=models.UniqueConstraint(
                fields=("realm", "family_type"), name="societies_particle_unique_per_realm_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="houserecognitionrule",
            constraint=models.UniqueConstraint(
                fields=("realm", "kind"), name="societies_recognition_rule_unique"
            ),
        ),
    ]
