# Generated by Django 5.2.15 on 2026-08-04 07:42


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0068_initial_part_68"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="roomalarmdetails",
            constraint=models.CheckConstraint(
                condition=models.Q(("level__gte", 1)), name="room_alarm_details_level_gte_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="portalanchor",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dissolved_at__isnull", True)),
                fields=("room_profile", "kind"),
                name="portal_anchor_unique_active_room_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.UniqueConstraint(
                condition=models.Q(("room__isnull", False)),
                fields=("room", "name"),
                name="unique_place_per_room",
            ),
        ),
        migrations.AddConstraint(
            model_name="npcassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("room", "assignment_role"),
                name="unique_active_npc_assignment_per_room_role",
            ),
        ),
        migrations.AddIndex(
            model_name="missionoption",
            index=models.Index(
                condition=models.Q(("authored_ic_framing_needs_rewrite", True)),
                fields=["node"],
                name="mo_flag_partial_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="missionoption",
            constraint=models.UniqueConstraint(
                fields=("node", "key"), name="unique_missionoption_node_key"
            ),
        ),
        migrations.AddIndex(
            model_name="missionnode",
            index=models.Index(
                condition=models.Q(("flavor_text_needs_rewrite", True)),
                fields=["template"],
                name="mn_flag_partial_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="missionnode",
            constraint=models.UniqueConstraint(
                fields=("template", "key"), name="unique_missionnode_template_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="locationvalueoverride",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("area__isnull", False), models.Q(("stat_key", ""), _negated=True)
                ),
                fields=("area", "stat_key"),
                name="unique_override_per_area_stat",
            ),
        ),
        migrations.AddConstraint(
            model_name="locationvalueoverride",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("room_profile__isnull", False), models.Q(("stat_key", ""), _negated=True)
                ),
                fields=("room_profile", "stat_key"),
                name="unique_override_per_room_stat",
            ),
        ),
        migrations.AddConstraint(
            model_name="locationvalueoverride",
            constraint=models.UniqueConstraint(
                condition=models.Q(("area__isnull", False), ("resonance__isnull", False)),
                fields=("area", "resonance"),
                name="unique_override_per_area_resonance",
            ),
        ),
        migrations.AddConstraint(
            model_name="locationvalueoverride",
            constraint=models.UniqueConstraint(
                condition=models.Q(("room_profile__isnull", False), ("resonance__isnull", False)),
                fields=("room_profile", "resonance"),
                name="unique_override_per_room_resonance",
            ),
        ),
        migrations.AddConstraint(
            model_name="locationvalueoverride",
            constraint=models.UniqueConstraint(
                condition=models.Q(("area__isnull", False), ("damage_type__isnull", False)),
                fields=("area", "damage_type"),
                name="unique_override_per_area_damage_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="locationvalueoverride",
            constraint=models.UniqueConstraint(
                condition=models.Q(("room_profile__isnull", False), ("damage_type__isnull", False)),
                fields=("room_profile", "damage_type"),
                name="unique_override_per_room_damage_type",
            ),
        ),
        migrations.AddIndex(
            model_name="locationvaluemodifier",
            index=models.Index(fields=["area", "stat_key"], name="arxii_locat_area_id_63f440_idx"),
        ),
    ]
