# Generated by Django 5.2.16 on 2026-09-05 23:20


import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

import core.mixins
import core.natural_keys
from core_management.batched_migration import BatchedCreateModelMigration
from world.migrations._generations import replaced_slice


class Migration(BatchedCreateModelMigration):
    dependencies = [
        ("arxii", "0069_g2_part_69"),
    ]

    replaces = replaced_slice(70, 103)
    operations = [
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "joined_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the persona joined this organization"
                    ),
                ),
                (
                    "left_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the persona voluntarily left the organization",
                        null=True,
                    ),
                ),
                (
                    "exiled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the persona was forcibly removed from the organization",
                        null=True,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The organization this membership belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="arxii.organization",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        help_text="The persona (character identity) that holds this membership",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_memberships",
                        to="arxii.persona",
                    ),
                ),
                (
                    "rank",
                    models.ForeignKey(
                        blank=True,
                        help_text="Rank rung held within this organization",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="arxii.organizationrank",
                    ),
                ),
                (
                    "covert_secret",
                    models.ForeignKey(
                        blank=True,
                        help_text="The subject-anchored Secret minted when this membership joined a covert org (#2820) — 'who is in the network' is playable through the clue→secret machinery. Level tracks rank tier. Survives leaving (having been a member remains a secret). NULL for overt orgs.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.secret",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        blank=True,
                        help_text="The CG Vacancy this membership was minted from (#3648); null otherwise.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="arxii.vacancy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Membership",
                "verbose_name_plural": "Organization Memberships",
                "ordering": ["organization", "rank__tier", "persona__name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("exiled_at__isnull", True), ("left_at__isnull", True)),
                        fields=("organization", "persona"),
                        name="unique_active_org_membership",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ResearchProjectDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "clue",
                    models.ForeignKey(
                        help_text="The clue whose target this project researches toward.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_projects",
                        to="arxii.clue",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_details",
                        to="arxii.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Project Details",
                "verbose_name_plural": "Research Project Details",
            },
        ),
        migrations.CreateModel(
            name="RoomClue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "detect_difficulty",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Search-check target difficulty to spot this clue here. Placeholder.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this clue is currently findable in the room.",
                    ),
                ),
                (
                    "eligibility_rule",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Predicate rule gating WHO may discover this placement (identity / org / resonance / species, evaluated via world.predicates). Empty {} = open to anyone — the default; add a rule to restrict. Same shape as MissionTemplate.visibility_rule.",
                    ),
                ),
                (
                    "fixture_key",
                    models.CharField(
                        blank=True,
                        help_text="Permanent stable identifier for authored (exported) clue placements, e.g. 'arx-city/golden-hart-taproom/torn-letter' (#2451). Set when the placement is authored via the world-builder canvas; NULL for ad hoc/test rows.",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "clue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_placements",
                        to="arxii.clue",
                    ),
                ),
                (
                    "room_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hidden_clues",
                        to="arxii.roomprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Clue",
                "verbose_name_plural": "Room Clues",
                "ordering": ["room_profile", "clue"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("room_profile", "clue"), name="room_clue_unique_room_clue"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SecretGossip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "heat",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Spread heat: ≥1 findable, decays toward the floor, public at the threshold.",
                    ),
                ),
                (
                    "went_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether heat crossed the public threshold (one-shot: ambient + exposure).",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    models.ForeignKey(
                        help_text="The region (Area at AreaLevel.REGION) this heat is scoped to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gossip_heat",
                        to="arxii.area",
                    ),
                ),
                (
                    "secret",
                    models.ForeignKey(
                        help_text="The Level-1 secret being gossiped.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gossip_heat",
                        to="arxii.secret",
                    ),
                ),
            ],
            options={
                "verbose_name": "Secret gossip",
                "verbose_name_plural": "Secret gossip",
                "indexes": [
                    models.Index(fields=["region", "heat"], name="arxii_secre_region__d5f215_idx")
                ],
                "unique_together": {("secret", "region")},
            },
        ),
        migrations.CreateModel(
            name="SecretKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "knows_category",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this knower has placed the secret's category (else it reads Unknown).",
                    ),
                ),
                (
                    "knows_consequences",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this knower has learned the secret's consequences.",
                    ),
                ),
                ("found_at", models.DateTimeField(auto_now_add=True)),
                (
                    "roster_entry",
                    models.ForeignKey(
                        help_text="The character who holds this knowledge.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secrets_known",
                        to="arxii.rosterentry",
                    ),
                ),
                (
                    "secret",
                    models.ForeignKey(
                        help_text="The secret this character knows.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="known_by",
                        to="arxii.secret",
                    ),
                ),
            ],
            options={
                "verbose_name": "Secret knowledge",
                "verbose_name_plural": "Secret knowledge",
                "ordering": ["-found_at"],
                "unique_together": {("roster_entry", "secret")},
            },
        ),
        migrations.CreateModel(
            name="SecretVictim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "severity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional magnitude of the direct standing hit. Null = derive from secret level.",
                        null=True,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="The victim organization (collective victim).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secret_victimhoods",
                        to="arxii.organization",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        help_text="The victim persona (individual victim).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secret_victimhoods",
                        to="arxii.persona",
                    ),
                ),
                (
                    "secret",
                    models.ForeignKey(
                        help_text="The secret whose underlying fact harmed this entity.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="victims",
                        to="arxii.secret",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("organization__isnull", False), ("persona__isnull", True)),
                            models.Q(("organization__isnull", True), ("persona__isnull", False)),
                            _connector="OR",
                        ),
                        name="secret_victim_exactly_one_target",
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="SituationChallengeLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "target_object_name",
                    models.CharField(
                        help_text="Display name for the ObjectDB instantiate_situation creates to embody this challenge (e.g. 'the locked door'). Player-visible via ChallengeInstanceSerializer.target_object_name.",
                        max_length=100,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "challenge_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="situation_links",
                        to="arxii.challengetemplate",
                    ),
                ),
                (
                    "situation_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_links",
                        to="arxii.situationtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("situation_template", "challenge_template"),
                        name="situation_challenge_unique",
                    )
                ],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
    ]
