# Generated by Django 5.2.16 on 2026-09-05 23:20


import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

from core_management.batched_migration import BatchedCreateModelMigration
from world.migrations._generations import replaced_slice


class Migration(BatchedCreateModelMigration):
    dependencies = [
        ("arxii", "0071_g2_part_71"),
    ]

    replaces = replaced_slice(72, 103)
    operations = [
        migrations.CreateModel(
            name="PactCommitment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("dowry", "Dowry"),
                            ("subsidy", "Recurring Subsidy"),
                            ("crisis_response", "Crisis Response"),
                            ("residency", "Residency"),
                            ("custom", "Custom (prose)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "owed_by_senior",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the senior house owes this (dowries/subsidies usually do).",
                    ),
                ),
                (
                    "amount",
                    models.PositiveBigIntegerField(
                        default=0, help_text="Coppers: dowry lump (DOWRY kind). PLACEHOLDER."
                    ),
                ),
                (
                    "percent",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="SUBSIDY kind: percent of declared income owed per settlement (materialized as the OrgObligation's percent). PLACEHOLDER.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="CUSTOM commitments: the prose terms."),
                ),
                ("breached_at", models.DateTimeField(blank=True, null=True)),
                (
                    "committed_person",
                    models.ForeignKey(
                        blank=True,
                        help_text="The named Gifted for CRISIS_RESPONSE/RESIDENCY commitments.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pact_commitments",
                        to="arxii.kinsperson",
                    ),
                ),
                (
                    "obligation",
                    models.OneToOneField(
                        blank=True,
                        help_text="The materialized recurring obligation (SUBSIDY kind).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pact_commitment",
                        to="arxii.orgobligation",
                    ),
                ),
                (
                    "pact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commitments",
                        to="arxii.marriagepact",
                    ),
                ),
            ],
            options={"ordering": ["pact", "kind"]},
        ),
        migrations.CreateModel(
            name="ParentageEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("biological", "Biological"),
                            ("tree_of_souls", "Tree of Souls"),
                            ("vampiric_embrace", "Vampiric Embrace"),
                            ("adoptive", "Adoptive"),
                            ("foster", "Foster"),
                            ("acknowledged", "Acknowledged"),
                        ],
                        default="biological",
                        max_length=20,
                    ),
                ),
                (
                    "is_public_record",
                    models.BooleanField(
                        default=True, help_text="Whether the world believes this edge."
                    ),
                ),
                (
                    "is_true",
                    models.BooleanField(
                        default=True,
                        help_text="False = the official story, contradicted by a hidden-true edge.",
                    ),
                ),
                (
                    "is_ritual_invoker",
                    models.BooleanField(
                        default=False,
                        help_text="TREE_OF_SOULS only: this parent invoked the ritual and is the dominant line regardless of gender (#2815).",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        help_text="The child end of the edge.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parentage_up",
                        to="arxii.kinsperson",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        help_text="The parent end of the edge.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parentage_down",
                        to="arxii.kinsperson",
                    ),
                ),
                (
                    "secret",
                    models.ForeignKey(
                        blank=True,
                        help_text="Secret gating a hidden edge. Hidden with no secret = staff-only.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.secret",
                    ),
                ),
                (
                    "born_within_union",
                    models.ForeignKey(
                        blank=True,
                        help_text="The union this birth occurred within, if any (legitimacy input).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="births",
                        to="arxii.union",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("child", "parent", "kind"), name="roster_parentage_unique_per_kind"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_ritual_invoker", True)),
                        fields=("child",),
                        name="roster_parentage_one_invoker_per_child",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("child", models.F("parent")), _negated=True),
                        name="roster_parentage_no_self_loop",
                    ),
                ],
                "indexes": [
                    models.Index(
                        fields=["child", "is_public_record"], name="arxii_paren_child_i_21378f_idx"
                    ),
                    models.Index(
                        fields=["parent", "is_public_record"], name="arxii_paren_parent__8a9ebf_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorshipDeclaration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "public_is_sincere",
                    models.BooleanField(
                        default=True,
                        help_text="Heart vs lip service (#2361 Ratified amendment #2): whether the character genuinely believes the public declaration (True) or it is performative only (False). Set explicitly at conversion; defaults True for CG declarations, where public and inward faith are the same thing by construction. PRIVATE — never leaves owner/staff surfaces, same leak-table pattern as current_mood in world.character_sheets.serializers._build_identity.",
                    ),
                ),
                (
                    "character_sheet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worship_declaration",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "secret",
                    models.ForeignKey(
                        blank=True,
                        help_text="The minted worship Secret when secret_being is set.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.secret",
                    ),
                ),
                (
                    "public_being",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="public_worshippers",
                        to="arxii.worshippedbeing",
                    ),
                ),
                (
                    "secret_being",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="secret_worshippers",
                        to="arxii.worshippedbeing",
                    ),
                ),
            ],
            options={"ordering": ["id"]},
        ),
        migrations.CreateModel(
            name="AccusationRebuttal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("succeeded", models.BooleanField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "refuter_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accusation_rebuttals",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "secret",
                    models.ForeignKey(
                        help_text="The ACCUSATION secret whose credibility was attacked.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rebuttals",
                        to="arxii.secret",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accusation rebuttal",
                "verbose_name_plural": "Accusation rebuttals",
                "ordering": ["-created_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("secret", "refuter_sheet"), name="uniq_rebuttal_secret_refuter"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BattlePlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "terrain_type",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("difficult", "Difficult"),
                            ("fortified", "Fortified"),
                            ("elevated", "Elevated"),
                            ("flooded", "Flooded"),
                            ("urban", "Urban"),
                            ("water", "Open water"),
                            ("aerial", "Open sky"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "movement_cost",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Authored cost for a future reposition/movement action — not yet filed as an issue; #1712 explicitly did not build this. Data only.",
                    ),
                ),
                (
                    "weather_override_expires_round",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Absolute round number this place's weather_override expires at (#1715). Cleared alongside weather_override at round-boundary expiry.",
                        null=True,
                    ),
                ),
                (
                    "x",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Position on the battle's internal battle-map coordinate plane (#1714). Additive to ADR-0081, which only rejected anchoring BattlePlace to the room-level Position/PositionEdge graph — see ADR-0085.",
                        max_digits=8,
                    ),
                ),
                ("y", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                (
                    "footprint_radius",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="How much of the battle-map grid this place occupies (#1714). Two places overlap when the distance between their (x, y) centers is less than the sum of their footprint_radius values.",
                        max_digits=6,
                    ),
                ),
                (
                    "battle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="places",
                        to="arxii.battle",
                    ),
                ),
                (
                    "controlled_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which side currently holds this front as an objective (#1712, set by a successful HOLD declaration). None means uncontrolled/contested.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="controlled_places",
                        to="arxii.battleside",
                    ),
                ),
                (
                    "combat_encounter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bridge seam: discrete combat taking place at this front.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="battle_places",
                        to="arxii.combatencounter",
                    ),
                ),
                (
                    "weather_override",
                    models.ForeignKey(
                        blank=True,
                        help_text="Local weather exception at this front (#1715) — beats the Battle-level weather_override/ambient value here only (cover, wards, a hostile local squall). Cleared at round-boundary expiry.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overriding_battle_places",
                        to="arxii.weathertype",
                    ),
                ),
            ],
            options={
                "ordering": ["battle", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("battle", "name"), name="unique_battle_place_name"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Fortification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("wall", "Wall"),
                            ("gate", "Gate"),
                            ("battlement", "Battlement"),
                            ("hull", "Hull"),
                        ],
                        default="wall",
                        max_length=20,
                    ),
                ),
                ("integrity", models.PositiveSmallIntegerField(default=0)),
                (
                    "max_integrity",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Snapshotted once at creation from BASE_INTEGRITY[kind] plus building.fortification_level * FORTIFICATION_LEVEL_INTEGRITY_BONUS, if building is set (#1713). See world.battles.services.create_fortification.",
                    ),
                ),
                ("breached", models.BooleanField(default=False)),
                (
                    "defending_side",
                    models.ForeignKey(
                        help_text="The side this structure protects. BREACH requires the declaring participant's side to differ from this; FORTIFY requires it to match (#1713).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fortifications",
                        to="arxii.battleside",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fortifications",
                        to="arxii.battleplace",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional persistent Building this structure derives its integrity ceiling from (#1713). None means an ad-hoc, non-persistent structure.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="battle_fortifications",
                        to="arxii.building",
                    ),
                ),
            ],
            options={"ordering": ["place", "kind", "id"]},
        ),
        migrations.CreateModel(
            name="BattleParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "transit_x",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="In-progress MOVE position on the battle-map coordinate plane (#2007). Null when at rest — effective position is then simply this participant's .place coordinates. Mirrors BattlePlace.x's shape.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "transit_y",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("withdrawn", "Withdrawn"),
                            ("incapacitated", "Incapacitated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "battle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="arxii.battle",
                    ),
                ),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battle_participations",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participants",
                        to="arxii.battleplace",
                    ),
                ),
                (
                    "transit_target_place",
                    models.ForeignKey(
                        blank=True,
                        help_text="Destination of an in-progress multi-round MOVE (#2007). Null when at rest.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participants_in_transit",
                        to="arxii.battleplace",
                    ),
                ),
                (
                    "side",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="arxii.battleside",
                    ),
                ),
            ],
            options={
                "ordering": ["battle", "character_sheet"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("battle", "character_sheet"), name="unique_battle_participant"
                    )
                ],
            },
        ),
    ]
