# Generated by Django 5.2.15 on 2026-08-04 07:42


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0073_initial_part_73"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="entryflourishrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scene__isnull", False)),
                fields=("character_sheet", "scene"),
                name="one_entry_flourish_per_sheet_scene",
            ),
        ),
        migrations.AddIndex(
            model_name="dramaticmomenttag",
            index=models.Index(
                fields=["character_sheet", "tagged_at"], name="dramatic_tag_sheet_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="decisivecheckmarker",
            index=models.Index(fields=["scene", "status"], name="arxii_decis_scene_i_4afc5c_idx"),
        ),
        migrations.AddConstraint(
            model_name="decisivecheckmarker",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("scene",),
                name="one_pending_decisive_marker_per_scene",
            ),
        ),
        migrations.AddConstraint(
            model_name="cohortenrollment",
            constraint=models.UniqueConstraint(
                fields=("cohort", "persona"), name="cohort_enrollment_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="auderemajoracrossing",
            constraint=models.UniqueConstraint(
                fields=("character_sheet", "threshold"),
                name="one_crossing_per_character_per_threshold",
            ),
        ),
        migrations.AddConstraint(
            model_name="affectionshift",
            constraint=models.UniqueConstraint(
                condition=models.Q(("boon__isnull", True)),
                fields=("relationship", "scene", "effect"),
                name="unique_affection_shift_per_scene",
            ),
        ),
        migrations.AddConstraint(
            model_name="affectionshift",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effect__isnull", False), ("boon__isnull", False), _connector="OR"
                ),
                name="affection_shift_has_provenance",
            ),
        ),
        migrations.AddConstraint(
            model_name="sceneactiontarget",
            constraint=models.UniqueConstraint(
                fields=("action_request", "target_persona"), name="uniq_action_target"
            ),
        ),
        migrations.AddConstraint(
            model_name="scenecheckmodifier",
            constraint=models.UniqueConstraint(
                fields=("scene", "check_type"), name="scene_check_modifier_unique_scene_check_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="sceneentryendorsement",
            constraint=models.UniqueConstraint(
                fields=("endorser_sheet", "endorsee_sheet", "scene"),
                name="unique_scene_entry_endorsement_per_pair_per_scene",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sceneparticipation", unique_together={("scene", "account")}
        ),
        migrations.AddConstraint(
            model_name="scene",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event__isnull", False), ("is_active", True)),
                fields=("event",),
                name="unique_active_scene_per_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="sceneround",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["declaring", "resolving", "between_rounds"])),
                fields=("room",),
                name="one_active_scene_round_per_room",
            ),
        ),
        migrations.AddConstraint(
            model_name="sceneroundparticipant",
            constraint=models.UniqueConstraint(
                fields=("scene_round", "character_sheet"), name="unique_scene_round_participant"
            ),
        ),
    ]
