# Generated by Django 5.2.15 on 2026-08-04 07:42


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0074_initial_part_74"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="sceneunseenobserver",
            constraint=models.UniqueConstraint(
                fields=("scene", "observer"), name="unique_unseen_observer_per_scene"
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("exiled_at__isnull", True), ("left_at__isnull", True)),
                fields=("organization", "persona"),
                name="unique_active_org_membership",
            ),
        ),
        migrations.AddConstraint(
            model_name="leverage",
            constraint=models.UniqueConstraint(
                fields=("holder_sheet", "subject_sheet", "founded_on"),
                name="uniq_leverage_holder_subject_secret",
            ),
        ),
        migrations.AddConstraint(
            model_name="denouncerecord",
            constraint=models.UniqueConstraint(
                fields=("authorship_secret", "denouncer_sheet"),
                name="uniq_denounce_secret_denouncer",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="characterdistinction", unique_together={("character", "distinction")}
        ),
        migrations.AddConstraint(
            model_name="accusationrebuttal",
            constraint=models.UniqueConstraint(
                fields=("secret", "refuter_sheet"), name="uniq_rebuttal_secret_refuter"
            ),
        ),
        migrations.AddIndex(
            model_name="secretgossip",
            index=models.Index(fields=["region", "heat"], name="arxii_secre_region__d5f215_idx"),
        ),
        migrations.AlterUniqueTogether(name="secretgossip", unique_together={("secret", "region")}),
        migrations.AddConstraint(
            model_name="secretgrievance",
            constraint=models.UniqueConstraint(
                fields=("secret", "victim_sheet"), name="one_grievance_per_secret_victim"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="secretknowledge", unique_together={("roster_entry", "secret")}
        ),
        migrations.AddConstraint(
            model_name="secretvictim",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("organization__isnull", False), ("persona__isnull", True)),
                    models.Q(("organization__isnull", True), ("persona__isnull", False)),
                    _connector="OR",
                ),
                name="secret_victim_exactly_one_target",
            ),
        ),
        migrations.AddIndex(
            model_name="sessionrequest",
            index=models.Index(
                fields=["status", "created_at"], name="arxii_sessi_status_819150_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionrequest",
            index=models.Index(fields=["episode", "status"], name="arxii_sessi_episode_50f833_idx"),
        ),
        migrations.AddIndex(
            model_name="sessionrequest",
            index=models.Index(
                fields=["assigned_gm", "status"], name="arxii_sessi_assigne_75c78e_idx"
            ),
        ),
    ]
