# Generated by Django 5.2.15 on 2026-08-04 07:42


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0077_initial_part_77"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="npcregard",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("target_organization__isnull", False), ("ended_at__isnull", True)
                ),
                fields=("holder_persona", "target_organization"),
                name="unique_active_regard_target_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="npcregard",
            constraint=models.UniqueConstraint(
                condition=models.Q(("target_society__isnull", False), ("ended_at__isnull", True)),
                fields=("holder_persona", "target_society"),
                name="unique_active_regard_target_society",
            ),
        ),
        migrations.AddConstraint(
            model_name="justicecase",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "awaiting_trial")),
                fields=("persona", "area"),
                name="one_open_case_per_persona_area",
            ),
        ),
        migrations.AddIndex(
            model_name="fashionpresentation",
            index=models.Index(
                fields=["presenter", "created_at"], name="arxii_fashi_present_1206c2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="facetvoguemomentum",
            constraint=models.UniqueConstraint(
                fields=("society", "facet"), name="unique_facet_momentum"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("target_type", "persona")),
                fields=("event", "target_type", "target_persona"),
                name="unique_persona_invitation",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("target_type", "organization")),
                fields=("event", "target_type", "target_organization"),
                name="unique_organization_invitation",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("target_type", "society")),
                fields=("event", "target_type", "target_society"),
                name="unique_society_invitation",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["status", "scheduled_real_time"], name="arxii_event_status_47a133_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["location", "scheduled_real_time"], name="arxii_event_locatio_bdb762_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="societyreputation",
            constraint=models.UniqueConstraint(
                fields=("persona", "society"), name="unique_persona_society_reputation"
            ),
        ),
        migrations.AddConstraint(
            model_name="soulincarnation",
            constraint=models.UniqueConstraint(
                fields=("soul", "kinsperson"), name="roster_soul_incarnation_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="soultetherrescue",
            index=models.Index(
                fields=["sinner_sheet", "-created_at"], name="arxii_soult_sinner__e5bd60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="soultetherrescue",
            index=models.Index(
                fields=["sineater_sheet", "-created_at"], name="arxii_soult_sineate_4c11c1_idx"
            ),
        ),
    ]
