# Generated by Django 5.2.15 on 2026-08-04 07:42


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0079_initial_part_79"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="npcregardevent",
            index=models.Index(
                fields=["regard", "-created_date"], name="arxii_npcre_regard__1b49a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stake",
            index=models.Index(fields=["beat"], name="arxii_stake_beat_id_1ad8bc_idx"),
        ),
        migrations.AddConstraint(
            model_name="conditionstatrule",
            constraint=models.UniqueConstraint(
                fields=("stat", "condition", "event_type"), name="unique_condition_stat_rule"
            ),
        ),
        migrations.AddConstraint(
            model_name="achievementstatrequirement",
            constraint=models.UniqueConstraint(
                fields=("achievement", "stat", "threshold", "comparison"),
                name="unique_achievement_requirement",
            ),
        ),
        migrations.AddConstraint(
            model_name="stattracker",
            constraint=models.UniqueConstraint(
                fields=("character_sheet", "stat"), name="unique_character_stat"
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklisting",
            constraint=models.UniqueConstraint(
                fields=("stall", "template"), name="items_market_stock_unique_per_stall"
            ),
        ),
        migrations.AddIndex(
            model_name="narrativemessage",
            index=models.Index(
                fields=["category", "-sent_at"], name="arxii_narra_categor_5368f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="narrativemessage",
            index=models.Index(
                fields=["sender_account", "-sent_at"], name="arxii_narra_sender__60d8f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupstoryrequest",
            index=models.Index(
                fields=["status", "created_at"], name="arxii_group_status_5e2eae_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupstoryrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("covenant",),
                name="unique_pending_group_story_request_per_covenant",
            ),
        ),
        migrations.AddIndex(
            model_name="groupstoryprogress",
            index=models.Index(
                fields=["gm_table", "is_active"], name="arxii_group_gm_tabl_ddcdb0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupstoryprogress",
            constraint=models.UniqueConstraint(
                fields=("story", "gm_table"), name="unique_group_progress_per_story_per_table"
            ),
        ),
        migrations.AddIndex(
            model_name="globalstoryprogress",
            index=models.Index(fields=["is_active"], name="arxii_globa_is_acti_199355_idx"),
        ),
        migrations.AddIndex(
            model_name="gemit",
            index=models.Index(fields=["-sent_at"], name="arxii_gemit_sent_at_9e809f_idx"),
        ),
    ]
