# Generated by Django 5.2.15 on 2026-08-04 07:42


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0081_initial_part_81"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="storyprogress",
            constraint=models.UniqueConstraint(
                fields=("story", "character_sheet"), name="unique_progress_per_story_per_character"
            ),
        ),
        migrations.AddIndex(
            model_name="storyprotectedsubject",
            index=models.Index(
                fields=["subject_sheet", "is_active"], name="arxii_story_subject_57a555_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="custodyclearance",
            index=models.Index(
                fields=["protected_subject", "status"], name="arxii_custo_protect_5a94b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="custodyclearance",
            index=models.Index(
                fields=["requested_by", "status"], name="arxii_custo_request_f7b295_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="custodyclearance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("pending", "escalated"))),
                fields=("protected_subject", "requested_by", "scope"),
                name="unique_live_clearance_per_subject_requester_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="storyroomgrant",
            constraint=models.UniqueConstraint(
                fields=("room", "character"), name="unique_story_room_grant"
            ),
        ),
        migrations.AddConstraint(
            model_name="streamcommongempool",
            constraint=models.UniqueConstraint(
                fields=("income_stream", "tier"),
                name="items_streamcommongempool_stream_tier_unique",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="motifresonancestyle", unique_together={("motif_resonance", "style")}
        ),
        migrations.AddConstraint(
            model_name="itemstyle",
            constraint=models.UniqueConstraint(
                fields=("item_instance", "style"), name="items_unique_itemstyle_per_instance"
            ),
        ),
        migrations.AddIndex(
            model_name="fashionshowing",
            index=models.Index(
                fields=["settled", "created_at"], name="arxii_fashi_settled_769cfc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="styleaffinity",
            constraint=models.UniqueConstraint(
                fields=("style", "stat_key"), name="unique_style_affinity_per_axis"
            ),
        ),
        migrations.AddConstraint(
            model_name="stylepresentationendorsement",
            constraint=models.UniqueConstraint(
                fields=("endorser_sheet", "endorsee_sheet", "scene"),
                name="unique_style_presentation_per_pair_per_scene",
            ),
        ),
        migrations.AddIndex(
            model_name="tablebulletinpost",
            index=models.Index(
                fields=["table", "story", "-created_at"], name="arxii_table_table_i_bbf6c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tablebulletinpost",
            index=models.Index(
                fields=["author_persona", "-created_at"], name="arxii_table_author__c85161_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tableupdaterequest",
            index=models.Index(
                fields=["status", "membership"], name="arxii_table_status_18b952_idx"
            ),
        ),
    ]
