# Generated by Django 5.2.16 on 2026-09-05 23:20


import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

from core_management.batched_migration import BatchedCreateModelMigration
from world.migrations._generations import replaced_slice


class Migration(BatchedCreateModelMigration):
    dependencies = [
        ("arxii", "0082_g2_part_82"),
    ]

    replaces = replaced_slice(83, 103)
    operations = [
        migrations.CreateModel(
            name="CharacterRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this relationship is currently active"
                    ),
                ),
                (
                    "is_pending",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this relationship is awaiting mutual consent",
                    ),
                ),
                (
                    "is_deceitful",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the displayed track/tier differs from the actual values",
                    ),
                ),
                (
                    "developments_this_week",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of development updates submitted this week (max 7)",
                    ),
                ),
                (
                    "changes_this_week",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of relationship changes submitted this week"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this relationship was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this relationship was last modified"
                    ),
                ),
                (
                    "is_soul_tether",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this relationship is a soul-tether bond (Spec B mechanics).",
                    ),
                ),
                (
                    "soul_tether_role",
                    models.CharField(
                        blank=True,
                        choices=[("SINEATER", "Sineater"), ("SINNER", "Sinner")],
                        help_text="Soul-tether role (SINNER or SINEATER); empty when not a tether.",
                        max_length=16,
                    ),
                ),
                (
                    "magical_flavor",
                    models.TextField(
                        blank=True,
                        help_text="Player-authored descriptor of the bond's magical quality.",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="The character who holds this relationship",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_as_source",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        help_text="The character this relationship is about; null when target_companion is set (#3575). Exactly one of target / target_companion is set.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_as_target",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "target_companion",
                    models.ForeignKey(
                        blank=True,
                        help_text="The bonded companion this relationship is about (#3575); null when target is set. Only the companion's owner may hold such a row.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_as_companion_target",
                        to="arxii.companion",
                    ),
                ),
                (
                    "game_week",
                    models.ForeignKey(
                        blank=True,
                        help_text="GameWeek these weekly counters belong to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relationships",
                        to="arxii.gameweek",
                    ),
                ),
                (
                    "conditions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Conditions that exist on this relationship",
                        related_name="character_relationships",
                        to="arxii.relationshipcondition",
                    ),
                ),
                (
                    "displayed_tier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tier displayed publicly (for deceit); null = show actual",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.relationshiptier",
                    ),
                ),
                (
                    "displayed_track",
                    models.ForeignKey(
                        blank=True,
                        help_text="Track displayed publicly (for deceit); null = show actual",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.relationshiptrack",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("target__isnull", False)),
                        fields=("source", "target"),
                        name="unique_relationship_pair",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("target_companion__isnull", False)),
                        fields=("source", "target_companion"),
                        name="unique_relationship_companion_pair",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("target__isnull", False), ("target_companion__isnull", True)),
                            models.Q(("target__isnull", True), ("target_companion__isnull", False)),
                            _connector="OR",
                        ),
                        name="relationship_target_xor_companion",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source", models.F("target")), _negated=True),
                        name="relationship_source_not_target",
                    ),
                ]
            },
        ),
        migrations.CreateModel(
            name="PendingStageAdvanceOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "sinner_corruption_stage",
                    models.PositiveSmallIntegerField(
                        help_text="The stage the Sinner is currently at when the prompt fires."
                    ),
                ),
                (
                    "commit_units_max",
                    models.PositiveSmallIntegerField(
                        help_text="Maximum Hollow units the Sineater may commit."
                    ),
                ),
                (
                    "strain_cost_per_unit",
                    models.PositiveSmallIntegerField(
                        help_text="Strain severity added to the Sineater per committed unit."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Prompt expires after this time. Stale rows are deleted on next access."
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_stage_advance_offers",
                        to="arxii.characterrelationship",
                    ),
                ),
                (
                    "sineater_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_advance_offers_received",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "sinner_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_advance_offers_sent",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "resonance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pending_stage_advance_offers",
                        to="arxii.resonance",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        help_text="Active scene at prompt time. Row is only written when a shared scene is found.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_stage_advance_offers",
                        to="arxii.scene",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sinner_sheet", "sineater_sheet"),
                        name="one_pending_stage_advance_per_pair",
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="RelationshipBump",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="Denormalized from interaction for composite FK with partitioned table"
                    ),
                ),
                (
                    "valence",
                    models.SmallIntegerField(
                        choices=[(1, "Positive"), (-1, "Negative")],
                        help_text="+1 warms (Regard system track), -1 cools (Friction system track)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interaction",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="The pose/emit this bump acknowledges (anchor + dedup key)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationship_bumps",
                        to="arxii.interaction",
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        help_text="The directed (source→target) relationship this bump nudges",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bumps",
                        to="arxii.characterrelationship",
                    ),
                ),
                (
                    "source_emoji",
                    models.ForeignKey(
                        blank=True,
                        help_text="The catalog emoji that carried this bump (null = telnet rel plus/neg)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.reactionemoji",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("relationship", "interaction"), name="unique_bump_per_interaction"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RelationshipCapstone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the monumental moment", max_length=200),
                ),
                (
                    "writeup",
                    models.TextField(help_text="Narrative description of the capstone event"),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        help_text="Points added to both capacity and developed_points"
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("shared", "Shared"),
                            ("gossip", "Gossip"),
                            ("public", "Public"),
                        ],
                        default="shared",
                        help_text="Who can see this capstone",
                        max_length=20,
                    ),
                ),
                (
                    "is_ritual_capstone",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this capstone was created via a Ritual Capstone (Spec B §12.1).",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this capstone was recorded"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The character who recorded this capstone",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        help_text="The relationship this capstone applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capstones",
                        to="arxii.characterrelationship",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        help_text="The track that gains points and capacity",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="arxii.relationshiptrack",
                    ),
                ),
                (
                    "ritual",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when is_ritual_capstone=True; references the Ritual that was performed.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capstone_events",
                        to="arxii.ritual",
                    ),
                ),
                (
                    "linked_scene",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional scene this capstone is based on",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="arxii.scene",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="RelationshipChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title summarizing the change", max_length=200
                    ),
                ),
                (
                    "writeup",
                    models.TextField(
                        help_text="Narrative writeup describing why the relationship changed"
                    ),
                ),
                (
                    "points_moved",
                    models.PositiveIntegerField(help_text="Number of points moved between tracks"),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("shared", "Shared"),
                            ("gossip", "Gossip"),
                            ("public", "Public"),
                        ],
                        default="shared",
                        help_text="Who can see this change",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this change was created"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The character who authored this change",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        help_text="The relationship this change applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="arxii.characterrelationship",
                    ),
                ),
                (
                    "source_track",
                    models.ForeignKey(
                        help_text="The track losing points",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changes_from",
                        to="arxii.relationshiptrack",
                    ),
                ),
                (
                    "target_track",
                    models.ForeignKey(
                        help_text="The track gaining points",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changes_to",
                        to="arxii.relationshiptrack",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="RelationshipDevelopment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title summarizing the development", max_length=200
                    ),
                ),
                (
                    "writeup",
                    models.TextField(
                        help_text="Narrative writeup describing the reflection or development"
                    ),
                ),
                (
                    "points_earned",
                    models.PositiveIntegerField(
                        help_text="Permanent points added to the track (up to capacity)"
                    ),
                ),
                (
                    "xp_awarded",
                    models.PositiveIntegerField(
                        default=0, help_text="XP awarded to the character for this development"
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("shared", "Shared"),
                            ("gossip", "Gossip"),
                            ("public", "Public"),
                        ],
                        default="shared",
                        help_text="Who can see this development",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this development was created"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The character who performed this development",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        help_text="The relationship this development applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developments",
                        to="arxii.characterrelationship",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        help_text="The track that gains permanent points",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="arxii.relationshiptrack",
                    ),
                ),
                (
                    "linked_scene",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional scene this development is based on",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="arxii.scene",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
