# Generated by Django 5.2.16 on 2026-09-05 23:20


import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

from core_management.batched_migration import BatchedCreateModelMigration
from world.migrations._generations import replaced_slice


class Migration(BatchedCreateModelMigration):
    dependencies = [
        ("arxii", "0083_g2_part_83"),
    ]

    replaces = replaced_slice(84, 103)
    operations = [
        migrations.CreateModel(
            name="RelationshipTrackProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=0, help_text="Maximum developed points allowed on this track"
                    ),
                ),
                (
                    "developed_points",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Permanent points earned through development and capstones",
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        help_text="The relationship this progress belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="track_progress",
                        to="arxii.characterrelationship",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        help_text="The track being progressed",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="arxii.relationshiptrack",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("relationship", "track"), name="unique_progress_per_track"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="RelationshipUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title summarizing the update", max_length=200
                    ),
                ),
                (
                    "writeup",
                    models.TextField(
                        help_text="Narrative writeup describing how the relationship developed"
                    ),
                ),
                (
                    "points_earned",
                    models.PositiveIntegerField(
                        help_text="Points earned: increases capacity and sets temporary value base"
                    ),
                ),
                (
                    "coloring",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        help_text="Emotional coloring for first impressions (blank for normal updates)",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("shared", "Shared"),
                            ("gossip", "Gossip"),
                            ("public", "Public"),
                        ],
                        default="shared",
                        help_text="Who can see this update",
                        max_length=20,
                    ),
                ),
                (
                    "is_first_impression",
                    models.BooleanField(
                        default=False, help_text="Whether this is a first impression update"
                    ),
                ),
                (
                    "reference_mode",
                    models.CharField(
                        choices=[
                            ("all_weekly", "All Interactions This Week"),
                            ("specific_interaction", "Specific Interaction"),
                            ("specific_scene", "Specific Scene"),
                        ],
                        default="all_weekly",
                        help_text="How this update references RP",
                        max_length=30,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this update was created"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The character who wrote this update",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "linked_interaction",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Specific interaction this update references (no DB FK constraint — partitioned table, application-level integrity)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referencing_updates",
                        to="arxii.interaction",
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        help_text="The relationship this update applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="arxii.characterrelationship",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        help_text="The track that gains points from this update",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="arxii.relationshiptrack",
                    ),
                ),
                (
                    "linked_scene",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional scene this update is based on",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="arxii.scene",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="SecretGrievance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "capstone",
                    models.ForeignKey(
                        blank=True,
                        help_text="The relationship capstone this grievance applied.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.relationshipcapstone",
                    ),
                ),
                (
                    "secret",
                    models.ForeignKey(
                        help_text="The secret that was answered.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grievances",
                        to="arxii.secret",
                    ),
                ),
                (
                    "victim_sheet",
                    models.ForeignKey(
                        help_text="The wronged character who answered it.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secret_grievances",
                        to="arxii.charactersheet",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("secret", "victim_sheet"), name="one_grievance_per_secret_victim"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="Sineating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("units_offered", models.PositiveIntegerField()),
                (
                    "units_accepted",
                    models.PositiveIntegerField(
                        help_text="0 = declined; 1..N = accepted that many units."
                    ),
                ),
                ("anima_cost", models.PositiveIntegerField(default=0)),
                ("fatigue_cost", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sineatings",
                        to="arxii.characterrelationship",
                    ),
                ),
                (
                    "resonance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sineatings",
                        to="arxii.resonance",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sineatings",
                        to="arxii.scene",
                    ),
                ),
                (
                    "sineater_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sineatings_as_sineater",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "sinner_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sineatings_as_sinner",
                        to="arxii.charactersheet",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["sinner_sheet", "-created_at"],
                        name="arxii_sinea_sinner__46e4c6_idx",
                    ),
                    models.Index(
                        fields=["sineater_sheet", "-created_at"],
                        name="arxii_sinea_sineate_75a413_idx",
                    ),
                    models.Index(
                        fields=["relationship", "-created_at"],
                        name="arxii_sinea_relatio_e3febb_idx",
                    ),
                ]
            },
        ),
        migrations.CreateModel(
            name="SineatingPendingOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("units_offered", models.PositiveSmallIntegerField()),
                ("anima_cost_per_unit", models.PositiveSmallIntegerField()),
                ("fatigue_cost_per_unit", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sineating_pending_offers",
                        to="arxii.characterrelationship",
                    ),
                ),
                (
                    "resonance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sineating_pending_offers",
                        to="arxii.resonance",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sineating_pending_offers",
                        to="arxii.scene",
                    ),
                ),
                (
                    "sineater_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sineating_offers_received",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "sinner_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sineating_offers_sent",
                        to="arxii.charactersheet",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sinner_sheet", "sineater_sheet"),
                        name="one_pending_sineating_per_pair",
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="SoulTetherRescue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sinner_stage_at_start", models.PositiveSmallIntegerField()),
                ("sinner_stage_at_end", models.PositiveSmallIntegerField()),
                ("severity_reduced", models.PositiveIntegerField()),
                ("sineater_strain_taken", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "check_outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="arxii.checkoutcome",
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rescues",
                        to="arxii.characterrelationship",
                    ),
                ),
                (
                    "resonance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rescues",
                        to="arxii.resonance",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rescues",
                        to="arxii.scene",
                    ),
                ),
                (
                    "sineater_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rescues_as_sineater",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "sinner_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rescues_as_sinner",
                        to="arxii.charactersheet",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["sinner_sheet", "-created_at"],
                        name="arxii_soult_sinner__e5bd60_idx",
                    ),
                    models.Index(
                        fields=["sineater_sheet", "-created_at"],
                        name="arxii_soult_sineate_4c11c1_idx",
                    ),
                ]
            },
        ),
    ]
