# Generated by Django 5.2.16 on 2026-09-06 00:50


import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

from core_management.batched_migration import BatchedCreateModelMigration
from world.migrations._generations import replaced_slice


class Migration(BatchedCreateModelMigration):
    dependencies = [
        ("arxii", "0086_g2_part_86"),
    ]

    replaces = replaced_slice(87, 103)
    operations = [
        migrations.CreateModel(
            name="CharacterVitals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "died_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the character died (permanent death).",
                        null=True,
                    ),
                ),
                (
                    "retired_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the dead character was released (player retire, staff force, or auto-retire). Set = the character can no longer be puppeted.",
                        null=True,
                    ),
                ),
                ("health", models.IntegerField(default=0, help_text="Current health points.")),
                (
                    "max_health",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Maximum health points. Derived as base_max_health + thread-derived VITAL_BONUS MAX_HEALTH addend by recompute_max_health.",
                    ),
                ),
                (
                    "base_max_health",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Authored fixed base override; null = derive from level/stamina/role (see services).",
                        null=True,
                    ),
                ),
                (
                    "life_state",
                    models.CharField(
                        choices=[("alive", "Alive"), ("dead", "Dead")],
                        default="alive",
                        help_text="Mortality axis. Consciousness/dying are conditions, not vitals.",
                        max_length=10,
                    ),
                ),
                (
                    "aging_death_ic_deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="IC datetime at which old-age death resolves (#2756). Stamped when Frailty drives max health through the aging floor; the death sweep resolves it via _mark_dead once get_ic_now() passes it. Null = not in the dying window.",
                        null=True,
                    ),
                ),
                (
                    "death_deferred_pending",
                    models.BooleanField(
                        default=False,
                        help_text="Set when CHARACTER_KILLED is suppressed by an active death_deferred condition. Cleared and CHARACTER_KILLED is emitted when that condition expires.",
                    ),
                ),
                (
                    "character_sheet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "died_in_scene",
                    models.ForeignKey(
                        blank=True,
                        help_text="Scene active at the body's location when the character died; bounds the ghost emit window and death-kudos eligibility. Null for offscreen deaths.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deaths",
                        to="arxii.scene",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="CharacterXP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "total_earned",
                    models.PositiveIntegerField(default=0, help_text="Total XP earned"),
                ),
                ("total_spent", models.PositiveIntegerField(default=0, help_text="Total XP spent")),
                (
                    "transferable",
                    models.BooleanField(
                        default=True,
                        help_text="If False, XP is locked to this character and cannot be transferred",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_xp",
                        to="arxii.charactersheet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character XP",
                "verbose_name_plural": "Character XP",
                "indexes": [
                    models.Index(
                        fields=["character", "transferable"], name="arxii_chara_charact_efaeb2_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CharacterXPTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="XP change (positive for awards, negative for spending)"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("xp_purchase", "XP Purchase"),
                            ("cg_conversion", "CG Point Conversion"),
                            ("scene_award", "Scene Award"),
                            ("gm_award", "GM Award"),
                            ("system_award", "System Award"),
                            ("refund", "Refund"),
                            ("correction", "GM Correction"),
                            ("kudos_claim", "Kudos Claim"),
                            ("first_impression", "First Impression"),
                            ("vote_reward", "Vote Reward"),
                            ("memorable_pose", "Memorable Pose"),
                            ("random_scene", "Random Scene"),
                            ("gm_story_reward", "GM Story Reward"),
                            ("other", "Other"),
                        ],
                        help_text="Reason for this transaction",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="Human-readable description", max_length=255
                    ),
                ),
                (
                    "transferable",
                    models.BooleanField(default=True, help_text="Whether this XP is transferable"),
                ),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_xp_transactions",
                        to="arxii.charactersheet",
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_date"],
                "indexes": [
                    models.Index(
                        fields=["character", "-transaction_date"],
                        name="arxii_chara_charact_ca31e3_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CheckCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "band",
                    models.CharField(
                        choices=[
                            ("trivial", "Trivial"),
                            ("easy", "Easy"),
                            ("normal", "Normal"),
                            ("hard", "Hard"),
                            ("daunting", "Daunting"),
                            ("harrowing", "Harrowing"),
                        ],
                        help_text="The DifficultyChoice band the calling GM picked -- theater, echoed to targets.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "caller_persona",
                    models.ForeignKey(
                        help_text="The GM's persona at the moment of the call.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_calls_issued",
                        to="arxii.persona",
                    ),
                ),
                (
                    "check_type",
                    models.ForeignKey(
                        help_text="The authored catalog check being called for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_calls",
                        to="arxii.checktype",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        help_text="The scene this call was issued in.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_calls",
                        to="arxii.scene",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="CheckCallTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("answered", "Answered"),
                            ("declined", "Declined"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="arxii.checkcall",
                    ),
                ),
                (
                    "target_sheet",
                    models.ForeignKey(
                        help_text="The character asked to roll.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_call_targets",
                        to="arxii.charactersheet",
                    ),
                ),
            ],
            options={"ordering": ["pk"], "unique_together": {("call", "target_sheet")}},
        ),
        migrations.CreateModel(
            name="ExitBarsDetails",
            fields=[
                (
                    "exit_profile",
                    models.OneToOneField(
                        help_text="The exit these bars are installed on.",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="bars_details",
                        serialize=False,
                        to="arxii.exitprofile",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Durability tier. Capped at EXIT_BARS_MAX_LEVEL.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("installed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_upgraded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dissolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the bars are broken to destruction; null = active.",
                        null=True,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("level__gte", 1)), name="exit_bars_details_level_gte_1"
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="GemDetails",
            fields=[
                (
                    "item_template",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="gem_details",
                        serialize=False,
                        to="arxii.itemtemplate",
                    ),
                ),
                (
                    "quality_level",
                    models.PositiveSmallIntegerField(
                        help_text="Gem type quality level 1-15 (1-5 semiprecious, 6-10 precious, 11-15 magical).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(15),
                        ],
                    ),
                ),
            ],
        ),
    ]
