# Generated by Django 5.2.15 on 2026-08-04 07:42


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0087_initial_part_87"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="threadpulleffect",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("effect_kind", "INTENSITY_BUMP"), _negated=True),
                    models.Q(
                        ("intensity_bump_amount__isnull", False),
                        ("flat_bonus_amount__isnull", True),
                        ("vital_bonus_amount__isnull", True),
                        ("vital_target__isnull", True),
                        ("capability_grant__isnull", True),
                        ("target_form__isnull", True),
                        ("resistance_amount__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="threadpulleffect_intensity_bump_payload",
            ),
        ),
        migrations.AddConstraint(
            model_name="threadpulleffect",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("effect_kind", "VITAL_BONUS"), _negated=True),
                    models.Q(
                        ("vital_bonus_amount__isnull", False),
                        ("vital_target__isnull", False),
                        ("flat_bonus_amount__isnull", True),
                        ("intensity_bump_amount__isnull", True),
                        ("capability_grant__isnull", True),
                        ("target_form__isnull", True),
                        ("resistance_amount__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="threadpulleffect_vital_bonus_payload",
            ),
        ),
        migrations.AddConstraint(
            model_name="threadpulleffect",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("effect_kind", "CAPABILITY_GRANT"), _negated=True),
                    models.Q(
                        ("capability_grant__isnull", False),
                        ("flat_bonus_amount__isnull", True),
                        ("intensity_bump_amount__isnull", True),
                        ("vital_bonus_amount__isnull", True),
                        ("vital_target__isnull", True),
                        ("target_form__isnull", True),
                        ("resistance_amount__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="threadpulleffect_capability_grant_payload",
            ),
        ),
        migrations.AddConstraint(
            model_name="threadpulleffect",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("effect_kind", "NARRATIVE_ONLY"), _negated=True),
                    models.Q(
                        models.Q(("narrative_snippet", ""), _negated=True),
                        ("flat_bonus_amount__isnull", True),
                        ("intensity_bump_amount__isnull", True),
                        ("vital_bonus_amount__isnull", True),
                        ("vital_target__isnull", True),
                        ("capability_grant__isnull", True),
                        ("target_form__isnull", True),
                        ("resistance_amount__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="threadpulleffect_narrative_only_payload",
            ),
        ),
        migrations.AddConstraint(
            model_name="threadpulleffect",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("effect_kind", "CORRUPTION_RESISTANCE"), _negated=True),
                    models.Q(
                        ("flat_bonus_amount__isnull", True),
                        ("intensity_bump_amount__isnull", True),
                        ("vital_bonus_amount__isnull", True),
                        ("vital_target__isnull", True),
                        ("capability_grant__isnull", True),
                        ("target_form__isnull", True),
                        ("resistance_amount__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="threadpulleffect_corruption_resistance_payload",
            ),
        ),
        migrations.AddConstraint(
            model_name="threadpulleffect",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("effect_kind", "ASSUME_ALTERNATE_SELF"), _negated=True),
                    models.Q(
                        ("target_form__isnull", False),
                        ("flat_bonus_amount__isnull", True),
                        ("intensity_bump_amount__isnull", True),
                        ("vital_bonus_amount__isnull", True),
                        ("vital_target__isnull", True),
                        ("capability_grant__isnull", True),
                        ("narrative_snippet", ""),
                        ("resistance_amount__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="threadpulleffect_assume_alternate_self_payload",
            ),
        ),
        migrations.AddConstraint(
            model_name="threadpulleffect",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("effect_kind", "RESISTANCE"), _negated=True),
                    models.Q(
                        ("resistance_amount__isnull", False),
                        ("flat_bonus_amount__isnull", True),
                        ("intensity_bump_amount__isnull", True),
                        ("vital_bonus_amount__isnull", True),
                        ("vital_target__isnull", True),
                        ("capability_grant__isnull", True),
                        ("target_form__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="threadpulleffect_resistance_payload",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="characterthreadweavingunlock", unique_together={("character", "unlock")}
        ),
        migrations.AddConstraint(
            model_name="creaturephasetemplate",
            constraint=models.UniqueConstraint(
                fields=("creature_template", "phase_number"),
                name="unique_phase_per_creature_template",
            ),
        ),
        migrations.AddConstraint(
            model_name="combatopponent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("persona__isnull", True), ("objectdb_is_ephemeral", False), _connector="OR"
                ),
                name="persona_bearing_opponent_not_ephemeral",
            ),
        ),
        migrations.AddConstraint(
            model_name="combatopponent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("objectdb__isnull", False)),
                fields=("encounter", "objectdb"),
                name="combatopponent_unique_objectdb_per_encounter",
            ),
        ),
        migrations.AddConstraint(
            model_name="bossphase",
            constraint=models.UniqueConstraint(
                fields=("opponent", "phase_number"), name="unique_phase_per_opponent"
            ),
        ),
        migrations.AlterUniqueTogether(name="threatpoolentry", unique_together={("pool", "name")}),
        migrations.AddConstraint(
            model_name="pendingopponentattack",
            constraint=models.CheckConstraint(
                condition=models.Q(("resolves_round__gt", models.F("declared_round"))),
                name="pendingopponentattack_resolves_after_declared",
            ),
        ),
    ]
