# Generated by Django 5.2.16 on 2026-09-06 00:50

from decimal import Decimal

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

from core_management.batched_migration import BatchedCreateModelMigration
from world.migrations._generations import replaced_slice


class Migration(BatchedCreateModelMigration):
    dependencies = [
        ("arxii", "0090_g2_part_90"),
    ]

    replaces = replaced_slice(91, 103)
    operations = [
        migrations.CreateModel(
            name="GranaryDetails",
            fields=[
                (
                    "feature_instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="granary_details",
                        serialize=False,
                        to="arxii.roomfeatureinstance",
                    ),
                )
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="LabStationDetails",
            fields=[
                (
                    "feature_instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="lab_station_details",
                        serialize=False,
                        to="arxii.roomfeatureinstance",
                    ),
                ),
                (
                    "durability",
                    models.PositiveIntegerField(
                        help_text="Current wear-remaining before the station is broken."
                    ),
                ),
                (
                    "max_durability",
                    models.PositiveIntegerField(
                        help_text="Durability ceiling for this station's current level."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SanctumDetails",
            fields=[
                (
                    "feature_instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="sanctum_details",
                        serialize=False,
                        to="arxii.roomfeatureinstance",
                    ),
                ),
                (
                    "owner_mode",
                    models.CharField(
                        choices=[
                            ("PERSONAL", "Personal (Persona-owned home)"),
                            ("COVENANT", "Covenant (Organization-owned sacred ground)"),
                        ],
                        help_text="PERSONAL Sanctums use ``PERSONAL_OWN`` / ``HELPER`` thread slots; COVENANT Sanctums use ``COVENANT`` slots. Set at Sanctification by the ritual variant performed.",
                        max_length=10,
                    ),
                ),
                (
                    "last_homecoming_ritual_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set on each successful Homecoming. Soft cooldown + UI display.",
                        null=True,
                    ),
                ),
                (
                    "last_purging_ritual_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set on each successful Purging. UI display + audit.",
                        null=True,
                    ),
                ),
                (
                    "pending_sacrifice_overflow",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Homecoming sacrifice that exceeded the per-Sanctum cap (owner Path-level × 10 for Personal). Held in escrow; absorbed by future Homecoming/cron when the cap rises.",
                        max_digits=12,
                    ),
                ),
                (
                    "founder_character_sheet",
                    models.ForeignKey(
                        blank=True,
                        help_text="The CharacterSheet of the witch who performed the Sanctification ritual that founded this Sanctum. For PERSONAL Sanctums, this is the ongoing owner; for COVENANT, this is historical identity (the ongoing authority is the Covenant Organization). Used to differentiate founder-vs-non-founder Dissolution checks (non-founder = harder difficulty + larger botch consequences). Plan 4 §F revised 2026-06-03.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="founded_sanctums",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "resonance_type",
                    models.ForeignKey(
                        help_text="The resonance this Sanctum is consecrated to. Income payouts (via the cron tick) target this type; Ritual of Homecoming rows are created against this type; Ritual of Purging changes it.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sanctums",
                        to="arxii.resonance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResonanceGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("POSE_ENDORSEMENT", "Pose endorsement"),
                            ("SCENE_ENTRY", "Scene entry endorsement"),
                            ("ROOM_RESIDENCE", "Room residence trickle"),
                            ("OUTFIT_TRICKLE", "Outfit trickle"),
                            ("STAFF_GRANT", "Staff grant"),
                            ("SANCTUM_WEAVING", "Sanctum weaving payout"),
                            ("SANCTUM_OWNER_BONUS", "Sanctum owner/member bonus"),
                            ("PROJECT_CONTRIBUTION", "Project contribution payout"),
                            ("SANCTUM_DISSOLUTION_RECOVERY", "Sanctum dissolution recovery"),
                            ("ENTRY_FLOURISH", "Entry flourishing"),
                            ("DRAMATIC_MOMENT", "Dramatic moment"),
                            ("STYLE_PRESENTATION", "Style presentation"),
                            ("MISSION_REWARD", "Mission reward"),
                            ("MISSION_REPORT", "Mission report style"),
                            ("STAKE_REWARD", "Stake reward"),
                            ("DISTINCTION", "Distinction"),
                            ("COMBO_DISCOVERY", "Combo discovery"),
                            ("COMPROMISE", "Moral compromise"),
                            ("PENANCE", "Atonement resonance conversion"),
                            ("FALL_CONVERSION", "Fall/Redemption conversion"),
                        ],
                        help_text="Discriminator. Identifies which source_* FK is populated.",
                        max_length=32,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resonance_grants",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "outfit_item_facet",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when source=OUTFIT_TRICKLE; the ItemFacet that produced this trickle.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resonance_grants",
                        to="arxii.itemfacet",
                    ),
                ),
                (
                    "resonance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="arxii.resonance"
                    ),
                ),
                (
                    "source_character_distinction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when source=DISTINCTION; the CharacterDistinction that granted this resonance. SET_NULL so deleting the distinction does not delete this audit row.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resonance_grants",
                        to="arxii.characterdistinction",
                    ),
                ),
                (
                    "source_dramatic_moment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when source=DRAMATIC_MOMENT.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resonance_grants",
                        to="arxii.dramaticmomenttag",
                    ),
                ),
                (
                    "source_entry_flourish",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when source=ENTRY_FLOURISH.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resonance_grants",
                        to="arxii.entryflourishrecord",
                    ),
                ),
                (
                    "source_mission_deed_reward_line",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when source=MISSION_REWARD.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resonance_grants",
                        to="arxii.missiondeedrewardline",
                    ),
                ),
                (
                    "source_pose_endorsement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resonance_grants",
                        to="arxii.poseendorsement",
                    ),
                ),
                (
                    "source_project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when source=PROJECT_CONTRIBUTION; the Project whose resolution paid this contributor's grant. Plan 1+.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resonance_grants",
                        to="arxii.project",
                    ),
                ),
                (
                    "source_staff_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resonance_grants_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_room_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resonance_grants",
                        to="arxii.roomprofile",
                    ),
                ),
                (
                    "source_scene_entry_endorsement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resonance_grants",
                        to="arxii.sceneentryendorsement",
                    ),
                ),
                (
                    "source_style_presentation_endorsement",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when source=STYLE_PRESENTATION.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resonance_grants",
                        to="arxii.stylepresentationendorsement",
                    ),
                ),
                (
                    "source_sanctum_details",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when source in (SANCTUM_WEAVING, SANCTUM_OWNER_BONUS); the Sanctum whose cron tick paid this grant. Plan 4 §F.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resonance_grants",
                        to="arxii.sanctumdetails",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("source", "ROOM_RESIDENCE"),
                                ("source_room_profile__isnull", False),
                                ("source_staff_account__isnull", True),
                                ("source_pose_endorsement__isnull", True),
                                ("source_scene_entry_endorsement__isnull", True),
                                ("outfit_item_facet__isnull", True),
                                ("source_sanctum_details__isnull", True),
                                ("source_project__isnull", True),
                                ("source_entry_flourish__isnull", True),
                                ("source_dramatic_moment__isnull", True),
                                ("source_style_presentation_endorsement__isnull", True),
                                ("source_mission_deed_reward_line__isnull", True),
                                ("source_character_distinction__isnull", True),
                            ),
                            models.Q(("source", "ROOM_RESIDENCE"), _negated=True),
                            _connector="OR",
                        ),
                        name="res_grant_residence_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("source", "STAFF_GRANT"),
                                ("source_room_profile__isnull", True),
                                ("source_pose_endorsement__isnull", True),
                                ("source_scene_entry_endorsement__isnull", True),
                                ("outfit_item_facet__isnull", True),
                                ("source_sanctum_details__isnull", True),
                                ("source_project__isnull", True),
                                ("source_entry_flourish__isnull", True),
                                ("source_dramatic_moment__isnull", True),
                                ("source_style_presentation_endorsement__isnull", True),
                                ("source_mission_deed_reward_line__isnull", True),
                                ("source_character_distinction__isnull", True),
                            ),
                            models.Q(("source", "STAFF_GRANT"), _negated=True),
                            _connector="OR",
                        ),
                        name="res_grant_staff_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("source", "MISSION_REPORT"),
                                ("source_room_profile__isnull", True),
                                ("source_staff_account__isnull", True),
                                ("source_pose_endorsement__isnull", True),
                                ("source_scene_entry_endorsement__isnull", True),
                                ("outfit_item_facet__isnull", True),
                                ("source_sanctum_details__isnull", True),
                                ("source_project__isnull", True),
                                ("source_entry_flourish__isnull", True),
                                ("source_dramatic_moment__isnull", True),
                                ("source_style_presentation_endorsement__isnull", True),
                                ("source_mission_deed_reward_line__isnull", True),
                                ("source_character_distinction__isnull", True),
                            ),
                            models.Q(("source", "MISSION_REPORT"), _negated=True),
                            _connector="OR",
                        ),
                        name="res_grant_mission_report_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("source", "STAKE_REWARD"),
                                ("source_room_profile__isnull", True),
                                ("source_staff_account__isnull", True),
                                ("source_pose_endorsement__isnull", True),
                                ("source_scene_entry_endorsement__isnull", True),
                                ("outfit_item_facet__isnull", True),
                                ("source_sanctum_details__isnull", True),
                                ("source_project__isnull", True),
                                ("source_entry_flourish__isnull", True),
                                ("source_dramatic_moment__isnull", True),
                                ("source_style_presentation_endorsement__isnull", True),
                                ("source_mission_deed_reward_line__isnull", True),
                                ("source_character_distinction__isnull", True),
                            ),
                            models.Q(("source", "STAKE_REWARD"), _negated=True),
                            _connector="OR",
                        ),
                        name="res_grant_stake_reward_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("source", "POSE_ENDORSEMENT"),
                                ("source_pose_endorsement__isnull", False),
                                ("source_room_profile__isnull", True),
                                ("source_staff_account__isnull", True),
                                ("source_scene_entry_endorsement__isnull", True),
                                ("outfit_item_facet__isnull", True),
                                ("source_sanctum_details__isnull", True),
                                ("source_project__isnull", True),
                                ("source_entry_flourish__isnull", True),
                                ("source_dramatic_moment__isnull", True),
                                ("source_style_presentation_endorsement__isnull", True),
                                ("source_mission_deed_reward_line__isnull", True),
                                ("source_character_distinction__isnull", True),
                            ),
                            models.Q(("source", "POSE_ENDORSEMENT"), _negated=True),
                            _connector="OR",
                        ),
                        name="res_grant_pose_endorsement_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("source", "SCENE_ENTRY"),
                                ("source_scene_entry_endorsement__isnull", False),
                                ("source_room_profile__isnull", True),
                                ("source_staff_account__isnull", True),
                                ("source_pose_endorsement__isnull", True),
                                ("outfit_item_facet__isnull", True),
                                ("source_sanctum_details__isnull", True),
                                ("source_project__isnull", True),
                                ("source_entry_flourish__isnull", True),
                                ("source_dramatic_moment__isnull", True),
                                ("source_style_presentation_endorsement__isnull", True),
                                ("source_mission_deed_reward_line__isnull", True),
                                ("source_character_distinction__isnull", True),
                            ),
                            models.Q(("source", "SCENE_ENTRY"), _negated=True),
                            _connector="OR",
                        ),
                        name="res_grant_scene_entry_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("source", "OUTFIT_TRICKLE"),
                                ("outfit_item_facet__isnull", False),
                                ("source_room_profile__isnull", True),
                                ("source_staff_account__isnull", True),
                                ("source_pose_endorsement__isnull", True),
                                ("source_scene_entry_endorsement__isnull", True),
                                ("source_sanctum_details__isnull", True),
                                ("source_project__isnull", True),
                                ("source_entry_flourish__isnull", True),
                                ("source_dramatic_moment__isnull", True),
                                ("source_style_presentation_endorsement__isnull", True),
                                ("source_mission_deed_reward_line__isnull", True),
                                ("source_character_distinction__isnull", True),
                            ),
                            models.Q(("source", "OUTFIT_TRICKLE"), _negated=True),
                            _connector="OR",
                        ),
                        name="res_grant_outfit_trickle_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("source", "SANCTUM_WEAVING"),
                                ("source_room_profile__isnull", True),
                                ("source_staff_account__isnull", True),
                                ("source_pose_endorsement__isnull", True),
                                ("source_scene_entry_endorsement__isnull", True),
                                ("outfit_item_facet__isnull", True),
                                ("source_project__isnull", True),
                                ("source_entry_flourish__isnull", True),
                                ("source_dramatic_moment__isnull", True),
                                ("source_style_presentation_endorsement__isnull", True),
                                ("source_mission_deed_reward_line__isnull", True),
                                ("source_character_distinction__isnull", True),
                            ),
                            models.Q(("source", "SANCTUM_WEAVING"), _negated=True),
                            _connector="OR",
                        ),
                        name="res_grant_sanctum_weaving_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("source", "SANCTUM_OWNER_BONUS"),
                                ("source_room_profile__isnull", True),
                                ("source_staff_account__isnull", True),
                                ("source_pose_endorsement__isnull", True),
                                ("source_scene_entry_endorsement__isnull", True),
                                ("outfit_item_facet__isnull", True),
                                ("source_project__isnull", True),
                                ("source_entry_flourish__isnull", True),
                                ("source_dramatic_moment__isnull", True),
                                ("source_style_presentation_endorsement__isnull", True),
                                ("source_mission_deed_reward_line__isnull", True),
                                ("source_character_distinction__isnull", True),
                            ),
                            models.Q(("source", "SANCTUM_OWNER_BONUS"), _negated=True),
                            _connector="OR",
                        ),
                        name="res_grant_sanctum_owner_bonus_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("source", "SANCTUM_DISSOLUTION_RECOVERY"),
                                ("source_room_profile__isnull", True),
                                ("source_staff_account__isnull", True),
                                ("source_pose_endorsement__isnull", True),
                                ("source_scene_entry_endorsement__isnull", True),
                                ("outfit_item_facet__isnull", True),
                                ("source_project__isnull", True),
                                ("source_entry_flourish__isnull", True),
                                ("source_dramatic_moment__isnull", True),
                                ("source_style_presentation_endorsement__isnull", True),
                                ("source_mission_deed_reward_line__isnull", True),
                                ("source_character_distinction__isnull", True),
                            ),
                            models.Q(("source", "SANCTUM_DISSOLUTION_RECOVERY"), _negated=True),
                            _connector="OR",
                        ),
                        name="res_grant_sanctum_dissolution_recovery_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("source", "PROJECT_CONTRIBUTION"),
                                ("source_project__isnull", False),
                                ("source_room_profile__isnull", True),
                                ("source_staff_account__isnull", True),
                                ("source_pose_endorsement__isnull", True),
                                ("source_scene_entry_endorsement__isnull", True),
                                ("outfit_item_facet__isnull", True),
                                ("source_sanctum_details__isnull", True),
                                ("source_entry_flourish__isnull", True),
                                ("source_dramatic_moment__isnull", True),
                                ("source_style_presentation_endorsement__isnull", True),
                                ("source_mission_deed_reward_line__isnull", True),
                                ("source_character_distinction__isnull", True),
                            ),
                            models.Q(("source", "PROJECT_CONTRIBUTION"), _negated=True),
                            _connector="OR",
                        ),
                        name="res_grant_project_contribution_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("source", "ENTRY_FLOURISH"),
                                ("source_entry_flourish__isnull", False),
                                ("source_room_profile__isnull", True),
                                ("source_staff_account__isnull", True),
                                ("source_pose_endorsement__isnull", True),
                                ("source_scene_entry_endorsement__isnull", True),
                                ("outfit_item_facet__isnull", True),
                                ("source_sanctum_details__isnull", True),
                                ("source_project__isnull", True),
                                ("source_dramatic_moment__isnull", True),
                                ("source_style_presentation_endorsement__isnull", True),
                                ("source_mission_deed_reward_line__isnull", True),
                                ("source_character_distinction__isnull", True),
                            ),
                            models.Q(("source", "ENTRY_FLOURISH"), _negated=True),
                            _connector="OR",
                        ),
                        name="res_grant_entry_flourish_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("source", "DRAMATIC_MOMENT"),
                                ("source_dramatic_moment__isnull", False),
                                ("source_room_profile__isnull", True),
                                ("source_staff_account__isnull", True),
                                ("source_pose_endorsement__isnull", True),
                                ("source_scene_entry_endorsement__isnull", True),
                                ("outfit_item_facet__isnull", True),
                                ("source_sanctum_details__isnull", True),
                                ("source_project__isnull", True),
                                ("source_entry_flourish__isnull", True),
                                ("source_style_presentation_endorsement__isnull", True),
                                ("source_mission_deed_reward_line__isnull", True),
                                ("source_character_distinction__isnull", True),
                            ),
                            models.Q(("source", "DRAMATIC_MOMENT"), _negated=True),
                            _connector="OR",
                        ),
                        name="res_grant_dramatic_moment_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("source", "STYLE_PRESENTATION"),
                                ("source_style_presentation_endorsement__isnull", False),
                                ("source_room_profile__isnull", True),
                                ("source_staff_account__isnull", True),
                                ("source_pose_endorsement__isnull", True),
                                ("source_scene_entry_endorsement__isnull", True),
                                ("outfit_item_facet__isnull", True),
                                ("source_sanctum_details__isnull", True),
                                ("source_project__isnull", True),
                                ("source_entry_flourish__isnull", True),
                                ("source_dramatic_moment__isnull", True),
                                ("source_mission_deed_reward_line__isnull", True),
                                ("source_character_distinction__isnull", True),
                            ),
                            models.Q(("source", "STYLE_PRESENTATION"), _negated=True),
                            _connector="OR",
                        ),
                        name="res_grant_style_presentation_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("source", "MISSION_REWARD"),
                                ("source_mission_deed_reward_line__isnull", False),
                                ("source_room_profile__isnull", True),
                                ("source_staff_account__isnull", True),
                                ("source_pose_endorsement__isnull", True),
                                ("source_scene_entry_endorsement__isnull", True),
                                ("outfit_item_facet__isnull", True),
                                ("source_sanctum_details__isnull", True),
                                ("source_project__isnull", True),
                                ("source_entry_flourish__isnull", True),
                                ("source_dramatic_moment__isnull", True),
                                ("source_style_presentation_endorsement__isnull", True),
                                ("source_character_distinction__isnull", True),
                            ),
                            models.Q(("source", "MISSION_REWARD"), _negated=True),
                            _connector="OR",
                        ),
                        name="res_grant_mission_reward_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("source", "DISTINCTION"),
                                ("source_room_profile__isnull", True),
                                ("source_staff_account__isnull", True),
                                ("source_pose_endorsement__isnull", True),
                                ("source_scene_entry_endorsement__isnull", True),
                                ("outfit_item_facet__isnull", True),
                                ("source_sanctum_details__isnull", True),
                                ("source_project__isnull", True),
                                ("source_entry_flourish__isnull", True),
                                ("source_dramatic_moment__isnull", True),
                                ("source_style_presentation_endorsement__isnull", True),
                                ("source_mission_deed_reward_line__isnull", True),
                            ),
                            models.Q(("source", "DISTINCTION"), _negated=True),
                            _connector="OR",
                        ),
                        name="res_grant_distinction_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("source", "COMPROMISE"),
                                ("source_room_profile__isnull", True),
                                ("source_staff_account__isnull", True),
                                ("source_pose_endorsement__isnull", True),
                                ("source_scene_entry_endorsement__isnull", True),
                                ("outfit_item_facet__isnull", True),
                                ("source_sanctum_details__isnull", True),
                                ("source_project__isnull", True),
                                ("source_entry_flourish__isnull", True),
                                ("source_dramatic_moment__isnull", True),
                                ("source_style_presentation_endorsement__isnull", True),
                                ("source_mission_deed_reward_line__isnull", True),
                                ("source_character_distinction__isnull", True),
                            ),
                            models.Q(("source", "COMPROMISE"), _negated=True),
                            _connector="OR",
                        ),
                        name="res_grant_compromise_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("source", "PENANCE"),
                                ("source_room_profile__isnull", True),
                                ("source_staff_account__isnull", True),
                                ("source_pose_endorsement__isnull", True),
                                ("source_scene_entry_endorsement__isnull", True),
                                ("outfit_item_facet__isnull", True),
                                ("source_sanctum_details__isnull", True),
                                ("source_project__isnull", True),
                                ("source_entry_flourish__isnull", True),
                                ("source_dramatic_moment__isnull", True),
                                ("source_style_presentation_endorsement__isnull", True),
                                ("source_mission_deed_reward_line__isnull", True),
                                ("source_character_distinction__isnull", True),
                            ),
                            models.Q(("source", "PENANCE"), _negated=True),
                            _connector="OR",
                        ),
                        name="res_grant_penance_shape",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("source", "FALL_CONVERSION"),
                                ("source_room_profile__isnull", True),
                                ("source_staff_account__isnull", True),
                                ("source_pose_endorsement__isnull", True),
                                ("source_scene_entry_endorsement__isnull", True),
                                ("outfit_item_facet__isnull", True),
                                ("source_sanctum_details__isnull", True),
                                ("source_project__isnull", True),
                                ("source_entry_flourish__isnull", True),
                                ("source_dramatic_moment__isnull", True),
                                ("source_style_presentation_endorsement__isnull", True),
                                ("source_mission_deed_reward_line__isnull", True),
                                ("source_character_distinction__isnull", True),
                            ),
                            models.Q(("source", "FALL_CONVERSION"), _negated=True),
                            _connector="OR",
                        ),
                        name="res_grant_fall_conversion_shape",
                    ),
                ],
                "indexes": [
                    models.Index(
                        fields=["character_sheet", "granted_at"], name="res_grant_sheet_time_idx"
                    ),
                    models.Index(
                        fields=["character_sheet", "source", "granted_at"],
                        name="res_grant_sheet_source_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SanctumPendingPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "pending_weaving",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Accumulated income from SANCTUM_WEAVING source. Drained on absorb.",
                    ),
                ),
                (
                    "pending_owner_bonus",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Accumulated income from SANCTUM_OWNER_BONUS source. Drained on absorb.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Bumped on each cron-tick accumulation. UI 'last accrual' display.",
                    ),
                ),
                (
                    "weaver_character_sheet",
                    models.ForeignKey(
                        help_text="The CharacterSheet of the weaver whose income is accumulating. One row per (sanctum, weaver) pair.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sanctum_pending_payouts",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "sanctum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_payouts",
                        to="arxii.sanctumdetails",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sanctum", "weaver_character_sheet"),
                        name="sanctum_pending_payout_unique_per_weaver",
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "target_kind",
                    models.CharField(
                        choices=[
                            ("TRAIT", "Trait"),
                            ("TECHNIQUE", "Technique"),
                            ("FACET", "Facet"),
                            ("RELATIONSHIP_TRACK", "Relationship Track"),
                            ("RELATIONSHIP_CAPSTONE", "Relationship Capstone"),
                            ("COVENANT_ROLE", "Covenant Role"),
                            ("MANTLE", "Mantle"),
                            ("SANCTUM", "Sanctum"),
                            ("GIFT", "Gift"),
                            ("ORGANIZATION", "Organization"),
                        ],
                        help_text="Discriminator selecting which target_* FK is populated.",
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "developed_points",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Permanent points; advances level via ThreadLevelUnlock entries.",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Current level on the internal scale (multiples of 10).",
                    ),
                ),
                (
                    "hollow_current",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Soul Tether Hollow capacity (Spec B §5). Only meaningful for RELATIONSHIP_CAPSTONE Sinner-side Threads. Drains on corruption redirect; refills via Sineating. Other Threads ignore this field.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "retired_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when owner soft-retires this thread; retired threads are excluded from list/detail views and from all pull / passive paths.",
                        null=True,
                    ),
                ),
                (
                    "slot_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PERSONAL_OWN", "Personal — own home"),
                            ("COVENANT", "Covenant — sacred ground"),
                            ("HELPER", "Helper — invited ally on another's personal Sanctum"),
                        ],
                        default="",
                        help_text="Per-PC weaving slot rule. Required for SANCTUM threads, must be empty for all other target_kinds. Enforced by CheckConstraint. PERSONAL_OWN + COVENANT slots are limited to one active per owner.",
                        max_length=16,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Character who owns this thread.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="threads",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "resonance",
                    models.ForeignKey(
                        help_text="Resonance this thread channels.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="threads",
                        to="arxii.resonance",
                    ),
                ),
                (
                    "signature_bonus",
                    models.ForeignKey(
                        blank=True,
                        help_text="Player-chosen SignatureMotifBonus attached to this thread. May only be non-null when target_kind=TECHNIQUE (#1582).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.signaturemotifbonus",
                    ),
                ),
                (
                    "target_capstone",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when target_kind=RELATIONSHIP_CAPSTONE; null otherwise.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anchored_threads",
                        to="arxii.relationshipcapstone",
                    ),
                ),
                (
                    "target_covenant_role",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when target_kind=COVENANT_ROLE; null otherwise.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anchored_threads",
                        to="arxii.covenantrole",
                    ),
                ),
                (
                    "target_facet",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when target_kind=FACET; null otherwise.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anchored_threads",
                        to="arxii.facet",
                    ),
                ),
                (
                    "target_gift",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when target_kind=GIFT; null otherwise.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anchored_threads",
                        to="arxii.gift",
                    ),
                ),
                (
                    "target_mantle",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when target_kind=MANTLE; null otherwise.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anchored_threads",
                        to="arxii.mantle",
                    ),
                ),
                (
                    "target_organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when target_kind=ORGANIZATION; null otherwise.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anchored_threads",
                        to="arxii.organization",
                    ),
                ),
                (
                    "target_relationship_track",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when target_kind=RELATIONSHIP_TRACK; null otherwise.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anchored_threads",
                        to="arxii.relationshiptrackprogress",
                    ),
                ),
                (
                    "target_technique",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when target_kind=TECHNIQUE; null otherwise.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anchored_threads",
                        to="arxii.technique",
                    ),
                ),
                (
                    "target_trait",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when target_kind=TRAIT; null otherwise.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anchored_threads",
                        to="arxii.trait",
                    ),
                ),
                (
                    "target_sanctum_details",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when target_kind=SANCTUM; null otherwise. Plan 4 §F.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anchored_threads",
                        to="arxii.sanctumdetails",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("target_kind", "TRAIT")),
                        fields=("owner", "resonance", "target_trait"),
                        name="uniq_thread_trait",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("target_kind", "TECHNIQUE")),
                        fields=("owner", "resonance", "target_technique"),
                        name="uniq_thread_technique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("target_kind", "RELATIONSHIP_TRACK")),
                        fields=("owner", "resonance", "target_relationship_track"),
                        name="uniq_thread_rel_track",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("target_kind", "RELATIONSHIP_CAPSTONE")),
                        fields=("owner", "resonance", "target_capstone"),
                        name="uniq_thread_rel_capstone",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("target_kind", "TRAIT"), _negated=True),
                            models.Q(
                                ("target_trait__isnull", False),
                                ("target_technique__isnull", True),
                                ("target_relationship_track__isnull", True),
                                ("target_capstone__isnull", True),
                                ("target_facet__isnull", True),
                                ("target_covenant_role__isnull", True),
                                ("target_gift__isnull", True),
                                ("target_mantle__isnull", True),
                                ("target_sanctum_details__isnull", True),
                                ("target_organization__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="thread_trait_payload",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("target_kind", "TECHNIQUE"), _negated=True),
                            models.Q(
                                ("target_trait__isnull", True),
                                ("target_technique__isnull", False),
                                ("target_relationship_track__isnull", True),
                                ("target_capstone__isnull", True),
                                ("target_facet__isnull", True),
                                ("target_covenant_role__isnull", True),
                                ("target_gift__isnull", True),
                                ("target_mantle__isnull", True),
                                ("target_sanctum_details__isnull", True),
                                ("target_organization__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="thread_technique_payload",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("target_kind", "RELATIONSHIP_TRACK"), _negated=True),
                            models.Q(
                                ("target_trait__isnull", True),
                                ("target_technique__isnull", True),
                                ("target_relationship_track__isnull", False),
                                ("target_capstone__isnull", True),
                                ("target_facet__isnull", True),
                                ("target_covenant_role__isnull", True),
                                ("target_gift__isnull", True),
                                ("target_mantle__isnull", True),
                                ("target_sanctum_details__isnull", True),
                                ("target_organization__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="thread_rel_track_payload",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("target_kind", "RELATIONSHIP_CAPSTONE"), _negated=True),
                            models.Q(
                                ("target_trait__isnull", True),
                                ("target_technique__isnull", True),
                                ("target_relationship_track__isnull", True),
                                ("target_capstone__isnull", False),
                                ("target_facet__isnull", True),
                                ("target_covenant_role__isnull", True),
                                ("target_gift__isnull", True),
                                ("target_mantle__isnull", True),
                                ("target_sanctum_details__isnull", True),
                                ("target_organization__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="thread_rel_capstone_payload",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("retired_at__isnull", True), ("target_kind", "FACET")),
                        fields=("owner", "target_facet"),
                        name="uniq_thread_facet_active",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("target_kind", "FACET"), _negated=True),
                            models.Q(
                                ("target_facet__isnull", False),
                                ("target_trait__isnull", True),
                                ("target_technique__isnull", True),
                                ("target_relationship_track__isnull", True),
                                ("target_capstone__isnull", True),
                                ("target_covenant_role__isnull", True),
                                ("target_gift__isnull", True),
                                ("target_mantle__isnull", True),
                                ("target_sanctum_details__isnull", True),
                                ("target_organization__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="thread_facet_payload",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("retired_at__isnull", True), ("target_kind", "COVENANT_ROLE")
                        ),
                        fields=("owner", "target_covenant_role"),
                        name="uniq_thread_covenant_role_active",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("target_kind", "COVENANT_ROLE"), _negated=True),
                            models.Q(
                                ("target_covenant_role__isnull", False),
                                ("target_trait__isnull", True),
                                ("target_technique__isnull", True),
                                ("target_relationship_track__isnull", True),
                                ("target_capstone__isnull", True),
                                ("target_facet__isnull", True),
                                ("target_gift__isnull", True),
                                ("target_mantle__isnull", True),
                                ("target_sanctum_details__isnull", True),
                                ("target_organization__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="thread_covenant_role_payload",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("retired_at__isnull", True), ("target_kind", "GIFT")),
                        fields=("owner", "target_gift", "resonance"),
                        name="uniq_thread_gift_active",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("target_kind", "GIFT"), _negated=True),
                            models.Q(
                                ("target_gift__isnull", False),
                                ("target_trait__isnull", True),
                                ("target_technique__isnull", True),
                                ("target_relationship_track__isnull", True),
                                ("target_capstone__isnull", True),
                                ("target_facet__isnull", True),
                                ("target_covenant_role__isnull", True),
                                ("target_mantle__isnull", True),
                                ("target_sanctum_details__isnull", True),
                                ("target_organization__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="thread_gift_payload",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("retired_at__isnull", True), ("target_kind", "MANTLE")),
                        fields=("owner", "target_mantle"),
                        name="uniq_thread_mantle_active",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("target_kind", "MANTLE"), _negated=True),
                            models.Q(
                                ("target_mantle__isnull", False),
                                ("target_trait__isnull", True),
                                ("target_technique__isnull", True),
                                ("target_relationship_track__isnull", True),
                                ("target_capstone__isnull", True),
                                ("target_facet__isnull", True),
                                ("target_covenant_role__isnull", True),
                                ("target_gift__isnull", True),
                                ("target_sanctum_details__isnull", True),
                                ("target_organization__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="thread_mantle_payload",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("retired_at__isnull", True),
                            ("slot_kind", "PERSONAL_OWN"),
                            ("target_kind", "SANCTUM"),
                        ),
                        fields=("owner",),
                        name="uniq_thread_sanctum_personal_own_active",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("retired_at__isnull", True),
                            ("slot_kind", "COVENANT"),
                            ("target_kind", "SANCTUM"),
                        ),
                        fields=("owner",),
                        name="uniq_thread_sanctum_covenant_active",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("retired_at__isnull", True), ("target_kind", "SANCTUM")
                        ),
                        fields=("owner", "target_sanctum_details"),
                        name="uniq_thread_sanctum_owner_target_active",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("target_kind", "SANCTUM"), _negated=True),
                            models.Q(
                                ("target_sanctum_details__isnull", False),
                                models.Q(("slot_kind", ""), _negated=True),
                                ("target_trait__isnull", True),
                                ("target_technique__isnull", True),
                                ("target_relationship_track__isnull", True),
                                ("target_capstone__isnull", True),
                                ("target_facet__isnull", True),
                                ("target_covenant_role__isnull", True),
                                ("target_gift__isnull", True),
                                ("target_mantle__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="thread_sanctum_payload",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("retired_at__isnull", True), ("target_kind", "ORGANIZATION")
                        ),
                        fields=("owner", "target_organization"),
                        name="uniq_thread_organization_active",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("target_kind", "ORGANIZATION"), _negated=True),
                            models.Q(
                                ("target_organization__isnull", False),
                                ("target_trait__isnull", True),
                                ("target_technique__isnull", True),
                                ("target_relationship_track__isnull", True),
                                ("target_capstone__isnull", True),
                                ("target_facet__isnull", True),
                                ("target_covenant_role__isnull", True),
                                ("target_gift__isnull", True),
                                ("target_mantle__isnull", True),
                                ("target_sanctum_details__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="thread_organization_payload",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("target_kind", "SANCTUM"), ("slot_kind", ""), _connector="OR"
                        ),
                        name="thread_slot_kind_only_for_sanctum",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("signature_bonus__isnull", True),
                            ("target_kind", "TECHNIQUE"),
                            _connector="OR",
                        ),
                        name="thread_signature_bonus_technique_only",
                    ),
                ]
            },
        ),
    ]
