# Generated by Django 5.2.15 on 2026-08-04 07:42


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0090_initial_part_90"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="developmenttransaction",
            index=models.Index(
                fields=["scene", "-transaction_date"], name="arxii_devel_scene_i_256452_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="developmentpoints",
            index=models.Index(
                fields=["character_sheet", "trait"], name="arxii_devel_charact_f3d0a0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="developmentpoints", unique_together={("character_sheet", "trait")}
        ),
        migrations.AddConstraint(
            model_name="craftingrecipe",
            constraint=models.UniqueConstraint(
                fields=("kind", "output_item_template"),
                name="items_craftingrecipe_kind_output_unique",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="checktypetrait", unique_together={("check_type", "trait")}
        ),
        migrations.AddIndex(
            model_name="charactertraitvalue",
            index=models.Index(
                fields=["character", "trait"], name="arxii_chara_charact_9bfc3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="charactertraitvalue",
            index=models.Index(fields=["character"], name="arxii_chara_charact_05f9fd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="charactertraitvalue", unique_together={("character", "trait")}
        ),
        migrations.AddIndex(
            model_name="characterclass",
            index=models.Index(fields=["is_hidden"], name="arxii_chara_is_hidd_e3a425_idx"),
        ),
        migrations.AddIndex(
            model_name="characterclass",
            index=models.Index(fields=["minimum_level"], name="arxii_chara_minimum_2e898f_idx"),
        ),
        migrations.AddConstraint(
            model_name="traitcapabilityderivation",
            constraint=models.UniqueConstraint(
                fields=("trait", "capability"), name="trait_capability_derivation_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="traitrankdescription",
            index=models.Index(fields=["trait", "value"], name="arxii_trait_trait_i_2ffa99_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="traitrankdescription", unique_together={("trait", "value")}
        ),
        migrations.AlterUniqueTogether(
            name="traitratingunlock", unique_together={("trait", "target_rating")}
        ),
        migrations.AddConstraint(
            model_name="traitrequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("class_level_unlock__isnull", False),
                        ("thread_crossing_threshold__isnull", True),
                        ("path__isnull", True),
                    ),
                    models.Q(
                        ("class_level_unlock__isnull", True),
                        ("thread_crossing_threshold__isnull", False),
                        ("path__isnull", True),
                    ),
                    models.Q(
                        ("class_level_unlock__isnull", True),
                        ("thread_crossing_threshold__isnull", True),
                        ("path__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="traitrequirement_exactly_one_unlock_target",
            ),
        ),
    ]
