# Generated by Django 5.2.15 on 2026-08-04 07:42


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0091_initial_part_91"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transition",
            index=models.Index(fields=["source_episode"], name="arxii_trans_source__dfdc97_idx"),
        ),
        migrations.AddIndex(
            model_name="episoderesolution",
            index=models.Index(
                fields=["episode", "-resolved_at"], name="arxii_episo_episode_23a5d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="episoderesolution",
            index=models.Index(
                fields=["character_sheet", "-resolved_at"], name="arxii_episo_charact_af17b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="episoderesolution",
            index=models.Index(
                fields=["gm_table", "-resolved_at"], name="arxii_episo_gm_tabl_834e67_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="transitionrequiredoutcome",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stake__isnull", True)),
                fields=("transition", "beat"),
                name="unique_routing_req_per_transition_beat",
            ),
        ),
        migrations.AddConstraint(
            model_name="transitionrequiredoutcome",
            constraint=models.UniqueConstraint(
                condition=models.Q(("stake__isnull", False)),
                fields=("transition", "stake"),
                name="unique_routing_req_per_transition_stake",
            ),
        ),
        migrations.AddConstraint(
            model_name="treatmentattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("once_per_scene_guard", True)),
                fields=("helper", "target", "scene", "treatment"),
                name="unique_treatment_attempt_per_helper_scene",
            ),
        ),
        migrations.AddConstraint(
            model_name="treatmentattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("once_per_wound_guard", True)),
                fields=("helper", "target_condition_instance"),
                name="unique_treatment_attempt_per_helper_wound",
            ),
        ),
        migrations.AddConstraint(
            model_name="techniquetreatment",
            constraint=models.UniqueConstraint(
                fields=("technique", "treatment_template"), name="unique_treatment_per_technique"
            ),
        ),
        migrations.AddIndex(
            model_name="sceneactionrequest",
            index=models.Index(fields=["scene", "status"], name="arxii_scene_scene_i_07c59d_idx"),
        ),
        migrations.AddIndex(
            model_name="sceneactionrequest",
            index=models.Index(
                fields=["initiator_persona", "created_at"], name="arxii_scene_initiat_46a0cb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(name="triggerdata", unique_together={("trigger", "key")}),
        migrations.AlterUniqueTogether(
            name="storytrustrequirement", unique_together={("story", "trust_category")}
        ),
        migrations.AlterUniqueTogether(
            name="playertrustlevel", unique_together={("player_trust", "trust_category")}
        ),
        migrations.AlterUniqueTogether(
            name="trustcategoryfeedbackrating", unique_together={("feedback", "trust_category")}
        ),
    ]
