# Generated by Django 5.2.16 on 2026-09-06 00:50


import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

from world.migrations._generations import replaced_slice


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0098_g2_part_98"),
    ]

    replaces = replaced_slice(99, 103)
    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="species",
            field=models.ForeignKey(
                blank=True,
                help_text="Character's species (may have parent for subspecies)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="character_sheets",
                to="arxii.species",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="covenant",
            field=models.ForeignKey(
                blank=True,
                help_text="For GROUP-scope stories: the covenant this storyline belongs to. Informational — not a credit gate. SET_NULL on covenant delete so an archived covenant doesn't cascade-delete its stories.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="storylines",
                to="arxii.covenant",
            ),
        ),
        migrations.AddField(
            model_name="technique",
            name="applied_conditions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Conditions this technique can apply, with formula-based scaling.",
                related_name="techniques_applying",
                through="arxii.TechniqueAppliedCondition",
                to="arxii.conditiontemplate",
            ),
        ),
        migrations.AddField(
            model_name="itemtemplate",
            name="interactions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Actions that can be performed on items of this type.",
                related_name="templates",
                through="arxii.TemplateInteraction",
                to="arxii.interactiontype",
            ),
        ),
        migrations.AddField(
            model_name="rosterentry",
            name="profile_picture",
            field=models.ForeignKey(
                blank=True,
                help_text="Profile picture for this character",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profile_for_entries",
                to="arxii.tenuremedia",
            ),
        ),
        migrations.AddField(
            model_name="beginnings",
            name="traditions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Traditions available for this beginning during CG.",
                related_name="available_beginnings",
                through="arxii.BeginningTradition",
                to="arxii.tradition",
            ),
        ),
    ]
