# Generated by Django 5.2.15 on 2026-08-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0102_alter_clashcontribution_interaction_timestamp_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="giftunlock",
            constraint=models.UniqueConstraint(
                fields=("gift",), name="unique_gift_unlock_per_gift"
            ),
        ),
    ]
