# Generated by Django 5.2.16 on 2026-09-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0104_formative_connections"),
    ]

    operations = [
        migrations.AddField(
            model_name="heritage",
            name="first_appeared_ic",
            field=models.DateField(
                blank=True,
                help_text="IC date the first of this heritage were born. When set, character generation caps age at the whole IC years elapsed since (floor 18); the appearance stage shows the year as a world fact (#3663).",
                null=True,
            ),
        ),
    ]
