# Generated by Django 5.2.15 on 2026-08-05 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0107_credit_authoring_domain_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftMarking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body_region",
                    models.CharField(
                        choices=[
                            ("head", "Head"),
                            ("face", "Face"),
                            ("neck", "Neck"),
                            ("shoulders", "Shoulders"),
                            ("torso", "Torso"),
                            ("back", "Back"),
                            ("waist", "Waist"),
                            ("left_arm", "Left Arm"),
                            ("right_arm", "Right Arm"),
                            ("left_hand", "Left Hand"),
                            ("right_hand", "Right Hand"),
                            ("left_leg", "Left Leg"),
                            ("right_leg", "Right Leg"),
                            ("feet", "Feet"),
                            ("left_finger", "Left Finger"),
                            ("right_finger", "Right Finger"),
                            ("left_ear", "Left Ear"),
                            ("right_ear", "Right Ear"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("tattoo", "Tattoo"),
                            ("scar", "Scar"),
                            ("brand", "Brand"),
                            ("birthmark", "Birthmark"),
                            ("rune", "Rune"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="markings",
                        to="arxii.characterdraft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Draft Marking",
                "verbose_name_plural": "Draft Markings",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="FormMarking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body_region",
                    models.CharField(
                        choices=[
                            ("head", "Head"),
                            ("face", "Face"),
                            ("neck", "Neck"),
                            ("shoulders", "Shoulders"),
                            ("torso", "Torso"),
                            ("back", "Back"),
                            ("waist", "Waist"),
                            ("left_arm", "Left Arm"),
                            ("right_arm", "Right Arm"),
                            ("left_hand", "Left Hand"),
                            ("right_hand", "Right Hand"),
                            ("left_leg", "Left Leg"),
                            ("right_leg", "Right Leg"),
                            ("feet", "Feet"),
                            ("left_finger", "Left Finger"),
                            ("right_finger", "Right Finger"),
                            ("left_ear", "Left Ear"),
                            ("right_ear", "Right Ear"),
                        ],
                        help_text="Where on the body the marking sits (same vocabulary as equipment slots).",
                        max_length=20,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("tattoo", "Tattoo"),
                            ("scar", "Scar"),
                            ("brand", "Brand"),
                            ("birthmark", "Birthmark"),
                            ("rune", "Rune"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='The look-line label ("a columbina-mask tattoo").',
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Prose shown on close inspection / web detail.",
                    ),
                ),
                (
                    "revealed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set by the Reveal action: a deliberately bared marking counts as visible despite covering garments. Cleared by Cover or by equipping a non-revealing garment over the region.",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("chargen", "Character Creation"),
                            ("gm_grant", "GM Grant"),
                            ("system", "System"),
                        ],
                        default="gm_grant",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="markings",
                        to="arxii.characterform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Marking",
                "verbose_name_plural": "Form Markings",
                "ordering": ["created_at"],
            },
        ),
    ]
