# Generated by Django 5.2.15 on 2026-08-05 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0108_draftmarking_formmarking"),
    ]

    operations = [
        migrations.CreateModel(
            name="DreamwalkPresence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dreamer",
                    models.OneToOneField(
                        help_text="The dreamwalker whose perception is displaced.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dreamwalk_presence",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        help_text="The dreamer whose dreamspace the walker perceives.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dream_visitors",
                        to="arxii.charactersheet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dreamwalk Presence",
                "verbose_name_plural": "Dreamwalk Presences",
                "ordering": ["pk"],
            },
        ),
    ]
