# Generated by Django 5.2.16 on 2026-09-08 18:53

from django.db import migrations, models
import django.db.models.deletion

import core.natural_keys


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0114_offer_openers_and_enemy_reasons"),
    ]

    operations = [
        migrations.AddField(
            model_name="realm",
            name="formal_name",
            field=models.CharField(
                blank=True,
                help_text="The long name the realm page shows under the title (#3725), e.g. 'The Umbral Empire'. Blank shows nothing.",
                max_length=150,
            ),
        ),
        migrations.CreateModel(
            name="RealmTestamentSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "written_on",
                    models.DateField(
                        blank=True, help_text="Date the prose was written.", null=True
                    ),
                ),
                (
                    "reviewed_on",
                    models.DateField(
                        blank=True, help_text="Date the prose was reviewed.", null=True
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        help_text="Position of this movement in the testament, from 1."
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="The movement's paragraphs; blank lines separate paragraphs."
                    ),
                ),
                (
                    "motto",
                    models.CharField(
                        blank=True,
                        help_text="The line the movement ends on, shown in the display face. Blank shows nothing.",
                        max_length=200,
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        help_text="The realm this movement belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testament_sections",
                        to="arxii.realm",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who reviewed this row's prose, if anyone. Distinct from writing it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.contentcontributor",
                    ),
                ),
                (
                    "written_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who wrote this row's prose. Null means it is still a placeholder.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.contentcontributor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Realm testament section",
                "verbose_name_plural": "Realm testament sections",
                "ordering": ["realm", "sort_order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("realm", "sort_order"),
                        name="realm_testament_section_order",
                    )
                ],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
    ]
