# Generated by Django 5.2.15 on 2026-08-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0114_rename_exposes_skin_silhouette_exposes_beneath"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equippeditem",
            name="revealed_at",
        ),
        migrations.RemoveField(
            model_name="formmarking",
            name="revealed_at",
        ),
        migrations.RemoveField(
            model_name="templateslot",
            name="covers_lower_layers",
        ),
        migrations.AddField(
            model_name="equippeditem",
            name="opened_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Worn open (#2985): the show verb parts this garment so whatever lies beneath it shows — the next layer, or skin at the bottom of the stack. Cleared by conceal or by dressing at the region; dies with the row on unequip.",
                null=True,
            ),
        ),
    ]
