# Generated by Django 5.2.15 on 2026-08-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0117_alter_techniqueprogress_source"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="craftingrecipe",
            name="items_craftingrecipe_kind_output_unique",
        ),
        migrations.AddConstraint(
            model_name="craftingmaterialrequirement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("item_template__isnull", False)),
                fields=("recipe", "item_template"),
                name="items_craftingmaterialrequirement_recipe_template_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="craftingmaterialrequirement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("material_category__isnull", False)),
                fields=("recipe", "material_category"),
                name="items_craftingmaterialrequirement_recipe_category_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="craftingrecipe",
            constraint=models.UniqueConstraint(
                fields=("kind", "output_item_template"),
                name="items_craftingrecipe_kind_output_unique",
                nulls_distinct=False,
            ),
        ),
    ]
