# Generated by Django 5.2.15 on 2026-08-07 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0119_mute_account_level_mute_muted_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="discovery",
            name="discovered_by_tenure",
            field=models.ForeignKey(
                default=1,
                help_text="The tenure (character piloted by a player) that first discovered this achievement. Required: discoveries are partly-OOC accolades earned through a character, and a sheet with no player tenure cannot claim a first-ever slot (#3055). Tenures are never deleted post-release, so this is PROTECT rather than CASCADE/SET_NULL.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="discoveries",
                to="arxii.rostertenure",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discovery",
            name="shared_with_tenures",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tenures that co-discovered this achievement in the same moment as the primary discoverer (a party or covenant finding it together). A player's full discovery record is the union of their tenures' 'discoveries' (primary) and 'shared_discoveries' (shared credit) (#3055).",
                related_name="shared_discoveries",
                to="arxii.rostertenure",
            ),
        ),
    ]
