# Generated by Django 5.2.16 on 2026-09-10 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0119_xp_attributed_to_character"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InteractionReadReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="Denormalized from interaction — required for composite FK with partitioned table"
                    ),
                ),
                ("seen_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interaction_read_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interaction",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="The pose marked read",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_receipts",
                        to="arxii.interaction",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("interaction", "timestamp", "account"),
                        name="unique_read_receipt_per_account",
                    )
                ],
            },
        ),
    ]
