# Generated by Django 5.2.16 on 2026-09-11 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("arxii", "0120_interactionreadreceipt")]

    operations = [
        migrations.CreateModel(
            name="PoseSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_request_id",
                    models.UUIDField(
                        help_text="Client-minted id, reused verbatim on retry of the same attempt."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interaction",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="The Interaction this submission produced.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pose_submission",
                        to="arxii.interaction",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pose_submissions",
                        to="arxii.persona",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["created_at"], name="arxii_poses_created_acb573_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("persona", "client_request_id"),
                        name="unique_submission_per_persona",
                    )
                ],
            },
        ),
    ]
