# Generated by Django 5.2.16 on 2026-09-11 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0125_beingnickname_organization_patron_nickname_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeingResonance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[("favored", "Favored"), ("associated", "Associated")],
                        max_length=20,
                    ),
                ),
                (
                    "being",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resonances",
                        to="arxii.worshippedbeing",
                    ),
                ),
                (
                    "resonance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="favored_by_beings",
                        to="arxii.resonance",
                    ),
                ),
            ],
            options={
                "ordering": ["being", "-tier", "resonance__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("being", "resonance"), name="unique_being_resonance"
                    )
                ],
            },
        ),
    ]
