# Generated by Django 5.2.15 on 2026-08-09 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("arxii", "0126_alter_trap_is_hidden")]

    operations = [
        migrations.AddField(
            model_name="duelchallenge",
            name="is_lethal",
            field=models.BooleanField(
                default=False,
                help_text="True iff this is a GM-initiated lethal duel proposal (#3068) — a climactic PC-vs-significant-NPC confrontation. Accepting routes through create_lethal_duel instead of create_pvp_duel.",
            ),
        ),
        migrations.AddField(
            model_name="duelchallenge",
            name="opponent_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name of the significant NPC antagonist. Set only when is_lethal.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="duelchallenge",
            name="opponent_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("swarm", "Swarm"),
                    ("mook", "Mook"),
                    ("elite", "Elite"),
                    ("boss", "Boss"),
                    ("hero_killer", "Hero Killer"),
                ],
                default="",
                help_text="Opponent tier for the lethal duel; must be a significant-NPC tier (ELITE/BOSS/HERO_KILLER — enforced by create_lethal_duel_challenge). Set only when is_lethal.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="duelchallenge",
            name="threat_pool",
            field=models.ForeignKey(
                blank=True,
                help_text="The NPC's move-set. Set only when is_lethal.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lethal_duel_challenges",
                to="arxii.threatpool",
            ),
        ),
        migrations.AlterField(
            model_name="duelchallenge",
            name="challenger_sheet",
            field=models.ForeignKey(
                blank=True,
                help_text="The PC who issued the challenge. Null for a GM-initiated lethal challenge (is_lethal=True) — the challenger is a significant NPC, described by opponent_name/opponent_tier/threat_pool instead.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="duel_challenges_issued",
                to="arxii.charactersheet",
            ),
        ),
    ]
