# Generated by Django 5.2.15 on 2026-08-09 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("arxii", "0129_gmsummonoffer")]

    operations = [
        migrations.AddField(
            model_name="consequence",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who reviewed this row's prose, if anyone. Distinct from writing it.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="arxii.contentcontributor",
            ),
        ),
        migrations.AddField(
            model_name="consequence",
            name="reviewed_on",
            field=models.DateField(blank=True, help_text="Date the prose was reviewed.", null=True),
        ),
        migrations.AddField(
            model_name="consequence",
            name="written_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who wrote this row's prose. Null means it is still a placeholder.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="arxii.contentcontributor",
            ),
        ),
        migrations.AddField(
            model_name="consequence",
            name="written_on",
            field=models.DateField(blank=True, help_text="Date the prose was written.", null=True),
        ),
        migrations.AddField(
            model_name="consequenceeffect",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who reviewed this row's prose, if anyone. Distinct from writing it.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="arxii.contentcontributor",
            ),
        ),
        migrations.AddField(
            model_name="consequenceeffect",
            name="reviewed_on",
            field=models.DateField(blank=True, help_text="Date the prose was reviewed.", null=True),
        ),
        migrations.AddField(
            model_name="consequenceeffect",
            name="secret",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consequence_effects",
                to="arxii.secret",
            ),
        ),
        migrations.AddField(
            model_name="consequenceeffect",
            name="written_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who wrote this row's prose. Null means it is still a placeholder.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="arxii.contentcontributor",
            ),
        ),
        migrations.AddField(
            model_name="consequenceeffect",
            name="written_on",
            field=models.DateField(blank=True, help_text="Date the prose was written.", null=True),
        ),
        migrations.AddField(
            model_name="consequencepool",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who reviewed this row's prose, if anyone. Distinct from writing it.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="arxii.contentcontributor",
            ),
        ),
        migrations.AddField(
            model_name="consequencepool",
            name="reviewed_on",
            field=models.DateField(blank=True, help_text="Date the prose was reviewed.", null=True),
        ),
        migrations.AddField(
            model_name="consequencepool",
            name="written_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who wrote this row's prose. Null means it is still a placeholder.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="arxii.contentcontributor",
            ),
        ),
        migrations.AddField(
            model_name="consequencepool",
            name="written_on",
            field=models.DateField(blank=True, help_text="Date the prose was written.", null=True),
        ),
        migrations.AlterField(
            model_name="consequenceeffect",
            name="effect_type",
            field=models.CharField(
                choices=[
                    ("apply_condition", "Apply Condition"),
                    ("remove_condition", "Remove Condition"),
                    ("set_relationship_condition", "Set Relationship Condition"),
                    ("shift_affection", "Shift Affection"),
                    ("shift_npc_regard", "Shift NPC Regard"),
                    ("add_property", "Add Property"),
                    ("remove_property", "Remove Property"),
                    ("grant_distinction", "Grant Distinction"),
                    ("deal_damage", "Deal Damage"),
                    ("launch_attack", "Launch Attack"),
                    ("launch_flow", "Launch Flow"),
                    ("grant_codex", "Grant Codex Entry"),
                    ("grant_secret", "Grant Secret Knowledge"),
                    ("magical_scars", "Mage Scars"),
                    ("legend_award", "Award Legend"),
                    ("capture", "Capture"),
                    ("escape_captivity", "Escape Captivity"),
                    ("rescue_captive", "Rescue Captive"),
                    ("create_position", "Create Position"),
                    ("move_to_position", "Move to Position"),
                    ("sever_edge", "Sever Edge"),
                    ("connect_edge", "Connect Edge"),
                    ("grant_flight", "Grant Flight"),
                    ("remove_flight", "Remove Flight"),
                    ("asset_status", "Asset Status"),
                    ("restore_fatigue", "Restore Fatigue"),
                    ("restore_anima", "Restore Anima"),
                    ("intoxicate", "Intoxicate"),
                ],
                max_length=32,
            ),
        ),
    ]
