# Generated by Django 5.2.16 on 2026-08-10 00:07

from django.db import migrations, models
import django.db.models.deletion

import core.natural_keys


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0130_consequence_reviewed_by_consequence_reviewed_on_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrestigeRankBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[("org", "Organization"), ("persona", "Persona")],
                        default="org",
                        max_length=10,
                    ),
                ),
                (
                    "min_rank",
                    models.PositiveIntegerField(
                        help_text="Best (lowest) 1-based rank this band covers."
                    ),
                ),
                (
                    "max_rank",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Worst rank covered; null = everything below min_rank.",
                        null=True,
                    ),
                ),
                (
                    "negative_only",
                    models.BooleanField(
                        default=False,
                        help_text="Applies only to holders of NEGATIVE prestige (rank is ignored).",
                    ),
                ),
                (
                    "prosperity_bonus",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Weekly prosperity drift for landed orgs in this band with zero open threats (#3091: prestige pays through bounded prosperity).",
                    ),
                ),
            ],
            options={
                "ordering": ["negative_only", "min_rank"],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="StatureBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
                (
                    "rank",
                    models.PositiveSmallIntegerField(
                        help_text="1 = highest band; bands are ordered, not overlapping."
                    ),
                ),
                (
                    "min_percentile",
                    models.PositiveSmallIntegerField(
                        help_text="Lowest cohort percentile (0-100) that earns this band."
                    ),
                ),
                (
                    "threat_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="Ambient threat chance is scaled by this for orgs in this band — weak-looking houses get probed harder (#3091 predation).",
                        max_digits=4,
                    ),
                ),
                (
                    "headline_template",
                    models.TextField(
                        blank=True,
                        help_text="Qualitative headline for the org page; '{org}' interpolates the org name. PLACEHOLDER prose pending the tuning pass.",
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.AddField(
            model_name="kinsperson",
            name="gifted_rating",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Staff-rated Gifted weight 0-5 for kin WITHOUT sheets (#3091). Sparse by design: only significant figures are Gifted; the wider population stays 0. Sheet-bound kin rate from their sheet instead. Feeds house stature and the MOST_POWERFUL_GIFTED succession rater.",
            ),
        ),
        migrations.AddField(
            model_name="nobiliaryparticle",
            name="spouse_particle",
            field=models.CharField(
                blank=True,
                help_text="Married-in spouse form (#3091): a courtesy-titled spouse renders this particle with their BIRTH family name after the married style, keeping the alliance legible in the name. PLACEHOLDER; blank = no spouse form for this realm/family type.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="unionkind",
            name="contributes_to_origin_house",
            field=models.BooleanField(
                default=True,
                help_text="Marriage counts both spouses to BOTH houses (additive, #3091 ruling); consort kinds contribute nothing back to the origin house.",
            ),
        ),
        migrations.AddField(
            model_name="unionkind",
            name="max_concurrent",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Realm cap on concurrent unions of this kind per senior party (Inferna consorts: 3; Umbros/Ariwn/Aythirmok: 1). Null = uncapped.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unionkind",
            name="requires_landed_title",
            field=models.BooleanField(
                default=False,
                help_text="Stature weight only flows while the senior party holds a Title with a seat (the ruling Grand Princess, not her courtesy-styled spouse).",
            ),
        ),
        migrations.AddField(
            model_name="unionkind",
            name="stature_share_pct",
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text="Percent of a partner's renown this union contributes to house stature.",
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="tier",
            field=models.CharField(
                choices=[
                    ("empire", "Empire"),
                    ("kingdom", "Kingdom"),
                    ("duchy", "Duchy"),
                    ("march", "March"),
                    ("county", "County"),
                    ("barony", "Barony"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OrgPrestigeRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prestige_rank", models.PositiveIntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestige_rank_row",
                        to="arxii.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["prestige_rank"],
            },
        ),
        migrations.CreateModel(
            name="HouseStature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("renown_strength", models.IntegerField(default=0)),
                ("military_strength", models.IntegerField(default=0)),
                ("economic_strength", models.IntegerField(default=0)),
                ("allied_strength", models.IntegerField(default=0)),
                (
                    "crisis_penalty",
                    models.IntegerField(
                        default=0,
                        help_text="Deduction from open threats (blood in the water); cleared on resolve.",
                    ),
                ),
                ("true_total", models.IntegerField(default=0)),
                (
                    "perceived_total",
                    models.IntegerField(
                        default=0,
                        help_text="What the world believes; converges toward true_total weekly.",
                    ),
                ),
                (
                    "prestige_rank",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="1-based rank among ALL orgs by prestige standing (#3091, rank-relative).",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stature",
                        to="arxii.organization",
                    ),
                ),
                (
                    "band",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_orgs",
                        to="arxii.statureband",
                    ),
                ),
                (
                    "previous_band",
                    models.ForeignKey(
                        blank=True,
                        help_text="Band before the last assignment — drives the trend display.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.statureband",
                    ),
                ),
            ],
            options={
                "ordering": ["-perceived_total"],
            },
        ),
        migrations.CreateModel(
            name="StatureShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cause",
                    models.CharField(
                        choices=[
                            ("death", "A Death"),
                            ("pact_signed", "Pact Signed"),
                            ("pact_dissolved", "Pact Dissolved"),
                            ("crisis_opened", "Crisis Opened"),
                            ("crisis_surfaced", "Crisis Surfaced"),
                            ("crisis_resolved", "Crisis Resolved"),
                            ("whispers", "Whisper Campaign"),
                            ("convergence", "Word Spreads"),
                            ("recompute", "Weekly Recompute"),
                        ],
                        max_length=20,
                    ),
                ),
                ("delta_true", models.IntegerField(default=0)),
                ("delta_perceived", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stature_shifts",
                        to="arxii.organization",
                    ),
                ),
                (
                    "subject_kinsperson",
                    models.ForeignKey(
                        blank=True,
                        help_text="The person whose death/marriage moved the number, when one did.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.kinsperson",
                    ),
                ),
                (
                    "subject_persona",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.persona",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
