# Generated by Django 5.2.16 on 2026-09-11 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0130_codexentry_quote"),
    ]

    operations = [
        migrations.AddField(
            model_name="worshippedbeing",
            name="codex_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="This being's Codex page. Visibility (Public/Obscure/Secret) is read entirely through the linked entry's is_public tier — no separate visibility field on WorshippedBeing itself.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="worshipped_beings",
                to="arxii.codexentry",
            ),
        ),
    ]
