# Generated by Django 5.2.16 on 2026-08-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0131_prestigerankband_statureband_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskoutcomeroute",
            name="whisper_stature_delta",
            field=models.PositiveIntegerField(
                default=0,
                help_text="ORG target: whisper campaign (#3091) — push the target's PERCEIVED stature down by up to this much, bounded below their true stature by the displacement cap. Zero = payout disabled.",
            ),
        ),
    ]
