# Generated by Django 5.2.16 on 2026-09-12 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0133_normalize_trust_required_access_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="interactionthread",
            name="anchor_interaction",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The interaction every row in this thread answers. Null only on threads written before #3787, when a thread was a flat membership container.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anchored_threads",
                to="arxii.interaction",
            ),
        ),
        migrations.AddField(
            model_name="interactionthread",
            name="anchor_timestamp",
            field=models.DateTimeField(
                blank=True,
                help_text="Denormalized from anchor_interaction - arxii_interaction is range-partitioned on timestamp with a composite primary key, so a single-column FK to its id cannot exist (the InteractionReceiver precedent).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="interactionthread",
            name="root",
            field=models.ForeignKey(
                blank=True,
                help_text="Denormalized top of the nesting tree, so a reader groups an exchange without walking parents. Null when this thread IS the root.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="descendant_threads",
                to="arxii.interactionthread",
            ),
        ),
        migrations.AlterField(
            model_name="interactionthread",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="The thread the anchor row itself belongs to, when the anchor is a reply. Null when the anchor is not a reply, which makes this thread a root.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_threads",
                to="arxii.interactionthread",
            ),
        ),
        migrations.AddConstraint(
            model_name="interactionthread",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("anchor_interaction__isnull", True),
                        ("anchor_timestamp__isnull", True),
                    ),
                    models.Q(
                        ("anchor_interaction__isnull", False),
                        ("anchor_timestamp__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="interaction_thread_anchor_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="interactionthread",
            constraint=models.UniqueConstraint(
                fields=("anchor_interaction", "anchor_timestamp"),
                name="unique_thread_per_anchor",
            ),
        ),
    ]
