# Generated by Django 5.2.16 on 2026-09-16 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0135_areaelevationrequirement_domain_defenses_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Relic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lore", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["being", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="RiteKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "tier",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Devotional"), (2, "Demanding"), (3, "Perilous")],
                        default=1,
                        help_text="Sets the AP cost (1 per tier) and the award table row; tier 3 is a Ceremony.",
                    ),
                ),
            ],
            options={
                "ordering": ["tier", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorshipRite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["being", "kind__tier", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorshipRitePerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resonance_granted", models.PositiveIntegerField(default=0)),
                ("favor_granted", models.PositiveIntegerField(default=0)),
                (
                    "performed_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
            ],
            options={
                "ordering": ["-performed_at"],
            },
        ),
        migrations.CreateModel(
            name="WorshipRiteTierAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Devotional"), (2, "Demanding"), (3, "Perilous")]
                    ),
                ),
                (
                    "resonance_amount",
                    models.PositiveIntegerField(
                        help_text="Resonance granted to the performer for this tier and outcome."
                    ),
                ),
                (
                    "favor_amount",
                    models.PositiveIntegerField(
                        help_text="Devotion favor granted (at most once per rite per week) for this tier and outcome."
                    ),
                ),
            ],
            options={
                "ordering": ["tier", "outcome_tier__success_level"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="resonancegrant",
            name="res_grant_residence_shape",
        ),
        migrations.RemoveConstraint(
            model_name="resonancegrant",
            name="res_grant_staff_shape",
        ),
        migrations.RemoveConstraint(
            model_name="resonancegrant",
            name="res_grant_mission_report_shape",
        ),
        migrations.RemoveConstraint(
            model_name="resonancegrant",
            name="res_grant_stake_reward_shape",
        ),
        migrations.RemoveConstraint(
            model_name="resonancegrant",
            name="res_grant_pose_endorsement_shape",
        ),
        migrations.RemoveConstraint(
            model_name="resonancegrant",
            name="res_grant_scene_entry_shape",
        ),
        migrations.RemoveConstraint(
            model_name="resonancegrant",
            name="res_grant_outfit_trickle_shape",
        ),
        migrations.RemoveConstraint(
            model_name="resonancegrant",
            name="res_grant_sanctum_weaving_shape",
        ),
        migrations.RemoveConstraint(
            model_name="resonancegrant",
            name="res_grant_sanctum_owner_bonus_shape",
        ),
        migrations.RemoveConstraint(
            model_name="resonancegrant",
            name="res_grant_sanctum_dissolution_recovery_shape",
        ),
        migrations.RemoveConstraint(
            model_name="resonancegrant",
            name="res_grant_project_contribution_shape",
        ),
        migrations.RemoveConstraint(
            model_name="resonancegrant",
            name="res_grant_entry_flourish_shape",
        ),
        migrations.RemoveConstraint(
            model_name="resonancegrant",
            name="res_grant_dramatic_moment_shape",
        ),
        migrations.RemoveConstraint(
            model_name="resonancegrant",
            name="res_grant_style_presentation_shape",
        ),
        migrations.RemoveConstraint(
            model_name="resonancegrant",
            name="res_grant_mission_reward_shape",
        ),
        migrations.RemoveConstraint(
            model_name="resonancegrant",
            name="res_grant_compromise_shape",
        ),
        migrations.RemoveConstraint(
            model_name="resonancegrant",
            name="res_grant_penance_shape",
        ),
        migrations.RemoveConstraint(
            model_name="resonancegrant",
            name="res_grant_fall_conversion_shape",
        ),
        migrations.AddField(
            model_name="ceremonyconfig",
            name="offering_favored_facet_multiplier_percent",
            field=models.PositiveIntegerField(
                default=200,
                help_text="Percent multiplier on an offering's pool grant and devotion bump when the offered item carries a Facet the being favors (BeingFacet), #3777. 100 = no bonus.",
            ),
        ),
        migrations.AlterField(
            model_name="ceremonytype",
            name="key",
            field=models.CharField(
                choices=[
                    ("funeral", "Funeral"),
                    ("blessing", "Blessing"),
                    ("sermon", "Sermon"),
                    ("seance", "Seance"),
                    ("wedding", "Wedding"),
                    ("conversion", "Conversion"),
                    ("coronation", "Coronation"),
                    ("rite", "Rite"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="resonancegrant",
            name="source",
            field=models.CharField(
                choices=[
                    ("POSE_ENDORSEMENT", "Pose endorsement"),
                    ("SCENE_ENTRY", "Scene entry endorsement"),
                    ("ROOM_RESIDENCE", "Room residence trickle"),
                    ("OUTFIT_TRICKLE", "Outfit trickle"),
                    ("STAFF_GRANT", "Staff grant"),
                    ("SANCTUM_WEAVING", "Sanctum weaving payout"),
                    ("SANCTUM_OWNER_BONUS", "Sanctum owner/member bonus"),
                    ("PROJECT_CONTRIBUTION", "Project contribution payout"),
                    ("SANCTUM_DISSOLUTION_RECOVERY", "Sanctum dissolution recovery"),
                    ("ENTRY_FLOURISH", "Entry flourishing"),
                    ("DRAMATIC_MOMENT", "Dramatic moment"),
                    ("STYLE_PRESENTATION", "Style presentation"),
                    ("MISSION_REWARD", "Mission reward"),
                    ("MISSION_REPORT", "Mission report style"),
                    ("STAKE_REWARD", "Stake reward"),
                    ("DISTINCTION", "Distinction"),
                    ("COMBO_DISCOVERY", "Combo discovery"),
                    ("COMPROMISE", "Moral compromise"),
                    ("PENANCE", "Atonement resonance conversion"),
                    ("FALL_CONVERSION", "Fall/Redemption conversion"),
                    ("WORSHIP_RITE", "Worship rite"),
                ],
                help_text="Discriminator. Identifies which source_* FK is populated.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="relic",
            name="being",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relics",
                to="arxii.worshippedbeing",
            ),
        ),
        migrations.AddField(
            model_name="relic",
            name="item_instance",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relic_of",
                to="arxii.iteminstance",
            ),
        ),
        migrations.AddField(
            model_name="worshiprite",
            name="being",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rites",
                to="arxii.worshippedbeing",
            ),
        ),
        migrations.AddField(
            model_name="worshiprite",
            name="check_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="worship_rites",
                to="arxii.checktype",
            ),
        ),
        migrations.AddField(
            model_name="worshiprite",
            name="kind",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rites",
                to="arxii.ritekind",
            ),
        ),
        migrations.AddField(
            model_name="worshiprite",
            name="resonance",
            field=models.ForeignKey(
                help_text="Which of this being's own resonances the rite channels (must belong to being).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rites",
                to="arxii.beingresonance",
            ),
        ),
        migrations.AddField(
            model_name="ceremony",
            name="worship_rite",
            field=models.ForeignKey(
                blank=True,
                help_text="A tier 3 rite this ceremony performs (#3777): at finish the officiant's Rites roll pays the rite's tier award on top of the ceremony's own honors.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ceremonies",
                to="arxii.worshiprite",
            ),
        ),
        migrations.AddField(
            model_name="worshipriteperformance",
            name="ceremony",
            field=models.OneToOneField(
                blank=True,
                help_text="Set for a tier 3 rite: the Ceremony whose finish resolved it.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rite_performance",
                to="arxii.ceremony",
            ),
        ),
        migrations.AddField(
            model_name="worshipriteperformance",
            name="character_sheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rite_performances",
                to="arxii.charactersheet",
            ),
        ),
        migrations.AddField(
            model_name="worshipriteperformance",
            name="game_week",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rite_performances",
                to="arxii.gameweek",
            ),
        ),
        migrations.AddField(
            model_name="worshipriteperformance",
            name="outcome_tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rite_performances",
                to="arxii.checkoutcome",
            ),
        ),
        migrations.AddField(
            model_name="worshipriteperformance",
            name="rite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="performances",
                to="arxii.worshiprite",
            ),
        ),
        migrations.AddField(
            model_name="worshipriteperformance",
            name="scene",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rite_performances",
                to="arxii.scene",
            ),
        ),
        migrations.AddField(
            model_name="resonancegrant",
            name="source_worship_rite_performance",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when source=WORSHIP_RITE (#3777).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resonance_grants",
                to="arxii.worshipriteperformance",
            ),
        ),
        migrations.AddConstraint(
            model_name="resonancegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source", "ROOM_RESIDENCE"),
                        ("source_room_profile__isnull", False),
                        ("source_staff_account__isnull", True),
                        ("source_pose_endorsement__isnull", True),
                        ("source_scene_entry_endorsement__isnull", True),
                        ("outfit_item_facet__isnull", True),
                        ("source_sanctum_details__isnull", True),
                        ("source_project__isnull", True),
                        ("source_entry_flourish__isnull", True),
                        ("source_dramatic_moment__isnull", True),
                        ("source_style_presentation_endorsement__isnull", True),
                        ("source_mission_deed_reward_line__isnull", True),
                        ("source_character_distinction__isnull", True),
                        ("source_worship_rite_performance__isnull", True),
                    ),
                    models.Q(("source", "ROOM_RESIDENCE"), _negated=True),
                    _connector="OR",
                ),
                name="res_grant_residence_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="resonancegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source", "STAFF_GRANT"),
                        ("source_room_profile__isnull", True),
                        ("source_pose_endorsement__isnull", True),
                        ("source_scene_entry_endorsement__isnull", True),
                        ("outfit_item_facet__isnull", True),
                        ("source_sanctum_details__isnull", True),
                        ("source_project__isnull", True),
                        ("source_entry_flourish__isnull", True),
                        ("source_dramatic_moment__isnull", True),
                        ("source_style_presentation_endorsement__isnull", True),
                        ("source_mission_deed_reward_line__isnull", True),
                        ("source_character_distinction__isnull", True),
                        ("source_worship_rite_performance__isnull", True),
                    ),
                    models.Q(("source", "STAFF_GRANT"), _negated=True),
                    _connector="OR",
                ),
                name="res_grant_staff_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="resonancegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source", "MISSION_REPORT"),
                        ("source_room_profile__isnull", True),
                        ("source_staff_account__isnull", True),
                        ("source_pose_endorsement__isnull", True),
                        ("source_scene_entry_endorsement__isnull", True),
                        ("outfit_item_facet__isnull", True),
                        ("source_sanctum_details__isnull", True),
                        ("source_project__isnull", True),
                        ("source_entry_flourish__isnull", True),
                        ("source_dramatic_moment__isnull", True),
                        ("source_style_presentation_endorsement__isnull", True),
                        ("source_mission_deed_reward_line__isnull", True),
                        ("source_character_distinction__isnull", True),
                        ("source_worship_rite_performance__isnull", True),
                    ),
                    models.Q(("source", "MISSION_REPORT"), _negated=True),
                    _connector="OR",
                ),
                name="res_grant_mission_report_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="resonancegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source", "STAKE_REWARD"),
                        ("source_room_profile__isnull", True),
                        ("source_staff_account__isnull", True),
                        ("source_pose_endorsement__isnull", True),
                        ("source_scene_entry_endorsement__isnull", True),
                        ("outfit_item_facet__isnull", True),
                        ("source_sanctum_details__isnull", True),
                        ("source_project__isnull", True),
                        ("source_entry_flourish__isnull", True),
                        ("source_dramatic_moment__isnull", True),
                        ("source_style_presentation_endorsement__isnull", True),
                        ("source_mission_deed_reward_line__isnull", True),
                        ("source_character_distinction__isnull", True),
                        ("source_worship_rite_performance__isnull", True),
                    ),
                    models.Q(("source", "STAKE_REWARD"), _negated=True),
                    _connector="OR",
                ),
                name="res_grant_stake_reward_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="resonancegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source", "POSE_ENDORSEMENT"),
                        ("source_pose_endorsement__isnull", False),
                        ("source_room_profile__isnull", True),
                        ("source_staff_account__isnull", True),
                        ("source_scene_entry_endorsement__isnull", True),
                        ("outfit_item_facet__isnull", True),
                        ("source_sanctum_details__isnull", True),
                        ("source_project__isnull", True),
                        ("source_entry_flourish__isnull", True),
                        ("source_dramatic_moment__isnull", True),
                        ("source_style_presentation_endorsement__isnull", True),
                        ("source_mission_deed_reward_line__isnull", True),
                        ("source_character_distinction__isnull", True),
                        ("source_worship_rite_performance__isnull", True),
                    ),
                    models.Q(("source", "POSE_ENDORSEMENT"), _negated=True),
                    _connector="OR",
                ),
                name="res_grant_pose_endorsement_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="resonancegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source", "SCENE_ENTRY"),
                        ("source_scene_entry_endorsement__isnull", False),
                        ("source_room_profile__isnull", True),
                        ("source_staff_account__isnull", True),
                        ("source_pose_endorsement__isnull", True),
                        ("outfit_item_facet__isnull", True),
                        ("source_sanctum_details__isnull", True),
                        ("source_project__isnull", True),
                        ("source_entry_flourish__isnull", True),
                        ("source_dramatic_moment__isnull", True),
                        ("source_style_presentation_endorsement__isnull", True),
                        ("source_mission_deed_reward_line__isnull", True),
                        ("source_character_distinction__isnull", True),
                        ("source_worship_rite_performance__isnull", True),
                    ),
                    models.Q(("source", "SCENE_ENTRY"), _negated=True),
                    _connector="OR",
                ),
                name="res_grant_scene_entry_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="resonancegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source", "OUTFIT_TRICKLE"),
                        ("outfit_item_facet__isnull", False),
                        ("source_room_profile__isnull", True),
                        ("source_staff_account__isnull", True),
                        ("source_pose_endorsement__isnull", True),
                        ("source_scene_entry_endorsement__isnull", True),
                        ("source_sanctum_details__isnull", True),
                        ("source_project__isnull", True),
                        ("source_entry_flourish__isnull", True),
                        ("source_dramatic_moment__isnull", True),
                        ("source_style_presentation_endorsement__isnull", True),
                        ("source_mission_deed_reward_line__isnull", True),
                        ("source_character_distinction__isnull", True),
                        ("source_worship_rite_performance__isnull", True),
                    ),
                    models.Q(("source", "OUTFIT_TRICKLE"), _negated=True),
                    _connector="OR",
                ),
                name="res_grant_outfit_trickle_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="resonancegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source", "SANCTUM_WEAVING"),
                        ("source_room_profile__isnull", True),
                        ("source_staff_account__isnull", True),
                        ("source_pose_endorsement__isnull", True),
                        ("source_scene_entry_endorsement__isnull", True),
                        ("outfit_item_facet__isnull", True),
                        ("source_project__isnull", True),
                        ("source_entry_flourish__isnull", True),
                        ("source_dramatic_moment__isnull", True),
                        ("source_style_presentation_endorsement__isnull", True),
                        ("source_mission_deed_reward_line__isnull", True),
                        ("source_character_distinction__isnull", True),
                        ("source_worship_rite_performance__isnull", True),
                    ),
                    models.Q(("source", "SANCTUM_WEAVING"), _negated=True),
                    _connector="OR",
                ),
                name="res_grant_sanctum_weaving_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="resonancegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source", "SANCTUM_OWNER_BONUS"),
                        ("source_room_profile__isnull", True),
                        ("source_staff_account__isnull", True),
                        ("source_pose_endorsement__isnull", True),
                        ("source_scene_entry_endorsement__isnull", True),
                        ("outfit_item_facet__isnull", True),
                        ("source_project__isnull", True),
                        ("source_entry_flourish__isnull", True),
                        ("source_dramatic_moment__isnull", True),
                        ("source_style_presentation_endorsement__isnull", True),
                        ("source_mission_deed_reward_line__isnull", True),
                        ("source_character_distinction__isnull", True),
                        ("source_worship_rite_performance__isnull", True),
                    ),
                    models.Q(("source", "SANCTUM_OWNER_BONUS"), _negated=True),
                    _connector="OR",
                ),
                name="res_grant_sanctum_owner_bonus_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="resonancegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source", "SANCTUM_DISSOLUTION_RECOVERY"),
                        ("source_room_profile__isnull", True),
                        ("source_staff_account__isnull", True),
                        ("source_pose_endorsement__isnull", True),
                        ("source_scene_entry_endorsement__isnull", True),
                        ("outfit_item_facet__isnull", True),
                        ("source_project__isnull", True),
                        ("source_entry_flourish__isnull", True),
                        ("source_dramatic_moment__isnull", True),
                        ("source_style_presentation_endorsement__isnull", True),
                        ("source_mission_deed_reward_line__isnull", True),
                        ("source_character_distinction__isnull", True),
                        ("source_worship_rite_performance__isnull", True),
                    ),
                    models.Q(("source", "SANCTUM_DISSOLUTION_RECOVERY"), _negated=True),
                    _connector="OR",
                ),
                name="res_grant_sanctum_dissolution_recovery_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="resonancegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source", "PROJECT_CONTRIBUTION"),
                        ("source_project__isnull", False),
                        ("source_room_profile__isnull", True),
                        ("source_staff_account__isnull", True),
                        ("source_pose_endorsement__isnull", True),
                        ("source_scene_entry_endorsement__isnull", True),
                        ("outfit_item_facet__isnull", True),
                        ("source_sanctum_details__isnull", True),
                        ("source_entry_flourish__isnull", True),
                        ("source_dramatic_moment__isnull", True),
                        ("source_style_presentation_endorsement__isnull", True),
                        ("source_mission_deed_reward_line__isnull", True),
                        ("source_character_distinction__isnull", True),
                        ("source_worship_rite_performance__isnull", True),
                    ),
                    models.Q(("source", "PROJECT_CONTRIBUTION"), _negated=True),
                    _connector="OR",
                ),
                name="res_grant_project_contribution_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="resonancegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source", "ENTRY_FLOURISH"),
                        ("source_entry_flourish__isnull", False),
                        ("source_room_profile__isnull", True),
                        ("source_staff_account__isnull", True),
                        ("source_pose_endorsement__isnull", True),
                        ("source_scene_entry_endorsement__isnull", True),
                        ("outfit_item_facet__isnull", True),
                        ("source_sanctum_details__isnull", True),
                        ("source_project__isnull", True),
                        ("source_dramatic_moment__isnull", True),
                        ("source_style_presentation_endorsement__isnull", True),
                        ("source_mission_deed_reward_line__isnull", True),
                        ("source_character_distinction__isnull", True),
                        ("source_worship_rite_performance__isnull", True),
                    ),
                    models.Q(("source", "ENTRY_FLOURISH"), _negated=True),
                    _connector="OR",
                ),
                name="res_grant_entry_flourish_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="resonancegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source", "DRAMATIC_MOMENT"),
                        ("source_dramatic_moment__isnull", False),
                        ("source_room_profile__isnull", True),
                        ("source_staff_account__isnull", True),
                        ("source_pose_endorsement__isnull", True),
                        ("source_scene_entry_endorsement__isnull", True),
                        ("outfit_item_facet__isnull", True),
                        ("source_sanctum_details__isnull", True),
                        ("source_project__isnull", True),
                        ("source_entry_flourish__isnull", True),
                        ("source_style_presentation_endorsement__isnull", True),
                        ("source_mission_deed_reward_line__isnull", True),
                        ("source_character_distinction__isnull", True),
                        ("source_worship_rite_performance__isnull", True),
                    ),
                    models.Q(("source", "DRAMATIC_MOMENT"), _negated=True),
                    _connector="OR",
                ),
                name="res_grant_dramatic_moment_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="resonancegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source", "STYLE_PRESENTATION"),
                        ("source_style_presentation_endorsement__isnull", False),
                        ("source_room_profile__isnull", True),
                        ("source_staff_account__isnull", True),
                        ("source_pose_endorsement__isnull", True),
                        ("source_scene_entry_endorsement__isnull", True),
                        ("outfit_item_facet__isnull", True),
                        ("source_sanctum_details__isnull", True),
                        ("source_project__isnull", True),
                        ("source_entry_flourish__isnull", True),
                        ("source_dramatic_moment__isnull", True),
                        ("source_mission_deed_reward_line__isnull", True),
                        ("source_character_distinction__isnull", True),
                        ("source_worship_rite_performance__isnull", True),
                    ),
                    models.Q(("source", "STYLE_PRESENTATION"), _negated=True),
                    _connector="OR",
                ),
                name="res_grant_style_presentation_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="resonancegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source", "MISSION_REWARD"),
                        ("source_mission_deed_reward_line__isnull", False),
                        ("source_room_profile__isnull", True),
                        ("source_staff_account__isnull", True),
                        ("source_pose_endorsement__isnull", True),
                        ("source_scene_entry_endorsement__isnull", True),
                        ("outfit_item_facet__isnull", True),
                        ("source_sanctum_details__isnull", True),
                        ("source_project__isnull", True),
                        ("source_entry_flourish__isnull", True),
                        ("source_dramatic_moment__isnull", True),
                        ("source_style_presentation_endorsement__isnull", True),
                        ("source_character_distinction__isnull", True),
                        ("source_worship_rite_performance__isnull", True),
                    ),
                    models.Q(("source", "MISSION_REWARD"), _negated=True),
                    _connector="OR",
                ),
                name="res_grant_mission_reward_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="resonancegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source", "COMPROMISE"),
                        ("source_room_profile__isnull", True),
                        ("source_staff_account__isnull", True),
                        ("source_pose_endorsement__isnull", True),
                        ("source_scene_entry_endorsement__isnull", True),
                        ("outfit_item_facet__isnull", True),
                        ("source_sanctum_details__isnull", True),
                        ("source_project__isnull", True),
                        ("source_entry_flourish__isnull", True),
                        ("source_dramatic_moment__isnull", True),
                        ("source_style_presentation_endorsement__isnull", True),
                        ("source_mission_deed_reward_line__isnull", True),
                        ("source_character_distinction__isnull", True),
                        ("source_worship_rite_performance__isnull", True),
                    ),
                    models.Q(("source", "COMPROMISE"), _negated=True),
                    _connector="OR",
                ),
                name="res_grant_compromise_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="resonancegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source", "PENANCE"),
                        ("source_room_profile__isnull", True),
                        ("source_staff_account__isnull", True),
                        ("source_pose_endorsement__isnull", True),
                        ("source_scene_entry_endorsement__isnull", True),
                        ("outfit_item_facet__isnull", True),
                        ("source_sanctum_details__isnull", True),
                        ("source_project__isnull", True),
                        ("source_entry_flourish__isnull", True),
                        ("source_dramatic_moment__isnull", True),
                        ("source_style_presentation_endorsement__isnull", True),
                        ("source_mission_deed_reward_line__isnull", True),
                        ("source_character_distinction__isnull", True),
                        ("source_worship_rite_performance__isnull", True),
                    ),
                    models.Q(("source", "PENANCE"), _negated=True),
                    _connector="OR",
                ),
                name="res_grant_penance_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="resonancegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source", "FALL_CONVERSION"),
                        ("source_room_profile__isnull", True),
                        ("source_staff_account__isnull", True),
                        ("source_pose_endorsement__isnull", True),
                        ("source_scene_entry_endorsement__isnull", True),
                        ("outfit_item_facet__isnull", True),
                        ("source_sanctum_details__isnull", True),
                        ("source_project__isnull", True),
                        ("source_entry_flourish__isnull", True),
                        ("source_dramatic_moment__isnull", True),
                        ("source_style_presentation_endorsement__isnull", True),
                        ("source_mission_deed_reward_line__isnull", True),
                        ("source_character_distinction__isnull", True),
                        ("source_worship_rite_performance__isnull", True),
                    ),
                    models.Q(("source", "FALL_CONVERSION"), _negated=True),
                    _connector="OR",
                ),
                name="res_grant_fall_conversion_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="resonancegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source", "WORSHIP_RITE"),
                        ("source_worship_rite_performance__isnull", False),
                        ("source_room_profile__isnull", True),
                        ("source_staff_account__isnull", True),
                        ("source_pose_endorsement__isnull", True),
                        ("source_scene_entry_endorsement__isnull", True),
                        ("outfit_item_facet__isnull", True),
                        ("source_sanctum_details__isnull", True),
                        ("source_project__isnull", True),
                        ("source_entry_flourish__isnull", True),
                        ("source_dramatic_moment__isnull", True),
                        ("source_style_presentation_endorsement__isnull", True),
                        ("source_mission_deed_reward_line__isnull", True),
                        ("source_character_distinction__isnull", True),
                    ),
                    models.Q(("source", "WORSHIP_RITE"), _negated=True),
                    _connector="OR",
                ),
                name="res_grant_worship_rite_shape",
            ),
        ),
        migrations.AddField(
            model_name="worshipritetieraward",
            name="outcome_tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="worship_rite_awards",
                to="arxii.checkoutcome",
            ),
        ),
        migrations.AddConstraint(
            model_name="worshiprite",
            constraint=models.UniqueConstraint(
                fields=("being", "name"), name="unique_being_rite_name"
            ),
        ),
        migrations.AddIndex(
            model_name="worshipriteperformance",
            index=models.Index(
                fields=["character_sheet", "rite", "game_week"],
                name="rite_perf_sheet_rite_week",
            ),
        ),
        migrations.AddConstraint(
            model_name="worshipritetieraward",
            constraint=models.UniqueConstraint(
                fields=("tier", "outcome_tier"), name="unique_worship_rite_tier_award"
            ),
        ),
    ]
