# Generated by Django 5.2.16 on 2026-09-16 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0135_areaelevationrequirement_domain_defenses_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiteKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "tier",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Devotional"), (2, "Demanding"), (3, "Perilous")],
                        default=1,
                        help_text="Sets the AP cost (1 per tier) and the award table row; tier 3 is a Ceremony.",
                    ),
                ),
            ],
            options={
                "ordering": ["tier", "name"],
            },
        ),
        migrations.AddField(
            model_name="ceremonyconfig",
            name="offering_favored_facet_multiplier_percent",
            field=models.PositiveIntegerField(
                default=200,
                help_text="Percent multiplier on an offering's pool grant and devotion bump when the offered item carries a Facet the being favors (BeingFacet), #3777. 100 = no bonus.",
            ),
        ),
        migrations.AlterField(
            model_name="resonancegrant",
            name="source",
            field=models.CharField(
                choices=[
                    ("POSE_ENDORSEMENT", "Pose endorsement"),
                    ("SCENE_ENTRY", "Scene entry endorsement"),
                    ("ROOM_RESIDENCE", "Room residence trickle"),
                    ("OUTFIT_TRICKLE", "Outfit trickle"),
                    ("STAFF_GRANT", "Staff grant"),
                    ("SANCTUM_WEAVING", "Sanctum weaving payout"),
                    ("SANCTUM_OWNER_BONUS", "Sanctum owner/member bonus"),
                    ("PROJECT_CONTRIBUTION", "Project contribution payout"),
                    ("SANCTUM_DISSOLUTION_RECOVERY", "Sanctum dissolution recovery"),
                    ("ENTRY_FLOURISH", "Entry flourishing"),
                    ("DRAMATIC_MOMENT", "Dramatic moment"),
                    ("STYLE_PRESENTATION", "Style presentation"),
                    ("MISSION_REWARD", "Mission reward"),
                    ("MISSION_REPORT", "Mission report style"),
                    ("STAKE_REWARD", "Stake reward"),
                    ("DISTINCTION", "Distinction"),
                    ("COMBO_DISCOVERY", "Combo discovery"),
                    ("COMPROMISE", "Moral compromise"),
                    ("PENANCE", "Atonement resonance conversion"),
                    ("FALL_CONVERSION", "Fall/Redemption conversion"),
                    ("WORSHIP_RITE", "Worship rite"),
                ],
                help_text="Discriminator. Identifies which source_* FK is populated.",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="Relic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lore", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "being",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relics",
                        to="arxii.worshippedbeing",
                    ),
                ),
                (
                    "item_instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relic_of",
                        to="arxii.iteminstance",
                    ),
                ),
            ],
            options={
                "ordering": ["being", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorshipRite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "being",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rites",
                        to="arxii.worshippedbeing",
                    ),
                ),
                (
                    "check_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="worship_rites",
                        to="arxii.checktype",
                    ),
                ),
                (
                    "kind",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rites",
                        to="arxii.ritekind",
                    ),
                ),
                (
                    "resonance",
                    models.ForeignKey(
                        help_text="Which of this being's own resonances the rite channels (must belong to being).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rites",
                        to="arxii.beingresonance",
                    ),
                ),
            ],
            options={
                "ordering": ["being", "kind__tier", "name"],
            },
        ),
        migrations.AddField(
            model_name="ceremony",
            name="worship_rite",
            field=models.ForeignKey(
                blank=True,
                help_text="A tier 3 rite this ceremony performs (#3777): at finish the officiant's Rites roll pays the rite's tier award on top of the ceremony's own honors.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ceremonies",
                to="arxii.worshiprite",
            ),
        ),
        migrations.CreateModel(
            name="WorshipRitePerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resonance_granted", models.PositiveIntegerField(default=0)),
                ("favor_granted", models.PositiveIntegerField(default=0)),
                (
                    "performed_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "ceremony",
                    models.OneToOneField(
                        blank=True,
                        help_text="Set for a tier 3 rite: the Ceremony whose finish resolved it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rite_performance",
                        to="arxii.ceremony",
                    ),
                ),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rite_performances",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "game_week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rite_performances",
                        to="arxii.gameweek",
                    ),
                ),
                (
                    "outcome_tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rite_performances",
                        to="arxii.checkoutcome",
                    ),
                ),
                (
                    "rite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="performances",
                        to="arxii.worshiprite",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rite_performances",
                        to="arxii.scene",
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_at"],
            },
        ),
        migrations.AddField(
            model_name="resonancegrant",
            name="source_worship_rite_performance",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when source=WORSHIP_RITE (#3777).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resonance_grants",
                to="arxii.worshipriteperformance",
            ),
        ),
        migrations.CreateModel(
            name="WorshipRiteTierAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Devotional"), (2, "Demanding"), (3, "Perilous")]
                    ),
                ),
                (
                    "resonance_amount",
                    models.PositiveIntegerField(
                        help_text="Resonance granted to the performer for this tier and outcome."
                    ),
                ),
                (
                    "favor_amount",
                    models.PositiveIntegerField(
                        help_text="Devotion favor granted (at most once per rite per week) for this tier and outcome."
                    ),
                ),
                (
                    "outcome_tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="worship_rite_awards",
                        to="arxii.checkoutcome",
                    ),
                ),
            ],
            options={
                "ordering": ["tier", "outcome_tier__success_level"],
            },
        ),
        migrations.AddConstraint(
            model_name="worshiprite",
            constraint=models.UniqueConstraint(
                fields=("being", "name"), name="unique_being_rite_name"
            ),
        ),
        migrations.AddIndex(
            model_name="worshipriteperformance",
            index=models.Index(
                fields=["character_sheet", "rite", "game_week"],
                name="rite_perf_sheet_rite_week",
            ),
        ),
        migrations.AddConstraint(
            model_name="worshipritetieraward",
            constraint=models.UniqueConstraint(
                fields=("tier", "outcome_tier"), name="unique_worship_rite_tier_award"
            ),
        ),
    ]
