# Generated by Django 5.2.16 on 2026-09-16 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0137_alter_roomfeaturekind_service_strategy_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "devotion_granted",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Favor paid by the weekly holy-site prayer; 0 for every other.",
                    ),
                ),
                (
                    "dire_straits",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("soulfray", "Soulfray active"),
                            ("near_death", "Near death"),
                        ],
                        default="",
                        max_length=12,
                    ),
                ),
                ("prayed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "being",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prayers",
                        to="arxii.worshippedbeing",
                    ),
                ),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prayers",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "game_week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prayers",
                        to="arxii.gameweek",
                    ),
                ),
                (
                    "intervention",
                    models.OneToOneField(
                        blank=True,
                        help_text="The miracle that answered a dire-straits prayer, when one did.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="answered_prayer",
                        to="arxii.miracleperformance",
                    ),
                ),
                (
                    "room_profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Where the prayer was made; a shrine or temple here is what pays devotion.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prayers",
                        to="arxii.roomprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prayer",
                "verbose_name_plural": "Prayers",
                "ordering": ["-prayed_at"],
            },
        ),
        migrations.CreateModel(
            name="Vision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                (
                    "reveal_source",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the recipient is told which being sent it.",
                    ),
                ),
                ("resonance_spent", models.PositiveIntegerField(default=0)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "being",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visions",
                        to="arxii.worshippedbeing",
                    ),
                ),
                (
                    "clue",
                    models.ForeignKey(
                        blank=True,
                        help_text="A Codex clue the vision hands the recipient (a mystery's starter).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visions",
                        to="arxii.clue",
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        blank=True,
                        help_text="The episode this is a personal beat of; the recipient must be in its story.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visions",
                        to="arxii.episode",
                    ),
                ),
                (
                    "message",
                    models.OneToOneField(
                        blank=True,
                        help_text="The narrative message (category VISIONS) that delivered it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vision",
                        to="arxii.narrativemessage",
                    ),
                ),
                (
                    "prayer",
                    models.ForeignKey(
                        blank=True,
                        help_text="The prayer this answers, when it answers one.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visions",
                        to="arxii.prayer",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visions",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The GM who composed it; null once that account is gone.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visions_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vision",
                "verbose_name_plural": "Visions",
                "ordering": ["-sent_at"],
            },
        ),
    ]
