# Generated by Django 5.2.16 on 2026-09-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0151_partition_metadata_orm_state"),
        ("arxii", "0155_bond_pull_tuning_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationshiprequirement",
            name="minimum_count",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Number of qualifying sides required (at/above minimum_tier).",
            ),
        ),
        migrations.AlterField(
            model_name="relationshiprequirement",
            name="minimum_tier",
            field=models.PositiveIntegerField(
                help_text="Minimum RelationshipTier.tier_number a side holding an open label of the required type must have reached."
            ),
        ),
    ]
