# Generated by Django 5.2.16 on 2026-08-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0152_ceremony_title_alter_ceremonytype_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ceremonytype",
            name="key",
            field=models.CharField(
                choices=[
                    ("funeral", "Funeral"),
                    ("blessing", "Blessing"),
                    ("sermon", "Sermon"),
                    ("seance", "Seance"),
                    ("wedding", "Wedding"),
                    ("conversion", "Conversion"),
                    ("coronation", "Coronation"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
