# Generated by Django 5.2.16 on 2026-09-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0153_delete_rivalry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="escalationcurve",
            name="spike_minimum_track_points",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Pair depth (scene + invested) a bonded side needs before a grief or peril spike fires.",
            ),
        ),
    ]
