# Generated by Django 5.2.16 on 2026-08-15 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("arxii", "0154_craftingserviceoffer_min_regard_and_more")]

    operations = [
        migrations.CreateModel(
            name="TradeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="proposed",
                        max_length=20,
                    ),
                ),
                ("initiator_confirmed", models.BooleanField(default=False)),
                ("counterparty_confirmed", models.BooleanField(default=False)),
                (
                    "initiator_coppers",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Coin the initiator has staged onto the table.",
                    ),
                ),
                (
                    "counterparty_coppers",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Coin the counterparty has staged onto the table.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the session reached COMPLETED or CANCELLED.",
                        null=True,
                    ),
                ),
                (
                    "counterparty_sheet",
                    models.ForeignKey(
                        help_text="The character invited to the trade.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_sessions_received",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "initiator_sheet",
                    models.ForeignKey(
                        help_text="The character who proposed the trade.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_sessions_initiated",
                        to="arxii.charactersheet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TradeItemStake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_stakes",
                        to="arxii.iteminstance",
                    ),
                ),
                (
                    "offered_by_sheet",
                    models.ForeignKey(
                        help_text="Must equal session.initiator_sheet or session.counterparty_sheet.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_stakes",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_stakes",
                        to="arxii.tradesession",
                    ),
                ),
            ],
            options={
                "ordering": ["staked_at"],
            },
        ),
        migrations.AddIndex(
            model_name="tradesession",
            index=models.Index(
                fields=["initiator_sheet", "status"],
                name="arxii_trade_initiat_addc6a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tradesession",
            index=models.Index(
                fields=["counterparty_sheet", "status"],
                name="arxii_trade_counter_ceee4e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tradeitemstake",
            index=models.Index(fields=["session"], name="arxii_trade_session_8c9008_idx"),
        ),
    ]
