# Generated by Django 5.2.16 on 2026-08-22 02:18

from django.db import migrations, models
import django.db.models.deletion

import core.natural_keys


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0162_traditioncodexgrant_is_perspective_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TavernGamblingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekly_loss_cap",
                    models.PositiveIntegerField(
                        default=500,
                        help_text="PLACEHOLDER - coppers a character may ante into tavern games in one IC week. Winnings do not offset it (#3292 decision 4).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tavern Gambling Config",
                "verbose_name_plural": "Tavern Gambling Config",
            },
        ),
        migrations.CreateModel(
            name="TavernGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "rules_blurb",
                    models.TextField(
                        blank=True,
                        help_text="Player-facing rules summary shown before opening a session.",
                    ),
                ),
                (
                    "min_ante",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Smallest ante an opener may set, in coppers.",
                    ),
                ),
                (
                    "max_ante",
                    models.PositiveIntegerField(
                        default=1000,
                        help_text="Largest ante an opener may set, in coppers.",
                    ),
                ),
                (
                    "resolution_kind",
                    models.CharField(
                        choices=[("highest_roll", "Highest Roll")],
                        default="highest_roll",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "ante",
                    models.PositiveIntegerField(
                        help_text="Fixed ante every seat pays to join, in coppers."
                    ),
                ),
                (
                    "pot",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Coppers currently escrowed at the table (sum of unrefunded antes).",
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "opened_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opened_tavern_game_sessions",
                        to="arxii.persona",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tavern_game_sessions",
                        to="arxii.place",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="arxii.taverngame",
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="GamblingLossLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_lost", models.PositiveIntegerField(default=0)),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gambling_loss_ledgers",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "game_week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gambling_loss_ledgers",
                        to="arxii.gameweek",
                    ),
                ),
            ],
            options={
                "ordering": ["-game_week"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character_sheet", "game_week"),
                        name="unique_gambling_loss_ledger_per_sheet_week",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GameSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ante_paid", models.PositiveIntegerField()),
                (
                    "roll_result",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("seated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tavern_game_seats",
                        to="arxii.persona",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="arxii.gamesession",
                    ),
                ),
            ],
            options={
                "ordering": ["seated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "persona"),
                        name="unique_seat_per_session_persona",
                    )
                ],
            },
        ),
    ]
