# Generated by Django 5.2.16 on 2026-08-22 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("arxii", "0163_interaction_attributed_companion")]

    operations = [
        migrations.CreateModel(
            name="JournalBequestGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["deceased_sheet_id", "id"],
            },
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="posthumous_journal_disposition",
            field=models.CharField(
                choices=[
                    ("reveal", "Reveal after death (default)"),
                    ("seal", "Seal forever"),
                ],
                default="reveal",
                help_text="Default fate of this character's private journal entries after death (#3287). REVEAL is the Arx I black-journal precedent; SEAL keeps them buried. A per-entry JournalEntry.posthumous_override can override this default.",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="posthumous_override",
            field=models.CharField(
                choices=[
                    ("inherit", "Inherit sheet default"),
                    ("reveal", "Reveal after death"),
                    ("seal", "Seal forever"),
                ],
                default="inherit",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="revealed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Stamped at estate settlement when this private entry's disposition is REVEAL.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="revealed_by_settlement",
            field=models.ForeignKey(
                blank=True,
                help_text="Which settlement revealed this entry — audit trail (#3287 spec Decision 2).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revealed_journal_entries",
                to="arxii.estatesettlement",
            ),
        ),
        migrations.AlterField(
            model_name="bequest",
            name="kind",
            field=models.CharField(
                choices=[
                    ("specific_item", "Specific Item"),
                    ("coin_amount", "Coin Amount"),
                    ("all_coin", "All Remaining Coin"),
                    ("building", "Building"),
                    ("business", "Business"),
                    ("residuary", "Residuary (everything else)"),
                    ("writings", "Writings (Private Journal Corpus)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["revealed_at"], name="arxii_journ_reveale_03ad58_idx"),
        ),
        migrations.AddField(
            model_name="journalbequestgrant",
            name="created_by_settlement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal_bequest_grants",
                to="arxii.estatesettlement",
            ),
        ),
        migrations.AddField(
            model_name="journalbequestgrant",
            name="deceased_sheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal_bequests_granted",
                to="arxii.charactersheet",
            ),
        ),
        migrations.AddField(
            model_name="journalbequestgrant",
            name="recipient_sheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal_bequests_received",
                to="arxii.charactersheet",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalbequestgrant",
            constraint=models.UniqueConstraint(
                fields=("recipient_sheet", "deceased_sheet"),
                name="unique_journal_bequest_grant",
            ),
        ),
    ]
