# Generated by Django 5.2.16 on 2026-08-22 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("arxii", "0163_interaction_attributed_companion")]

    operations = [
        migrations.AddField(
            model_name="organizationrank",
            name="can_moderate_board",
            field=models.BooleanField(
                default=False,
                help_text="Members at this rank can remove ANY notice from this organization's board (authors may always remove their own; staff always can) (#3286).",
            ),
        ),
        migrations.AddField(
            model_name="organizationrank",
            name="can_post_to_board",
            field=models.BooleanField(
                default=False,
                help_text="Members at this rank can pin new notices to this organization's board (#3286).",
            ),
        ),
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Display name for this board.", max_length=100),
                ),
                (
                    "max_active_posts",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="Newest-first display cap. Older posts fall off the display but are retained in the DB (no auto-expiry at MVP).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="ORG board anchor: the organization this board belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boards",
                        to="arxii.organization",
                    ),
                ),
                (
                    "room_profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="LOCATION board anchor: the room this board physically stands in.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boards",
                        to="arxii.roomprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BoardPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author_persona",
                    models.ForeignKey(
                        help_text="The face that signed this notice (masked personas post under the mask).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_posts",
                        to="arxii.persona",
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="arxii.board",
                    ),
                ),
                (
                    "removed_by_persona",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who took this post down (author, org moderator, or staff persona).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="board_posts_removed",
                        to="arxii.persona",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="board",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("room_profile__isnull", False),
                    ("organization__isnull", False),
                    _connector="XOR",
                ),
                name="board_exactly_one_anchor",
            ),
        ),
        migrations.AddConstraint(
            model_name="board",
            constraint=models.UniqueConstraint(
                condition=models.Q(("room_profile__isnull", False)),
                fields=("room_profile",),
                name="unique_board_per_room",
            ),
        ),
        migrations.AddConstraint(
            model_name="board",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organization__isnull", False)),
                fields=("organization",),
                name="unique_board_per_org",
            ),
        ),
        migrations.AddIndex(
            model_name="boardpost",
            index=models.Index(
                fields=["board", "-created_at"], name="arxii_board_board_i_25a5a4_idx"
            ),
        ),
    ]
