# Generated by Django 5.2.16 on 2026-09-29 03:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0164_farmland_is_a_farm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holdingkind",
            name="stream_kind",
            field=models.CharField(
                choices=[
                    ("domain_tax", "Domain Tax"),
                    ("crime_kickup", "Crime Kick-up"),
                    ("territory", "Territory"),
                    ("levy", "Levy"),
                ],
                help_text="currency.IncomeStreamKind value the materialized stream uses.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orgincomestream",
            name="kind",
            field=models.CharField(
                choices=[
                    ("domain_tax", "Domain Tax"),
                    ("crime_kickup", "Crime Kick-up"),
                    ("territory", "Territory"),
                    ("levy", "Levy"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Levy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("tax", "Tax"), ("protection", "Protection")],
                        max_length=12,
                    ),
                ),
                (
                    "rate_pct",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Percent of a business's gross taken each cycle. 0 switches the levy off.",
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        help_text="The rung this levy applies at; every business under it pays.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levies",
                        to="arxii.area",
                    ),
                ),
                (
                    "income_stream",
                    models.OneToOneField(
                        blank=True,
                        help_text="The LEVY stream the take pools in, on the rung's current controller.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="levy",
                        to="arxii.orgincomestream",
                    ),
                ),
                (
                    "room_profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="A crew's corner (PROTECTION only): the business on this room pays.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levies",
                        to="arxii.roomprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Levy",
                "verbose_name_plural": "Levies",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("area__isnull", False), ("room_profile__isnull", True)),
                            models.Q(("area__isnull", True), ("room_profile__isnull", False)),
                            _connector="OR",
                        ),
                        name="societies_levy_exactly_one_site",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("area__isnull", False)),
                        fields=("area", "kind"),
                        name="societies_levy_one_per_area_kind",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("room_profile__isnull", False)),
                        fields=("room_profile", "kind"),
                        name="societies_levy_one_per_room_kind",
                    ),
                ],
            },
        ),
    ]
