# Generated by Django 5.2.16 on 2026-09-29 03:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0165_levies"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainholding",
            name="owner_org",
            field=models.ForeignKey(
                blank=True,
                help_text="The organization this holding pays; blank = the domain's owner.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_holdings",
                to="arxii.organization",
            ),
        ),
        migrations.AddField(
            model_name="origintemplateslotchoice",
            name="family_standing",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="How a NEW family the player names starts out, 0-100 (50 is neutral): a noble claim's seat prosperity, or the standing of a commoner family's businesses (#4060). Blank means this answer says nothing about it.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
    ]
