# Generated by Django 5.2.16 on 2026-08-26 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("arxii", "0172_area_exile_destination_justicecase_sentence_ends_at_and_more")]

    operations = [
        migrations.AlterField(
            model_name="affectionshift",
            name="boon",
            field=models.OneToOneField(
                blank=True,
                help_text="The granted Boon this shift charges (#2540) — per-Boon dedup, stacking. CASCADE (not SET_NULL): affection_shift_has_provenance requires effect-or-boon non-null, so a boon-keyed row's provenance dies with the boon.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="affection_shift",
                to="arxii.boon",
            ),
        ),
    ]
