# Generated by Django 5.2.17 on 2026-10-01 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0174_knownultimate_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alternateself",
            name="techniques",
            field=models.ManyToManyField(
                blank=True,
                help_text="Techniques granted on assuming this alternate self. Never an ultimate (#4098) — past-life bond ultimates are out of scope; an ultimate is reachable only by discovering it at Audere/Audere Majora.",
                limit_choices_to={"is_ultimate": False},
                related_name="alternate_self_grants",
                to="arxii.technique",
            ),
        ),
        migrations.AlterField(
            model_name="techniquegrant",
            name="technique",
            field=models.ForeignKey(
                help_text="The technique this grant teaches. Never an ultimate (#4098) — an ultimate is reachable only by discovering it at Audere/Audere Majora.",
                limit_choices_to={"is_ultimate": False},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grants",
                to="arxii.technique",
            ),
        ),
    ]
