# Generated by Django 5.2.17 on 2026-10-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0177_technique_personalization_fields"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="charactertechnique",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("custom_name__contains", "—"), _negated=True),
                    models.Q(("custom_name__contains", "–"), _negated=True),
                ),
                name="character_technique_custom_name_no_dash",
            ),
        ),
        migrations.AddConstraint(
            model_name="restriction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("creation_point_cost__isnull", True),
                    ("kind", "price"),
                    _connector="OR",
                ),
                name="restriction_creation_cost_price_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="signaturemotifbonus",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("creation_point_cost__isnull", True),
                    ("min_crossing_level__lte", 2),
                    _connector="OR",
                ),
                name="signature_bonus_creation_cost_below_crossing",
            ),
        ),
        migrations.AddConstraint(
            model_name="techniquevariant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("creation_point_cost__isnull", True),
                    models.Q(("unlock_thread_level__gte", 1), ("unlock_thread_level__lte", 2)),
                    _connector="OR",
                ),
                name="technique_variant_creation_cost_early_level",
            ),
        ),
    ]
