# Generated by Django 5.2.16 on 2026-08-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("arxii", "0178_cast_power_scale_dispel_treatment")]

    operations = [
        migrations.AlterField(
            model_name="combatopponent",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("defeated", "Defeated"),
                    ("fled", "Fled"),
                    ("removed", "Removed"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="engagementlock",
            name="break_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("defeat", "Opponent Defeated"),
                    ("flee", "Locked PC Fled"),
                    ("disengage", "Deliberate Disengage"),
                    ("interference", "Interference Defeated"),
                    ("expired", "Expired"),
                    ("removed", "Opponent Removed"),
                ],
                max_length=15,
                null=True,
            ),
        ),
    ]
