# Generated by Django 5.2.16 on 2026-08-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0183_alter_triggerdefinition_event_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemtemplate",
            name="requires_attunement",
            field=models.BooleanField(
                default=False,
                help_text="When true, this template's mechanics are inert for an unattuned holder (#3430). Writers: the touchstone ritual (attune_touchstone, resonance-tied items only) and staff admin edits on ItemInstance.attuned_to_character_sheet — unchanged by this flag. Enforcement: collect_check_modifiers' EQUIPMENT block (world.checks.services) only emits this template's ItemCheckModifier contributions for an instance both equipped by and attuned to the acting character; use_item (world.items.services.usage) refuses on-use dispatch the same way. Stacking: with multiple equipped instances of a flagged template, the modifier applies once iff at least one is attuned to the holder — attunement never multiplies a bonus.",
            ),
        ),
    ]
