# Generated by Django 5.2.16 on 2026-08-28 23:36

from django.db import migrations, models

# Ramp matches world.gm.factories.seed_default_gm_level_caps's defaults (#3426);
# staff-tunable in admin thereafter. AddField's default=0 alone would leave
# every pre-existing row (any already-seeded dev/prod database) stuck at 0 for
# every level, not just STARTING -- get_or_create in the seed helper never
# backfills an existing row, so this RunPython is the only path that reaches
# already-seeded GMLevelCap rows. Config data, not authored content -- no
# ADR-0237 disposition applies.
_STORY_NPC_CAP_RAMP = {
    "starting": 0,
    "junior": 2,
    "gm": 4,
    "experienced": 8,
    "senior": 12,
}


def _seed_max_story_npcs(apps, schema_editor):
    GMLevelCap = apps.get_model("arxii", "GMLevelCap")
    for level, cap in _STORY_NPC_CAP_RAMP.items():
        GMLevelCap.objects.filter(level=level).update(max_story_npcs=cap)


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0183_alter_triggerdefinition_event_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="gmlevelcap",
            name="max_story_npcs",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Concurrent Story NPCs (active NPC-shelf tenures) a GM at this level may hold (#3426).",
            ),
        ),
        migrations.RunPython(_seed_max_story_npcs, _noop),
    ]
