# Generated by Django 5.2.17 on 2026-10-02 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0184_gmpromptnarration_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterCrossingText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vision_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Shown ONLY to the crossing player. Blank = the patron or tier vision.",
                    ),
                ),
                (
                    "manifestation_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The room line for this crossing. Blank = the patron or tier line.",
                    ),
                ),
                (
                    "deed_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Public deed name for this crossing. Blank = the tier's deed title.",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prepared_crossing_texts",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "crossing",
                    models.OneToOneField(
                        blank=True,
                        help_text="Set when a crossing used this text; a used text never fires again.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prepared_text",
                        to="arxii.auderemajoracrossing",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who wrote it (staff or the character's table GM). Never shown to players.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prepared Crossing Text",
                "verbose_name_plural": "Prepared Crossing Texts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CharacterSurgeText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "surge_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Room line when this character surges. {name} = primary-persona name.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character_sheet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prepared_surge_text",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prepared Surge Text",
                "verbose_name_plural": "Prepared Surge Texts",
            },
        ),
    ]
