# Generated by Django 5.2.16 on 2026-08-29 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0191_alter_npcserviceoffer_kind_cluerevealofferdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="legendentry",
            name="earned_at_level",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=0,
                help_text="Station this deed was won at: min(earner level, threat level). 0 = no station (minted outside a perilous stakes contract); such a deed still counts for fame and spread but qualifies no advancement.",
            ),
        ),
        migrations.AddField(
            model_name="legendrequirement",
            name="counts_from_level_offset",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="How many levels below this unlock's target a deed may have been won at and still qualify. 1 = the step you're taking plus the one below it. Deeds with station 0 (won outside a perilous stakes contract) never qualify.",
            ),
        ),
        migrations.CreateModel(
            name="LegendContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "success_level",
                    models.SmallIntegerField(
                        help_text="The check's success_level (-10 to +10). SERVER-ONLY — never serialize."
                    ),
                ),
                (
                    "was_crucial",
                    models.BooleanField(
                        default=False,
                        help_text="Derived at write time from the served stake's severity, never authored per row. Crucial contributions carry the standout pass.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activation",
                    models.ForeignKey(
                        help_text="The staked unit being settled; the contribution dies with it.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legend_contributions",
                        to="arxii.stakecontractactivation",
                    ),
                ),
                (
                    "character_sheet",
                    models.ForeignKey(
                        help_text="Who acted.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legend_contributions",
                        to="arxii.charactersheet",
                    ),
                ),
                (
                    "check_type",
                    models.ForeignKey(
                        help_text="What kind of thing they did.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legend_contributions",
                        to="arxii.checktype",
                    ),
                ),
                (
                    "stake",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which objective this served; null when the act served the beat at large.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legend_contributions",
                        to="arxii.stake",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legend Contribution",
                "verbose_name_plural": "Legend Contributions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["activation", "character_sheet"],
                        name="legendcontrib_activation_idx",
                    )
                ],
            },
        ),
    ]
