# Generated by Django 5.2.17 on 2026-10-03 07:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

import core.natural_keys
import evennia_extensions.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0194_membership_favor_and_goals_untiered"),
    ]

    operations = [
        migrations.CreateModel(
            name="LifeBeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "written_on",
                    models.DateField(
                        blank=True, help_text="Date the prose was written.", null=True
                    ),
                ),
                (
                    "reviewed_on",
                    models.DateField(
                        blank=True, help_text="Date the prose was reviewed.", null=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The beat's name, as the player reads it.",
                        max_length=100,
                    ),
                ),
                (
                    "life_stage",
                    models.CharField(
                        choices=[
                            ("childhood", "Childhood"),
                            ("youth", "Youth"),
                            ("adulthood", "Before the Glimpse"),
                            ("at_the_glimpse", "At the Glimpse"),
                            ("since_the_glimpse", "Since the Glimpse"),
                        ],
                        help_text="Which stage of a life this beat is pooled under.",
                        max_length=20,
                    ),
                ),
                (
                    "prompt",
                    models.TextField(help_text="The prompt shown above the beat's answers."),
                ),
                (
                    "selection",
                    models.CharField(
                        choices=[("one_of", "One of"), ("any", "Any that apply")],
                        default="one_of",
                        help_text="One answer (drawn across) or any that apply (drawn down).",
                        max_length=10,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Inactive beats are offered nowhere."
                    ),
                ),
            ],
            options={
                "verbose_name": "Life beat",
                "verbose_name_plural": "Life beats",
                "ordering": ["life_stage", "sort_order", "id"],
            },
            bases=(
                evennia_extensions.mixins.CachedPropertiesMixin,
                core.natural_keys.NaturalKeyMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="LifeBeatExclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Why this Beginning never meets this beat.",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "verbose_name": "Life beat exclusion",
                "verbose_name_plural": "Life beat exclusions",
            },
        ),
        migrations.AlterModelOptions(
            name="characteroriginslot",
            options={
                "ordering": [
                    "slot__sort_order",
                    "beat__life_stage",
                    "beat__sort_order",
                ],
                "verbose_name": "Character Upbringing Answer",
                "verbose_name_plural": "Character Upbringing Answers",
            },
        ),
        migrations.RemoveConstraint(
            model_name="distinctionoffer",
            name="distinctionoffer_at_most_one_opener",
        ),
        migrations.AlterUniqueTogether(
            name="characteroriginslot",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="beginnings",
            name="beat_mode",
            field=models.CharField(
                choices=[
                    ("pool", "A pool to add from"),
                    ("one_kept", "One beat kept, the rest unknown"),
                ],
                db_default="pool",
                default="pool",
                help_text="A pool the player adds beats from (the default), or one kept beat with every other beat standing unknown (the Sleeper).",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="characteroriginslot",
            name="unknown",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="A beat the character does not remember (#4124); the sheet shows it blank.",
            ),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="maturation_floor",
            field=models.PositiveSmallIntegerField(
                db_default=0,
                default=0,
                help_text="Matured years at creation; milestones at or below it are never earned. 0 means the character predates the rule and keeps its banked points.",
                validators=[django.core.validators.MaxValueValidator(10000)],
            ),
        ),
        migrations.AddField(
            model_name="secret",
            name="resolves_beat",
            field=models.ForeignKey(
                blank=True,
                help_text="The subject's unknown beat this secret resolves once they learn it (#4124).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolving_secrets",
                to="arxii.characteroriginslot",
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="cg_point_cost",
            field=models.IntegerField(
                db_default=0,
                default=0,
                help_text="CG point cost of being this species, added to the purse beside its gift grants; 0 for most. Prices eternal youth.",
            ),
        ),
        migrations.AlterField(
            model_name="characteroriginslot",
            name="slot",
            field=models.ForeignKey(
                blank=True,
                help_text="The catalog slot this answer fills; null for a beat row (#4124).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="character_rows",
                to="arxii.origintemplateslot",
            ),
        ),
        migrations.AlterField(
            model_name="distinctionoffer",
            name="chapter",
            field=models.CharField(
                choices=[
                    ("tradition_step", "Gift, tradition step"),
                    ("glimpse", "Gift, the Glimpse"),
                    ("lineage", "Lineage"),
                    ("appearance", "Appearance"),
                    ("actors_sheet", "The actor's sheet"),
                    ("enemy", "Who wants you to fail"),
                    ("backgrounds", "Backgrounds, a beat"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="origintemplateslot",
            name="life_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("childhood", "Childhood"),
                    ("youth", "Youth"),
                    ("adulthood", "Before the Glimpse"),
                    ("at_the_glimpse", "At the Glimpse"),
                    ("since_the_glimpse", "Since the Glimpse"),
                ],
                default="",
                help_text="When the tie was formed; a tag (#3660).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lifebeat",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who reviewed this row's prose, if anyone. Distinct from writing it.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="arxii.contentcontributor",
            ),
        ),
        migrations.AddField(
            model_name="lifebeat",
            name="written_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who wrote this row's prose. Null means it is still a placeholder.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="arxii.contentcontributor",
            ),
        ),
        migrations.AddField(
            model_name="characteroriginslot",
            name="beat",
            field=models.ForeignKey(
                blank=True,
                help_text="The beat this row takes; null for an Upbringing prompt's answer (#4124).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="character_rows",
                to="arxii.lifebeat",
            ),
        ),
        migrations.AddField(
            model_name="distinctionoffer",
            name="beat",
            field=models.ForeignKey(
                blank=True,
                help_text="Backgrounds only: the beat this offer is an answer on (#4124).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distinction_offers",
                to="arxii.lifebeat",
            ),
        ),
        migrations.AddConstraint(
            model_name="characteroriginslot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("slot__isnull", False)),
                fields=("sheet", "slot"),
                name="characteroriginslot_sheet_slot_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="characteroriginslot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("beat__isnull", False)),
                fields=("sheet", "beat"),
                name="characteroriginslot_sheet_beat_unique",
            ),
        ),
        migrations.AddField(
            model_name="lifebeatexclusion",
            name="beat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exclusions",
                to="arxii.lifebeat",
            ),
        ),
        migrations.AddField(
            model_name="lifebeatexclusion",
            name="beginning",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beat_exclusions",
                to="arxii.beginnings",
            ),
        ),
        migrations.AddConstraint(
            model_name="lifebeat",
            constraint=models.UniqueConstraint(
                fields=("life_stage", "name"), name="lifebeat_stage_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="lifebeatexclusion",
            constraint=models.UniqueConstraint(
                fields=("beat", "beginning"), name="lifebeat_exclusion_unique"
            ),
        ),
    ]
