# Generated by Django 5.2.16 on 2026-08-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0195_boss_beat_surge_triggers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breakbarconfig",
            name="intensity_bonus",
            field=models.PositiveIntegerField(
                default=2,
                help_text="Flat intensity bonus to PC techniques during the window. Power-ledger term (feeds power_intensity_bonus), NOT the engagement's intensity_modifier.",
            ),
        ),
        migrations.AlterField(
            model_name="combatopponent",
            name="vulnerability_intensity_bonus",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Intensity bonus during vulnerability window; from BreakBarConfig. Power-ledger term (feeds power_intensity_bonus), NOT the engagement's intensity_modifier.",
            ),
        ),
    ]
