# Generated by Django 5.2.16 on 2026-08-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0196_alter_bossphase_vulnerability_intensity_bonus_and_more")
    ]

    operations = [
        migrations.CreateModel(
            name="LegendLevelCalibration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        help_text="The character level this row prices. Level 0 is meaningful: a deed settled at station 0 was won outside a perilous stakes contract.",
                        unique=True,
                    ),
                ),
                (
                    "honor_hares_required",
                    models.PositiveSmallIntegerField(
                        help_text="Golden Hares a character of this level surrenders to honor a deed."
                    ),
                ),
                (
                    "honor_value_added",
                    models.PositiveIntegerField(
                        help_text="Legend a voice at this level adds to a deed, before the event ceiling clamps it."
                    ),
                ),
                (
                    "deed_title_threshold",
                    models.PositiveIntegerField(
                        help_text="base_value a deed at this station must reach before it grants its earner a title."
                    ),
                ),
            ],
            options={
                "verbose_name": "legend level calibration",
                "verbose_name_plural": "legend level calibrations",
                "ordering": ["level"],
            },
        ),
    ]
