# Generated by Django 5.2.16 on 2026-08-31 07:19

from django.db import migrations, models
import django.utils.timezone


def _backfill_published_at(apps, schema_editor):
    """Stamp every pre-existing RoomProfile as published (#3477).

    Forward-only: every room that already exists is a live room today —
    "unpublished" is a new concept that only applies going forward, to
    rooms the staff world-builder canvas digs. AddField's own ``default``
    already backfills a single evaluated timestamp onto existing rows at
    the schema level; this RunPython is the explicit, documented backfill
    the data-migration convention (ADR-0237) calls for, not a fix for a gap.
    """
    RoomProfile = apps.get_model("arxii", "RoomProfile")
    RoomProfile.objects.filter(published_at__isnull=True).update(
        published_at=django.utils.timezone.now()
    )


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0198_areabuildgrant"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomprofile",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Stamped by staff_publish_room when this room is live in the world (#3477); defaults to now() so an ordinary room is live the moment it exists. Null = unpublished/WIP — not enterable and its exits hidden except to a story-runner (GM/Staff). world.areas.grid_services.create_room (the staff world-builder canvas dig) is the one path that overrides this default to None: a canvas-dug room is born unpublished until staff reviews it and calls staff_publish_room — re-publishing just refreshes the stamp (idempotent; no separate 'done' flag).",
                null=True,
            ),
        ),
        migrations.RunPython(_backfill_published_at, migrations.RunPython.noop),
    ]
