# Generated by Django 5.2.16 on 2026-08-31 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0199_roomprofile_published_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomprofile",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Stamped by staff_publish_room when this room is live in the world (#3477); defaults to now() so an ordinary room is live the moment it exists. Null = unpublished/WIP — not enterable and its exits hidden except to a story-runner (GM/Staff). Two paths override this default explicitly, in opposite directions: world.areas.grid_services.create_room's origin=AUTHORED branch (the staff world-builder canvas dig) sets it to None — a canvas-dug room is born unpublished until staff reviews it and calls staff_publish_room, which just refreshes the stamp on a re-call (idempotent; no separate 'done' flag) — while core_management.grid_import._upsert_single_room's new-room branch stamps now() explicitly: a grid_import is a restore of previously-live world content (the content repo is downstream/bootstrap-only, ADR-0238), not a canvas dig awaiting review, so it is born published.",
                null=True,
            ),
        ),
    ]
