# Generated by Django 5.2.16 on 2026-09-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0204_alter_legendlevelcalibration_options_legendhonor"),
    ]

    operations = [
        migrations.AddField(
            model_name="conditioninstance",
            name="soulfray_consented",
            field=models.BooleanField(
                default=False,
                help_text="The caster consented, at cast time, to keep this condition's reactive cost and upkeep firing past zero anima at the price of Soulfray (#3573). Read by _try_spend_reactive and drain_reactive_upkeep; never changes after creation.",
            ),
        ),
    ]
