# Generated by Django 5.2.17 on 2026-10-08 16:43

from django.db import migrations, models
import django.db.models.deletion

import core.natural_keys


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0208_makeover_consent_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacetAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "written_on",
                    models.DateField(
                        blank=True, help_text="Date the prose was written.", null=True
                    ),
                ),
                (
                    "reviewed_on",
                    models.DateField(
                        blank=True, help_text="Date the prose was reviewed.", null=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The other spelling (e.g. 'Scythes'); unique across aliases and facets.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "facet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="arxii.facet",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who reviewed this row's prose, if anyone. Distinct from writing it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.contentcontributor",
                    ),
                ),
                (
                    "written_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who wrote this row's prose. Null means it is still a placeholder.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.contentcontributor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facet alias",
                "verbose_name_plural": "Facet aliases",
                "ordering": ["name"],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
    ]
