# Generated by Django 5.2.17 on 2026-10-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("arxii", "0210_being_tarot_orientation_and_relationship_sides")]

    operations = [
        migrations.AddField(
            model_name="successionlaw",
            name="gender_tiebreak",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No preference"),
                    ("female", "Daughters first on a tie"),
                    ("male", "Sons first on a tie"),
                ],
                db_default="",
                default="",
                help_text="Who goes first when the ordering rule ties (#4201): equal age under Eldest, equal rating under Most powerful Gifted. Umbros: daughters first.",
                max_length=10,
            ),
        ),
    ]
