# Generated by Django 5.2.16 on 2026-09-03 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0212_alter_stakeresolution_machine_match_lifecycle_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="beat",
            name="required_npc_sheet",
            field=models.ForeignKey(
                blank=True,
                help_text="For NPC_REGARD_AT_LEAST predicates: the NPC whose regard for the character is read (NpcRegard from the NPC's primary persona toward the character's primary persona, the row the stake npc_regard_delta and the SHIFT_NPC_REGARD pool effect write). Not the functionary standing (NPCStanding.affection) and not the relationships affection track.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="arxii.charactersheet",
            ),
        ),
        migrations.AlterField(
            model_name="beat",
            name="predicate_type",
            field=models.CharField(
                choices=[
                    ("gm_marked", "GM-marked"),
                    ("character_level_at_least", "Character level at least"),
                    ("achievement_held", "Achievement held"),
                    ("condition_held", "Condition held"),
                    ("codex_entry_unlocked", "Codex entry unlocked"),
                    ("story_at_milestone", "Referenced story at milestone"),
                    ("aggregate_threshold", "Aggregate threshold reached"),
                    ("outcome_tier", "Outcome tier (machine-graded)"),
                    ("faction_standing_at_least", "Faction standing at least"),
                    ("npc_regard_at_least", "NPC regard at least"),
                ],
                default="outcome_tier",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="beat",
            name="required_standing",
            field=models.IntegerField(
                blank=True,
                help_text="For FACTION_STANDING_AT_LEAST and NPC_REGARD_AT_LEAST predicates: the minimum raw value (-1000..1000).",
                null=True,
            ),
        ),
    ]
