# Generated by Django 5.2.16 on 2026-09-03 03:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("arxii", "0212_alter_stakeresolution_machine_match_lifecycle_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeatStagedBattle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Battle name; blank uses the first line of the beat's internal description.",
                        max_length=100,
                    ),
                ),
                (
                    "party_side_role",
                    models.CharField(
                        choices=[("attacker", "Attacker"), ("defender", "Defender")],
                        default="defender",
                        help_text="Which side the running scene's party is enlisted on.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "beat",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staged_battle",
                        to="arxii.beat",
                    ),
                ),
                (
                    "blueprint",
                    models.ForeignKey(
                        help_text="The map this beat's battle is cloned from at run time.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staged_on_beats",
                        to="arxii.battlemapblueprint",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional region the battle is set in (Battle.region).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="arxii.area",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beat staged battle",
            },
        ),
        migrations.CreateModel(
            name="BeatStagedBattleUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side_role",
                    models.CharField(
                        choices=[("attacker", "Attacker"), ("defender", "Defender")],
                        default="attacker",
                        max_length=20,
                    ),
                ),
                (
                    "place_name",
                    models.CharField(
                        blank=True,
                        help_text="Blueprint place name to spawn at; blank spawns unplaced.",
                        max_length=100,
                    ),
                ),
                (
                    "count",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "staged_battle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_lines",
                        to="arxii.beatstagedbattle",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staged_on_beats",
                        to="arxii.battleunittemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["staged_battle", "order", "pk"],
            },
        ),
    ]
