# Generated by Django 5.2.16 on 2026-09-03 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("arxii", "0215_remove_situationchallengelink_depends_on_and_more")]

    operations = [
        migrations.AddField(
            model_name="gmlevelcap",
            name="allow_item_rewards",
            field=models.BooleanField(
                default=False,
                help_text="May author ITEM stake reward lines (minting an item is world state) (#3566).",
            ),
        ),
        migrations.AddField(
            model_name="stakerewardline",
            name="clue",
            field=models.ForeignKey(
                blank=True,
                help_text="Required when sink=CLUE; must be null otherwise.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="arxii.clue",
            ),
        ),
        migrations.AddField(
            model_name="stakerewardline",
            name="codex_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="Required when sink=CODEX; must be null otherwise.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="arxii.codexentry",
            ),
        ),
        migrations.AddField(
            model_name="stakerewardline",
            name="item_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Required when sink=ITEM; must be null otherwise.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="arxii.itemtemplate",
            ),
        ),
        migrations.AlterField(
            model_name="stakerewardline",
            name="sink",
            field=models.CharField(
                choices=[
                    ("money", "Money"),
                    ("resonance", "Resonance"),
                    ("item", "Item"),
                    ("clue", "Clue"),
                    ("codex", "Codex Entry"),
                ],
                max_length=12,
            ),
        ),
    ]
