# Generated by Django 5.2.16 on 2026-09-04 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("arxii", "0223_remove_playerdata_max_file_size_and_more")]

    operations = [
        migrations.RemoveConstraint(
            model_name="characterrelationship",
            name="unique_relationship_pair",
        ),
        migrations.RemoveConstraint(
            model_name="dramaticsurgerecord",
            name="unique_surge_without_subject",
        ),
        migrations.RemoveConstraint(
            model_name="dramaticsurgerecord",
            name="surge_subject_sheet_xor_opponent",
        ),
        migrations.AddField(
            model_name="characterrelationship",
            name="target_companion",
            field=models.ForeignKey(
                blank=True,
                help_text="The bonded companion this relationship is about (#3575); null when target is set. Only the companion's owner may hold such a row.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationships_as_companion_target",
                to="arxii.companion",
            ),
        ),
        migrations.AddField(
            model_name="dramaticsurgerecord",
            name="subject_companion",
            field=models.ForeignKey(
                blank=True,
                help_text="The bonded companion whose fall produced this ALLY_FALLEN surge (#3575); null for every other subject kind. CASCADE for the same reason as subject_opponent: nulling would drop the row into the subject-less slice of the unique index. A Companion row is never hard-deleted, so nothing is lost.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="arxii.companion",
            ),
        ),
        migrations.AlterField(
            model_name="characterrelationship",
            name="target",
            field=models.ForeignKey(
                blank=True,
                help_text="The character this relationship is about; null when target_companion is set (#3575). Exactly one of target / target_companion is set.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationships_as_target",
                to="arxii.charactersheet",
            ),
        ),
        migrations.AddConstraint(
            model_name="characterrelationship",
            constraint=models.UniqueConstraint(
                condition=models.Q(("target__isnull", False)),
                fields=("source", "target"),
                name="unique_relationship_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="characterrelationship",
            constraint=models.UniqueConstraint(
                condition=models.Q(("target_companion__isnull", False)),
                fields=("source", "target_companion"),
                name="unique_relationship_companion_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="characterrelationship",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("target__isnull", False), ("target_companion__isnull", True)),
                    models.Q(("target__isnull", True), ("target_companion__isnull", False)),
                    _connector="OR",
                ),
                name="relationship_target_xor_companion",
            ),
        ),
        migrations.AddConstraint(
            model_name="dramaticsurgerecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("subject_companion__isnull", True),
                    ("subject_opponent__isnull", True),
                    ("subject_sheet__isnull", True),
                ),
                fields=("encounter", "participant", "trigger_kind"),
                name="unique_surge_without_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="dramaticsurgerecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subject_companion__isnull", False)),
                fields=(
                    "encounter",
                    "participant",
                    "trigger_kind",
                    "subject_companion",
                ),
                name="unique_surge_companion_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="dramaticsurgerecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("subject_sheet__isnull", False),
                        ("subject_opponent__isnull", False),
                        _negated=True,
                    ),
                    models.Q(
                        ("subject_sheet__isnull", False),
                        ("subject_companion__isnull", False),
                        _negated=True,
                    ),
                    models.Q(
                        ("subject_opponent__isnull", False),
                        ("subject_companion__isnull", False),
                        _negated=True,
                    ),
                ),
                name="surge_subject_sheet_xor_opponent",
            ),
        ),
    ]
