# Generated by Django 5.2.4 on 2026-02-13 16:12

from django.db import migrations, models
import django.db.models.deletion

import core.natural_keys


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("character_creation", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterClueKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("found_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Character Clue Knowledge",
                "verbose_name_plural": "Character Clue Knowledge",
            },
        ),
        migrations.CreateModel(
            name="CharacterCodexKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("uncovered", "Uncovered"), ("known", "Known")],
                        default="uncovered",
                        max_length=20,
                    ),
                ),
                (
                    "learning_progress",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Accumulated progress toward entry.learn_threshold.",
                    ),
                ),
                (
                    "learned_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this entry was fully learned.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Character Codex Knowledge",
                "verbose_name_plural": "Character Codex Knowledge",
            },
        ),
        migrations.CreateModel(
            name="CodexCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of this category.", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what lore this category contains.",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, help_text="Order for display in lists."),
                ),
            ],
            options={
                "verbose_name": "Codex Category",
                "verbose_name_plural": "Codex Categories",
                "ordering": ["display_order", "name"],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CodexClue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the clue (e.g., 'Torn Journal Page').",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="What the player sees when they find this clue."),
                ),
                (
                    "research_value",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Research progress granted when this clue is found.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Codex Clue",
                "verbose_name_plural": "Codex Clues",
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CodexEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Title of this entry.", max_length=200),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="Short summary for tooltips/modals (1-2 sentences).",
                        max_length=300,
                    ),
                ),
                (
                    "lore_content",
                    models.TextField(
                        blank=True,
                        help_text="In-character world flavor/lore content.",
                        null=True,
                    ),
                ),
                (
                    "mechanics_content",
                    models.TextField(
                        blank=True,
                        help_text="Out-of-character mechanical explanation.",
                        null=True,
                    ),
                ),
                (
                    "share_cost",
                    models.PositiveIntegerField(
                        default=5, help_text="AP cost for teacher to offer this entry."
                    ),
                ),
                (
                    "learn_cost",
                    models.PositiveIntegerField(
                        default=5, help_text="AP cost for learner to accept an offer."
                    ),
                ),
                (
                    "learn_difficulty",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Base difficulty for learning progress checks.",
                    ),
                ),
                (
                    "learn_threshold",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Total progress needed to complete learning.",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for display within subject."
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="If True, visible to everyone including logged-out visitors. If False, only visible to characters who have learned it.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Codex Entry",
                "verbose_name_plural": "Codex Entries",
                "ordering": ["display_order", "name"],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CodexSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of this subject.", max_length=100),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this subject."),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for display within parent/category."
                    ),
                ),
            ],
            options={
                "verbose_name": "Codex Subject",
                "verbose_name_plural": "Codex Subjects",
                "ordering": ["display_order", "name"],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CodexTeachingOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visibility_mode",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("characters", "Specific Characters"),
                            ("groups", "Consent Groups"),
                        ],
                        default="private",
                        help_text="Who can see this content.",
                        max_length=20,
                    ),
                ),
                (
                    "pitch",
                    models.TextField(
                        help_text="Player-written description of what they're offering to teach."
                    ),
                ),
                (
                    "gold_cost",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Optional gold payment required from learner.",
                    ),
                ),
                (
                    "banked_ap",
                    models.PositiveIntegerField(help_text="AP committed from teacher's pool."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Codex Teaching Offer",
                "verbose_name_plural": "Codex Teaching Offers",
            },
        ),
        migrations.CreateModel(
            name="DistinctionCodexGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distinction Codex Grant",
                "verbose_name_plural": "Distinction Codex Grants",
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PathCodexGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Path Codex Grant",
                "verbose_name_plural": "Path Codex Grants",
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BeginningsCodexGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "beginnings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codex_grants",
                        to="character_creation.beginnings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beginnings Codex Grant",
                "verbose_name_plural": "Beginnings Codex Grants",
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
    ]
