# Generated by Django 5.2.14 on 2026-07-03 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        ("codex", "0002_initial"),
        ("consent", "0002_initial"),
        ("distinctions", "0001_initial"),
        ("mechanics", "0001_initial"),
        ("roster", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="codexentry",
            name="modifier_target",
            field=models.OneToOneField(
                blank=True,
                help_text="Link to a modifier target this entry documents (for resonances, stats, etc.).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="codex_entry",
                to="mechanics.modifiertarget",
            ),
        ),
        migrations.AddField(
            model_name="codexentry",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True,
                help_text="Entries required before this can be learned.",
                related_name="unlocks",
                to="codex.codexentry",
            ),
        ),
        migrations.AddField(
            model_name="charactercodexknowledge",
            name="entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_knowledge",
                to="codex.codexentry",
            ),
        ),
        migrations.AddField(
            model_name="beginningscodexgrant",
            name="entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beginnings_grants",
                to="codex.codexentry",
            ),
        ),
        migrations.AddField(
            model_name="codexsubject",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="codex.codexcategory",
            ),
        ),
        migrations.AddField(
            model_name="codexsubject",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent subject for nesting. Leave blank for top-level.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="codex.codexsubject",
            ),
        ),
        migrations.AddField(
            model_name="codexentry",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="codex.codexsubject",
            ),
        ),
        migrations.AddField(
            model_name="codexteachingoffer",
            name="entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaching_offers",
                to="codex.codexentry",
            ),
        ),
        migrations.AddField(
            model_name="codexteachingoffer",
            name="excluded_tenures",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tenures explicitly excluded even if otherwise visible.",
                related_name="%(class)s_excluded",
                to="roster.rostertenure",
            ),
        ),
        migrations.AddField(
            model_name="codexteachingoffer",
            name="teacher",
            field=models.ForeignKey(
                help_text="Tenure (player-character instance) offering to teach.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="codex_teaching_offers",
                to="roster.rostertenure",
            ),
        ),
        migrations.AddField(
            model_name="codexteachingoffer",
            name="visible_to_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Consent groups who can see this (if mode is 'groups').",
                related_name="%(class)s_visible",
                to="consent.consentgroup",
            ),
        ),
        migrations.AddField(
            model_name="codexteachingoffer",
            name="visible_to_tenures",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tenures who can see this (if mode is 'characters').",
                related_name="%(class)s_visible",
                to="roster.rostertenure",
            ),
        ),
        migrations.AddField(
            model_name="distinctioncodexgrant",
            name="distinction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="codex_grants",
                to="distinctions.distinction",
            ),
        ),
        migrations.AddField(
            model_name="distinctioncodexgrant",
            name="entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distinction_grants",
                to="codex.codexentry",
            ),
        ),
        migrations.AddField(
            model_name="pathcodexgrant",
            name="entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="path_grants",
                to="codex.codexentry",
            ),
        ),
        migrations.AddField(
            model_name="pathcodexgrant",
            name="path",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="codex_grants",
                to="classes.path",
            ),
        ),
        migrations.AddField(
            model_name="traditioncodexgrant",
            name="entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tradition_grants",
                to="codex.codexentry",
            ),
        ),
    ]
