# Generated by Django 5.2.14 on 2026-06-16 23:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("codex", "0003_create_subjectbreadcrumb_view"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="codexclue",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="codexclue",
            name="entry",
        ),
        migrations.DeleteModel(
            name="CharacterClueKnowledge",
        ),
        migrations.DeleteModel(
            name="CodexClue",
        ),
    ]
