# Generated by Django 5.2.15 on 2026-07-18 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("codex", "0004_alter_codexclue_unique_together_and_more"),
        ("evennia_extensions", "0015_pagebackground"),
    ]

    operations = [
        migrations.AddField(
            model_name="codexentry",
            name="art",
            field=models.ForeignKey(
                blank=True,
                help_text="Illustration for this entry, shown in the codex modal (#2408).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="codex_entries",
                to="evennia_extensions.media",
            ),
        ),
    ]
