# Generated by Django 5.2.4 on 2026-02-05 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("codex", "0006_split_content_to_lore_and_mechanics"),
        ("mechanics", "0003_add_resonance_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="codexentry",
            name="modifier_type",
            field=models.OneToOneField(
                blank=True,
                help_text="Link to a modifier type this entry documents (for resonances, stats, etc.).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="codex_entry",
                to="mechanics.modifiertype",
            ),
        ),
    ]
