# Generated by Django 5.2.15 on 2026-07-14 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("character_sheets", "0010_remove_charactersheet_family_and_more"),
        ("conditions", "0019_conditioninstance_last_resist_attempt_at"),
        ("covenants", "0027_alter_geararchetypecompatibility_gear_archetype_and_more"),
        ("mechanics", "0011_propertydetonation"),
        ("societies", "0028_organizationoffice"),
        ("stories", "0027_alter_storyprotectedsubject_subject_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="Army",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "disbanded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this army was disbanded. Null means active.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign_story",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional campaign story this army was formed for.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="armies",
                        to="stories.story",
                    ),
                ),
                (
                    "commander",
                    models.ForeignKey(
                        blank=True,
                        help_text="The overall commander of this army. May differ from individual unit commanders.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commanded_armies",
                        to="character_sheets.charactersheet",
                    ),
                ),
                (
                    "covenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional war covenant organizing this force.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="armies",
                        to="covenants.covenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MilitaryUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "descriptor",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional flavor tag (e.g. 'zombies-on-nightmares'). Narrative only — properties/capabilities/quality below drive mechanics.",
                        max_length=80,
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("militia", "Militia"),
                            ("levy", "Levy"),
                            ("trained", "Trained"),
                            ("veteran", "Veteran"),
                            ("elite", "Elite"),
                        ],
                        default="trained",
                        max_length=20,
                    ),
                ),
                ("strength", models.PositiveSmallIntegerField(default=100)),
                (
                    "morale",
                    models.PositiveSmallIntegerField(
                        default=70,
                        help_text="Second resource alongside strength (#1712). Unlike strength (starts at its ceiling), morale starts well below it.",
                    ),
                ),
                (
                    "individual_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Population data point mirroring CombatOpponent.swarm_count's naming/shape (#1794) — null means 'not a swarm-style unit'.",
                        null=True,
                    ),
                ),
                (
                    "commander",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional commander whose Battle Command modifier bonus applies to participants fighting alongside this unit's side/place.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commanded_military_units",
                        to="character_sheets.charactersheet",
                    ),
                ),
                (
                    "owner_org",
                    models.ForeignKey(
                        blank=True,
                        help_text="The organization that owns this unit. Null for transient enemy/summoned units.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="military_units",
                        to="societies.organization",
                    ),
                ),
                (
                    "properties",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Descriptive tags this unit carries (flying, aquatic, metal-clad, etc.) — the same catalog characters use (#1794). Presence-only.",
                        related_name="military_units",
                        to="mechanics.property",
                    ),
                ),
                (
                    "summoned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when this unit was created via a military-grade summon (#1711).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="summoned_military_units",
                        to="character_sheets.charactersheet",
                    ),
                ),
            ],
            options={
                "ordering": ["owner_org", "name"],
            },
        ),
        migrations.CreateModel(
            name="ArmyMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "left_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this unit left the army. Null means active membership.",
                        null=True,
                    ),
                ),
                (
                    "army",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="army_memberships",
                        to="military.army",
                    ),
                ),
                (
                    "military_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="army_memberships",
                        to="military.militaryunit",
                    ),
                ),
            ],
            options={
                "ordering": ["army", "joined_at"],
            },
        ),
        migrations.AddField(
            model_name="army",
            name="units",
            field=models.ManyToManyField(
                related_name="armies",
                through="military.ArmyMembership",
                to="military.militaryunit",
            ),
        ),
        migrations.CreateModel(
            name="MilitaryUnitCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.PositiveIntegerField()),
                (
                    "capability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="military_unit_values",
                        to="conditions.capabilitytype",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capability_values",
                        to="military.militaryunit",
                    ),
                ),
            ],
            options={
                "ordering": ["unit", "capability"],
            },
        ),
        migrations.AddField(
            model_name="militaryunit",
            name="capabilities",
            field=models.ManyToManyField(
                blank=True,
                help_text="What this unit can DO, at an authored per-unit magnitude via MilitaryUnitCapability (#1794).",
                related_name="military_units",
                through="military.MilitaryUnitCapability",
                to="conditions.capabilitytype",
            ),
        ),
        migrations.AddConstraint(
            model_name="armymembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("left_at__isnull", True)),
                fields=("army", "military_unit"),
                name="unique_active_army_membership",
            ),
        ),
        migrations.AddConstraint(
            model_name="militaryunitcapability",
            constraint=models.UniqueConstraint(
                fields=("unit", "capability"), name="unique_military_unit_capability"
            ),
        ),
    ]
