# Generated by Django 5.2.4 on 2026-01-19 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("traits", "0003_alter_pointconversionrange_trait_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tooltip",
                    models.TextField(
                        blank=True, help_text="Short description shown on hover in UI"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Order for display in character sheets and CG",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this skill is available for use",
                    ),
                ),
                (
                    "trait",
                    models.OneToOneField(
                        help_text="The trait definition this skill is linked to",
                        limit_choices_to={"trait_type": "skill"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill",
                        to="traits.trait",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "trait__name"],
            },
        ),
    ]
