# Generated by Django on 2026-01-19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Updates PathSkillSuggestion to reference Path model instead of CharacterClass.

    Note: Field is named 'character_path' instead of 'path' because SharedMemoryModel
    reserves 'path' as a class attribute for the model's module path.

    Data was cleared in 0002_clear_old_suggestions.
    """

    dependencies = [
        ("classes", "0002_add_path_model"),
        ("skills", "0001_initial"),
    ]

    operations = [
        # Remove the old character_class FK and unique_together constraint
        migrations.AlterUniqueTogether(
            name="pathskillsuggestion",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="pathskillsuggestion",
            name="character_class",
        ),
        # Add the new character_path FK
        migrations.AddField(
            model_name="pathskillsuggestion",
            name="character_path",
            field=models.ForeignKey(
                help_text="The path this suggestion belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skill_suggestions",
                to="classes.path",
                # Temporarily allow null for migration, will be cleaned up after
                null=True,
            ),
            preserve_default=False,
        ),
        # Now make it non-nullable (safe because RunPython deleted all existing rows)
        migrations.AlterField(
            model_name="pathskillsuggestion",
            name="character_path",
            field=models.ForeignKey(
                help_text="The path this suggestion belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skill_suggestions",
                to="classes.path",
            ),
        ),
        # Add back the unique_together with new field name
        migrations.AlterUniqueTogether(
            name="pathskillsuggestion",
            unique_together={("character_path", "skill")},
        ),
        # Update ordering
        migrations.AlterModelOptions(
            name="pathskillsuggestion",
            options={"ordering": ["character_path", "display_order", "skill__trait__name"]},
        ),
    ]
