# Generated by Django 5.2.4 on 2026-03-10 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0003_trainingallocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillpointbudget",
            name="teaching_skill",
            field=models.ForeignKey(
                blank=True,
                help_text="Skill used for mentor teaching bonus in training formula",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="skills.skill",
            ),
        ),
    ]
