# Generated by Django 5.2.4 on 2026-01-01 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
        ("roster", "0003_add_test_family"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialHeritage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'Sleeper', 'Misbegotten')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description explaining this heritage type to players"
                    ),
                ),
                (
                    "allows_full_species_list",
                    models.BooleanField(
                        default=True,
                        help_text="If True, players can select any species instead of restricted list",
                    ),
                ),
                (
                    "family_display",
                    models.CharField(
                        default="Unknown",
                        help_text="What to display for family (e.g., 'Unknown', 'Discoverable in play')",
                        max_length=100,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order in selection UI (lower = first)",
                    ),
                ),
                (
                    "starting_room_override",
                    models.ForeignKey(
                        blank=True,
                        help_text="Override starting room for this heritage (e.g., Sleeper Wake Room). If blank, uses area's default room.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="special_heritage_start",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "verbose_name": "Special Heritage",
                "verbose_name_plural": "Special Heritages",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="StartingArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the starting area (e.g., 'Arx')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Rich description shown on hover/click in character creation"
                    ),
                ),
                (
                    "crest_image",
                    models.URLField(
                        blank=True,
                        help_text="Cloudinary URL for crest/flag image. Leave blank for gradient placeholder.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this area can be selected in character creation",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order in selection UI (lower = first)",
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("all", "All Players"),
                            ("trust_required", "Trust Required"),
                            ("staff_only", "Staff Only"),
                        ],
                        default="all",
                        help_text="Who can select this area in character creation",
                        max_length=20,
                    ),
                ),
                (
                    "minimum_trust",
                    models.IntegerField(
                        default=0,
                        help_text="Minimum trust required when access_level is 'trust_required'",
                    ),
                ),
                (
                    "default_starting_room",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default Evennia room where characters from this area start. Can be None during early testing.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="starting_area_default",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "special_heritages",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Special heritage options available when selecting this area",
                        related_name="available_in_areas",
                        to="character_creation.specialheritage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Starting Area",
                "verbose_name_plural": "Starting Areas",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CharacterDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_stage",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Origin"),
                            (2, "Heritage"),
                            (3, "Lineage"),
                            (4, "Attributes"),
                            (5, "Path & Skills"),
                            (6, "Traits"),
                            (7, "Identity"),
                            (8, "Review"),
                        ],
                        default=1,
                        help_text="Current stage in character creation flow",
                    ),
                ),
                (
                    "species",
                    models.CharField(blank=True, help_text="Selected species", max_length=100),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("nonbinary", "Non-binary"),
                            ("other", "Other"),
                        ],
                        help_text="Character gender",
                        max_length=20,
                    ),
                ),
                (
                    "pronoun_subject",
                    models.CharField(
                        blank=True,
                        help_text="Subject pronoun (e.g., 'they')",
                        max_length=20,
                    ),
                ),
                (
                    "pronoun_object",
                    models.CharField(
                        blank=True,
                        help_text="Object pronoun (e.g., 'them')",
                        max_length=20,
                    ),
                ),
                (
                    "pronoun_possessive",
                    models.CharField(
                        blank=True,
                        help_text="Possessive pronoun (e.g., 'theirs')",
                        max_length=20,
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True, help_text="Character age in years", null=True
                    ),
                ),
                (
                    "is_orphan",
                    models.BooleanField(
                        default=False,
                        help_text="True if character has no family (normal upbringing only)",
                    ),
                ),
                (
                    "draft_data",
                    models.JSONField(
                        default=dict,
                        help_text="JSON blob for staged data: stats, skills, traits, identity, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Account creating this character",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        blank=True,
                        help_text="Selected family (null for orphan or special heritage)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="character_drafts",
                        to="roster.family",
                    ),
                ),
                (
                    "selected_heritage",
                    models.ForeignKey(
                        blank=True,
                        help_text="Selected special heritage (null = normal upbringing)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drafts",
                        to="character_creation.specialheritage",
                    ),
                ),
                (
                    "selected_area",
                    models.ForeignKey(
                        blank=True,
                        help_text="Selected starting area",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drafts",
                        to="character_creation.startingarea",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Draft",
                "verbose_name_plural": "Character Drafts",
            },
        ),
    ]
