# Generated by Django 5.2.4 on 2026-04-13 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("character_creation", "0002_initial"),
        ("character_sheets", "0003_initial"),
        ("classes", "0001_initial"),
        ("distinctions", "0001_initial"),
        ("forms", "0001_initial"),
        ("magic", "0001_initial"),
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
        ("realms", "0001_initial"),
        ("roster", "0001_initial"),
        ("societies", "0001_initial"),
        ("species", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="beginnings",
            name="societies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Societies characters gain awareness/membership in during character creation",
                related_name="connected_beginnings",
                to="societies.society",
            ),
        ),
        migrations.AddField(
            model_name="beginnings",
            name="starting_languages",
            field=models.ManyToManyField(
                blank=True,
                help_text="Languages granted to all characters from this path",
                related_name="beginnings",
                to="species.language",
            ),
        ),
        migrations.AddField(
            model_name="beginnings",
            name="starting_room_override",
            field=models.ForeignKey(
                blank=True,
                help_text="Override starting room for this Beginnings path (e.g., Sleeper wake room)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="beginnings_start",
                to="objects.objectdb",
            ),
        ),
        migrations.AddField(
            model_name="beginningtradition",
            name="beginning",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beginning_traditions",
                to="character_creation.beginnings",
            ),
        ),
        migrations.AddField(
            model_name="beginningtradition",
            name="required_distinction",
            field=models.ForeignKey(
                blank=True,
                help_text="Distinction required to select this tradition for this beginning.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="distinctions.distinction",
            ),
        ),
        migrations.AddField(
            model_name="beginningtradition",
            name="tradition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beginning_traditions",
                to="magic.tradition",
            ),
        ),
        migrations.AddField(
            model_name="beginnings",
            name="traditions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Traditions available for this beginning during CG.",
                related_name="available_beginnings",
                through="character_creation.BeginningTradition",
                to="magic.tradition",
            ),
        ),
        migrations.AddField(
            model_name="characterdraft",
            name="account",
            field=models.ForeignKey(
                help_text="Account creating this character",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_drafts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="characterdraft",
            name="build",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected build type",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drafts",
                to="forms.build",
            ),
        ),
        migrations.AddField(
            model_name="characterdraft",
            name="family",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected family (null for orphan or special heritage).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="character_drafts",
                to="roster.family",
            ),
        ),
        migrations.AddField(
            model_name="characterdraft",
            name="family_member",
            field=models.ForeignKey(
                blank=True,
                help_text="Family member position this character is filling",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drafts",
                to="roster.familymember",
            ),
        ),
        migrations.AddField(
            model_name="characterdraft",
            name="height_band",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected height band for CG",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drafts",
                to="forms.heightband",
            ),
        ),
        migrations.AddField(
            model_name="characterdraft",
            name="selected_beginnings",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected beginnings path",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drafts",
                to="character_creation.beginnings",
            ),
        ),
        migrations.AddField(
            model_name="characterdraft",
            name="selected_gender",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected gender",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drafts",
                to="character_sheets.gender",
            ),
        ),
        migrations.AddField(
            model_name="characterdraft",
            name="selected_path",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected starting path (Prospect stage only)",
                limit_choices_to={"is_active": True, "stage": 1},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drafts",
                to="classes.path",
            ),
        ),
        migrations.AddField(
            model_name="characterdraft",
            name="selected_species",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected species",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drafts",
                to="species.species",
            ),
        ),
        migrations.AddField(
            model_name="characterdraft",
            name="selected_tradition",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected magical tradition (gates magic template).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="magic.tradition",
            ),
        ),
        migrations.AddField(
            model_name="draftapplication",
            name="draft",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="application",
                to="character_creation.characterdraft",
            ),
        ),
        migrations.AddField(
            model_name="draftapplication",
            name="player_account",
            field=models.ForeignKey(
                blank=True,
                help_text="The player who submitted this application (survives draft deletion).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="draftapplication",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claimed_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="draftapplicationcomment",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="character_creation.draftapplication",
            ),
        ),
        migrations.AddField(
            model_name="draftapplicationcomment",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="Null for system-generated status change events.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="startingarea",
            name="default_starting_room",
            field=models.ForeignKey(
                blank=True,
                help_text="Default Evennia room where characters from this area start. Can be None during early testing.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="starting_area_default",
                to="objects.objectdb",
            ),
        ),
        migrations.AddField(
            model_name="startingarea",
            name="realm",
            field=models.ForeignKey(
                blank=True,
                help_text="Canonical realm/area referenced by this StartingArea (realms app).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="starting_areas",
                to="realms.realm",
            ),
        ),
        migrations.AddField(
            model_name="characterdraft",
            name="selected_area",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected starting area",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drafts",
                to="character_creation.startingarea",
            ),
        ),
        migrations.AddField(
            model_name="beginnings",
            name="starting_area",
            field=models.ForeignKey(
                help_text="The starting area this option belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beginnings",
                to="character_creation.startingarea",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="beginningtradition",
            unique_together={("beginning", "tradition")},
        ),
        migrations.AlterUniqueTogether(
            name="beginnings",
            unique_together={("starting_area", "name")},
        ),
    ]
