# Generated by Django 5.2.4 on 2026-01-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character_creation", "0003_shift_review_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterdraft",
            name="current_stage",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Origin"),
                    (2, "Heritage"),
                    (3, "Lineage"),
                    (4, "Attributes"),
                    (5, "Path & Skills"),
                    (6, "Distinctions"),
                    (7, "Magic"),
                    (8, "Appearance"),
                    (9, "Identity"),
                    (10, "Final Touches"),
                    (11, "Review"),
                ],
                default=1,
                help_text="Current stage in character creation flow",
            ),
        ),
    ]
