# Generated by Django 5.2.4 on 2026-03-07 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("character_creation", "0003_initial"),
        ("forms", "0001_initial"),
        ("magic", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="beginningtradition",
            name="tradition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beginning_traditions",
                to="magic.tradition",
            ),
        ),
        migrations.AddField(
            model_name="beginnings",
            name="traditions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Traditions available for this beginning during CG.",
                related_name="available_beginnings",
                through="character_creation.BeginningTradition",
                to="magic.tradition",
            ),
        ),
        migrations.AddField(
            model_name="characterdraft",
            name="account",
            field=models.ForeignKey(
                help_text="Account creating this character",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_drafts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="characterdraft",
            name="build",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected build type",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drafts",
                to="forms.build",
            ),
        ),
    ]
