# Generated by Django 5.2.4 on 2026-01-15 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("character_creation", "0008_remove_beginnings_ordering"),
        ("forms", "0003_add_height_build_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterdraft",
            name="build",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected build type",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drafts",
                to="forms.build",
            ),
        ),
        migrations.AddField(
            model_name="characterdraft",
            name="height_band",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected height band for CG",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drafts",
                to="forms.heightband",
            ),
        ),
        migrations.AddField(
            model_name="characterdraft",
            name="height_inches",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Exact height in inches within the selected band",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="characterdraft",
            name="current_stage",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Origin"),
                    (2, "Heritage"),
                    (3, "Lineage"),
                    (4, "Attributes"),
                    (5, "Path & Skills"),
                    (6, "Traits"),
                    (7, "Appearance"),
                    (8, "Identity"),
                    (9, "Review"),
                ],
                default=1,
                help_text="Current stage in character creation flow",
            ),
        ),
    ]
