# Generated by Django 5.2.4 on 2026-01-16 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "character_creation",
            "0009_characterdraft_build_characterdraft_height_band_and_more",
        ),
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beginnings",
            name="starting_room_override",
            field=models.ForeignKey(
                blank=True,
                help_text="Override starting room for this Beginnings path (e.g., Sleeper wake room)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="beginnings_start",
                to="objects.objectdb",
            ),
        ),
    ]
