# Generated by Django 5.2.15 on 2026-07-18 21:17

from django.db import migrations, models
import django.db.models.deletion

import core.natural_keys


class Migration(migrations.Migration):
    dependencies = [
        ("character_creation", "0014_beginnings_prelude_mission"),
    ]

    operations = [
        migrations.CreateModel(
            name="OriginTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name (part of natural key).", max_length=100
                    ),
                ),
                (
                    "frame_narrative",
                    models.TextField(
                        help_text="The fixed frame prose every character with this beginning shares."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Inactive templates are hidden from CG."
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Display order when multiple templates exist.",
                    ),
                ),
                (
                    "beginning",
                    models.ForeignKey(
                        help_text="The beginning this origin-story frame belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="origin_templates",
                        to="character_creation.beginnings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Origin Template",
                "verbose_name_plural": "Origin Templates",
                "ordering": ["beginning", "sort_order", "name"],
                "unique_together": {("beginning", "name")},
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="OriginTemplateSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Slot name (part of natural key).", max_length=100),
                ),
                (
                    "prompt",
                    models.TextField(help_text="The question shown to the player."),
                ),
                (
                    "example",
                    models.TextField(
                        blank=True,
                        help_text="Short illustrative answer shown in the guided step.",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="Required slots are marked in the post-CG finish-later editor.",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="The template this slot belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="character_creation.origintemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Origin Template Slot",
                "verbose_name_plural": "Origin Template Slots",
                "ordering": ["template", "sort_order", "name"],
                "unique_together": {("template", "name")},
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
    ]
