# Generated by Django 5.2.15 on 2026-07-18 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("character_creation", "0015_origintemplate_origintemplateslot"),
        ("character_sheets", "0011_charactersheet_origin_story_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterOriginSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(help_text="The player's authored answer.")),
                (
                    "sheet",
                    models.ForeignKey(
                        help_text="The character sheet this slot answer belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="origin_slots",
                        to="character_sheets.charactersheet",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        help_text="The catalog slot this answer fills.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="character_rows",
                        to="character_creation.origintemplateslot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Origin Slot",
                "verbose_name_plural": "Character Origin Slots",
                "ordering": ["slot__sort_order"],
                "unique_together": {("sheet", "slot")},
            },
        ),
    ]
