# Generated by Django 5.2.4 on 2025-07-27 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0012_defaultaccount_alter_accountdb_id_account_bot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerData",
            fields=[
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="player_data",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="How they appear to others",
                        max_length=100,
                    ),
                ),
                ("karma", models.PositiveIntegerField(default=0)),
                ("hide_from_watch", models.BooleanField(default=False)),
                ("private_mode", models.BooleanField(default=False)),
                (
                    "gm_notes",
                    models.TextField(blank=True, help_text="Staff notes about player"),
                ),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Player Data",
                "verbose_name_plural": "Player Data",
            },
        ),
        migrations.CreateModel(
            name="PlayerBlockList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blocked_date", models.DateTimeField(auto_now_add=True)),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Optional reason for blocking",
                        max_length=200,
                    ),
                ),
                (
                    "blocked_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_by",
                        to="evennia_extensions.playerdata",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="block_list",
                        to="evennia_extensions.playerdata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player Block List Entry",
                "verbose_name_plural": "Player Block List Entries",
                "unique_together": {("owner", "blocked_player")},
            },
        ),
        migrations.CreateModel(
            name="PlayerAllowList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="Optional note about this player",
                        max_length=200,
                    ),
                ),
                (
                    "allowed_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowed_by",
                        to="evennia_extensions.playerdata",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allow_list",
                        to="evennia_extensions.playerdata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player Allow List Entry",
                "verbose_name_plural": "Player Allow List Entries",
                "unique_together": {("owner", "allowed_player")},
            },
        ),
    ]
