# Generated by Django 5.2.4 on 2026-02-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evennia_extensions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerdata",
            name="rollmod",
            field=models.SmallIntegerField(default=0),
        ),
    ]
