# Generated by Django 5.2.15 on 2026-07-18 22:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("evennia_extensions", "0013_rename_playermedia_to_media"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="media",
            new_name="evennia_ext_player__dc5e36_idx",
            old_name="evennia_ext_player__8c3895_idx",
        ),
    ]
