# Generated by Django 5.2.14 on 2026-05-29 17:28

from django.db import migrations, models
import django.db.models.deletion

import core.natural_keys


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CheckCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Check categories",
                "ordering": ["display_order", "name"],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CheckTypeAspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Relevance multiplier for this aspect (default 1.0)",
                        max_digits=4,
                    ),
                ),
            ],
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CheckTypeTrait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Multiplier for this trait's contribution (default 1.0)",
                        max_digits=4,
                    ),
                ),
            ],
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Consequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("mechanical_description", models.TextField(blank=True)),
                ("weight", models.PositiveIntegerField(default=1)),
                ("character_loss", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConsequenceEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "effect_type",
                    models.CharField(
                        choices=[
                            ("apply_condition", "Apply Condition"),
                            ("remove_condition", "Remove Condition"),
                            ("add_property", "Add Property"),
                            ("remove_property", "Remove Property"),
                            ("deal_damage", "Deal Damage"),
                            ("launch_attack", "Launch Attack"),
                            ("launch_flow", "Launch Flow"),
                            ("grant_codex", "Grant Codex Entry"),
                            ("magical_scars", "Mage Scars"),
                            ("legend_award", "Award Legend"),
                        ],
                        max_length=20,
                    ),
                ),
                ("execution_order", models.PositiveIntegerField(default=0)),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("self", "Self (acting character)"),
                            (
                                "target",
                                "Target (recipient of social or targeted action)",
                            ),
                            ("location", "Location (challenge's room)"),
                        ],
                        default="self",
                        max_length=20,
                    ),
                ),
                (
                    "condition_severity",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("property_value", models.PositiveIntegerField(blank=True, null=True)),
                ("damage_amount", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "legend_base_value",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "legend_description_template",
                    models.TextField(blank=True, default=""),
                ),
            ],
            options={
                "ordering": ["execution_order"],
            },
        ),
        migrations.CreateModel(
            name="CheckType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_types",
                        to="checks.checkcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["category__display_order", "display_order", "name"],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
    ]
