# Generated by Django 5.2.4 on 2026-03-06 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("checks", "0001_initial"),
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checktypeaspect",
            name="aspect",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="check_type_aspects",
                to="classes.aspect",
            ),
        ),
        migrations.AddField(
            model_name="checktypeaspect",
            name="check_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aspects",
                to="checks.checktype",
            ),
        ),
        migrations.AddField(
            model_name="checktypetrait",
            name="check_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="traits",
                to="checks.checktype",
            ),
        ),
    ]
