# Generated by Django 5.2.4 on 2026-02-08 04:05

from django.db import migrations, models
import django.db.models.deletion

import core.natural_keys


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0002_checktypetrait"),
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckTypeAspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Relevance multiplier for this aspect (default 1.0)",
                        max_digits=4,
                    ),
                ),
                (
                    "aspect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_type_aspects",
                        to="classes.aspect",
                    ),
                ),
                (
                    "check_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aspects",
                        to="checks.checktype",
                    ),
                ),
            ],
            options={
                "ordering": ["check_type", "-weight"],
                "unique_together": {("check_type", "aspect")},
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
    ]
