# Generated by Django 5.2.4 on 2026-03-06 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("checks", "0002_initial"),
        ("traits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checktypetrait",
            name="trait",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="check_type_traits",
                to="traits.trait",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="checktype",
            unique_together={("name", "category")},
        ),
        migrations.AlterUniqueTogether(
            name="checktypeaspect",
            unique_together={("check_type", "aspect")},
        ),
        migrations.AlterUniqueTogether(
            name="checktypetrait",
            unique_together={("check_type", "trait")},
        ),
    ]
