# Generated by Django 5.2.14 on 2026-06-09 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0005_actiontemplate_accepts_pose_text_and_more"),
        ("character_sheets", "0005_charactersheet_max_active_npc_missions"),
        ("checks", "0003_initial"),
        ("mechanics", "0002_initial"),
        ("scenes", "0014_scenecheckmodifier"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsequenceOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modifier_total", models.IntegerField(default=0)),
                ("summary", models.CharField(blank=True, max_length=255)),
                (
                    "combat_interaction_timestamp",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Denormalized from combat_interaction.timestamp. Required because scenes_interaction is range-partitioned by timestamp — the composite FK constraint targets (combat_interaction_id, combat_interaction_timestamp). Populated atomically with combat_interaction_id by the caller.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge_record",
                    models.ForeignKey(
                        blank=True,
                        help_text="The CharacterChallengeRecord this outcome was resolved for. Null for combat-based resolutions.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consequence_outcomes",
                        to="mechanics.characterchallengerecord",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consequence_outcomes",
                        to="character_sheets.charactersheet",
                    ),
                ),
                (
                    "check_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consequence_outcomes",
                        to="checks.checktype",
                    ),
                ),
                (
                    "combat_interaction",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The Interaction created when this outcome was resolved via combat. Null for challenge-based resolutions.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consequence_outcomes",
                        to="scenes.interaction",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consequence_outcomes",
                        to="actions.consequencepool",
                    ),
                ),
                (
                    "selected_consequence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consequence_outcomes",
                        to="checks.consequence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsequenceOutcomeModifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("condition", "Condition"),
                            ("rollmod", "Roll Modifier"),
                            ("scene", "Surroundings"),
                            ("equipment", "Equipment"),
                            ("effort", "Effort"),
                            ("fatigue", "Fatigue"),
                            ("strain", "Strain"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_label", models.CharField(max_length=120)),
                ("value", models.IntegerField()),
                (
                    "outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifiers",
                        to="checks.consequenceoutcome",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="consequenceoutcome",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("combat_interaction__isnull", False),
                        ("challenge_record__isnull", True),
                    ),
                    models.Q(
                        ("combat_interaction__isnull", True),
                        ("challenge_record__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="consequence_outcome_exactly_one_source",
            ),
        ),
    ]
