# Generated by Django 5.2.4 on 2026-05-12 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0005_alter_consequenceeffect_effect_type"),
        ("societies", "0003_covenantlegendsummary_covenantlegendcredit"),
    ]

    operations = [
        migrations.AddField(
            model_name="consequenceeffect",
            name="legend_base_value",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consequenceeffect",
            name="legend_description_template",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="consequenceeffect",
            name="legend_source_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consequence_effects",
                to="societies.legendsourcetype",
            ),
        ),
        migrations.AlterField(
            model_name="consequenceeffect",
            name="effect_type",
            field=models.CharField(
                choices=[
                    ("apply_condition", "Apply Condition"),
                    ("remove_condition", "Remove Condition"),
                    ("add_property", "Add Property"),
                    ("remove_property", "Remove Property"),
                    ("deal_damage", "Deal Damage"),
                    ("launch_attack", "Launch Attack"),
                    ("launch_flow", "Launch Flow"),
                    ("grant_codex", "Grant Codex Entry"),
                    ("magical_scars", "Mage Scars"),
                    ("legend_award", "Award Legend"),
                ],
                max_length=20,
            ),
        ),
    ]
