# Generated by Django 5.2.14 on 2026-06-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0006_alter_consequenceoutcomemodifier_source_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="consequence",
            name="theater",
            field=models.BooleanField(
                default=False,
                help_text="Authored drama flag (#924): a tier pool containing this consequence fires the roulette reveal even without a character_loss candidate (character_loss always fires it).",
            ),
        ),
    ]
