# Generated by Django 5.2.14 on 2026-06-13 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0007_consequence_theater"),
        ("societies", "0015_personadeedknowledge"),
    ]

    operations = [
        migrations.AddField(
            model_name="consequenceeffect",
            name="capture_captor_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The org that takes the captive (and issues any ransom). Optional.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="capture_consequence_effects",
                to="societies.organization",
            ),
        ),
        migrations.AddField(
            model_name="consequenceeffect",
            name="capture_offscreen_loss_allowed",
            field=models.BooleanField(
                default=False,
                help_text="Authored default for the captive's off-screen-loss flag. False keeps the captive un-loseable while the player is away.",
            ),
        ),
        migrations.AlterField(
            model_name="consequenceeffect",
            name="effect_type",
            field=models.CharField(
                choices=[
                    ("apply_condition", "Apply Condition"),
                    ("remove_condition", "Remove Condition"),
                    ("add_property", "Add Property"),
                    ("remove_property", "Remove Property"),
                    ("deal_damage", "Deal Damage"),
                    ("launch_attack", "Launch Attack"),
                    ("launch_flow", "Launch Flow"),
                    ("grant_codex", "Grant Codex Entry"),
                    ("magical_scars", "Mage Scars"),
                    ("legend_award", "Award Legend"),
                    ("capture", "Capture"),
                ],
                max_length=20,
            ),
        ),
    ]
