# Generated by Django 5.2.14 on 2026-06-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0013_alter_consequenceeffect_effect_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consequenceeffect",
            name="effect_type",
            field=models.CharField(
                choices=[
                    ("apply_condition", "Apply Condition"),
                    ("remove_condition", "Remove Condition"),
                    ("add_property", "Add Property"),
                    ("remove_property", "Remove Property"),
                    ("deal_damage", "Deal Damage"),
                    ("launch_attack", "Launch Attack"),
                    ("launch_flow", "Launch Flow"),
                    ("grant_codex", "Grant Codex Entry"),
                    ("magical_scars", "Mage Scars"),
                    ("legend_award", "Award Legend"),
                    ("capture", "Capture"),
                    ("escape_captivity", "Escape Captivity"),
                    ("rescue_captive", "Rescue Captive"),
                ],
                max_length=20,
            ),
        ),
    ]
