# Generated by Django 5.2.14 on 2026-06-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0017_checktypespecialization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consequenceoutcomemodifier",
            name="source_kind",
            field=models.CharField(
                choices=[
                    ("condition", "Condition"),
                    ("rollmod", "Roll Modifier"),
                    ("scene", "Surroundings"),
                    ("equipment", "Equipment"),
                    ("fashion", "Fashion"),
                    ("character", "Character"),
                    ("effort", "Effort"),
                    ("fatigue", "Fatigue"),
                    ("strain", "Strain"),
                    ("affinity", "Affinity"),
                    ("pull", "Combat Pull"),
                    ("relationship", "Relationship"),
                ],
                max_length=20,
            ),
        ),
    ]
