# Generated by Django 5.2.14 on 2026-07-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0022_consequenceeffect_distinction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consequenceeffect",
            name="npc_regard_amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="consequenceeffect",
            name="effect_type",
            field=models.CharField(
                choices=[
                    ("apply_condition", "Apply Condition"),
                    ("remove_condition", "Remove Condition"),
                    ("set_relationship_condition", "Set Relationship Condition"),
                    ("shift_affection", "Shift Affection"),
                    ("shift_npc_regard", "Shift NPC Regard"),
                    ("add_property", "Add Property"),
                    ("remove_property", "Remove Property"),
                    ("grant_distinction", "Grant Distinction"),
                    ("deal_damage", "Deal Damage"),
                    ("launch_attack", "Launch Attack"),
                    ("launch_flow", "Launch Flow"),
                    ("grant_codex", "Grant Codex Entry"),
                    ("magical_scars", "Mage Scars"),
                    ("legend_award", "Award Legend"),
                    ("capture", "Capture"),
                    ("escape_captivity", "Escape Captivity"),
                    ("rescue_captive", "Rescue Captive"),
                    ("create_position", "Create Position"),
                    ("move_to_position", "Move to Position"),
                    ("sever_edge", "Sever Edge"),
                    ("connect_edge", "Connect Edge"),
                    ("grant_flight", "Grant Flight"),
                    ("remove_flight", "Remove Flight"),
                ],
                max_length=32,
            ),
        ),
    ]
