# Generated by Django 5.2.4 on 2026-04-13 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
        ("scenes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BugReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="What the player observed."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("reviewed", "Reviewed"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "reporter_account",
                    models.ForeignKey(
                        help_text="The account that submitted this.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter_persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bug_reports",
                        to="scenes.persona",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlayerFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Freeform feedback text from the player."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("reviewed", "Reviewed"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Room the submitter was in at the time, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "reporter_account",
                    models.ForeignKey(
                        help_text="The account that submitted this.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter_persona",
                    models.ForeignKey(
                        help_text="The persona the submitter was wearing when they submitted.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feedback_submissions",
                        to="scenes.persona",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlayerReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "behavior_description",
                    models.TextField(
                        help_text="What the reported persona did. Stub — wording needs design pass."
                    ),
                ),
                (
                    "asked_to_stop",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the reporter asked the other player to stop the behavior.",
                    ),
                ),
                (
                    "blocked_or_muted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the reporter blocked or muted as a result.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("reviewed", "Reviewed"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "interaction",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="A specific flagged interaction, if applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="scenes.interaction",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Room the reporter was in when submitting.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "reported_account",
                    models.ForeignKey(
                        help_text="The account behind the reported persona at the time of the incident. Stored directly so staff can query by account without walking the persona chain.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reported_persona",
                    models.ForeignKey(
                        help_text="The persona of the reported player at the time of the incident.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports_against",
                        to="scenes.persona",
                    ),
                ),
                (
                    "reporter_account",
                    models.ForeignKey(
                        help_text="The account that submitted this.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter_persona",
                    models.ForeignKey(
                        help_text="The persona the reporter was wearing when submitting.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports_submitted",
                        to="scenes.persona",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        help_text="The scene where the behavior occurred, if applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="scenes.scene",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("reporter_persona", models.F("reported_persona")),
                            _negated=True,
                        ),
                        name="player_report_reporter_not_reported",
                    )
                ],
            },
        ),
    ]
