# Generated by Django 5.2.4 on 2026-03-06 20:05

from decimal import Decimal

import django.core.validators
from django.db import migrations, models

import core.natural_keys


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Affinity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Affinity name (e.g., 'Celestial', 'Abyssal', 'Primal').",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this affinity."),
                ),
            ],
            options={
                "verbose_name_plural": "Affinities",
                "ordering": ["name"],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="AnimaRitualPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "performed_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the ritual was performed."
                    ),
                ),
                (
                    "was_successful",
                    models.BooleanField(help_text="Whether the ritual succeeded."),
                ),
                (
                    "anima_recovered",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Amount of anima recovered (if successful).",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes about this performance."
                    ),
                ),
            ],
            options={
                "verbose_name": "Anima Ritual Performance",
                "verbose_name_plural": "Anima Ritual Performances",
                "ordering": ["-performed_at"],
            },
        ),
        migrations.CreateModel(
            name="Cantrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField()),
                (
                    "archetype",
                    models.CharField(
                        choices=[
                            ("attack", "Attack"),
                            ("defense", "Defense"),
                            ("buff", "Buff"),
                            ("debuff", "Debuff"),
                            ("utility", "Utility"),
                        ],
                        help_text="Player-facing category for CG grouping: attack, defense, buff, debuff, utility.",
                        max_length=20,
                    ),
                ),
                (
                    "base_intensity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Starting intensity for the technique created from this cantrip.",
                    ),
                ),
                (
                    "base_control",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Starting control for the technique created from this cantrip.",
                    ),
                ),
                (
                    "base_anima_cost",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Starting anima cost for the technique created from this cantrip.",
                    ),
                ),
                (
                    "requires_facet",
                    models.BooleanField(
                        default=False,
                        help_text="If true, player must pick a facet (element/damage type) from allowed_facets.",
                    ),
                ),
                (
                    "facet_prompt",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Player-facing dropdown label, e.g. "Choose your element". Only used when requires_facet=True.',
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Cantrip",
                "verbose_name_plural": "Cantrips",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CharacterAffinityTotal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Character Affinity Total",
                "verbose_name_plural": "Character Affinity Totals",
            },
        ),
        migrations.CreateModel(
            name="CharacterAnima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current",
                    models.PositiveIntegerField(default=10, help_text="Current anima available."),
                ),
                (
                    "maximum",
                    models.PositiveIntegerField(default=10, help_text="Maximum anima capacity."),
                ),
                (
                    "last_recovery",
                    models.DateTimeField(
                        blank=True,
                        help_text="When anima was last recovered through ritual.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Anima",
                "verbose_name_plural": "Character Anima",
            },
        ),
        migrations.CreateModel(
            name="CharacterAnimaRitual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Social activity that restores anima."),
                ),
            ],
            options={
                "verbose_name": "Character Anima Ritual",
                "verbose_name_plural": "Character Anima Rituals",
            },
        ),
        migrations.CreateModel(
            name="CharacterAura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "celestial",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage of Celestial affinity (0-100).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal(0)),
                            django.core.validators.MaxValueValidator(Decimal(100)),
                        ],
                    ),
                ),
                (
                    "primal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("80.00"),
                        help_text="Percentage of Primal affinity (0-100).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal(0)),
                            django.core.validators.MaxValueValidator(Decimal(100)),
                        ],
                    ),
                ),
                (
                    "abyssal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        help_text="Percentage of Abyssal affinity (0-100).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal(0)),
                            django.core.validators.MaxValueValidator(Decimal(100)),
                        ],
                    ),
                ),
                (
                    "glimpse_story",
                    models.TextField(
                        blank=True,
                        help_text="Narrative of the character's first magical awakening (The Glimpse).",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Character Aura",
                "verbose_name_plural": "Character Auras",
            },
        ),
        migrations.CreateModel(
            name="CharacterFacet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flavor_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="What this facet means to the character.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Character Facet",
                "verbose_name_plural": "Character Facets",
            },
        ),
        migrations.CreateModel(
            name="CharacterGift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acquired_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this gift was acquired."
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Gift",
                "verbose_name_plural": "Character Gifts",
            },
        ),
        migrations.CreateModel(
            name="CharacterResonance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("self", "Self Only"), ("area", "Area Effect")],
                        default="self",
                        help_text="Whether this resonance affects only the character or an area.",
                        max_length=20,
                    ),
                ),
                (
                    "strength",
                    models.CharField(
                        choices=[
                            ("minor", "Minor"),
                            ("moderate", "Moderate"),
                            ("major", "Major"),
                        ],
                        default="moderate",
                        help_text="The strength of this resonance attachment.",
                        max_length=20,
                    ),
                ),
                (
                    "flavor_text",
                    models.TextField(
                        blank=True,
                        help_text="Optional player-defined description of how this resonance manifests.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this resonance is currently active.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Character Resonance",
                "verbose_name_plural": "Character Resonances",
            },
        ),
        migrations.CreateModel(
            name="CharacterResonanceTotal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Character Resonance Total",
                "verbose_name_plural": "Character Resonance Totals",
            },
        ),
        migrations.CreateModel(
            name="CharacterTechnique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acquired_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this technique was acquired."
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Technique",
                "verbose_name_plural": "Character Techniques",
            },
        ),
        migrations.CreateModel(
            name="CharacterTradition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acquired_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the character joined this tradition.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Tradition",
                "verbose_name_plural": "Character Traditions",
            },
        ),
        migrations.CreateModel(
            name="EffectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Effect type name (e.g., 'Attack', 'Defense', 'Movement').",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this effect type."),
                ),
                (
                    "base_power",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Base power value for scaled effects. Null for binary effects.",
                        null=True,
                    ),
                ),
                (
                    "base_anima_cost",
                    models.PositiveIntegerField(
                        default=2, help_text="Base anima cost for this effect type."
                    ),
                ),
                (
                    "has_power_scaling",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this effect type uses power scaling.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Effect Type",
                "verbose_name_plural": "Effect Types",
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Facet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Facet name (e.g., 'Wolf', 'Silk', 'Creatures').",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of this facet's thematic meaning.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facet",
                "verbose_name_plural": "Facets",
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this gift.",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Player-facing description of this gift."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="IntensityTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this tier (e.g., 'Minor', 'Moderate').",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "threshold",
                    models.PositiveIntegerField(
                        help_text="Minimum calculated power to reach this tier.",
                        unique=True,
                    ),
                ),
                (
                    "control_modifier",
                    models.IntegerField(
                        default=0,
                        help_text="Modifier to control rolls at this intensity.",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Player-facing description of this intensity level.",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Staff-only notes about this tier."),
                ),
            ],
            options={
                "verbose_name": "Intensity Tier",
                "verbose_name_plural": "Intensity Tiers",
                "ordering": ["threshold"],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Motif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Overall magical aesthetic description."
                    ),
                ),
            ],
            options={
                "verbose_name": "Motif",
                "verbose_name_plural": "Motifs",
            },
        ),
        migrations.CreateModel(
            name="MotifResonance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_from_gift",
                    models.BooleanField(
                        default=False,
                        help_text="True if auto-populated from a Gift, False if optional.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Motif Resonance",
                "verbose_name_plural": "Motif Resonances",
            },
        ),
        migrations.CreateModel(
            name="MotifResonanceAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Motif Resonance Association",
                "verbose_name_plural": "Motif Resonance Associations",
            },
        ),
        migrations.CreateModel(
            name="Reincarnation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "past_life_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the past life (filled in by staff/GM).",
                        max_length=200,
                    ),
                ),
                (
                    "past_life_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about the past life (filled in by staff/GM).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reincarnation",
                "verbose_name_plural": "Reincarnations",
            },
        ),
        migrations.CreateModel(
            name="Resonance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Resonance name (e.g., 'Bene', 'Praedari', 'Sylva').",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this resonance."),
                ),
            ],
            options={
                "ordering": ["affinity", "name"],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Restriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the restriction (e.g., 'Touch Range', 'Undead Only').",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of this restriction's limitations.",
                    ),
                ),
                (
                    "power_bonus",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Power bonus granted when this restriction is applied.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Restriction",
                "verbose_name_plural": "Restrictions",
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Technique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the technique (not unique - different characters can have same name).",
                        max_length=200,
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="The level of this technique (determines tier).",
                    ),
                ),
                (
                    "intensity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Base power of the technique. Determines damage and effect strength.",
                    ),
                ),
                (
                    "control",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Base safety/precision. When intensity exceeds control at runtime, effects become unpredictable and anima cost can spike.",
                    ),
                ),
                (
                    "anima_cost",
                    models.PositiveIntegerField(help_text="Anima cost to use this technique."),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what this technique does."
                    ),
                ),
            ],
            options={
                "verbose_name": "Technique",
                "verbose_name_plural": "Techniques",
            },
        ),
        migrations.CreateModel(
            name="TechniqueStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Style name (e.g., 'Manifestation', 'Subtle', 'Prayer').",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this technique style."),
                ),
            ],
            options={
                "verbose_name": "Technique Style",
                "verbose_name_plural": "Technique Styles",
                "ordering": ["name"],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "romantic",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Romantic intensity (0-100).",
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "trust",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Trust and faith (0-100).",
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "rivalry",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Competitive tension (0-100).",
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "protective",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Protective instinct (0-100).",
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "enmity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Hatred and opposition (0-100).",
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "is_soul_tether",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is an Abyssal Soul Tether (grants Control bonus).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Thread",
                "verbose_name_plural": "Threads",
            },
        ),
        migrations.CreateModel(
            name="ThreadJournal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The journal entry content (IC description of the moment)."
                    ),
                ),
                (
                    "romantic_change",
                    models.IntegerField(
                        default=0,
                        help_text="Change in romantic value when this entry was made.",
                    ),
                ),
                (
                    "trust_change",
                    models.IntegerField(
                        default=0,
                        help_text="Change in trust value when this entry was made.",
                    ),
                ),
                (
                    "rivalry_change",
                    models.IntegerField(
                        default=0,
                        help_text="Change in rivalry value when this entry was made.",
                    ),
                ),
                (
                    "protective_change",
                    models.IntegerField(
                        default=0,
                        help_text="Change in protective value when this entry was made.",
                    ),
                ),
                (
                    "enmity_change",
                    models.IntegerField(
                        default=0,
                        help_text="Change in enmity value when this entry was made.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Thread Journal Entry",
                "verbose_name_plural": "Thread Journal Entries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ThreadResonance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strength",
                    models.CharField(
                        choices=[
                            ("minor", "Minor"),
                            ("moderate", "Moderate"),
                            ("major", "Major"),
                        ],
                        default="moderate",
                        help_text="The strength of this resonance on the thread.",
                        max_length=20,
                    ),
                ),
                (
                    "flavor_text",
                    models.TextField(
                        blank=True,
                        help_text="How this resonance manifests in the relationship.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Thread Resonance",
                "verbose_name_plural": "Thread Resonances",
            },
        ),
        migrations.CreateModel(
            name="ThreadType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Display name for this thread type.", max_length=50),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier for this thread type.",
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Player-facing description of this thread type.",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Staff-only notes about this thread type."
                    ),
                ),
                (
                    "romantic_threshold",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum romantic value to qualify (null = not required).",
                        null=True,
                    ),
                ),
                (
                    "trust_threshold",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum trust value to qualify (null = not required).",
                        null=True,
                    ),
                ),
                (
                    "rivalry_threshold",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum rivalry value to qualify (null = not required).",
                        null=True,
                    ),
                ),
                (
                    "protective_threshold",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum protective value to qualify (null = not required).",
                        null=True,
                    ),
                ),
                (
                    "enmity_threshold",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum enmity value to qualify (null = not required).",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Thread Type",
                "verbose_name_plural": "Thread Types",
                "ordering": ["name"],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Tradition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this tradition.",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Player-facing description of this tradition's philosophy and practices.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this tradition is currently available for selection.",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display ordering within lists (lower numbers appear first).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tradition",
                "verbose_name_plural": "Traditions",
                "ordering": ["sort_order", "name"],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
    ]
