# Generated by Django 5.2.4 on 2026-01-29 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("character_sheets", "0002_initial"),
        ("magic", "0001_initial"),
        ("mechanics", "0002_modifiertype_affiliated_affinity"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterAffinityTotal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "affinity_type",
                    models.CharField(
                        choices=[
                            ("celestial", "Celestial"),
                            ("primal", "Primal"),
                            ("abyssal", "Abyssal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total", models.IntegerField(default=0)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affinity_totals",
                        to="character_sheets.charactersheet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Affinity Total",
                "verbose_name_plural": "Character Affinity Totals",
                "unique_together": {("character", "affinity_type")},
            },
        ),
        migrations.CreateModel(
            name="CharacterResonanceTotal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.IntegerField(default=0)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resonance_totals",
                        to="character_sheets.charactersheet",
                    ),
                ),
                (
                    "resonance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="character_totals",
                        to="mechanics.modifiertype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Resonance Total",
                "verbose_name_plural": "Character Resonance Totals",
                "unique_together": {("character", "resonance")},
            },
        ),
    ]
