# Generated by Django 5.2.4 on 2026-02-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intensitytier",
            name="name",
            field=models.CharField(
                help_text="Display name for this tier (e.g., 'Minor', 'Moderate').",
                max_length=50,
                unique=True,
            ),
        ),
    ]
