# Generated by Django 5.2.4 on 2026-02-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="characteraura",
            name="glimpse_story",
            field=models.TextField(
                blank=True,
                help_text="Narrative of the character's first magical awakening (The Glimpse).",
            ),
        ),
    ]
