# Generated by Django 5.2.4 on 2026-02-14 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("character_sheets", "0002_initial"),
        ("magic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reincarnation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "past_life_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the past life (filled in by staff/GM).",
                        max_length=200,
                    ),
                ),
                (
                    "past_life_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about the past life (filled in by staff/GM).",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        help_text="The character who is a reincarnation.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reincarnations",
                        to="character_sheets.charactersheet",
                    ),
                ),
                (
                    "gift",
                    models.ForeignKey(
                        help_text="The Atavism gift manifesting the past life.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reincarnation",
                        to="magic.gift",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reincarnation",
                "verbose_name_plural": "Reincarnations",
            },
        ),
    ]
