# Generated by Django 5.2.4 on 2026-03-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0002_initial"),
        ("mechanics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resonance",
            name="properties",
            field=models.ManyToManyField(
                blank=True,
                help_text="Properties associated with this resonance (e.g., Flame → flame property).",
                related_name="resonances",
                to="mechanics.property",
            ),
        ),
    ]
