# Generated by Django 5.2.14 on 2026-07-03 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("character_sheets", "0002_initial"),
        ("classes", "0001_initial"),
        ("magic", "0002_initial"),
        ("scenes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animaritualperformance",
            name="scene",
            field=models.ForeignKey(
                blank=True,
                help_text="The scene where this ritual was performed.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anima_ritual_performances",
                to="scenes.scene",
            ),
        ),
        migrations.AddField(
            model_name="animaritualperformance",
            name="target_character",
            field=models.ForeignKey(
                help_text="The character the ritual was performed with.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anima_ritual_participations",
                to="character_sheets.charactersheet",
            ),
        ),
        migrations.AddField(
            model_name="auderemajoracrossing",
            name="character_sheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audere_majora_crossings",
                to="character_sheets.charactersheet",
            ),
        ),
        migrations.AddField(
            model_name="auderemajoracrossing",
            name="chosen_path",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audere_majora_crossings",
                to="classes.path",
            ),
        ),
        migrations.AddField(
            model_name="auderemajoracrossing",
            name="declaration_interaction",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The declaration pose. Soft FK — partitioned table.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="scenes.interaction",
            ),
        ),
    ]
