# Generated by Django 5.2.4 on 2026-02-14 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0002_reincarnation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reincarnation",
            name="gift",
            field=models.OneToOneField(
                help_text="The Atavism gift manifesting the past life.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reincarnation",
                to="magic.gift",
            ),
        ),
    ]
