# Generated by Django 5.2.4 on 2026-02-01 01:58

from django.db import migrations, models

import core.natural_keys


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0001_initial"),
        ("magic", "0002_characteraffinitytotal_characterresonancetotal"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechniqueStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Style name (e.g., 'Manifestation', 'Subtle', 'Prayer').",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this technique style."),
                ),
                (
                    "allowed_paths",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Paths that can use techniques of this style.",
                        related_name="allowed_styles",
                        to="classes.path",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technique Style",
                "verbose_name_plural": "Technique Styles",
                "ordering": ["name"],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
    ]
