# Generated by Django 5.2.14 on 2026-05-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0003_accept_soul_tether_placeholder_grants"),
        ("mechanics", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="technique",
            name="properties",
            field=models.ManyToManyField(
                blank=True,
                help_text="Neutral descriptive tags on this technique (e.g. cursed), used by reactive trigger filters via the has_property op.",
                related_name="techniques",
                to="mechanics.property",
            ),
        ),
    ]
