# Generated by Django 5.2.4 on 2026-03-06 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("magic", "0003_initial"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="characteranimaritual",
            name="skill",
            field=models.ForeignKey(
                help_text="The skill used in this ritual.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="anima_rituals",
                to="skills.skill",
            ),
        ),
        migrations.AddField(
            model_name="characteranimaritual",
            name="specialization",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional specialization for this ritual.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="anima_rituals",
                to="skills.specialization",
            ),
        ),
    ]
