# Generated by Django 5.2.4 on 2026-02-01 02:20

from django.db import migrations, models

import core.natural_keys


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0004_add_effect_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the restriction (e.g., 'Touch Range', 'Undead Only').",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of this restriction's limitations.",
                    ),
                ),
                (
                    "power_bonus",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Power bonus granted when this restriction is applied.",
                    ),
                ),
                (
                    "allowed_effect_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Effect types this restriction can be applied to.",
                        related_name="available_restrictions",
                        to="magic.effecttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Restriction",
                "verbose_name_plural": "Restrictions",
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
    ]
