# Generated by Django 5.2.4 on 2026-01-20 23:38

from django.db import migrations, models
import django.db.models.deletion

import core.natural_keys


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0005_intensitytier_gift_power_charactergift_and_more"),
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimaRitualType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Display name for this ritual type.", max_length=50),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier for this ritual type.",
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("solitary", "Solitary"),
                            ("collaborative", "Collaborative"),
                            ("environmental", "Environmental"),
                            ("ceremonial", "Ceremonial"),
                        ],
                        help_text="The category of ritual activity.",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Player-facing description of this ritual type.",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Staff-only notes about this ritual type."
                    ),
                ),
                (
                    "base_recovery",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Base anima recovered when performing this ritual.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anima Ritual Type",
                "verbose_name_plural": "Anima Ritual Types",
                "ordering": ["category", "name"],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CharacterAnima",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current",
                    models.PositiveIntegerField(default=10, help_text="Current anima available."),
                ),
                (
                    "maximum",
                    models.PositiveIntegerField(default=10, help_text="Maximum anima capacity."),
                ),
                (
                    "last_recovery",
                    models.DateTimeField(
                        blank=True,
                        help_text="When anima was last recovered through ritual.",
                        null=True,
                    ),
                ),
                (
                    "character",
                    models.OneToOneField(
                        help_text="The character this anima belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anima",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Anima",
                "verbose_name_plural": "Character Anima",
            },
        ),
        migrations.CreateModel(
            name="CharacterAnimaRitual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "personal_description",
                    models.TextField(
                        help_text="How this character personally performs this ritual."
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the character's primary recovery method.",
                    ),
                ),
                (
                    "times_performed",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this ritual has been performed.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        help_text="The character who performs this ritual.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anima_rituals",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "ritual_type",
                    models.ForeignKey(
                        help_text="The type of ritual.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="character_rituals",
                        to="magic.animaritualtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Anima Ritual",
                "verbose_name_plural": "Character Anima Rituals",
                "unique_together": {("character", "ritual_type")},
            },
        ),
    ]
