# Generated by Django 5.2.4 on 2026-01-20 23:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

import core.natural_keys


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0006_animaritualtype_characteranima_characteranimaritual"),
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "romantic",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Romantic intensity (0-100).",
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "trust",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Trust and faith (0-100).",
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "rivalry",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Competitive tension (0-100).",
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "protective",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Protective instinct (0-100).",
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "enmity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Hatred and opposition (0-100).",
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "is_soul_tether",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is an Abyssal Soul Tether (grants Control bonus).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character_a",
                    models.ForeignKey(
                        help_text="The first character in this thread.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads_initiated",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "character_b",
                    models.ForeignKey(
                        help_text="The second character in this thread.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads_received",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thread",
                "verbose_name_plural": "Threads",
                "unique_together": {("character_a", "character_b")},
            },
        ),
        migrations.CreateModel(
            name="ThreadJournal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The journal entry content (IC description of the moment)."
                    ),
                ),
                (
                    "romantic_change",
                    models.IntegerField(
                        default=0,
                        help_text="Change in romantic value when this entry was made.",
                    ),
                ),
                (
                    "trust_change",
                    models.IntegerField(
                        default=0,
                        help_text="Change in trust value when this entry was made.",
                    ),
                ),
                (
                    "rivalry_change",
                    models.IntegerField(
                        default=0,
                        help_text="Change in rivalry value when this entry was made.",
                    ),
                ),
                (
                    "protective_change",
                    models.IntegerField(
                        default=0,
                        help_text="Change in protective value when this entry was made.",
                    ),
                ),
                (
                    "enmity_change",
                    models.IntegerField(
                        default=0,
                        help_text="Change in enmity value when this entry was made.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The character who wrote this entry.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="thread_journal_entries",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        help_text="The thread this entry belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to="magic.thread",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thread Journal Entry",
                "verbose_name_plural": "Thread Journal Entries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ThreadType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Display name for this thread type.", max_length=50),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier for this thread type.",
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Player-facing description of this thread type.",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Staff-only notes about this thread type."
                    ),
                ),
                (
                    "romantic_threshold",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum romantic value to qualify (null = not required).",
                        null=True,
                    ),
                ),
                (
                    "trust_threshold",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum trust value to qualify (null = not required).",
                        null=True,
                    ),
                ),
                (
                    "rivalry_threshold",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum rivalry value to qualify (null = not required).",
                        null=True,
                    ),
                ),
                (
                    "protective_threshold",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum protective value to qualify (null = not required).",
                        null=True,
                    ),
                ),
                (
                    "enmity_threshold",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum enmity value to qualify (null = not required).",
                        null=True,
                    ),
                ),
                (
                    "grants_resonance",
                    models.ForeignKey(
                        blank=True,
                        help_text="Resonance granted by this thread type.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="thread_type_grants",
                        to="magic.resonance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thread Type",
                "verbose_name_plural": "Thread Types",
                "ordering": ["name"],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ThreadResonance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strength",
                    models.CharField(
                        choices=[
                            ("minor", "Minor"),
                            ("moderate", "Moderate"),
                            ("major", "Major"),
                        ],
                        default="moderate",
                        help_text="The strength of this resonance on the thread.",
                        max_length=20,
                    ),
                ),
                (
                    "flavor_text",
                    models.TextField(
                        blank=True,
                        help_text="How this resonance manifests in the relationship.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resonance",
                    models.ForeignKey(
                        help_text="The resonance type.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thread_attachments",
                        to="magic.resonance",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        help_text="The thread this resonance is attached to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resonances",
                        to="magic.thread",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thread Resonance",
                "verbose_name_plural": "Thread Resonances",
                "unique_together": {("thread", "resonance")},
            },
        ),
    ]
