# Generated by Django 5.2.4 on 2026-03-16 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0006_remove_techniquecapabilitygrant_prerequisite_key_and_more"),
        ("mechanics", "0005_prerequisitetype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="techniquecapabilitygrant",
            name="prerequisite",
            field=models.ForeignKey(
                blank=True,
                help_text="Source-specific prerequisite, checked in addition to Capability-level ones.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="technique_grants",
                to="mechanics.prerequisitetype",
            ),
        ),
    ]
