# Generated by Django 5.2.4 on 2026-04-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0006_threadpullcost"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThreadXPLockedLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveSmallIntegerField(unique=True)),
                ("xp_cost", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ("level",),
            },
        ),
    ]
