# Generated by Django 5.2.14 on 2026-06-02 00:30

from decimal import Decimal

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0007_level_power_config"),
        ("room_features", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SanctumDetails",
            fields=[
                (
                    "feature_instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="sanctum_details",
                        serialize=False,
                        to="room_features.roomfeatureinstance",
                    ),
                ),
                (
                    "owner_mode",
                    models.CharField(
                        choices=[
                            ("PERSONAL", "Personal (Persona-owned home)"),
                            ("COVENANT", "Covenant (Organization-owned sacred ground)"),
                        ],
                        help_text="Denormalized from the Building's owner type at install time. Re-synced by the ownership-transfer service when the Building's ownership changes. PERSONAL Sanctums use ``PERSONAL_OWN`` / ``HELPER`` thread slots; COVENANT Sanctums use ``COVENANT`` slots.",
                        max_length=10,
                    ),
                ),
                (
                    "last_homecoming_ritual_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set on each successful Homecoming. Soft cooldown + UI display.",
                        null=True,
                    ),
                ),
                (
                    "last_purging_ritual_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set on each successful Purging. UI display + audit.",
                        null=True,
                    ),
                ),
                (
                    "pending_sacrifice_overflow",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Homecoming sacrifice that exceeded the per-Sanctum cap (owner Path-level × 10 for Personal). Held in escrow; absorbed by future Homecoming/cron when the cap rises.",
                        max_digits=12,
                    ),
                ),
                (
                    "resonance_type",
                    models.ForeignKey(
                        help_text="The resonance this Sanctum is consecrated to. Income payouts (via the cron tick) target this type; Ritual of Homecoming rows are created against this type; Ritual of Purging changes it.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sanctums",
                        to="magic.resonance",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
