# Generated by Django 5.2.4 on 2026-02-01 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0007_update_gift_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the technique (not unique - different characters can have same name).",
                        max_length=200,
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="The level of this technique (determines tier).",
                    ),
                ),
                (
                    "anima_cost",
                    models.PositiveIntegerField(help_text="Anima cost to use this technique."),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what this technique does."
                    ),
                ),
                (
                    "effect_type",
                    models.ForeignKey(
                        help_text="The type of effect this technique produces.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="techniques",
                        to="magic.effecttype",
                    ),
                ),
                (
                    "gift",
                    models.ForeignKey(
                        help_text="The gift this technique belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="techniques",
                        to="magic.gift",
                    ),
                ),
                (
                    "restrictions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Restrictions applied to this technique for power bonuses.",
                        related_name="techniques",
                        to="magic.restriction",
                    ),
                ),
                (
                    "style",
                    models.ForeignKey(
                        help_text="The style of this technique (restricted by Path).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="techniques",
                        to="magic.techniquestyle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technique",
                "verbose_name_plural": "Techniques",
            },
        ),
    ]
