# Generated by Django 5.2.4 on 2026-04-19 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0008_threadpulleffect"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImbuingProseTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TRAIT", "Trait"),
                            ("TECHNIQUE", "Technique"),
                            ("ITEM", "Item"),
                            ("ROOM", "Room"),
                            ("RELATIONSHIP_TRACK", "Relationship Track"),
                            ("RELATIONSHIP_CAPSTONE", "Relationship Capstone"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("prose", models.TextField()),
                (
                    "resonance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="imbuing_prose",
                        to="magic.resonance",
                    ),
                ),
            ],
            options={
                "unique_together": {("resonance", "target_kind")},
            },
        ),
    ]
