# Generated by Django 5.2.4 on 2026-04-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conditions", "0002_initial"),
        ("flows", "0008_remove_triggerdefinition_event_and_more"),
        ("magic", "0010_ritual_ritualcomponentrequirement"),
        ("mechanics", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ritual",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("execution_kind", "SERVICE"),
                        models.Q(("service_function_path", ""), _negated=True),
                        ("flow__isnull", True),
                    ),
                    models.Q(
                        ("execution_kind", "FLOW"),
                        ("service_function_path", ""),
                        ("flow__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ritual_execution_payload",
            ),
        ),
        migrations.AddConstraint(
            model_name="threadpulleffect",
            constraint=models.UniqueConstraint(
                fields=("target_kind", "resonance", "tier", "min_thread_level"),
                name="threadpulleffect_lookup_key",
            ),
        ),
    ]
