# Generated by Django 5.2.14 on 2026-06-02 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("character_sheets", "0003_initial"),
        ("evennia_extensions", "0001_initial"),
        ("items", "0003_iteminstance_lore_value_and_more"),
        ("magic", "0010_sanctuminstallparams"),
        ("projects", "0001_initial"),
        ("room_features", "0002_roomfeaturekind_install_mechanism_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SanctumPendingPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pending_weaving",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Accumulated income from SANCTUM_WEAVING source. Drained on absorb.",
                    ),
                ),
                (
                    "pending_owner_bonus",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Accumulated income from SANCTUM_OWNER_BONUS source. Drained on absorb.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Bumped on each cron-tick accumulation. UI 'last accrual' display.",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="sanctuminstallparams",
            name="progression_details",
        ),
        migrations.RemoveField(
            model_name="sanctuminstallparams",
            name="resonance_type",
        ),
        migrations.AddField(
            model_name="sanctumdetails",
            name="founder_character_sheet",
            field=models.ForeignKey(
                blank=True,
                help_text="The CharacterSheet of the witch who performed the Sanctification ritual that founded this Sanctum. For PERSONAL Sanctums, this is the ongoing owner; for COVENANT, this is historical identity (the ongoing authority is the Covenant Organization). Used to differentiate founder-vs-non-founder Dissolution checks (non-founder = harder difficulty + larger botch consequences). Plan 4 §F revised 2026-06-03.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="founded_sanctums",
                to="character_sheets.charactersheet",
            ),
        ),
        migrations.AlterField(
            model_name="resonancegrant",
            name="source",
            field=models.CharField(
                choices=[
                    ("POSE_ENDORSEMENT", "Pose endorsement"),
                    ("SCENE_ENTRY", "Scene entry endorsement"),
                    ("ROOM_RESIDENCE", "Room residence trickle"),
                    ("OUTFIT_TRICKLE", "Outfit trickle"),
                    ("STAFF_GRANT", "Staff grant"),
                    ("SANCTUM_WEAVING", "Sanctum weaving payout"),
                    ("SANCTUM_OWNER_BONUS", "Sanctum owner/member bonus"),
                    ("PROJECT_CONTRIBUTION", "Project contribution payout"),
                    ("SANCTUM_DISSOLUTION_RECOVERY", "Sanctum dissolution recovery"),
                ],
                help_text="Discriminator. Identifies which source_* FK is populated.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="sanctumdetails",
            name="owner_mode",
            field=models.CharField(
                choices=[
                    ("PERSONAL", "Personal (Persona-owned home)"),
                    ("COVENANT", "Covenant (Organization-owned sacred ground)"),
                ],
                help_text="PERSONAL Sanctums use ``PERSONAL_OWN`` / ``HELPER`` thread slots; COVENANT Sanctums use ``COVENANT`` slots. Set at Sanctification by the ritual variant performed.",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="resonancegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source", "SANCTUM_DISSOLUTION_RECOVERY"),
                        ("source_sanctum_details__isnull", False),
                        ("source_room_profile__isnull", True),
                        ("source_staff_account__isnull", True),
                        ("source_pose_endorsement__isnull", True),
                        ("source_scene_entry_endorsement__isnull", True),
                        ("outfit_item_facet__isnull", True),
                        ("source_project__isnull", True),
                    ),
                    models.Q(("source", "SANCTUM_DISSOLUTION_RECOVERY"), _negated=True),
                    _connector="OR",
                ),
                name="res_grant_sanctum_dissolution_recovery_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="sanctumdetails",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("founder_character_sheet__isnull", False),
                    ("owner_mode", "PERSONAL"),
                ),
                fields=("founder_character_sheet",),
                name="sanctum_details_one_personal_per_character_sheet",
            ),
        ),
        migrations.AddField(
            model_name="sanctumpendingpayout",
            name="sanctum",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pending_payouts",
                to="magic.sanctumdetails",
            ),
        ),
        migrations.AddField(
            model_name="sanctumpendingpayout",
            name="weaver_character_sheet",
            field=models.ForeignKey(
                help_text="The CharacterSheet of the weaver whose income is accumulating. One row per (sanctum, weaver) pair.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sanctum_pending_payouts",
                to="character_sheets.charactersheet",
            ),
        ),
        migrations.DeleteModel(
            name="SanctumInstallParams",
        ),
        migrations.AddConstraint(
            model_name="sanctumpendingpayout",
            constraint=models.UniqueConstraint(
                fields=("sanctum", "weaver_character_sheet"),
                name="sanctum_pending_payout_unique_per_weaver",
            ),
        ),
    ]
