# Generated by Django 5.2.4 on 2026-04-20 00:07

from decimal import Decimal

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0001_initial"),
        ("magic", "0013_threadlevelunlock"),
        ("mechanics", "0001_initial"),
        ("relationships", "0001_initial"),
        ("traits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThreadWeavingUnlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_kind",
                    models.CharField(
                        choices=[
                            ("TRAIT", "Trait"),
                            ("TECHNIQUE", "Technique"),
                            ("ITEM", "Item"),
                            ("ROOM", "Room"),
                            ("RELATIONSHIP_TRACK", "Relationship Track"),
                            ("RELATIONSHIP_CAPSTONE", "Relationship Capstone"),
                        ],
                        help_text="Discriminator selecting which unlock_* field is populated.",
                        max_length=32,
                    ),
                ),
                (
                    "unlock_item_typeclass_path",
                    models.CharField(
                        blank=True,
                        help_text="Set when target_kind=ITEM; typeclass path string.",
                        max_length=255,
                    ),
                ),
                (
                    "xp_cost",
                    models.PositiveIntegerField(
                        help_text="Base XP cost; multiplied by out_of_path_multiplier when out-of-Path."
                    ),
                ),
                (
                    "out_of_path_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.0"),
                        help_text="Cost multiplier applied when buyer's Path is not in `paths`.",
                        max_digits=4,
                    ),
                ),
                (
                    "paths",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Paths that treat this unlock as in-band (full xp_cost).",
                        related_name="thread_weaving_unlocks",
                        to="classes.path",
                    ),
                ),
                (
                    "unlock_gift",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when target_kind=TECHNIQUE; covers all techniques under Gift.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thread_weaving_unlocks",
                        to="magic.gift",
                    ),
                ),
                (
                    "unlock_room_property",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when target_kind=ROOM; rooms with this Property.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thread_weaving_unlocks",
                        to="mechanics.property",
                    ),
                ),
                (
                    "unlock_track",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when target_kind=RELATIONSHIP_TRACK; per-track unlock.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thread_weaving_unlocks",
                        to="relationships.relationshiptrack",
                    ),
                ),
                (
                    "unlock_trait",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when target_kind=TRAIT; null otherwise.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thread_weaving_unlocks",
                        to="traits.trait",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("target_kind", "TRAIT")),
                        fields=("unlock_trait",),
                        name="unique_threadweaving_unlock_trait",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("target_kind", "TECHNIQUE")),
                        fields=("unlock_gift",),
                        name="unique_threadweaving_unlock_gift",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("target_kind", "ITEM")),
                        fields=("unlock_item_typeclass_path",),
                        name="unique_threadweaving_unlock_item",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("target_kind", "ROOM")),
                        fields=("unlock_room_property",),
                        name="unique_threadweaving_unlock_room",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("target_kind", "RELATIONSHIP_TRACK")),
                        fields=("unlock_track",),
                        name="unique_threadweaving_unlock_track",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("target_kind", "TRAIT"), _negated=True),
                            models.Q(
                                ("unlock_trait__isnull", False),
                                ("unlock_gift__isnull", True),
                                ("unlock_item_typeclass_path", ""),
                                ("unlock_room_property__isnull", True),
                                ("unlock_track__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="threadweaving_trait_payload",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("target_kind", "TECHNIQUE"), _negated=True),
                            models.Q(
                                ("unlock_trait__isnull", True),
                                ("unlock_gift__isnull", False),
                                ("unlock_item_typeclass_path", ""),
                                ("unlock_room_property__isnull", True),
                                ("unlock_track__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="threadweaving_technique_payload",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("target_kind", "ITEM"), _negated=True),
                            models.Q(
                                ("unlock_trait__isnull", True),
                                ("unlock_gift__isnull", True),
                                models.Q(("unlock_item_typeclass_path", ""), _negated=True),
                                ("unlock_room_property__isnull", True),
                                ("unlock_track__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="threadweaving_item_payload",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("target_kind", "ROOM"), _negated=True),
                            models.Q(
                                ("unlock_trait__isnull", True),
                                ("unlock_gift__isnull", True),
                                ("unlock_item_typeclass_path", ""),
                                ("unlock_room_property__isnull", False),
                                ("unlock_track__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="threadweaving_room_payload",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("target_kind", "RELATIONSHIP_TRACK"), _negated=True),
                            models.Q(
                                ("unlock_trait__isnull", True),
                                ("unlock_gift__isnull", True),
                                ("unlock_item_typeclass_path", ""),
                                ("unlock_room_property__isnull", True),
                                ("unlock_track__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="threadweaving_track_payload",
                    ),
                ],
            },
        ),
    ]
