# Generated by Django 5.2.14 on 2026-06-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magic", "0018_rename_ritual_check_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="techniquedamageprofile",
            name="uses_equipped_weapon",
            field=models.BooleanField(
                default=False,
                help_text="When True, the wielder's equipped-weapon effective damage is added to this profile's budget and its damage_type fills in when null.",
            ),
        ),
    ]
