# Generated by Django 5.2.14 on 2026-06-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0019_magicprogressionmilestone"),
    ]

    operations = [
        migrations.AddField(
            model_name="technique",
            name="combo_opening_probing",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="If set, this technique used as a passive grants this much probing to engaged opponents when it resolves (feeds combo minimum_probing). None means the technique is not a combo-opening passive.",
                null=True,
            ),
        ),
    ]
