# Generated by Django 5.2.4 on 2026-04-23 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("evennia_extensions", "0001_initial"),
        ("magic", "0022_resonancegainconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomAuraProfile",
            fields=[
                (
                    "room_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="room_aura_profile",
                        serialize=False,
                        to="evennia_extensions.roomprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
