# Generated by Django 5.2.4 on 2026-04-23 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0023_roomauraprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomResonance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resonance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="room_tags",
                        to="magic.resonance",
                    ),
                ),
                (
                    "room_aura_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_resonances",
                        to="magic.roomauraprofile",
                    ),
                ),
                (
                    "set_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff/player who tagged this resonance.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("room_aura_profile", "resonance"),
                        name="unique_room_resonance_per_profile",
                    )
                ],
            },
        ),
    ]
