# Generated by Django 5.2.14 on 2026-06-14 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character_sheets", "0005_charactersheet_max_active_npc_missions"),
        ("items", "0012_fashionpresentation"),
        ("magic", "0023_alter_poseendorsement_endorsee_sheet_and_more"),
        ("scenes", "0021_persona_prestige_from_fashion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PresentationEndorsement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Per-judge weight (reserved for taste-authority scaling).",
                    ),
                ),
                (
                    "endorsee_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_received",
                        to="character_sheets.charactersheet",
                    ),
                ),
                (
                    "endorser_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_given",
                        to="character_sheets.charactersheet",
                    ),
                ),
                (
                    "persona_snapshot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Endorsee's persona at endorsement time — masquerade audit.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scenes.persona",
                    ),
                ),
                (
                    "presentation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endorsements",
                        to="items.fashionpresentation",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("endorser_sheet", "presentation"),
                        name="unique_presentation_endorsement_per_judge",
                    )
                ],
            },
        ),
    ]
