# Generated by Django 5.2.14 on 2026-06-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0026_alter_resonancegrant_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="resonancegainconfig",
            name="entry_flourish_grant",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Flat resonance grant awarded to a character when they perform a successful entry flourish (Entrance action with resonance declared).",
            ),
        ),
    ]
