# Generated by Django 5.2.4 on 2026-04-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0031_corruptionconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resonancegrant",
            name="source",
            field=models.CharField(
                choices=[
                    ("POSE_ENDORSEMENT", "Pose endorsement"),
                    ("SCENE_ENTRY", "Scene entry endorsement"),
                    ("ROOM_RESIDENCE", "Room residence trickle"),
                    ("OUTFIT_TRICKLE", "Outfit trickle"),
                    ("STAFF_GRANT", "Staff grant"),
                ],
                help_text="Discriminator. Identifies which source_* FK is populated.",
                max_length=24,
            ),
        ),
    ]
