# Generated by Django 5.2.14 on 2026-06-17 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0018_itemtemplate_style_capacity_and_more"),
        ("magic", "0031_dramaticmomenttype_per_scene_cap_archetypes"),
    ]

    operations = [
        migrations.CreateModel(
            name="MotifResonanceStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motif_resonance",
                    models.ForeignKey(
                        help_text="The motif resonance this style belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style_assignments",
                        to="magic.motifresonance",
                    ),
                ),
                (
                    "style",
                    models.ForeignKey(
                        help_text="The aesthetic style.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="motif_usages",
                        to="items.style",
                    ),
                ),
            ],
            options={
                "verbose_name": "Motif Resonance Style",
                "verbose_name_plural": "Motif Resonance Styles",
                "unique_together": {("motif_resonance", "style")},
            },
        ),
    ]
