# Generated by Django 5.2.4 on 2026-04-28 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("character_sheets", "0004_charactersheet_current_residence"),
        ("covenants", "0003_charactercovenantrole"),
        ("magic", "0034_remove_thread_uniq_thread_facet_and_more"),
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
        ("relationships", "0002_soul_tether_fields"),
        ("traits", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="thread",
            name="thread_trait_payload",
        ),
        migrations.RemoveConstraint(
            model_name="thread",
            name="thread_technique_payload",
        ),
        migrations.RemoveConstraint(
            model_name="thread",
            name="thread_item_payload",
        ),
        migrations.RemoveConstraint(
            model_name="thread",
            name="thread_room_payload",
        ),
        migrations.RemoveConstraint(
            model_name="thread",
            name="thread_rel_track_payload",
        ),
        migrations.RemoveConstraint(
            model_name="thread",
            name="thread_rel_capstone_payload",
        ),
        migrations.RemoveConstraint(
            model_name="thread",
            name="thread_facet_payload",
        ),
        migrations.AddField(
            model_name="thread",
            name="target_covenant_role",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when target_kind=COVENANT_ROLE; null otherwise.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="anchored_threads",
                to="covenants.covenantrole",
            ),
        ),
        migrations.AlterField(
            model_name="imbuingprosetemplate",
            name="target_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TRAIT", "Trait"),
                    ("TECHNIQUE", "Technique"),
                    ("FACET", "Facet"),
                    ("ITEM", "Item"),
                    ("ROOM", "Room"),
                    ("RELATIONSHIP_TRACK", "Relationship Track"),
                    ("RELATIONSHIP_CAPSTONE", "Relationship Capstone"),
                    ("COVENANT_ROLE", "Covenant Role"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="thread",
            name="target_kind",
            field=models.CharField(
                choices=[
                    ("TRAIT", "Trait"),
                    ("TECHNIQUE", "Technique"),
                    ("FACET", "Facet"),
                    ("ITEM", "Item"),
                    ("ROOM", "Room"),
                    ("RELATIONSHIP_TRACK", "Relationship Track"),
                    ("RELATIONSHIP_CAPSTONE", "Relationship Capstone"),
                    ("COVENANT_ROLE", "Covenant Role"),
                ],
                help_text="Discriminator selecting which target_* FK is populated.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="threadpulleffect",
            name="target_kind",
            field=models.CharField(
                choices=[
                    ("TRAIT", "Trait"),
                    ("TECHNIQUE", "Technique"),
                    ("FACET", "Facet"),
                    ("ITEM", "Item"),
                    ("ROOM", "Room"),
                    ("RELATIONSHIP_TRACK", "Relationship Track"),
                    ("RELATIONSHIP_CAPSTONE", "Relationship Capstone"),
                    ("COVENANT_ROLE", "Covenant Role"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="threadweavingunlock",
            name="target_kind",
            field=models.CharField(
                choices=[
                    ("TRAIT", "Trait"),
                    ("TECHNIQUE", "Technique"),
                    ("FACET", "Facet"),
                    ("ITEM", "Item"),
                    ("ROOM", "Room"),
                    ("RELATIONSHIP_TRACK", "Relationship Track"),
                    ("RELATIONSHIP_CAPSTONE", "Relationship Capstone"),
                    ("COVENANT_ROLE", "Covenant Role"),
                ],
                help_text="Discriminator selecting which unlock_* field is populated.",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="thread",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("target_kind", "TRAIT"), _negated=True),
                    models.Q(
                        ("target_trait__isnull", False),
                        ("target_technique__isnull", True),
                        ("target_object__isnull", True),
                        ("target_relationship_track__isnull", True),
                        ("target_capstone__isnull", True),
                        ("target_facet__isnull", True),
                        ("target_covenant_role__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="thread_trait_payload",
            ),
        ),
        migrations.AddConstraint(
            model_name="thread",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("target_kind", "TECHNIQUE"), _negated=True),
                    models.Q(
                        ("target_trait__isnull", True),
                        ("target_technique__isnull", False),
                        ("target_object__isnull", True),
                        ("target_relationship_track__isnull", True),
                        ("target_capstone__isnull", True),
                        ("target_facet__isnull", True),
                        ("target_covenant_role__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="thread_technique_payload",
            ),
        ),
        migrations.AddConstraint(
            model_name="thread",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("target_kind", "ITEM"), _negated=True),
                    models.Q(
                        ("target_trait__isnull", True),
                        ("target_technique__isnull", True),
                        ("target_object__isnull", False),
                        ("target_relationship_track__isnull", True),
                        ("target_capstone__isnull", True),
                        ("target_facet__isnull", True),
                        ("target_covenant_role__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="thread_item_payload",
            ),
        ),
        migrations.AddConstraint(
            model_name="thread",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("target_kind", "ROOM"), _negated=True),
                    models.Q(
                        ("target_trait__isnull", True),
                        ("target_technique__isnull", True),
                        ("target_object__isnull", False),
                        ("target_relationship_track__isnull", True),
                        ("target_capstone__isnull", True),
                        ("target_facet__isnull", True),
                        ("target_covenant_role__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="thread_room_payload",
            ),
        ),
        migrations.AddConstraint(
            model_name="thread",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("target_kind", "RELATIONSHIP_TRACK"), _negated=True),
                    models.Q(
                        ("target_trait__isnull", True),
                        ("target_technique__isnull", True),
                        ("target_object__isnull", True),
                        ("target_relationship_track__isnull", False),
                        ("target_capstone__isnull", True),
                        ("target_facet__isnull", True),
                        ("target_covenant_role__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="thread_rel_track_payload",
            ),
        ),
        migrations.AddConstraint(
            model_name="thread",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("target_kind", "RELATIONSHIP_CAPSTONE"), _negated=True),
                    models.Q(
                        ("target_trait__isnull", True),
                        ("target_technique__isnull", True),
                        ("target_object__isnull", True),
                        ("target_relationship_track__isnull", True),
                        ("target_capstone__isnull", False),
                        ("target_facet__isnull", True),
                        ("target_covenant_role__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="thread_rel_capstone_payload",
            ),
        ),
        migrations.AddConstraint(
            model_name="thread",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("target_kind", "FACET"), _negated=True),
                    models.Q(
                        ("target_facet__isnull", False),
                        ("target_trait__isnull", True),
                        ("target_technique__isnull", True),
                        ("target_object__isnull", True),
                        ("target_relationship_track__isnull", True),
                        ("target_capstone__isnull", True),
                        ("target_covenant_role__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="thread_facet_payload",
            ),
        ),
        migrations.AddConstraint(
            model_name="thread",
            constraint=models.UniqueConstraint(
                condition=models.Q(("retired_at__isnull", True), ("target_kind", "COVENANT_ROLE")),
                fields=("owner", "target_covenant_role"),
                name="uniq_thread_covenant_role_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="thread",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("target_kind", "COVENANT_ROLE"), _negated=True),
                    models.Q(
                        ("target_covenant_role__isnull", False),
                        ("target_trait__isnull", True),
                        ("target_technique__isnull", True),
                        ("target_object__isnull", True),
                        ("target_relationship_track__isnull", True),
                        ("target_capstone__isnull", True),
                        ("target_facet__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="thread_covenant_role_payload",
            ),
        ),
    ]
