# Generated by Django 5.2.4 on 2026-04-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0001_initial"),
        ("magic", "0036_remove_resonancegrant_res_grant_residence_shape_and_more"),
        ("mechanics", "0001_initial"),
        ("relationships", "0002_soul_tether_fields"),
        ("traits", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="characterfacet",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="characterfacet",
            name="character",
        ),
        migrations.RemoveField(
            model_name="characterfacet",
            name="facet",
        ),
        migrations.RemoveField(
            model_name="characterfacet",
            name="resonance",
        ),
        migrations.RemoveConstraint(
            model_name="thread",
            name="uniq_thread_item",
        ),
        migrations.RemoveConstraint(
            model_name="thread",
            name="thread_item_payload",
        ),
        migrations.RemoveConstraint(
            model_name="threadweavingunlock",
            name="unique_threadweaving_unlock_item",
        ),
        migrations.RemoveConstraint(
            model_name="threadweavingunlock",
            name="threadweaving_trait_payload",
        ),
        migrations.RemoveConstraint(
            model_name="threadweavingunlock",
            name="threadweaving_technique_payload",
        ),
        migrations.RemoveConstraint(
            model_name="threadweavingunlock",
            name="threadweaving_item_payload",
        ),
        migrations.RemoveConstraint(
            model_name="threadweavingunlock",
            name="threadweaving_room_payload",
        ),
        migrations.RemoveConstraint(
            model_name="threadweavingunlock",
            name="threadweaving_track_payload",
        ),
        migrations.RemoveField(
            model_name="threadweavingunlock",
            name="unlock_item_typeclass_path",
        ),
        migrations.AlterField(
            model_name="imbuingprosetemplate",
            name="target_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TRAIT", "Trait"),
                    ("TECHNIQUE", "Technique"),
                    ("FACET", "Facet"),
                    ("ROOM", "Room"),
                    ("RELATIONSHIP_TRACK", "Relationship Track"),
                    ("RELATIONSHIP_CAPSTONE", "Relationship Capstone"),
                    ("COVENANT_ROLE", "Covenant Role"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="thread",
            name="target_kind",
            field=models.CharField(
                choices=[
                    ("TRAIT", "Trait"),
                    ("TECHNIQUE", "Technique"),
                    ("FACET", "Facet"),
                    ("ROOM", "Room"),
                    ("RELATIONSHIP_TRACK", "Relationship Track"),
                    ("RELATIONSHIP_CAPSTONE", "Relationship Capstone"),
                    ("COVENANT_ROLE", "Covenant Role"),
                ],
                help_text="Discriminator selecting which target_* FK is populated.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="threadpulleffect",
            name="target_kind",
            field=models.CharField(
                choices=[
                    ("TRAIT", "Trait"),
                    ("TECHNIQUE", "Technique"),
                    ("FACET", "Facet"),
                    ("ROOM", "Room"),
                    ("RELATIONSHIP_TRACK", "Relationship Track"),
                    ("RELATIONSHIP_CAPSTONE", "Relationship Capstone"),
                    ("COVENANT_ROLE", "Covenant Role"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="threadweavingunlock",
            name="target_kind",
            field=models.CharField(
                choices=[
                    ("TRAIT", "Trait"),
                    ("TECHNIQUE", "Technique"),
                    ("FACET", "Facet"),
                    ("ROOM", "Room"),
                    ("RELATIONSHIP_TRACK", "Relationship Track"),
                    ("RELATIONSHIP_CAPSTONE", "Relationship Capstone"),
                    ("COVENANT_ROLE", "Covenant Role"),
                ],
                help_text="Discriminator selecting which unlock_* field is populated.",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="threadweavingunlock",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("target_kind", "TRAIT"), _negated=True),
                    models.Q(
                        ("unlock_trait__isnull", False),
                        ("unlock_gift__isnull", True),
                        ("unlock_room_property__isnull", True),
                        ("unlock_track__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="threadweaving_trait_payload",
            ),
        ),
        migrations.AddConstraint(
            model_name="threadweavingunlock",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("target_kind", "TECHNIQUE"), _negated=True),
                    models.Q(
                        ("unlock_trait__isnull", True),
                        ("unlock_gift__isnull", False),
                        ("unlock_room_property__isnull", True),
                        ("unlock_track__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="threadweaving_technique_payload",
            ),
        ),
        migrations.AddConstraint(
            model_name="threadweavingunlock",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("target_kind", "ROOM"), _negated=True),
                    models.Q(
                        ("unlock_trait__isnull", True),
                        ("unlock_gift__isnull", True),
                        ("unlock_room_property__isnull", False),
                        ("unlock_track__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="threadweaving_room_payload",
            ),
        ),
        migrations.AddConstraint(
            model_name="threadweavingunlock",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("target_kind", "RELATIONSHIP_TRACK"), _negated=True),
                    models.Q(
                        ("unlock_trait__isnull", True),
                        ("unlock_gift__isnull", True),
                        ("unlock_room_property__isnull", True),
                        ("unlock_track__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="threadweaving_track_payload",
            ),
        ),
        migrations.DeleteModel(
            name="CharacterFacet",
        ),
    ]
