# Generated by Django 5.2.14 on 2026-06-19 00:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0036_standingcapband"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aurapowerconfig",
            name="resonance_standing_cap",
        ),
    ]
