# Generated by Django 5.2.14 on 2026-06-19 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0036_remove_thread_uniq_thread_room_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SoulTetherConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anima_cost_per_unit", models.PositiveSmallIntegerField(default=2)),
                ("fatigue_cost_per_unit", models.PositiveSmallIntegerField(default=1)),
                (
                    "per_scene_cap_hard_max",
                    models.PositiveSmallIntegerField(default=20),
                ),
                (
                    "per_scene_cap_level_mult",
                    models.PositiveSmallIntegerField(default=2),
                ),
                ("per_scene_cap_base", models.PositiveSmallIntegerField(default=5)),
                ("hollow_max_level_mult", models.PositiveSmallIntegerField(default=10)),
                ("rescue_strain_stage3", models.PositiveSmallIntegerField(default=5)),
                ("rescue_strain_stage4", models.PositiveSmallIntegerField(default=10)),
                ("rescue_strain_stage5", models.PositiveSmallIntegerField(default=18)),
                (
                    "rescue_resonance_stage3",
                    models.PositiveSmallIntegerField(default=10),
                ),
                (
                    "rescue_resonance_stage4",
                    models.PositiveSmallIntegerField(default=20),
                ),
                (
                    "rescue_resonance_stage5",
                    models.PositiveSmallIntegerField(default=35),
                ),
                (
                    "rescue_budget_base_stage3",
                    models.PositiveSmallIntegerField(default=60),
                ),
                (
                    "rescue_budget_base_stage4",
                    models.PositiveSmallIntegerField(default=120),
                ),
                (
                    "rescue_budget_base_stage5",
                    models.PositiveSmallIntegerField(default=250),
                ),
                (
                    "rescue_budget_base_mult_tenths",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Base budget multiplier in tenths (10 → 1.0).",
                    ),
                ),
                (
                    "rescue_budget_success_mult_tenths",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Per-success-level budget multiplier in tenths (5 → 0.5).",
                    ),
                ),
                (
                    "rescue_budget_thread_mult_hundredths",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Per-thread-level budget multiplier in hundredths (5 → 0.05).",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="soul_tether_config_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
