# Generated by Django 5.2.14 on 2026-06-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0037_remove_aurapowerconfig_resonance_standing_cap"),
        (
            "societies",
            "0017_remove_rankingdisplay_societies_ranking_display_scope_matches_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dramaticmomenttype",
            name="archetypes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Philosophical archetypes forwarded to fire_renown_award.",
                related_name="%(class)s_renown_configs",
                to="societies.philosophicalarchetype",
            ),
        ),
    ]
