# Generated by Django 5.2.4 on 2026-05-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0039_techniquedamageprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="hollow_current",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Soul Tether Hollow capacity (Spec B §5). Only meaningful for RELATIONSHIP_CAPSTONE Sinner-side Threads. Drains on corruption redirect; refills via Sineating. Other Threads ignore this field.",
            ),
        ),
    ]
