# Generated by Django 5.2.14 on 2026-06-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0043_pendingentryflourishoffer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThreadSurvivabilityTuning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vital_target",
                    models.CharField(
                        choices=[
                            ("MAX_HEALTH", "Max Health"),
                            ("DAMAGE_TAKEN_REDUCTION", "Damage Taken Reduction"),
                        ],
                        help_text="Which survivability vector this row tunes.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "coefficient",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Linear multiplier on the breadth×depth investment score S (default 1).",
                    ),
                ),
                (
                    "cap",
                    models.PositiveSmallIntegerField(
                        help_text="Ceiling the baseline asymptotes toward at very high investment."
                    ),
                ),
                (
                    "half_saturation",
                    models.PositiveSmallIntegerField(
                        help_text="Investment score S at which the baseline reaches half of cap."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
