# Generated by Django 5.2.14 on 2026-06-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0044_threadsurvivabilitytuning"),
    ]

    operations = [
        migrations.AddField(
            model_name="ritual",
            name="draft_validator_path",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
