# Generated by Django 5.2.14 on 2026-06-20 07:46

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0045_alter_threadpulleffect_vital_target_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="threadsurvivabilitytuning",
            name="coherence_max_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("2.00"),
                help_text="Ceiling on the per-thread coherence multiplier (1.00 = inert).",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="threadsurvivabilitytuning",
            name="coherence_scale",
            field=models.PositiveSmallIntegerField(
                default=50,
                help_text="Per-resonance coherence bonus that yields +1.0 to a thread's depth multiplier. 0 disables the fashion/motif amplifier for this target.",
            ),
        ),
    ]
