# Generated by Django 5.2.14 on 2026-06-21 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0048_technique_target_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="RitualLiturgy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opening_call",
                    models.TextField(
                        help_text="The officiant's spoken invocation at the opening of the rite."
                    ),
                ),
                (
                    "ritual",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liturgy",
                        to="magic.ritual",
                    ),
                ),
            ],
            options={
                "verbose_name": "ritual liturgy",
                "verbose_name_plural": "ritual liturgies",
            },
        ),
    ]
