# Generated by Django 5.2.14 on 2026-06-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0053_charactertechnique_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="gift",
            name="kind",
            field=models.CharField(
                choices=[
                    ("MAJOR", "Major (CG-chosen)"),
                    ("MINOR", "Minor (shared, acquirable)"),
                ],
                db_index=True,
                default="MAJOR",
                help_text="Major: the one CG-chosen gift. Minor: shared/acquirable gifts that species abilities and in-play powers are delivered as (ADR-0050).",
                max_length=16,
            ),
        ),
    ]
