# Generated by Django 5.2.4 on 2026-05-14 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character_sheets", "0004_charactersheet_current_residence"),
        ("evennia_extensions", "0002_roomprofile_is_outdoor"),
        ("items", "0004_itemtemplate_is_wardrobe_outfit_outfitslot_and_more"),
        ("magic", "0059_backfill_resonancegrant_source_room_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="resonancegrant",
            name="res_grant_staff_shape",
        ),
        migrations.RemoveConstraint(
            model_name="resonancegrant",
            name="res_grant_pose_endorsement_shape",
        ),
        migrations.RemoveConstraint(
            model_name="resonancegrant",
            name="res_grant_scene_entry_shape",
        ),
        migrations.RemoveConstraint(
            model_name="resonancegrant",
            name="res_grant_outfit_trickle_shape",
        ),
        migrations.RemoveConstraint(
            model_name="resonancegrant",
            name="res_grant_residence_shape",
        ),
        migrations.RemoveField(
            model_name="resonancegrant",
            name="source_room_aura_profile",
        ),
        migrations.AddConstraint(
            model_name="resonancegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source", "ROOM_RESIDENCE"),
                        ("source_room_profile__isnull", False),
                        ("source_staff_account__isnull", True),
                        ("source_pose_endorsement__isnull", True),
                        ("source_scene_entry_endorsement__isnull", True),
                        ("outfit_item_facet__isnull", True),
                    ),
                    models.Q(("source", "ROOM_RESIDENCE"), _negated=True),
                    _connector="OR",
                ),
                name="res_grant_residence_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="resonancegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source", "STAFF_GRANT"),
                        ("source_room_profile__isnull", True),
                        ("source_pose_endorsement__isnull", True),
                        ("source_scene_entry_endorsement__isnull", True),
                        ("outfit_item_facet__isnull", True),
                    ),
                    models.Q(("source", "STAFF_GRANT"), _negated=True),
                    _connector="OR",
                ),
                name="res_grant_staff_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="resonancegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source", "POSE_ENDORSEMENT"),
                        ("source_pose_endorsement__isnull", False),
                        ("source_room_profile__isnull", True),
                        ("source_staff_account__isnull", True),
                        ("source_scene_entry_endorsement__isnull", True),
                        ("outfit_item_facet__isnull", True),
                    ),
                    models.Q(("source", "POSE_ENDORSEMENT"), _negated=True),
                    _connector="OR",
                ),
                name="res_grant_pose_endorsement_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="resonancegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source", "SCENE_ENTRY"),
                        ("source_scene_entry_endorsement__isnull", False),
                        ("source_room_profile__isnull", True),
                        ("source_staff_account__isnull", True),
                        ("source_pose_endorsement__isnull", True),
                        ("outfit_item_facet__isnull", True),
                    ),
                    models.Q(("source", "SCENE_ENTRY"), _negated=True),
                    _connector="OR",
                ),
                name="res_grant_scene_entry_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="resonancegrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source", "OUTFIT_TRICKLE"),
                        ("outfit_item_facet__isnull", False),
                        ("source_room_profile__isnull", True),
                        ("source_staff_account__isnull", True),
                        ("source_pose_endorsement__isnull", True),
                        ("source_scene_entry_endorsement__isnull", True),
                    ),
                    models.Q(("source", "OUTFIT_TRICKLE"), _negated=True),
                    _connector="OR",
                ),
                name="res_grant_outfit_trickle_shape",
            ),
        ),
    ]
