# Generated by Django 5.2.14 on 2026-05-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0064_affinityinteraction_consequence_pool_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="technique",
            name="clash_capable",
            field=models.BooleanField(
                default=False,
                help_text="When True, this technique can be committed as a clash action. Drives clash-opportunity detection.",
            ),
        ),
    ]
