# Generated by Django 5.2.14 on 2026-06-30 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0067_alter_thread_target_technique_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="thread",
            name="uniq_thread_technique",
        ),
    ]
