# Generated by Django 5.2.14 on 2026-07-04 07:42

from decimal import Decimal

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "distinctions",
            "0004_remove_characterdistinction_visibility_override_and_more",
        ),
        ("magic", "0080_remove_resonancegrant_res_grant_residence_shape_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistinctionResonanceGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flat_amount_per_rank",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Flat resonance seeded per rank held in the distinction.",
                    ),
                ),
                (
                    "earn_rate_bonus_per_rank",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Earn-rate bonus per rank held in the distinction.",
                        max_digits=4,
                        validators=[django.core.validators.MaxValueValidator(Decimal("5.00"))],
                    ),
                ),
                (
                    "distinction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resonance_grants",
                        to="distinctions.distinction",
                    ),
                ),
                (
                    "resonance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="distinction_grants",
                        to="magic.resonance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distinction Resonance Grant",
                "verbose_name_plural": "Distinction Resonance Grants",
                "ordering": ["distinction_id", "resonance_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("distinction", "resonance"),
                        name="unique_distinction_resonance_grant",
                    )
                ],
            },
        ),
    ]
