# Generated by Django 5.2.14 on 2026-07-05 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("covenants", "0022_covenantrank_can_lead_rituals"),
        ("magic", "0086_threadcrossingthreshold"),
        (
            "societies",
            "0021_gangturfdetails_gangturftierthreshold_gangturfreputationaward",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ritualsessionreference",
            name="ritual_session_reference_exactly_one_ref",
        ),
        migrations.AddField(
            model_name="ritualsessionreference",
            name="ref_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ritualsessionreference_set",
                to="societies.organization",
            ),
        ),
        migrations.AlterField(
            model_name="ritualsessionreference",
            name="kind",
            field=models.CharField(
                choices=[
                    ("COVENANT", "Covenant"),
                    ("COVENANT_ROLE", "Covenant Role"),
                    ("ORGANIZATION", "Organization"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="ritualsessionreference",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("kind", "COVENANT"),
                        ("ref_covenant__isnull", False),
                        ("ref_covenant_role__isnull", True),
                        ("ref_organization__isnull", True),
                    ),
                    models.Q(
                        ("kind", "COVENANT_ROLE"),
                        ("ref_covenant__isnull", True),
                        ("ref_covenant_role__isnull", False),
                        ("ref_organization__isnull", True),
                    ),
                    models.Q(
                        ("kind", "ORGANIZATION"),
                        ("ref_covenant__isnull", True),
                        ("ref_covenant_role__isnull", True),
                        ("ref_organization__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ritual_session_reference_exactly_one_ref",
            ),
        ),
    ]
