# Generated by Django 5.2.14 on 2026-07-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0091_signature_crossing_gate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resonancegrant",
            name="source",
            field=models.CharField(
                choices=[
                    ("POSE_ENDORSEMENT", "Pose endorsement"),
                    ("SCENE_ENTRY", "Scene entry endorsement"),
                    ("ROOM_RESIDENCE", "Room residence trickle"),
                    ("OUTFIT_TRICKLE", "Outfit trickle"),
                    ("STAFF_GRANT", "Staff grant"),
                    ("SANCTUM_WEAVING", "Sanctum weaving payout"),
                    ("SANCTUM_OWNER_BONUS", "Sanctum owner/member bonus"),
                    ("PROJECT_CONTRIBUTION", "Project contribution payout"),
                    ("SANCTUM_DISSOLUTION_RECOVERY", "Sanctum dissolution recovery"),
                    ("ENTRY_FLOURISH", "Entry flourishing"),
                    ("DRAMATIC_MOMENT", "Dramatic moment"),
                    ("STYLE_PRESENTATION", "Style presentation"),
                    ("MISSION_REWARD", "Mission reward"),
                    ("MISSION_REPORT", "Mission report style"),
                    ("STAKE_REWARD", "Stake reward"),
                    ("DISTINCTION", "Distinction"),
                    ("COMBO_DISCOVERY", "Combo discovery"),
                ],
                help_text="Discriminator. Identifies which source_* FK is populated.",
                max_length=32,
            ),
        ),
    ]
