# Generated by Django 5.2.14 on 2026-07-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0094_charactertechnique_role_source_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TouchstoneCastConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "config_scale",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Per-tier bonus multiplier (integer-tenths: 10 = x1.0). Bonus = resonance_tier.tier_level * config_scale / 10.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Touchstone Cast Config",
                "verbose_name_plural": "Touchstone Cast Config",
            },
        ),
    ]
