# Generated by Django 5.2.14 on 2026-07-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0096_relationshipbondpulltuning_devotion_cap_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="technique",
            name="reach_hops",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="When reach=REACH_N, the maximum number of passable edges BFS may traverse. Ignored for SAME/ADJACENT/ANY.",
            ),
        ),
        migrations.AlterField(
            model_name="technique",
            name="reach",
            field=models.CharField(
                choices=[
                    ("same", "Same position"),
                    ("adjacent", "Adjacent position"),
                    ("any", "Anywhere in room"),
                    ("reach_n", "N-hop reach"),
                ],
                default="any",
                help_text="Positional reach: which positions this technique can target (SAME=melee, ADJACENT=reach, ANY=ranged).",
                max_length=20,
            ),
        ),
    ]
