# Generated by Django 5.2.14 on 2026-07-10 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("distinctions", "0005_alter_characterdistinction_origin"),
        ("magic", "0096_relationshipbondpulltuning_devotion_cap_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistinctionResonanceRankThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        help_text="Which rank of the distinction this threshold unlocks."
                    ),
                ),
                (
                    "lifetime_earned_threshold",
                    models.PositiveIntegerField(
                        help_text="CharacterResonance.lifetime_earned in this resonance required to reach the above rank."
                    ),
                ),
                (
                    "distinction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resonance_rank_thresholds",
                        to="distinctions.distinction",
                    ),
                ),
                (
                    "resonance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="distinction_rank_thresholds",
                        to="magic.resonance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distinction Resonance Rank Threshold",
                "verbose_name_plural": "Distinction Resonance Rank Thresholds",
                "ordering": ["distinction_id", "resonance_id", "rank"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("distinction", "resonance", "rank"),
                        name="unique_distinction_resonance_rank_threshold",
                    )
                ],
            },
        ),
    ]
