# Generated by Django 5.2.14 on 2026-07-11 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("evennia_extensions", "0009_exitprofile"),
        ("magic", "0100_dramaticmomenttype_suggest_on_technique_entrance_and_more"),
        ("scenes", "0050_sceneactionrequest_originated_as_entrance"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalAnchorKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this anchor kind (e.g. 'Mirror').",
                        max_length=80,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Player-facing description of this anchor kind.",
                    ),
                ),
                (
                    "arrival_verb",
                    models.CharField(
                        default="steps out of",
                        help_text="Verb phrase narrating arrival through an anchor of this kind.",
                        max_length=120,
                    ),
                ),
                (
                    "departure_verb",
                    models.CharField(
                        default="steps into",
                        help_text="Verb phrase narrating departure through an anchor of this kind.",
                        max_length=120,
                    ),
                ),
            ],
            options={
                "verbose_name": "Portal Anchor Kind",
                "verbose_name_plural": "Portal Anchor Kinds",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="technique",
            name="travel_anchor_kind",
            field=models.ForeignKey(
                blank=True,
                help_text="Set = this technique is a portal-travel technique through this anchor medium (#2222).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="travel_techniques",
                to="magic.portalanchorkind",
            ),
        ),
        migrations.CreateModel(
            name="PortalAnchor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this specific anchor (e.g. 'a tall silvered mirror').",
                        max_length=120,
                    ),
                ),
                (
                    "is_network_open",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this anchor is open to travel from other anchors of the same kind.",
                    ),
                ),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dissolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the anchor is dissolved; null = active.",
                        null=True,
                    ),
                ),
                (
                    "installed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Persona who installed this anchor, if known.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="scenes.persona",
                    ),
                ),
                (
                    "room_profile",
                    models.ForeignKey(
                        help_text="The room this anchor is installed in.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_anchors",
                        to="evennia_extensions.roomprofile",
                    ),
                ),
                (
                    "kind",
                    models.ForeignKey(
                        help_text="The medium of this anchor (e.g. Mirror, Doorway).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anchors",
                        to="magic.portalanchorkind",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portal Anchor",
                "verbose_name_plural": "Portal Anchors",
                "ordering": ["room_profile_id", "kind_id", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("dissolved_at__isnull", True)),
                        fields=("room_profile", "kind"),
                        name="portal_anchor_unique_active_room_kind",
                    )
                ],
            },
        ),
    ]
