# Generated by Django 5.2.15 on 2026-07-16 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("codex", "0004_alter_codexclue_unique_together_and_more"),
        ("magic", "0104_alter_fallredemptionconfig_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="effecttype",
            name="category",
            field=models.CharField(
                choices=[
                    ("attack", "Attack"),
                    ("defense", "Defense"),
                    ("buff", "Buff"),
                    ("debuff", "Debuff"),
                    ("utility", "Utility"),
                ],
                default="utility",
                help_text="Player-facing grouping (Offense/Defense/...) for CG and category-keyed modifiers.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="gift",
            name="codex_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="Lore entry this gift is bound to, if any.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gifts",
                to="codex.codexentry",
            ),
        ),
        migrations.AddField(
            model_name="technique",
            name="codex_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="Lore entry this technique is bound to, if any.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="techniques",
                to="codex.codexentry",
            ),
        ),
        migrations.CreateModel(
            name="TraditionGiftGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tradition_grants",
                        to="magic.gift",
                    ),
                ),
                (
                    "signature_techniques",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Curated subset of this gift's techniques available to characters picking this gift under this tradition.",
                        related_name="granted_by_tradition_gifts",
                        to="magic.technique",
                    ),
                ),
                (
                    "tradition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gift_grants",
                        to="magic.tradition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tradition Gift Grant",
                "verbose_name_plural": "Tradition Gift Grants",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tradition", "gift"), name="unique_tradition_gift_grant"
                    )
                ],
            },
        ),
    ]
