# Generated by Django 5.2.15 on 2026-07-18 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("codex", "0004_alter_codexclue_unique_together_and_more"),
        ("magic", "0112_alter_technique_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="resonance",
            name="codex_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="Lore entry this resonance is bound to, if any.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resonances",
                to="codex.codexentry",
            ),
        ),
    ]
