# Generated by Django 5.2.15 on 2026-07-23 20:37

from django.db import migrations, models
import django.db.models.deletion

import core.natural_keys


class Migration(migrations.Migration):
    dependencies = [
        ("conditions", "0023_conditioninstance_source_vow"),
        ("magic", "0121_alter_techniquefunctiontag_function"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechniqueTreatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_kind",
                    models.CharField(
                        choices=[
                            ("self", "Self"),
                            ("ally", "Ally"),
                            ("enemy", "Enemy"),
                        ],
                        default="ally",
                        max_length=16,
                    ),
                ),
                (
                    "minimum_success_level",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum success level required to perform this treatment.",
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatments",
                        to="magic.technique",
                    ),
                ),
                (
                    "treatment_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="technique_payloads",
                        to="conditions.treatmenttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technique Treatment",
                "verbose_name_plural": "Technique Treatments",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("technique", "treatment_template"),
                        name="unique_treatment_per_technique",
                    )
                ],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
    ]
