# Generated by Django 5.2.15 on 2026-07-25 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("character_sheets", "0013_charactersheet_durance_cohort_and_more"),
        ("game_clock", "0001_initial"),
        ("magic", "0127_technique_progress_config_fields"),
        ("roster", "0009_alter_rosterapplication_character"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechniqueProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points_accumulated",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Development points accumulated toward the technique.",
                    ),
                ),
                (
                    "total_required",
                    models.PositiveIntegerField(
                        help_text="Total development points required, snapshotted at creation."
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("assumed_alternate_self", "assuming an alternate self"),
                            ("reverted_alternate_self", "reverting to your true self"),
                            ("covenant_role_engaged", "taking up your covenant role"),
                            (
                                "covenant_role_disengaged",
                                "setting down your covenant role",
                            ),
                            ("character_creation", "your origins"),
                            ("path_advancement", "advancing into a new path"),
                            ("gift_acquisition", "acquiring a new gift"),
                            ("technique_grant", "studying a technique source"),
                            ("academy_training", "training at the Academy"),
                        ],
                        help_text="Provenance: how this meter was created.",
                        max_length=30,
                    ),
                ),
                (
                    "is_cross_path",
                    models.BooleanField(
                        default=False,
                        help_text="True when the teacher's Path.style differed from the learner's at creation. Drives the effective weekly cap.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technique_progress",
                        to="character_sheets.charactersheet",
                    ),
                ),
                (
                    "teacher_tenure",
                    models.ForeignKey(
                        blank=True,
                        help_text="Teacher RosterTenure when applicable; null for self-directed acquisition.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="technique_progress_taught",
                        to="roster.rostertenure",
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="progress_records",
                        to="magic.technique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technique Progress",
                "verbose_name_plural": "Technique Progress",
                "ordering": ["character_sheet", "technique"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character_sheet", "technique"),
                        name="unique_technique_progress_per_character",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TechniqueProgressWeekly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points_contributed",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Meter-progress points contributed this week.",
                    ),
                ),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technique_progress_weekly",
                        to="character_sheets.charactersheet",
                    ),
                ),
                (
                    "game_week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technique_progress_weekly",
                        to="game_clock.gameweek",
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_weekly",
                        to="magic.technique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technique Progress Weekly",
                "verbose_name_plural": "Technique Progress Weekly",
                "ordering": ["character_sheet", "technique", "game_week"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character_sheet", "technique", "game_week"),
                        name="unique_technique_progress_weekly",
                    )
                ],
            },
        ),
    ]
