# Generated by Django 5.2.15 on 2026-08-03 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0140_alter_resonance_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="gift",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Umbrella gift this gift hangs beneath. A character holding this gift also reaches the parent's techniques, on one thread (e.g. Vulpi.parent = Khati).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="magic.gift",
            ),
        ),
    ]
