# Generated by Django 5.2.15 on 2026-08-04 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0141_gift_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="dramaticmomentsuggestion",
            name="technique",
            field=models.ForeignKey(
                blank=True,
                help_text="The technique the entrance was cast with. Carried so that confirming the suggestion can resolve the resonance from the thread the character wove into that technique's gift. Null for a manual GM tag with no technique behind it.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dramatic_moment_suggestions",
                to="magic.technique",
            ),
        ),
        migrations.AlterField(
            model_name="dramaticmomenttype",
            name="resonance",
            field=models.ForeignKey(
                blank=True,
                help_text="OPTIONAL override pinning this moment type to one resonance. Leave blank (the norm): the grant then follows the resonance the character wove into the gift of the technique they made their entrance with. Resonance comes from the player, not from authored content (ADR-0052).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dramatic_moment_types",
                to="magic.resonance",
            ),
        ),
        migrations.AlterField(
            model_name="dramaticmomenttype",
            name="resonance_amount",
            field=models.PositiveIntegerField(
                default=15,
                help_text="Flat resonance units granted to the tagged character. Granted to whichever resonance is resolved; no grant fires when none resolves.",
            ),
        ),
    ]
