# Generated by Django 5.2.14 on 2026-07-01 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("consent", "0004_social_consent_categories"),
        ("roster", "0005_rosterentry_created_by_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialconsentcategoryrule",
            name="mode",
            field=models.CharField(
                choices=[
                    ("everyone", "Everyone"),
                    ("all_but_blacklist", "Everyone except my blacklist"),
                    ("friends_whitelist", "Friends and my whitelist"),
                    ("allowlist", "Allowlist only"),
                ],
                default="everyone",
                help_text="EVERYONE (anyone), ALL_BUT_BLACKLIST (anyone but this category's blacklist), FRIENDS_WHITELIST (OOC friends + whitelist), or ALLOWLIST (only whitelisted actors).",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SocialConsentBlacklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked_tenure",
                    models.ForeignKey(
                        help_text="Tenure barred from targeting owner_tenure in this category.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_consent_blacklist_blocked",
                        to="roster.rostertenure",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Blacklist is scoped per category.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklist_entries",
                        to="consent.socialconsentcategory",
                    ),
                ),
                (
                    "owner_tenure",
                    models.ForeignKey(
                        help_text="Tenure that owns the preference (does NOT want these actions).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_consent_blacklist_owned",
                        to="roster.rostertenure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Consent Blacklist Entry",
                "verbose_name_plural": "Social Consent Blacklist Entries",
                "unique_together": {("owner_tenure", "blocked_tenure", "category")},
            },
        ),
    ]
