# Generated by Django 5.2.14 on 2026-07-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consent", "0005_alter_socialconsentcategoryrule_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialconsentcategory",
            name="default_mode",
            field=models.CharField(
                choices=[
                    ("everyone", "Everyone"),
                    ("all_but_blacklist", "Everyone except my blacklist"),
                    ("friends_whitelist", "Friends and my whitelist"),
                    ("allowlist", "Allowlist only"),
                ],
                default="everyone",
                help_text="Targeting mode when a player has set no rule for this category. EVERYONE preserves legacy behavior; ALLOWLIST makes the category opt-in (used by theft, #1909).",
                max_length=20,
            ),
        ),
    ]
