# Generated by Django 5.2.15 on 2026-07-24 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("evennia_extensions", "0015_pagebackground"),
        ("instances", "0002_instancedroom_gm_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instancedroom",
            name="room",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instance_data",
                to="evennia_extensions.roomprofile",
            ),
        ),
    ]
