# Generated by Django 5.2.14 on 2026-05-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mechanics", "0002_challengeapproach_auto_succeeds"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengeapproach",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="When true, this approach is offered to every character regardless of capabilities — the fallback anyone can attempt.",
            ),
        ),
    ]
