# Generated by Django 5.2.4 on 2026-03-13 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mechanics", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactermodifier",
            name="target",
            field=models.ForeignKey(
                default=1,
                help_text="What this modifier affects (e.g., strength, ap_daily_regen).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_modifiers",
                to="mechanics.modifiertarget",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="charactermodifier",
            name="source",
            field=models.ForeignKey(
                help_text="Where this modifier came from (for cascade deletion and display).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modifiers",
                to="mechanics.modifiersource",
            ),
        ),
    ]
