# Generated by Django 5.2.4 on 2026-03-16 04:47

from django.db import migrations, models

import core.natural_keys


class Migration(migrations.Migration):
    dependencies = [
        ("mechanics", "0004_challengecategory_property_propertycategory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrerequisiteType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
    ]
