# Generated by Django 5.2.14 on 2026-06-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mechanics", "0005_modifiersource_residence_comfort"),
    ]

    operations = [
        migrations.AddField(
            model_name="modifiersource",
            name="achievement_reward",
            field=models.BooleanField(
                default=False,
                help_text="Marks the shared source for achievement-granted bonus modifiers.",
            ),
        ),
    ]
