# Generated by Django 5.2.4 on 2026-03-18 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("codex", "0002_initial"),
        ("conditions", "0004_remove_capabilitytype_prerequisite_key_and_more"),
        ("flows", "0001_initial"),
        ("mechanics", "0005_prerequisitetype"),
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
        ("traits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterchallengerecord",
            name="consequence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="challenge_records",
                to="mechanics.challengeconsequence",
            ),
        ),
        migrations.AddField(
            model_name="characterchallengerecord",
            name="outcome",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="challenge_records",
                to="traits.checkoutcome",
            ),
        ),
        migrations.CreateModel(
            name="ChallengeTemplateProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.PositiveIntegerField(default=1)),
                (
                    "challenge_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_template_properties",
                        to="mechanics.challengetemplate",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_template_properties",
                        to="mechanics.property",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="challengetemplate",
            name="properties",
        ),
        migrations.AddField(
            model_name="challengetemplate",
            name="properties",
            field=models.ManyToManyField(
                blank=True,
                related_name="challenge_templates",
                through="mechanics.ChallengeTemplateProperty",
                to="mechanics.property",
            ),
        ),
        migrations.CreateModel(
            name="ConsequenceEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "effect_type",
                    models.CharField(
                        choices=[
                            ("apply_condition", "Apply Condition"),
                            ("remove_condition", "Remove Condition"),
                            ("add_property", "Add Property"),
                            ("remove_property", "Remove Property"),
                            ("deal_damage", "Deal Damage"),
                            ("launch_attack", "Launch Attack"),
                            ("launch_flow", "Launch Flow"),
                            ("grant_codex", "Grant Codex Entry"),
                        ],
                        max_length=20,
                    ),
                ),
                ("execution_order", models.PositiveIntegerField(default=0)),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("self", "Self (acting character)"),
                            ("location", "Location (challenge's room)"),
                        ],
                        default="self",
                        max_length=20,
                    ),
                ),
                (
                    "condition_severity",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("property_value", models.PositiveIntegerField(blank=True, null=True)),
                ("damage_amount", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "codex_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consequence_effects",
                        to="codex.codexentry",
                    ),
                ),
                (
                    "condition_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consequence_effects",
                        to="conditions.conditiontemplate",
                    ),
                ),
                (
                    "consequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="effects",
                        to="mechanics.challengeconsequence",
                    ),
                ),
                (
                    "damage_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consequence_effects",
                        to="conditions.damagetype",
                    ),
                ),
                (
                    "flow_definition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consequence_effects",
                        to="flows.flowdefinition",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consequence_effects",
                        to="mechanics.property",
                    ),
                ),
            ],
            options={
                "ordering": ["execution_order"],
            },
        ),
        migrations.CreateModel(
            name="ObjectProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object_properties",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object_properties",
                        to="mechanics.property",
                    ),
                ),
                (
                    "source_challenge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_properties",
                        to="mechanics.challengeinstance",
                    ),
                ),
                (
                    "source_condition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_properties",
                        to="conditions.conditioninstance",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="challengetemplateproperty",
            constraint=models.UniqueConstraint(
                fields=("challenge_template", "property"),
                name="challenge_template_property_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="objectproperty",
            constraint=models.UniqueConstraint(
                fields=("object", "property"), name="object_property_unique"
            ),
        ),
    ]
