# Generated by Django 5.2.15 on 2026-08-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0011_actiontemplate_difficulty_tier_modifier"),
        ("checks", "0030_consequenceeffect_anima_amount_and_more"),
        ("mechanics", "0013_alter_characterchallengerecord_character_and_more"),
        ("objects", "0014_defaultobject_defaultcharacter_defaultexit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengeinstance",
            name="adjustment_reason",
            field=models.CharField(
                blank=True,
                help_text="Why the GM shifted the band. Required whenever severity_adjustment is non-zero, and GM-facing only — never surfaced to players.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="challengeinstance",
            name="severity_adjustment",
            field=models.SmallIntegerField(
                default=0,
                help_text="Signed one-band shift a GM applied when placing this challenge (#2865), in DIFFICULTY_VALUES points. Folded into the template's severity at resolution. Constrained to exactly one band either way — never an arbitrary offset.",
            ),
        ),
        migrations.AlterField(
            model_name="challengetemplate",
            name="severity",
            field=models.PositiveIntegerField(
                default=45,
                help_text="Authored difficulty in DIFFICULTY_VALUES points (15 Trivial .. 90 Harrowing), passed straight to perform_check's target_difficulty. NOT a 1-5 rating: the old default of 1 resolved every authored challenge at the bottom rank (#2865).",
            ),
        ),
        migrations.AddConstraint(
            model_name="challengeinstance",
            constraint=models.CheckConstraint(
                condition=models.Q(("severity_adjustment__in", [-15, 0, 15])),
                name="challenge_instance_adjustment_one_band",
            ),
        ),
        migrations.AddConstraint(
            model_name="challengeinstance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("severity_adjustment", 0),
                    models.Q(("adjustment_reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="challenge_instance_adjustment_needs_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="situationtraplink",
            constraint=models.UniqueConstraint(
                fields=("situation_template", "name"),
                name="situation_trap_link_unique_name",
            ),
        ),
    ]
