# Generated by Django 5.2.15 on 2026-08-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mechanics", "0014_challengeinstance_adjustment_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modifiertarget",
            name="is_styleable",
            field=models.BooleanField(
                default=False,
                help_text="Crafters may work this axis into a piece as an Accent at craft time (#2878) — e.g. allure, menace. Data designation, never an enum: adding a styleable axis is a row flip, not a migration.",
            ),
        ),
    ]
