# Generated by Django 5.2.4 on 2026-02-13 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("character_sheets", "0001_initial"),
        ("mechanics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelationshipCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Condition name (e.g., 'Attracted To', 'Fears', 'Trusts')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this condition represents",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order for display purposes (lower values appear first)",
                    ),
                ),
                (
                    "gates_modifiers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Modifier types that only apply when this condition exists",
                        related_name="gated_by_conditions",
                        to="mechanics.modifiertype",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CharacterRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reputation",
                    models.IntegerField(
                        default=0,
                        help_text="Reputation score from -1000 (hostile) to 1000 (allied)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        help_text="The character who holds this opinion",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_as_source",
                        to="character_sheets.charactersheet",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        help_text="The character this opinion is about",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_as_target",
                        to="character_sheets.charactersheet",
                    ),
                ),
                (
                    "conditions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Conditions that exist on this relationship",
                        related_name="character_relationships",
                        to="relationships.relationshipcondition",
                    ),
                ),
            ],
            options={
                "unique_together": {("source", "target")},
            },
        ),
    ]
