# Generated by Django 5.2.14 on 2026-07-03 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("character_sheets", "0002_initial"),
        ("magic", "0002_initial"),
        ("mechanics", "0002_initial"),
        ("relationships", "0001_initial"),
        ("scenes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="relationshipcapstone",
            name="linked_scene",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional scene this capstone is based on",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scenes.scene",
            ),
        ),
        migrations.AddField(
            model_name="relationshipcapstone",
            name="relationship",
            field=models.ForeignKey(
                help_text="The relationship this capstone applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="capstones",
                to="relationships.characterrelationship",
            ),
        ),
        migrations.AddField(
            model_name="relationshipcapstone",
            name="ritual",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when is_ritual_capstone=True; references the Ritual that was performed.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="capstone_events",
                to="magic.ritual",
            ),
        ),
        migrations.AddField(
            model_name="relationshipchange",
            name="author",
            field=models.ForeignKey(
                help_text="The character who authored this change",
                on_delete=django.db.models.deletion.CASCADE,
                to="character_sheets.charactersheet",
            ),
        ),
        migrations.AddField(
            model_name="relationshipchange",
            name="relationship",
            field=models.ForeignKey(
                help_text="The relationship this change applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="changes",
                to="relationships.characterrelationship",
            ),
        ),
        migrations.AddField(
            model_name="relationshipcondition",
            name="gates_modifiers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Modifier types that only apply when this condition exists",
                related_name="gated_by_conditions",
                to="mechanics.modifiertarget",
            ),
        ),
        migrations.AddField(
            model_name="characterrelationship",
            name="conditions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Conditions that exist on this relationship",
                related_name="character_relationships",
                to="relationships.relationshipcondition",
            ),
        ),
        migrations.AddField(
            model_name="relationshipdevelopment",
            name="author",
            field=models.ForeignKey(
                help_text="The character who performed this development",
                on_delete=django.db.models.deletion.CASCADE,
                to="character_sheets.charactersheet",
            ),
        ),
        migrations.AddField(
            model_name="relationshipdevelopment",
            name="linked_scene",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional scene this development is based on",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scenes.scene",
            ),
        ),
        migrations.AddField(
            model_name="relationshipdevelopment",
            name="relationship",
            field=models.ForeignKey(
                help_text="The relationship this development applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="developments",
                to="relationships.characterrelationship",
            ),
        ),
        migrations.AddField(
            model_name="characterrelationship",
            name="displayed_tier",
            field=models.ForeignKey(
                blank=True,
                help_text="Tier displayed publicly (for deceit); null = show actual",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="relationships.relationshiptier",
            ),
        ),
        migrations.AddField(
            model_name="relationshiptier",
            name="track",
            field=models.ForeignKey(
                help_text="The track this tier belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tiers",
                to="relationships.relationshiptrack",
            ),
        ),
        migrations.AddField(
            model_name="relationshipdevelopment",
            name="track",
            field=models.ForeignKey(
                help_text="The track that gains permanent points",
                on_delete=django.db.models.deletion.PROTECT,
                to="relationships.relationshiptrack",
            ),
        ),
        migrations.AddField(
            model_name="relationshipchange",
            name="source_track",
            field=models.ForeignKey(
                help_text="The track losing points",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="changes_from",
                to="relationships.relationshiptrack",
            ),
        ),
        migrations.AddField(
            model_name="relationshipchange",
            name="target_track",
            field=models.ForeignKey(
                help_text="The track gaining points",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="changes_to",
                to="relationships.relationshiptrack",
            ),
        ),
        migrations.AddField(
            model_name="relationshipcapstone",
            name="track",
            field=models.ForeignKey(
                help_text="The track that gains points and capacity",
                on_delete=django.db.models.deletion.PROTECT,
                to="relationships.relationshiptrack",
            ),
        ),
        migrations.AddField(
            model_name="hybridrequirement",
            name="track",
            field=models.ForeignKey(
                help_text="The track that must meet the minimum tier",
                on_delete=django.db.models.deletion.CASCADE,
                to="relationships.relationshiptrack",
            ),
        ),
        migrations.AddField(
            model_name="grievanceoption",
            name="track",
            field=models.ForeignKey(
                help_text="The negative-sign track this grievance lands on.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grievance_options",
                to="relationships.relationshiptrack",
            ),
        ),
        migrations.AddField(
            model_name="characterrelationship",
            name="displayed_track",
            field=models.ForeignKey(
                blank=True,
                help_text="Track displayed publicly (for deceit); null = show actual",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="relationships.relationshiptrack",
            ),
        ),
        migrations.AddField(
            model_name="relationshiptrackprogress",
            name="relationship",
            field=models.ForeignKey(
                help_text="The relationship this progress belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="track_progress",
                to="relationships.characterrelationship",
            ),
        ),
        migrations.AddField(
            model_name="relationshiptrackprogress",
            name="track",
            field=models.ForeignKey(
                help_text="The track being progressed",
                on_delete=django.db.models.deletion.CASCADE,
                to="relationships.relationshiptrack",
            ),
        ),
        migrations.AddField(
            model_name="relationshipupdate",
            name="author",
            field=models.ForeignKey(
                help_text="The character who wrote this update",
                on_delete=django.db.models.deletion.CASCADE,
                to="character_sheets.charactersheet",
            ),
        ),
        migrations.AddField(
            model_name="relationshipupdate",
            name="linked_interaction",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Specific interaction this update references (no DB FK constraint — partitioned table, application-level integrity)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referencing_updates",
                to="scenes.interaction",
            ),
        ),
        migrations.AddField(
            model_name="relationshipupdate",
            name="linked_scene",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional scene this update is based on",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scenes.scene",
            ),
        ),
        migrations.AddField(
            model_name="relationshipupdate",
            name="relationship",
            field=models.ForeignKey(
                help_text="The relationship this update applies to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updates",
                to="relationships.characterrelationship",
            ),
        ),
        migrations.AddField(
            model_name="relationshipupdate",
            name="track",
            field=models.ForeignKey(
                help_text="The track that gains points from this update",
                on_delete=django.db.models.deletion.PROTECT,
                to="relationships.relationshiptrack",
            ),
        ),
        migrations.AddField(
            model_name="temporaryrelationshipcondition",
            name="condition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="temporary_applications",
                to="relationships.relationshipcondition",
            ),
        ),
        migrations.AddField(
            model_name="temporaryrelationshipcondition",
            name="relationship",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="temporary_conditions",
                to="relationships.characterrelationship",
            ),
        ),
        migrations.AddField(
            model_name="writeupcomplaint",
            name="capstone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="relationships.relationshipcapstone",
            ),
        ),
        migrations.AddField(
            model_name="writeupcomplaint",
            name="complainant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="writeup_complaints_filed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="writeupcomplaint",
            name="development",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="relationships.relationshipdevelopment",
            ),
        ),
        migrations.AddField(
            model_name="writeupcomplaint",
            name="update",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="relationships.relationshipupdate",
            ),
        ),
        migrations.AddField(
            model_name="writeupkudos",
            name="account",
            field=models.ForeignKey(
                help_text="The subject's controlling account (the commender).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="writeup_kudos_given",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="writeupkudos",
            name="capstone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="relationships.relationshipcapstone",
            ),
        ),
        migrations.AddField(
            model_name="writeupkudos",
            name="development",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="relationships.relationshipdevelopment",
            ),
        ),
        migrations.AddField(
            model_name="writeupkudos",
            name="update",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="relationships.relationshipupdate",
            ),
        ),
        migrations.AddConstraint(
            model_name="relationshiptier",
            constraint=models.UniqueConstraint(
                fields=("track", "tier_number"), name="unique_tier_per_track"
            ),
        ),
        migrations.AddConstraint(
            model_name="hybridrequirement",
            constraint=models.UniqueConstraint(
                fields=("hybrid_type", "track"), name="unique_track_per_hybrid"
            ),
        ),
        migrations.AddConstraint(
            model_name="characterrelationship",
            constraint=models.UniqueConstraint(
                fields=("source", "target"), name="unique_relationship_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="characterrelationship",
            constraint=models.CheckConstraint(
                condition=models.Q(("source", models.F("target")), _negated=True),
                name="relationship_source_not_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="relationshiptrackprogress",
            constraint=models.UniqueConstraint(
                fields=("relationship", "track"), name="unique_progress_per_track"
            ),
        ),
        migrations.AddIndex(
            model_name="temporaryrelationshipcondition",
            index=models.Index(
                fields=["relationship", "expires_at"],
                name="relationshi_relatio_4cedd6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="temporaryrelationshipcondition",
            constraint=models.UniqueConstraint(
                fields=("relationship", "condition"),
                name="uniq_temp_relationship_condition",
            ),
        ),
        migrations.AddConstraint(
            model_name="writeupcomplaint",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("capstone__isnull", True),
                        ("development__isnull", True),
                        ("update__isnull", False),
                    ),
                    models.Q(
                        ("capstone__isnull", True),
                        ("development__isnull", False),
                        ("update__isnull", True),
                    ),
                    models.Q(
                        ("capstone__isnull", False),
                        ("development__isnull", True),
                        ("update__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="writeupcomplaint_exactly_one_writeup",
            ),
        ),
        migrations.AddConstraint(
            model_name="writeupkudos",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("capstone__isnull", True),
                        ("development__isnull", True),
                        ("update__isnull", False),
                    ),
                    models.Q(
                        ("capstone__isnull", True),
                        ("development__isnull", False),
                        ("update__isnull", True),
                    ),
                    models.Q(
                        ("capstone__isnull", False),
                        ("development__isnull", True),
                        ("update__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="writeupkudos_exactly_one_writeup",
            ),
        ),
        migrations.AddConstraint(
            model_name="writeupkudos",
            constraint=models.UniqueConstraint(
                condition=models.Q(("update__isnull", False)),
                fields=("account", "update"),
                name="unique_kudos_account_update",
            ),
        ),
        migrations.AddConstraint(
            model_name="writeupkudos",
            constraint=models.UniqueConstraint(
                condition=models.Q(("development__isnull", False)),
                fields=("account", "development"),
                name="unique_kudos_account_development",
            ),
        ),
        migrations.AddConstraint(
            model_name="writeupkudos",
            constraint=models.UniqueConstraint(
                condition=models.Q(("capstone__isnull", False)),
                fields=("account", "capstone"),
                name="unique_kudos_account_capstone",
            ),
        ),
    ]
