# Generated by Django 5.2.4 on 2026-05-04 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0042_sineating_soultetherrescue"),
        ("relationships", "0002_soul_tether_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="relationshipcapstone",
            name="is_ritual_capstone",
            field=models.BooleanField(
                default=False,
                help_text="Whether this capstone was created via a Ritual Capstone (Spec B §12.1).",
            ),
        ),
        migrations.AddField(
            model_name="relationshipcapstone",
            name="ritual",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when is_ritual_capstone=True; references the Ritual that was performed.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="capstone_events",
                to="magic.ritual",
            ),
        ),
    ]
