# Generated by Django 5.2.14 on 2026-06-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relationships", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="relationshiptrack",
            name="fuels_escalation_spikes",
            field=models.BooleanField(
                default=False,
                help_text="Whether bonds on this track qualify for combat escalation intensity spikes when the bonded character falls (#872).",
            ),
        ),
    ]
