# Generated by Django 5.2.14 on 2026-07-10 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0021_consequenceeffect_affection_amount_and_more"),
        ("relationships", "0010_bondcombatconfig"),
        ("scenes", "0048_reactionemoji"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffectionShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Signed points applied: positive → Regard, negative → Friction"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "effect",
                    models.ForeignKey(
                        help_text="The SHIFT_AFFECTION effect row that fired (dedup key + provenance)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affection_shifts",
                        to="checks.consequenceeffect",
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        help_text="The directed (target→actor) relationship this shift moved",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affection_shifts",
                        to="relationships.characterrelationship",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        help_text="The scene the shifting action resolved in (dedup key)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affection_shifts",
                        to="scenes.scene",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("relationship", "scene", "effect"),
                        name="unique_affection_shift_per_scene",
                    )
                ],
            },
        ),
    ]
