# Generated by Django 5.2.4 on 2026-03-23 04:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
        ("scenes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("removed", "Removed"),
                            ("hidden", "Hidden"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        help_text="The room this place belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="places",
                        to="objects.objectdb",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="interaction",
            name="place",
            field=models.ForeignKey(
                blank=True,
                help_text="Sub-location where this interaction occurred",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interactions",
                to="scenes.place",
            ),
        ),
        migrations.CreateModel(
            name="PlacePresence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("arrived_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place_presences",
                        to="scenes.persona",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presences",
                        to="scenes.place",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InteractionReceiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="Denormalized from interaction -- required for composite FK with partitioned table"
                    ),
                ),
                (
                    "interaction",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="The interaction this receiver record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receivers",
                        to="scenes.interaction",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        help_text="The persona who received this interaction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions_received",
                        to="scenes.persona",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["persona", "interaction"], name="scenes_inte_persona_1c018f_idx"
                    ),
                    models.Index(fields=["timestamp"], name="interactionreceiver_ts_brin"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("interaction", "persona"), name="unique_receiver_per_interaction"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.UniqueConstraint(
                condition=models.Q(("room__isnull", False)),
                fields=("room", "name"),
                name="unique_place_per_room",
            ),
        ),
        migrations.AddConstraint(
            model_name="placepresence",
            constraint=models.UniqueConstraint(
                fields=("place", "persona"), name="unique_presence_per_place"
            ),
        ),
    ]
