# Generated by Django 5.2.14 on 2026-07-03 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("scenes", "0001_initial"),
        ("skills", "0001_initial"),
        ("traits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sceneactionrequest",
            name="snapshot_skill",
            field=models.ForeignKey(
                blank=True,
                help_text="Skill from ritual check spec at fire time",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="skills.skill",
            ),
        ),
        migrations.AddField(
            model_name="sceneactionrequest",
            name="snapshot_specialization",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional specialization from ritual check spec at fire time",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="skills.specialization",
            ),
        ),
        migrations.AddField(
            model_name="sceneactionrequest",
            name="snapshot_stat",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary stat from ritual check spec at fire time",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="traits.trait",
            ),
        ),
    ]
