# Generated by Django 5.2.4 on 2026-03-20 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
        ("roster", "0001_initial"),
        ("scenes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scene",
            name="is_public",
        ),
        migrations.AddField(
            model_name="scene",
            name="privacy_mode",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("ephemeral", "Ephemeral"),
                ],
                default="public",
                help_text="Privacy floor for all interactions in this scene",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="scene",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="Scene summary — required for ephemeral scenes, optional for others",
            ),
        ),
        migrations.AddField(
            model_name="scene",
            name="summary_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Pending Review"),
                    ("agreed", "Agreed"),
                ],
                default="draft",
                help_text="Status of collaborative summary (mainly for ephemeral scenes)",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="The actual written text of the interaction"),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("pose", "Pose"),
                            ("emit", "Emit"),
                            ("say", "Say"),
                            ("whisper", "Whisper"),
                            ("shout", "Shout"),
                            ("action", "Action"),
                        ],
                        default="pose",
                        help_text="The type of IC interaction",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("very_private", "Very Private"),
                        ],
                        default="default",
                        help_text="Privacy override — can only escalate, never reduce",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "sequence_number",
                    models.PositiveIntegerField(
                        help_text="Ordering within a location for chronological display"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Where this interaction happened. Denormalized from scene.location for scene interactions — enables direct (location, timestamp) index scans for room activity feeds without joining through Scene.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions_at",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        help_text="Disguise/alt identity if active during this interaction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interactions_written",
                        to="scenes.persona",
                    ),
                ),
                (
                    "roster_entry",
                    models.ForeignKey(
                        help_text="The specific player who wrote this. Required because persona is nullable (scene-less interactions have no persona). Also enables direct roster_entry-based privacy queries without joining through persona -> participation -> account.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions_written",
                        to="roster.rosterentry",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        help_text="Scene container if one was active",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interactions",
                        to="scenes.scene",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InteractionTargetPersona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="Denormalized from interaction for partitioned table FK"
                    ),
                ),
                (
                    "interaction",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interaction_targets",
                        to="scenes.interaction",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targeted_in_interactions",
                        to="scenes.persona",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="interaction",
            name="target_personas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Explicit IC targets for thread derivation",
                related_name="interactions_targeted",
                through="scenes.InteractionTargetPersona",
                to="scenes.persona",
            ),
        ),
        migrations.CreateModel(
            name="SceneSummaryRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="The summary text for this revision"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submit", "Submit"),
                            ("edit", "Edit"),
                            ("agree", "Agree"),
                        ],
                        help_text="Whether this is a submission, edit, or agreement",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "persona",
                    models.ForeignKey(
                        help_text="Who submitted this revision (IC identity, never account)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary_revisions",
                        to="scenes.persona",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        help_text="The ephemeral scene this revision belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary_revisions",
                        to="scenes.scene",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InteractionAudience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="Denormalized from interaction — required for composite FK with partitioned table"
                    ),
                ),
                (
                    "interaction",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="The interaction this audience record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audience",
                        to="scenes.interaction",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        help_text="The IC identity they were presenting as when they saw it",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interactions_witnessed",
                        to="scenes.persona",
                    ),
                ),
                (
                    "roster_entry",
                    models.ForeignKey(
                        help_text="The specific player who saw this interaction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions_witnessed",
                        to="roster.rosterentry",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["roster_entry", "interaction"],
                        name="scenes_inte_roster__fceef4_idx",
                    ),
                    models.Index(fields=["timestamp"], name="interactionaudience_ts_brin"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("interaction", "roster_entry"),
                        name="unique_audience_per_interaction",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InteractionFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="Denormalized from interaction — required for composite FK with partitioned table"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interaction",
                    models.ForeignKey(
                        db_constraint=False,
                        help_text="The bookmarked interaction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="scenes.interaction",
                    ),
                ),
                (
                    "roster_entry",
                    models.ForeignKey(
                        help_text="The player who bookmarked this",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_interactions",
                        to="roster.rosterentry",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("interaction", "roster_entry"),
                        name="unique_favorite_per_interaction",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="interactiontargetpersona",
            constraint=models.UniqueConstraint(
                fields=("interaction", "persona"), name="unique_target_per_interaction"
            ),
        ),
        migrations.AddIndex(
            model_name="interaction",
            index=models.Index(
                fields=["location", "timestamp"], name="scenes_inte_locatio_644746_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interaction",
            index=models.Index(
                fields=["scene", "sequence_number"],
                name="scenes_inte_scene_i_ffcd83_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interaction",
            index=models.Index(
                fields=["roster_entry", "timestamp"],
                name="scenes_inte_roster__d2fc52_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interaction",
            index=models.Index(
                fields=["location", "-sequence_number"],
                name="interaction_loc_seq_desc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interaction",
            index=models.Index(
                condition=models.Q(("visibility", "very_private")),
                fields=["timestamp"],
                name="interaction_very_private_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interaction",
            index=models.Index(
                condition=models.Q(("scene__isnull", True)),
                fields=["location", "timestamp"],
                name="interaction_no_scene_idx",
            ),
        ),
    ]
