# Generated by Django 5.2.4 on 2026-04-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0002_partition_interaction"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="interaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("vote_count__gte", 0)),
                name="interaction_vote_count_nonnegative",
            ),
        ),
    ]
