# Generated by Django 5.2.4 on 2026-04-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0003_interaction_interaction_vote_count_nonnegative"),
    ]

    operations = [
        migrations.AddField(
            model_name="interaction",
            name="pose_kind",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("entry", "Entry"),
                    ("departure", "Departure"),
                ],
                db_index=True,
                default="standard",
                help_text="Classifies the pose as standard, entry, or departure. Set by the +enter command (future) or scene-entry hook. Spec C reads ENTRY to filter scene-entry-endorsement targets.",
                max_length=16,
            ),
        ),
    ]
