# Generated by Django 5.2.14 on 2026-05-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0006_alter_interaction_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="is_system",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="OOC system/narrator/GM identity. Excluded from the persona picker (PersonaViewSet filters is_system=False); its authored interactions still display in the scene log.",
            ),
        ),
    ]
