# Generated by Django 5.2.4 on 2026-03-28 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_event_options"),
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
        ("scenes", "0010_scene_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="scene",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event__isnull", False), ("is_active", True)),
                fields=("event",),
                name="unique_active_scene_per_event",
            ),
        ),
    ]
