# Generated by Django 5.2.14 on 2026-06-09 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0003_initial"),
        ("scenes", "0011_sceneactionrequest_effort_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SceneCheckModifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modifier_value",
                    models.IntegerField(
                        help_text="Flat modifier (positive = bonus, negative = penalty)"
                    ),
                ),
                (
                    "check_type",
                    models.ForeignKey(
                        help_text="The check type this modifier applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scene_check_modifiers",
                        to="checks.checktype",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        help_text="The scene whose surroundings this modifier describes",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_modifiers",
                        to="scenes.scene",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scene", "check_type"),
                        name="scene_check_modifier_unique_scene_check_type",
                    )
                ],
            },
        ),
    ]
