# Generated by Django 5.2.14 on 2026-06-09 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0012_interactionpowerledgerentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="sceneactionrequest",
            name="action_interaction",
            field=models.OneToOneField(
                blank=True,
                db_constraint=False,
                help_text="ACTION-mode Interaction for this cast (carries the power ledger).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_request_action",
                to="scenes.interaction",
            ),
        ),
    ]
