# Generated by Django 5.2.4 on 2026-04-13 00:57

from django.db import migrations


def populate_character_sheet(apps, schema_editor):
    Persona = apps.get_model("scenes", "Persona")
    for persona in Persona.objects.filter(character_sheet__isnull=True).iterator():
        # CharacterSheet shares pk with ObjectDB; character_identity.character is the ObjectDB.
        if persona.character_identity_id:
            persona.character_sheet_id = persona.character_identity.character_id
            persona.save(update_fields=["character_sheet_id"])


def unpopulate_character_sheet(apps, schema_editor):
    Persona = apps.get_model("scenes", "Persona")
    Persona.objects.update(character_sheet=None)


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0013_persona_character_sheet"),
    ]

    operations = [
        migrations.RunPython(
            populate_character_sheet,
            reverse_code=unpopulate_character_sheet,
        ),
    ]
