# Generated by Django 5.2.14 on 2026-06-15 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character_sheets", "0005_charactersheet_max_active_npc_missions"),
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
        ("scenes", "0021_persona_prestige_from_fashion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SceneRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("declaring", "Declaring"),
                            ("resolving", "Resolving"),
                            ("between_rounds", "Between Rounds"),
                            ("completed", "Completed"),
                        ],
                        default="between_rounds",
                        max_length=20,
                    ),
                ),
                (
                    "start_reason",
                    models.CharField(
                        choices=[
                            ("opt_in", "Player opt-in"),
                            ("gm", "GM-started"),
                            ("danger", "Danger (auto-started)"),
                        ],
                        default="opt_in",
                        max_length=20,
                    ),
                ),
                ("round_started_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "room",
                    models.ForeignKey(
                        help_text="Room the round takes place in (mirrors CombatEncounter.room).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scene_rounds",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scene_rounds",
                        to="scenes.scene",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SceneRoundParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("initiative_order", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("left", "Left")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scene_round_participations",
                        to="character_sheets.charactersheet",
                    ),
                ),
                (
                    "scene_round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="scenes.sceneround",
                    ),
                ),
            ],
            options={
                "ordering": ["initiative_order", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="sceneround",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["declaring", "resolving", "between_rounds"])
                ),
                fields=("room",),
                name="one_active_scene_round_per_room",
            ),
        ),
        migrations.AddConstraint(
            model_name="sceneroundparticipant",
            constraint=models.UniqueConstraint(
                fields=("scene_round", "character_sheet"),
                name="unique_scene_round_participant",
            ),
        ),
    ]
