# Generated by Django 5.2.14 on 2026-06-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0029_mute"),
    ]

    operations = [
        migrations.AddField(
            model_name="sceneactionrequest",
            name="engagement_credited",
            field=models.BooleanField(
                default=False,
                help_text="Whether this consent already accrued good-sport credit.",
            ),
        ),
        migrations.AddField(
            model_name="sceneactionrequest",
            name="resist_effort_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("very_low", "Very Low Effort"),
                    ("low", "Low Effort"),
                    ("medium", "Medium Effort"),
                    ("high", "High Effort"),
                    ("extreme", "Extreme Effort"),
                ],
                default="",
                help_text="Optional active-resistance effort spent by the defender.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sceneactiontarget",
            name="difficulty_choice",
            field=models.CharField(
                choices=[
                    ("trivial", "Trivial"),
                    ("easy", "Easy"),
                    ("normal", "Normal"),
                    ("hard", "Hard"),
                    ("daunting", "Daunting"),
                ],
                default="normal",
                help_text="Plausibility band chosen by the defender at consent.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sceneactiontarget",
            name="engagement_credited",
            field=models.BooleanField(
                default=False,
                help_text="Whether this consent already accrued good-sport credit.",
            ),
        ),
        migrations.AddField(
            model_name="sceneactiontarget",
            name="resist_effort_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("very_low", "Very Low Effort"),
                    ("low", "Low Effort"),
                    ("medium", "Medium Effort"),
                    ("high", "High Effort"),
                    ("extreme", "Extreme Effort"),
                ],
                default="",
                help_text="Optional active-resistance effort spent by the defender.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sceneactionrequest",
            name="difficulty_choice",
            field=models.CharField(
                choices=[
                    ("trivial", "Trivial"),
                    ("easy", "Easy"),
                    ("normal", "Normal"),
                    ("hard", "Hard"),
                    ("daunting", "Daunting"),
                ],
                default="normal",
                help_text="Plausibility band chosen by the defender at consent.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sceneactionrequest",
            name="resolved_difficulty",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Numeric difficulty used for resolution.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sceneactiontarget",
            name="resolved_difficulty",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Numeric difficulty used for resolution.",
                null=True,
            ),
        ),
    ]
