# Generated by Django 5.2.14 on 2026-06-21 02:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0031_blockcontactflag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sceneactionrequest",
            name="engagement_credited",
        ),
        migrations.RemoveField(
            model_name="sceneactiontarget",
            name="engagement_credited",
        ),
    ]
