# Generated by Django 5.2.14 on 2026-06-26 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0050_pending_ritual_effect"),
        ("scenes", "0036_sceneactionrequest_target_condition_instance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sceneactionrequest",
            name="thread_used",
            field=models.ForeignKey(
                blank=True,
                help_text="Bond thread used to pay the cost of a treatment, when required.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="treatment_action_requests",
                to="magic.thread",
            ),
        ),
    ]
