# Generated by Django 5.2.14 on 2026-06-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0037_sceneactionrequest_thread_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenerounddefaultsconfig",
            name="abandonment_grace_rounds",
            field=models.PositiveIntegerField(
                default=2,
                help_text="N action-driven beats an abandoned downed victim waits for rescue before their fate resolves.",
            ),
        ),
    ]
