# Generated by Django 5.2.14 on 2026-06-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0038_scenerounddefaultsconfig_abandonment_grace_rounds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="persona",
            name="persona_type",
            field=models.CharField(
                choices=[
                    ("primary", "Primary"),
                    ("established", "Established"),
                    ("temporary", "Temporary"),
                    ("alternate", "Alternate"),
                ],
                default="temporary",
                help_text="PRIMARY = real identity, ESTABLISHED = persistent alter ego, TEMPORARY = throwaway disguise, ALTERNATE = an alternate self's persona (shapeshift/possession/past-life)",
                max_length=20,
            ),
        ),
    ]
