# Generated by Django 5.2.14 on 2026-06-30 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("roster", "0005_rosterentry_created_by_account_and_more"),
        ("scenes", "0040_alter_sceneactionrequest_difficulty_choice_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "friend_tenure",
                    models.ForeignKey(
                        help_text="The friended character's tenure (a specific player's run of that character).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendships_received",
                        to="roster.rostertenure",
                    ),
                ),
                (
                    "friender_tenure",
                    models.ForeignKey(
                        help_text="The friender's tenure (this player's run of the character that friended).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friendships_made",
                        to="roster.rostertenure",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["friend_tenure"], name="scenes_frie_friend__4f7b51_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("friender_tenure", "friend_tenure"),
                        name="unique_friendship",
                    )
                ],
            },
        ),
    ]
