# Generated by Django 5.2.14 on 2026-07-01 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0041_friendship"),
    ]

    operations = [
        migrations.AddField(
            model_name="sceneactiondeclaration",
            name="succor_resolution",
            field=models.FloatField(
                blank=True,
                help_text="Cached graded outcome of this round's Succor resolution (#1744).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sceneactiondeclaration",
            name="succor_target",
            field=models.ForeignKey(
                blank=True,
                help_text="The participant this declaration shelters, when maneuver is Succor (#1744).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="succor_declarations",
                to="scenes.sceneroundparticipant",
            ),
        ),
    ]
