# Generated by Django 5.2.14 on 2026-07-03 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("character_sheets", "0010_remove_charactersheet_family_and_more"),
        ("scenes", "0044_alter_pendingsuddenharm_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingsuddenharm",
            name="target_sheet",
            field=models.ForeignKey(
                help_text="The character this pending harm targets; multiple unresolved rows may exist.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pending_sudden_harm",
                to="character_sheets.charactersheet",
            ),
        ),
    ]
