# Generated by Django 5.2.15 on 2026-07-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenes", "0057_alter_interaction_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="sceneactionrequest",
            name="cast_openly",
            field=models.BooleanField(
                default=False,
                help_text="The caster waived their style's cast concealment for this cast (#2710). Persisted rather than passed, because a consent-gated cast poses at ACCEPT time: a flag held only in the calling frame would silently go subtle when the target accepts. One-way — it can only waive concealment, never add it.",
            ),
        ),
    ]
