# Generated by Django 5.2.4 on 2026-03-18 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InteractionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal identifier (e.g., 'eat', 'wield', 'study').",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Player-facing label (e.g., 'Eat', 'Wield', 'Study').",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this interaction does.",
                    ),
                ),
            ],
            options={
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="QualityTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "color_hex",
                    models.CharField(
                        help_text="Hex color code for UI display (e.g., '#00FF00').",
                        max_length=7,
                    ),
                ),
                (
                    "numeric_min",
                    models.PositiveIntegerField(
                        help_text="Lower bound of the internal numeric quality range."
                    ),
                ),
                (
                    "numeric_max",
                    models.PositiveIntegerField(
                        help_text="Upper bound of the internal numeric quality range."
                    ),
                ),
                (
                    "stat_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Multiplier applied to base stats for items of this tier.",
                        max_digits=4,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display ordering (lower = worse quality)."
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="CurrencyBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gold",
                    models.PositiveIntegerField(default=0, help_text="Current gold balance."),
                ),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currency_balance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ItemTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Default full description when examined. Instances can override.",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Base weight of the item.",
                        max_digits=8,
                    ),
                ),
                (
                    "size",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Size value for container nesting. Smaller items fit inside larger containers.",
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(
                        default=0, help_text="Base gold value for trading/selling."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive templates cannot be used to create new items.",
                    ),
                ),
                (
                    "supports_open_close",
                    models.BooleanField(
                        default=False,
                        help_text="Whether instances can be opened/closed (coats, bags, lockets).",
                    ),
                ),
                (
                    "is_container",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this item can hold other items.",
                    ),
                ),
                (
                    "container_capacity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Maximum number of items this container can hold.",
                    ),
                ),
                (
                    "container_max_item_size",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Maximum size of items that fit inside this container.",
                    ),
                ),
                (
                    "is_stackable",
                    models.BooleanField(
                        default=False,
                        help_text="Whether items of this type can be stacked.",
                    ),
                ),
                (
                    "max_stack_size",
                    models.PositiveIntegerField(
                        default=1, help_text="Maximum quantity in a single stack."
                    ),
                ),
                (
                    "is_consumable",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this item has limited uses/charges.",
                    ),
                ),
                (
                    "max_charges",
                    models.PositiveIntegerField(
                        default=0, help_text="Maximum charges for consumable items."
                    ),
                ),
                (
                    "is_craftable",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this item can be crafted by players.",
                    ),
                ),
                (
                    "crafting_skill_threshold",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minimum crafting skill required to attempt this item.",
                    ),
                ),
                (
                    "interactions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Actions that can be performed on items of this type.",
                        related_name="templates",
                        to="items.interactiontype",
                    ),
                ),
                (
                    "required_materials",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Material templates required to craft this item.",
                        related_name="used_in_crafting",
                        to="items.itemtemplate",
                    ),
                ),
                (
                    "minimum_quality_tier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Minimum quality tier this item can be crafted at.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="minimum_for_templates",
                        to="items.qualitytier",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ItemInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_name",
                    models.CharField(
                        blank=True,
                        help_text="MU*-style descriptive name override.",
                        max_length=300,
                    ),
                ),
                (
                    "custom_description",
                    models.TextField(
                        blank=True,
                        help_text="Custom examination text, overrides template description.",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="Stack quantity for stackable items."
                    ),
                ),
                (
                    "charges",
                    models.PositiveIntegerField(
                        default=0, help_text="Remaining charges for consumable items."
                    ),
                ),
                (
                    "is_open",
                    models.BooleanField(
                        default=False, help_text="Whether this item is currently open."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crafter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crafted_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "game_object",
                    models.OneToOneField(
                        blank=True,
                        help_text="The Evennia object representing this item in the game world.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_instance",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="The archetype this item is based on.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="items.itemtemplate",
                    ),
                ),
                (
                    "quality_tier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="item_instances",
                        to="items.qualitytier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OwnershipEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("given", "Given"),
                            ("stolen", "Stolen"),
                            ("transferred", "Transferred"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Additional context for this event."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Previous owner (null for creation events).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items_given_away",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownership_events",
                        to="items.iteminstance",
                    ),
                ),
                (
                    "to_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="New owner.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flavor_text",
                    models.TextField(
                        blank=True,
                        help_text="Contextual text shown when this interaction is performed.",
                    ),
                ),
                (
                    "interaction_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_bindings",
                        to="items.interactiontype",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interaction_bindings",
                        to="items.itemtemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemplateSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body_region",
                    models.CharField(
                        choices=[
                            ("head", "Head"),
                            ("face", "Face"),
                            ("neck", "Neck"),
                            ("shoulders", "Shoulders"),
                            ("torso", "Torso"),
                            ("back", "Back"),
                            ("waist", "Waist"),
                            ("left_arm", "Left Arm"),
                            ("right_arm", "Right Arm"),
                            ("left_hand", "Left Hand"),
                            ("right_hand", "Right Hand"),
                            ("left_leg", "Left Leg"),
                            ("right_leg", "Right Leg"),
                            ("feet", "Feet"),
                            ("left_finger", "Left Finger"),
                            ("right_finger", "Right Finger"),
                            ("left_ear", "Left Ear"),
                            ("right_ear", "Right Ear"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "equipment_layer",
                    models.CharField(
                        choices=[
                            ("skin", "Skin"),
                            ("under", "Under"),
                            ("base", "Base"),
                            ("over", "Over"),
                            ("outer", "Outer"),
                            ("accessory", "Accessory"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "covers_lower_layers",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this slot hides items on lower layers at the same region.",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="items.itemtemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EquippedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body_region",
                    models.CharField(
                        choices=[
                            ("head", "Head"),
                            ("face", "Face"),
                            ("neck", "Neck"),
                            ("shoulders", "Shoulders"),
                            ("torso", "Torso"),
                            ("back", "Back"),
                            ("waist", "Waist"),
                            ("left_arm", "Left Arm"),
                            ("right_arm", "Right Arm"),
                            ("left_hand", "Left Hand"),
                            ("right_hand", "Right Hand"),
                            ("left_leg", "Left Leg"),
                            ("right_leg", "Right Leg"),
                            ("feet", "Feet"),
                            ("left_finger", "Left Finger"),
                            ("right_finger", "Right Finger"),
                            ("left_ear", "Left Ear"),
                            ("right_ear", "Right Ear"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "equipment_layer",
                    models.CharField(
                        choices=[
                            ("skin", "Skin"),
                            ("under", "Under"),
                            ("base", "Base"),
                            ("over", "Over"),
                            ("outer", "Outer"),
                            ("accessory", "Accessory"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        help_text="The character wearing/wielding this item.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipped_items",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "item_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipped_slots",
                        to="items.iteminstance",
                    ),
                ),
            ],
            options={
                "unique_together": {("character", "body_region", "equipment_layer")},
            },
        ),
        migrations.AddIndex(
            model_name="iteminstance",
            index=models.Index(fields=["template"], name="items_itemi_templat_494772_idx"),
        ),
        migrations.AddIndex(
            model_name="iteminstance",
            index=models.Index(fields=["owner"], name="items_itemi_owner_i_93abb8_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="templateinteraction",
            unique_together={("template", "interaction_type")},
        ),
        migrations.AlterUniqueTogether(
            name="templateslot",
            unique_together={("template", "body_region", "equipment_layer")},
        ),
    ]
