# Generated by Django 5.2.14 on 2026-05-29 17:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InteractionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal identifier (e.g., 'eat', 'wield', 'study').",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Player-facing label (e.g., 'Eat', 'Wield', 'Study').",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this interaction does.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ItemInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_name",
                    models.CharField(
                        blank=True,
                        help_text="MU*-style descriptive name override.",
                        max_length=300,
                    ),
                ),
                (
                    "custom_description",
                    models.TextField(
                        blank=True,
                        help_text="Custom examination text, overrides template description.",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="Stack quantity for stackable items."
                    ),
                ),
                (
                    "charges",
                    models.PositiveIntegerField(
                        default=0, help_text="Remaining charges for consumable items."
                    ),
                ),
                (
                    "is_open",
                    models.BooleanField(
                        default=False, help_text="Whether this item is currently open."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ItemTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Default full description when examined. Instances can override.",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Base weight of the item.",
                        max_digits=8,
                    ),
                ),
                (
                    "size",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Size value for container nesting. Smaller items fit inside larger containers.",
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(
                        default=0, help_text="Base gold value for trading/selling."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive templates cannot be used to create new items.",
                    ),
                ),
                (
                    "supports_open_close",
                    models.BooleanField(
                        default=False,
                        help_text="Whether instances can be opened/closed (coats, bags, lockets).",
                    ),
                ),
                (
                    "is_container",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this item can hold other items.",
                    ),
                ),
                (
                    "is_wardrobe",
                    models.BooleanField(
                        default=False,
                        help_text="Whether instances of this template can store Outfit definitions.",
                    ),
                ),
                (
                    "container_capacity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Maximum number of items this container can hold.",
                    ),
                ),
                (
                    "container_max_item_size",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Maximum size of items that fit inside this container.",
                    ),
                ),
                (
                    "is_stackable",
                    models.BooleanField(
                        default=False,
                        help_text="Whether items of this type can be stacked.",
                    ),
                ),
                (
                    "max_stack_size",
                    models.PositiveIntegerField(
                        default=1, help_text="Maximum quantity in a single stack."
                    ),
                ),
                (
                    "is_consumable",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this item has limited uses/charges.",
                    ),
                ),
                (
                    "max_charges",
                    models.PositiveIntegerField(
                        default=0, help_text="Maximum charges for consumable items."
                    ),
                ),
                (
                    "is_craftable",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this item can be crafted by players.",
                    ),
                ),
                (
                    "facet_capacity",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Number of Facet slots this template can carry. Plain items = 0 or 1; fine items = 2-3; ceremonial = 4-5.",
                    ),
                ),
                (
                    "gear_archetype",
                    models.CharField(
                        choices=[
                            ("light_armor", "Light Armor"),
                            ("medium_armor", "Medium Armor"),
                            ("heavy_armor", "Heavy Armor"),
                            ("robe", "Robe"),
                            ("melee_one_hand", "One-Handed Melee"),
                            ("melee_two_hand", "Two-Handed Melee"),
                            ("ranged", "Ranged"),
                            ("thrown", "Thrown"),
                            ("shield", "Shield"),
                            ("jewelry", "Jewelry"),
                            ("clothing", "Clothing"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Gear category. Drives covenant role × gear compatibility. Immutable across instances of this template.",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Outfit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OutfitSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body_region",
                    models.CharField(
                        choices=[
                            ("head", "Head"),
                            ("face", "Face"),
                            ("neck", "Neck"),
                            ("shoulders", "Shoulders"),
                            ("torso", "Torso"),
                            ("back", "Back"),
                            ("waist", "Waist"),
                            ("left_arm", "Left Arm"),
                            ("right_arm", "Right Arm"),
                            ("left_hand", "Left Hand"),
                            ("right_hand", "Right Hand"),
                            ("left_leg", "Left Leg"),
                            ("right_leg", "Right Leg"),
                            ("feet", "Feet"),
                            ("left_finger", "Left Finger"),
                            ("right_finger", "Right Finger"),
                            ("left_ear", "Left Ear"),
                            ("right_ear", "Right Ear"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "equipment_layer",
                    models.CharField(
                        choices=[
                            ("skin", "Skin"),
                            ("under", "Under"),
                            ("base", "Base"),
                            ("over", "Over"),
                            ("outer", "Outer"),
                            ("accessory", "Accessory"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OwnershipEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("given", "Given"),
                            ("stolen", "Stolen"),
                            ("transferred", "Transferred"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Additional context for this event."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QualityTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "color_hex",
                    models.CharField(
                        help_text="Hex color code for UI display (e.g., '#00FF00').",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9A-Fa-f]{6}$", "Must be a hex color (#RRGGBB)."
                            )
                        ],
                    ),
                ),
                (
                    "numeric_min",
                    models.PositiveIntegerField(
                        help_text="Lower bound of the internal numeric quality range."
                    ),
                ),
                (
                    "numeric_max",
                    models.PositiveIntegerField(
                        help_text="Upper bound of the internal numeric quality range."
                    ),
                ),
                (
                    "stat_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Multiplier applied to base stats for items of this tier.",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display ordering (lower = worse quality)."
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="TemplateInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flavor_text",
                    models.TextField(
                        blank=True,
                        help_text="Contextual text shown when this interaction is performed.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemplateSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body_region",
                    models.CharField(
                        choices=[
                            ("head", "Head"),
                            ("face", "Face"),
                            ("neck", "Neck"),
                            ("shoulders", "Shoulders"),
                            ("torso", "Torso"),
                            ("back", "Back"),
                            ("waist", "Waist"),
                            ("left_arm", "Left Arm"),
                            ("right_arm", "Right Arm"),
                            ("left_hand", "Left Hand"),
                            ("right_hand", "Right Hand"),
                            ("left_leg", "Left Leg"),
                            ("right_leg", "Right Leg"),
                            ("feet", "Feet"),
                            ("left_finger", "Left Finger"),
                            ("right_finger", "Right Finger"),
                            ("left_ear", "Left Ear"),
                            ("right_ear", "Right Ear"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "equipment_layer",
                    models.CharField(
                        choices=[
                            ("skin", "Skin"),
                            ("under", "Under"),
                            ("base", "Base"),
                            ("over", "Over"),
                            ("outer", "Outer"),
                            ("accessory", "Accessory"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "covers_lower_layers",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this slot hides items on lower layers at the same region.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CurrencyBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gold",
                    models.PositiveIntegerField(default=0, help_text="Current gold balance."),
                ),
                (
                    "character",
                    models.OneToOneField(
                        help_text="The character who holds this gold.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currency_balance",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EquippedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body_region",
                    models.CharField(
                        choices=[
                            ("head", "Head"),
                            ("face", "Face"),
                            ("neck", "Neck"),
                            ("shoulders", "Shoulders"),
                            ("torso", "Torso"),
                            ("back", "Back"),
                            ("waist", "Waist"),
                            ("left_arm", "Left Arm"),
                            ("right_arm", "Right Arm"),
                            ("left_hand", "Left Hand"),
                            ("right_hand", "Right Hand"),
                            ("left_leg", "Left Leg"),
                            ("right_leg", "Right Leg"),
                            ("feet", "Feet"),
                            ("left_finger", "Left Finger"),
                            ("right_finger", "Right Finger"),
                            ("left_ear", "Left Ear"),
                            ("right_ear", "Right Ear"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "equipment_layer",
                    models.CharField(
                        choices=[
                            ("skin", "Skin"),
                            ("under", "Under"),
                            ("base", "Base"),
                            ("over", "Over"),
                            ("outer", "Outer"),
                            ("accessory", "Accessory"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        help_text="The character wearing/wielding this item.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipped_items",
                        to="objects.objectdb",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemFacet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applied_by_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facet_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
