# Generated by Django 5.2.14 on 2026-07-03 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("items", "0001_initial"),
        ("magic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facetvoguemomentum",
            name="facet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vogue_momentum",
                to="magic.facet",
            ),
        ),
    ]
