# Generated by Django 5.2.14 on 2026-06-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="iteminstance",
            name="lore_value",
            field=models.IntegerField(
                default=0,
                help_text="Material construction-value boost. Used by the buildings system to inflate this instance's value when contributed as a MATERIAL to a BUILDING_CONSTRUCTION project. Pure number — more = more valuable in construction. Special properties (e.g. godswar stone grants resonance_amp to inhabitants) live on world.buildings.MaterialLoreEffect, NOT here.",
            ),
        ),
        migrations.AlterField(
            model_name="ownershipevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("given", "Given"),
                    ("stolen", "Stolen"),
                    ("transferred", "Transferred"),
                    ("activated", "Activated"),
                    ("consumed", "Consumed"),
                ],
                max_length=20,
            ),
        ),
    ]
