# Generated by Django 5.2.14 on 2026-06-09 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0003_initial"),
        ("items", "0007_fashionstyle_fashionstylebonus"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemCheckModifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modifier_value",
                    models.IntegerField(
                        help_text="Flat modifier applied when the item is equipped (positive = bonus, negative = penalty)."
                    ),
                ),
                (
                    "check_type",
                    models.ForeignKey(
                        help_text="The check type this modifier affects.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_check_modifiers",
                        to="checks.checktype",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="Item template that carries this modifier.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_modifiers",
                        to="items.itemtemplate",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("template", "check_type"),
                        name="items_unique_itemcheckmodifier_per_template_check",
                    )
                ],
            },
        ),
    ]
