# Generated by Django 5.2.14 on 2026-06-13 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0009_alter_projecttemplate_weekly_upkeep_cost"),
        ("conditions", "0007_conditioncapabilityeffect_scales_with_severity_and_more"),
        ("evennia_extensions", "0002_roomprofile_tenant_persona"),
        ("items", "0008_itemcheckmodifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="iteminstance",
            name="durability",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Current durability. Null = not tracked; 0 = broken.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="itemtemplate",
            name="base_armor_soak",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Base damage-mitigation soak when worn (armor archetypes only).",
            ),
        ),
        migrations.AddField(
            model_name="itemtemplate",
            name="base_weapon_damage",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Base weapon-damage contribution (weapon archetypes only).",
            ),
        ),
        migrations.AddField(
            model_name="itemtemplate",
            name="max_durability",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Max durability. 0 = item is not durability-tracked.",
            ),
        ),
        migrations.AddField(
            model_name="itemtemplate",
            name="weapon_damage_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Damage type dealt when this item is wielded as a weapon.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="weapon_templates",
                to="conditions.damagetype",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemtemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "gear_archetype__in",
                        [
                            "melee_one_hand",
                            "melee_two_hand",
                            "ranged",
                            "thrown",
                            "shield",
                        ],
                    ),
                    ("base_weapon_damage", 0),
                    _connector="OR",
                ),
                name="items_weapon_damage_requires_weapon_archetype",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemtemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "gear_archetype__in",
                        [
                            "light_armor",
                            "medium_armor",
                            "heavy_armor",
                            "robe",
                            "shield",
                        ],
                    ),
                    ("base_armor_soak", 0),
                    _connector="OR",
                ),
                name="items_armor_soak_requires_armor_archetype",
            ),
        ),
    ]
