# Generated by Django 5.2.14 on 2026-06-14 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0012_fashionpresentation"),
        ("magic", "0024_presentationendorsement"),
        ("societies", "0016_spreadingconfig_spread_assist_fraction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacetVogueMomentum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vogue_momentum",
                        to="magic.facet",
                    ),
                ),
                (
                    "society",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facet_momentum",
                        to="societies.society",
                    ),
                ),
            ],
            options={
                "ordering": ["-points"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("society", "facet"), name="unique_facet_momentum"
                    )
                ],
            },
        ),
    ]
