# Generated by Django 5.2.14 on 2026-06-14 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0012_iteminstance_destroyed_at_and_more"),
        ("items", "0014_trendsetter"),
    ]

    operations = []
