# Generated by Django 5.2.14 on 2026-06-14 22:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0013_facetcraftingconfig"),
        ("items", "0015_merge_20260614_2144"),
    ]

    operations = []
