# Generated by Django 5.2.14 on 2026-06-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0019_fashionstyle_in_vogue_styles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fashionstyle",
            name="in_vogue_styles",
            field=models.ManyToManyField(
                blank=True,
                help_text="Aesthetic styles (vocabulary words) that are currently fashionable.",
                related_name="vogue_in",
                to="items.style",
            ),
        ),
    ]
