# Generated by Django 5.2.14 on 2026-06-19 23:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0021_craftingmaterialrequirement_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FacetCraftingConfig",
        ),
    ]
