# Generated by Django 5.2.14 on 2026-07-06 23:33

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0026_iteminstance_access_policy"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudacityTuning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "understated_mult",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.75"),
                        help_text="Reward multiplier for UNDERSTATED-audacity styles.",
                        max_digits=4,
                    ),
                ),
                (
                    "expressive_mult",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Reward multiplier for EXPRESSIVE-audacity styles.",
                        max_digits=4,
                    ),
                ),
                (
                    "bold_mult",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.35"),
                        help_text="Reward multiplier for BOLD-audacity styles.",
                        max_digits=4,
                    ),
                ),
                (
                    "outrageous_mult",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.75"),
                        help_text="Reward multiplier for OUTRAGEOUS-audacity styles.",
                        max_digits=4,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="style",
            name="audacity",
            field=models.IntegerField(
                choices=[
                    (1, "Understated"),
                    (2, "Expressive"),
                    (3, "Bold"),
                    (4, "Outrageous"),
                ],
                default=2,
                help_text="How daring this style reads — scales its mechanical reward via AudacityTuning (#2029).",
            ),
        ),
    ]
