# Generated by Django 5.2.14 on 2026-07-07 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("areas", "0013_blueprintpositionshelter_positionshelter"),
        ("character_sheets", "0010_remove_charactersheet_family_and_more"),
        ("evennia_extensions", "0008_remove_roomprofile_tenant_persona"),
        ("items", "0027_audacitytuning_style_audacity"),
        ("realms", "0001_initial"),
        ("scenes", "0047_sceneactionpulldeclaration"),
        ("societies", "0022_alter_gangturfreputationaward_outcome_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="iteminstance",
            name="designer_character_sheet",
            field=models.ForeignKey(
                blank=True,
                help_text="The body that named/described this item (#2066 dual provenance — Arx 1 erased the prose author). Equal to the crafter on self-finished work; the ware finishing pass and service crafting stamp the buyer.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="designed_items",
                to="character_sheets.charactersheet",
            ),
        ),
        migrations.AddField(
            model_name="iteminstance",
            name="designer_persona_display",
            field=models.ForeignKey(
                blank=True,
                help_text="The persona the designer was presenting as. Renders as 'Crafted by X, Designed by Y', collapsing when equal.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="scenes.persona",
            ),
        ),
        migrations.CreateModel(
            name="MarketSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("stock", "NPC Stock"),
                            ("ware", "Ware"),
                            ("service", "Crafting Service"),
                        ],
                        max_length=10,
                    ),
                ),
                ("price", models.PositiveIntegerField()),
                ("host_cut", models.PositiveIntegerField(default=0)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer_persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_purchases",
                        to="scenes.persona",
                    ),
                ),
                (
                    "item_instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="market_sales",
                        to="items.iteminstance",
                    ),
                ),
                (
                    "seller_persona",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for NPC stock sales (pure sink).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="market_sales",
                        to="scenes.persona",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="MarketSquare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "area",
                    models.ForeignKey(
                        help_text="The capital-city Area this square trades in.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="market_squares",
                        to="areas.area",
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="market_squares",
                        to="realms.realm",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MarketStall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "cut_percent",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Host's percentage cut of each sale (0 for plain stalls). PLACEHOLDER.",
                    ),
                ),
                (
                    "host_org",
                    models.ForeignKey(
                        blank=True,
                        help_text="Org taking the listing cut, when the stall is org-hosted (#1884 stream).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hosted_stalls",
                        to="societies.organization",
                    ),
                ),
                (
                    "owner_persona",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = NPC stall (authored stock, infinite supply).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="market_stalls",
                        to="scenes.persona",
                    ),
                ),
                (
                    "square",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stalls",
                        to="items.marketsquare",
                    ),
                ),
            ],
            options={
                "ordering": ["square", "name"],
            },
        ),
        migrations.CreateModel(
            name="StockListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(help_text="Coppers. PLACEHOLDER pricing."),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "stall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_listings",
                        to="items.marketstall",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_listings",
                        to="items.itemtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["stall", "template__name"],
            },
        ),
        migrations.CreateModel(
            name="WareListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveIntegerField(help_text="Coppers.")),
                (
                    "open_style_slot",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the finishing pass may attach a style.",
                    ),
                ),
                (
                    "open_facet_slot",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the finishing pass may attach a facet.",
                    ),
                ),
                ("listed_at", models.DateTimeField(auto_now_add=True)),
                ("sold_at", models.DateTimeField(blank=True, null=True)),
                (
                    "item_instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ware_listing",
                        to="items.iteminstance",
                    ),
                ),
                (
                    "seller_persona",
                    models.ForeignKey(
                        help_text="The persona listing (and credited as crafter via the instance).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ware_listings",
                        to="scenes.persona",
                    ),
                ),
                (
                    "stall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ware_listings",
                        to="items.marketstall",
                    ),
                ),
            ],
            options={
                "ordering": ["-listed_at"],
            },
        ),
        migrations.CreateModel(
            name="FinishingPass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "buyer_persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finishing_passes",
                        to="scenes.persona",
                    ),
                ),
                (
                    "listing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finishing_pass",
                        to="items.warelisting",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Finishing passes",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="CraftingServiceOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipe_kind",
                    models.CharField(
                        help_text="CraftingRecipeKind this offer covers (attachment crafting).",
                        max_length=40,
                    ),
                ),
                (
                    "fee",
                    models.PositiveIntegerField(help_text="Coppers per attempt. PLACEHOLDER."),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "crafter_persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crafting_service_offers",
                        to="scenes.persona",
                    ),
                ),
                (
                    "shop_room",
                    models.ForeignKey(
                        help_text="The crafter's shop — service runs require presence here.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crafting_service_offers",
                        to="evennia_extensions.roomprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["crafter_persona", "recipe_kind"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("crafter_persona", "recipe_kind", "shop_room"),
                        name="items_market_service_offer_unique",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="marketstall",
            constraint=models.UniqueConstraint(
                fields=("square", "name"),
                name="items_market_stall_unique_name_per_square",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklisting",
            constraint=models.UniqueConstraint(
                fields=("stall", "template"), name="items_market_stock_unique_per_stall"
            ),
        ),
        migrations.AddIndex(
            model_name="warelisting",
            index=models.Index(fields=["stall", "sold_at"], name="items_warel_stall_i_4ccf01_idx"),
        ),
    ]
