# Generated by Django 5.2.14 on 2026-07-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0028_iteminstance_designer_character_sheet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="iteminstance",
            name="custom_flourish_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Player-customizable combat flourish prose. Overrides template flourish_text when non-empty.",
            ),
        ),
        migrations.AddField(
            model_name="itemtemplate",
            name="flourish_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Staff-authored combat flourish prose. Appended as an em-dash clause to combat outcome narration when this item is equipped.",
            ),
        ),
    ]
