# Generated by Django 5.2.15 on 2026-07-18 21:32

from django.db import migrations, models
import django.db.models.deletion

import core.natural_keys


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0040_itemtemplate_adornment_capacity_adornment"),
        ("mechanics", "0012_application_default_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemTemplateProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.PositiveIntegerField(default=1)),
                (
                    "item_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="default_properties",
                        to="items.itemtemplate",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_template_defaults",
                        to="mechanics.property",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("item_template", "property"),
                        name="items_template_property_unique",
                    )
                ],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
    ]
