# Generated by Django 5.2.15 on 2026-07-31 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0051_itemtemplate_is_revealing_and_more"),
        ("room_features", "0020_preparedground"),
    ]

    operations = [
        migrations.AddField(
            model_name="craftingrecipe",
            name="required_feature_kind",
            field=models.ForeignKey(
                blank=True,
                help_text="When set, the crafter's room must carry an active RoomFeatureInstance of this kind (#2862 — generalizes the LAB hardcode; e.g. the Workshop of Iniquity gates illicit refinement). Independent of requires_station.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gated_recipes",
                to="room_features.roomfeaturekind",
            ),
        ),
    ]
