# Generated by Django 5.2.15 on 2026-07-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0052_craftingrecipe_required_feature_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketstall",
            name="stall_kind",
            field=models.CharField(
                choices=[("square", "Market Stall"), ("fence", "Fence")],
                default="square",
                help_text="FENCE (#2862): an NPC buyer of last resort — pays a cut rate, asks no questions about provenance, and dealing vice through it mints heat weighted by the local AreaLaw.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="marketsale",
            name="kind",
            field=models.CharField(
                choices=[
                    ("stock", "NPC Stock"),
                    ("ware", "Ware"),
                    ("service", "Crafting Service"),
                    ("fence", "Fenced Goods"),
                ],
                max_length=10,
            ),
        ),
    ]
