# Generated by Django 5.2.15 on 2026-08-02 01:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

import core.natural_keys


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0055_itemtemplate_weapon_class"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeaponClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                (
                    "strength_tenths",
                    models.PositiveSmallIntegerField(
                        help_text="Strength's share of the blend, in tenths (0-10). Agility's share is 10 minus this value. 10 = pure strength (e.g. a maul), 0 = pure agility (e.g. a crossbow — stored mechanical energy, no physical pull).",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "gear_archetype",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("light_armor", "Light Armor"),
                            ("medium_armor", "Medium Armor"),
                            ("heavy_armor", "Heavy Armor"),
                            ("robe", "Robe"),
                            ("melee_one_hand", "One-Handed Melee"),
                            ("melee_two_hand", "Two-Handed Melee"),
                            ("ranged", "Ranged"),
                            ("thrown", "Thrown"),
                            ("shield", "Shield"),
                            ("lance", "Lance"),
                            ("jewelry", "Jewelry"),
                            ("clothing", "Clothing"),
                            ("other", "Other"),
                        ],
                        default="",
                        help_text="Typical archetype for this weapon class, advisory only. ItemTemplate.gear_archetype remains authoritative for physics gates (wind penalty, lance maneuvers, hands, covenant gear compatibility) — this field does not drive them.",
                        max_length=20,
                    ),
                ),
                (
                    "default_damage",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Reference damage at Common quality; authored templates set their own.",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.AlterField(
            model_name="itemtemplate",
            name="weapon_class",
            field=models.ForeignKey(
                blank=True,
                help_text="Weighted strength/agility blend for combat stat-override (#2879). Null = fall back to gear_archetype mapping.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="item_templates",
                to="items.weaponclass",
            ),
        ),
    ]
