# Generated by Django 5.2.15 on 2026-08-01 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0057_crafteditemrecipe_crafter_persona_and_more"),
        ("mechanics", "0015_modifiertarget_styleable_adjective"),
        ("projects", "0024_alter_contributionmethod_kind_alter_project_kind_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemRefinementDetails",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="item_refinement_details",
                        serialize=False,
                        to="projects.project",
                    ),
                ),
                (
                    "accent_target",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Accent axis being raised/added; null = base quality.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refinement_projects",
                        to="mechanics.modifiertarget",
                    ),
                ),
                (
                    "item_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refinement_projects",
                        to="items.iteminstance",
                    ),
                ),
            ],
        ),
    ]
