# Generated by Django 5.2.15 on 2026-08-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0065_cachetwallet_silhouettevoguemomentum_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equippeditem",
            name="revealed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set by the Reveal action (#2965): a deliberately revealed piece counts for social-facing effects despite covering layers. The state dies with this row on unequip — no cleanup needed.",
                null=True,
            ),
        ),
    ]
