# Generated by Django 5.2.4 on 2026-04-13 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("character_sheets", "0001_initial"),
        ("realms", "0001_initial"),
        ("roster", "0001_initial"),
        ("species", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="family",
            field=models.ForeignKey(
                blank=True,
                help_text="Character's family. Null for orphans/unknown lineage.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="roster.family",
            ),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="origin_realm",
            field=models.ForeignKey(
                blank=True,
                help_text="Realm/homeland the character is from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="character_sheets",
                to="realms.realm",
            ),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="species",
            field=models.ForeignKey(
                blank=True,
                help_text="Character's species (may have parent for subspecies)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="character_sheets",
                to="species.species",
            ),
        ),
    ]
