# Generated by Django 5.2.4 on 2025-08-10 03:58

from django.db import migrations


def add_basic_characteristics(apps, schema_editor):
    """Add basic characteristic types and values that characters can have."""
    Characteristic = apps.get_model("character_sheets", "Characteristic")
    CharacteristicValue = apps.get_model("character_sheets", "CharacteristicValue")

    # Create basic characteristic types
    eye_color = Characteristic.objects.create(
        name="eye_color",
        display_name="Eye Color",
        description="The color of the character's eyes",
    )

    hair_color = Characteristic.objects.create(
        name="hair_color",
        display_name="Hair Color",
        description="The color of the character's hair",
    )

    height = Characteristic.objects.create(
        name="height",
        display_name="Height",
        description="The character's height category",
    )

    skin_tone = Characteristic.objects.create(
        name="skin_tone",
        display_name="Skin Tone",
        description="The character's skin tone",
    )

    # Add eye color values
    eye_colors = ["blue", "green", "brown", "hazel", "gray", "amber", "violet"]
    for color in eye_colors:
        CharacteristicValue.objects.create(
            characteristic=eye_color, value=color, display_value=color.title()
        )

    # Add hair color values
    hair_colors = [
        "black",
        "brown",
        "blonde",
        "red",
        "gray",
        "white",
        "auburn",
        "silver",
    ]
    for color in hair_colors:
        CharacteristicValue.objects.create(
            characteristic=hair_color, value=color, display_value=color.title()
        )

    # Add height values
    heights = ["very_short", "short", "average", "tall", "very_tall"]
    height_displays = ["Very Short", "Short", "Average Height", "Tall", "Very Tall"]
    for height_val, display in zip(heights, height_displays):
        CharacteristicValue.objects.create(
            characteristic=height, value=height_val, display_value=display
        )

    # Add skin tone values
    skin_tones = [
        "very_pale",
        "pale",
        "fair",
        "olive",
        "tan",
        "brown",
        "dark_brown",
        "very_dark",
    ]
    tone_displays = [
        "Very Pale",
        "Pale",
        "Fair",
        "Olive",
        "Tan",
        "Brown",
        "Dark Brown",
        "Very Dark",
    ]
    for tone_val, display in zip(skin_tones, tone_displays):
        CharacteristicValue.objects.create(
            characteristic=skin_tone, value=tone_val, display_value=display
        )


def remove_basic_characteristics(apps, schema_editor):
    """Remove the basic characteristics if rolling back."""
    Characteristic = apps.get_model("character_sheets", "Characteristic")
    Characteristic.objects.filter(
        name__in=["eye_color", "hair_color", "height", "skin_tone"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("character_sheets", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_basic_characteristics, remove_basic_characteristics),
    ]
