# Generated by Django 5.2.4 on 2026-03-22 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("character_sheets", "0001_initial"),
        ("forms", "0001_initial"),
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
        ("realms", "0001_initial"),
        ("roster", "0001_initial"),
        ("scenes", "0001_initial"),
        ("species", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="characteridentity",
            name="active_persona",
            field=models.ForeignKey(
                blank=True,
                help_text="Who this character is presenting as right now. Nullable to break the circular FK with Persona.character_identity during creation; ensure_character_identity() always sets this immediately.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="active_for_identities",
                to="scenes.persona",
            ),
        ),
        migrations.AddField(
            model_name="characteridentity",
            name="character",
            field=models.OneToOneField(
                help_text="The character this identity belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_identity",
                to="objects.objectdb",
            ),
        ),
        migrations.AddField(
            model_name="characteristicvalue",
            name="allowed_for_species",
            field=models.ManyToManyField(
                blank=True,
                help_text="Species this value is allowed for (empty = all species)",
                related_name="allowed_characteristic_values",
                to="species.species",
            ),
        ),
        migrations.AddField(
            model_name="characteristicvalue",
            name="characteristic",
            field=models.ForeignKey(
                help_text="The characteristic type this value belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="character_sheets.characteristic",
            ),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="build",
            field=models.ForeignKey(
                blank=True,
                help_text="Character's body type",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="character_sheets",
                to="forms.build",
            ),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="family",
            field=models.ForeignKey(
                blank=True,
                help_text="Character's family. Null for orphans/unknown lineage.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="roster.family",
            ),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="origin_realm",
            field=models.ForeignKey(
                blank=True,
                help_text="Realm/homeland the character is from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="character_sheets",
                to="realms.realm",
            ),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="species",
            field=models.ForeignKey(
                blank=True,
                help_text="Character's species (may have parent for subspecies)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="character_sheets",
                to="species.species",
            ),
        ),
    ]
