# Generated by Django 5.2.4 on 2026-01-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character_sheets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="pronoun_object",
            field=models.CharField(
                default="them",
                help_text="Object pronoun (e.g., 'him', 'her', 'them')",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="pronoun_possessive",
            field=models.CharField(
                default="their",
                help_text="Possessive pronoun (e.g., 'his', 'her', 'their')",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="charactersheet",
            name="pronoun_subject",
            field=models.CharField(
                default="they",
                help_text="Subject pronoun (e.g., 'he', 'she', 'they')",
                max_length=20,
            ),
        ),
    ]
