# Generated by Django 5.2.4 on 2026-03-22 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("character_sheets", "0003_initial"),
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
        ("scenes", "0003_partition_interaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active_guise",
                    models.ForeignKey(
                        help_text="Which identity they're currently presenting as. Defaults to primary_guise.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="active_for_identities",
                        to="character_sheets.guise",
                    ),
                ),
                (
                    "active_persona",
                    models.ForeignKey(
                        help_text="Current appearance. Defaults to active_guise's default persona.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="active_for_identities",
                        to="scenes.persona",
                    ),
                ),
                (
                    "character",
                    models.OneToOneField(
                        help_text="The character this identity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_identity",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "primary_guise",
                    models.ForeignKey(
                        help_text="The character's 'real' identity. Always exists, never null.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_for_identities",
                        to="character_sheets.guise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Identity",
                "verbose_name_plural": "Character Identities",
            },
        ),
    ]
