# Generated by Django 5.2.4 on 2026-01-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character_sheets", "0004_add_physical_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="guise",
            name="is_persistent",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is an established alias (can join orgs) vs a temporary disguise (cannot join orgs)",
            ),
        ),
    ]
