# Generated by Django 5.2.14 on 2026-06-15 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("character_sheets", "0005_charactersheet_max_active_npc_missions"),
        ("scenes", "0021_persona_prestige_from_fashion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactersheet",
            name="active_persona",
            field=models.ForeignKey(
                blank=True,
                help_text="The face this character is currently presenting as (#981); NULL ⇒ PRIMARY. Resolve via active_persona_for_sheet; set only via set_active_persona — never gate IC reads on primary_persona directly.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="scenes.persona",
            ),
        ),
    ]
