# Generated by Django 5.2.15 on 2026-07-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character_sheets", "0013_charactersheet_durance_cohort_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charactersheet",
            name="lifecycle_state",
            field=models.CharField(
                choices=[
                    ("ALIVE", "Alive"),
                    ("CAPTURED", "Captured"),
                    ("UNKNOWN", "Whereabouts unknown"),
                    ("COMA", "Coma"),
                    ("RETIRED", "Retired"),
                    ("DEAD", "Dead"),
                ],
                default="ALIVE",
                help_text="IC condition. ALIVE / CAPTURED / UNKNOWN / COMA / RETIRED / DEAD. CAPTURED means someone is holding them; UNKNOWN means their whereabouts are genuinely unknown in-world (#2728). Orthogonal to activity_state — both must be ALIVE+ACTIVE for the character to count as 'present and playing' to consumer systems.",
                max_length=8,
            ),
        ),
    ]
