# Generated by Django 5.2.14 on 2026-06-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("narrative", "0006_alter_narrativemessage_category_usercategorymute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="narrativemessage",
            name="category",
            field=models.CharField(
                choices=[
                    ("story", "Story update"),
                    ("atmosphere", "Atmosphere"),
                    ("visions", "Visions"),
                    ("happenstance", "Happenstance"),
                    ("system", "System"),
                    ("covenant", "Covenant"),
                    ("renown", "Renown"),
                    ("weather", "Weather"),
                    ("ability", "Ability access"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usercategorymute",
            name="category",
            field=models.CharField(
                choices=[
                    ("story", "Story update"),
                    ("atmosphere", "Atmosphere"),
                    ("visions", "Visions"),
                    ("happenstance", "Happenstance"),
                    ("system", "System"),
                    ("covenant", "Covenant"),
                    ("renown", "Renown"),
                    ("weather", "Weather"),
                    ("ability", "Ability access"),
                ],
                max_length=20,
            ),
        ),
    ]
