# Generated by Django 5.2.14 on 2026-05-24 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("achievements", "0001_initial"),
        ("character_sheets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterachievement",
            name="character_sheet",
            field=models.ForeignKey(
                help_text="The character who earned this achievement",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achievements",
                to="character_sheets.charactersheet",
            ),
        ),
    ]
