# Generated by Django 5.2.4 on 2026-05-14 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0002_initial"),
        (
            "conditions",
            "0007_remove_treatmentattempt_unique_treatment_attempt_per_helper_scene_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ConditionStatRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(choices=[("gained", "Condition gained")], max_length=32),
                ),
                ("increment_amount", models.PositiveIntegerField(default=1)),
                (
                    "condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stat_rules_for",
                        to="conditions.conditiontemplate",
                    ),
                ),
                (
                    "stat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condition_rules",
                        to="achievements.statdefinition",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("stat", "condition", "event_type"),
                        name="unique_condition_stat_rule",
                    )
                ],
            },
        ),
    ]
