# Generated by Django 5.2.14 on 2026-06-27 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0003_initial"),
        ("character_sheets", "0010_remove_charactersheet_family_and_more"),
        ("mechanics", "0006_modifiersource_achievement_reward"),
    ]

    operations = [
        migrations.AddField(
            model_name="rewarddefinition",
            name="modifier_target",
            field=models.ForeignKey(
                blank=True,
                help_text="For BONUS rewards: which stat the bonus modifies (e.g. allure). The amount comes from AchievementReward.reward_value.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reward_definitions",
                to="mechanics.modifiertarget",
            ),
        ),
        migrations.AlterField(
            model_name="rewarddefinition",
            name="reward_type",
            field=models.CharField(
                choices=[
                    ("title", "Title"),
                    ("bonus", "Mechanical Bonus"),
                    ("cosmetic", "Cosmetic"),
                    ("prestige", "Prestige"),
                ],
                help_text="The category of reward",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CharacterTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="titles",
                        to="character_sheets.charactersheet",
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        help_text="The TITLE-type RewardDefinition this title comes from.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_titles",
                        to="achievements.rewarddefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["character_sheet", "reward"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character_sheet", "reward"),
                        name="unique_character_title",
                    )
                ],
            },
        ),
    ]
