# Generated by Django 5.2.14 on 2026-07-03 04:38

from django.db import migrations, models

import core.natural_keys


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActionEnhancement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_action_key", models.CharField(db_index=True, max_length=100)),
                ("variant_name", models.CharField(max_length=100)),
                ("is_involuntary", models.BooleanField(default=False)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("distinction", "Distinction"),
                            ("condition", "Condition"),
                            ("technique", "Technique"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name (e.g., 'Fire Bolt', 'Pick Lock').",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Narrative description of this action."),
                ),
                (
                    "pipeline",
                    models.CharField(
                        choices=[
                            ("single", "Single Check"),
                            ("gated", "Gated (with prerequisite checks)"),
                        ],
                        default="single",
                        help_text="Resolution pattern: SINGLE (one check) or GATED (prerequisite checks first).",
                        max_length=20,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("self", "Self"),
                            ("single", "Single Target"),
                            ("area", "Area"),
                            ("filtered_group", "Filtered Group"),
                        ],
                        default="self",
                        help_text="What kind of target this action operates on.",
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Frontend icon identifier.", max_length=50
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Grouping category (e.g., 'magic', 'combat', 'exploration').",
                        max_length=50,
                    ),
                ),
                (
                    "accepts_pose_text",
                    models.BooleanField(
                        default=False,
                        help_text="If true, dispatch may carry freeform pose_text echoed with the outcome.",
                    ),
                ),
                (
                    "default_delivery",
                    models.CharField(
                        choices=[
                            ("pose", "Pose (whole room)"),
                            ("whisper", "Whisper (target only)"),
                            ("table_talk", "Table talk (your place)"),
                            ("mutter", "Mutter (partial echo)"),
                        ],
                        default="pose",
                        help_text="Default audience routing for this action's result echo (#903). Intimate/suggestive socials should author WHISPER; players may override per use.",
                        max_length=20,
                    ),
                ),
                (
                    "ap_cost",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Action points charged on resolution (abstracted time).",
                    ),
                ),
                (
                    "social_fatigue_cost",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Base social fatigue charged on resolution, scaled by effort_level.",
                    ),
                ),
                (
                    "difficulty_tier_modifier",
                    models.IntegerField(
                        default=0,
                        help_text="Shifts this action's resolved difficulty by N tiers relative to the derived base (#1697). Seduce = +1 (one tier harder than Flirt). 0 for ordinary actions.",
                    ),
                ),
                (
                    "grants_entry_flourish",
                    models.BooleanField(
                        default=False,
                        help_text="If True, a successful dispatch of this action triggers an entry flourish resonance grant for the actor (used by the Entrance social action).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action Template",
                "verbose_name_plural": "Action Templates",
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ActionTemplateGate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gate_role",
                    models.CharField(
                        choices=[("activation", "Activation")],
                        default="activation",
                        help_text="Semantic role of this gate.",
                        max_length=20,
                    ),
                ),
                (
                    "step_order",
                    models.IntegerField(
                        default=0,
                        help_text="Execution order (lower = earlier). Negative = before main step.",
                    ),
                ),
                (
                    "failure_aborts",
                    models.BooleanField(
                        default=True,
                        help_text="If True, failing this gate stops the pipeline.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action Template Gate",
                "verbose_name_plural": "Action Template Gates",
                "ordering": ["step_order"],
            },
        ),
        migrations.CreateModel(
            name="AddModifierConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("execution_order", models.PositiveIntegerField(default=0)),
                ("modifier_key", models.CharField(max_length=50)),
                ("modifier_value", models.IntegerField()),
            ],
            options={
                "ordering": ["execution_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConditionOnCheckConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("execution_order", models.PositiveIntegerField(default=0)),
                (
                    "target_difficulty",
                    models.IntegerField(
                        blank=True,
                        help_text="Fixed difficulty fallback for NPCs/missions.",
                        null=True,
                    ),
                ),
                ("severity", models.PositiveIntegerField(default=1)),
                ("duration_rounds", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "immunity_duration",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "source_description",
                    models.CharField(
                        blank=True,
                        help_text="Narrative label for the condition source (e.g. 'Alluring Whisper').",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "ordering": ["execution_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConsequencePool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable pool name (e.g., 'Wild Magic Surge').",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="GM authoring context for this pool."),
                ),
            ],
            options={
                "verbose_name": "Consequence Pool",
                "verbose_name_plural": "Consequence Pools",
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ConsequencePoolEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight_override",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Overrides Consequence.weight for this pool. Null uses default.",
                        null=True,
                    ),
                ),
                (
                    "is_excluded",
                    models.BooleanField(
                        default=False,
                        help_text="If True, suppresses this consequence when inherited from parent.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consequence Pool Entry",
                "verbose_name_plural": "Consequence Pool Entries",
            },
        ),
        migrations.CreateModel(
            name="ModifyKwargsConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("execution_order", models.PositiveIntegerField(default=0)),
                ("kwarg_name", models.CharField(max_length=50)),
                (
                    "transform",
                    models.CharField(
                        choices=[
                            ("uppercase", "Uppercase"),
                            ("lowercase", "Lowercase"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["execution_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RemoveConditionOnCheckConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("execution_order", models.PositiveIntegerField(default=0)),
                (
                    "target_difficulty",
                    models.IntegerField(
                        blank=True,
                        help_text="Fixed difficulty fallback for NPCs/missions.",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["execution_order"],
                "abstract": False,
            },
        ),
    ]
