# Generated by Django 5.2.4 on 2026-03-03 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("checks", "0001_initial"),
        ("conditions", "0002_initial"),
        ("distinctions", "0002_initial"),
        ("magic", "0002_characteraura_glimpse_story"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionEnhancement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_action_key", models.CharField(db_index=True, max_length=100)),
                ("variant_name", models.CharField(max_length=100)),
                ("is_involuntary", models.BooleanField(default=False)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("distinction", "Distinction"),
                            ("condition", "Condition"),
                            ("technique", "Technique"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "condition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_enhancements",
                        to="conditions.conditiontemplate",
                    ),
                ),
                (
                    "distinction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_enhancements",
                        to="distinctions.distinction",
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_enhancements",
                        to="magic.technique",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AddModifierConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("execution_order", models.PositiveIntegerField(default=0)),
                ("modifier_key", models.CharField(max_length=50)),
                ("modifier_value", models.IntegerField()),
                (
                    "enhancement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_configs",
                        to="actions.actionenhancement",
                    ),
                ),
            ],
            options={
                "ordering": ["execution_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConditionOnCheckConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("execution_order", models.PositiveIntegerField(default=0)),
                (
                    "target_difficulty",
                    models.IntegerField(
                        blank=True,
                        help_text="Fixed difficulty fallback for NPCs/missions.",
                        null=True,
                    ),
                ),
                ("severity", models.PositiveIntegerField(default=1)),
                ("duration_rounds", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "immunity_duration",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "source_description",
                    models.CharField(
                        blank=True,
                        help_text="Narrative label for the condition source (e.g. 'Alluring Whisper').",
                        max_length=200,
                    ),
                ),
                (
                    "check_type",
                    models.ForeignKey(
                        help_text="Attacker's check type (weighted trait combination).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="checks.checktype",
                    ),
                ),
                (
                    "condition",
                    models.ForeignKey(
                        help_text="Condition to apply on successful check.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="conditions.conditiontemplate",
                    ),
                ),
                (
                    "enhancement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_configs",
                        to="actions.actionenhancement",
                    ),
                ),
                (
                    "immunity_condition",
                    models.ForeignKey(
                        blank=True,
                        help_text="Condition to apply on failed check (short-term immunity).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="conditions.conditiontemplate",
                    ),
                ),
                (
                    "resistance_check_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Defender's resistance check type. Null = use target_difficulty.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="checks.checktype",
                    ),
                ),
            ],
            options={
                "ordering": ["execution_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ModifyKwargsConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("execution_order", models.PositiveIntegerField(default=0)),
                ("kwarg_name", models.CharField(max_length=50)),
                (
                    "transform",
                    models.CharField(
                        choices=[
                            ("uppercase", "Uppercase"),
                            ("lowercase", "Lowercase"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "enhancement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_configs",
                        to="actions.actionenhancement",
                    ),
                ),
            ],
            options={
                "ordering": ["execution_order"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="actionenhancement",
            index=models.Index(
                fields=["base_action_key", "is_involuntary"],
                name="actions_act_base_ac_9122ed_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="actionenhancement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("condition__isnull", True),
                        ("distinction__isnull", False),
                        ("source_type", "distinction"),
                        ("technique__isnull", True),
                    ),
                    models.Q(
                        ("condition__isnull", False),
                        ("distinction__isnull", True),
                        ("source_type", "condition"),
                        ("technique__isnull", True),
                    ),
                    models.Q(
                        ("condition__isnull", True),
                        ("distinction__isnull", True),
                        ("source_type", "technique"),
                        ("technique__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="action_enhancement_exactly_one_source",
            ),
        ),
    ]
