# Generated by Django 5.2.4 on 2026-04-13 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("actions", "0001_initial"),
        ("conditions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionenhancement",
            name="condition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="action_enhancements",
                to="conditions.conditiontemplate",
            ),
        ),
    ]
