# Generated by Django 5.2.14 on 2026-06-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0005_actiontemplate_accepts_pose_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="actiontemplate",
            name="default_delivery",
            field=models.CharField(
                choices=[
                    ("pose", "Pose (whole room)"),
                    ("whisper", "Whisper (target only)"),
                    ("table_talk", "Table talk (your place)"),
                ],
                default="pose",
                help_text="Default audience routing for this action's result echo (#903). Intimate/suggestive socials should author WHISPER; players may override per use.",
                max_length=20,
            ),
        ),
    ]
