# Generated by Django 5.2.14 on 2026-06-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0010_actiontemplate_consent_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="actiontemplate",
            name="difficulty_tier_modifier",
            field=models.IntegerField(
                default=0,
                help_text="Shifts this action's resolved difficulty by N tiers relative to the derived base (#1697). Seduce = +1 (one tier harder than Flirt). 0 for ordinary actions.",
            ),
        ),
    ]
