# Generated by Django 5.2.14 on 2026-07-02 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("battles", "0003_battle_afk_peril_override"),
        ("character_sheets", "0010_remove_charactersheet_family_and_more"),
        ("magic", "0075_alter_resonancegrant_source_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="battleunit",
            name="unit_type",
        ),
        migrations.AddField(
            model_name="battleplace",
            name="movement_cost",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Authored cost for a future reposition action (#1712) to consume. This field is data only — #1711 does not build a movement action.",
            ),
        ),
        migrations.AddField(
            model_name="battleplace",
            name="terrain_type",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("difficult", "Difficult"),
                    ("fortified", "Fortified"),
                    ("elevated", "Elevated"),
                    ("flooded", "Flooded"),
                    ("urban", "Urban"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="battleside",
            name="posture",
            field=models.CharField(
                choices=[
                    ("balanced", "Balanced"),
                    ("aggressive", "Aggressive"),
                    ("defensive", "Defensive"),
                ],
                default="balanced",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="battleunit",
            name="commander",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional commander whose Battle Command modifier bonus applies to participants fighting alongside this unit's side/place.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commanded_battle_units",
                to="character_sheets.charactersheet",
            ),
        ),
        migrations.AddField(
            model_name="battleunit",
            name="composition",
            field=models.CharField(
                choices=[
                    ("infantry", "Infantry"),
                    ("cavalry", "Cavalry"),
                    ("archers", "Archers"),
                    ("siege", "Siege"),
                    ("flying", "Flying"),
                    ("naval", "Naval"),
                    ("magical", "Magical"),
                    ("irregular", "Irregular"),
                ],
                default="irregular",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="battleunit",
            name="descriptor",
            field=models.CharField(
                blank=True,
                help_text="Optional flavor tag (e.g. 'zombies-on-nightmares'). Narrative only — composition/quality below drive mechanics.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="battleunit",
            name="quality",
            field=models.CharField(
                choices=[
                    ("militia", "Militia"),
                    ("levy", "Levy"),
                    ("trained", "Trained"),
                    ("veteran", "Veteran"),
                    ("elite", "Elite"),
                ],
                default="trained",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="battleunit",
            name="summoned_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this unit was created via a military-grade summon (#1711).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="summoned_battle_units",
                to="character_sheets.charactersheet",
            ),
        ),
        migrations.CreateModel(
            name="TerrainCompositionEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "terrain_type",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("difficult", "Difficult"),
                            ("fortified", "Fortified"),
                            ("elevated", "Elevated"),
                            ("flooded", "Flooded"),
                            ("urban", "Urban"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "composition",
                    models.CharField(
                        choices=[
                            ("infantry", "Infantry"),
                            ("cavalry", "Cavalry"),
                            ("archers", "Archers"),
                            ("siege", "Siege"),
                            ("flying", "Flying"),
                            ("naval", "Naval"),
                            ("magical", "Magical"),
                            ("irregular", "Irregular"),
                        ],
                        max_length=20,
                    ),
                ),
                ("modifier", models.SmallIntegerField()),
            ],
            options={
                "ordering": ["terrain_type", "composition"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("terrain_type", "composition"),
                        name="unique_terrain_composition_effect",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TechniqueCompositionAffinity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "composition",
                    models.CharField(
                        choices=[
                            ("infantry", "Infantry"),
                            ("cavalry", "Cavalry"),
                            ("archers", "Archers"),
                            ("siege", "Siege"),
                            ("flying", "Flying"),
                            ("naval", "Naval"),
                            ("magical", "Magical"),
                            ("irregular", "Irregular"),
                        ],
                        max_length=20,
                    ),
                ),
                ("modifier", models.SmallIntegerField()),
                (
                    "technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="battle_composition_affinities",
                        to="magic.technique",
                    ),
                ),
            ],
            options={
                "ordering": ["technique", "composition"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("technique", "composition"),
                        name="unique_technique_composition_affinity",
                    )
                ],
            },
        ),
    ]
