# Generated by Django 5.2.14 on 2026-07-03 23:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("battles", "0013_merge_20260703_2002"),
        ("battles", "0015_alter_battleactiondeclaration_scope"),
    ]

    operations = []
