# Generated by Django 5.2.14 on 2026-07-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battles", "0022_alter_battlevehicle_vehicle_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="battle",
            name="risk_level",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("moderate", "Moderate"),
                    ("high", "High"),
                    ("extreme", "Extreme"),
                    ("lethal", "Lethal"),
                ],
                default="low",
                help_text="Stakes axis for companion death-gating (#1873). EXTREME/LETHAL make companion death possible on defeat. Mirrors CombatEncounter.risk_level.",
                max_length=10,
            ),
        ),
    ]
