# Generated by Django 5.2.14 on 2026-07-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("battles", "0023_battle_risk_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="battle",
            name="is_paused",
            field=models.BooleanField(
                default=False,
                help_text="Set when a participant disconnects (#1899) — see maybe_pause_battle_for_disconnect.",
            ),
        ),
    ]
