# Generated by Django 5.2.14 on 2026-07-10 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("battles", "0024_battle_is_paused"),
        ("conditions", "0016_conditiontemplate_exploitable_tiers"),
        ("mechanics", "0010_situationchallengelink_target_object_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BattleMapBlueprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive blueprints are hidden from the GM staging catalog but not deleted — existing data derived from them may still exist.",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BattleUnitTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "descriptor",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("militia", "Militia"),
                            ("levy", "Levy"),
                            ("trained", "Trained"),
                            ("veteran", "Veteran"),
                            ("elite", "Elite"),
                        ],
                        default="trained",
                        max_length=20,
                    ),
                ),
                ("strength", models.PositiveIntegerField(default=100)),
                ("morale", models.PositiveIntegerField(default=70)),
                (
                    "individual_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Population data point mirroring BattleUnit.individual_count — null means 'not a swarm-style unit'.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive templates are hidden from the GM staging catalog but not deleted.",
                    ),
                ),
                (
                    "properties",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Descriptive tags carried over onto the staged BattleUnit's own properties — see BattleUnit.properties.",
                        related_name="+",
                        to="mechanics.property",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BattleUnitTemplateCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField(default=0)),
                (
                    "capability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="battle_unit_template_values",
                        to="conditions.capabilitytype",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capability_values",
                        to="battles.battleunittemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["template", "capability"],
            },
        ),
        migrations.AddField(
            model_name="battleunittemplate",
            name="capabilities",
            field=models.ManyToManyField(
                blank=True,
                help_text="What a unit staged from this template can DO, at an authored per-template magnitude via BattleUnitTemplateCapability — see BattleUnit.capabilities.",
                related_name="+",
                through="battles.BattleUnitTemplateCapability",
                to="conditions.capabilitytype",
            ),
        ),
        migrations.CreateModel(
            name="BlueprintBattlePlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "terrain_type",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("difficult", "Difficult"),
                            ("fortified", "Fortified"),
                            ("elevated", "Elevated"),
                            ("flooded", "Flooded"),
                            ("urban", "Urban"),
                            ("water", "Open water"),
                            ("aerial", "Open sky"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "movement_cost",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Authored cost carried over onto the staged BattlePlace's own movement_cost — see BattlePlace.movement_cost.",
                    ),
                ),
                (
                    "x",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Position on the blueprint's battle-map coordinate plane, carried over onto the staged BattlePlace's own x/y (#1714).",
                        max_digits=8,
                    ),
                ),
                ("y", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                (
                    "footprint_radius",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="How much of the battle-map grid this place occupies — see BattlePlace.footprint_radius.",
                        max_digits=6,
                    ),
                ),
                (
                    "blueprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="places",
                        to="battles.battlemapblueprint",
                    ),
                ),
            ],
            options={
                "ordering": ["blueprint", "name"],
            },
        ),
        migrations.CreateModel(
            name="BlueprintFortification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("wall", "Wall"),
                            ("gate", "Gate"),
                            ("battlement", "Battlement"),
                            ("hull", "Hull"),
                        ],
                        default="wall",
                        max_length=20,
                    ),
                ),
                (
                    "max_integrity",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Carried over onto the staged Fortification's max_integrity (and starting integrity) — see Fortification.max_integrity.",
                    ),
                ),
                (
                    "defending_side_role",
                    models.CharField(
                        choices=[("attacker", "Attacker"), ("defender", "Defender")],
                        help_text="Which staged BattleSide role this structure protects — resolved to a concrete BattleSide when the blueprint is staged onto a Battle.",
                        max_length=20,
                    ),
                ),
                (
                    "blueprint_place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fortifications",
                        to="battles.blueprintbattleplace",
                    ),
                ),
            ],
            options={
                "ordering": ["blueprint_place", "kind", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="battleunittemplatecapability",
            constraint=models.UniqueConstraint(
                fields=("template", "capability"),
                name="unique_battle_unit_template_capability",
            ),
        ),
        migrations.AddConstraint(
            model_name="blueprintbattleplace",
            constraint=models.UniqueConstraint(
                fields=("blueprint", "name"), name="unique_blueprint_place_name"
            ),
        ),
    ]
