# Generated by Django 5.2.14 on 2026-07-10 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("battles", "0025_battlemapblueprint_battleunittemplate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="battleparticipant",
            name="transit_target_place",
            field=models.ForeignKey(
                blank=True,
                help_text="Destination of an in-progress multi-round MOVE (#2007). Null when at rest.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="participants_in_transit",
                to="battles.battleplace",
            ),
        ),
        migrations.AddField(
            model_name="battleparticipant",
            name="transit_x",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="In-progress MOVE position on the battle-map coordinate plane (#2007). Null when at rest — effective position is then simply this participant's .place coordinates. Mirrors BattlePlace.x's shape.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="battleparticipant",
            name="transit_y",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="battleunit",
            name="transit_target_place",
            field=models.ForeignKey(
                blank=True,
                help_text="Destination of an in-progress multi-round MOVE (#2007). Null when at rest.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="units_in_transit",
                to="battles.battleplace",
            ),
        ),
        migrations.AddField(
            model_name="battleunit",
            name="transit_x",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="In-progress MOVE position on the battle-map coordinate plane (#2007). Null when at rest — effective position is then simply this unit's .place coordinates. Mirrors BattlePlace.x's shape.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="battleunit",
            name="transit_y",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="battleactiondeclaration",
            name="target_place",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when scope=PLACE, or as a MOVE destination regardless of scope (#2007) — null with action_kind=MOVE and scope=UNIT means withdraw.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scoped_declarations",
                to="battles.battleplace",
            ),
        ),
    ]
