# Generated by Django 5.2.15 on 2026-07-14 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("battles", "0031_populate_military_units"),
        ("military", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="battleunit",
            name="capabilities",
        ),
        migrations.AlterModelOptions(
            name="battleunit",
            options={"ordering": ["battle", "side", "military_unit__name"]},
        ),
        migrations.RemoveField(
            model_name="battleunit",
            name="commander",
        ),
        migrations.RemoveField(
            model_name="battleunit",
            name="descriptor",
        ),
        migrations.RemoveField(
            model_name="battleunit",
            name="individual_count",
        ),
        migrations.RemoveField(
            model_name="battleunit",
            name="morale",
        ),
        migrations.RemoveField(
            model_name="battleunit",
            name="name",
        ),
        migrations.RemoveField(
            model_name="battleunit",
            name="properties",
        ),
        migrations.RemoveField(
            model_name="battleunit",
            name="quality",
        ),
        migrations.RemoveField(
            model_name="battleunit",
            name="strength",
        ),
        migrations.RemoveField(
            model_name="battleunit",
            name="summoned_by",
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="battleunit",
            name="military_unit",
            field=models.ForeignKey(
                help_text="The persistent MilitaryUnit this battle unit projects from. All identity and stats live on MilitaryUnit (ADR-0014, ADR-0125).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="battle_units",
                to="military.militaryunit",
            ),
        ),
        migrations.DeleteModel(
            name="BattleUnitCapability",
        ),
    ]
