# Generated by Django 5.2.4 on 2026-01-13 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("species", "0002_remove_speciesareastatbonus_species_area_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeciesOrigin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this origin (e.g., 'Compact Rex'alfar', 'Arvani Human')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Lore description of this species origin"
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        help_text="The species this origin belongs to (can be a sub-species)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="origins",
                        to="species.species",
                    ),
                ),
            ],
            options={
                "verbose_name": "Species Origin",
                "verbose_name_plural": "Species Origins",
                "unique_together": {("species", "name")},
            },
        ),
        migrations.CreateModel(
            name="SpeciesOriginStatBonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stat",
                    models.CharField(
                        choices=[
                            ("strength", "Strength"),
                            ("agility", "Agility"),
                            ("stamina", "Stamina"),
                            ("charm", "Charm"),
                            ("presence", "Presence"),
                            ("intellect", "Intellect"),
                            ("wits", "Wits"),
                            ("willpower", "Willpower"),
                        ],
                        help_text="The stat to modify",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.SmallIntegerField(help_text="Bonus value (+1, -1, +2, etc.)"),
                ),
                (
                    "species_origin",
                    models.ForeignKey(
                        help_text="The species origin this bonus applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stat_bonuses",
                        to="species.speciesorigin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Species Origin Stat Bonus",
                "verbose_name_plural": "Species Origin Stat Bonuses",
                "unique_together": {("species_origin", "stat")},
            },
        ),
    ]
