# Generated by Django 5.2.4 on 2026-01-17 07:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("character_creation", "0013_remove_deprecated_species_models"),
        ("forms", "0001_initial"),
        ("species", "0004_add_species_selection_fields"),
    ]

    operations = [
        # First remove unique_together constraints
        migrations.AlterUniqueTogether(
            name="speciesoriginstatbonus",
            unique_together=set(),
        ),
        # Then remove the FK field
        migrations.RemoveField(
            model_name="speciesoriginstatbonus",
            name="species_origin",
        ),
        # Delete SpeciesOriginStatBonus first (it has FK to SpeciesOrigin)
        migrations.DeleteModel(
            name="SpeciesOriginStatBonus",
        ),
        # Then delete SpeciesOrigin
        migrations.DeleteModel(
            name="SpeciesOrigin",
        ),
    ]
