# Generated by Django 5.2.14 on 2026-07-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Captivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("held", "Held"),
                            ("escaped", "Escaped"),
                            ("rescued", "Rescued"),
                            ("ransomed", "Ransomed"),
                            ("released", "Released"),
                        ],
                        default="held",
                        max_length=20,
                    ),
                ),
                (
                    "offscreen_loss_allowed",
                    models.BooleanField(
                        default=False,
                        help_text="Authored at the consent gate. Intended to gate off-screen loss (False = un-loseable while the player is away), but NO consumer reads it yet — escalation/loss logic that honours it is a later phase. Today it is a recorded intent only.  TODO(#931 followup).",
                    ),
                ),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the captivity ended. Null while HELD.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Captivity",
                "verbose_name_plural": "Captivities",
                "ordering": ["-captured_at"],
            },
        ),
        migrations.CreateModel(
            name="CaptivityConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cell_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Default cell room name (player-visible — author in your voice).",
                        max_length=255,
                    ),
                ),
                (
                    "cell_description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Default cell room description (player-visible — author in your voice).",
                    ),
                ),
                (
                    "clue_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Default rescue-clue name at the capture site (player-visible — your voice).",
                        max_length=255,
                    ),
                ),
                (
                    "clue_description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Default rescue-clue description (player-visible — author in your voice).",
                    ),
                ),
                (
                    "clue_detect_difficulty",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Default Search-check difficulty to spot the rescue clue. Placeholder.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
