# Generated by Django 5.2.14 on 2026-07-03 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("captivity", "0001_initial"),
        ("character_sheets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="captivity",
            name="captive",
            field=models.ForeignKey(
                help_text="The held character (the body, regardless of presented persona).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="captivities",
                to="character_sheets.charactersheet",
            ),
        ),
    ]
