# Generated by Django 5.2.14 on 2026-06-29 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("captivity", "0004_captivityconfig_clue_description_and_more"),
        ("projects", "0004_alter_contributionmethod_kind_alter_project_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="captivity",
            name="ransom_project",
            field=models.ForeignKey(
                blank=True,
                help_text="The crowdfundable RANSOM Project standing in the cell (#1500). Anyone may donate toward it; the instant it's fully funded the captive is freed. The FK lives here (the consumer), keeping the projects app free of any captivity dependency (ADR-0010).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ransom_captivities",
                to="projects.project",
            ),
        ),
    ]
