# Generated by Django 5.2.14 on 2026-06-29 02:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("captivity", "0005_captivity_ransom_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="captivity",
            name="ransom_contract",
        ),
    ]
