# Generated by Django 5.2.15 on 2026-07-14 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("captivity", "0006_remove_captivity_ransom_contract"),
        ("instances", "0001_initial"),
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="captivity",
            name="holding_room",
            field=models.ForeignKey(
                blank=True,
                help_text="The persistent room the captive is held in (e.g. a ship's Brig). Null for instanced-cell captures — set when cell is null.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="held_captivities",
                to="objects.objectdb",
            ),
        ),
        migrations.AddField(
            model_name="captivity",
            name="return_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Where the captive returns on resolution. Used when cell is null (Brig path); falls back to cell.return_location for instanced cells.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="return_captivities",
                to="objects.objectdb",
            ),
        ),
        migrations.AlterField(
            model_name="captivity",
            name="cell",
            field=models.ForeignKey(
                blank=True,
                help_text="The instanced cell this captive is held in (shared by a captured party). Goes null when the cell is torn down on resolution — a resolved captivity outlives its cell so its history survives. Also null for Brig-path captures (holding_room is set instead).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="captivities",
                to="instances.instancedroom",
            ),
        ),
    ]
