# Generated by Django 5.2.4 on 2026-04-04 01:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

import core.natural_keys


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0012_defaultaccount_alter_accountdb_id_account_bot_and_more"),
        ("achievements", "0002_initial"),
        ("character_sheets", "0003_initial"),
        ("classes", "0001_initial"),
        ("game_clock", "0002_gameseason_gameweek"),
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
        ("roster", "0001_initial"),
        ("scenes", "0012_interaction_vote_count"),
        ("traits", "0002_alter_trait_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperiencePointsData",
            fields=[
                (
                    "account",
                    models.OneToOneField(
                        help_text="The account this XP belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="experience_points_data",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "total_earned",
                    models.PositiveIntegerField(default=0, help_text="Total XP earned over time"),
                ),
                (
                    "total_spent",
                    models.PositiveIntegerField(default=0, help_text="Total XP spent over time"),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Experience Points Data",
                "verbose_name_plural": "Experience Points Data",
            },
        ),
        migrations.CreateModel(
            name="KudosClaimCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name (e.g., 'xp', 'cg_points')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name (e.g., 'Convert to XP')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description shown to players explaining this claim option",
                    ),
                ),
                (
                    "kudos_cost",
                    models.PositiveIntegerField(
                        help_text="How many kudos required for one unit of reward"
                    ),
                ),
                (
                    "reward_amount",
                    models.PositiveIntegerField(
                        help_text="How much reward is granted per kudos_cost spent"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this claim type is currently available",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kudos Claim Category",
                "verbose_name_plural": "Kudos Claim Categories",
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="KudosPointsData",
            fields=[
                (
                    "account",
                    models.OneToOneField(
                        help_text="The account this kudos belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="kudos_points_data",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "total_earned",
                    models.PositiveIntegerField(
                        default=0, help_text="Total kudos earned over time"
                    ),
                ),
                (
                    "total_claimed",
                    models.PositiveIntegerField(
                        default=0, help_text="Total kudos claimed/converted over time"
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kudos Points Data",
                "verbose_name_plural": "Kudos Points Data",
            },
        ),
        migrations.CreateModel(
            name="KudosSourceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name (e.g., 'player_vote', 'death_bonus')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name (e.g., 'Player Vote', 'Graceful Character Death')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this category rewards",
                    ),
                ),
                (
                    "default_amount",
                    models.PositiveIntegerField(
                        default=1, help_text="Default kudos amount for this category"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this category is currently available",
                    ),
                ),
                (
                    "staff_only",
                    models.BooleanField(
                        default=False,
                        help_text="If true, only staff can award this type of kudos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kudos Source Category",
                "verbose_name_plural": "Kudos Source Categories",
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="XPCostChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this cost chart",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of when to use this chart"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this chart is active"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ClassLevelUnlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_level",
                    models.PositiveIntegerField(help_text="Level being unlocked"),
                ),
                (
                    "character_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="level_unlocks",
                        to="classes.characterclass",
                    ),
                ),
            ],
            options={
                "ordering": ["character_class", "target_level"],
                "unique_together": {("character_class", "target_level")},
            },
        ),
        migrations.CreateModel(
            name="ClassLevelRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this requirement"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this requirement is active"
                    ),
                ),
                (
                    "minimum_level",
                    models.PositiveIntegerField(help_text="Minimum level required in this class"),
                ),
                (
                    "character_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classes.characterclass",
                    ),
                ),
                (
                    "class_level_unlock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_requirements",
                        to="progression.classlevelunlock",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AchievementRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this requirement"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this requirement is active"
                    ),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        help_text="The achievement required",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="achievements.achievement",
                    ),
                ),
                (
                    "class_level_unlock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_requirements",
                        to="progression.classlevelunlock",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LegendRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this requirement"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this requirement is active"
                    ),
                ),
                (
                    "minimum_legend",
                    models.PositiveIntegerField(help_text="Minimum total legend required"),
                ),
                (
                    "class_level_unlock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_requirements",
                        to="progression.classlevelunlock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legend Requirement",
                "verbose_name_plural": "Legend Requirements",
            },
        ),
        migrations.CreateModel(
            name="LevelRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this requirement"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this requirement is active"
                    ),
                ),
                (
                    "minimum_level",
                    models.PositiveIntegerField(help_text="Minimum character level required"),
                ),
                (
                    "class_level_unlock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_requirements",
                        to="progression.classlevelunlock",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MultiClassLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "minimum_level",
                    models.PositiveIntegerField(help_text="Minimum level required in this class"),
                ),
                (
                    "character_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classes.characterclass",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MultiClassRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this requirement"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this requirement is active"
                    ),
                ),
                (
                    "description_override",
                    models.CharField(
                        blank=True,
                        help_text="Override description (e.g., 'Two different classes at level 6+')",
                        max_length=255,
                    ),
                ),
                (
                    "class_level_unlock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_requirements",
                        to="progression.classlevelunlock",
                    ),
                ),
                (
                    "required_classes",
                    models.ManyToManyField(
                        related_name="multi_requirements",
                        through="progression.MultiClassLevel",
                        to="classes.characterclass",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="multiclasslevel",
            name="multi_class_requirement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_levels",
                to="progression.multiclassrequirement",
            ),
        ),
        migrations.CreateModel(
            name="RelationshipRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this requirement"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this requirement is active"
                    ),
                ),
                (
                    "relationship_target",
                    models.CharField(help_text="Target of the relationship", max_length=100),
                ),
                (
                    "minimum_level",
                    models.PositiveIntegerField(help_text="Minimum relationship level required"),
                ),
                (
                    "class_level_unlock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_requirements",
                        to="progression.classlevelunlock",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TierRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this requirement"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this requirement is active"
                    ),
                ),
                (
                    "minimum_tier",
                    models.PositiveIntegerField(
                        help_text="Minimum tier required (1 for levels 1-5, 2 for levels 6-10)"
                    ),
                ),
                (
                    "class_level_unlock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_requirements",
                        to="progression.classlevelunlock",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TraitRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this requirement"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this requirement is active"
                    ),
                ),
                (
                    "minimum_value",
                    models.PositiveIntegerField(help_text="Minimum trait value required"),
                ),
                (
                    "class_level_unlock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_requirements",
                        to="progression.classlevelunlock",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trait_requirements",
                        to="traits.trait",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CharacterPathHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this path was selected"
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        help_text="The character this path history belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="path_history",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "path",
                    models.ForeignKey(
                        help_text="The path selected by the character",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="character_selections",
                        to="classes.path",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Path History",
                "verbose_name_plural": "Character Path Histories",
                "ordering": ["character", "path__stage"],
                "indexes": [
                    models.Index(fields=["character"], name="progression_charact_89ec40_idx")
                ],
                "unique_together": {("character", "path")},
            },
        ),
        migrations.CreateModel(
            name="CharacterUnlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_level",
                    models.PositiveIntegerField(help_text="Level unlocked for this class"),
                ),
                ("unlocked_date", models.DateTimeField(auto_now_add=True)),
                (
                    "xp_spent",
                    models.PositiveIntegerField(
                        default=0, help_text="XP actually spent on this unlock"
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlocks",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "character_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_unlocks",
                        to="classes.characterclass",
                    ),
                ),
            ],
            options={
                "ordering": ["-unlocked_date"],
                "indexes": [
                    models.Index(
                        fields=["character", "-unlocked_date"],
                        name="progression_charact_e0cfbd_idx",
                    )
                ],
                "unique_together": {("character", "character_class", "target_level")},
            },
        ),
        migrations.CreateModel(
            name="CharacterXP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_earned",
                    models.PositiveIntegerField(default=0, help_text="Total XP earned"),
                ),
                (
                    "total_spent",
                    models.PositiveIntegerField(default=0, help_text="Total XP spent"),
                ),
                (
                    "transferable",
                    models.BooleanField(
                        default=True,
                        help_text="If False, XP is locked to this character and cannot be transferred",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_xp",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character XP",
                "verbose_name_plural": "Character XP",
                "indexes": [
                    models.Index(
                        fields=["character", "transferable"],
                        name="progression_charact_afa84c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CharacterXPTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="XP change (positive for awards, negative for spending)"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("xp_purchase", "XP Purchase"),
                            ("cg_conversion", "CG Point Conversion"),
                            ("scene_award", "Scene Award"),
                            ("gm_award", "GM Award"),
                            ("system_award", "System Award"),
                            ("refund", "Refund"),
                            ("correction", "GM Correction"),
                            ("kudos_claim", "Kudos Claim"),
                            ("first_impression", "First Impression"),
                            ("vote_reward", "Vote Reward"),
                            ("memorable_pose", "Memorable Pose"),
                            ("random_scene", "Random Scene"),
                            ("other", "Other"),
                        ],
                        help_text="Reason for this transaction",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable description",
                        max_length=255,
                    ),
                ),
                (
                    "transferable",
                    models.BooleanField(default=True, help_text="Whether this XP is transferable"),
                ),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="character_xp_transactions",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_date"],
                "indexes": [
                    models.Index(
                        fields=["character", "-transaction_date"],
                        name="progression_charact_75baee_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DevelopmentPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_earned",
                    models.PositiveIntegerField(
                        default=0, help_text="Total development points earned"
                    ),
                ),
                (
                    "rust_debt",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Rust debt that must be paid off before dp counts toward advancement",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="development_points",
                        to="character_sheets.charactersheet",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="development_points",
                        to="traits.trait",
                    ),
                ),
            ],
            options={
                "ordering": ["character_sheet", "trait"],
                "indexes": [
                    models.Index(
                        fields=["character_sheet", "trait"],
                        name="progression_charact_f357e6_idx",
                    )
                ],
                "unique_together": {("character_sheet", "trait")},
            },
        ),
        migrations.CreateModel(
            name="DevelopmentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("scene", "Scene Participation"),
                            ("training", "Training Activity"),
                            ("practice", "Practice Session"),
                            ("teaching", "Teaching Others"),
                            ("quest", "Quest Completion"),
                            ("exploration", "Exploration"),
                            ("crafting", "Crafting Activity"),
                            ("combat", "Combat Encounter"),
                            ("social", "Social Activity"),
                            ("rust", "Skill Rust"),
                            ("other", "Other Activity"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(help_text="Development points awarded and applied"),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("xp_purchase", "XP Purchase"),
                            ("cg_conversion", "CG Point Conversion"),
                            ("scene_award", "Scene Award"),
                            ("gm_award", "GM Award"),
                            ("system_award", "System Award"),
                            ("refund", "Refund"),
                            ("correction", "GM Correction"),
                            ("kudos_claim", "Kudos Claim"),
                            ("first_impression", "First Impression"),
                            ("vote_reward", "Vote Reward"),
                            ("memorable_pose", "Memorable Pose"),
                            ("random_scene", "Random Scene"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="development_transactions",
                        to="character_sheets.charactersheet",
                    ),
                ),
                (
                    "gm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="development_transactions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="scenes.scene",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="development_transactions",
                        to="traits.trait",
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_date"],
                "indexes": [
                    models.Index(
                        fields=["character_sheet", "-transaction_date"],
                        name="progression_charact_f786c3_idx",
                    ),
                    models.Index(
                        fields=["trait", "-transaction_date"],
                        name="progression_trait_i_68c284_idx",
                    ),
                    models.Index(
                        fields=["scene", "-transaction_date"],
                        name="progression_scene_i_164f7a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="KudosTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Kudos change (positive for awards, negative for claims)"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Visible description explaining why kudos was awarded/claimed",
                        max_length=500,
                    ),
                ),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kudos_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "awarded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Account that awarded this kudos (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kudos_awarded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        help_text="Character involved (e.g., for death bonus)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kudos_transactions",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "claim_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Claim category for claims (null for awards)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="progression.kudosclaimcategory",
                    ),
                ),
                (
                    "source_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source category for awards (null for claims)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="progression.kudossourcecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_date"],
                "indexes": [
                    models.Index(
                        fields=["account", "-transaction_date"],
                        name="progression_account_dded4e_idx",
                    ),
                    models.Index(
                        fields=["source_category", "-transaction_date"],
                        name="progression_source__6342be_idx",
                    ),
                    models.Index(
                        fields=["claim_category", "-transaction_date"],
                        name="progression_claim_c_2246a9_idx",
                    ),
                ],
            },
        ),
        migrations.AlterUniqueTogether(
            name="multiclasslevel",
            unique_together={("multi_class_requirement", "character_class")},
        ),
        migrations.CreateModel(
            name="RandomSceneCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="random_scene_completions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "claimer_entry",
                    models.ForeignKey(
                        help_text="Which of the claimer's characters they were playing",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="random_scene_claimed_as",
                        to="roster.rosterentry",
                    ),
                ),
                (
                    "target_persona",
                    models.ForeignKey(
                        help_text="The target persona that was RP'd with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="random_scene_completed_by",
                        to="scenes.persona",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "target_persona"),
                        name="unique_rs_completion_per_pair",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RandomSceneTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot_number",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("claimed", models.BooleanField(default=False)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "first_time",
                    models.BooleanField(
                        default=False,
                        help_text="First RS completion with this target ever",
                    ),
                ),
                ("rerolled", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="random_scene_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "game_week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="random_scene_targets",
                        to="game_clock.gameweek",
                    ),
                ),
                (
                    "target_persona",
                    models.ForeignKey(
                        help_text="The persona (IC identity) to RP with",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targeted_for_random_scene",
                        to="scenes.persona",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "game_week", "slot_number"),
                        name="unique_rs_target_per_slot",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TraitRatingUnlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_rating",
                    models.PositiveIntegerField(
                        help_text="Rating being unlocked (should be divisible by 10)"
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_unlocks",
                        to="traits.trait",
                    ),
                ),
            ],
            options={
                "ordering": ["trait", "target_rating"],
                "unique_together": {("trait", "target_rating")},
            },
        ),
        migrations.CreateModel(
            name="WeeklySkillUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_earned", models.PositiveIntegerField(default=0)),
                ("check_count", models.PositiveIntegerField(default=0)),
                ("processed", models.BooleanField(default=False)),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_skill_usage",
                        to="character_sheets.charactersheet",
                    ),
                ),
                (
                    "game_week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_usages",
                        to="game_clock.gameweek",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_skill_usage",
                        to="traits.trait",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character_sheet", "trait", "game_week"),
                        name="unique_skill_usage_per_week",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WeeklyVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("interaction", "Interaction"),
                            ("scene_participation", "Scene Participation"),
                            ("journal", "Journal Entry"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "target_id",
                    models.PositiveIntegerField(
                        help_text="PK of the voted-on object (not a FK -- no cascades)"
                    ),
                ),
                (
                    "processed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Set True by the weekly cron after XP is awarded",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author_account",
                    models.ForeignKey(
                        help_text="Account that authored the voted-on content",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "game_week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="game_clock.gameweek",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("voter", "target_type", "target_id", "game_week"),
                        name="unique_vote_per_target_per_week",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WeeklyVoteBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_votes", models.PositiveIntegerField(default=7)),
                ("scene_bonus_votes", models.PositiveIntegerField(default=0)),
                ("votes_spent", models.PositiveIntegerField(default=0)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_vote_budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "game_week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vote_budgets",
                        to="game_clock.gameweek",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "game_week"),
                        name="unique_account_week_budget",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TraitXPCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost_modifier",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Cost modifier as percentage (100 = normal, 150 = 50% more expensive, 80 = 20% cheaper)",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xp_costs",
                        to="traits.trait",
                    ),
                ),
                (
                    "cost_chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trait_costs",
                        to="progression.xpcostchart",
                    ),
                ),
            ],
            options={
                "unique_together": {("trait", "cost_chart")},
            },
        ),
        migrations.CreateModel(
            name="ClassXPCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost_modifier",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Cost modifier as percentage (100 = normal, 150 = 50% more expensive, 80 = 20% cheaper)",
                    ),
                ),
                (
                    "character_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xp_costs",
                        to="classes.characterclass",
                    ),
                ),
                (
                    "cost_chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_costs",
                        to="progression.xpcostchart",
                    ),
                ),
            ],
            options={
                "unique_together": {("character_class", "cost_chart")},
            },
        ),
        migrations.CreateModel(
            name="XPCostEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        help_text="Level (for classes) or rating threshold (for traits)"
                    ),
                ),
                (
                    "xp_cost",
                    models.PositiveIntegerField(help_text="XP cost for this level/rating"),
                ),
                (
                    "chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_entries",
                        to="progression.xpcostchart",
                    ),
                ),
            ],
            options={
                "ordering": ["chart", "level"],
                "unique_together": {("chart", "level")},
            },
        ),
        migrations.CreateModel(
            name="XPTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="XP change (positive for awards, negative for spending)"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("xp_purchase", "XP Purchase"),
                            ("cg_conversion", "CG Point Conversion"),
                            ("scene_award", "Scene Award"),
                            ("gm_award", "GM Award"),
                            ("system_award", "System Award"),
                            ("refund", "Refund"),
                            ("correction", "GM Correction"),
                            ("kudos_claim", "Kudos Claim"),
                            ("first_impression", "First Impression"),
                            ("vote_reward", "Vote Reward"),
                            ("memorable_pose", "Memorable Pose"),
                            ("random_scene", "Random Scene"),
                            ("other", "Other"),
                        ],
                        help_text="Reason for this transaction",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, help_text="Detailed description", max_length=255),
                ),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xp_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        help_text="Character this XP was spent on (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="objects.objectdb",
                    ),
                ),
                (
                    "gm",
                    models.ForeignKey(
                        blank=True,
                        help_text="GM who made this change",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="xp_transactions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_date"],
                "indexes": [
                    models.Index(
                        fields=["account", "-transaction_date"],
                        name="progression_account_33a39c_idx",
                    ),
                    models.Index(
                        fields=["character", "-transaction_date"],
                        name="progression_charact_a7f627_idx",
                    ),
                ],
            },
        ),
    ]
