# Generated by Django 5.2.4 on 2026-03-09 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("progression", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegendRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of this requirement"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this requirement is active"
                    ),
                ),
                (
                    "minimum_legend",
                    models.PositiveIntegerField(help_text="Minimum total legend required"),
                ),
                (
                    "class_level_unlock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_requirements",
                        to="progression.classlevelunlock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legend Requirement",
                "verbose_name_plural": "Legend Requirements",
            },
        ),
    ]
