# Generated by Django 5.2.4 on 2026-04-01 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("progression", "0002_alter_characterxptransaction_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_start",
                    models.DateField(help_text="Monday of the voting week (ISO week start)"),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("interaction", "Interaction"),
                            ("scene_participation", "Scene Participation"),
                            ("journal", "Journal Entry"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "target_id",
                    models.PositiveIntegerField(
                        help_text="PK of the voted-on object (not a FK -- no cascades)"
                    ),
                ),
                (
                    "processed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Set True by the weekly cron after XP is awarded",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author_account",
                    models.ForeignKey(
                        help_text="Account that authored the voted-on content",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("voter", "target_type", "target_id", "week_start"),
                        name="unique_vote_per_target_per_week",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WeeklyVoteBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_start",
                    models.DateField(help_text="Monday of the voting week (ISO week start)"),
                ),
                ("base_votes", models.PositiveIntegerField(default=7)),
                ("scene_bonus_votes", models.PositiveIntegerField(default=0)),
                ("votes_spent", models.PositiveIntegerField(default=0)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_vote_budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "week_start"),
                        name="unique_account_week_budget",
                    )
                ],
            },
        ),
    ]
