# Generated by Django 5.2.15 on 2026-07-20 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0005_rewarddefinition_distinction_and_more"),
        ("classes", "0005_classstagehealthrate"),
        ("magic", "0115_covenantroleblendconfig_and_more"),
        ("progression", "0017_majorgifttechniquerequirement"),
        ("relationships", "0011_affectionshift"),
        ("traits", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="achievementrequirement",
            name="achievementrequirement_exactly_one_unlock_target",
        ),
        migrations.RemoveConstraint(
            model_name="classlevelrequirement",
            name="classlevelrequirement_exactly_one_unlock_target",
        ),
        migrations.RemoveConstraint(
            model_name="levelrequirement",
            name="levelrequirement_exactly_one_unlock_target",
        ),
        migrations.RemoveConstraint(
            model_name="majorgifttechniquerequirement",
            name="majorgifttechniquerequirement_exactly_one_unlock_target",
        ),
        migrations.RemoveConstraint(
            model_name="multiclassrequirement",
            name="multiclassrequirement_exactly_one_unlock_target",
        ),
        migrations.RemoveConstraint(
            model_name="relationshiprequirement",
            name="relationshiprequirement_exactly_one_unlock_target",
        ),
        migrations.RemoveConstraint(
            model_name="tierrequirement",
            name="tierrequirement_exactly_one_unlock_target",
        ),
        migrations.RemoveConstraint(
            model_name="traitrequirement",
            name="traitrequirement_exactly_one_unlock_target",
        ),
        migrations.AddField(
            model_name="achievementrequirement",
            name="path",
            field=models.ForeignKey(
                blank=True,
                help_text="Path this requirement gates (#2538). Used for hybrid path entry and cross-path technique learning. Exactly one of class_level_unlock / thread_crossing_threshold / path must be set.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_requirements",
                to="classes.path",
            ),
        ),
        migrations.AddField(
            model_name="classlevelrequirement",
            name="path",
            field=models.ForeignKey(
                blank=True,
                help_text="Path this requirement gates (#2538). Used for hybrid path entry and cross-path technique learning. Exactly one of class_level_unlock / thread_crossing_threshold / path must be set.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_requirements",
                to="classes.path",
            ),
        ),
        migrations.AddField(
            model_name="itemrequirement",
            name="path",
            field=models.ForeignKey(
                blank=True,
                help_text="Path this requirement gates (#2538). Used for hybrid path entry and cross-path technique learning. Exactly one of class_level_unlock / thread_crossing_threshold / path must be set.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_requirements",
                to="classes.path",
            ),
        ),
        migrations.AddField(
            model_name="legendrequirement",
            name="path",
            field=models.ForeignKey(
                blank=True,
                help_text="Path this requirement gates (#2538). Used for hybrid path entry and cross-path technique learning. Exactly one of class_level_unlock / thread_crossing_threshold / path must be set.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_requirements",
                to="classes.path",
            ),
        ),
        migrations.AddField(
            model_name="levelrequirement",
            name="path",
            field=models.ForeignKey(
                blank=True,
                help_text="Path this requirement gates (#2538). Used for hybrid path entry and cross-path technique learning. Exactly one of class_level_unlock / thread_crossing_threshold / path must be set.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_requirements",
                to="classes.path",
            ),
        ),
        migrations.AddField(
            model_name="majorgifttechniquerequirement",
            name="path",
            field=models.ForeignKey(
                blank=True,
                help_text="Path this requirement gates (#2538). Used for hybrid path entry and cross-path technique learning. Exactly one of class_level_unlock / thread_crossing_threshold / path must be set.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_requirements",
                to="classes.path",
            ),
        ),
        migrations.AddField(
            model_name="multiclassrequirement",
            name="path",
            field=models.ForeignKey(
                blank=True,
                help_text="Path this requirement gates (#2538). Used for hybrid path entry and cross-path technique learning. Exactly one of class_level_unlock / thread_crossing_threshold / path must be set.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_requirements",
                to="classes.path",
            ),
        ),
        migrations.AddField(
            model_name="relationshiprequirement",
            name="path",
            field=models.ForeignKey(
                blank=True,
                help_text="Path this requirement gates (#2538). Used for hybrid path entry and cross-path technique learning. Exactly one of class_level_unlock / thread_crossing_threshold / path must be set.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_requirements",
                to="classes.path",
            ),
        ),
        migrations.AddField(
            model_name="tierrequirement",
            name="path",
            field=models.ForeignKey(
                blank=True,
                help_text="Path this requirement gates (#2538). Used for hybrid path entry and cross-path technique learning. Exactly one of class_level_unlock / thread_crossing_threshold / path must be set.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_requirements",
                to="classes.path",
            ),
        ),
        migrations.AddField(
            model_name="traitrequirement",
            name="path",
            field=models.ForeignKey(
                blank=True,
                help_text="Path this requirement gates (#2538). Used for hybrid path entry and cross-path technique learning. Exactly one of class_level_unlock / thread_crossing_threshold / path must be set.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_requirements",
                to="classes.path",
            ),
        ),
        migrations.AlterField(
            model_name="achievementrequirement",
            name="thread_crossing_threshold",
            field=models.ForeignKey(
                blank=True,
                help_text="Thread crossing threshold this requirement gates. Exactly one of class_level_unlock / thread_crossing_threshold / path must be set.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_requirements",
                to="magic.threadcrossingthreshold",
            ),
        ),
        migrations.AlterField(
            model_name="classlevelrequirement",
            name="thread_crossing_threshold",
            field=models.ForeignKey(
                blank=True,
                help_text="Thread crossing threshold this requirement gates. Exactly one of class_level_unlock / thread_crossing_threshold / path must be set.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_requirements",
                to="magic.threadcrossingthreshold",
            ),
        ),
        migrations.AlterField(
            model_name="itemrequirement",
            name="thread_crossing_threshold",
            field=models.ForeignKey(
                blank=True,
                help_text="Thread crossing threshold this requirement gates. Exactly one of class_level_unlock / thread_crossing_threshold / path must be set.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_requirements",
                to="magic.threadcrossingthreshold",
            ),
        ),
        migrations.AlterField(
            model_name="legendrequirement",
            name="thread_crossing_threshold",
            field=models.ForeignKey(
                blank=True,
                help_text="Thread crossing threshold this requirement gates. Exactly one of class_level_unlock / thread_crossing_threshold / path must be set.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_requirements",
                to="magic.threadcrossingthreshold",
            ),
        ),
        migrations.AlterField(
            model_name="levelrequirement",
            name="thread_crossing_threshold",
            field=models.ForeignKey(
                blank=True,
                help_text="Thread crossing threshold this requirement gates. Exactly one of class_level_unlock / thread_crossing_threshold / path must be set.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_requirements",
                to="magic.threadcrossingthreshold",
            ),
        ),
        migrations.AlterField(
            model_name="majorgifttechniquerequirement",
            name="thread_crossing_threshold",
            field=models.ForeignKey(
                blank=True,
                help_text="Thread crossing threshold this requirement gates. Exactly one of class_level_unlock / thread_crossing_threshold / path must be set.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_requirements",
                to="magic.threadcrossingthreshold",
            ),
        ),
        migrations.AlterField(
            model_name="multiclassrequirement",
            name="thread_crossing_threshold",
            field=models.ForeignKey(
                blank=True,
                help_text="Thread crossing threshold this requirement gates. Exactly one of class_level_unlock / thread_crossing_threshold / path must be set.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_requirements",
                to="magic.threadcrossingthreshold",
            ),
        ),
        migrations.AlterField(
            model_name="relationshiprequirement",
            name="thread_crossing_threshold",
            field=models.ForeignKey(
                blank=True,
                help_text="Thread crossing threshold this requirement gates. Exactly one of class_level_unlock / thread_crossing_threshold / path must be set.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_requirements",
                to="magic.threadcrossingthreshold",
            ),
        ),
        migrations.AlterField(
            model_name="tierrequirement",
            name="thread_crossing_threshold",
            field=models.ForeignKey(
                blank=True,
                help_text="Thread crossing threshold this requirement gates. Exactly one of class_level_unlock / thread_crossing_threshold / path must be set.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_requirements",
                to="magic.threadcrossingthreshold",
            ),
        ),
        migrations.AlterField(
            model_name="traitrequirement",
            name="thread_crossing_threshold",
            field=models.ForeignKey(
                blank=True,
                help_text="Thread crossing threshold this requirement gates. Exactly one of class_level_unlock / thread_crossing_threshold / path must be set.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_requirements",
                to="magic.threadcrossingthreshold",
            ),
        ),
        migrations.AddConstraint(
            model_name="achievementrequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("class_level_unlock__isnull", False),
                        ("thread_crossing_threshold__isnull", True),
                        ("path__isnull", True),
                    ),
                    models.Q(
                        ("class_level_unlock__isnull", True),
                        ("thread_crossing_threshold__isnull", False),
                        ("path__isnull", True),
                    ),
                    models.Q(
                        ("class_level_unlock__isnull", True),
                        ("thread_crossing_threshold__isnull", True),
                        ("path__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="achievementrequirement_exactly_one_unlock_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="classlevelrequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("class_level_unlock__isnull", False),
                        ("thread_crossing_threshold__isnull", True),
                        ("path__isnull", True),
                    ),
                    models.Q(
                        ("class_level_unlock__isnull", True),
                        ("thread_crossing_threshold__isnull", False),
                        ("path__isnull", True),
                    ),
                    models.Q(
                        ("class_level_unlock__isnull", True),
                        ("thread_crossing_threshold__isnull", True),
                        ("path__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="classlevelrequirement_exactly_one_unlock_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="levelrequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("class_level_unlock__isnull", False),
                        ("thread_crossing_threshold__isnull", True),
                        ("path__isnull", True),
                    ),
                    models.Q(
                        ("class_level_unlock__isnull", True),
                        ("thread_crossing_threshold__isnull", False),
                        ("path__isnull", True),
                    ),
                    models.Q(
                        ("class_level_unlock__isnull", True),
                        ("thread_crossing_threshold__isnull", True),
                        ("path__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="levelrequirement_exactly_one_unlock_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="majorgifttechniquerequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("class_level_unlock__isnull", False),
                        ("thread_crossing_threshold__isnull", True),
                        ("path__isnull", True),
                    ),
                    models.Q(
                        ("class_level_unlock__isnull", True),
                        ("thread_crossing_threshold__isnull", False),
                        ("path__isnull", True),
                    ),
                    models.Q(
                        ("class_level_unlock__isnull", True),
                        ("thread_crossing_threshold__isnull", True),
                        ("path__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="majorgifttechniquerequirement_exactly_one_unlock_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="multiclassrequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("class_level_unlock__isnull", False),
                        ("thread_crossing_threshold__isnull", True),
                        ("path__isnull", True),
                    ),
                    models.Q(
                        ("class_level_unlock__isnull", True),
                        ("thread_crossing_threshold__isnull", False),
                        ("path__isnull", True),
                    ),
                    models.Q(
                        ("class_level_unlock__isnull", True),
                        ("thread_crossing_threshold__isnull", True),
                        ("path__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="multiclassrequirement_exactly_one_unlock_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="relationshiprequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("class_level_unlock__isnull", False),
                        ("thread_crossing_threshold__isnull", True),
                        ("path__isnull", True),
                    ),
                    models.Q(
                        ("class_level_unlock__isnull", True),
                        ("thread_crossing_threshold__isnull", False),
                        ("path__isnull", True),
                    ),
                    models.Q(
                        ("class_level_unlock__isnull", True),
                        ("thread_crossing_threshold__isnull", True),
                        ("path__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="relationshiprequirement_exactly_one_unlock_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="tierrequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("class_level_unlock__isnull", False),
                        ("thread_crossing_threshold__isnull", True),
                        ("path__isnull", True),
                    ),
                    models.Q(
                        ("class_level_unlock__isnull", True),
                        ("thread_crossing_threshold__isnull", False),
                        ("path__isnull", True),
                    ),
                    models.Q(
                        ("class_level_unlock__isnull", True),
                        ("thread_crossing_threshold__isnull", True),
                        ("path__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="tierrequirement_exactly_one_unlock_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="traitrequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("class_level_unlock__isnull", False),
                        ("thread_crossing_threshold__isnull", True),
                        ("path__isnull", True),
                    ),
                    models.Q(
                        ("class_level_unlock__isnull", True),
                        ("thread_crossing_threshold__isnull", False),
                        ("path__isnull", True),
                    ),
                    models.Q(
                        ("class_level_unlock__isnull", True),
                        ("thread_crossing_threshold__isnull", True),
                        ("path__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="traitrequirement_exactly_one_unlock_target",
            ),
        ),
    ]
