# Generated by Django 5.2.4 on 2026-03-06 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classes", "0001_initial"),
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
        ("traits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterclass",
            name="core_traits",
            field=models.ManyToManyField(
                blank=True,
                help_text="Core traits associated with this class",
                related_name="classes_requiring_trait",
                to="traits.trait",
            ),
        ),
        migrations.AddField(
            model_name="characterclasslevel",
            name="character",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_class_levels",
                to="objects.objectdb",
            ),
        ),
        migrations.AddField(
            model_name="characterclasslevel",
            name="character_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="character_assignments",
                to="classes.characterclass",
            ),
        ),
        migrations.AddField(
            model_name="path",
            name="parent_paths",
            field=models.ManyToManyField(
                blank=True,
                help_text="Paths that can evolve into this one",
                related_name="child_paths",
                to="classes.path",
            ),
        ),
        migrations.AddField(
            model_name="pathaspect",
            name="aspect",
            field=models.ForeignKey(
                help_text="The aspect being granted",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="path_aspects",
                to="classes.aspect",
            ),
        ),
        migrations.AddField(
            model_name="pathaspect",
            name="character_path",
            field=models.ForeignKey(
                help_text="The path this aspect belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="path_aspects",
                to="classes.path",
            ),
        ),
        migrations.AddIndex(
            model_name="characterclass",
            index=models.Index(fields=["is_hidden"], name="classes_cha_is_hidd_16f053_idx"),
        ),
        migrations.AddIndex(
            model_name="characterclass",
            index=models.Index(fields=["minimum_level"], name="classes_cha_minimum_b4a0af_idx"),
        ),
        migrations.AddIndex(
            model_name="characterclasslevel",
            index=models.Index(fields=["character"], name="classes_cha_charact_3a3842_idx"),
        ),
        migrations.AddIndex(
            model_name="characterclasslevel",
            index=models.Index(
                fields=["character", "level"], name="classes_cha_charact_195bcc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="characterclasslevel",
            index=models.Index(
                fields=["character", "is_primary"],
                name="classes_cha_charact_b5139a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="characterclasslevel",
            unique_together={("character", "character_class")},
        ),
        migrations.AlterUniqueTogether(
            name="pathaspect",
            unique_together={("character_path", "aspect")},
        ),
    ]
