# Generated by Django 5.2.14 on 2026-05-31 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="path",
            name="action_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("physical", "Physical"),
                    ("social", "Social"),
                    ("mental", "Mental"),
                ],
                help_text="Action arena this path specializes in (drives CG technique category).",
                max_length=10,
                null=True,
            ),
        ),
    ]
