# Generated by Django 5.2.14 on 2026-06-20 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0004_alter_characterclasslevel_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassStageHealthRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Prospect"),
                            (2, "Potential"),
                            (3, "Puissant"),
                            (4, "True"),
                            (5, "Grand"),
                            (6, "Transcendent"),
                        ],
                        help_text="PathStage band this rate applies within",
                    ),
                ),
                (
                    "health_per_level",
                    models.PositiveSmallIntegerField(
                        help_text="Health gained per character level while in this stage band"
                    ),
                ),
                (
                    "character_class",
                    models.ForeignKey(
                        help_text="Class this health rate applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_health_rates",
                        to="classes.characterclass",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class Stage Health Rate",
                "verbose_name_plural": "Class Stage Health Rates",
                "ordering": ["character_class", "stage"],
                "unique_together": {("character_class", "stage")},
            },
        ),
    ]
