# Generated by Django 5.2.14 on 2026-07-13 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("character_sheets", "0010_remove_charactersheet_family_and_more"),
        ("evennia_extensions", "0009_exitprofile"),
        ("events", "0005_eventinvitation_responded_at_and_more"),
        ("scenes", "0051_decisivecheckmarker"),
        ("worship", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CeremonyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "officiant_cut_percent",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Officiant's prestige cut as % of the honoree award.",
                    ),
                ),
                (
                    "offering_resonance_per_value",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Worship resonance granted per point of offered item value.",
                    ),
                ),
                (
                    "offering_prestige_per_value",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Honoree prestige per point of offered item value.",
                    ),
                ),
                (
                    "speech_prestige_base",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Base honoree prestige per successful speech level.",
                    ),
                ),
                (
                    "base_honoree_prestige",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Base prestige deed value per honoree at finish.",
                    ),
                ),
                (
                    "quality_multiplier_percent_per_level",
                    models.PositiveIntegerField(
                        default=25,
                        help_text="Tally multiplier % added per quality success level.",
                    ),
                ),
                (
                    "leak_detect_difficulty",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Perception difficulty for sensing a twisted rite.",
                    ),
                ),
                (
                    "devotion_per_offering",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Devotion favor an offerer gains per offering.",
                    ),
                ),
                (
                    "devotion_officiant",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Devotion favor the officiant gains at finish.",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CeremonyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("funeral", "Funeral"),
                            ("blessing", "Blessing"),
                            ("sermon", "Sermon"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="PLACEHOLDER player-facing copy — Apostate rewrite pending.",
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="Ceremony",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "quality_level",
                    models.IntegerField(
                        blank=True,
                        help_text="Success level of the officiant's Rites roll at finish (null until then).",
                        null=True,
                    ),
                ),
                (
                    "being",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ceremonies",
                        to="worship.worshippedbeing",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ceremonies",
                        to="events.event",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ceremonies",
                        to="evennia_extensions.roomprofile",
                    ),
                ),
                (
                    "officiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ceremonies_officiated",
                        to="scenes.persona",
                    ),
                ),
                (
                    "presented_being",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="worship.worshippedbeing",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ceremonies",
                        to="scenes.scene",
                    ),
                ),
                (
                    "ceremony_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ceremonies",
                        to="ceremonies.ceremonytype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ceremonies",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="CeremonyHonoree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prestige_awarded", models.BigIntegerField(default=0)),
                (
                    "ceremony",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="honorees",
                        to="ceremonies.ceremony",
                    ),
                ),
                (
                    "honoree_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ceremony_honors",
                        to="character_sheets.charactersheet",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CeremonyOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=200)),
                ("item_value", models.PositiveIntegerField(default=0)),
                (
                    "ceremony",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offerings",
                        to="ceremonies.ceremony",
                    ),
                ),
                (
                    "offered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ceremony_offerings",
                        to="scenes.persona",
                    ),
                ),
                (
                    "worship_grant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="worship.worshipgrant",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CeremonySpeech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "success_level",
                    models.IntegerField(
                        blank=True,
                        help_text="Speech check success level (null if unrolled).",
                        null=True,
                    ),
                ),
                (
                    "ceremony",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speeches",
                        to="ceremonies.ceremony",
                    ),
                ),
                (
                    "speaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ceremony_speeches",
                        to="scenes.persona",
                    ),
                ),
                (
                    "target_honoree",
                    models.ForeignKey(
                        blank=True,
                        help_text="Speech dedicated to one honoree; null = all honorees.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="speeches",
                        to="ceremonies.ceremonyhonoree",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ceremony speeches",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="ceremonyhonoree",
            constraint=models.UniqueConstraint(
                fields=("ceremony", "honoree_sheet"), name="unique_ceremony_honoree"
            ),
        ),
        migrations.AddConstraint(
            model_name="ceremony",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("location",),
                name="one_open_ceremony_per_location",
            ),
        ),
    ]
