# Generated by Django 5.2.14 on 2026-05-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactervitals",
            name="life_state",
            field=models.CharField(
                choices=[("alive", "Alive"), ("dead", "Dead")],
                default="alive",
                help_text="Mortality axis. Consciousness/dying are conditions, not vitals.",
                max_length=10,
            ),
        ),
    ]
