# Generated by Django 5.2.4 on 2026-04-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactervitals",
            name="dying_final_round",
            field=models.BooleanField(
                default=False,
                help_text="Whether the character gets one final action before death.",
            ),
        ),
        migrations.AddField(
            model_name="charactervitals",
            name="health",
            field=models.IntegerField(default=0, help_text="Current health points."),
        ),
        migrations.AddField(
            model_name="charactervitals",
            name="max_health",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Maximum health points. Recalculated when stats change.",
            ),
        ),
    ]
