# Generated by Django 5.2.14 on 2026-06-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitals", "0002_vitalsconsequenceconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactervitals",
            name="death_deferred_pending",
            field=models.BooleanField(
                default=False,
                help_text="Set when CHARACTER_KILLED is suppressed by an active death_deferred condition. Cleared and CHARACTER_KILLED is emitted when that condition expires.",
            ),
        ),
    ]
