# Generated by Django 5.2.15 on 2026-07-27 01:41

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitals", "0007_wounddetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactervitals",
            name="aging_death_ic_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="IC datetime at which old-age death resolves (#2756). Stamped when Frailty drives max health through the aging floor; the death sweep resolves it via _mark_dead once get_ic_now() passes it. Null = not in the dying window.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vitalsconsequenceconfig",
            name="aging_death_window_ic_days",
            field=models.PositiveIntegerField(
                default=30,
                help_text="IC days between the dying-window notification and death resolving — the deathbed-scene grace period.",
            ),
        ),
        migrations.AddField(
            model_name="vitalsconsequenceconfig",
            name="aging_difficulty_per_year",
            field=models.PositiveSmallIntegerField(
                default=7,
                help_text="Aging-check difficulty points per year of biological age past the species decline_start_age.",
            ),
        ),
        migrations.AddField(
            model_name="vitalsconsequenceconfig",
            name="aging_floor_fraction",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.20"),
                help_text="Fraction of base max health at which age-bled max health tips the character into the dying window.",
                max_digits=3,
            ),
        ),
        migrations.AddField(
            model_name="vitalsconsequenceconfig",
            name="frailty_fail_severity",
            field=models.PositiveSmallIntegerField(
                default=2, help_text="Frailty severity gained on a failed aging check."
            ),
        ),
        migrations.AddField(
            model_name="vitalsconsequenceconfig",
            name="frailty_partial_severity",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Frailty severity gained on a partial-success aging check.",
            ),
        ),
    ]
