# Generated by Django 5.2.15 on 2026-07-24 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("action_points", "0001_initial"),
        ("character_sheets", "0013_charactersheet_durance_cohort_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionpointpool",
            name="character",
            field=models.OneToOneField(
                help_text="The character this pool belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="action_points",
                to="character_sheets.charactersheet",
            ),
        ),
    ]
