# Generated by Django 5.2.14 on 2026-07-03 04:38

from decimal import Decimal

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

import core.natural_keys


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("covenants", "0001_initial"),
        ("evennia_extensions", "0001_initial"),
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
        ("scenes", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterLegendSummary",
            fields=[
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="objects.objectdb",
                    ),
                ),
                ("personal_legend", models.IntegerField()),
            ],
            options={
                "db_table": "societies_characterlegendsummary",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CovenantLegendSummary",
            fields=[
                (
                    "covenant",
                    models.OneToOneField(
                        db_column="covenant_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="legend_summary",
                        serialize=False,
                        to="covenants.covenant",
                    ),
                ),
                ("legend_total", models.PositiveBigIntegerField()),
            ],
            options={
                "db_table": "societies_covenantlegendsummary",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PersonaLegendSummary",
            fields=[
                (
                    "persona",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="scenes.persona",
                    ),
                ),
                ("persona_legend", models.IntegerField()),
            ],
            options={
                "db_table": "societies_personalegendsummary",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LegendEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Short name for this legend record", max_length=200),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of what happened"),
                ),
                (
                    "base_value",
                    models.PositiveIntegerField(default=0, help_text="Base legend value"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LegendSourceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for this legend source type",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this source type represents",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order for display in lists (lower = first)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this source type is currently available",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="LegendSpread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value_added",
                    models.PositiveIntegerField(
                        default=0, help_text="How much legend this spread contributed"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="The embellished version / how they told it",
                    ),
                ),
                (
                    "method",
                    models.TextField(
                        blank=True,
                        help_text="How it was spread (e.g., bard song, tavern gossip, pamphlet)",
                    ),
                ),
                (
                    "audience_factor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.0"),
                        help_text="Multiplier based on audience size/quality",
                        max_digits=6,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Legend Spread",
                "verbose_name_plural": "Legend Spreads",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The organization's name", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A description of the organization's purpose and history",
                    ),
                ),
                (
                    "mercy_override",
                    models.IntegerField(
                        blank=True,
                        help_text="Override for mercy principle (-5 to +5). If null, uses society's value.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-5),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "method_override",
                    models.IntegerField(
                        blank=True,
                        help_text="Override for method principle (-5 to +5). If null, uses society's value.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-5),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "status_override",
                    models.IntegerField(
                        blank=True,
                        help_text="Override for status principle (-5 to +5). If null, uses society's value.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-5),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "change_override",
                    models.IntegerField(
                        blank=True,
                        help_text="Override for change principle (-5 to +5). If null, uses society's value.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-5),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "allegiance_override",
                    models.IntegerField(
                        blank=True,
                        help_text="Override for allegiance principle (-5 to +5). If null, uses society's value.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-5),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "power_override",
                    models.IntegerField(
                        blank=True,
                        help_text="Override for power principle (-5 to +5). If null, uses society's value.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-5),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "rank_1_title_override",
                    models.CharField(
                        blank=True,
                        help_text="Override for rank 1 title. If blank, uses org_type's default.",
                        max_length=50,
                    ),
                ),
                (
                    "rank_2_title_override",
                    models.CharField(
                        blank=True,
                        help_text="Override for rank 2 title. If blank, uses org_type's default.",
                        max_length=50,
                    ),
                ),
                (
                    "rank_3_title_override",
                    models.CharField(
                        blank=True,
                        help_text="Override for rank 3 title. If blank, uses org_type's default.",
                        max_length=50,
                    ),
                ),
                (
                    "rank_4_title_override",
                    models.CharField(
                        blank=True,
                        help_text="Override for rank 4 title. If blank, uses org_type's default.",
                        max_length=50,
                    ),
                ),
                (
                    "rank_5_title_override",
                    models.CharField(
                        blank=True,
                        help_text="Override for rank 5 title. If blank, uses org_type's default.",
                        max_length=50,
                    ),
                ),
                (
                    "base_prestige",
                    models.BigIntegerField(
                        default=0,
                        help_text="Admin-set permanent prestige floor for this organization. Never decays; never event-modified. Quarterly accounting may uplift base from accumulated, but that's a separate operation.",
                    ),
                ),
                (
                    "accumulated_prestige",
                    models.BigIntegerField(
                        default=0,
                        help_text="Event-fed prestige accumulation from member deeds (10% of any member persona's deed prestige). Decays at a high rate per IC day via the renown decay cron.",
                    ),
                ),
                (
                    "accumulated_fame",
                    models.BigIntegerField(
                        default=0,
                        help_text="Event-fed fame buffer for this organization, from member deed fame gains. Decays fast like persona fame.",
                    ),
                ),
                (
                    "accumulated_legend",
                    models.BigIntegerField(
                        default=0,
                        help_text="Event-fed legend accumulation, COVENANTS ONLY. Body-flow rule: any member-body's legend gain credits 10% here regardless of which persona did the deed. Permanent — never decays. Used as a ritual-availability gate (separate magic design pass).",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "joined_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the persona joined this organization",
                    ),
                ),
                (
                    "left_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the persona voluntarily left the organization",
                        null=True,
                    ),
                ),
                (
                    "exiled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the persona was forcibly removed from the organization",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Membership",
                "verbose_name_plural": "Organization Memberships",
                "ordering": ["organization", "rank__tier", "persona__name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationMembershipOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("invite", "Invite"), ("application", "Application")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("message", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Diegetic name for this rung (e.g., Guildmaster, Captain)",
                        max_length=60,
                    ),
                ),
                (
                    "tier",
                    models.PositiveIntegerField(help_text="Authority tier (1 highest, 5 lowest)"),
                ),
                (
                    "can_invite",
                    models.BooleanField(
                        default=False,
                        help_text="Members at this rank can invite others to the organization",
                    ),
                ),
                (
                    "can_kick",
                    models.BooleanField(
                        default=False,
                        help_text="Members at this rank can expel lower-ranked members",
                    ),
                ),
                (
                    "can_manage_ranks",
                    models.BooleanField(
                        default=False,
                        help_text="Members at this rank can promote/demote others",
                    ),
                ),
            ],
            options={
                "ordering": ["tier"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationReputation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        default=0,
                        help_text="Reputation value (-1000 to 1000)",
                        validators=[
                            django.core.validators.MinValueValidator(-1000),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Reputation",
                "verbose_name_plural": "Organization Reputations",
            },
        ),
        migrations.CreateModel(
            name="OrganizationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique identifier for this organization type (e.g., 'noble', 'covenant')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "rank_1_title",
                    models.CharField(
                        default="Leader",
                        help_text="Default title for rank 1 (highest)",
                        max_length=50,
                    ),
                ),
                (
                    "rank_2_title",
                    models.CharField(
                        default="Officer",
                        help_text="Default title for rank 2",
                        max_length=50,
                    ),
                ),
                (
                    "rank_3_title",
                    models.CharField(
                        default="Member",
                        help_text="Default title for rank 3",
                        max_length=50,
                    ),
                ),
                (
                    "rank_4_title",
                    models.CharField(
                        default="Associate",
                        help_text="Default title for rank 4",
                        max_length=50,
                    ),
                ),
                (
                    "rank_5_title",
                    models.CharField(
                        default="Contact",
                        help_text="Default title for rank 5 (lowest)",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PersonaDeedKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("witnessed", "Witnessed"),
                            ("heard_told", "Heard the tale told"),
                        ],
                        help_text="How the knowledge arrived (witnessed / heard the tale told)",
                        max_length=20,
                    ),
                ),
                ("learned_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Persona Deed Knowledge",
                "verbose_name_plural": "Persona Deed Knowledge",
            },
        ),
        migrations.CreateModel(
            name="PhilosophicalArchetype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "mercy_delta",
                    models.IntegerField(
                        default=0,
                        help_text="Compassion (+) ↔ Ruthlessness (-) axis contribution.",
                        validators=[
                            django.core.validators.MinValueValidator(-5),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "method_delta",
                    models.IntegerField(
                        default=0,
                        help_text="Honor (+) ↔ Cunning (-) axis contribution.",
                        validators=[
                            django.core.validators.MinValueValidator(-5),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "status_delta",
                    models.IntegerField(
                        default=0,
                        help_text="Humility (+) ↔ Ambition (-) axis contribution.",
                        validators=[
                            django.core.validators.MinValueValidator(-5),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "change_delta",
                    models.IntegerField(
                        default=0,
                        help_text="Progress (+) ↔ Tradition (-) axis contribution.",
                        validators=[
                            django.core.validators.MinValueValidator(-5),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "allegiance_delta",
                    models.IntegerField(
                        default=0,
                        help_text="Independence (+) ↔ Loyalty (-) axis contribution.",
                        validators=[
                            django.core.validators.MinValueValidator(-5),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "power_delta",
                    models.IntegerField(
                        default=0,
                        help_text="Equality (+) ↔ Hierarchy (-) axis contribution.",
                        validators=[
                            django.core.validators.MinValueValidator(-5),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="RankingBandLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank_min",
                    models.PositiveSmallIntegerField(
                        help_text="First rank position (1-based, inclusive) this label covers."
                    ),
                ),
                (
                    "rank_max",
                    models.PositiveSmallIntegerField(
                        help_text="Last rank position (inclusive) this label covers."
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="The qualitative phrase rendered beside names in this band.",
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="RankingDisplay",
            fields=[
                (
                    "display_object",
                    models.OneToOneField(
                        help_text="The Evennia object (a herald, plaque, board) players interact with to view the ranking.",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="ranking_display",
                        serialize=False,
                        to="objects.objectdb",
                    ),
                ),
                (
                    "ranking_type",
                    models.CharField(
                        choices=[
                            ("society_prestige", "Society Prestige"),
                            ("academy_legend", "Academy Legend"),
                            ("society_fashion", "Society Fashion"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "top_n",
                    models.PositiveIntegerField(default=10, help_text="How many entries to show."),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Society",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "mercy",
                    models.IntegerField(
                        default=0,
                        help_text="Ruthlessness (-5) to Compassion (+5)",
                        validators=[
                            django.core.validators.MinValueValidator(-5),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "method",
                    models.IntegerField(
                        default=0,
                        help_text="Cunning (-5) to Honor (+5)",
                        validators=[
                            django.core.validators.MinValueValidator(-5),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        default=0,
                        help_text="Ambition (-5) to Humility (+5)",
                        validators=[
                            django.core.validators.MinValueValidator(-5),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "change",
                    models.IntegerField(
                        default=0,
                        help_text="Tradition (-5) to Progress (+5)",
                        validators=[
                            django.core.validators.MinValueValidator(-5),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "allegiance",
                    models.IntegerField(
                        default=0,
                        help_text="Loyalty (-5) to Independence (+5)",
                        validators=[
                            django.core.validators.MinValueValidator(-5),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "power",
                    models.IntegerField(
                        default=0,
                        help_text="Hierarchy (-5) to Equality (+5)",
                        validators=[
                            django.core.validators.MinValueValidator(-5),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "fame_perception_offset",
                    models.IntegerField(
                        default=0,
                        help_text="How isolated this society's news flow is. 0 = fully connected; -4 = very isolated (only World Famous personas register at all, and only at Normal multiplier). See Renown design (#676).",
                        validators=[
                            django.core.validators.MinValueValidator(-4),
                            django.core.validators.MaxValueValidator(0),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "societies",
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SocietyReputation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        default=0,
                        help_text="Reputation value (-1000 to 1000)",
                        validators=[
                            django.core.validators.MinValueValidator(-1000),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Society Reputation",
                "verbose_name_plural": "Society Reputations",
            },
        ),
        migrations.CreateModel(
            name="SpreadAssistTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_value",
                    models.PositiveIntegerField(
                        help_text="The telling's own spread value; the bonus is a fraction of this."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SpreadingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_spread_multiplier",
                    models.PositiveIntegerField(
                        default=9,
                        help_text="Default spread multiplier for new deeds. Total legend can reach base_value * (1 + multiplier). With default 9, a deed worth 10 can reach 100.",
                    ),
                ),
                (
                    "base_audience_factor",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.0"),
                        help_text="Base factor applied to audience calculations for spreading",
                        max_digits=6,
                    ),
                ),
                (
                    "spread_assist_fraction",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.10"),
                        help_text="Bonus spread per PC acclaim of a telling (#915), as a fraction of the original telling's value. PC assists are deliberately minor; the NPC traffic band stays the primary spread vector.",
                        max_digits=4,
                    ),
                ),
                (
                    "spread_assist_per_scene_cap",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Hard cap on the total spread-assist bonus from one telling (#915). 0 = no separate cap (still clamped by the deed's remaining capacity).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Spreading Configuration",
                "verbose_name_plural": "Spreading Configuration",
            },
        ),
        migrations.CreateModel(
            name="CovenantLegendCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "covenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legend_credits",
                        to="covenants.covenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FameReactionCooldown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available_at",
                    models.DateTimeField(
                        help_text="Reactions to this persona in this room re-fire after this time."
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fame_reaction_cooldowns",
                        to="scenes.persona",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fame_reaction_cooldowns",
                        to="evennia_extensions.roomprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FameReactionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_fame_tier",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("talked_about", "Talked About"),
                            ("celebrity", "Celebrity"),
                            ("household_name", "Household Name"),
                            ("world_famous", "World Famous"),
                        ],
                        default="talked_about",
                        help_text="Minimum perceived fame tier of the arriver for this line to fire.",
                        max_length=20,
                    ),
                ),
                (
                    "bystander_body",
                    models.TextField(
                        blank=True,
                        help_text="What the room's other occupants see when the line fires.",
                    ),
                ),
                (
                    "arriver_body",
                    models.TextField(
                        blank=True,
                        help_text="What the arriving character themselves sees.",
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Relative draw weight among this room's eligible lines.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fame_reaction_lines",
                        to="evennia_extensions.roomprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LegendDeedStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(help_text="The player-written account of the deed"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="The persona that wrote this account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legend_stories_written",
                        to="scenes.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legend Deed Story",
                "verbose_name_plural": "Legend Deed Stories",
            },
        ),
        migrations.CreateModel(
            name="LegendEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Short name for this legend record", max_length=200),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of what happened"),
                ),
                (
                    "base_value",
                    models.PositiveIntegerField(default=0, help_text="Base legend value"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_note",
                    models.TextField(
                        blank=True,
                        help_text="Freeform placeholder for source (until mission/event models exist)",
                    ),
                ),
                (
                    "location_note",
                    models.TextField(
                        blank=True,
                        help_text="Freeform placeholder for location (until grid exists)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this entry contributes to legend totals",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "spread_multiplier",
                    models.PositiveIntegerField(
                        default=9,
                        help_text="How many times the base_value can be added via spreading. Total legend = base_value + up to (base_value * spread_multiplier).",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        help_text="The persona (identity) that earned this legend",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legend_entries",
                        to="scenes.persona",
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        blank=True,
                        help_text="The scene where this deed occurred, if any",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legend_entries",
                        to="scenes.scene",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legend Entry",
                "verbose_name_plural": "Legend Entries",
            },
        ),
    ]
