# Generated by Django 5.2.4 on 2026-03-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("societies", "0004_alter_legenddeedstory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="legendsourcetype",
            options={},
        ),
        migrations.AlterField(
            model_name="legendentry",
            name="base_value",
            field=models.PositiveIntegerField(
                default=0, help_text="Initial legend value from the deed itself"
            ),
        ),
        migrations.AlterField(
            model_name="legendspread",
            name="value_added",
            field=models.PositiveIntegerField(
                default=0, help_text="How much legend this spread contributed"
            ),
        ),
    ]
