# Generated by Django 5.2.14 on 2026-06-10 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("evennia_extensions", "0002_roomprofile_tenant_persona"),
        ("scenes", "0014_scenecheckmodifier"),
        ("societies", "0013_society_current_fashion_style"),
    ]

    operations = [
        migrations.CreateModel(
            name="FameReactionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_fame_tier",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("talked_about", "Talked About"),
                            ("celebrity", "Celebrity"),
                            ("household_name", "Household Name"),
                            ("world_famous", "World Famous"),
                        ],
                        default="talked_about",
                        help_text="Minimum perceived fame tier of the arriver for this line to fire.",
                        max_length=20,
                    ),
                ),
                (
                    "bystander_body",
                    models.TextField(
                        blank=True,
                        help_text="What the room's other occupants see when the line fires.",
                    ),
                ),
                (
                    "arriver_body",
                    models.TextField(
                        blank=True,
                        help_text="What the arriving character themselves sees.",
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Relative draw weight among this room's eligible lines.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fame_reaction_lines",
                        to="evennia_extensions.roomprofile",
                    ),
                ),
                (
                    "society",
                    models.ForeignKey(
                        blank=True,
                        help_text="The society whose voice this room speaks with — its fame_perception_offset filters how famous the arriver reads. Null = raw fame tier.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fame_reaction_lines",
                        to="societies.society",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FameReactionCooldown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available_at",
                    models.DateTimeField(
                        help_text="Reactions to this persona in this room re-fire after this time."
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fame_reaction_cooldowns",
                        to="scenes.persona",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fame_reaction_cooldowns",
                        to="evennia_extensions.roomprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("persona", "room"),
                        name="unique_fame_reaction_cooldown_pair",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RankingBandLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank_min",
                    models.PositiveSmallIntegerField(
                        help_text="First rank position (1-based, inclusive) this label covers."
                    ),
                ),
                (
                    "rank_max",
                    models.PositiveSmallIntegerField(
                        help_text="Last rank position (inclusive) this label covers."
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="The qualitative phrase rendered beside names in this band.",
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "society",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = the global/default label set (Academy boards + fallback).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranking_band_labels",
                        to="societies.society",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("rank_min__lte", models.F("rank_max"))),
                        name="societies_band_label_min_lte_max",
                    )
                ],
            },
        ),
    ]
