# Generated by Django 5.2.14 on 2026-07-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("societies", "0018_organization_membership_lifecycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="society",
            name="enforcer_name",
            field=models.CharField(
                default="The Watch",
                help_text="Admin-editable flavor: who hunts the wanted in this society's dominion (heat surfaces render it — e.g. Luxen's 'The Honest'). Phrase it as a collective plural: '<name> have been looking …'.",
                max_length=100,
            ),
        ),
    ]
