# Generated by Django 5.2.14 on 2026-07-07 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("character_creation", "0005_characterdraft_claimed_kin_pool_and_more"),
        ("realms", "0001_initial"),
        (
            "societies",
            "0023_holdingkind_organization_family_domain_domaincrisis_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HouseTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "family_type",
                    models.CharField(
                        help_text="roster.Family.FamilyType the defined family gets.",
                        max_length=20,
                    ),
                ),
                (
                    "name_pattern",
                    models.CharField(
                        default="[A-Z][a-z]{2,19}",
                        help_text="Full-match regex the proposed house name must satisfy — the realm's naming conventions as an automated gate. PLACEHOLDER.",
                        max_length=200,
                    ),
                ),
                ("mercy_min", models.SmallIntegerField(default=-5)),
                ("mercy_max", models.SmallIntegerField(default=5)),
                ("method_min", models.SmallIntegerField(default=-5)),
                ("method_max", models.SmallIntegerField(default=5)),
                ("status_min", models.SmallIntegerField(default=-5)),
                ("status_max", models.SmallIntegerField(default=5)),
                ("change_min", models.SmallIntegerField(default=-5)),
                ("change_max", models.SmallIntegerField(default=5)),
                ("allegiance_min", models.SmallIntegerField(default=-5)),
                ("allegiance_max", models.SmallIntegerField(default=5)),
                ("power_min", models.SmallIntegerField(default=-5)),
                ("power_max", models.SmallIntegerField(default=5)),
                (
                    "starting_kin_slots",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="KinSlotPool capacity minted for the new family. PLACEHOLDER.",
                    ),
                ),
                (
                    "default_succession_law",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="house_templates",
                        to="societies.successionlaw",
                    ),
                ),
                (
                    "holdings",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Holdings materialized on the title's seat domain at finalization.",
                        related_name="house_templates",
                        to="societies.holdingkind",
                    ),
                ),
                (
                    "liege",
                    models.ForeignKey(
                        help_text="The org the new house swears fealty to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="house_templates",
                        to="societies.organization",
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="house_templates",
                        to="realms.realm",
                    ),
                ),
                (
                    "society",
                    models.ForeignKey(
                        help_text="The society the materialized org joins.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="house_templates",
                        to="societies.society",
                    ),
                ),
            ],
            options={
                "ordering": ["realm", "name"],
            },
        ),
        migrations.CreateModel(
            name="HouseClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "house_name",
                    models.CharField(
                        help_text='The family name (org renders "House <name>" for nobles).',
                        max_length=100,
                    ),
                ),
                (
                    "backstory",
                    models.TextField(
                        help_text="The thematic pitch staff reviews — the house as it has always been."
                    ),
                ),
                ("mercy", models.SmallIntegerField(default=0)),
                ("method", models.SmallIntegerField(default=0)),
                ("status_principle", models.SmallIntegerField(default=0)),
                ("change", models.SmallIntegerField(default=0)),
                ("allegiance", models.SmallIntegerField(default=0)),
                ("power", models.SmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "draft",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="house_claim",
                        to="character_creation.characterdraft",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        help_text="The vacant claimable title this house is defined behind.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="societies.title",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="societies.housetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
