# Generated by Django 5.2.14 on 2026-07-07 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("societies", "0025_housetemplate_houseclaim"),
    ]

    operations = [
        migrations.CreateModel(
            name="HouseAspectDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "prompt",
                    models.TextField(
                        help_text="Player-facing question the founder answers by picking options."
                    ),
                ),
                ("min_picks", models.PositiveSmallIntegerField(default=1)),
                ("max_picks", models.PositiveSmallIntegerField(default=1)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="HouseFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "slug",
                    models.SlugField(help_text="Stable code anchor.", max_length=60, unique=True),
                ),
                (
                    "description",
                    models.TextField(help_text="Player-facing: how this shapes play."),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="domain",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="The lands, described — CG lands_writeup materializes here (#2079).",
            ),
        ),
        migrations.AddField(
            model_name="houseclaim",
            name="colors",
            field=models.CharField(
                default="", help_text="House colors, prose (#2079).", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="houseclaim",
            name="lands_writeup",
            field=models.TextField(
                blank=True,
                help_text="The seat domain's lands, described (required for landed titles, #2079).",
            ),
        ),
        migrations.AddField(
            model_name="houseclaim",
            name="sigil_description",
            field=models.TextField(default="", help_text="The sigil, described (#2079)."),
        ),
        migrations.AddField(
            model_name="houseclaim",
            name="words",
            field=models.CharField(
                default="", help_text="House words / motto (#2079).", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="colors",
            field=models.CharField(
                blank=True,
                help_text="The organization's colors, in prose (#2079).",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="sigil_description",
            field=models.TextField(blank=True, help_text="Sigil / emblem, described (#2079)."),
        ),
        migrations.AddField(
            model_name="organization",
            name="words",
            field=models.CharField(
                blank=True,
                help_text="Words / motto — house words, gang credo, guild maxim (#2079).",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="housetemplate",
            name="aspect_definitions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Required catalog choices for claims on this template (#2079).",
                related_name="templates",
                to="societies.houseaspectdefinition",
            ),
        ),
        migrations.CreateModel(
            name="HouseAspectOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Player-facing blurb shown on the option card.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="societies.houseaspectdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["definition", "display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="HouseClaimAspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aspects",
                        to="societies.houseclaim",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="societies.houseaspectdefinition",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="societies.houseaspectoption",
                    ),
                ),
            ],
            options={
                "ordering": ["claim", "definition", "option"],
            },
        ),
        migrations.AddField(
            model_name="housetemplate",
            name="features",
            field=models.ManyToManyField(
                blank=True,
                help_text="Cultural facts stamped on materialized houses (#2079).",
                related_name="templates",
                to="societies.housefeature",
            ),
        ),
        migrations.CreateModel(
            name="OrganizationAspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="societies.houseaspectdefinition",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="societies.houseaspectoption",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aspects",
                        to="societies.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["organization", "definition", "option"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organization_features",
                        to="societies.housefeature",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="societies.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["organization", "feature"],
            },
        ),
        migrations.AddConstraint(
            model_name="houseaspectoption",
            constraint=models.UniqueConstraint(
                fields=("definition", "name"), name="unique_option_name_per_definition"
            ),
        ),
        migrations.AddConstraint(
            model_name="houseclaimaspect",
            constraint=models.UniqueConstraint(
                fields=("claim", "option"), name="unique_claim_option"
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationaspect",
            constraint=models.UniqueConstraint(
                fields=("organization", "option"), name="unique_org_option"
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationfeature",
            constraint=models.UniqueConstraint(
                fields=("organization", "feature"), name="unique_org_feature"
            ),
        ),
    ]
