# Generated by Django 5.2.14 on 2026-07-10 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0016_alter_contributionmethod_kind_alter_project_kind"),
        ("societies", "0026_houseaspectdefinition_housefeature_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropagandaCampaignTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "magnitude",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("very_high", "Very High"),
                        ],
                        default="small",
                        help_text="Renown magnitude passed to fire_renown_award.",
                        max_length=20,
                    ),
                ),
                (
                    "risk",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("extreme", "Extreme"),
                        ],
                        default="none",
                        help_text="Risk level for legend award; NONE means no legend granted.",
                        max_length=20,
                    ),
                ),
                (
                    "reach",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("local", "Local"),
                            ("regional", "Regional"),
                            ("continental", "Continental"),
                            ("world", "World"),
                        ],
                        help_text="Override reach; if null, derived from magnitude default.",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "threshold_coppers",
                    models.PositiveIntegerField(
                        help_text="Total funding (coppers) required to complete a campaign at this scale."
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive tiers disappear from the launch picker without deleting history.",
                    ),
                ),
                (
                    "archetypes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Philosophical archetypes forwarded to fire_renown_award.",
                        related_name="%(class)s_renown_configs",
                        to="societies.philosophicalarchetype",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PropagandaDetails",
            fields=[
                (
                    "magnitude",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("very_high", "Very High"),
                        ],
                        default="small",
                        help_text="Renown magnitude passed to fire_renown_award.",
                        max_length=20,
                    ),
                ),
                (
                    "risk",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("extreme", "Extreme"),
                        ],
                        default="none",
                        help_text="Risk level for legend award; NONE means no legend granted.",
                        max_length=20,
                    ),
                ),
                (
                    "reach",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("local", "Local"),
                            ("regional", "Regional"),
                            ("continental", "Continental"),
                            ("world", "World"),
                        ],
                        help_text="Override reach; if null, derived from magnitude default.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="propaganda_details",
                        serialize=False,
                        to="projects.project",
                    ),
                ),
                (
                    "campaign_name",
                    models.CharField(
                        help_text="Sponsor-authored campaign title; becomes the renown deed's title.",
                        max_length=200,
                    ),
                ),
                (
                    "renown_fired",
                    models.BooleanField(
                        default=False,
                        help_text="Set by the kind handler after fire_renown_award; guards re-fires.",
                    ),
                ),
                (
                    "archetypes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Philosophical archetypes forwarded to fire_renown_award.",
                        related_name="%(class)s_renown_configs",
                        to="societies.philosophicalarchetype",
                    ),
                ),
                (
                    "source_tier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Provenance: the tier this campaign's config was copied from.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns",
                        to="societies.propagandacampaigntier",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
