# Generated by Django 5.2.14 on 2026-05-31 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("scenes", "0007_persona_is_system"),
        ("societies", "0004_alter_organization_society_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NPCRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name; e.g., 'Builders Guild Clerk', 'Town Guard'.",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Admin-editable flavor; what this role does in the world.",
                    ),
                ),
                (
                    "default_description_template",
                    models.TextField(
                        blank=True,
                        help_text="Fallback flavor description rendered when a class-1 nameless NPC of this role is presented to the player. Class-2+ NPCs use their persona's description instead.",
                    ),
                ),
                (
                    "default_rapport_starting_value",
                    models.IntegerField(
                        default=0,
                        help_text="Initial in-interaction rapport for class-1 interactions. Class-2/3/4 interactions start at `default + NPCStanding.affection`.",
                    ),
                ),
                (
                    "faction_affiliation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional org this role fronts for (e.g., Builders Guild Clerk → Builders Guild Organization). Used by org-scoped permission filters.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="npc_roles",
                        to="societies.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NPCServiceOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("permit", "Permit")],
                        help_text="Discriminator: routes to per-kind details model + effect handler registered in `world.npc_services.effects.OFFER_EFFECT_HANDLERS`.",
                        max_length=32,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="UI display text for the menu option.", max_length=200
                    ),
                ),
                (
                    "draw_mode",
                    models.CharField(
                        choices=[("menu", "Menu"), ("pool", "Pool")],
                        default="menu",
                        help_text="MENU = deterministic option always shown if eligible. POOL = NPC draws from a pool per visit (mission-style; #686).",
                        max_length=8,
                    ),
                ),
                (
                    "eligibility_rule",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Predicate JSON evaluated via `world.missions.predicates.evaluate`. Empty dict = no gate. Drives both visibility and selectability — if it fails, the offer doesn't appear in the menu.",
                    ),
                ),
                (
                    "rapport_requirement",
                    models.IntegerField(
                        default=0,
                        help_text="Minimum in-interaction rapport to see/select this option. Separate from durable eligibility; 0 = no rapport gate.",
                    ),
                ),
                (
                    "is_final",
                    models.BooleanField(
                        default=True,
                        help_text="Final actions resolve + end the interaction. Non-final actions adjust rapport and re-render the menu (e.g., flattery/negotiation).",
                    ),
                ),
                (
                    "rapport_delta_success",
                    models.IntegerField(
                        default=0,
                        help_text="Rapport delta on success of a non-final check-based action.",
                    ),
                ),
                (
                    "rapport_delta_failure",
                    models.IntegerField(
                        default=0,
                        help_text="Rapport delta on failure of a non-final check-based action.",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="npc_services.npcrole",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PermitOfferDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offer",
                    models.OneToOneField(
                        help_text="The NPCServiceOffer row this details model decorates.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permit_offer_details",
                        to="npc_services.npcserviceoffer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NPCStanding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "affection",
                    models.IntegerField(
                        default=0,
                        help_text="Per-persona-pair standing / affection. Predicate gate `min_npc_standing` reads this. Negative values mean disliked. Movement mechanic (flirt/seduce/cultivation checks) is adjacent gameplay work that mutates this value; the model just carries it.",
                    ),
                ),
                (
                    "available_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Cooldown gate (mission accept sets this; non-mission consumers leave null). availability filters exclude rows with `available_at > now`.",
                        null=True,
                    ),
                ),
                (
                    "last_interaction_summary",
                    models.TextField(
                        blank=True,
                        help_text="Free-text summary of the last interaction; used by both mission and functionary contexts to surface 'why we left off where we did'.",
                    ),
                ),
                ("last_changed_at", models.DateTimeField(auto_now=True)),
                (
                    "npc_persona",
                    models.ForeignKey(
                        help_text="The NPC's persona the standing is with.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="standings_held_by",
                        to="scenes.persona",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        help_text="The PC's persona that holds this standing.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="npc_standings",
                        to="scenes.persona",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("persona", "npc_persona"),
                        name="unique_npcstanding_persona_npc",
                    )
                ],
            },
        ),
    ]
