# Generated by Django 5.2.14 on 2026-06-01 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0003_initial"),
        ("npc_services", "0001_initial"),
        ("scenes", "0007_persona_is_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferCooldown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available_at",
                    models.DateTimeField(
                        help_text="Earliest time `persona` can select this offer again."
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="npcstanding",
            name="available_at",
        ),
        migrations.AddField(
            model_name="npcserviceoffer",
            name="check_difficulty",
            field=models.IntegerField(
                default=0,
                help_text="Target difficulty passed to `perform_check` when `check_type` is set. Meaningless when `check_type` is null.",
            ),
        ),
        migrations.AddField(
            model_name="npcserviceoffer",
            name="check_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: if set, non-final actions roll `perform_check` against this check type and `check_difficulty`. Success → `rapport_delta_success`; failure → `rapport_delta_failure`. Final actions ignore this — the effect IS the payoff.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="checks.checktype",
            ),
        ),
        migrations.AddField(
            model_name="npcserviceoffer",
            name="cooldown",
            field=models.DurationField(
                blank=True,
                help_text="Per-(offer, persona) throttle applied after a final-action grant. When set, `OfferCooldown.available_at = now + cooldown` blocks re-selection until it elapses. Null = no cooldown.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="npcserviceoffer",
            constraint=models.UniqueConstraint(
                fields=("role", "label"), name="unique_offer_role_label"
            ),
        ),
        migrations.AddField(
            model_name="offercooldown",
            name="offer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cooldowns",
                to="npc_services.npcserviceoffer",
            ),
        ),
        migrations.AddField(
            model_name="offercooldown",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="offer_cooldowns",
                to="scenes.persona",
            ),
        ),
        migrations.AddConstraint(
            model_name="offercooldown",
            constraint=models.UniqueConstraint(
                fields=("offer", "persona"), name="unique_offercooldown_offer_persona"
            ),
        ),
    ]
