# Generated by Django 5.2.14 on 2026-06-01 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("areas", "0003_area_allowed_building_kinds_and_more"),
        ("buildings", "0001_initial"),
        ("npc_services", "0002_offercooldown_remove_npcstanding_available_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="permitofferdetails",
            name="building_kind",
            field=models.ForeignKey(
                blank=True,
                help_text="Which BuildingKind this offer issues permits for. Required for kind=PERMIT offers in Plan 3 (nullable in the schema so existing rows can migrate; runtime issuance asserts non-null).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="offered_by",
                to="buildings.buildingkind",
            ),
        ),
        migrations.AddField(
            model_name="permitofferdetails",
            name="default_approved_wards",
            field=models.ManyToManyField(
                blank=True,
                help_text="Default set of wards the issued permit is valid in. Snapshotted onto BuildingPermitDetails.approved_wards at issuance time.",
                related_name="default_permits_offered",
                to="areas.area",
            ),
        ),
        migrations.AddField(
            model_name="permitofferdetails",
            name="default_max_target_size",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="Default cap on ``target_size`` for buildings constructed under permits from this offer.",
            ),
        ),
        migrations.AddField(
            model_name="permitofferdetails",
            name="permit_cost_currency",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Currency cost of the permit (approval fee — distinct from construction cost). Charged to the PC's account at grant time.",
            ),
        ),
    ]
