# Generated by Django 5.2.14 on 2026-06-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npc_services", "0004_npcrole_is_active_alter_npcserviceoffer_kind_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="missionofferdetails",
            name="draw_priority",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="POOL-draw priority tier (#726). The highest tier present is drawn first with guaranteed inclusion (up to the pool count); lower tiers fill any remaining slots via the weighted draw. Give chain-unlock / high-stakes follow-up missions a positive value so they surface ahead of the general pool. 0 = general pool.",
            ),
        ),
    ]
