# Generated by Django 5.2.14 on 2026-07-04 03:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

import core.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("npc_services", "0008_npcserviceoffer_ap_cost_alter_npcserviceoffer_kind"),
        ("scenes", "0046_sceneunseenobserver"),
        ("societies", "0019_society_enforcer_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="NpcRegard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("persona", "Persona"),
                            ("organization", "Organization"),
                            ("society", "Society"),
                        ],
                        help_text="Selects which target FK (persona, organization, society) is active.",
                        max_length=12,
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        default=0,
                        help_text="Signed opinion (-1000 to 1000). Negative = hostile.",
                        validators=[
                            django.core.validators.MinValueValidator(-1000),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Narrative/GM-facing flavor for why this opinion exists.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this opinion was resolved/retracted. NULL = currently active.",
                        null=True,
                    ),
                ),
                (
                    "holder_persona",
                    models.ForeignKey(
                        help_text="The notable NPC's persona whose opinion this is.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regards_held",
                        to="scenes.persona",
                    ),
                ),
                (
                    "target_organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set iff target_type=ORGANIZATION.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regards_as_target",
                        to="societies.organization",
                    ),
                ),
                (
                    "target_persona",
                    models.ForeignKey(
                        blank=True,
                        help_text="Any persona (PC or NPC) this opinion is about. Set iff target_type=PERSONA.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regards_as_target",
                        to="scenes.persona",
                    ),
                ),
                (
                    "target_society",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set iff target_type=SOCIETY.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regards_as_target",
                        to="societies.society",
                    ),
                ),
            ],
            options={
                "verbose_name": "NPC Regard",
                "verbose_name_plural": "NPC Regards",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("target_persona__isnull", False),
                            ("ended_at__isnull", True),
                        ),
                        fields=("holder_persona", "target_persona"),
                        name="unique_active_regard_target_persona",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("target_organization__isnull", False),
                            ("ended_at__isnull", True),
                        ),
                        fields=("holder_persona", "target_organization"),
                        name="unique_active_regard_target_organization",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("target_society__isnull", False),
                            ("ended_at__isnull", True),
                        ),
                        fields=("holder_persona", "target_society"),
                        name="unique_active_regard_target_society",
                    ),
                ],
            },
            bases=(core.mixins.DiscriminatorMixin, models.Model),
        ),
    ]
