# Generated by Django 5.2.14 on 2026-07-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npc_services", "0013_alter_npcserviceoffer_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="npcserviceoffer",
            name="kind",
            field=models.CharField(
                choices=[
                    ("permit", "Permit"),
                    ("mission", "Mission"),
                    ("loan", "Loan"),
                    ("collection", "Collection"),
                    ("improvement", "Improvement"),
                    ("court_grant", "Court Grant"),
                    ("informant", "Informant"),
                    ("contact", "Contact"),
                    ("personal_favor", "Personal Favor"),
                    ("guard", "Guard"),
                    ("fan", "Fan"),
                    ("minor_ally", "Minor Ally"),
                ],
                help_text="Discriminator: routes to per-kind details model + effect handler registered in `world.npc_services.effects.OFFER_EFFECT_HANDLERS`.",
                max_length=32,
            ),
        ),
    ]
