# Generated by Django 5.2.15 on 2026-07-17 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("magic", "0107_remove_technique_source_cantrip_delete_cantrip"),
        ("npc_services", "0022_alter_npcserviceoffer_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="npcrole",
            name="teaches_tradition",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: the Tradition this role's trainer teaches signature techniques for (#2440). Gates TRAIN-offer signature-technique availability to learners who belong to the same Tradition (CharacterTradition membership). Blank = the role only trains shared (Path × Gift) pool techniques, no tradition signatures.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teaching_npc_roles",
                to="magic.tradition",
            ),
        ),
        migrations.AlterField(
            model_name="npcserviceoffer",
            name="kind",
            field=models.CharField(
                choices=[
                    ("permit", "Permit"),
                    ("mission", "Mission"),
                    ("loan", "Loan"),
                    ("collection", "Collection"),
                    ("improvement", "Improvement"),
                    ("court_grant", "Court Grant"),
                    ("informant", "Informant"),
                    ("contact", "Contact"),
                    ("personal_favor", "Personal Favor"),
                    ("guard", "Guard"),
                    ("fan", "Fan"),
                    ("minor_ally", "Minor Ally"),
                    ("asset_task_intel", "Asset Task: Intel"),
                    ("asset_task_collect", "Asset Task: Collect"),
                    ("train", "Train"),
                ],
                help_text="Discriminator: routes to per-kind details model + effect handler registered in `world.npc_services.effects.OFFER_EFFECT_HANDLERS`.",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="TrainOfferDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "learn_ap_cost",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Base AP the learner pays to accept, before the has-gift/major-gift multiplier (mirrors TechniqueTeachingOffer.learn_ap_cost).",
                    ),
                ),
                (
                    "gold_cost",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Coin charged to the learner's purse, credited to the Academy's treasury.",
                    ),
                ),
                (
                    "offer",
                    models.OneToOneField(
                        help_text="The NPCServiceOffer row this details model decorates.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="train_offer_details",
                        to="npc_services.npcserviceoffer",
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        help_text="The technique this trainer teaches on this offer.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="train_offers",
                        to="magic.technique",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
