# Generated by Django 5.2.15 on 2026-07-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npc_services", "0026_npcreactionline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="npcreactionline",
            name="metric",
            field=models.CharField(
                choices=[("allure", "Allure"), ("menace", "Menace")],
                help_text="Which number of the served character the band reads.",
                max_length=30,
            ),
        ),
    ]
