# Generated by Django 5.2.15 on 2026-07-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("npc_services", "0027_alter_npcreactionline_metric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="npcassignment",
            name="assignment_role",
            field=models.CharField(
                choices=[
                    ("guard", "Guard"),
                    ("doorman", "Doorman"),
                    ("servant", "Servant"),
                    ("listener", "Listener"),
                ],
                help_text="What role the NPC serves: GUARD, DOORMAN, SERVANT.",
                max_length=20,
            ),
        ),
    ]
