# Generated by Django 5.2.15 on 2026-07-28 17:00

from django.db import migrations, models
import django.db.models.deletion

import core.natural_keys


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0029_alter_consequenceoutcomemodifier_source_kind"),
        ("npc_services", "0030_nameculture_namecultureentry"),
        ("scenes", "0058_sceneactionrequest_cast_openly"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalityTrait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "ease_magnitude",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Points of check modifier a LIKE grants (a DISLIKE costs).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "eased_check",
                    models.ForeignKey(
                        blank=True,
                        help_text="The check a LIKE of this trait eases (a DISLIKE hardens). NULL = flavor only.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="checks.checktype",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="NpcPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valence",
                    models.CharField(
                        choices=[("likes", "Likes"), ("dislikes", "Dislikes")],
                        max_length=10,
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="npc_preferences",
                        to="scenes.persona",
                    ),
                ),
                (
                    "trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holders",
                        to="npc_services.personalitytrait",
                    ),
                ),
            ],
            options={
                "ordering": ["persona", "trait__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("persona", "trait"),
                        name="unique_npc_preference_per_trait",
                    )
                ],
            },
        ),
    ]
