# Generated by Django 5.2.4 on 2026-02-09 02:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

import core.natural_keys


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("checks", "0001_initial"),
        ("traits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttemptCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Attempt categories",
                "ordering": ["display_order", "name"],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="AttemptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="attempts.attemptcategory",
                    ),
                ),
                (
                    "check_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempt_templates",
                        to="checks.checktype",
                    ),
                ),
            ],
            options={
                "ordering": ["category__display_order", "display_order", "name"],
                "unique_together": {("name", "category")},
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="AttemptConsequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='Narrative text shown on roulette (e.g. "Guard raises alarm")',
                        max_length=200,
                    ),
                ),
                (
                    "mechanical_description",
                    models.TextField(
                        blank=True,
                        help_text='Optional mechanical trigger description (e.g. "apply Wanted condition")',
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Probability weight within this outcome tier (minimum 1)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "character_loss",
                    models.BooleanField(
                        default=False,
                        help_text="If True, marks this consequence as permanent character removal",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Ordering on the roulette within tier"
                    ),
                ),
                (
                    "outcome_tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempt_consequences",
                        to="traits.checkoutcome",
                    ),
                ),
                (
                    "attempt_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consequences",
                        to="attempts.attempttemplate",
                    ),
                ),
            ],
            options={
                "unique_together": {("attempt_template", "label")},
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
    ]
