# Generated by Django 5.2.14 on 2026-06-16 23:44

from django.db import migrations, models
import django.db.models.deletion

import core.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("codex", "0004_alter_codexclue_unique_together_and_more"),
        ("missions", "0017_missioninstance_rescue_target"),
        ("roster", "0003_remove_rosterentry_frozen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_kind",
                    models.CharField(
                        choices=[("codex", "Codex Entry"), ("mission", "Mission")],
                        help_text="Which target this clue points at (selects the active FK).",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the clue (e.g. 'Torn Journal Page'). Player-visible.",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="What the player sees when they find this clue. Player-visible."
                    ),
                ),
                (
                    "research_value",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Progress this clue contributes toward resolving its target.",
                    ),
                ),
                (
                    "resolution_mode",
                    models.CharField(
                        choices=[
                            ("automatic", "Automatic (granted on acquisition)"),
                            ("research", "Research project"),
                        ],
                        default="automatic",
                        help_text="How holding this clue becomes having the target.",
                        max_length=20,
                    ),
                ),
                (
                    "target_codex_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="The codex entry this clue hints at (target_kind=CODEX).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clues",
                        to="codex.codexentry",
                    ),
                ),
                (
                    "target_mission",
                    models.ForeignKey(
                        blank=True,
                        help_text="The mission this clue points to (target_kind=MISSION).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clues",
                        to="missions.missiontemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clue",
                "verbose_name_plural": "Clues",
                "ordering": ["name"],
            },
            bases=(core.mixins.DiscriminatorMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CharacterClue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("found_at", models.DateTimeField(auto_now_add=True)),
                (
                    "roster_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clues_held",
                        to="roster.rosterentry",
                    ),
                ),
                (
                    "clue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="held_by",
                        to="clues.clue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Clue",
                "verbose_name_plural": "Character Clues",
                "ordering": ["-found_at"],
                "unique_together": {("roster_entry", "clue")},
            },
        ),
    ]
