# Generated by Django 5.2.14 on 2026-06-17 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clues", "0001_initial"),
        ("evennia_extensions", "0002_roomprofile_tenant_persona"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomClue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detect_difficulty",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Search-check target difficulty to spot this clue here. Placeholder.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this clue is currently findable in the room.",
                    ),
                ),
                (
                    "clue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_placements",
                        to="clues.clue",
                    ),
                ),
                (
                    "room_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hidden_clues",
                        to="evennia_extensions.roomprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Clue",
                "verbose_name_plural": "Room Clues",
                "ordering": ["room_profile", "clue"],
            },
        ),
    ]
