# Generated by Django 5.2.14 on 2026-06-17 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("captivity", "0003_captivity_rescue_template"),
        ("clues", "0004_roomclue_eligibility_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="clue",
            name="target_captivity",
            field=models.ForeignKey(
                blank=True,
                help_text="The captivity this clue points to freeing (target_kind=RESCUE, #931).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rescue_clues",
                to="captivity.captivity",
            ),
        ),
        migrations.AlterField(
            model_name="clue",
            name="target_kind",
            field=models.CharField(
                choices=[
                    ("codex", "Codex Entry"),
                    ("mission", "Mission"),
                    ("rescue", "Rescue (a held captive)"),
                ],
                help_text="Which target this clue points at (selects the active FK).",
                max_length=20,
            ),
        ),
    ]
