# Generated by Django 5.2.4 on 2026-04-17 05:30

from django.db import migrations, models
import django.db.models.deletion


def _clear_existing_triggers(apps, schema_editor):
    """Delete any pre-existing Trigger rows before adding non-null fields.

    Task 4 adds a non-null FK (source_condition) and a non-null choice field
    (scope) to flows.Trigger. Existing rows (none expected, but belt-and-
    suspenders) would violate the new constraints. Clearing is safe because
    Triggers are expected to be installed by ConditionInstances, and prior
    Task 1-3 work has not yet put live Trigger data into production.
    """
    Trigger = apps.get_model("flows", "Trigger")
    Trigger.objects.all().delete()


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("conditions", "0002_initial"),
        ("flows", "0002_mvp_events"),
    ]

    operations = [
        migrations.RunPython(_clear_existing_triggers, _noop),
        migrations.AddField(
            model_name="trigger",
            name="scope",
            field=models.CharField(
                choices=[("personal", "Personal"), ("room", "Room")],
                help_text="Dispatch scope - PERSONAL (subject) or ROOM (location).",
                max_length=16,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trigger",
            name="source_condition",
            field=models.ForeignKey(
                help_text="Condition that installed this trigger. Required.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="triggers",
                to="conditions.conditioninstance",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trigger",
            name="source_stage",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, active only while source_condition is at this stage.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stage_triggers",
                to="conditions.conditionstage",
            ),
        ),
    ]
