# Generated by Django 5.2.4 on 2026-04-18 00:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flows", "0006_alter_flowstepdefinition_action"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trigger",
            name="scope",
        ),
    ]
