# Generated by Django 5.2.4 on 2026-04-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flows", "0007_drop_trigger_scope"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="triggerdefinition",
            name="event",
        ),
        migrations.AddField(
            model_name="triggerdefinition",
            name="event_name",
            field=models.CharField(
                choices=[
                    ("attack_pre_resolve", "Attack Pre-Resolve"),
                    ("attack_landed", "Attack Landed"),
                    ("attack_missed", "Attack Missed"),
                    ("damage_pre_apply", "Damage Pre-Apply"),
                    ("damage_applied", "Damage Applied"),
                    ("character_incapacitated", "Character Incapacitated"),
                    ("character_killed", "Character Killed"),
                    ("move_pre_depart", "Move: Pre-Depart"),
                    ("moved", "Moved"),
                    ("examine_pre", "Examine Pre"),
                    ("examined", "Examined"),
                    ("condition_pre_apply", "Condition Pre-Apply"),
                    ("condition_applied", "Condition Applied"),
                    ("condition_stage_changed", "Condition Stage Changed"),
                    ("condition_removed", "Condition Removed"),
                    ("technique_pre_cast", "Technique Pre-Cast"),
                    ("technique_cast", "Technique Cast"),
                    ("technique_affected", "Technique Affected"),
                ],
                default="examined",
                help_text="The event name this trigger listens for.",
                max_length=64,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Event",
        ),
    ]
