# Generated by Django 5.2.4 on 2025-07-28 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "objects",
            "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BehaviorPackageDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "service_function_path",
                    models.CharField(
                        help_text="Python path to the service function for this package.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BehaviorPackageInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hook",
                    models.CharField(
                        help_text="Name of the hook where this package applies.",
                        max_length=100,
                    ),
                ),
                ("data", models.JSONField(blank=True, null=True)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="behaviors.behaviorpackagedefinition",
                    ),
                ),
                (
                    "obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_packages",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
