# Generated by Django 5.2.15 on 2026-07-28 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("clues", "0012_cluetrigger_clue_trigger_unique_room_clue_and_more"),
        ("scenes", "0058_sceneactionrequest_cast_openly"),
        ("tasking", "0002_listenerpost_listenerharvest"),
    ]

    operations = [
        migrations.AddField(
            model_name="listenerharvest",
            name="planted_clue",
            field=models.ForeignKey(
                blank=True,
                help_text="A flip controller's red herring delivered instead of a real catch (#2820 phase 4). Collection grants this clue as if it were real.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="clues.clue",
            ),
        ),
        migrations.AddField(
            model_name="listenerpost",
            name="flipped_controller",
            field=models.ForeignKey(
                blank=True,
                help_text="The rival persona who truly controls this listener (double agent). The original handler's board shows nothing. Hidden.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flipped_listener_posts",
                to="scenes.persona",
            ),
        ),
        migrations.AddField(
            model_name="listenerpost",
            name="pending_plant",
            field=models.ForeignKey(
                blank=True,
                help_text="A red-herring clue (accusation-provenance secret) queued by the flip controller; the next harvest delivers it. Hidden.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="clues.clue",
            ),
        ),
        migrations.AddField(
            model_name="listenerpost",
            name="suppressed_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Intimidated into silence until this moment. Hidden from the board.",
                null=True,
            ),
        ),
    ]
