# Generated by Django 5.2.15 on 2026-07-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agriculture", "0003_foodconfig_pool_difficulty_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodconfig",
            name="army_food_per_member",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Food consumed per engaged covenant member at army mobilization. PLACEHOLDER.",
            ),
        ),
        migrations.AddField(
            model_name="foodconfig",
            name="max_provisioning_morale_penalty",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Maximum morale points subtracted from units at zero provisioning. PLACEHOLDER.",
            ),
        ),
        migrations.AddField(
            model_name="foodconfig",
            name="max_provisioning_strength_penalty",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Maximum strength points subtracted from units at zero provisioning. PLACEHOLDER.",
            ),
        ),
    ]
