# Generated by Django 5.2.14 on 2026-07-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_alter_contributionmethod_kind_alter_project_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributionmethod",
            name="kind",
            field=models.CharField(
                choices=[
                    ("BUILDING_CONSTRUCTION", "Building Construction"),
                    ("BUILDING_EXTENSION", "Building Extension"),
                    ("INTERIOR_DESIGN", "Interior Design"),
                    ("ROOM_FEATURE_PROGRESSION", "Room Feature Progression"),
                    ("RESEARCH", "Research"),
                    ("RANSOM", "Ransom"),
                    ("TEST_KIND", "Test Kind (framework tests only)"),
                ],
                help_text="The ProjectKind whose projects offer this contribution method.",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="kind",
            field=models.CharField(
                choices=[
                    ("BUILDING_CONSTRUCTION", "Building Construction"),
                    ("BUILDING_EXTENSION", "Building Extension"),
                    ("INTERIOR_DESIGN", "Interior Design"),
                    ("ROOM_FEATURE_PROGRESSION", "Room Feature Progression"),
                    ("RESEARCH", "Research"),
                    ("RANSOM", "Ransom"),
                    ("TEST_KIND", "Test Kind (framework tests only)"),
                ],
                help_text="Discriminator selecting which per-kind details model applies.",
                max_length=40,
            ),
        ),
    ]
