# Generated by Django 5.2.14 on 2026-07-02 18:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("areas", "0011_area_climate"),
        ("scenes", "0042_sceneactiondeclaration_succor_resolution_and_more"),
        ("societies", "0018_organization_membership_lifecycle"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrimeKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="PersonaHeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.PositiveIntegerField(default=0)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heat_rows",
                        to="areas.area",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heat_rows",
                        to="scenes.persona",
                    ),
                ),
                (
                    "society",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heat_rows",
                        to="societies.society",
                    ),
                ),
            ],
            options={
                "verbose_name": "Persona heat",
                "verbose_name_plural": "Persona heat",
                "ordering": ["-value"],
            },
        ),
        migrations.CreateModel(
            name="HeatSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "deed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="heat_sources",
                        to="societies.legendentry",
                    ),
                ),
                (
                    "heat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="justice.personaheat",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="AreaLaw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heat_weight",
                    models.IntegerField(
                        default=10,
                        help_text="Heat minted per accrual event here (PLACEHOLDER magnitudes).",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "exempts",
                    models.BooleanField(
                        default=False,
                        help_text="Explicitly legal here despite an ancestor's ban (short-circuits the cascade).",
                    ),
                ),
                (
                    "punishment",
                    models.CharField(
                        blank=True,
                        help_text="Admin-editable flavor shown on the crime tab (PLACEHOLDER until authored).",
                        max_length=200,
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laws",
                        to="areas.area",
                    ),
                ),
                (
                    "crime_kind",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="laws",
                        to="justice.crimekind",
                    ),
                ),
            ],
            options={
                "ordering": ["area_id", "crime_kind_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("area", "crime_kind"), name="unique_area_crime_law"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DeedCrimeTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crime_kind",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deed_tags",
                        to="justice.crimekind",
                    ),
                ),
                (
                    "deed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crime_tags",
                        to="societies.legendentry",
                    ),
                ),
            ],
            options={
                "ordering": ["deed_id", "crime_kind_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("deed", "crime_kind"), name="unique_deed_crime_tag"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="personaheat",
            index=models.Index(
                fields=["persona", "society"], name="justice_per_persona_d2415d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="personaheat",
            constraint=models.UniqueConstraint(
                fields=("persona", "area", "society"),
                name="unique_persona_area_society_heat",
            ),
        ),
    ]
