# Generated by Django 5.2.4 on 2026-01-28 17:46

from django.db import migrations, models
import django.db.models.deletion

import core.natural_keys


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistinctionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this category.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier for this category.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what distinctions belong in this category.",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which to display this category (lower = first).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distinction Category",
                "verbose_name_plural": "Distinction Categories",
                "ordering": ["display_order", "name"],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="DistinctionPrerequisite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_json",
                    models.JSONField(
                        help_text="JSON structure defining the prerequisite rule with AND/OR/NOT logic."
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable description of the prerequisite.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distinction Prerequisite",
                "verbose_name_plural": "Distinction Prerequisites",
            },
        ),
        migrations.CreateModel(
            name="DistinctionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this tag.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier for this tag.",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Distinction Tag",
                "verbose_name_plural": "Distinction Tags",
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Distinction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this distinction.", max_length=100
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier for this distinction.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this distinction represents.",
                    ),
                ),
                (
                    "cost_per_rank",
                    models.IntegerField(
                        default=0,
                        help_text="Cost per rank. Positive costs points, negative reimburses.",
                    ),
                ),
                (
                    "max_rank",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum rank. 1 means binary (have it or don't).",
                    ),
                ),
                (
                    "allow_other",
                    models.BooleanField(
                        default=False,
                        help_text="True if players can specify a custom 'other' value.",
                    ),
                ),
                (
                    "variants_are_mutually_exclusive",
                    models.BooleanField(
                        default=False,
                        help_text="If True, only one variant of this parent can be selected per character.",
                    ),
                ),
                (
                    "trust_value",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum trust value required to take this distinction.",
                        null=True,
                    ),
                ),
                (
                    "is_automatic",
                    models.BooleanField(
                        default=False,
                        help_text="True if this distinction is automatically granted.",
                    ),
                ),
                (
                    "requires_slot_filled",
                    models.BooleanField(
                        default=False,
                        help_text="True if this requires a slot selection to be valid.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this distinction is available for selection.",
                    ),
                ),
                (
                    "mutually_exclusive_with",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Distinctions that are mutually exclusive with this one.",
                        to="distinctions.distinction",
                    ),
                ),
                (
                    "parent_distinction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent distinction if this is a variant.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="distinctions.distinction",
                    ),
                ),
                (
                    "trust_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Trust category required to take this distinction.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gated_distinctions",
                        to="stories.trustcategory",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category this distinction belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="distinctions",
                        to="distinctions.distinctioncategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distinction",
                "verbose_name_plural": "Distinctions",
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CharacterDistinctionOther",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "freeform_text",
                    models.CharField(
                        help_text="What the player entered as their 'Other' value.",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending Review"),
                            ("approved", "Approved"),
                            ("mapped", "Mapped to Distinction"),
                        ],
                        default="pending_review",
                        help_text="Current status of this 'Other' entry.",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this entry was created."
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        help_text="The character who entered this 'Other' distinction.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distinction_other_entries",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "parent_distinction",
                    models.ForeignKey(
                        help_text="The variant parent distinction this 'Other' belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_entries",
                        to="distinctions.distinction",
                    ),
                ),
                (
                    "staff_mapped_distinction",
                    models.ForeignKey(
                        blank=True,
                        help_text="The distinction this was mapped to by staff.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mapped_from_other",
                        to="distinctions.distinction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Distinction Other Entry",
                "verbose_name_plural": "Character Distinction Other Entries",
            },
        ),
        migrations.CreateModel(
            name="CharacterDistinction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Current rank of this distinction (1 for binary distinctions).",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Player notes about this distinction.",
                        max_length=280,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("character_creation", "Character Creation"),
                            ("gameplay", "Gameplay"),
                        ],
                        default="character_creation",
                        help_text="How this character acquired the distinction.",
                        max_length=30,
                    ),
                ),
                (
                    "is_temporary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this distinction is temporary (e.g., magical effect).",
                    ),
                ),
                (
                    "source_description",
                    models.TextField(
                        blank=True,
                        help_text="Description of how the distinction was acquired (for gameplay).",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this distinction was granted.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this distinction was last modified.",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        help_text="The character who has this distinction.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distinctions",
                        to="objects.objectdb",
                    ),
                ),
                (
                    "distinction",
                    models.ForeignKey(
                        help_text="The distinction granted to this character.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="character_grants",
                        to="distinctions.distinction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Distinction",
                "verbose_name_plural": "Character Distinctions",
            },
        ),
        migrations.CreateModel(
            name="DistinctionEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value_per_rank",
                    models.IntegerField(
                        blank=True,
                        help_text="Value per rank for linear scaling.",
                        null=True,
                    ),
                ),
                (
                    "scaling_values",
                    models.JSONField(
                        blank=True,
                        help_text="List of values for non-linear scaling [rank1, rank2, ...].",
                        null=True,
                    ),
                ),
                (
                    "amplifies_sources_by",
                    models.IntegerField(
                        blank=True,
                        help_text="Bonus to OTHER sources of this modifier type (+2 = all other Allure +2).",
                        null=True,
                    ),
                ),
                (
                    "grants_immunity_to_negative",
                    models.BooleanField(
                        default=False,
                        help_text="If true, character is immune to negative modifiers of this type.",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of what this effect does."),
                ),
                (
                    "distinction",
                    models.ForeignKey(
                        help_text="The distinction this effect belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="effects",
                        to="distinctions.distinction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distinction Effect",
                "verbose_name_plural": "Distinction Effects",
            },
        ),
    ]
