# Generated by Django 5.2.4 on 2026-03-06 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("distinctions", "0001_initial"),
        ("mechanics", "0001_initial"),
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="distinction",
            name="trust_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Trust category required to take this distinction.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gated_distinctions",
                to="stories.trustcategory",
            ),
        ),
        migrations.AddField(
            model_name="characterdistinctionother",
            name="parent_distinction",
            field=models.ForeignKey(
                help_text="The variant parent distinction this 'Other' belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="other_entries",
                to="distinctions.distinction",
            ),
        ),
        migrations.AddField(
            model_name="characterdistinctionother",
            name="staff_mapped_distinction",
            field=models.ForeignKey(
                blank=True,
                help_text="The distinction this was mapped to by staff.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mapped_from_other",
                to="distinctions.distinction",
            ),
        ),
        migrations.AddField(
            model_name="characterdistinction",
            name="distinction",
            field=models.ForeignKey(
                help_text="The distinction granted to this character.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="character_grants",
                to="distinctions.distinction",
            ),
        ),
        migrations.AddField(
            model_name="distinction",
            name="category",
            field=models.ForeignKey(
                help_text="Category this distinction belongs to.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="distinctions",
                to="distinctions.distinctioncategory",
            ),
        ),
        migrations.AddField(
            model_name="distinctioneffect",
            name="distinction",
            field=models.ForeignKey(
                help_text="The distinction this effect belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="effects",
                to="distinctions.distinction",
            ),
        ),
        migrations.AddField(
            model_name="distinctioneffect",
            name="target",
            field=models.ForeignKey(
                help_text="The modifier type this effect targets.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="distinction_effects",
                to="mechanics.modifiertarget",
            ),
        ),
        migrations.AddField(
            model_name="distinctionprerequisite",
            name="distinction",
            field=models.ForeignKey(
                help_text="The distinction this prerequisite belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prerequisites",
                to="distinctions.distinction",
            ),
        ),
        migrations.AddField(
            model_name="distinction",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags for filtering and searching.",
                related_name="distinctions",
                to="distinctions.distinctiontag",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="characterdistinction",
            unique_together={("character", "distinction")},
        ),
        migrations.AlterUniqueTogether(
            name="distinctioneffect",
            unique_together={("distinction", "target")},
        ),
        migrations.AlterUniqueTogether(
            name="distinctionprerequisite",
            unique_together={("distinction", "key")},
        ),
    ]
