# Generated by Django 5.2.14 on 2026-06-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("distinctions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterdistinction",
            name="visibility_override",
            field=models.CharField(
                blank=True,
                choices=[("public", "Public"), ("private", "Private")],
                default=None,
                help_text="Player's per-character privacy gate. When set, overrides the distinction kind's default visibility; null inherits the kind default.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="distinction",
            name="default_visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="public",
                help_text="Default profile visibility for this distinction kind (player-overridable).",
                max_length=10,
            ),
        ),
    ]
