# Generated by Django 5.2.4 on 2026-01-21 22:07

from django.db import migrations, models
import django.db.models.deletion

import core.natural_keys


class Migration(migrations.Migration):
    dependencies = [
        ("distinctions", "0003_remove_distinctiontag_ordering"),
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Distinction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this distinction.", max_length=100
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier for this distinction.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this distinction represents.",
                    ),
                ),
                (
                    "cost_per_rank",
                    models.IntegerField(
                        default=0,
                        help_text="Cost per rank. Positive costs points, negative reimburses.",
                    ),
                ),
                (
                    "max_rank",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum rank. 1 means binary (have it or don't).",
                    ),
                ),
                (
                    "is_variant_parent",
                    models.BooleanField(
                        default=False,
                        help_text="True if this distinction has variants to choose from.",
                    ),
                ),
                (
                    "allow_other",
                    models.BooleanField(
                        default=False,
                        help_text="True if players can specify a custom 'other' value.",
                    ),
                ),
                (
                    "trust_required",
                    models.BooleanField(
                        default=False,
                        help_text="True if this distinction requires trust to take.",
                    ),
                ),
                (
                    "trust_value",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum trust value required if trust_required is True.",
                        null=True,
                    ),
                ),
                (
                    "is_automatic",
                    models.BooleanField(
                        default=False,
                        help_text="True if this distinction is automatically granted.",
                    ),
                ),
                (
                    "requires_slot_filled",
                    models.BooleanField(
                        default=False,
                        help_text="True if this requires a slot selection to be valid.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this distinction is available for selection.",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category this distinction belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="distinctions",
                        to="distinctions.distinctioncategory",
                    ),
                ),
                (
                    "parent_distinction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent distinction if this is a variant.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="distinctions.distinction",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Tags for filtering and searching.",
                        related_name="distinctions",
                        to="distinctions.distinctiontag",
                    ),
                ),
                (
                    "trust_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Trust category required if trust_required is True.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gated_distinctions",
                        to="stories.trustcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distinction",
                "verbose_name_plural": "Distinctions",
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
    ]
