# Generated by Django 5.2.4 on 2026-01-21 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("distinctions", "0004_distinction"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistinctionEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "effect_type",
                    models.CharField(
                        choices=[
                            ("stat_modifier", "Stat Modifier"),
                            ("affinity_modifier", "Affinity Modifier"),
                            ("resonance_modifier", "Resonance Modifier"),
                            ("roll_modifier", "Roll Modifier"),
                            ("code_handled", "Code Handled"),
                        ],
                        help_text="The type of mechanical effect.",
                        max_length=30,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        blank=True,
                        help_text="What this effect targets (e.g., 'allure', 'strength').",
                        max_length=100,
                    ),
                ),
                (
                    "value_per_rank",
                    models.IntegerField(
                        blank=True,
                        help_text="Value per rank for linear scaling.",
                        null=True,
                    ),
                ),
                (
                    "scaling_values",
                    models.JSONField(
                        blank=True,
                        help_text="List of values for non-linear scaling [rank1, rank2, ...].",
                        null=True,
                    ),
                ),
                (
                    "slug_reference",
                    models.SlugField(
                        blank=True,
                        help_text="Reference slug for code-handled effects.",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of what this effect does."),
                ),
                (
                    "distinction",
                    models.ForeignKey(
                        help_text="The distinction this effect belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="effects",
                        to="distinctions.distinction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distinction Effect",
                "verbose_name_plural": "Distinction Effects",
            },
        ),
    ]
