# Generated by Django 5.2.15 on 2026-07-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("distinctions", "0005_alter_characterdistinction_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterdistinction",
            name="origin",
            field=models.CharField(
                choices=[
                    ("character_creation", "Character Creation"),
                    ("gameplay", "Gameplay"),
                    ("gm_award", "GM Award"),
                    ("achievement_auto_grant", "Achievement"),
                    ("consequence_pool", "Consequence"),
                    ("endorsement_threshold", "Endorsement Threshold"),
                    ("species", "Species"),
                ],
                default="character_creation",
                help_text="How this character acquired the distinction.",
                max_length=30,
            ),
        ),
    ]
