# Generated by Django 5.2.15 on 2026-07-17 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("distinctions", "0006_alter_characterdistinction_origin"),
        ("magic", "0109_giftacquisitionconfig_imbue_ap_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="characterdistinction",
            name="from_glimpse",
            field=models.ForeignKey(
                blank=True,
                help_text="The Glimpse (aura) this distinction was born in; null = no glimpse link.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="glimpse_born_distinctions",
                to="magic.characteraura",
            ),
        ),
    ]
