# Generated by Django 5.2.4 on 2026-01-28 03:27

from django.db import migrations


def add_tireless_and_efficient(apps, schema_editor):
    """Add Tireless and Efficient distinctions."""
    DistinctionCategory = apps.get_model("distinctions", "DistinctionCategory")
    Distinction = apps.get_model("distinctions", "Distinction")
    DistinctionEffect = apps.get_model("distinctions", "DistinctionEffect")
    ModifierType = apps.get_model("mechanics", "ModifierType")

    # Get or create the Personality category
    personality, _ = DistinctionCategory.objects.get_or_create(
        slug="personality",
        defaults={
            "name": "Personality",
            "description": "Character personality traits and behavioral tendencies",
            "display_order": 3,
        },
    )

    # Get modifier types
    daily_regen = ModifierType.objects.get(
        category__name="action_points",
        name="ap_daily_regen",
    )
    weekly_regen = ModifierType.objects.get(
        category__name="action_points",
        name="ap_weekly_regen",
    )
    ap_maximum = ModifierType.objects.get(
        category__name="action_points",
        name="ap_maximum",
    )

    # === Tireless ===
    tireless, created = Distinction.objects.get_or_create(
        slug="tireless",
        defaults={
            "name": "Tireless",
            "description": (
                "You possess an unusual reserve of energy, able to keep going "
                "when others would need rest."
            ),
            "category": personality,
            "cost_per_rank": 15,  # Advantage: costs 15 points
            "max_rank": 1,
            "is_active": True,
        },
    )
    if created:
        DistinctionEffect.objects.create(
            distinction=tireless,
            target=daily_regen,
            value_per_rank=1,  # Half of Indolent's -2
            description="Increases daily AP regeneration by 1",
        )
        DistinctionEffect.objects.create(
            distinction=tireless,
            target=weekly_regen,
            value_per_rank=20,  # Half of Indolent's -40
            description="Increases weekly AP regeneration by 20",
        )

    # === Efficient ===
    efficient, created = Distinction.objects.get_or_create(
        slug="efficient",
        defaults={
            "name": "Efficient",
            "description": (
                "You make the most of your efforts, able to juggle more responsibilities than most."
            ),
            "category": personality,
            "cost_per_rank": 10,  # Advantage: costs 10 points
            "max_rank": 1,
            "is_active": True,
        },
    )
    if created:
        DistinctionEffect.objects.create(
            distinction=efficient,
            target=ap_maximum,
            value_per_rank=100,  # 50% increase of base 200
            description="Increases maximum AP capacity by 100",
        )


def remove_tireless_and_efficient(apps, schema_editor):
    """Remove Tireless and Efficient distinctions."""
    Distinction = apps.get_model("distinctions", "Distinction")
    Distinction.objects.filter(slug__in=["tireless", "efficient"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("distinctions", "0007_add_indolent_distinction"),
        ("mechanics", "0005_add_ap_maximum_modifier"),
    ]

    operations = [
        migrations.RunPython(
            add_tireless_and_efficient,
            remove_tireless_and_efficient,
        ),
    ]
