# Generated by Django 5.2.4 on 2026-01-28

from django.db import migrations


def add_giants_blood_distinction(apps, schema_editor):
    """Add Giant's Blood distinction with strength and height band effects."""
    DistinctionCategory = apps.get_model("distinctions", "DistinctionCategory")
    Distinction = apps.get_model("distinctions", "Distinction")
    DistinctionEffect = apps.get_model("distinctions", "DistinctionEffect")
    ModifierType = apps.get_model("mechanics", "ModifierType")

    # Get or create the Physical category
    physical, _ = DistinctionCategory.objects.get_or_create(
        slug="physical",
        defaults={
            "name": "Physical",
            "description": "Physical traits and characteristics",
            "display_order": 1,
        },
    )

    # Get the modifier types
    strength = ModifierType.objects.get(
        category__name="stat",
        name="strength",
    )
    height_band = ModifierType.objects.get(
        category__name="height_band",
        name="max_height_band_bonus",
    )

    # Create the Giant's Blood distinction
    giants_blood, created = Distinction.objects.get_or_create(
        slug="giants-blood",
        defaults={
            "name": "Giant's Blood",
            "description": (
                "You have the blood of giants in your lineage, granting you "
                "unusual size and strength. You tower over most of your peers "
                "and possess raw physical power to match."
            ),
            "category": physical,
            "cost_per_rank": 20,  # Advantage: costs 20 points
            "max_rank": 1,
            "is_active": True,
        },
    )

    if created:
        # Create the effects
        # +1.0 to strength display value = +10 internal value
        DistinctionEffect.objects.create(
            distinction=giants_blood,
            target=strength,
            value_per_rank=10,
            description="Increases Strength by 1.0",
        )
        # +1 height band above normal maximum
        DistinctionEffect.objects.create(
            distinction=giants_blood,
            target=height_band,
            value_per_rank=1,
            description="Can select one height band taller than normal maximum",
        )


def remove_giants_blood_distinction(apps, schema_editor):
    """Remove the Giant's Blood distinction."""
    Distinction = apps.get_model("distinctions", "Distinction")
    # CASCADE will delete the effects
    Distinction.objects.filter(slug="giants-blood").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("distinctions", "0008_add_tireless_and_efficient"),
        ("mechanics", "0006_add_stat_height_development_modifiers"),
    ]

    operations = [
        migrations.RunPython(
            add_giants_blood_distinction,
            remove_giants_blood_distinction,
        ),
    ]
