# Generated by Django 5.2.4 on 2026-04-20 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("combat", "0002_initial"),
        ("conditions", "0002_initial"),
        ("magic", "0017_threadweavingunlock_threadweaving_no_capstone"),
    ]

    operations = [
        migrations.CreateModel(
            name="CombatPull",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.PositiveIntegerField()),
                ("tier", models.PositiveSmallIntegerField()),
                ("resonance_spent", models.PositiveIntegerField()),
                ("anima_spent", models.PositiveIntegerField()),
                ("committed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combat_pulls",
                        to="combat.combatencounter",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combat_pulls",
                        to="combat.combatparticipant",
                    ),
                ),
                (
                    "resonance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="combat_pulls",
                        to="magic.resonance",
                    ),
                ),
                (
                    "threads",
                    models.ManyToManyField(related_name="combat_pulls", to="magic.thread"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CombatPullResolvedEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("FLAT_BONUS", "Flat Bonus"),
                            ("INTENSITY_BUMP", "Intensity Bump"),
                            ("VITAL_BONUS", "Vital Bonus"),
                            ("CAPABILITY_GRANT", "Capability Grant"),
                            ("NARRATIVE_ONLY", "Narrative Only"),
                        ],
                        max_length=32,
                    ),
                ),
                ("authored_value", models.IntegerField(blank=True, null=True)),
                ("level_multiplier", models.PositiveSmallIntegerField()),
                ("scaled_value", models.IntegerField(blank=True, null=True)),
                (
                    "vital_target",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MAX_HEALTH", "Max Health"),
                            ("DAMAGE_TAKEN_REDUCTION", "Damage Taken Reduction"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("source_thread_level", models.PositiveSmallIntegerField()),
                ("source_tier", models.PositiveSmallIntegerField()),
                ("narrative_snippet", models.TextField(blank=True)),
                (
                    "granted_capability",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thread_pull_grants",
                        to="conditions.capabilitytype",
                    ),
                ),
                (
                    "pull",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolved_effects",
                        to="combat.combatpull",
                    ),
                ),
                (
                    "source_thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resolved_pull_effects",
                        to="magic.thread",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="combatpull",
            index=models.Index(
                fields=["encounter", "round_number"],
                name="combat_comb_encount_73b1ee_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="combatpull",
            unique_together={("participant", "round_number")},
        ),
        migrations.AddConstraint(
            model_name="combatpullresolvedeffect",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "FLAT_BONUS"), _negated=True),
                    models.Q(
                        ("scaled_value__isnull", False),
                        ("granted_capability__isnull", True),
                        ("narrative_snippet", ""),
                        ("vital_target__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="combatpullresolvedeffect_flat_bonus_payload",
            ),
        ),
        migrations.AddConstraint(
            model_name="combatpullresolvedeffect",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "INTENSITY_BUMP"), _negated=True),
                    models.Q(
                        ("scaled_value__isnull", False),
                        ("granted_capability__isnull", True),
                        ("narrative_snippet", ""),
                        ("vital_target__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="combatpullresolvedeffect_intensity_bump_payload",
            ),
        ),
        migrations.AddConstraint(
            model_name="combatpullresolvedeffect",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "VITAL_BONUS"), _negated=True),
                    models.Q(
                        ("scaled_value__isnull", False),
                        ("vital_target__isnull", False),
                        ("granted_capability__isnull", True),
                        ("narrative_snippet", ""),
                    ),
                    _connector="OR",
                ),
                name="combatpullresolvedeffect_vital_bonus_payload",
            ),
        ),
        migrations.AddConstraint(
            model_name="combatpullresolvedeffect",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "CAPABILITY_GRANT"), _negated=True),
                    models.Q(
                        ("granted_capability__isnull", False),
                        ("scaled_value__isnull", True),
                        ("narrative_snippet", ""),
                        ("vital_target__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="combatpullresolvedeffect_capability_grant_payload",
            ),
        ),
        migrations.AddConstraint(
            model_name="combatpullresolvedeffect",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "NARRATIVE_ONLY"), _negated=True),
                    models.Q(
                        models.Q(("narrative_snippet", ""), _negated=True),
                        ("scaled_value__isnull", True),
                        ("granted_capability__isnull", True),
                        ("vital_target__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="combatpullresolvedeffect_narrative_only_payload",
            ),
        ),
    ]
