# Generated by Django 5.2.4 on 2026-04-07 18:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("combat", "0002_combatopponent_persona"),
        ("combat", "0003_remove_combatencounter_episode_and_more"),
    ]

    operations = []
