# Generated by Django 5.2.14 on 2026-06-12 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0007_consequence_theater"),
        ("combat", "0007_combatencounter_completed_at_combatencounter_outcome_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EscalationCurve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "start_round",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="First round the escalation tick fires (>=2 keeps round one calm).",
                    ),
                ),
                (
                    "intensity_step",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Intensity modifier added to each participant's engagement per tick.",
                    ),
                ),
                (
                    "pace_difficulty_base",
                    models.PositiveIntegerField(
                        default=0, help_text="Base difficulty of the pace check."
                    ),
                ),
                (
                    "pace_difficulty_per_level",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Difficulty added per accumulated escalation level.",
                    ),
                ),
                (
                    "control_step_on_success",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Control modifier gained on a pace-check success (success_level >= 1).",
                    ),
                ),
                (
                    "control_step_on_partial",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Control modifier gained on a partial success (success_level == 0).",
                    ),
                ),
                (
                    "control_step_on_botch",
                    models.IntegerField(
                        default=-1,
                        help_text="Control modifier change on a botch (success_level <= -2); author negative.",
                    ),
                ),
                (
                    "max_escalation_level",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Tick stops raising pressure past this level. 0 = uncapped.",
                    ),
                ),
                (
                    "spike_intensity_amount",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Intensity spike applied to bonded co-combatants when an ally falls.",
                    ),
                ),
                (
                    "spike_minimum_track_points",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum developed_points on a spike-fueling relationship track for the bond to qualify.",
                    ),
                ),
                (
                    "tick_narration",
                    models.TextField(
                        blank=True,
                        help_text="Narrative line surfaced to the combat panel on each tick.",
                    ),
                ),
                (
                    "pace_check_type",
                    models.ForeignKey(
                        help_text="Check rolled each tick to keep control in pace with intensity.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escalation_curves",
                        to="checks.checktype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escalation Curve",
                "verbose_name_plural": "Escalation Curves",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="combatencounter",
            name="escalation_curve",
            field=models.ForeignKey(
                blank=True,
                help_text="Authored escalation ramp; null = this encounter does not escalate (#872).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="encounters",
                to="combat.escalationcurve",
            ),
        ),
    ]
