# Generated by Django 5.2.4 on 2026-05-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("combat", "0007_threatpoolentry_damage_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combatpullresolvedeffect",
            name="kind",
            field=models.CharField(
                choices=[
                    ("FLAT_BONUS", "Flat Bonus"),
                    ("INTENSITY_BUMP", "Intensity Bump"),
                    ("VITAL_BONUS", "Vital Bonus"),
                    ("CAPABILITY_GRANT", "Capability Grant"),
                    ("NARRATIVE_ONLY", "Narrative Only"),
                    ("CORRUPTION_RESISTANCE", "Corruption Resistance"),
                ],
                max_length=32,
            ),
        ),
    ]
