# Generated by Django 5.2.14 on 2026-05-22 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0004_initial"),
        ("character_sheets", "0005_alter_charactersheet_current_residence"),
        ("combat", "0010_clashconfig_strainconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flavor",
                    models.CharField(
                        choices=[
                            ("CLASH", "Clash"),
                            ("LOCK", "Lock"),
                            ("WARD", "Ward"),
                            ("BREAK", "Break"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "lock_pc_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUSTAINING", "Sustaining"),
                            ("ESCAPING", "Escaping"),
                        ],
                        help_text="Set iff flavor=LOCK; null otherwise.",
                        max_length=12,
                        null=True,
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
                ("pc_win_threshold", models.IntegerField()),
                (
                    "npc_win_threshold",
                    models.IntegerField(
                        blank=True,
                        help_text="Set iff flavor=CLASH; null otherwise.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("RESOLVED", "Resolved")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("started_round", models.PositiveIntegerField()),
                ("resolved_round", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PC_DECISIVE", "PC Decisive"),
                            ("PC_MARGINAL", "PC Marginal"),
                            ("MUTUAL", "Mutual"),
                            ("NPC_MARGINAL", "NPC Marginal"),
                            ("NPC_DECISIVE", "NPC Decisive"),
                            ("ABANDONED", "Abandoned"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "ward_ends_on_round",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Set iff flavor=WARD; null otherwise.",
                        null=True,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clashes",
                        to="combat.combatencounter",
                    ),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="character_sheets.charactersheet",
                    ),
                ),
                (
                    "npc_opponent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clashes",
                        to="combat.combatopponent",
                    ),
                ),
                (
                    "per_round_consequence_pool",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="actions.consequencepool",
                    ),
                ),
                (
                    "resolution_consequence_pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="actions.consequencepool",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                models.Q(("flavor", "LOCK"), _negated=True),
                                ("lock_pc_role__isnull", False),
                                _connector="OR",
                            ),
                            models.Q(
                                ("flavor", "LOCK"),
                                ("lock_pc_role__isnull", True),
                                _connector="OR",
                            ),
                        ),
                        name="clash_lock_role_iff_lock_flavor",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                models.Q(("flavor", "CLASH"), _negated=True),
                                ("npc_win_threshold__isnull", False),
                                _connector="OR",
                            ),
                            models.Q(
                                ("flavor", "CLASH"),
                                ("npc_win_threshold__isnull", True),
                                _connector="OR",
                            ),
                        ),
                        name="clash_npc_threshold_iff_clash_flavor",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                models.Q(("flavor", "WARD"), _negated=True),
                                ("ward_ends_on_round__isnull", False),
                                _connector="OR",
                            ),
                            models.Q(
                                ("flavor", "WARD"),
                                ("ward_ends_on_round__isnull", True),
                                _connector="OR",
                            ),
                        ),
                        name="clash_ward_round_iff_ward_flavor",
                    ),
                ],
            },
        ),
    ]
