# Generated by Django 5.2.14 on 2026-05-22 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0004_initial"),
        ("combat", "0011_clash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clash",
            name="per_round_consequence_pool",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional per-round consequence pool fired each round for incremental feedback; omit for flavors with no per-round effects.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="actions.consequencepool",
            ),
        ),
    ]
