# Generated by Django 5.2.14 on 2026-07-06 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0020_alter_consequenceeffect_position_destination"),
        ("combat", "0030_threatpoolentry_on_hit_consequence_pool"),
    ]

    operations = [
        migrations.AddField(
            model_name="threatpoolentry",
            name="defense_check_type",
            field=models.ForeignKey(
                blank=True,
                help_text="CheckType the targeted PC rolls to evade/mitigate this attack. Null = flat base_damage with no defense roll (backward-compatible).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="threat_pool_entries",
                to="checks.checktype",
            ),
        ),
    ]
