# Generated by Django 5.2.14 on 2026-07-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("combat", "0033_escalationcurve_hated_foe_spike_intensity_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combatroundaction",
            name="maneuver",
            field=models.CharField(
                blank=True,
                choices=[
                    ("flee", "Flee"),
                    ("cover", "Cover"),
                    ("yield", "Yield"),
                    ("interpose", "Interpose"),
                    ("succor", "Succor"),
                    ("engage", "Engage"),
                    ("disengage", "Disengage"),
                ],
                help_text="Special maneuver this declaration is (flee/cover/yield/interpose); null = normal action.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dramaticsurgerecord",
            name="trigger_kind",
            field=models.CharField(
                choices=[
                    ("ally_fallen", "Ally Fallen"),
                    ("ally_peril", "Ally In Peril"),
                    ("hated_foe", "Hated Foe"),
                    ("high_stakes", "High Stakes"),
                    ("interference", "Interference"),
                ],
                max_length=20,
            ),
        ),
    ]
