# Generated by Django 5.2.14 on 2026-07-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("combat", "0036_combatopponent_auto_lock_threshold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="combatopponent",
            name="max_morale",
            field=models.PositiveSmallIntegerField(
                default=100, help_text="Ceiling for morale; RALLY restores toward it."
            ),
        ),
        migrations.AddField(
            model_name="combatopponent",
            name="morale",
            field=models.PositiveSmallIntegerField(
                default=70,
                help_text="Depletable resolve pool (#2015). Falter/break thresholds drive select_npc_actions; mindless opponents (tier template has_morale=False) resist morale checks, not immune to them.",
            ),
        ),
        migrations.AddField(
            model_name="opponenttiertemplate",
            name="has_morale",
            field=models.BooleanField(
                default=True,
                help_text="False for mindless tiers (constructs). Adds MINDLESS_MORALE_RESISTANCE to morale checks against this opponent — not an immunity; a powerful enough roll breaks through.",
            ),
        ),
        migrations.AddField(
            model_name="threatpoolentry",
            name="requires_steady",
            field=models.BooleanField(
                default=False,
                help_text="If True, this entry is skipped when the opponent is faltering (morale_state FALTER). Lets designers author 'weakened' entries (#2015).",
            ),
        ),
        migrations.AlterField(
            model_name="combatroundaction",
            name="maneuver",
            field=models.CharField(
                blank=True,
                choices=[
                    ("flee", "Flee"),
                    ("cover", "Cover"),
                    ("yield", "Yield"),
                    ("interpose", "Interpose"),
                    ("succor", "Succor"),
                    ("engage", "Engage"),
                    ("disengage", "Disengage"),
                    ("rally", "Rally"),
                    ("demoralize", "Demoralize"),
                    ("taunt", "Taunt"),
                    ("parley", "Parley"),
                ],
                help_text="Special maneuver this declaration is (flee/cover/yield/interpose); null = normal action.",
                max_length=20,
                null=True,
            ),
        ),
    ]
