# Generated by Django 5.2.14 on 2026-07-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("combat", "0041_wall_breaker_combo"),
    ]

    operations = [
        migrations.AddField(
            model_name="comboslot",
            name="required_archetype",
            field=models.CharField(
                blank=True,
                choices=[("sword", "Sword"), ("shield", "Shield"), ("crown", "Crown")],
                default="",
                help_text="#2022: Required covenant role archetype for this slot's participant. Blank means any archetype. Lets authored combos require specific role composition (e.g. Slot 1: SWORD, Slot 2: SHIELD).",
                max_length=20,
            ),
        ),
    ]
