# Generated by Django 5.2.14 on 2026-07-09 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("combat", "0042_comboslot_required_archetype"),
        ("items", "0029_itemtemplate_flourish_text_iteminstance_custom_flourish_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="combatroundaction",
            name="item_instance",
            field=models.ForeignKey(
                blank=True,
                help_text="Item to use when maneuver == USE_ITEM.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="items.iteminstance",
            ),
        ),
        migrations.AlterField(
            model_name="combatroundaction",
            name="maneuver",
            field=models.CharField(
                blank=True,
                choices=[
                    ("flee", "Flee"),
                    ("cover", "Cover"),
                    ("yield", "Yield"),
                    ("interpose", "Interpose"),
                    ("succor", "Succor"),
                    ("engage", "Engage"),
                    ("disengage", "Disengage"),
                    ("rally", "Rally"),
                    ("demoralize", "Demoralize"),
                    ("taunt", "Taunt"),
                    ("parley", "Parley"),
                    ("use_item", "Use Item"),
                ],
                help_text="Special maneuver this declaration is (flee/cover/yield/interpose/use_item); null = normal action.",
                max_length=20,
                null=True,
            ),
        ),
    ]
