# Generated by Django 5.2.14 on 2026-07-12 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("combat", "0045_combatroundaction_from_entrance"),
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="combatroundaction",
            name="redirect_object_target",
            field=models.ForeignKey(
                blank=True,
                help_text="Declared redirect destination — a volatile object in the encounter room (#2210). ObjectDB is correct here (any object may be volatile), not a narrower model. Mutually exclusive with redirect_opponent_target; both null means 'away' (the universal fallback).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="objects.objectdb",
            ),
        ),
        migrations.AddField(
            model_name="combatroundaction",
            name="redirect_opponent_target",
            field=models.ForeignKey(
                blank=True,
                help_text="Declared redirect destination — a chosen-enemy CombatOpponent (#2210). Mutually exclusive with redirect_object_target; both null means 'away' (the universal fallback).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="combat.combatopponent",
            ),
        ),
    ]
