# Generated by Django 5.2.15 on 2026-07-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("combat", "0050_combatencounter_opened_from_parley"),
    ]

    operations = [
        migrations.AddField(
            model_name="combatopponent",
            name="affinity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("celestial", "Celestial"),
                    ("primal", "Primal"),
                    ("abyssal", "Abyssal"),
                ],
                default="",
                help_text="Authored magical affinity for non-persona NPCs (generic/ephemeral opponents carry no CharacterAura row to infer from). Blank = untyped/unauthored — the ATTACKER_ABYSSAL situational-perk evaluator (world.covenants.perks.evaluators) falls back to a reachable ObjectDB's CharacterAura.dominant_affinity when this is blank.",
                max_length=20,
            ),
        ),
    ]
