# Generated by Django 5.2.15 on 2026-07-22 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("combat", "0055_combatparticipant_insight_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="combatopponentaction",
            name="damage_scale",
            field=models.FloatField(
                default=1.0,
                help_text="Multiplier applied to threat_entry.base_damage on resolution (#2637). 1.0 (default) is today's unscaled behavior. A matured wind-up (PendingOpponentAttack) sets this from its downgrade ladder — x(1 - 0.25*downgrades), floored at x0.25 — so a wrecked telegraph lands weaker without touching the authored ThreatPoolEntry row.",
            ),
        ),
        migrations.AddField(
            model_name="combatparticipant",
            name="reactions_used",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Reactions (e.g. INTERPOSE fires) this participant has spent this round (#2639). Reset to 0 in begin_declaration_phase. Gated against combat.constants.REACTIONS_PER_ROUND at the reaction fire seam (_dispatch_interpose_action).",
            ),
        ),
        migrations.AddField(
            model_name="threatpoolentry",
            name="windup_rounds",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Rounds this attack telegraphs before it lands (#2637). 0 (default) is today's same-round behavior. > 0 creates a PendingOpponentAttack at declaration instead of a same-round CombatOpponentAction; the attack matures resolves_round rounds later, and can be interrupted/downgraded by PC hits on the opponent in the meantime.",
            ),
        ),
        migrations.AddField(
            model_name="threatpoolentry",
            name="windup_telegraph",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Telegraph text broadcast when this wind-up is declared (#2637). Blank falls back to a generic line ('The {opponent} begins something enormous...') at broadcast time.",
                max_length=300,
            ),
        ),
        migrations.CreateModel(
            name="PendingOpponentAttack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "declared_round",
                    models.PositiveIntegerField(
                        help_text="The round this wind-up was declared/telegraphed."
                    ),
                ),
                (
                    "resolves_round",
                    models.PositiveIntegerField(
                        help_text="The round this wind-up matures and resolves. Always > declared_round."
                    ),
                ),
                (
                    "called_out",
                    models.BooleanField(
                        default=False,
                        help_text="Auto-called by a flagged CovenantRole.calls_out_windups engaged member at most once per round per encounter (#2637 design 6). A called-out wind-up's interception downgrade is +2 instead of +1.",
                    ),
                ),
                (
                    "downgrades",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Interception hits landed on the winding-up opponent before maturation. >= 3 fully cancels the attack; otherwise scales its damage down.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_opponent_attacks",
                        to="combat.combatencounter",
                    ),
                ),
                (
                    "opponent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_attacks",
                        to="combat.combatopponent",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        help_text="v1 single-target. Null when the entry is room-targeting.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="combat.combatparticipant",
                    ),
                ),
                (
                    "threat_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="combat.threatpoolentry",
                    ),
                ),
            ],
            options={
                "ordering": ["resolves_round", "pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("resolves_round__gt", models.F("declared_round"))),
                        name="pendingopponentattack_resolves_after_declared",
                    )
                ],
            },
        ),
    ]
