# Generated by Django 5.2.15 on 2026-07-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("combat", "0056_combatopponentaction_damage_scale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="combatopponentaction",
            name="matured_from_called_out_windup",
            field=models.BooleanField(
                default=False,
                help_text="Stamped True at wind-up maturation (#2638) when the PendingOpponentAttack this action was synthesized from carried called_out=True (#2637 design 6). PendingOpponentAttack is deleted at maturation, so this is the only surviving record of whether the attack that lands was called out — read by a sends_flying consequence's celebration broadcast to credit the auto-caller alongside the catcher. False (the default) for every non-wind-up same-round action.",
            ),
        ),
        migrations.AddField(
            model_name="combatparticipant",
            name="sent_flying_damage",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The triggering hit's damage, stamped when a `sends_flying` ThreatPoolEntry's attack applies the Sent Flying marker condition to this participant (#2638). v1 carrier choice: rather than a new model, the amount rides this single field (only one Sent Flying marker can be active on a participant at a time — the condition is non-stackable) so world.combat.services._resolve_sent_flying_markers can compute the unanswered-impact debit (floor(sent_flying_damage * SENT_FLYING_IMPACT_FRACTION)) at end of round without threading extra state through the condition system. 0 = not currently marked; cleared back to 0 on catch or landing.",
            ),
        ),
        migrations.AddField(
            model_name="threatpoolentry",
            name="sends_flying",
            field=models.BooleanField(
                default=False,
                help_text="Big attacks that launch their victim on a damaging hit (#2638). Pairs naturally with windup_rounds — a telegraphed haymaker that connects sends the victim flying. Applies the seeded 'Sent Flying' marker condition (world.combat.sent_flying_content) whenever this entry's attack deals damage > 0; the marker is then reactable (an armed guardian INTERPOSE may catch it mid-air) or resolves explicitly at end of round — see world.combat.services._resolve_sent_flying_markers.",
            ),
        ),
    ]
