# Generated by Django 5.2.15 on 2026-07-23 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("combat", "0057_combatopponentaction_matured_from_called_out_windup_and_more"),
        ("magic", "0121_alter_techniquefunctiontag_function"),
    ]

    operations = [
        migrations.CreateModel(
            name="CombatMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.PositiveIntegerField()),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks",
                        to="combat.combatencounter",
                    ),
                ),
                (
                    "opponent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks",
                        to="combat.combatopponent",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks",
                        to="combat.combatparticipant",
                    ),
                ),
                (
                    "source_technique",
                    models.ForeignKey(
                        blank=True,
                        help_text="Technique that created the mark (provenance).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="magic.technique",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("participant", "round_number"),
                        name="combat_mark_unique_per_participant_round",
                    )
                ],
            },
        ),
    ]
