# Generated by Django 5.2.4 on 2026-05-20 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0005_missiontemplate_availability_rule_missiongiver_and_more"),
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="missiondeedrewardline",
            name="recipient",
            field=models.ForeignKey(
                default=1,
                help_text="Character whose ledger this line pays into. May differ from the parent deed's actor when the route emitted a contract_holder_only line (Phase 5b.0).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="objects.objectdb",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="MissionOptionRouteReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("post_cron", "Post Cron"),
                            ("propagation", "Propagation"),
                        ],
                        help_text="When the emitted line pays out (IMMEDIATE/POST_CRON/PROPAGATION).",
                        max_length=12,
                    ),
                ),
                (
                    "sink",
                    models.CharField(
                        choices=[
                            ("money", "Money"),
                            ("legend_points", "Legend Points"),
                            ("resonance", "Resonance"),
                            ("rumor", "Rumor"),
                            ("crime_watch", "Crime Watch"),
                            ("beat", "Beat"),
                        ],
                        help_text="Which ledger the emitted line pays into.",
                        max_length=14,
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Numeric magnitude of the broadcast reward, when applicable.",
                        null=True,
                    ),
                ),
                (
                    "ref",
                    models.CharField(
                        blank=True,
                        help_text="Optional reference/discriminator (e.g., a rumor key).",
                        max_length=200,
                    ),
                ),
                (
                    "contract_holder_only",
                    models.BooleanField(
                        default=False,
                        help_text="True → emit exactly one line to the instance's contract holder, regardless of how many participants ran the mission. False → distribute per the template's reward_group_rule.",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_templates",
                        to="missions.missionoptionroute",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
