# Generated by Django 5.2.14 on 2026-06-04 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0006_remove_missiongiveroffering_giver_and_more"),
        ("scenes", "0007_persona_is_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="missioninstance",
            name="accepted_as_persona",
            field=models.ForeignKey(
                blank=True,
                help_text="The persona the contract-holder presented when accepting this run (#686). Used by the per-(persona × role) one-in-flight gate. Null for trigger-based and legacy seed rows (which skip the gate).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="scenes.persona",
            ),
        ),
    ]
