# Generated by Django 5.2.4 on 2026-05-20 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0006_missiondeedrewardline_recipient_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MissionRewardQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("post_cron", "Post Cron"),
                            ("propagation", "Propagation"),
                        ],
                        help_text="Mirrors the line's kind so the cron filters cheaply without an extra join.",
                        max_length=12,
                    ),
                ),
                (
                    "sink",
                    models.CharField(
                        choices=[
                            ("money", "Money"),
                            ("legend_points", "Legend Points"),
                            ("resonance", "Resonance"),
                            ("rumor", "Rumor"),
                            ("crime_watch", "Crime Watch"),
                            ("beat", "Beat"),
                        ],
                        help_text="Mirrors the line's sink so the cron filters cheaply without an extra join.",
                        max_length=14,
                    ),
                ),
                ("applied", models.BooleanField(default=False)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        help_text="Populated when applied=True but the cron's sink call raised; cron telemetry — not used in Phase 5b.1.",
                        max_length=500,
                    ),
                ),
                (
                    "deed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queued_rewards",
                        to="missions.missiondeedrecord",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        help_text="The emitted reward line this queue row routes. Exactly one queue row per line — see UniqueConstraint below.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="missions.missiondeedrewardline",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("line",), name="unique_missionrewardqueue_line")
                ],
            },
        ),
    ]
