# Generated by Django 5.2.4 on 2026-05-20 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0007_missionrewardqueue"),
        ("stories", "0031_story_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="missioninstance",
            name="source_beat",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: the stories Beat that launched this run. SET_NULL on Beat delete. Engine that flips the Beat at terminal is deferred to a future stories-missions seam design pass (5b.3 stub-records the trigger only).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="stories.beat",
            ),
        ),
    ]
