# Generated by Django 5.2.14 on 2026-05-22 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mechanics", "0003_challengeapproach_is_default"),
        ("missions", "0009_missionnode_attached_challenges"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="missionnode",
            name="attached_challenges",
        ),
        migrations.AddField(
            model_name="missionoption",
            name="challenge",
            field=models.ForeignKey(
                blank=True,
                help_text="CHALLENGE source: the challenge whose approaches fan out into this option's challenge-contributed options at runtime.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="mechanics.challengetemplate",
            ),
        ),
        migrations.AlterField(
            model_name="missionoption",
            name="source_kind",
            field=models.CharField(
                choices=[
                    ("affordance", "Affordance"),
                    ("authored", "Authored"),
                    ("challenge", "Challenge"),
                ],
                max_length=10,
            ),
        ),
    ]
