# Generated by Django 5.2.14 on 2026-05-22 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("checks", "0006_consequenceeffect_legend_base_value_and_more"),
        ("mechanics", "0003_challengeapproach_is_default"),
        ("missions", "0011_remove_missionoption_accepted_affordances_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missionnode",
            name="allowed_riders",
            field=models.ManyToManyField(
                blank=True,
                help_text="Reusable consequence riders permitted at this node. NOT consumed by the engine in Phase A; reserved for future use.",
                related_name="+",
                to="checks.consequence",
            ),
        ),
        migrations.AlterField(
            model_name="missionnode",
            name="deny_all_riders",
            field=models.BooleanField(
                default=False,
                help_text="When true, no consequence riders may attach at this node. NOT consumed by the engine in Phase A; reserved for future use.",
            ),
        ),
        migrations.AlterField(
            model_name="missionoption",
            name="challenge",
            field=models.ForeignKey(
                blank=True,
                help_text="CHALLENGE source: the challenge whose approaches fan out into this option's challenge-contributed options at runtime. on_delete=PROTECT — detach all referencing options before deleting the challenge.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="mechanics.challengetemplate",
            ),
        ),
    ]
