# Generated by Django 5.2.14 on 2026-05-23 02:00

from django.db import migrations, models

import core.natural_keys


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0012_alter_missionnode_allowed_riders_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MissionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Mission categories",
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.AddField(
            model_name="missiontemplate",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Content-type tags for this mission (multi-valued, e.g. assassination, courtly, heist). Drives browse/filter in the authoring tool.",
                related_name="templates",
                to="missions.missioncategory",
            ),
        ),
    ]
