# Generated by Django 5.2.14 on 2026-07-01 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0019_missiondeedrewardline_resonance"),
        ("npc_services", "0006_functionary"),
    ]

    operations = [
        migrations.AddField(
            model_name="missioninstance",
            name="report_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("humble", "Humble"),
                    ("accurate", "Accurate"),
                    ("mostly_accurate", "Mostly accurate"),
                    ("embellished", "Embellished"),
                ],
                default="",
                help_text="How the player reported this run's outcome (#1753). Blank until reported.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="missioninstance",
            name="reported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="missiontemplate",
            name="report_to_role",
            field=models.ForeignKey(
                blank=True,
                help_text="The NPC role a player reports this mission's outcome to (#1753) — a Functionary of this role, possibly different from the giver (e.g. a guildmaster). Null → report to the giver's role (source_offer.role); if there is no NPC giver either, the mission ends at resolution (legend spreads, no monetary reward).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="missions_reported_to",
                to="npc_services.npcrole",
            ),
        ),
        migrations.AlterField(
            model_name="missioninstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("resolved", "Resolved (awaiting report)"),
                    ("complete", "Complete"),
                    ("abandoned", "Abandoned"),
                    ("expired", "Expired"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
