# Generated by Django 5.2.14 on 2026-05-24 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0021_missiontemplate_access_tier"),
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="missiongiver",
            name="environmental_detail",
        ),
        migrations.RemoveField(
            model_name="missiongiver",
            name="location",
        ),
        migrations.RemoveField(
            model_name="missiongiver",
            name="npc",
        ),
        migrations.AddField(
            model_name="missiongiver",
            name="target",
            field=models.ForeignKey(
                blank=True,
                help_text="The Evennia object this giver is bound to. Its typeclass must match giver_kind: NPC → Character-typeclass; ROOM_TRIGGER → Room-typeclass; ENVIRONMENTAL_DETAIL → any non-Character/Room/Exit Object (an examinable item or room detail). Null = draft (see is_publishable). All FK targets land in ObjectDB; the kind enum + clean() typeclass check enforce semantic shape without the wasted nullable columns of a discriminator.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="objects.objectdb",
            ),
        ),
        migrations.AlterField(
            model_name="missiongiver",
            name="giver_kind",
            field=models.CharField(
                choices=[
                    ("npc", "NPC"),
                    ("environmental_detail", "Environmental Detail"),
                    ("room_trigger", "Room Trigger"),
                ],
                default="room_trigger",
                help_text="How this giver reaches the player; selects the target's expected typeclass.",
                max_length=20,
            ),
        ),
    ]
