# Generated by Django 5.2.14 on 2026-07-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0024_missioninvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="missioninstance",
            name="is_paused",
            field=models.BooleanField(
                default=False,
                help_text="Set when a participant disconnects (#1899) — see maybe_pause_mission_for_disconnect.",
            ),
        ),
    ]
