# Generated by Django 5.2.14 on 2026-07-08 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0026_add_board_giver_kind"),
        ("npc_services", "0015_npcstanding_consecutive_refused_summons_offersummons"),
    ]

    operations = [
        migrations.AddField(
            model_name="missiondeedrewardline",
            name="followon_expiry_hours",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Mirrors the template's followon_expiry_hours.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="missiondeedrewardline",
            name="followon_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Mirrors the template's followon_message.",
            ),
        ),
        migrations.AddField(
            model_name="missiondeedrewardline",
            name="followon_offer",
            field=models.ForeignKey(
                blank=True,
                help_text="Mirrors the template's followon_offer (set when sink=FOLLOW_ON_SUMMONS).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="npc_services.npcserviceoffer",
            ),
        ),
        migrations.AddField(
            model_name="missionoptionroutereward",
            name="followon_expiry_hours",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="When sink=FOLLOW_ON_SUMMONS: the summons lapses after this many hours if unanswered (triggering the refusal/escalation path). Null = no expiry (the summons persists until accepted or declined).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="missionoptionroutereward",
            name="followon_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="IC text for the follow-on summons when sink=FOLLOW_ON_SUMMONS. Empty = the summons shows the offer's default text.",
            ),
        ),
        migrations.AddField(
            model_name="missionoptionroutereward",
            name="followon_offer",
            field=models.ForeignKey(
                blank=True,
                help_text="Required when sink=FOLLOW_ON_SUMMONS: the MISSION-kind offer whose summons fires as the follow-on reward.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="npc_services.npcserviceoffer",
            ),
        ),
        migrations.AlterField(
            model_name="missiondeedrewardline",
            name="sink",
            field=models.CharField(
                choices=[
                    ("money", "Money"),
                    ("legend_points", "Legend Points"),
                    ("resonance", "Resonance"),
                    ("rumor", "Rumor"),
                    ("crime_watch", "Crime Watch"),
                    ("beat", "Beat"),
                    ("item", "Item"),
                    ("summons", "Follow-On Summons"),
                ],
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="missionoptionroutereward",
            name="sink",
            field=models.CharField(
                choices=[
                    ("money", "Money"),
                    ("legend_points", "Legend Points"),
                    ("resonance", "Resonance"),
                    ("rumor", "Rumor"),
                    ("crime_watch", "Crime Watch"),
                    ("beat", "Beat"),
                    ("item", "Item"),
                    ("summons", "Follow-On Summons"),
                ],
                help_text="Which ledger the emitted line pays into.",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="missionrewardqueue",
            name="sink",
            field=models.CharField(
                choices=[
                    ("money", "Money"),
                    ("legend_points", "Legend Points"),
                    ("resonance", "Resonance"),
                    ("rumor", "Rumor"),
                    ("crime_watch", "Crime Watch"),
                    ("beat", "Beat"),
                    ("item", "Item"),
                    ("summons", "Follow-On Summons"),
                ],
                help_text="Mirrors the line's sink so the cron filters cheaply without an extra join.",
                max_length=14,
            ),
        ),
    ]
