# Generated by Django 5.2.14 on 2026-07-10 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("areas", "0015_add_obstacle_lifecycle_fields"),
        ("missions", "0031_support_moves"),
    ]

    operations = [
        migrations.AddField(
            model_name="missionnode",
            name="target_area",
            field=models.ForeignKey(
                blank=True,
                help_text="Target area for AREA location_mode. A room matches when its RoomProfile.area is this area or any descendant via AreaClosure.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="areas.area",
            ),
        ),
        migrations.AlterField(
            model_name="missionnode",
            name="location_mode",
            field=models.CharField(
                choices=[
                    ("anywhere", "Anywhere"),
                    ("anchor", "Anchor Room"),
                    ("rooms", "Authored Rooms"),
                    ("instance", "Spawned Instance"),
                    ("area", "Target Area"),
                ],
                default="anywhere",
                help_text="Default location gate for this node's options (#885): ANYWHERE = live wherever the character is; ANCHOR = live only in the instance's grant-time anchor room; ROOMS = live in this node's authored ``locations`` set. An option with its own ``locations`` rows overrides this default.",
                max_length=10,
            ),
        ),
    ]
