# Generated by Django 5.2.14 on 2026-07-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0031_support_moves"),
    ]

    operations = [
        migrations.AddField(
            model_name="missionoption",
            name="required_act",
            field=models.CharField(
                blank=True,
                choices=[
                    ("technique_cast", "Technique Cast"),
                    ("thread_woven", "Thread Woven"),
                    ("covenant_sworn", "Covenant Sworn"),
                ],
                default="",
                help_text="EXTERNAL_ACT options only: the non-mission act (cast/weave/covenant) that resolves this option (#1035). Blank for BRANCH/CHECK options.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="missionoption",
            name="option_kind",
            field=models.CharField(
                choices=[
                    ("branch", "Branch"),
                    ("check", "Check"),
                    ("external_act", "External Act"),
                ],
                max_length=12,
            ),
        ),
    ]
