# Generated by Django 5.2.14 on 2026-07-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Secret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Uncommon Knowledge"),
                            (2, "Whispers"),
                            (3, "Carefully Kept"),
                            (4, "Dangerous Secret"),
                        ],
                        default=1,
                        help_text="How deep/dangerous — narrative weight + default share-scope.",
                    ),
                ),
                (
                    "consequences",
                    models.TextField(
                        blank=True,
                        help_text="What happens if it surfaces. Blank = Unknown.",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="The secret itself, as narrated. Player- or GM-authored prose.",
                    ),
                ),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("gm", "GM/Staff authored (canon)"),
                            ("action", "Action-anchored (minted by play)"),
                            ("flavor", "Player flavor (unverified)"),
                        ],
                        help_text="Where the secret came from (drives the anchor rule + OOC attribution).",
                        max_length=10,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="SecretCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category label (player-visible).",
                        max_length=60,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Staff note on what belongs here."),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Offer this category to authors."),
                ),
            ],
            options={
                "verbose_name": "Secret category",
                "verbose_name_plural": "Secret categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SecretGossip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heat",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Spread heat: ≥1 findable, decays toward the floor, public at the threshold.",
                    ),
                ),
                (
                    "went_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether heat crossed the public threshold (one-shot: ambient + exposure).",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Secret gossip",
                "verbose_name_plural": "Secret gossip",
            },
        ),
        migrations.CreateModel(
            name="SecretGrievance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SecretKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "knows_category",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this knower has placed the secret's category (else it reads Unknown).",
                    ),
                ),
                (
                    "knows_consequences",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this knower has learned the secret's consequences.",
                    ),
                ),
                ("found_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Secret knowledge",
                "verbose_name_plural": "Secret knowledge",
                "ordering": ["-found_at"],
            },
        ),
        migrations.CreateModel(
            name="SecretVictim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional magnitude of the direct standing hit. Null = derive from secret level.",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
