# Generated by Django 5.2.14 on 2026-07-03 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("areas", "0003_initial"),
        ("character_sheets", "0002_initial"),
        ("missions", "0002_initial"),
        ("relationships", "0002_initial"),
        ("roster", "0001_initial"),
        ("scenes", "0003_initial"),
        ("secrets", "0001_initial"),
        ("societies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="secret",
            name="archetypes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Moral framings that drive the diffuse per-society reputation hit on reveal.",
                related_name="secrets",
                to="societies.philosophicalarchetype",
            ),
        ),
        migrations.AddField(
            model_name="secret",
            name="author_persona",
            field=models.ForeignKey(
                blank=True,
                help_text="The narrating persona (player-authored). Null for GM/staff-authored.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authored_secrets",
                to="scenes.persona",
            ),
        ),
        migrations.AddField(
            model_name="secret",
            name="legend_deed",
            field=models.ForeignKey(
                blank=True,
                help_text="The public legend telling of the act this secret is the truth behind (#1573).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="explaining_secrets",
                to="societies.legendentry",
            ),
        ),
        migrations.AddField(
            model_name="secret",
            name="mission_deed",
            field=models.ForeignKey(
                blank=True,
                help_text="The recorded mission act this secret is the truth behind (#1573).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="explaining_secrets",
                to="missions.missiondeedrecord",
            ),
        ),
        migrations.AddField(
            model_name="secret",
            name="scene",
            field=models.ForeignKey(
                blank=True,
                help_text="Scene the act happened in — freeform/blackmail context (#1573).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="explaining_secrets",
                to="scenes.scene",
            ),
        ),
        migrations.AddField(
            model_name="secret",
            name="societies_exposed",
            field=models.ManyToManyField(
                blank=True,
                help_text="Societies already exposed to this secret (so reveal fires once per society).",
                related_name="exposed_secrets",
                to="societies.society",
            ),
        ),
        migrations.AddField(
            model_name="secret",
            name="subject_sheet",
            field=models.ForeignKey(
                help_text="The character this secret is about — and its sole owner.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secrets",
                to="character_sheets.charactersheet",
            ),
        ),
        migrations.AddField(
            model_name="secret",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="What the secret is about. Null = Unknown (not yet placed).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="secrets",
                to="secrets.secretcategory",
            ),
        ),
        migrations.AddField(
            model_name="secretgossip",
            name="region",
            field=models.ForeignKey(
                help_text="The region (Area at AreaLevel.REGION) this heat is scoped to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gossip_heat",
                to="areas.area",
            ),
        ),
        migrations.AddField(
            model_name="secretgossip",
            name="secret",
            field=models.ForeignKey(
                help_text="The Level-1 secret being gossiped.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gossip_heat",
                to="secrets.secret",
            ),
        ),
        migrations.AddField(
            model_name="secretgrievance",
            name="capstone",
            field=models.ForeignKey(
                blank=True,
                help_text="The relationship capstone this grievance applied.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="relationships.relationshipcapstone",
            ),
        ),
        migrations.AddField(
            model_name="secretgrievance",
            name="secret",
            field=models.ForeignKey(
                help_text="The secret that was answered.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grievances",
                to="secrets.secret",
            ),
        ),
        migrations.AddField(
            model_name="secretgrievance",
            name="victim_sheet",
            field=models.ForeignKey(
                help_text="The wronged character who answered it.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secret_grievances",
                to="character_sheets.charactersheet",
            ),
        ),
        migrations.AddField(
            model_name="secretknowledge",
            name="roster_entry",
            field=models.ForeignKey(
                help_text="The character who holds this knowledge.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secrets_known",
                to="roster.rosterentry",
            ),
        ),
        migrations.AddField(
            model_name="secretknowledge",
            name="secret",
            field=models.ForeignKey(
                help_text="The secret this character knows.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="known_by",
                to="secrets.secret",
            ),
        ),
        migrations.AddField(
            model_name="secretvictim",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The victim organization (collective victim).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secret_victimhoods",
                to="societies.organization",
            ),
        ),
        migrations.AddField(
            model_name="secretvictim",
            name="persona",
            field=models.ForeignKey(
                blank=True,
                help_text="The victim persona (individual victim).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secret_victimhoods",
                to="scenes.persona",
            ),
        ),
        migrations.AddField(
            model_name="secretvictim",
            name="secret",
            field=models.ForeignKey(
                help_text="The secret whose underlying fact harmed this entity.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="victims",
                to="secrets.secret",
            ),
        ),
        migrations.AddIndex(
            model_name="secret",
            index=models.Index(
                fields=["subject_sheet", "level"], name="secrets_sec_subject_c6586f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="secretgossip",
            index=models.Index(fields=["region", "heat"], name="secrets_sec_region__d29033_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="secretgossip",
            unique_together={("secret", "region")},
        ),
        migrations.AddConstraint(
            model_name="secretgrievance",
            constraint=models.UniqueConstraint(
                fields=("secret", "victim_sheet"),
                name="one_grievance_per_secret_victim",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="secretknowledge",
            unique_together={("roster_entry", "secret")},
        ),
        migrations.AddConstraint(
            model_name="secretvictim",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("organization__isnull", False), ("persona__isnull", True)),
                    models.Q(("organization__isnull", True), ("persona__isnull", False)),
                    _connector="OR",
                ),
                name="secret_victim_exactly_one_target",
            ),
        ),
    ]
