# Generated by Django 5.2.14 on 2026-06-21 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("roster", "0003_remove_rosterentry_frozen"),
        ("secrets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecretKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "knows_category",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this knower has placed the secret's category (else it reads Unknown).",
                    ),
                ),
                (
                    "knows_consequences",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this knower has learned the secret's consequences.",
                    ),
                ),
                ("found_at", models.DateTimeField(auto_now_add=True)),
                (
                    "roster_entry",
                    models.ForeignKey(
                        help_text="The character who holds this knowledge.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secrets_known",
                        to="roster.rosterentry",
                    ),
                ),
                (
                    "secret",
                    models.ForeignKey(
                        help_text="The secret this character knows.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="known_by",
                        to="secrets.secret",
                    ),
                ),
            ],
            options={
                "verbose_name": "Secret knowledge",
                "verbose_name_plural": "Secret knowledge",
                "ordering": ["-found_at"],
                "unique_together": {("roster_entry", "secret")},
            },
        ),
    ]
