# Generated by Django 5.2.14 on 2026-06-23 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("character_sheets", "0010_remove_charactersheet_family_and_more"),
        ("relationships", "0004_grievanceoption"),
        ("secrets", "0004_secret_archetypes_secret_societies_exposed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecretGrievance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "capstone",
                    models.ForeignKey(
                        blank=True,
                        help_text="The relationship capstone this grievance applied.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="relationships.relationshipcapstone",
                    ),
                ),
                (
                    "secret",
                    models.ForeignKey(
                        help_text="The secret that was answered.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grievances",
                        to="secrets.secret",
                    ),
                ),
                (
                    "victim_sheet",
                    models.ForeignKey(
                        help_text="The wronged character who answered it.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secret_grievances",
                        to="character_sheets.charactersheet",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("secret", "victim_sheet"),
                        name="one_grievance_per_secret_victim",
                    )
                ],
            },
        ),
    ]
