# Generated by Django 5.2.14 on 2026-06-30 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("areas", "0011_area_climate"),
        ("secrets", "0006_secret_legend_deed_secret_mission_deed_secret_scene"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecretGossip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heat",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Spread heat: ≥1 findable, decays toward the floor, public at the threshold.",
                    ),
                ),
                (
                    "went_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether heat crossed the public threshold (one-shot: ambient + exposure).",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    models.ForeignKey(
                        help_text="The region (Area at AreaLevel.REGION) this heat is scoped to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gossip_heat",
                        to="areas.area",
                    ),
                ),
                (
                    "secret",
                    models.ForeignKey(
                        help_text="The Level-1 secret being gossiped.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gossip_heat",
                        to="secrets.secret",
                    ),
                ),
            ],
            options={
                "verbose_name": "Secret gossip",
                "verbose_name_plural": "Secret gossip",
                "indexes": [
                    models.Index(fields=["region", "heat"], name="secrets_sec_region__d29033_idx")
                ],
                "unique_together": {("secret", "region")},
            },
        ),
    ]
