# Generated by Django 5.2.4 on 2026-03-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
        ("scenes", "0010_scene_event"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="eventhost",
            name="unique_event_host",
        ),
        migrations.AddConstraint(
            model_name="eventhost",
            constraint=models.UniqueConstraint(
                condition=models.Q(("persona__isnull", False)),
                fields=("event", "persona"),
                name="unique_event_host",
            ),
        ),
    ]
