# Generated by Django 5.2.14 on 2026-06-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_event_host_society"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventinvitation",
            name="responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventinvitation",
            name="response",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
            ),
        ),
    ]
