# Generated by Django 5.2.4 on 2026-04-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0002_story_primary_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Era",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.SlugField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=200)),
                (
                    "season_number",
                    models.PositiveIntegerField(help_text="Player-facing 'Season N' number."),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("active", "Active"),
                            ("concluded", "Concluded"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("concluded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("status",),
                        name="only_one_active_era",
                    )
                ],
            },
        ),
    ]
