# Generated by Django 5.2.4 on 2026-04-21 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0004_story_character_sheet_story_created_in_era_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episode",
            name="connection_summary",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="connection_to_next",
        ),
        migrations.RemoveField(
            model_name="episodescene",
            name="connection_summary",
        ),
        migrations.RemoveField(
            model_name="episodescene",
            name="connection_to_next",
        ),
    ]
