# Generated by Django 5.2.14 on 2026-07-02 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0011_actiontemplate_difficulty_tier_modifier"),
        ("character_sheets", "0010_remove_charactersheet_family_and_more"),
        ("items", "0022_garmentmitigation"),
        ("societies", "0018_organization_membership_lifecycle"),
        ("stories", "0005_alter_beat_predicate_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskCalibration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("extreme", "Extreme"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("severity_floor_total", models.PositiveSmallIntegerField()),
                (
                    "severity_ceiling",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Setback"),
                            (2, "Costly"),
                            (3, "Grave"),
                            (4, "Dire"),
                            (5, "Removal from play"),
                        ]
                    ),
                ),
                ("max_fuse_hops", models.PositiveSmallIntegerField()),
                ("reward_floor", models.PositiveIntegerField(default=0)),
                ("reward_ceiling", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["risk"],
            },
        ),
        migrations.CreateModel(
            name="StakeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "subject_kind",
                    models.CharField(
                        choices=[
                            ("personal_jeopardy", "Personal jeopardy"),
                            ("npc_fate", "NPC fate"),
                            ("location", "Location"),
                            ("faction", "Faction relationship"),
                            ("item", "Item"),
                            ("campaign_track", "Campaign track"),
                            ("custom", "Custom (trust-gated)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Setback"),
                            (2, "Costly"),
                            (3, "Grave"),
                            (4, "Dire"),
                            (5, "Removal from play"),
                        ]
                    ),
                ),
                (
                    "min_risk",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("extreme", "Extreme"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                (
                    "max_risk",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("extreme", "Extreme"),
                        ],
                        default="extreme",
                        max_length=10,
                    ),
                ),
                (
                    "player_summary_template",
                    models.TextField(
                        help_text="Player-facing summary shown at opt-in; GM fills the specifics."
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["subject_kind", "severity", "name"],
            },
        ),
        migrations.AddField(
            model_name="beat",
            name="target_level",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The character level this beat's stakes are declared against ('EXTREME at level 4'). Effective risk at activation is computed from the gap between this and the actual party's average level. Required (via readiness validation, not clean()) when risk != NONE.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Stake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_kind",
                    models.CharField(
                        choices=[
                            ("personal_jeopardy", "Personal jeopardy"),
                            ("npc_fate", "NPC fate"),
                            ("location", "Location"),
                            ("faction", "Faction relationship"),
                            ("item", "Item"),
                            ("campaign_track", "Campaign track"),
                            ("custom", "Custom (trust-gated)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Setback"),
                            (2, "Costly"),
                            (3, "Grave"),
                            (4, "Dire"),
                            (5, "Removal from play"),
                        ]
                    ),
                ),
                (
                    "subject_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Freeform subject name (CUSTOM / CAMPAIGN_TRACK, or flavor).",
                        max_length=200,
                    ),
                ),
                (
                    "player_summary",
                    models.TextField(
                        help_text="Player-facing line shown at opt-in: what is wagered, how badly."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "beat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stakes",
                        to="stories.beat",
                    ),
                ),
                (
                    "subject_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="For ITEM subjects.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="items.iteminstance",
                    ),
                ),
                (
                    "subject_organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="For FACTION subjects (organization-level).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="societies.organization",
                    ),
                ),
                (
                    "subject_sheet",
                    models.ForeignKey(
                        blank=True,
                        help_text="For NPC_FATE / PERSONAL_JEOPARDY subjects.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="character_sheets.charactersheet",
                    ),
                ),
                (
                    "subject_society",
                    models.ForeignKey(
                        blank=True,
                        help_text="For FACTION subjects (society-level).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="societies.society",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null only for trust-gated custom stakes.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stakes",
                        to="stories.staketemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["beat", "-severity", "pk"],
            },
        ),
        migrations.CreateModel(
            name="StakeContractActivation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locked_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("party_average_level", models.PositiveIntegerField()),
                (
                    "declared_target_level",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Beat.target_level snapshot at activation (0 = unset).",
                    ),
                ),
                (
                    "declared_risk",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("extreme", "Extreme"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "effective_risk",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("extreme", "Extreme"),
                        ],
                        help_text="What Legend actually pays on — see compute_effective_risk.",
                        max_length=10,
                    ),
                ),
                (
                    "is_ready",
                    models.BooleanField(
                        help_text="Readiness verdict at activation; False forced effective NONE."
                    ),
                ),
                ("readiness_notes", models.TextField(blank=True, default="")),
                (
                    "beat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stake_activations",
                        to="stories.beat",
                    ),
                ),
            ],
            options={
                "ordering": ["-locked_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("resolved_at__isnull", True)),
                        fields=("beat",),
                        name="unique_open_activation_per_beat",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StakeResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "column",
                    models.CharField(
                        choices=[
                            ("win", "Win"),
                            ("loss", "Loss"),
                            ("withdrawal", "Withdrawal"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "escalates_to_risk",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("extreme", "Extreme"),
                        ],
                        default="",
                        help_text="The risk tier the situation spawned by this branch carries — the fuse mechanic. Blank = no escalation declared.",
                        max_length=10,
                    ),
                ),
                (
                    "narrative_summary",
                    models.TextField(
                        blank=True,
                        help_text="What happens in the story when this branch fires (GM-authored).",
                    ),
                ),
                (
                    "consequence_pool",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pool to fire when this column resolves (tier-aware).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="actions.consequencepool",
                    ),
                ),
                (
                    "stake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolutions",
                        to="stories.stake",
                    ),
                ),
            ],
            options={
                "ordering": ["stake", "column"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("stake", "column"),
                        name="unique_resolution_per_stake_column",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="stake",
            index=models.Index(fields=["beat"], name="stories_sta_beat_id_9ba3eb_idx"),
        ),
    ]
