# Generated by Django 5.2.4 on 2026-04-21 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0007_beat"),
    ]

    operations = [
        migrations.CreateModel(
            name="EpisodeProgressionRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "required_outcome",
                    models.CharField(
                        choices=[
                            ("unsatisfied", "Unsatisfied"),
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("expired", "Expired"),
                            ("pending_gm_review", "Pending GM review"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                (
                    "beat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gating_for_episodes",
                        to="stories.beat",
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progression_requirements",
                        to="stories.episode",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("episode", "beat"),
                        name="unique_progression_req_per_episode_beat",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TransitionRequiredOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "required_outcome",
                    models.CharField(
                        choices=[
                            ("unsatisfied", "Unsatisfied"),
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("expired", "Expired"),
                            ("pending_gm_review", "Pending GM review"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "beat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routing_for_transitions",
                        to="stories.beat",
                    ),
                ),
                (
                    "transition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_outcomes",
                        to="stories.transition",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("transition", "beat"),
                        name="unique_routing_req_per_transition_beat",
                    )
                ],
            },
        ),
    ]
