# Generated by Django 5.2.4 on 2026-04-21 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("character_sheets", "0003_initial"),
        ("roster", "0001_initial"),
        ("stories", "0008_episodeprogressionrequirement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeatCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("unsatisfied", "Unsatisfied"),
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("expired", "Expired"),
                            ("pending_gm_review", "Pending GM review"),
                        ],
                        max_length=20,
                    ),
                ),
                ("gm_notes", models.TextField(blank=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "beat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="stories.beat",
                    ),
                ),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beat_completions",
                        to="character_sheets.charactersheet",
                    ),
                ),
                (
                    "era",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="beat_completions",
                        to="stories.era",
                    ),
                ),
                (
                    "roster_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which roster tenure (which player) was active when this beat completed. For audit only.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="roster.rosterentry",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["beat", "character_sheet"],
                        name="stories_bea_beat_id_b87d2d_idx",
                    ),
                    models.Index(
                        fields=["character_sheet", "-recorded_at"],
                        name="stories_bea_charact_f2981a_idx",
                    ),
                ],
            },
        ),
    ]
