# Generated by Django 5.2.4 on 2026-04-21 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("character_sheets", "0003_initial"),
        ("gm", "0003_gmrosterinvite"),
        ("stories", "0009_beatcompletion"),
    ]

    operations = [
        migrations.CreateModel(
            name="EpisodeResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gm_notes", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episode_resolutions",
                        to="character_sheets.charactersheet",
                    ),
                ),
                (
                    "chosen_transition",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null when the episode resolves with no transition (frontier pause).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolutions_using",
                        to="stories.transition",
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolutions",
                        to="stories.episode",
                    ),
                ),
                (
                    "era",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stories.era",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="episode_resolutions",
                        to="gm.gmprofile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["episode", "-resolved_at"],
                        name="stories_epi_episode_c6f3c7_idx",
                    ),
                    models.Index(
                        fields=["character_sheet", "-resolved_at"],
                        name="stories_epi_charact_69c6c1_idx",
                    ),
                ],
            },
        ),
    ]
