# Generated by Django 5.2.14 on 2026-07-04 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gm", "0003_initial"),
        ("stories", "0013_beat_required_organization_beat_required_society_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalstoryprogress",
            name="resolved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When a FORECLOSED thread was wrapped up by staff; null = not yet wrapped up. FORECLOSED stays the honest terminal status; a non-null resolved_at marks the closure process layered on top.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="globalstoryprogress",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="GMProfile that wrapped up this foreclosed thread.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="global_progress_resolved",
                to="gm.gmprofile",
            ),
        ),
        migrations.AddField(
            model_name="groupstoryprogress",
            name="resolved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When a FORECLOSED thread was wrapped up by staff; null = not yet wrapped up. FORECLOSED stays the honest terminal status; a non-null resolved_at marks the closure process layered on top.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="groupstoryprogress",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="GMProfile that wrapped up this foreclosed thread.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="group_progress_resolved",
                to="gm.gmprofile",
            ),
        ),
        migrations.AddField(
            model_name="storyprogress",
            name="resolved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When a FORECLOSED thread was wrapped up by staff; null = not yet wrapped up. FORECLOSED stays the honest terminal status; a non-null resolved_at marks the closure process layered on top.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storyprogress",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="GMProfile that wrapped up this foreclosed thread.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="character_progress_resolved",
                to="gm.gmprofile",
            ),
        ),
    ]
