# Generated by Django 5.2.4 on 2026-04-22 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("conditions", "0002_initial"),
        ("stories", "0017_add_achievement_held_beat_predicate"),
    ]

    operations = [
        migrations.AddField(
            model_name="beat",
            name="required_condition_template",
            field=models.ForeignKey(
                blank=True,
                help_text="For CONDITION_HELD predicates.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="conditions.conditiontemplate",
            ),
        ),
    ]
