# Generated by Django 5.2.4 on 2026-04-23 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("codex", "0003_create_subjectbreadcrumb_view"),
        ("stories", "0018_add_condition_held_beat_predicate"),
    ]

    operations = [
        migrations.AddField(
            model_name="beat",
            name="required_codex_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="For CODEX_ENTRY_UNLOCKED predicates.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="codex.codexentry",
            ),
        ),
    ]
