# Generated by Django 5.2.4 on 2026-04-23 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gm", "0003_gmrosterinvite"),
        ("stories", "0021_beat_required_points_aggregatebeatcontribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="beat",
            name="agm_eligible",
            field=models.BooleanField(
                default=False,
                help_text="Lead GM may flag this beat to be claimable by Assistant GMs.",
            ),
        ),
        migrations.CreateModel(
            name="AssistantGMClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                (
                    "rejection_note",
                    models.TextField(blank=True, help_text="Reason for rejection (shown to AGM)."),
                ),
                (
                    "framing_note",
                    models.TextField(
                        blank=True,
                        help_text="Lead GM's one-paragraph framing for the AGM session. Sets the scene without exposing the rest of the story.",
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Lead GM or Staff member who approved/rejected.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_claims_approved",
                        to="gm.gmprofile",
                    ),
                ),
                (
                    "assistant_gm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_claims_made",
                        to="gm.gmprofile",
                    ),
                ),
                (
                    "beat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_claims",
                        to="stories.beat",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "requested_at"],
                        name="stories_ass_status_b2c6f5_idx",
                    ),
                    models.Index(fields=["beat", "status"], name="stories_ass_beat_id_081c3e_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["requested", "approved"])),
                        fields=("beat", "assistant_gm"),
                        name="unique_active_claim_per_beat_per_agm",
                    )
                ],
            },
        ),
    ]
