# Generated by Django 5.2.14 on 2026-07-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0024_alter_beat_referenced_chapter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stakeresolution",
            name="npc_regard_delta",
            field=models.SmallIntegerField(
                default=0,
                help_text="Pre-authored NpcRegard delta applied on resolution, when stake.subject_kind is NPC_FATE (#2039). Fires via record_npc_regard_event, citing this row.",
            ),
        ),
    ]
