# Generated by Django 5.2.4 on 2026-04-27 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gm", "0003_gmrosterinvite"),
        ("stories", "0024_beatcompletion_gm_table_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryGMOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, help_text="Optional note from offerer."),
                ),
                (
                    "response_note",
                    models.TextField(blank=True, help_text="Optional GM response."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "offered_by_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_offers_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offered_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_offers_received",
                        to="gm.gmprofile",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gm_offers",
                        to="stories.story",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["offered_to", "status"],
                        name="stories_sto_offered_86a1a4_idx",
                    ),
                    models.Index(
                        fields=["story", "status"],
                        name="stories_sto_story_i_f8f68d_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("story", "offered_to"),
                        name="unique_pending_offer_per_story_per_gm",
                    )
                ],
            },
        ),
    ]
