# Generated by Django 5.2.4 on 2026-05-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0030_beat_advances_beat_kind_beat_risk_chapter_maturity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="Player-facing 'The Story So Far' — GM-maintained running recap of what has happened and what may lie ahead. Surfaced to players via the role-gated story log, maturity-gated. NOT auto-generated.",
            ),
        ),
    ]
