# Generated by Django 5.2.4 on 2026-05-20 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0008_missioninstance_source_beat"),
        ("stories", "0031_story_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="beat",
            name="required_mission",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: a MissionTemplate this beat requires (Phase 5b.3 data shape only; engine deferred). SET_NULL on template delete.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="missions.missiontemplate",
            ),
        ),
    ]
