# Generated by Django 5.2.4 on 2026-05-10 02:20

from django.db import migrations, models
import django.db.models.deletion

import core.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("areas", "0002_create_areaclosure_view"),
        ("evennia_extensions", "0002_roomprofile_is_outdoor"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationStatOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent_type",
                    models.CharField(
                        choices=[("area", "Area"), ("room", "Room")],
                        help_text="Selects which FK (area or room_profile) is active.",
                        max_length=10,
                    ),
                ),
                (
                    "stat_key",
                    models.CharField(
                        choices=[
                            ("crime", "Crime"),
                            ("order", "Order"),
                            ("cleanliness", "Cleanliness"),
                            ("lighting", "Lighting"),
                            ("noise", "Noise"),
                            ("traffic", "Traffic"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        help_text="The absolute value asserted at this level. Final read clamps to STAT_CLAMPS."
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stat_overrides",
                        to="areas.area",
                    ),
                ),
                (
                    "room_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stat_overrides",
                        to="evennia_extensions.roomprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location Stat Override",
                "verbose_name_plural": "Location Stat Overrides",
                "indexes": [
                    models.Index(
                        fields=["area", "stat_key"],
                        name="locations_l_area_id_30b3cc_idx",
                    ),
                    models.Index(
                        fields=["room_profile", "stat_key"],
                        name="locations_l_room_pr_8002e5_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("area__isnull", False)),
                        fields=("area", "stat_key"),
                        name="unique_override_per_area_stat",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("room_profile__isnull", False)),
                        fields=("room_profile", "stat_key"),
                        name="unique_override_per_room_stat",
                    ),
                ],
            },
            bases=(core.mixins.DiscriminatorMixin, models.Model),
        ),
    ]
