# Generated by Django 5.2.4 on 2026-05-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "locations",
            "0006_rename_locationstatoverride_locationvalueoverride_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="locationvaluemodifier",
            new_name="locations_l_area_id_fa22ea_idx",
            old_name="locations_l_area_id_6f9438_idx",
        ),
        migrations.RenameIndex(
            model_name="locationvaluemodifier",
            new_name="locations_l_room_pr_7d79f4_idx",
            old_name="locations_l_room_pr_5b8d04_idx",
        ),
        migrations.RenameIndex(
            model_name="locationvaluemodifier",
            new_name="locations_l_area_id_1b47ea_idx",
            old_name="locations_l_area_id_f5a738_idx",
        ),
        migrations.RenameIndex(
            model_name="locationvaluemodifier",
            new_name="locations_l_room_pr_bbc5b5_idx",
            old_name="locations_l_room_pr_495761_idx",
        ),
        migrations.AlterField(
            model_name="locationvaluemodifier",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Free-text label for the originating system or event. Use to bulk-clean rows when the source ends (e.g. ``LocationValueModifier.objects.filter(source='rebellion_1234').delete()``).",
                max_length=200,
            ),
        ),
    ]
