# Generated by Django 5.2.4 on 2026-04-13 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameClock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anchor_real_time",
                    models.DateTimeField(
                        help_text="Real-world timestamp when the clock was last set."
                    ),
                ),
                (
                    "anchor_ic_time",
                    models.DateTimeField(
                        help_text="IC datetime corresponding to anchor_real_time."
                    ),
                ),
                (
                    "time_ratio",
                    models.FloatField(default=3.0, help_text="IC seconds per real second."),
                ),
                (
                    "paused",
                    models.BooleanField(
                        default=False,
                        help_text="When True, IC time is frozen at anchor_ic_time.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Clock",
                "verbose_name_plural": "Game Clock",
            },
        ),
        migrations.CreateModel(
            name="GameSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ScheduledTaskRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_key",
                    models.CharField(
                        help_text="String identifier for the periodic task.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Real time when this task last completed.",
                        null=True,
                    ),
                ),
                (
                    "last_ic_run_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="IC time of last run (for IC-frequency tasks).",
                        null=True,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, help_text="Staff can disable individual tasks."
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Task",
            },
        ),
        migrations.CreateModel(
            name="GameClockHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, help_text="When the change was made."),
                ),
                ("old_anchor_real_time", models.DateTimeField()),
                ("old_anchor_ic_time", models.DateTimeField()),
                ("old_time_ratio", models.FloatField()),
                ("new_anchor_real_time", models.DateTimeField()),
                ("new_anchor_ic_time", models.DateTimeField()),
                ("new_time_ratio", models.FloatField()),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Account that made the change.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Clock History",
                "verbose_name_plural": "Game Clock History",
            },
        ),
        migrations.CreateModel(
            name="GameWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Week number within its season (resets on new season)"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        help_text="Real-world time when this week began (cron creation time)"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Real-world time when this week ended (next cron run)",
                        null=True,
                    ),
                ),
                ("is_current", models.BooleanField(db_index=True, default=False)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weeks",
                        to="game_clock.gameseason",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("season", "number"), name="unique_week_per_season"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("is_current",),
                        name="unique_current_game_week",
                    ),
                ],
            },
        ),
    ]
