# Generated by Django 5.2.4 on 2026-03-12 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameClock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anchor_real_time",
                    models.DateTimeField(
                        help_text="Real-world timestamp when the clock was last set."
                    ),
                ),
                (
                    "anchor_ic_time",
                    models.DateTimeField(
                        help_text="IC datetime corresponding to anchor_real_time."
                    ),
                ),
                (
                    "time_ratio",
                    models.FloatField(default=3.0, help_text="IC seconds per real second."),
                ),
                (
                    "paused",
                    models.BooleanField(
                        default=False,
                        help_text="When True, IC time is frozen at anchor_ic_time.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Clock",
                "verbose_name_plural": "Game Clock",
            },
        ),
        migrations.CreateModel(
            name="GameClockHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, help_text="When the change was made."),
                ),
                ("old_anchor_real_time", models.DateTimeField()),
                ("old_anchor_ic_time", models.DateTimeField()),
                ("old_time_ratio", models.FloatField()),
                ("new_anchor_real_time", models.DateTimeField()),
                ("new_anchor_ic_time", models.DateTimeField()),
                ("new_time_ratio", models.FloatField()),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Account that made the change.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Clock History",
                "verbose_name_plural": "Game Clock History",
                "ordering": ["-changed_at"],
            },
        ),
    ]
