# Generated by Django 5.2.4 on 2026-02-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminExcludedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Excluded Export Model",
                "verbose_name_plural": "Excluded Export Models",
                "unique_together": {("app_label", "model_name")},
            },
        ),
        migrations.CreateModel(
            name="AdminPinnedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=100)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Pinned Admin Model",
                "verbose_name_plural": "Pinned Admin Models",
                "ordering": ["sort_order", "created_at"],
                "unique_together": {("app_label", "model_name")},
            },
        ),
    ]
