# Generated by Django 5.2.15 on 2026-07-29 21:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

import core.natural_keys


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("scenes", "0058_sceneactionrequest_cast_openly"),
        ("societies", "0035_crisisintel_domaincrisis_org_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EdictKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "income_gross_pct",
                    models.IntegerField(
                        default=0,
                        help_text="Percentage adjustment to domain gross income while active.",
                    ),
                ),
                (
                    "weekly_unrest_delta",
                    models.IntegerField(
                        default=0,
                        help_text="Weekly unrest change applied while this edict is active.",
                    ),
                ),
                (
                    "weekly_upkeep_coppers",
                    models.IntegerField(
                        default=0,
                        help_text="Additional weekly upkeep in coppers while this edict is active.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="StanceArchetype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "mercy_delta",
                    models.IntegerField(
                        default=0,
                        help_text="Compassion (+) ↔ Ruthlessness (-) axis contribution.",
                        validators=[
                            django.core.validators.MinValueValidator(-5),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "method_delta",
                    models.IntegerField(
                        default=0,
                        help_text="Honor (+) ↔ Cunning (-) axis contribution.",
                        validators=[
                            django.core.validators.MinValueValidator(-5),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "status_delta",
                    models.IntegerField(
                        default=0,
                        help_text="Humility (+) ↔ Ambition (-) axis contribution.",
                        validators=[
                            django.core.validators.MinValueValidator(-5),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "change_delta",
                    models.IntegerField(
                        default=0,
                        help_text="Progress (+) ↔ Tradition (-) axis contribution.",
                        validators=[
                            django.core.validators.MinValueValidator(-5),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "allegiance_delta",
                    models.IntegerField(
                        default=0,
                        help_text="Independence (+) ↔ Loyalty (-) axis contribution.",
                        validators=[
                            django.core.validators.MinValueValidator(-5),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "power_delta",
                    models.IntegerField(
                        default=0,
                        help_text="Equality (+) ↔ Hierarchy (-) axis contribution.",
                        validators=[
                            django.core.validators.MinValueValidator(-5),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Proclamation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prose",
                    models.TextField(
                        blank=True,
                        help_text="Player-authored text shown verbatim on the feed, never parsed.",
                    ),
                ),
                (
                    "check_outcome",
                    models.CharField(
                        blank=True,
                        help_text="Stored CheckOutcome name from the issue roll.",
                        max_length=50,
                    ),
                ),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "issuer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proclamations",
                        to="scenes.persona",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: speaking on behalf of this organization.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proclamations",
                        to="societies.organization",
                    ),
                ),
                (
                    "stance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proclamations",
                        to="proclamations.stancearchetype",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="DomainEdict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enacted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edicts",
                        to="societies.domain",
                    ),
                ),
                (
                    "kind",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="domain_edicts",
                        to="proclamations.edictkind",
                    ),
                ),
                (
                    "proclamation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edicts",
                        to="proclamations.proclamation",
                    ),
                ),
            ],
            options={
                "ordering": ["-enacted_at"],
            },
        ),
        migrations.AddField(
            model_name="edictkind",
            name="stance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="edict_kinds",
                to="proclamations.stancearchetype",
            ),
        ),
    ]
