# Generated by Django 5.2.14 on 2026-05-29 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("character_sheets", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="WeeklyJournalXP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("posts_this_week", models.PositiveSmallIntegerField(default=0)),
                ("praised_this_week", models.BooleanField(default=False)),
                ("was_praised_this_week", models.BooleanField(default=False)),
                ("retorted_this_week", models.BooleanField(default=False)),
                ("was_retorted_this_week", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("is_public", models.BooleanField(default=False)),
                (
                    "response_type",
                    models.CharField(
                        blank=True,
                        choices=[("praise", "Praise"), ("retort", "Retort")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ic_timestamp",
                    models.DateTimeField(
                        blank=True,
                        help_text="System-derived IC timestamp. Populated when IC time system exists.",
                        null=True,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to="character_sheets.charactersheet",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responses",
                        to="journals.journalentry",
                    ),
                ),
            ],
        ),
    ]
