# Generated by Django 5.2.4 on 2026-03-11 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("character_sheets", "0003_initial"),
        ("journals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyJournalXP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("posts_this_week", models.PositiveSmallIntegerField(default=0)),
                ("praised_this_week", models.BooleanField(default=False)),
                ("was_praised_this_week", models.BooleanField(default=False)),
                ("retorted_this_week", models.BooleanField(default=False)),
                ("was_retorted_this_week", models.BooleanField(default=False)),
                ("week_reset_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character_sheet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_journal_xp",
                        to="character_sheets.charactersheet",
                    ),
                ),
            ],
        ),
    ]
