# Generated by Django 5.2.4 on 2026-04-13 00:59

from django.db import migrations


def populate_character_sheet(apps, schema_editor):
    RosterEntry = apps.get_model("roster", "RosterEntry")
    CharacterSheet = apps.get_model("character_sheets", "CharacterSheet")
    sheet_ids = set(CharacterSheet.objects.values_list("pk", flat=True))
    for entry in RosterEntry.objects.filter(character_sheet__isnull=True).iterator():
        if entry.character_id in sheet_ids:
            entry.character_sheet_id = entry.character_id
            entry.save(update_fields=["character_sheet_id"])


def unpopulate_character_sheet(apps, schema_editor):
    RosterEntry = apps.get_model("roster", "RosterEntry")
    RosterEntry.objects.update(character_sheet=None)


class Migration(migrations.Migration):
    dependencies = [
        ("roster", "0002_rosterentry_character_sheet"),
    ]

    operations = [
        migrations.RunPython(
            populate_character_sheet,
            reverse_code=unpopulate_character_sheet,
        ),
    ]
