# Generated by Django 5.2.14 on 2026-06-28 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gm", "0003_initial"),
        ("roster", "0004_tenuredisplaysettings_appear_offline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rosterentry",
            name="created_by_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Account that authored this character (the GM, the staffer, or the player).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authored_roster_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rosterentry",
            name="created_for_table",
            field=models.ForeignKey(
                blank=True,
                help_text="For GM_TABLE provenance: the GM table this character was created for.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authored_roster_entries",
                to="gm.gmtable",
            ),
        ),
        migrations.AddField(
            model_name="rosterentry",
            name="creation_provenance",
            field=models.CharField(
                choices=[
                    ("staff", "Staff-created"),
                    ("gm_table", "GM-created (for a table)"),
                    ("player", "Player-created"),
                ],
                default="player",
                help_text="Who authored this character — a display-only quality/trust signal.",
                max_length=16,
            ),
        ),
    ]
