# Generated by Django 5.2.15 on 2026-07-18 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("evennia_extensions", "0010_roomprofile_fixture_key_roomprofile_origin"),
        ("roster", "0007_alter_rosterapplication_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="URL-safe random token (secrets.token_urlsafe(48))",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="The inviter's contextual note to the friend (why they're invited)."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("claimed", "Claimed"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional expiry; null = no expiry.",
                        null=True,
                    ),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when the invitee claims the token (first login).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invites",
                        to="evennia_extensions.playerdata",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Account that revoked this invite (inviter or staff).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Game Invite",
                "verbose_name_plural": "Game Invites",
                "ordering": ["-created_at"],
            },
        ),
    ]
