# Generated by Django 5.2.15 on 2026-07-27 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0014_speciesformtrait_is_required_and_more"),
        ("roster", "0013_remove_roster_activity_requirement_and_more"),
        ("secrets", "0011_accusationrebuttal"),
        ("species", "0006_species_decline_start_age_species_eternal_youth"),
    ]

    operations = [
        migrations.CreateModel(
            name="KinspersonTraitValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.AddField(
            model_name="kinsperson",
            name="power_band",
            field=models.CharField(
                blank=True,
                choices=[
                    ("quiescent", "Quiescent"),
                    ("prospect", "Prospect"),
                    ("potential", "Potential"),
                    ("puissant", "Puissant"),
                    ("true", "True"),
                    ("grand", "Grand"),
                    ("transcendent", "Transcendent"),
                ],
                help_text="Staff/GM-authored only; null = unspecified (assumed sub-Puissant). Drives Parent Dominance: species flips and chimeric children require bands that support them at creation time.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="kinsperson",
            name="species",
            field=models.ForeignKey(
                blank=True,
                help_text="Null = undeclared. CG approval back-inference pins the dominant-line parent to the child's species; staff author it directly.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="kinspeople",
                to="species.species",
            ),
        ),
        migrations.AddField(
            model_name="parentageedge",
            name="is_ritual_invoker",
            field=models.BooleanField(
                default=False,
                help_text="TREE_OF_SOULS only: this parent invoked the ritual and is the dominant line regardless of gender (#2815).",
            ),
        ),
        migrations.AddConstraint(
            model_name="parentageedge",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_ritual_invoker", True)),
                fields=("child",),
                name="roster_parentage_one_invoker_per_child",
            ),
        ),
        migrations.AddField(
            model_name="kinspersontraitvalue",
            name="kinsperson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trait_values",
                to="roster.kinsperson",
            ),
        ),
        migrations.AddField(
            model_name="kinspersontraitvalue",
            name="option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kinsperson_values",
                to="forms.formtraitoption",
            ),
        ),
        migrations.AddField(
            model_name="kinspersontraitvalue",
            name="trait",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kinsperson_values",
                to="forms.formtrait",
            ),
        ),
        migrations.AddConstraint(
            model_name="kinspersontraitvalue",
            constraint=models.UniqueConstraint(
                fields=("kinsperson", "trait"), name="roster_kinsperson_trait_unique"
            ),
        ),
    ]
