# Generated by Django 5.2.15 on 2026-08-01 06:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("roster", "0014_kinspersontraitvalue_kinsperson_power_band_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rostertenure",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Roster Tenure",
                "verbose_name_plural": "Roster Tenures",
            },
        ),
    ]
