# Generated by Django 5.2.14 on 2026-07-03 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("character_sheets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Covenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "covenant_type",
                    models.CharField(
                        choices=[
                            ("durance", "Covenant of the Durance"),
                            ("battle", "Covenant of Battle"),
                            ("court", "Covenant of the Court"),
                        ],
                        default="durance",
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Group progression tier (Slice D will drive growth).",
                    ),
                ),
                (
                    "sworn_objective",
                    models.TextField(help_text="Free text in Slice A; structured in Slice C."),
                ),
                ("formed_at", models.DateTimeField(auto_now_add=True)),
                ("dissolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "battle_binding",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("standing", "Standing (unit or banner — can rise again)"),
                            (
                                "campaign",
                                "Campaign (one-time event — dissolves when done)",
                            ),
                        ],
                        default="",
                        help_text="Battle covenants only (Slice E). STANDING can rise again; CAMPAIGN dissolves when its objective concludes. Empty for DURANCE covenants.",
                        max_length=20,
                    ),
                ),
                (
                    "is_dormant",
                    models.BooleanField(
                        default=False,
                        help_text="Battle covenants only: True when a STANDING covenant has stood down and awaits a 'call the banners' rise ritual. A dormant covenant cannot be engaged. Never True for DURANCE or CAMPAIGN covenants.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CovenantLevelBonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus_per_level",
                    models.SmallIntegerField(
                        help_text="Per-level coefficient. Final bonus for an engaged member = covenant.level * bonus_per_level, summed across engaged covenants."
                    ),
                ),
            ],
            options={
                "ordering": ["modifier_target"],
            },
        ),
        migrations.CreateModel(
            name="CovenantLevelThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.PositiveIntegerField(unique=True)),
                ("required_legend", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="CovenantRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Player-chosen tier name, e.g. 'Magister'.",
                        max_length=60,
                    ),
                ),
                (
                    "tier",
                    models.PositiveIntegerField(
                        help_text="Precedence; lower = higher authority (1 = top)."
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional flavor/ceremony text."),
                ),
                ("can_invite", models.BooleanField(default=False)),
                (
                    "can_kick",
                    models.BooleanField(
                        default=False,
                        help_text="May remove members of a strictly lower tier.",
                    ),
                ),
                (
                    "can_manage_ranks",
                    models.BooleanField(
                        default=False,
                        help_text="May edit the ladder and assign members.",
                    ),
                ),
            ],
            options={
                "ordering": ["covenant", "tier"],
            },
        ),
        migrations.CreateModel(
            name="CovenantRite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "covenant_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("durance", "Covenant of the Durance"),
                            ("battle", "Covenant of Battle"),
                            ("court", "Covenant of the Court"),
                        ],
                        help_text="Restrict to this covenant type; blank = any.",
                        max_length=32,
                    ),
                ),
                ("min_covenant_level", models.PositiveSmallIntegerField(default=1)),
                ("min_members_present", models.PositiveSmallIntegerField(default=2)),
                ("base_severity", models.PositiveSmallIntegerField(default=1)),
                (
                    "severity_per_extra_participant",
                    models.PositiveSmallIntegerField(default=0),
                ),
                (
                    "max_severity",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "duration_rounds",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Override; blank uses the condition's UNTIL_END_OF_COMBAT default.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Covenant Rite",
                "verbose_name_plural": "Covenant Rites",
            },
        ),
        migrations.CreateModel(
            name="CovenantRiteInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fired_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CovenantRiteParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CovenantRiteRolePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_covenant_level", models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="CovenantRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unlock_thread_level",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 = base/parent; >=3 = variant (thread level needed to unlock).",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Display name, e.g. 'Vanguard'.", max_length=60),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Stable identifier for code references, e.g. 'vanguard'.",
                        max_length=60,
                        unique=True,
                    ),
                ),
                (
                    "covenant_type",
                    models.CharField(
                        choices=[
                            ("durance", "Covenant of the Durance"),
                            ("battle", "Covenant of Battle"),
                            ("court", "Covenant of the Court"),
                        ],
                        default="durance",
                        help_text="Which covenant type this role belongs to.",
                        max_length=20,
                    ),
                ),
                (
                    "archetype",
                    models.CharField(
                        choices=[
                            ("sword", "Sword"),
                            ("shield", "Shield"),
                            ("crown", "Crown"),
                        ],
                        help_text="Foundational archetype: Sword (offense), Shield (defense), Crown (support).",
                        max_length=20,
                    ),
                ),
                (
                    "speed_rank",
                    models.PositiveIntegerField(
                        help_text="Combat resolution order. Lower is faster (1 = fastest)."
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Player-facing description of the role's identity and combat style.",
                    ),
                ),
                (
                    "command_tier",
                    models.CharField(
                        choices=[
                            ("none", "No command tier"),
                            ("subordinate", "Subordinate Commander"),
                            ("supreme", "Supreme Commander"),
                        ],
                        default="none",
                        help_text="Battle-command hierarchy tier (#1710). Only settable on CovenantType.BATTLE roles — see clean().",
                        max_length=20,
                    ),
                ),
                (
                    "is_champion_role",
                    models.BooleanField(
                        default=False,
                        help_text="True if holding this role lets a character issue/answer a single-combat duel for the covenant (#1710). Only settable on CovenantType.BATTLE roles.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CovenantRoleBonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus_per_level",
                    models.SmallIntegerField(
                        help_text="Per-level coefficient. Bonus for an engaged role holder = character_level * bonus_per_level."
                    ),
                ),
            ],
            options={
                "ordering": ["covenant_role", "modifier_target"],
            },
        ),
        migrations.CreateModel(
            name="GearArchetypeCompatibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gear_archetype",
                    models.CharField(
                        choices=[
                            ("light_armor", "Light Armor"),
                            ("medium_armor", "Medium Armor"),
                            ("heavy_armor", "Heavy Armor"),
                            ("robe", "Robe"),
                            ("melee_one_hand", "One-Handed Melee"),
                            ("melee_two_hand", "Two-Handed Melee"),
                            ("ranged", "Ranged"),
                            ("thrown", "Thrown"),
                            ("shield", "Shield"),
                            ("jewelry", "Jewelry"),
                            ("clothing", "Clothing"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MentorBond",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "adjusted_party",
                    models.CharField(
                        choices=[("mentor", "Mentor"), ("sidekick", "Sidekick")],
                        default="sidekick",
                        help_text="Which party the encounter-scaling adjustment is applied to.",
                        max_length=20,
                    ),
                ),
                ("formed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dissolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the bond is dissolved; null means currently active.",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-formed_at"],
            },
        ),
        migrations.CreateModel(
            name="MentorBondConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "band_width",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="Level-range half-width for eligible mentor/sidekick pairs.",
                    ),
                ),
                (
                    "adjacency_offset",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Additional level offset applied when computing adjacency.",
                    ),
                ),
                (
                    "max_sidekicks_per_mentor",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=None,
                        help_text="Cap on sidekick count per mentor; null means unlimited.",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="CharacterCovenantRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "engaged",
                    models.BooleanField(
                        default=False,
                        help_text="True when the character is currently 'fulfilling' this role for this covenant. At most one engaged active row per (character_sheet, covenant.covenant_type) — service-enforced + clean()-enforced. Drives role bonuses (modifier pipeline) and COVENANT_ROLE Thread pull eligibility. See spec 2026-05-09 §3.6.",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="covenant_role_assignments",
                        to="character_sheets.charactersheet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourtPact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "granted_pull_cap",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Master-set ceiling on the servant's Court-role thread level.",
                    ),
                ),
                ("sworn_at", models.DateTimeField(auto_now_add=True)),
                (
                    "released_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the pact is released; null means currently active.",
                        null=True,
                    ),
                ),
                (
                    "servant_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="court_pacts",
                        to="character_sheets.charactersheet",
                    ),
                ),
            ],
            options={
                "ordering": ["covenant", "servant_sheet"],
            },
        ),
    ]
