# Generated by Django 5.2.14 on 2026-07-03 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("achievements", "0004_initial"),
        ("character_sheets", "0002_initial"),
        ("codex", "0004_initial"),
        ("combat", "0003_initial"),
        ("conditions", "0004_initial"),
        ("covenants", "0001_initial"),
        ("magic", "0003_initial"),
        ("mechanics", "0002_initial"),
        ("scenes", "0002_initial"),
        ("societies", "0001_initial"),
        ("stories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="covenant",
            name="campaign_story",
            field=models.ForeignKey(
                blank=True,
                help_text="CAMPAIGN battle covenants only: the defining story whose completion dissolves this campaign. SET_NULL so deleting the story does not cascade-delete the covenant. Empty for STANDING/DURANCE covenants.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ended_campaigns",
                to="stories.story",
            ),
        ),
        migrations.AddField(
            model_name="covenant",
            name="leader",
            field=models.ForeignKey(
                blank=True,
                help_text="Court covenants only: the puissant this Court is sworn to. Empty for other types.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="led_courts",
                to="character_sheets.charactersheet",
            ),
        ),
        migrations.AddField(
            model_name="covenant",
            name="organization",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="covenant",
                to="societies.organization",
            ),
        ),
        migrations.AddField(
            model_name="courtpact",
            name="covenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="court_pacts",
                to="covenants.covenant",
            ),
        ),
        migrations.AddField(
            model_name="charactercovenantrole",
            name="covenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="covenants.covenant",
            ),
        ),
        migrations.AddField(
            model_name="covenantlevelbonus",
            name="modifier_target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="covenant_level_bonuses",
                to="mechanics.modifiertarget",
            ),
        ),
        migrations.AddConstraint(
            model_name="covenantlevelthreshold",
            constraint=models.CheckConstraint(
                condition=models.Q(("level__gte", 1)),
                name="covenant_level_threshold_level_gte_1",
            ),
        ),
        migrations.AddField(
            model_name="covenantrank",
            name="covenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ranks",
                to="covenants.covenant",
            ),
        ),
        migrations.AddField(
            model_name="charactercovenantrole",
            name="rank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="covenants.covenantrank",
            ),
        ),
        migrations.AddField(
            model_name="covenantrite",
            name="granted_condition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="conditions.conditiontemplate",
            ),
        ),
        migrations.AddField(
            model_name="covenantrite",
            name="ritual",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="covenant_rite",
                to="magic.ritual",
            ),
        ),
        migrations.AddField(
            model_name="covenantriteinstance",
            name="combat_encounter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="covenant_rite_instances",
                to="combat.combatencounter",
            ),
        ),
        migrations.AddField(
            model_name="covenantriteinstance",
            name="covenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rite_instances",
                to="covenants.covenant",
            ),
        ),
        migrations.AddField(
            model_name="covenantriteinstance",
            name="rite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="instances",
                to="covenants.covenantrite",
            ),
        ),
        migrations.AddField(
            model_name="covenantriteinstance",
            name="scene",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="covenant_rite_instances",
                to="scenes.scene",
            ),
        ),
        migrations.AddField(
            model_name="covenantriteparticipant",
            name="character_sheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="character_sheets.charactersheet",
            ),
        ),
        migrations.AddField(
            model_name="covenantriteparticipant",
            name="granted_condition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="conditions.conditiontemplate",
            ),
        ),
        migrations.AddField(
            model_name="covenantriteparticipant",
            name="instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participant_records",
                to="covenants.covenantriteinstance",
            ),
        ),
        migrations.AddField(
            model_name="covenantriteinstance",
            name="participants",
            field=models.ManyToManyField(
                related_name="covenant_rite_instances",
                through="covenants.CovenantRiteParticipant",
                to="character_sheets.charactersheet",
            ),
        ),
        migrations.AddField(
            model_name="covenantriterolepackage",
            name="condition_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="conditions.conditiontemplate",
            ),
        ),
        migrations.AddField(
            model_name="covenantriterolepackage",
            name="rite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_packages",
                to="covenants.covenantrite",
            ),
        ),
        migrations.AddField(
            model_name="covenantrole",
            name="codex_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="Variant only: lore entry unlocked on manifestation.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="codex.codexentry",
            ),
        ),
        migrations.AddField(
            model_name="covenantrole",
            name="discovery_achievement",
            field=models.ForeignKey(
                blank=True,
                help_text="Variant only: achievement granted (+ global-first Discovery) on manifestation.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="achievements.achievement",
            ),
        ),
        migrations.AddField(
            model_name="covenantrole",
            name="parent_role",
            field=models.ForeignKey(
                blank=True,
                help_text="Null for primary roles. Set for sub-roles.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sub_roles",
                to="covenants.covenantrole",
            ),
        ),
        migrations.AddField(
            model_name="covenantrole",
            name="resonance",
            field=models.ForeignKey(
                blank=True,
                help_text="Null for the base/parent row; set for variants.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_subrole",
                to="magic.resonance",
            ),
        ),
        migrations.AddField(
            model_name="covenantriterolepackage",
            name="covenant_role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="covenants.covenantrole",
            ),
        ),
        migrations.AddField(
            model_name="charactercovenantrole",
            name="covenant_role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="character_assignments",
                to="covenants.covenantrole",
            ),
        ),
        migrations.AddField(
            model_name="covenantrolebonus",
            name="covenant_role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_bonuses",
                to="covenants.covenantrole",
            ),
        ),
        migrations.AddField(
            model_name="covenantrolebonus",
            name="modifier_target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="covenant_role_bonuses",
                to="mechanics.modifiertarget",
            ),
        ),
        migrations.AddField(
            model_name="geararchetypecompatibility",
            name="covenant_role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gear_compatibilities",
                to="covenants.covenantrole",
            ),
        ),
        migrations.AddField(
            model_name="mentorbond",
            name="covenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentor_bonds",
                to="covenants.covenant",
            ),
        ),
        migrations.AddField(
            model_name="mentorbond",
            name="mentor_sheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentor_bonds_as_mentor",
                to="character_sheets.charactersheet",
            ),
        ),
        migrations.AddField(
            model_name="mentorbond",
            name="sidekick_sheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentor_bonds_as_sidekick",
                to="character_sheets.charactersheet",
            ),
        ),
        migrations.AddField(
            model_name="mentorbondconfig",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mentor_bond_config_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="courtpact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("released_at__isnull", True)),
                fields=("covenant", "servant_sheet"),
                name="uniq_court_pact_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="covenantlevelbonus",
            constraint=models.UniqueConstraint(
                fields=("modifier_target",), name="covenant_level_bonus_unique_target"
            ),
        ),
        migrations.AddConstraint(
            model_name="covenantrank",
            constraint=models.UniqueConstraint(
                fields=("covenant", "tier"),
                name="covenants_unique_rank_tier_per_covenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="covenantrank",
            constraint=models.UniqueConstraint(
                fields=("covenant", "name"),
                name="covenants_unique_rank_name_per_covenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="covenantriteparticipant",
            constraint=models.UniqueConstraint(
                fields=("instance", "character_sheet"),
                name="covenant_rite_participant_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="covenantrole",
            constraint=models.UniqueConstraint(
                fields=("covenant_type", "name"),
                name="unique_role_name_per_covenant_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="covenantrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent_role__isnull", False)),
                fields=("parent_role", "resonance", "unlock_thread_level"),
                name="covenant_subrole_unique_per_parent_resonance_level",
            ),
        ),
        migrations.AddConstraint(
            model_name="covenantriterolepackage",
            constraint=models.UniqueConstraint(
                fields=("rite", "covenant_role", "min_covenant_level"),
                name="covenant_rite_role_package_unique_band",
            ),
        ),
        migrations.AddConstraint(
            model_name="charactercovenantrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("left_at__isnull", True)),
                fields=("character_sheet", "covenant"),
                name="covenants_one_active_role_per_covenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="covenantrolebonus",
            constraint=models.UniqueConstraint(
                fields=("covenant_role", "modifier_target"),
                name="covenant_role_bonus_unique_role_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="geararchetypecompatibility",
            constraint=models.UniqueConstraint(
                fields=("covenant_role", "gear_archetype"),
                name="covenants_unique_role_archetype_compat",
            ),
        ),
        migrations.AddConstraint(
            model_name="mentorbond",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dissolved_at__isnull", True)),
                fields=("covenant", "sidekick_sheet"),
                name="unique_active_sidekick_bond",
            ),
        ),
    ]
