# Generated by Django 5.2.4 on 2026-04-28 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("covenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GearArchetypeCompatibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gear_archetype",
                    models.CharField(
                        choices=[
                            ("light_armor", "Light Armor"),
                            ("medium_armor", "Medium Armor"),
                            ("heavy_armor", "Heavy Armor"),
                            ("robe", "Robe"),
                            ("melee_one_hand", "One-Handed Melee"),
                            ("melee_two_hand", "Two-Handed Melee"),
                            ("ranged", "Ranged"),
                            ("thrown", "Thrown"),
                            ("shield", "Shield"),
                            ("jewelry", "Jewelry"),
                            ("clothing", "Clothing"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "covenant_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gear_compatibilities",
                        to="covenants.covenantrole",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("covenant_role", "gear_archetype"),
                        name="covenants_unique_role_archetype_compat",
                    )
                ],
            },
        ),
    ]
