# Generated by Django 5.2.4, hand-edited to wipe existing rows and make covenant non-null.

from django.db import migrations, models
import django.db.models.deletion


def wipe_charactercovenantrole(apps, schema_editor):
    """Wipe all rows. Local dev DB is disposable; pre-MVP factory-driven."""
    CharacterCovenantRole = apps.get_model("covenants", "CharacterCovenantRole")
    CharacterCovenantRole.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("character_sheets", "0004_charactersheet_current_residence"),
        ("covenants", "0004_covenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="charactercovenantrole",
            name="covenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="covenants.covenant",
            ),
        ),
        migrations.AddField(
            model_name="charactercovenantrole",
            name="engaged",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "True when the character is currently 'fulfilling' this role for this "
                    "covenant. At most one engaged active row per (character_sheet, "
                    "covenant.covenant_type) — service-enforced + clean()-enforced. "
                    "Drives role bonuses (modifier pipeline) and COVENANT_ROLE Thread pull "
                    "eligibility. See spec 2026-05-09 §3.6."
                ),
            ),
        ),
        migrations.RunPython(wipe_charactercovenantrole, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="charactercovenantrole",
            name="covenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="memberships",
                to="covenants.covenant",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="charactercovenantrole",
            name="covenants_one_active_role_assignment",
        ),
        migrations.AddConstraint(
            model_name="charactercovenantrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(left_at__isnull=True),
                fields=("character_sheet", "covenant"),
                name="covenants_one_active_role_per_covenant",
            ),
        ),
    ]
