# Generated by Django 5.2.14 on 2026-06-08 05:56 — hand-edited to avoid AlterField on M2M
# Django forbids AlterField to add/remove through= on ManyToManyField on Postgres.
# Correct fix: RemoveField (bare M2M) → CreateModel (through table) → AddField (M2M with through).

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("character_sheets", "0005_charactersheet_max_active_npc_missions"),
        ("conditions", "0007_conditioncapabilityeffect_scales_with_severity_and_more"),
        ("covenants", "0007_covenantriterolepackage"),
    ]

    operations = [
        # 1. Drop the old bare M2M first (no through table).
        migrations.RemoveField(
            model_name="covenantriteinstance",
            name="participants",
        ),
        # 2. Create the through model CovenantRiteParticipant.
        migrations.CreateModel(
            name="CovenantRiteParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="character_sheets.charactersheet",
                    ),
                ),
                (
                    "granted_condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="conditions.conditiontemplate",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_records",
                        to="covenants.covenantriteinstance",
                    ),
                ),
            ],
        ),
        # 3. Re-add the M2M WITH the through= argument.
        migrations.AddField(
            model_name="covenantriteinstance",
            name="participants",
            field=models.ManyToManyField(
                related_name="covenant_rite_instances",
                through="covenants.CovenantRiteParticipant",
                to="character_sheets.charactersheet",
            ),
        ),
        # 4. Add the uniqueness constraint on the through table.
        migrations.AddConstraint(
            model_name="covenantriteparticipant",
            constraint=models.UniqueConstraint(
                fields=("instance", "character_sheet"),
                name="covenant_rite_participant_unique",
            ),
        ),
    ]
