# Generated by Django 5.2.14 on 2026-06-29 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0004_rewarddefinition_modifier_target_and_more"),
        ("covenants", "0016_covenantrole_codex_entry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="covenantrole",
            name="discovery_achievement",
            field=models.ForeignKey(
                blank=True,
                help_text="Achievement granted (with global-first Discovery) the first time a character gains this content. Null = not discoverable.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="achievements.achievement",
            ),
        ),
    ]
