# Generated by Django 5.2.14 on 2026-07-09 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("conditions", "0014_alter_conditiondamageovertime_tick_timing"),
        ("covenants", "0023_courtgrantconfig_summons_refusal_escalation_pool_and_more"),
        ("magic", "0093_traitcrossingoption_traitcrossingchoice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="covenantrole",
            name="granted_capabilities",
            field=models.ManyToManyField(
                blank=True,
                help_text="#2022: Capabilities granted by this role while engaged. Written to the character's capability ledger on engage; revoked on disengage.",
                related_name="granted_by_roles",
                to="conditions.capabilitytype",
            ),
        ),
        migrations.CreateModel(
            name="CovenantRoleGiftGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unlock_thread_level",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The COVENANT_ROLE thread level at which this gift's techniques become available while engaged. 0 = always available.",
                    ),
                ),
                (
                    "covenant_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gift_grants",
                        to="covenants.covenantrole",
                    ),
                ),
                (
                    "gift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_grants",
                        to="magic.gift",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="covenantrole",
            name="granted_gifts",
            field=models.ManyToManyField(
                blank=True,
                help_text="#2022: Gifts granted by this role while engaged. The role's gift techniques are auto-granted on engage and auto-revoked on disengage (the #2051 vow-dim path). Techniques are primarily enhancements that boost overlapping techniques from the character's existing gifts.",
                related_name="granted_by_roles",
                through="covenants.CovenantRoleGiftGrant",
                to="magic.gift",
            ),
        ),
        migrations.AddConstraint(
            model_name="covenantrolegiftgrant",
            constraint=models.UniqueConstraint(
                fields=("covenant_role", "gift"), name="covenant_role_gift_grant_unique"
            ),
        ),
    ]
