# Generated by Django 5.2.15 on 2026-07-20 03:18

from django.db import migrations, models
import django.db.models.deletion

import core.natural_keys


class Migration(migrations.Migration):
    dependencies = [
        ("covenants", "0030_covenantroletechniquespecialty"),
    ]

    operations = [
        migrations.CreateModel(
            name="CovenantRoleDefenseProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("gear_soak", "Gear Soak"),
                            ("evasion", "Evasion"),
                            ("barrier", "Barrier"),
                        ],
                        help_text="How this role's vow defends (#2533).",
                        max_length=20,
                    ),
                ),
                (
                    "gear_additive_tenths",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Fraction of COMPATIBLE armor soak that stays additive with the vow's own defense; 10 = fully additive (legacy behavior).",
                    ),
                ),
                (
                    "covenant_role",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defense_profile",
                        to="covenants.covenantrole",
                    ),
                ),
            ],
            options={
                "ordering": ["covenant_role__slug"],
            },
            bases=(core.natural_keys.NaturalKeyMixin, models.Model),
        ),
    ]
