# Generated by Django 5.2.15 on 2026-07-21 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("covenants", "0034_vowsituationalperk_floor_success_level"),
        ("missions", "0035_alter_missionoptionroutereward_sequence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vowsituationalperk",
            name="battle_action_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("strike", "Strike a unit"),
                    ("support", "Support an ally"),
                    ("rescue", "Rescue a surrounded ally"),
                    ("rout", "Rout an enemy unit"),
                    ("rally", "Rally an ally"),
                    ("repel", "Repel an attack"),
                    ("hold", "Hold or seize an objective"),
                    ("breach", "Breach a fortification"),
                    ("fortify", "Fortify a structure"),
                    ("set_environment", "Set battlefield weather"),
                    ("reposition", "Reposition a vehicle"),
                    ("move", "Move to a front"),
                ],
                default="",
                help_text="CHECK_BONUS/POWER_BONUS scope: fires only on this declared warfare action kind.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vowsituationalperk",
            name="mission_category",
            field=models.ForeignKey(
                blank=True,
                help_text="CHECK_BONUS scope: fires only on a mission whose template carries this category.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="situational_perks",
                to="missions.missioncategory",
            ),
        ),
        migrations.AddField(
            model_name="vowsituationalperk",
            name="mission_template",
            field=models.ForeignKey(
                blank=True,
                help_text="CHECK_BONUS scope: fires only on a check driven by this specific mission.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="situational_perks",
                to="missions.missiontemplate",
            ),
        ),
    ]
