# Generated by Django 5.2.15 on 2026-07-21 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("covenants", "0039_alter_vowsituationalperkrung_extra_situation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vowsituationalperkrung",
            name="affinity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("celestial", "Celestial"),
                    ("primal", "Primal"),
                    ("abyssal", "Abyssal"),
                ],
                default="",
                help_text="Affinity axis for attacker typing (ATTACKER_AFFINITY).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vowsituationalperkrung",
            name="count_threshold",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Count-shaped floor: surrounded lock count, minimum affection.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vowsituationalperkrung",
            name="origin_side",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ours", "Our Side Sprang It"),
                    ("theirs", "Their Side Sprang It"),
                ],
                default="",
                help_text="Directed combat-origin side; blank = side-blind.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="vowsituationalperkrung",
            name="threshold_percent",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Percent-shaped floor (0-100): aura-axis floor, ally-health fraction.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AddField(
            model_name="vowsituationalperksituation",
            name="affinity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("celestial", "Celestial"),
                    ("primal", "Primal"),
                    ("abyssal", "Abyssal"),
                ],
                default="",
                help_text="Affinity axis for attacker typing (ATTACKER_AFFINITY).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vowsituationalperksituation",
            name="count_threshold",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Count-shaped floor: surrounded lock count, minimum affection.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vowsituationalperksituation",
            name="origin_side",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ours", "Our Side Sprang It"),
                    ("theirs", "Their Side Sprang It"),
                ],
                default="",
                help_text="Directed combat-origin side; blank = side-blind.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="vowsituationalperksituation",
            name="threshold_percent",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Percent-shaped floor (0-100): aura-axis floor, ally-health fraction.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AlterField(
            model_name="vowsituationalperkrung",
            name="extra_situation",
            field=models.CharField(
                choices=[
                    ("at_range", "At Range"),
                    ("in_melee", "In Melee"),
                    ("surrounded", "Surrounded"),
                    ("target_distracted", "Target Distracted"),
                    ("target_swayed_by_ally", "Target Swayed by Ally"),
                    ("target_focused_elsewhere", "Target Focused Elsewhere"),
                    ("ally_low_health", "Ally Low Health"),
                    ("during_negotiation", "During Negotiation"),
                    ("target_favorably_disposed", "Target Favorably Disposed"),
                    ("champion_duel", "Champion Duel"),
                    ("combat_opened_from_parley", "Combat Opened From Parley"),
                    ("ambush_underway", "Ambush Underway"),
                    ("ally_intercepted_for_me", "Ally Intercepted for Me"),
                    ("attacker_affinity", "Attacker Affinity"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="vowsituationalperksituation",
            name="situation",
            field=models.CharField(
                choices=[
                    ("at_range", "At Range"),
                    ("in_melee", "In Melee"),
                    ("surrounded", "Surrounded"),
                    ("target_distracted", "Target Distracted"),
                    ("target_swayed_by_ally", "Target Swayed by Ally"),
                    ("target_focused_elsewhere", "Target Focused Elsewhere"),
                    ("ally_low_health", "Ally Low Health"),
                    ("during_negotiation", "During Negotiation"),
                    ("target_favorably_disposed", "Target Favorably Disposed"),
                    ("champion_duel", "Champion Duel"),
                    ("combat_opened_from_parley", "Combat Opened From Parley"),
                    ("ambush_underway", "Ambush Underway"),
                    ("ally_intercepted_for_me", "Ally Intercepted for Me"),
                    ("attacker_affinity", "Attacker Affinity"),
                ],
                max_length=32,
            ),
        ),
    ]
