# Generated by Django 5.2.15 on 2026-07-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("covenants", "0047_alter_vowsituationalperkrung_extra_situation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="covenantroletechniquespecialty",
            name="function",
            field=models.CharField(
                choices=[
                    ("damage_buff_self", "Self Damage Buff"),
                    ("damage_buff_ally", "Ally Damage Buff"),
                    ("defense_buff", "Defense Buff"),
                    ("barrier", "Barrier"),
                    ("cleanse", "Cleanse"),
                    ("mobility", "Mobility"),
                    ("charm", "Charm"),
                    ("distraction", "Distraction"),
                    ("fear", "Fear"),
                    ("weaken", "Weaken"),
                    ("perception", "Perception"),
                    ("concealment", "Concealment"),
                    ("hold", "Hold / Lock"),
                ],
                max_length=32,
            ),
        ),
    ]
