# Generated by Django 5.2.14 on 2026-07-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companions", "0002_companion"),
    ]

    operations = [
        migrations.AddField(
            model_name="companionarchetype",
            name="max_health",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Max health when bridged into a CombatOpponent (manual mode).",
            ),
        ),
        migrations.AddField(
            model_name="companionarchetype",
            name="soak_value",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Damage mitigation when bridged into a CombatOpponent.",
            ),
        ),
        migrations.AddField(
            model_name="companionarchetype",
            name="strength",
            field=models.PositiveSmallIntegerField(
                default=5, help_text="Unit strength when bridged into a BattleVehicle."
            ),
        ),
        migrations.AddField(
            model_name="companionarchetype",
            name="tier",
            field=models.CharField(
                choices=[
                    ("swarm", "Swarm"),
                    ("mook", "Mook"),
                    ("elite", "Elite"),
                    ("boss", "Boss"),
                    ("hero_killer", "Hero Killer"),
                ],
                default="mook",
                help_text="Opponent tier when bridged into a CombatOpponent.",
                max_length=20,
            ),
        ),
    ]
